### ISSUE TITLE
android app problems

### ISSUE THREAD

**Issue by treakiandroid** [badaix/snapcast#100]
Hi,

i have the android app from fdroid and following problems:

it dosnt seams to work if only the port 1704 is forwarded in the firewall but i dont want to give out the controll possibility, it should only stream to my android.

i was unable to connect to a server using ipv6, i have tryed notation direct and in []. first of all the fext field dosent show the end of the text if you enter such a long text then an ipv6 address and secundly there is no connection comming

hope that can be fixed

**Comment by badaix** [comment]
I would recommend to not expose any Snapserver port to the internet.
Use it rather in you LAN only.

**Comment by genofire** [comment]
I really like it to use it with my IPv6 ULA setup between buildings. (Not over internet)
