### ISSUE TITLE
CMake installs server config in wrong place

### ISSUE THREAD

**Issue by janbaudisch** [badaix/snapcast#1003]
I am trying to get snapcast into Fedora. For the rpm I am using CMake and so far everything is working, except for the server config file. It gets installed in `/usr/etc/snapserver.conf`, while it should be `/etc/snapserver.conf`. I am not sure why this happens. Here is the relevant part of the CMake log:

```
-- Install configuration: ""
-- Installing: /builddir/build/BUILDROOT/snapcast-0.26.0-1.fc37.x86_64/usr/bin/snapserver
-- Installing: /builddir/build/BUILDROOT/snapcast-0.26.0-1.fc37.x86_64/usr/share/man/man1/snapserver.1
-- Installing: /builddir/build/BUILDROOT/snapcast-0.26.0-1.fc37.x86_64/usr/etc/snapserver.conf
-- Installing: /builddir/build/BUILDROOT/snapcast-0.26.0-1.fc37.x86_64/usr/bin/snapclient
-- Installing: /builddir/build/BUILDROOT/snapcast-0.26.0-1.fc37.x86_64/usr/share/man/man1/snapclient.1
```

I don't see where this mixup comes from. The rpm actions in the SnapOS repo seem to produce the same result.
Here are the Fedora CMake flags:

```
  /usr/bin/cmake \
        -S "." \
        -B "x86_64-redhat-linux-gnu" \
        -DCMAKE_C_FLAGS_RELEASE:STRING="-DNDEBUG" \
        -DCMAKE_CXX_FLAGS_RELEASE:STRING="-DNDEBUG" \
        -DCMAKE_Fortran_FLAGS_RELEASE:STRING="-DNDEBUG" \
        -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON \
        -DCMAKE_INSTALL_DO_STRIP:BOOL=OFF \
        -DCMAKE_INSTALL_PREFIX:PATH=/usr \
        -DINCLUDE_INSTALL_DIR:PATH=/usr/include \
        -DLIB_INSTALL_DIR:PATH=/usr/lib64 \
        -DSYSCONF_INSTALL_DIR:PATH=/etc \
        -DSHARE_INSTALL_PREFIX:PATH=/usr/share \
        -DBUILD_SHARED_LIBS:BOOL=ON
```

**Steps to Reproduce**
- Sources for the rpm: https://git.sr.ht/~janbaudisch/copr-snapcast
- COPR repo with a failed build: https://copr.fedorainfracloud.org/coprs/janbaudisch/snapcast
- Failed build log: https://download.copr.fedorainfracloud.org/results/janbaudisch/snapcast/fedora-rawhide-x86_64/03709371-snapcast/builder-live.log.gz

**Environment details**
- OS: Fedora
- Snapcast version: 0.26.0

**Comment by amak79** [comment]
The snapserver [CMakeLists.txt](https://github.com/badaix/snapcast/blob/master/server/CMakeLists.txt#L117) respects the `CMAKE_INSTALL_SYSCONFDIR` variable when installing `snapserver.conf`. Try passing `-DCMAKE_INSTALL_SYSCONFDIR=/etc` to `cmake`.
