### ISSUE TITLE
Data loss on double screen rotation

### ISSUE THREAD

**Issue by davirec** [badaix/snapcast#1004]
- When executing this sequence of actions, there is a loss of data in the activity AboutActivity:

1. ScrollEvent(direction=FULL_LEFT)	
2. IntentEvent(intent='am start de.badaix.snapcast/de.badaix.snapcast.MainActivity')	
3. LongTouchEvent(duration=2000)	[[649,61],[720,145]]
4. DoubleRotationEvent	
5. TouchEvent	[[649,61],[720,145]]
6. TouchEvent	[[370,61],[713,145]]
7. TouchEvent	[[14,1156],[467,1191]]
8. IntentEvent(intent='am start de.badaix.snapcast/de.badaix.snapcast.MainActivity')	
9. **Cap01:** capture screen properties before rotation
10. _DoubleRotationEvent_
11. **Cap02:** capture screen properties after rotation
12. **Cap01 != Cap02**

- MainActivity:fragment changes size
<div id="ladoalado" style="display:flex;justify-content:center;">

<figure id="container">Before and after double screen rotation<br>
<img src="https://user-images.githubusercontent.com/3637419/159940210-e653680d-a9f2-4e7f-8635-1a18b5f82b34.png" width=20% height=20% >
</figure>

<figure id="container">
<img src="https://user-images.githubusercontent.com/3637419/159940206-584b4591-0178-45c2-9aed-028f231292f0.png" width=20% height=20%>
</figure>

</div> 

- MainActivity:pop-up menu disappears
<div id="ladoalado" style="display:flex;justify-content:center;">

<figure id="container">Before and after double screen rotation<br>
<img src="https://user-images.githubusercontent.com/3637419/159940799-0743d80b-e9d0-42d2-b1c6-91a1ca3e8716.png" width=20% height=20% >
</figure>

<figure id="container">
<img src="https://user-images.githubusercontent.com/3637419/159940793-826a46e5-2a18-4d63-9d55-7c0168790b5a.png" width=20% height=20%>
</figure>

</div> 

A data loss problem occurs when data is accidentally deleted or state variables are accidentally assigned with default or initial values. This issue is related to the activity's lifecycle (1). When a screen rotation occurs, the activity is destroyed and resumed. Data loss will happen if the developer does not save the variables before the destruction and restore them after creation. To avoid this, the developers have to implement both the logic necessary to save the activity state in the onSaveInstanceState() callback method and the logic to resume its state in the onRestoreInstanceState() callback method.
Another way to avoid data loss problems is to use the view model, designed to store and manage UI-related data in a lifecycle-conscious way (2).

Note:

  - Double screen rotation: It is executed twice to reach a state that should be exactly the same as the screen before if no data loss occurred.
  - A data loss problem occurs when data is accidentally deleted or state variables are accidentally assigned with default or initial values.

1. https://developer.android.com/guide/components/activities/activity-lifecycle 
2. https://developer.android.com/topic/libraries/architecture/viewmodel

**Comment by badaix** [comment]
Looks like a snapdroid issue, which is a different project

**Comment by davirec** [comment]
Hi badaix! Sorry about that :)
