### ISSUE TITLE
Playing multiple sources at the same time (for example: voice notifications)

### ISSUE THREAD

**Issue by bunchofbricks** [badaix/snapcast#1005]
**Is your feature request related to a problem? Please describe.**
I would like to start building something like a voice assistant (-> voice notification with text to speech) with the help of snapcast. For this i would need to stream from more than one source at the same time with my snapcast clients. One stream which is always on additional to my spotify and mopidy streams. in the standard configuration this is not possible afaik

**Describe the solution you'd like**
The solution i would like is the possibility to have more than one source/stream active on every client. For example i would have one "voice" source which is always turned on and would deliver my voice notifications to all my snapcast clients. for a second active source i would choose as usual my spotify or mopidy stream

**Describe alternatives you've considered**
An alternative could be running two snapcast clients on one host or merging the "voice" stream on the snapcast server into the other sources.

**Additional context**
Maybe an additional feature to this could be lowering volumes on the one stream if the other (voice) gets active.
But i think this would only make sense if a source is explicitly considered as a voice stream. This could be scripted from the application running the tts engine (which is homeassistant in my example)

**Comment by kingosticks** [comment]
To me, either of the alternatives sound better than adding this specific functionality to snapcast. Could you explain a bit more why they don't work?

**Comment by bunchofbricks** [comment]
i didn't try them yet to be honest. Im not far enough in my voice/tts implementation at this moment.
i just think this could be a useful feature so i dropped this here.

So im not sure at all if the alternatives will work, maybe i can give this a try in the next week.

**Comment by gtsteffaniak** [comment]
@bunchofbricks  I have been trying to accomplish the exact same thing (spotify and tts voiceover via home assistant) and believe I figured out the solution. You are correct you cannot simultaneously play two streams at the same time on the same snap client. 

Snapserver can be configured with two different streams, here's my config: 
```
[stream]
source = pipe:///opt/mpd/snapfifo?name=mpd
source = spotify:///librespot?name=spotify&devicename=Snapcast&bitrate=320&autoplay=false&volume=50&normalize=false
```

However, only one stream can play on a client, so you can hit the gear icon on the snapweb webui and toggle which stream for each client.

A workaround would be to run two clients on the same speaker that you want to have playing both spotify and voiceover. I personally do this via docker containers and it works great. However, I believe it would be a great feature addition to snapcast to allow multiple streams to a single client.

**Comment by yellowonblack** [comment]
This request seems to be related to an older one https://github.com/badaix/snapcast/issues/700

**Comment by tgurr** [comment]
Not sure if this fits your needs but I had a quite similiar although not identical requirement and solved it via the neat meta stream feature of snapcast so my notification (which is currently my door bell which I want to ring even when listening to music via mopidy) is priorized. Works well for me:
```
stream = tcp://127.0.0.1?name=Mopidy&port=4953
stream = alsa://?name=Notification&sampleformat=48000:16:2&device=hw:0,1,0&volume=100
stream = spotify:///librespot?name=Librespot&devicename=Multiroom&bitrate=320&volume=100&cache=/var/lib/snapserver
stream = meta:///Notification/Librespot/Mopidy?name=Meta&control_url=http://192.168.0.10:6680
```
The doorbell is just an ALSA virtual loopback device (modprobe snd-aloop) on a headless machine, fed by openHAB running on the same system and just playing a sound file to the "system speaker (the loopback device)" which is then used via snapcast as the notification stream and assembled into the meta stream and taked into account with priority over the others, in my case the two others being librespot & mopidy. Additional advantage I never have to switch my streams back and forth via a web gui or other client.

**Comment by bunchofbricks** [comment]
This looks exactly like the solution i am requesting. Haven't found the meta streams feature.
So my current build looks like this:

# Two Spotify "Channels", one mopidy stream for podcasts, and a phono stream which catches audio from a usb phono amplifier
source = tcp://0.0.0.0:4953?name=mopidy&mode=server
source = librespot:///root/.cargo/bin/librespot?name=Spotify1&devicename=Spotify1&bitrate=320&volume=100&normalize=true&disable_audio_cache=true&killall=false
source = librespot:///root/.cargo/bin/librespot?name=Spotify2&devicename=Spotify2&bitrate=320&volume=100&normalize=true&disable_audio_cache=true&killall=false
source = alsa://?name=Phono&device=hw:1&silence_threshold_percent=0.4

To achieve what i want i would just add the following:

# This will be my Notification Stream
stream = tcp://0.0.0.0:4954?name=Notification&mode=server

# The Meta Streams
stream = meta:///Notification/Spotify1?name=MetaSpotify1
stream = meta:///Notification/Spotify2?name=MetaSpotify2
stream = meta:///Notification/mopidy?name=MetaMopidy
stream = meta:///Notification/Phono?name=MetaPhono


Gonna try this out, thanks @tgurr .
Unfortunately im not able to check this out this week. I try next week and close this issue when i was successful.

**Comment by Chreece** [comment]
I was having the same issue and for me it works as follow:

Server:
One snapcast server for music-audio getting it's source from mopidy
And one snapcast server for TTS getting it's source from an MPD player (where I can post my announce from Home Assistant).

Clients:
One snapclient for music
And one snapclient for TTS.
They both output to the same speaker and can be played simultanuesly with the alsa dmix.

What I have achieved is: play music, along with the announce, only lowering the volume as long the TTS snapclient is playing, and then turn music volume back to it's previous state.

**Comment by bunchofbricks** [comment]
Checked out the Meta streams exactly as described above. this perfectly achieves what i want without the need to build a workaround like using multiple snapcast clients.

Note: Because the running stream is completely muted as long as the "notification" is playing, theres no way to play around with volumes and achieve a feeling exactly like real voice assistants do. for this a workaround is still needed. This could maybe be a feature request to create options for meta streams to achieve this.

thanks again @tgurr
