### ISSUE TITLE
Autoplay on loading snapcast web client 

### ISSUE THREAD

**Issue by sascha005** [badaix/snapcast#1007]
Hello,

i want to send the snapcast webclient page to a google hub display. This also works perfectly. Is there a way to automatically start playback when the snapcast web client page loads? So you don't have to click the play button first?

Greetings Sascha

**Comment by badaix** [comment]
This is related to [Snapweb](https://github.com/badaix/snapweb). There are some constraints regarding auto play, as you can read [here](https://developer.mozilla.org/en-US/docs/Web/Media/Autoplay_guide). Not sure if this feature is possible.

**Comment by Platypuschan** [comment]
https://github.com/badaix/snapweb/pull/12 <-- isn´t that the feature? i´ve tried to add /autoplay to the url, but it didn´t work. did i missunderstood the function?

**Comment by W-Floyd** [comment]
This feature was lost in snapweb `v0.6.0` (likely due to the GUI rewrite)
