### ISSUE TITLE
control client for desktop

### ISSUE THREAD

**Issue by treakiandroid** [badaix/snapcast#101]
hi,

is there any client for the control interface on port 1705 for desktop systems or only the android one? if so please implement one. a cli thing like nmcli or pacmd would be enough, some gui (may using gtk) would be nice to but not necessary..

**Comment by happyleavesaoc** [comment]
https://home-assistant.io/ implements GUI controls for volume and source selection. But that is more general purpose software, not just media player.

**Comment by Outurnate** [comment]
I plan to implement one for windows.  Maybe I will just expand the scope to cover all platforms

**Comment by treakiandroid** [comment]
@happyleavesaoc that page looks like an ios app, i dont have any apple devices and i dont plan having one in my live.

@Outurnate i am also never using ms windows

i need some software running on debian gnu linux... The universal operating system i am using for nearly everything (including my desktop). Free software for the win, i ma not using propiortory stuff and i dont plan to change that...

so i would be glad if there would be a desktop software running on GNU/Linux based systems

regards

**Comment by happyleavesaoc** [comment]
@treakiandroid it is cross platform.

**Comment by pbros** [comment]
@treakiandroid the Home Assistant integration is also what I use to control my snapclients (source and volume). It's purely web-based, so it will work in any modern web browser (including desktop, iOS and android)
