### ISSUE TITLE
Using librespot-java audio playing too fast.

### ISSUE THREAD

**Issue by foxy82** [badaix/snapcast#1010]
**Describe the bug**

I've created a pipe stream:
```source = pipe:///srv/music/librespot-java-pipe?name=Spotify&mode=read&bitrate=160&sampleformat=44100:16:2```

When I play the music using the android app on my phone it is too fast and also crackly.

**Environment details**
- OS: debian
- Snapcast version: 0.26.0
- Installed from a package

**Comment by foxy82** [comment]
Interesting...

I stopped snapcast server and switched back to my previously working spocon -> owntone setup and it was playing too fast. 

The only thing I'd changed since having a working setup was installing snapserver using the 0.26 deb. Purging the deb and restarting and the sound is back to the correct speed...

Very strange! Anything I can do to fix this as I want to try and possibly move to Snapcast.

**Comment by franconianmetal** [comment]
Change /etc/snapserver.conf

sampleformat = 44100:16:2

Speed will be ok

**Comment by foxy82** [comment]
> Change /etc/snapserver.conf
> 
> sampleformat = 44100:16:2
> 
> Speed will be ok

Isn't that what I've done with my source config with the last parameter?

**Comment by foxy82** [comment]
Weird - so I created a new Debian VM and just installed Spocon and Snapserver and it works ok. So it would appear that owntone and snapserver didn't like being installed on the same VM which seems very strange...

**Comment by badaix** [comment]
yep, strange
