### ISSUE TITLE
Add support for Music Assistant 

### ISSUE THREAD

**Issue by Schluggi** [badaix/snapcast#1019]
Since Home Assistant added aupport for Music Assistant it would be nice to have a "play from url" feature added to the snapcast server. Afterwards we could add a snapserver as a speaker device in Music Assistant. 

https://github.com/music-assistant/hass-music-assistant#supported-media-players

https://youtu.be/SEH-DxOsywg

**Comment by kingosticks** [comment]
Is this possible already by having some other program "play from url" (vlc?) and provide snapcast with PCM data?

**Comment by badaix** [comment]
@Schluggi, I agree with @kingosticks: the philsophy of Snapserver is that the audio signal is fed by another source into the server (and Snapserver offers some generic interfaces for this). One possible solution would be a [Process source](https://github.com/badaix/snapcast/blob/master/doc/configuration.md#process) that launches some player "play from url" capable player and streams the audio from this player.

**Comment by Schluggi** [comment]
> @Schluggi, I agree with @kingosticks: the philsophy of Snapserver is that the audio signal is fed by another source into the server (and Snapserver offers some generic interfaces for this). One possible solution would be a [Process source](https://github.com/badaix/snapcast/blob/master/doc/configuration.md#process) that launches some player "play from url" capable player and streams the audio from this player.

Thank you for the feedback. I'll play around with this.

**Comment by Schluggi** [comment]
> @Schluggi did you manage to play around with this and what were your final results?

No, unfortunately not :/
