### ISSUE TITLE
Group deletion

### ISSUE THREAD

**Issue by MrTiptop** [badaix/snapcast#1022]
Hello, it would be nice (if not already possible) to have the ability to delete groups

**Comment by badaix** [comment]
A group will be deleted implicitly when it is empty. AFAIK there are open feature requests for more explicit group handling (creation, deletion of named groups, e.g. #108). When you remove a client from a group, this client will appear in a new, implicitly created group. Shifting this client into an existing group will delete it's original, now empty, group.
