### ISSUE TITLE
Time Triggered Streaming

### ISSUE THREAD

**Issue by YetAnotherElectronicsChannel** [badaix/snapcast#1027]
I hear very often webradio in the morning with my Sonos sound system.
It automatically starts & stops at certain programmable times with a predefined radio-sender.

My idea: Make a configuration-option that snapcast-server switches predefined-slaves to a predefined source with a programmable volume and start/stop a process in parallel (e.g. player for webradio which routes audio into fifo).

**Comment by badaix** [comment]
Snapcast tries to follow the Unix philosophy: do one thing and do it well. This thing is synchronous audio playback, plus it offers an API to group certain clients and assign a stream to this group.
Using this API you could create a script to accomplish this task.
