### ISSUE TITLE
Mopidy issue on raspberry pi2

### ISSUE THREAD

**Issue by HendrikRoth** [badaix/snapcast#104]
Hello, i am trying to use snapcast with mopidy on a raspberry pi2 (hifiberry digi)

systemctl status mopidy says:

```
Failed to create audio output "audioresample ! audioconvert ! audio/x-raw,rate=48000,channels=2,format=S16LE ! wavenc ! filesink location=/tmp/snapfifo": could not link audioconvert0 to wavenc0
```

/etc/default/snapserver:

```
...
SNAPSERVER_OPTS="-d -s pipe:///tmp/snapfifo?name=wohnzimmer&sampleformat=48000:16:2&codec=flac"
```

/etc/mopidy/mopidy.conf:

```
[audio]
mixer=software
output = audioresample ! audioconvert ! audio/x-raw,rate=48000,channels=2,format=S16LE ! wavenc ! filesink location=/tmp/snapfifo
```

Any ideas, what i need to change? Thanks!

**Comment by jjok** [comment]
Where's the error coming from? It looks like it's Mopidy saying that it can't create the pipe.
I've had it working with the same `output` as in the example.

**Comment by miLORD1337** [comment]
Hi @HendrikRoth and @badaix 
I got that error as well. It is related to the version of gstreamer you are using. As it might be the 0.10 the pipe specifier should be 
`output = audioresample ! audioconvert ! audio/x-raw-int,rate=44100,channels=2,width=16,depth=16,endianness=1234,signed=true ! wavenc ! filesink location=/tmp/snapfifo`

The example works with gstreamer 1.0 I guess. The Readme should probably mention this.

Nice Project!

Regards, miLORD

**Comment by badaix** [comment]
You can also try to use the "read-only" pipe mode:
`SNAPSERVER_OPTS="-d -s pipe:///tmp/snapfifo?name=Radio&mode=read"`
