### ISSUE TITLE
Audio often skipping audibly 

### ISSUE THREAD

**Issue by tinuzz** [badaix/snapcast#105]
Hi,

I'm using snapcast with MPD, and I can hear audio skipping very short periods (order of ms), but it happens often enough to be unbearable, something like once a minute.

What can I tweak to get rid of this behaviour?

Before I started using Snapcast recently, I was using Pulseaudio output in MPD, streaming directly to the remote Pulseaudio daemon, and I did not have this issue. Also, other types of streams, like HD video usually isn't a problem. The remote is a Raspberry Pi 1 running OSMC. I suspect some kind of buffer issue or clock issue, but I don't know where to start looking.

My setup is as follows:
- Debian Linux (amd64) running MPD 0.19 with audio_output type "fifo"
- Snapserver 0.8.0
- Gbit ethernet
- Snapclient 0.8.0 (armhf)
- All Snapcast options default. Codec flac or pcm doesn't make a difference.

MPD configuration:

```
# Snapcast
audio_output {
    type            "fifo"
    name            "Snapcast"
    path            "/tmp/snapfifo"
    format          "48000:16:2"
#    mixer_type      "software"
}

```

Any other information that might help?

BTW, I'm quite sure this is not a problem with MPD. When I cat a file, or use Gstreamer to output an mp3 to the FIFO, the behaviour is the same.

Best regards,
Martijn.

**Comment by s1lvester** [comment]
Did you check that the audio-sources are using the same samplerate as snapserver? also: You can try to increase the pipe-read-buffer but you'll have to account for it via samplerate. I know this sounds terribly complicated but the fact of the matter is, that synchronous audio-streaming is really hard and that's part of the reason that off-the-shelf devices are expensive.

@mikebrady (developer of shairport-sync) has a short writeup in his readme: https://github.com/mikebrady/shairport-sync#latency

**Comment by badaix** [comment]
Snapserver tries to read at 48kHz. When you feed at a slower pace into the pipe (e.g. with 44.1kHz), the server will log `resync` messages and you will hear audio drop outs.
You can start snapserver manually on a shell and watch the output. You can do the same with the client. If there are any buffer underruns or sync issues then you should see them in the log.

**Comment by tinuzz** [comment]
I was aware of the 48k samplerate requirement, hence the `format "48000:16:2"` in mpd.conf. Also my Gstreamer experiments always had something like `audioresample ! audio/x-raw, rate=48000` in the pipeline.

I'll try to get some log output from the server. Thanks,
