### ISSUE TITLE
libFLAC.so.8 library not found

### ISSUE THREAD

**Issue by crab-aesthetics** [badaix/snapcast#1058]
After an update and reboot on Arch, Snapclient no longer starts. 

Trying to start Snapclient results in the error:

`snapclient: error while loading shared libraries: libFLAC.so.8: cannot open shared object file: No such file or directory
`
Other computers running Manjaro or Arch on the same network are fine, but they have not been kept current on updates. The server is a raspberry pi; this is strictly a client side problem. 

FLAC on a working system is version 1.3.4-2

FLAC on this non-working system is 1.4.0-1

Snapcast on both working and non-working systems is 0.26.0-1

I tried reverting FLAC to an earlier version but this will not work due to dependence on libsndfile. I tried removing libsndfile, figuring if I remove it, then install the old FLAC version, then install the old version of libsndfile again that would work, but you can't remove libsndfile without removing pipewire, libpulse, and libbs2b, which have who knows how many other dependencies. 

I also tried uninstalling and reinstalling Snapcast, this has no effect. 
I also tried reinstalling FLAC, this has no effect. 

**Steps to Reproduce**
1. Run updates on Arch, restart the computer
2. Try to start Snapclient with, e.g. snapclient -h 192.168.1.123
3. Receive error message about error while loading shared libraries

**Environment details**
- OS: Arch
- Snapcast version: 0.26.0-1
- Installed from a package, self compiled: Installed through AUR

**Comment by crab-aesthetics** [comment]
I fixed this on my system by making a symbolic link to the new libFLAC.so.12 library:
`cd /usr/lib
sudo ln -s libFLAC.so.12 libFLAC.so.8`

**Comment by johny-numbers** [comment]
> I fixed this on my system by making a symbolic link to the new libFLAC.so.12 library: `cd /usr/lib && sudo ln -s libFLAC.so.12 libFLAC.so.8`

This worked for me too on Fedora 42.
