### ISSUE TITLE
Raspberry pi 3 - Vollumio 3 os / Failed to start Snapcast server - clients

### ISSUE THREAD

**Issue by Atolalab** [badaix/snapcast#1059]
**Failed to start snapcast**
hello, following the installation of volumio with snapcast, I cannot start either the snapserver or the snapclient.

volumio@volumio:~$ sudo service snapserver status
● snapserver.service - Snapcast server
   Loaded: loaded (/lib/systemd/system/snapserver.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2022-09-23 19:17:00 UTC; 6min ago
     Docs: man:snapserver(1)
  Process: 9452 ExecStart=/usr/bin/snapserver --logging.sink=system --server.datadir=${HOME} $**SNAPSERVER_OPTS (code=exited, status=1/FAILURE)**
 Main PID: 9452 **(code=exited, status=1/FAILURE)**

Sep 23 19:17:00 volumio systemd[1]: snapserver.service: Service RestartSec=100ms expired, scheduling restart.
Sep 23 19:17:00 volumio systemd[1]: snapserver.service: Scheduled restart job, restart counter is at 5.
Sep 23 19:17:00 volumio systemd[1]: Stopped Snapcast server.
Sep 23 19:17:00 volumio systemd[1]: snapserver.service: Start request repeated too quickly.
Sep 23 19:17:00 volumio systemd[1]: snapserver.service: Failed with result 'exit-code'.
Sep 23 19:17:00 volumio systemd[1]: **Failed to start Snapcast server.**

**Environment details**
- OS: [Raspberry Pi 3, Volimio 3.1]
- Snapcast version [e.g. 0.21.0]
- Installed from a package, self compiled, ...

```

**Comment by kingosticks** [comment]
You need to find a way to provide snapcast logs, there's no info here to help debug. The volimio project should be able to help you get those logs.
