### ISSUE TITLE
Problems making snapcast server on Freebsd 10.2

### ISSUE THREAD

**Issue by nimonimonimo** [badaix/snapcast#107]
When trying to make Snapcast according to the instructions I get the following result:
`# gmake TARGET=FREEBSD

/usr/local/bin/g++ -std=c++0x -Wall -Wno-unused-function -O3 -pthread -DASIO_STANDALONE -DVERSION=\"0.8.0\" -I. -I.. -I../externals/asio/asio/include -I../externals/popl/include -DNO_CPP11_STRING -DFREEBSD -c snapServer.cpp -o snapServer.o
In file included from snapServer.cpp:24:0:
../common/daemon.h: In function 'void daemonize(const char*)':
../common/daemon.h:39:8: error: 'EXIT_FAILURE' was not declared in this scope
   exit(EXIT_FAILURE);
        ^
../common/daemon.h:39:20: error: 'exit' was not declared in this scope
   exit(EXIT_FAILURE);
                    ^
../common/daemon.h:44:8: error: 'EXIT_SUCCESS' was not declared in this scope
   exit(EXIT_SUCCESS);
        ^
../common/daemon.h:44:20: error: 'exit' was not declared in this scope
   exit(EXIT_SUCCESS);
                    ^
../common/daemon.h:56:8: error: 'EXIT_FAILURE' was not declared in this scope
   exit(EXIT_FAILURE);
        ^
../common/daemon.h:56:20: error: 'exit' was not declared in this scope
   exit(EXIT_FAILURE);
                    ^
../common/daemon.h:63:8: error: 'EXIT_FAILURE' was not declared in this scope
   exit(EXIT_FAILURE);
        ^
../common/daemon.h:63:20: error: 'exit' was not declared in this scope
   exit(EXIT_FAILURE);
                    ^
../common/daemon.h:73:8: error: 'EXIT_FAILURE' was not declared in this scope
   exit(EXIT_FAILURE);
        ^
../common/daemon.h:73:20: error: 'exit' was not declared in this scope
   exit(EXIT_FAILURE);
                    ^
../common/daemon.h:81:8: error: 'EXIT_FAILURE' was not declared in this scope
   exit(EXIT_FAILURE);
        ^
../common/daemon.h:81:20: error: 'exit' was not declared in this scope
   exit(EXIT_FAILURE);
                    ^
../common/daemon.h:93:8: error: 'EXIT_FAILURE' was not declared in this scope
   exit(EXIT_FAILURE);
        ^
../common/daemon.h:93:20: error: 'exit' was not declared in this scope
   exit(EXIT_FAILURE);
                    ^
In file included from ../externals/asio/asio/include/asio/detail/impl/posix_tss_ptr.ipp:24:0,
                 from ../externals/asio/asio/include/asio/detail/posix_tss_ptr.hpp:74,
                 from ../externals/asio/asio/include/asio/detail/tss_ptr.hpp:27,
                 from ../externals/asio/asio/include/asio/detail/call_stack.hpp:20,
                 from ../externals/asio/asio/include/asio/impl/handler_alloc_hook.ipp:19,
                 from ../externals/asio/asio/include/asio/handler_alloc_hook.hpp:78,
                 from ../externals/asio/asio/include/asio/detail/handler_alloc_helpers.hpp:21,
                 from ../externals/asio/asio/include/asio/detail/bind_handler.hpp:19,
                 from ../externals/asio/asio/include/asio/detail/wrapped_handler.hpp:18,
                 from ../externals/asio/asio/include/asio/io_service.hpp:24,
                 from ../externals/asio/asio/include/asio/basic_io_object.hpp:19,
                 from ../externals/asio/asio/include/asio/basic_socket.hpp:20,
                 from ../externals/asio/asio/include/asio/basic_datagram_socket.hpp:20,
                 from ../externals/asio/asio/include/asio.hpp:19,
                 from streamServer.h:22,
                 from snapServer.cpp:31:
../externals/asio/asio/include/asio/error.hpp: At global scope:
../externals/asio/asio/include/asio/error.hpp:256:36: warning: 'asio::error::system_category' defined but not used [-Wunused-variable]
 static const asio::error_category& system_category
                                    ^
../externals/asio/asio/include/asio/error.hpp:258:36: warning: 'asio::error::netdb_category' defined but not used [-Wunused-variable]
 static const asio::error_category& netdb_category
                                    ^
../externals/asio/asio/include/asio/error.hpp:260:36: warning: 'asio::error::addrinfo_category' defined but not used [-Wunused-variable]
 static const asio::error_category& addrinfo_category
                                    ^
../externals/asio/asio/include/asio/error.hpp:262:36: warning: 'asio::error::misc_category' defined but not used [-Wunused-variable]
 static const asio::error_category& misc_category
                                    ^
gmake: *** [Makefile:51: snapServer.o] Error 1`

**Comment by nimonimonimo** [comment]
Found how to solve it here: http://stackoverflow.com/questions/3604524/socket-programming-in-c-in-ubuntu

Basically it was just to add `#include <stdlib.h>` to common/daemon.h.


I am new to github, is there anything I can do to submit this "fix" to the code? `git push`, after asking for credentials at github, said access denied for "badaix/snapcast.git".

**Comment by badaix** [comment]
Thanks :smiley: 

I think you have to fork your own version of snapcast, add the include and do a pull request.
If it's not working, I can add the line.

**Comment by nimonimonimo** [comment]
Thanks!

Now I have tried to make a pull request. Please tell me if I am missing something.
