### ISSUE TITLE
Getting an error one day after successful install/configuration.

### ISSUE THREAD

**Issue by drock1985** [badaix/snapcast#110]
Hi,

I just recently had Snapcast (Server and Client) working in my home. I have mopidy running on my headless server with Snapcast acting as the server for my whole home. I used three Rpi's (2x1st gen, 1 2nd gen) with USB Wifi and had SnapClient installed. I was able to get my streams from Mopidy working with ease. The only item I had to change was the source for one of my Rpi's sound cards (Uses a USB sound card)

Today, I tried to also install local instances of Mopidy on the Raspberry Pi's (starting with the 2nd gen) and was able to get it installed, but the audio ran out the HDMI slot. After reconfiguring Alsa and setting the USB sound card as device 0, I was able to get Mopidy to run locally no problem. I then went to run/test the whole home audio and found nothing working. After checking the server, I am seeing this error in systemd:

```
Exception in StreamSession::reader(): read_some: End of file
```

Not sure what I did to do this, as I never touched the server side.

**Comment by drock1985** [comment]
Hello again,

I seem to have solved my own problem, and discovered a new one. I had to shutdown snapserver and change the output temporarily, and then change it back for it to work. It was strange, but it did fix the issue. 

Now on the same box, I am having trouble getting the local Mopidy instance to stream music. Seems SnapClient takes over the audio driver/alsa.

```
 [alsa-sink-USB Audio] alsa-sink.c: Error opening PCM device
```

Any ideas what I can do?

Thanks,

**Comment by egon0** [comment]
Add this to your mopidy.conf:

`[audio]
output = audioresample ! audio/x-raw,rate=48000,channels=2,format=S16LE ! audioconvert ! wavenc ! filesink location=/tmp/snapfifo`
