### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by mogwa1** [badaix/snapcast#1100]
Archlinux has updated the repositories to include boost 1.81.0, which means that the latest released snapcast version doesn't compile anymore. I noticed that the `develop` branch already has the fix for this.  Would it be possible to make a new release anytime soon?

If not, it's also fine, but then I need to look into patching the arch AUR package to cherry-pick the commit that fixes the boost compilation errors.

**Comment by badaix** [comment]
I was planning to include a new web UI in the next release, but didn't find the time to finish it during the last few month. I think it's a good idea to release the current develop-branch state, that contains a lot of bug fixes soon. 
I will update the documentation and changelog and do some more testing and will try to release next weekend without the updated web UI.

**Comment by badaix** [comment]
Done: https://github.com/badaix/snapcast/releases/tag/v0.27.0

**Comment by mogwa1** [comment]
Thanks!
Seems to work on Archlinux again!

NB: I see that the systemd service files and the "default" env config files have been removed.  Maybe it's a good idea to add them again in a next release if you don't mind?  These were not debian-specific and very useful for Arch as well.  I will need to manually ship those files for the Arch package anyway, since it's kind of expected for a daemon to have a systemd unit and config files.

**Comment by mogwa1** [comment]
Nevermind, I now see they have moved to snapOS.  Sorry for the confusion.
