### ISSUE TITLE
Ship / Add (back) upstream systemd units to release tarball

### ISSUE THREAD

**Issue by tgurr** [badaix/snapcast#1105]
**Describe the bug**
The new release tarball is missing the previously provided upstream systemd units for snapclient and snapserver, removed by https://github.com/badaix/snapcast/commit/0868ae1a6865be689c1568bc49ce6a26a1854cbc. These files still appear to be referenced in the Makefiles, e.g. https://github.com/badaix/snapcast/blob/develop/client/Makefile#L165.

I also found https://github.com/badaix/snapos/tree/master/debian where they probably moved but are not part of the tarball and nothing is mentioned in the changelog / release notes about this for packagers breaking change. Edit: Probably it is more or less mentioned/implied by "Remove debhelper files from project (moved to SnapOS project)" - if you're familiar with debian terms, however it's not only about Debian specific files as mentioned above other distributions also relied on them. For now I've worked around it like Arch packagers did by downloading the snapos tarball additionally.

It would however be *very* helpful to keep providing those with the snapcast release tarball as various distributions relied on and shipped them, it's always good to have an upstream variant which distributions can pick up so configuration and systemd units are not written by each distribution individually and configuration among them diverges.

**Steps to Reproduce**
1. Download tarball of 0.27.0
2. Find the previously shipped systemd files missing

**Environment details**
- OS: Exherbo
- Snapcast version 0.27.0
- source-based (self compiled)

**Comment by badaix** [comment]
They are back: 4fdb4367b55481944c4d2420da9005e7bd645d0d
What I didn't like is that debian requires the debian directory on top level, it's now in extras/package/debian and the CI creates a symlink for the built.

**Comment by badaix** [comment]
@tgurr About the Makefile: are you still using them? Not talking about CMake, but the plain Makefiles.

**Comment by tgurr** [comment]
> @tgurr About the Makefile: are you still using them? Not talking about CMake, but the plain Makefiles.

Thanks for bringing them back! And no we don't use the plain Makefiles anymore, migrated to CMake with the update from 0.16.0 to 0.17.1 3 years ago.

**Comment by badaix** [comment]
> Thanks for bringing them back! And no we don't use the plain Makefiles anymore, migrated to CMake with the update from 0.16.0 to 0.17.1 3 years ago.

Very good, I want to remove them in the next release and have worries, that still people rely on them.

**Comment by badaix** [comment]
Fixed in version [0.28.0](https://github.com/badaix/snapcast/releases/tag/v0.28.0)
