### ISSUE TITLE
XRUN/Not enough frames available every ~16 seconds

### ISSUE THREAD

**Issue by daniel-sousa-me** [badaix/snapcast#1127]
**Describe the bug**
Every ~16 seconds the audio has a bit of noise

**Environment details**
- Raspberry Pi 3B playing through the 3.5 jack
- OS: OSMC (basically Raspbian I think)
- Snapcast version 0.25
- Installed from the package on the official repo

I'm running it successfully on other Pis with the same snapserver on another OS on the 3.5 jack, and with the same OS but through HDMI.

**Log**
[snapclient_log.txt](https://github.com/badaix/snapcast/files/11309098/snapclient_log.txt)

**Comment by badaix** [comment]
Version 0.25.0 is quite old, please try with the latest version.
