### ISSUE TITLE
Snapweb: cannot unmute group when only one one active client left.

### ISSUE THREAD

**Issue by nis65** [badaix/snapcast#1128]
**Describe the bug**
I usually have two sinks in my workstation-group: The raspberry pi driving the nice loudspeakers (for the bass) and a snapclient on my workstation to inject the mid and high frequencies into the headset. The grouping allows me to mute both sinks at once when there is e.g. a phone call.

When I have stopped my workstation but still want to listen via the loudspeakers, the workstation-group has just one 
member left. But no mute/unmute button on the group level is displayed

**Steps to Reproduce**
1. Create in snapweb a group with two members
2. Mute the group
3. Stop one of the snapclients (or move it out of the group)
4. Try to unmute the only running member: You can unmute on member level, but still no sound as the group is still muted. 

**Environment details**
- OS: Raspbian
-  Snapcast version: 0.27.0
- Installed from https://github.com/badaix/snapcast/releases/download/v0.27.0/snapserver_0.27.0-1_armhf.deb

**Possible solutions**

Currently the group mute/unmute button is hidden when the group has only one member. Snapweb could show the group mute/unmute button of a group with one member:
* always, or 
* when the group is muted (to enable group unmute)

I also thought about automatic unmuting the group when the last but one member leaves. But I don't think it is possible to define sane defaults for all edge cases (should the last member be muted? what happens when the other client joins again and the user intention was not to unmute the group at all because it is 3 o clock at night?).

**Comment by badaix** [comment]
Please report snapweb related issues in the snapweb repository. This is a duplicate of https://github.com/badaix/snapweb/issues/6

**Comment by nis65** [comment]
Thanks @badaix for this quick clarification. I knew that snapweb is kind of something separate, but I was unable to find a link. Sorry for the noise, closing.
