### ISSUE TITLE
Snapclient with multiple hosts

### ISSUE THREAD

**Issue by maweki** [badaix/snapcast#114]
I want to run multiple snapservers and snapclients in my network and every snapclient should be able to play from any server.

As far as I can see, a snapclient only plays from one host and since my clients use alsa to play, I can't start multiple clients for every server I have.

I am willing to contribute code, but my C++ is a bit rusty (in that I can't write a C program to save my life - I am usually doing js, python, and haskell). What do you think is needed to extend the hosts to a list of hosts and do everything that is done for one host, for all hosts? Is this at any point a problem? Can we mix multiple hosts or need all to be muted but one?

**Comment by 1337sup3rh4x0r** [comment]
You can already use several streams within a server and have the clients switch between those. What can't you achieve with this, that you would need a second snapcast server for?

**Comment by maweki** [comment]
I didn't know that. How can this be done?

And I wanted to use multiple servers because I wanted to attach one to a chromecast audio, my desktop machine should be one server, so should my wife's. But any other way to achieve multi-room multi-source parallel playback is fine. I thought I could do it with snapcast and multiple servers, since it uses avahi. But the client would need to support multiple servers, if I see it correctly.

**Comment by badaix** [comment]
You can configure different streams or "zones" on a single server and assign clients to zones:
See [configuration](https://github.com/badaix/snapcast#configuration):

> Different streams can by configured with a list of `-s` options, e.g.:
>
>    SNAPSERVER_OPTS="-d -s pipe:///tmp/snapfifo?name=Radio&sampleformat=48000:16:2&codec=flac -s file:///home/user/Musik/Some%20wave%20file.wav?name=File"

What you could do is to start two client instances, each configured with it's own server. But mutli-instance is not yet supported.

**Comment by maweki** [comment]
Ok, this looks good. So for my setup I would create multiple fifos, one for every zone. Would create a pulseaudio sink for every zone (source) on the server and move my stream from my computers into its designated zone. And all clients are connected to the same server and I could configure the zone where they are streaming from.

For hardware inputs, I would do the same thing. Create a zone (fifo in the server) for the chromecast audio, connect it to a raspberry pi or something, configure pulseuaudio to forward the line in to the designated zone/remote sink and we're good.

Is this how it should/would work right now?

**Comment by frankdeath** [comment]
> You can already use several streams within a server and have the clients switch between those. What can't you achieve with this, that you would need a second snapcast server for?

I also want to do what @maweki describes in the 1st post of this issue.  My use-case involves multiple Raspberry Pi 3's running RuneAudio (one for each room).

Each rpi3 is running both a snapserver (mpd is configured to output to the snapserver's fifo) and a client (which defaults to the snapserver running on localhost).  Currently I have to modify the snapclient config and restart the snapclient on each rpi3 when I want them to join a different server.

It is natural to run one instance of mpd and one snapserver on each rpi3.  If I used a server that is more powerful than a rpi3, it would make more sense to run multiple streams with a dedicated mpd instance for each.

**Comment by pdcmoreira** [comment]
- Is it possible to be the server who chooses which clients are connected? Or that must be set on the client?
- Can I remake the stream config on the fly? Or do I have to write it on the config file and restart the server?
