### ISSUE TITLE
Dealing with latency better (in android app)

### ISSUE THREAD

**Issue by axelsimon** [badaix/snapcast#115]
Hi,
I just spent a few minutes playing around, trying to adjust my phones delay, so the Bluetooth speaker it was outputting to could be in sync with the main server's own speakers. An amusing game, but really quite hard.
Especially considering every time you want to make a change, you have to go into the device's settings, then delay, adjust (entering the value manually) then ok, then back out of the settings to "save" them.

May I suggest a simple menu with the possibility to enter a value, possibly a slider bar, but especially -and + buttons to be able to adjust delay, and to make that change immediate to get immediate feedback on what's changing.

This issue is the follow up to issue #85 I suppose :)

Thanks!

**Comment by voltagex** [comment]
I think a test mode of some kind with rising tones would help a lot in getting things in sync, too.

**Comment by voltagex** [comment]
#341 is related as well

**Comment by badaix** [comment]
This issue is related to [Snapdroid](https://github.com/badaix/snapdroid). Please reopen there.
