### ISSUE TITLE
[Feature Request] multiple inputs

### ISSUE THREAD

**Issue by lucasgelfond** [badaix/snapcast#117]
ability for a couple of inputs to be passed into Snapcast - the most recent would be broadcast. ie, I could have family streaming at home via mpd and when I get home I could stream directly off of my phone music, etc. Most recent stream would take priority. Hopefully one could pass in a bunch of inputs

**Comment by badaix** [comment]
This is what zones or streams are for:
https://github.com/badaix/snapcast#configuration

Alternatively, use a single stream, e.g. with mpd as source and configure the source (mpd) to take different audio inputs like DLNA
