### ISSUE TITLE
Script volume control script is called on each update without waiting for the previous to end

### ISSUE THREAD

**Issue by arpena** [badaix/snapcast#1174]
**Describe the bug**
When using the --mixer script option, the script is called so many times when there is an update that it behaves as a fork bomb and my Raspberry PI 2B can't keep up and it even disconnects from the network

**Steps to Reproduce**
1. Start an snapclient with --mixer script option. It doesn't matter what the script does, I even tried with an empty script
2. Slide the volume for the client on Snapweb several times up and down without pause
3. The Raspberry could not keep up with the newly created processes, stops reproducing music and if it is even pushed to disconnect from the wifi network

**Environment details**
- OS: Raspbian GNU/Linux 11 (bullseye)
- Snapcast version 0.27.0
- Installed from github release package

**Comment by badaix** [comment]
This is fixed now in the develop branch: while the script is still executing, the most recent volume change is cached and applied, once the script execution is finished.
You can find debian packages here: https://github.com/badaix/snapcast/actions/runs/8500530509

**Comment by badaix** [comment]
Fixed in version [0.28.0](https://github.com/badaix/snapcast/releases/tag/v0.28.0)
