### ISSUE TITLE
Media player does not support browsing media

### ISSUE THREAD

**Issue by STUKguy** [badaix/snapcast#1177]
So in an effort to get some bluetooth speakers to work with in Home Assistant, i got some advise to try installing Snapcast server and snapcast client, the client is set up on a FireTab 7 and connect to a bluetooth speaker. I installed the intergration for HA connected it to the server and then rebooted HA, tried find the client in the inbuilt media player but didnt find anything, i then tried to build a automation, the FireTab came up but i got the message “Media player does not support browsing media.” directly underneath it, can someone please help. Or am i barking up the wrong tree?
![84d2e4988bd8b860dc02aad4881e524fa786e6f2](https://github.com/badaix/snapcast/assets/66088795/24c48c96-8311-4ac2-95c6-cb2e9927d9d3)

**Comment by rwjack** [comment]
I'm not sure Snapcast does that. From my understanding Snapcast is just audio transport/synchronization between your master media player and satellites.

Think you now need to configure a snapcast backend, such as MPD or Spotify, and control your media from there. That's how I do it with spotify.
