### ISSUE TITLE
quote in name fails

### ISSUE THREAD

**Issue by welch** [badaix/snapcast#118]
When adding a radio station whose name included a double-quote
(7" soul), everything beyond the quote is dropped, the URL is forgotten,
and attempting to delete the garbled station via the burger menu fails.

**Comment by badaix** [comment]
Where did you add the station?
Snapcast doesn't have any burger menu

**Comment by welch** [comment]
how strange, I got here from a RuneAudio link. I don't even know what snapcast is!
