### ISSUE TITLE
iphone or ipad client?

### ISSUE THREAD

**Issue by laoshaw** [badaix/snapcast#1212]
**Is your feature request related to a problem? Please describe.**

can I have an app on iphone and ipad?

**Describe the solution you'd like**

make an apps for iphone and ipad

**Describe alternatives you've considered**

**Additional context**

**Comment by badaix** [comment]
Since I don't posses any Apple hardware, I will not create a client for iPhone or iPad. You can use Snapweb or https://apps.apple.com/de/app/snapcast-client/id1552559653 or donate Apple hardware to me.
