### ISSUE TITLE
How to switch off snapserver syslog messages?

### ISSUE THREAD

**Issue by mrdago** [badaix/snapcast#122]
Hi,

I'm running snapcast v0.9.0 on several Raspberry PI's. If I start or stop a snapclient on the snapserver site or if I send a control request to the server, I receive the following debug output within my ssh session at the server.

How can I switch off this output?

Thanks in advance!

```
Message from syslogd@Lucato at Oct 31 06:42:55 ...
 snapserver[5834]: Contr

Message from syslogd@Lucato at Oct 31 06:42:56 ...
 snapserver[5834]: Session inactive. Removing#012joining readerThread

Broadcast message from systemd-journald@Lucato (Mon 2016-10-31 06:42:56 CET):

snapserver[5834]: Session inactive. Removing
joining readerThread


Broadcast message from systemd-journald@Lucato (Mon 2016-10-31 06:42:56 CET):

snapserver[5834]:


Message from syslogd@Lucato at Oct 31 06:42:56 ...
 snapserver[5834]:

**Comment by s1lvester** [comment]
There is no Option to switch it off. If it bothers you then just send all snapcast-output to /dev/null. e.g.

`snapserver --some-option --some-other-option > /dev/null`

although this shouldn't be necessary if youre running the snapserver via systemd-service...

**Comment by kaindl** [comment]
@mrdago is not complaining about stdout oder stderr messages, but about syslog-messages! and there is indeed no way, to switch them off. Even if I run snapserver directly, without the daemon-parameter, there are messages logged to syslog additional to them in stdout/stderr! This should either only happen, if it is run as a daemon or should be turned off by a paramter (or both..)

**Comment by badaix** [comment]
done in a2311df
There are the client settings:
* `--logsink`: `null`, `system`, `stdout`, `stderr`, `file:<filename>`
when left empty (default): if running as daemon `system` else `stdout`
* `--logfilter`: `<tag>:<level>[,<tag>:<level>]*`, with tag = `*` or `<log tag>` and `level` = `trace`, `debug`, `info`, `notice`, `warning`, `error`, `fatal`
default: `*:info`, chunk statistics can be viewed with `Stats:debug`

For the server there are the same options available in `snapserver.conf`:
```
# Logging options #############################################################
#
[logging]

# log sink [null,system,stdout,stderr,file:<filename>]
# when left empty: if running as daemon "system" else "stdout"
#sink = 

# log filter <tag>:<level>[,<tag>:<level>]* 
# with tag = * or <log tag> and level = [trace,debug,info,notice,warning,error,fatal]
#filter = *:info
#
###############################################################################
```
