### ISSUE TITLE
feature request: hidden / meta-only sources

### ISSUE THREAD

**Issue by pharmacologic** [badaix/snapcast#1224]
**Is your feature request related to a problem? Please describe.**
I have some audio sources that I've set up which are intended only as components of meta streams - for example, an mpd instance specifically for text-to-speech announcements - and their presence in the UI feels somewhat cluttered. I had planned on building additional meta streams for other users, but I'm hesitant at this point. (I have 12 streams currently)

**Describe the solution you'd like**
I think it could be a simple flag like:
 `source = pipe:///run/snapfifo?name=meta-only&hidden=true`

This would have the effect of removing the source from the list of available streams on the front-end, while remaining available to be called by meta streams. 

**Describe alternatives you've considered**
It's a fairly minor issue, so perhaps it could be overlooked, or the names could be made easier to distinguish in the drop-down list. These don't feel optimal in the context of other household users, however.

**Additional context**
I'm hoping to share snapcast with other household members, and I think it would likely be easier to use on their end if I could present simply one meta stream per person + perhaps dedicated airplay / spotify connect streams.

**Comment by badaix** [comment]
This is described here: 
https://github.com/badaix/snapcast/blob/develop/doc/configuration.md#meta

> ...
> Use codec=null for stream sources that should only serve as input for meta streams
>

Maybe I could add to the documentation that this will effectively hide the source

**Comment by pharmacologic** [comment]
Oh, wonderful, thank you! I did try to read through the documentation for a relevant feature but I guess I still managed to miss that part.

Would `codec=null` be considered a global parameter valid for all sources? I wonder if it's worth mentioning near the top of that document as well (along with the other global parameters).

I think I likely did read that bit under the `meta` section at an earlier point, but when I was looking for it, I had the impression that parameters listed only under a source type subsection were specific to that source type, so most of my focus was on the top global parameters section
