### ISSUE TITLE
The compilation of Snapcast in OpenWrt 23.05.3 still encounters errors and remains unresolved for an extended period

### ISSUE THREAD

**Issue by dycfan** [badaix/snapcast#1225]
This issue should have been raised in the SnapOS repository, but for unknown reasons, the SnapOS repository has been closed, preventing the submission of any problems. Therefore, I'm resorting to submitting it here.

My OpenWrt version is 23.05.3, sourced from the official repository. I attempted to compile using the SnapOS repository.

Command to clone the SnapOS repository:
git clone -b v0.27 --single-branch --depth=1 https://github.com/badaix/snapos.git

However, errors persist during the compilation process：

-- Build files have been written to: /mnt/LocalDisk1/Openwrt/myop23053/build_dir/target-x86_64_musl/snapcast-0.27.0
touch /mnt/LocalDisk1/Openwrt/myop23053/build_dir/target-x86_64_musl/snapcast-0.27.0/.configured_68b329da9893e34099c7d8ad5cb9c940
rm -f /mnt/LocalDisk1/Openwrt/myop23053/build_dir/target-x86_64_musl/snapcast-0.27.0/.built
touch /mnt/LocalDisk1/Openwrt/myop23053/build_dir/target-x86_64_musl/snapcast-0.27.0/.built_check
MAKEFLAGS="" /mnt/LocalDisk1/Openwrt/myop23053/staging_dir/host/bin/ninja  -j1 -C /mnt/LocalDisk1/Openwrt/myop23053/build_dir/target-x86_64_musl/snapcast-0.27.0
ninja: Entering directory `/mnt/LocalDisk1/Openwrt/myop23053/build_dir/target-x86_64_musl/snapcast-0.27.0'
[57/57] Linking CXX executable bin/snapclient
FAILED: bin/snapclient
![BIANYITISHI01](https://github.com/badaix/snapcast/assets/75351554/5976edbc-e501-4edd-b81b-df01b388578f)

**Comment by badaix** [comment]
I don't know what's going wrong with your build, the CMake warning seems to be just a warning and not the error. 
This is an issue regarding to the OpenWRT recipe for your specific OpenWRT version and setup, not a Snapcast issue. 
Unfortunately, I don't have time to maintain SnapOS, so I've archived the project. Everyone is free to create a fork of the project and continue maintaining it.
Maybe you can open a [discussion](https://github.com/badaix/snapcast/discussions) if you cannot solve the problem on your own.
