### ISSUE TITLE
Send snapclient stream over bluetooth

### ISSUE THREAD

**Issue by fallenicarus** [badaix/snapcast#123]
Is it possible to tap into the stream being played by a snapclient and send it over bluetooth to a bluetooth speaker (via pulse audio maybe). 

The reason I ask is  - I am looking at setting up a multiroom system where some of the snapclients may need to pass along an audio stream to a bluetooth speaker (say in a bathroom or something where you cant really place a rpi or equivalent device). For the most part it should be good enough for just snapclients to work as documented everywhere else. But for some cases, I would need to send stuff over a bluetooth setup and I just wanted to check. Looking around I cant find much information. 

edit-  wanted to add. I am aware of the potential issues with synchronous play in bluetooth but just checking out if this is something thats a possibility.

**Comment by pbros** [comment]
Hi, I was able to do this by setting up a raspberry pi with a bluetooth adapter and pulseaudio. It was not able to make it autoconnect to the bluetooth speaker (UE Megaboom), so I created a web service that wraps bluetoothctl commands, which I call from my home automation software (homeassistant).

All that being said, I've had issues maintaining synchronization. By trial and error, I got a latency of around 196ms added by the bluetooth stack, but it often jumps around to 182ms which is an audible difference. Even after restarting the speaker and reconnecting the latency doesn't always go back to my baseline of 196ms.

If there was a way to "force" a latency on the bluetooth to keep it constant it might work better, but as my setup currently is, it is impossible to maintain synchronization.

**Comment by fallenicarus** [comment]
So I take it its possible to setup the source stream for snapcast to be routed to pulseaudio? Is there some place I can readup more about how to do it?

**Comment by badaix** [comment]
[here](https://wiki.debian.org/Bluetooth/Alsa) they install some `bluez-alsa` package and get an additional alsa device that could be configured as output device in snapclient with `--soundcard`.
Although they say "bluez-alsa package is not available on jessie and above" this should be the right direction: somehow using an Alsa or Pulseaudio plugin

**Comment by pbros** [comment]
That's exactly what I did. I use the --soundcard for snapclient to select the soundcard created by pulse/bluez after connecting to my bluetooth speaker.
