### ISSUE TITLE
how can i switch to non exclusionary alsa mode?

### ISSUE THREAD

**Issue by treaki** [badaix/snapcast#124]
hi,

i have some respi in my kitchen for playing music using snapcast. Now i want to introduce another snapserver to the network that should be played parallel with the other one. Problem is:

```
2016-11-04 10-39-10 [err] Controller::onException: Can't open plughw:CARD=Device,DEV=0 PCM device: Device or resource busy
```

so how can i get snapclient to dont use alsa using the exclusive mode but that mode that can be used by more then one software simultaneously? I know an option with other softwares using alsa.

Thanks in advance

**Comment by badaix** [comment]
Is it a normal Raspbian Jessie? I can start several snapclients on my pi's (also on my x64 Linux Mint). How can I reproduce this?
Is this related to #121?

**Comment by quantenschaum** [comment]
I do not completely understand the question/problem, but it is possible to start multiple instances of `snapclient` using the same audio device. But only one of them can play at a time. An ALSA `hw` device cannot be shared, but a snapclient, that is not playing, will release the device after, I think, 5 seconds. 

Another way to allow shared and simultaneous access to the audio device is to use ALSA's `dmix`.

**Comment by maotouying** [comment]
You need change alsa device,that will be ok,as this:
//if ((pcm = snd_pcm_open(&handle_, pcmDevice_.name.c_str(), SND_PCM_STREAM_PLAYBACK, 0)) < 0)
>>
	if ((pcm = snd_pcm_open(&handle_, "default", SND_PCM_STREAM_PLAYBACK, 0)) < 0)

**Comment by P-D-G** [comment]
If a workaround is okay with you, you can define different channels which route audio to a common slave device. [Here](http://mailman.alsa-project.org/pipermail/alsa-devel/2008-April/007069.html) is the example that I've used to have a snapclient and librespot play at the same time. It seems to do the trick.

For the sake of completeness, here is my current /etc/asound.conf : 
`pcm.!default {
    type	plug
    slave.pcm	"dmixer"
}
ctl.!default {
    type hw
    card 1
}

pcm.dmixer  {
 	type dmix
 	ipc_key 1024
 	slave {
		pcm "hw:1"
		period_time 0
		period_size 1024
		buffer_size 4096
		channels 2
	}
	bindings {
		0 0
		1 1
	}
}

ctl.dmixer {
	type hw
	card 1
}

# This would be channel 1
pcm.channel1 {
    type plug
    slave.pcm "chan_1"
}
# Channel 2
pcm.channel2 {
    type plug
    slave.pcm "chan_2"
}
# Channel 3
pcm.channel3 {
    type plug
    slave.pcm "chan_3"
}
# Channel 4
pcm.channel4 {
    type plug
    slave.pcm "chan_4"
}
# Here are the slave plug-ins for the above devices
pcm.chan_1 {
    type            softvol
    slave.pcm       "dmixer"
    control.name    "chan_1"
    control.card    1
}
pcm.chan_2 {
    type            softvol
    slave.pcm       "dmixer"
    control.name    "chan_2"
    control.card    1
}
pcm.chan_3 {
    type            softvol
    slave.pcm       "dmixer"
    control.name    "chan_3"
    control.card    1
}
pcm.chan_4 {
    type            softvol
    slave.pcm       "dmixer"
    control.name    "chan_4"
    control.card    1
}
`

**Comment by treaki** [comment]
thanks for the advice i am not much into alsa cause on all other systems there is that resource hungry pulse thing.... But on my raspi not and i dont want to until snapcast gets support for pulse or jackd.

i will try to get into and use your examle config @P-D-G if i find the time, thanks for that t so far.

@badaix i could dd you out a image from my sdcard if you want, but i am unable to tell you whats going on exactly because its to much time ago before i set up my raspi

thanks for your help so far and keep up the good work i will check your workaroungs out once i face the problem again that i had theese days 9 not very acute anymore nowadays...)
