### ISSUE TITLE
[Feature Request] Allow intents to control the android app

### ISSUE THREAD

**Issue by hillbicks** [badaix/snapcast#125]
Hi,

it would be great to get intents to control settings for the android app, this way the usage could be automated (I'm in the process of integrating snapcast into my mopidy and fhem environment). 

This way I could automatically start/stop certain clients and change the volume.

**Comment by LeoSum8** [comment]
Did you already start programming a FHEM module?

If you plan to, you could use my work as a basis. It is currently working for me, but requires some additional coding, which I currently don't find the time for. I have it running with mopidy and spotify connect web.

I think FHEM is really the way to go here and you don't really need the android client too much anymore. You can control snapcast and the connected players with hardware buttons then.

If you are interested, let me know!

In case you speak German, here is the FHEM thread about it: https://forum.fhem.de/index.php/topic,55054.msg470764.html

**Comment by hillbicks** [comment]
Well, if you look at the last answer in that thread asking about the current status, that was me ;)

My plan was to use the existing android tablets with the snapcast client to stream the music to them. For this I want to be able to start and stop the snap cast client from the fhem instance via AMAD module. 

But I need to be able to start the clients via intent, otherwise I'll have to start the clients manually :)

BTW: could you share your current implementation for the FHEM module in that thread?

**Comment by LeoSum8** [comment]
I have created a repository and tried to give some explanation on how to get it to work:

https://github.com/LeoSum8/snapcast-fhem/tree/master

Forking and Pull Requests highly appreciated!
