### ISSUE TITLE
Snapserver in Virtualbox - connect to other computer

### ISSUE THREAD

**Issue by vrs01** [badaix/snapcast#126]
Hi!

I have a snapserver running on Debian 8 in a virtualbox on Windows. Inside the virtualbox the snapclient picks up the signal from the snapserver just fine. But how do I get a snapclient on a Raspberry Pi on the same network to connect?
I tried opening port 1704 on the virtualbox. Is this the port snapcast uses?

**Comment by 1337sup3rh4x0r** [comment]
You also need port 1705 for the control commands

**Comment by s1lvester** [comment]
I think you should google and read up on bridged networking in virtualbox. That way the server is easily discoverable.

**Comment by badaix** [comment]
yes, you should use a bridged network for bidirectional network access (being in the same subnet).
