### ISSUE TITLE
 git submodule update --init --recursive, error

### ISSUE THREAD

**Issue by vtec83** [badaix/snapcast#127]
fatal: unable to access 'https://git.xiph.org/flac.git/': Failed to connect to git.xiph.org port 443: Connection timed out Clone of 'https://git.xiph.org/flac.git' into submodule path 'externals/flac' failed

**Comment by badaix** [comment]
just tried it, all good:

````
$ git submodule update --init --recursive
Submodul 'externals/asio' (https://github.com/chriskohlhoff/asio.git) für Pfad 'externals/externals/asio' in die Konfiguration eingetragen.
Submodul 'externals/flac' (https://git.xiph.org/flac.git) für Pfad 'externals/externals/flac' in die Konfiguration eingetragen.
Submodul 'externals/ogg' (https://git.xiph.org/ogg.git) für Pfad 'externals/externals/ogg' in die Konfiguration eingetragen.
Submodul 'externals/popl' (https://github.com/badaix/popl.git) für Pfad 'externals/externals/popl' in die Konfiguration eingetragen.
Submodul 'externals/tremor' (https://git.xiph.org/tremor.git) für Pfad 'externals/externals/tremor' in die Konfiguration eingetragen.
Klone nach '/home/johannes/Develop/test/snapcast/externals/asio' ...
Klone nach '/home/johannes/Develop/test/snapcast/externals/flac' ...
Klone nach '/home/johannes/Develop/test/snapcast/externals/ogg' ...
Klone nach '/home/johannes/Develop/test/snapcast/externals/popl' ...
Klone nach '/home/johannes/Develop/test/snapcast/externals/tremor' ...
Submodul-Pfad: 'asio': '6c4268544ded99344206147a17c5fa87ed91e832' ausgecheckt
Submodul-Pfad: 'flac': '0e11f73eabd3544f59937d0a0d8e076d7c9c2d1d' ausgecheckt
Submodul-Pfad: 'ogg': '18c401c6bc8814d06f3ae53ebf5d4399f90871cc' ausgecheckt
Submodul-Pfad: 'popl': '0dc38f8bc30bec1946f7e3dbc5a2d37ad1edb93e' ausgecheckt
Submodul-Pfad: 'tremor': 'b56ffce0c0773ec5ca04c466bc00b1bbcaf65aef' ausgecheckt
````

**Comment by vtec83** [comment]
Strangely

`git submodule update --init --recursive
Submodule 'externals/asio' (https://github.com/chriskohlhoff/asio.git) registered for path 'asio'
Submodule 'externals/flac' (https://git.xiph.org/flac.git) registered for path 'flac'
Submodule 'externals/ogg' (https://git.xiph.org/ogg.git) registered for path 'ogg'
Submodule 'externals/popl' (https://github.com/badaix/popl.git) registered for path 'popl'
Submodule 'externals/tremor' (https://git.xiph.org/tremor.git) registered for path 'tremor'
Cloning into 'externals/asio'...
remote: Counting objects: 40541, done.
remote: Total 40541 (delta 0), reused 0 (delta 0), pack-reused 40541
Receiving objects: 100% (40541/40541), 13.92 MiB | 1.51 MiB/s, done.
Resolving deltas: 100% (26237/26237), done.
Checking connectivity... done.
Submodule path 'asio': checked out '6c4268544ded99344206147a17c5fa87ed91e832'
Cloning into 'externals/flac'...
fatal: unable to access 'https://git.xiph.org/flac.git/': Failed to connect to git.xiph.org port 443: Connection timed out
Clone of 'https://git.xiph.org/flac.git' into submodule path 'externals/flac' failed
`

**Comment by vtec83** [comment]
On the other server the same. I'm from Russia, can access closed?
