### ISSUE TITLE
current git master does not run... floating point exception

### ISSUE THREAD

**Issue by whatamesss** [badaix/snapcast#1284]
**Describe the bug**

it's been like this for serveral weeks, snapcast builds but does not run

**Steps to Reproduce**
1. build from git master (in sync with develop) using gentoo ebuild or directly with cmake
2. run resulting snapserver binary
3. cry

**Environment details**
- OS: gentoo linux 6.10.7-x86_64 #1 SMP PREEMPT 
- Snapcast version [e.g. 0.21.0] git master
- Installed from a package, self compiled, ...

**Attach logfile if applicable**
Generate logs with `snapclient --logfilter debug` or `snapserver --logging.filter debug` if possible and paste them in the following codeblock

```logsnapserver --logging.filter debug
2024-09-02 10-54-39.404 [Info] (Snapserver) Version 0.29.0
2024-09-02 10-54-39.404 [Info] (Snapserver) Adding source: pipe:///tmp/snapfifo?name=snapcast
2024-09-02 10-54-39.404 [Notice] (init) Settings file: "/root/.config/snapserver/server.json"
2024-09-02 10-54-39.405 [Debug] (parse) StreamUri: pipe:///tmp/snapfifo?name=snapcast
2024-09-02 10-54-39.405 [Debug] (parse) StreamUri.toString: pipe:////tmp/snapfifo?name=snapcast
Floating point exception


[ 3399.012258] traps: snapserver[6653] trap divide error ip:55e519f9f214 sp:7fffe6b08150 error:0 in snapserver[386214,55e519c45000+44a000]

```

**Comment by badaix** [comment]
Not reproducible on a [gentoo/stage3 docker container](https://hub.docker.com/r/gentoo/stage3):

```
3e5f90798586 ~/snapcast/build # cmake .. -G Ninja
-- The CXX compiler identification is GNU 13.3.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/sbin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The C compiler identification is GNU 13.3.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/sbin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Architecture: x86_64
-- Performing Test HAVE_CXX_ATOMICS_WITHOUT_LIB
-- Performing Test HAVE_CXX_ATOMICS_WITHOUT_LIB - Success
-- Found PkgConfig: /usr/sbin/pkg-config (found version "2.2.0")
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Performing Test HAS_CXX11_STRING_SUPPORT
-- Performing Test HAS_CXX11_STRING_SUPPORT - Success
-- Checking for one of the modules 'alsa'
-- Checking for one of the modules 'jack'
-- Checking for one of the modules 'libpulse'
-- Checking for one of the modules 'avahi-client'
-- Checking for one of the modules 'soxr'
-- Checking for one of the modules 'flac'
-- Checking for one of the modules 'ogg'
-- Checking for one of the modules 'vorbis'
-- Checking for one of the modules 'vorbisidec'
-- Checking for one of the modules 'vorbisenc'
-- Checking for one of the modules 'opus'
-- Checking for one of the modules 'expat'
CMake Warning (dev) at CMakeLists.txt:310 (find_package):
  Policy CMP0167 is not set: The FindBoost module is removed.  Run "cmake
  --help-policy CMP0167" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found Boost: /usr/lib64/cmake/Boost-1.85.0/BoostConfig.cmake (found suitable version "1.85.0", minimum required is "1.74")
-- Configuring done (2.8s)
-- Generating done (0.0s)
-- Build files have been written to: /root/snapcast/build

3e5f90798586 ~/snapcast/build # ninja
[55/55] Linking CXX executable /root/snapcast/bin/snapserver

3e5f90798586 ~/snapcast/build # ../bin/snapserver --logging.filter debug
2024-09-02 19-51-19.746 [Info] (Snapserver) Version 0.29.0
2024-09-02 19-51-19.746 [Info] (Snapserver) Adding source: pipe:///tmp/snapfifo?name=default
2024-09-02 19-51-19.746 [Notice] (init) Settings file: "/root/.config/snapserver/server.json"
2024-09-02 19-51-19.747 [Error] (Avahi) Failed to create client: Daemon not running
2024-09-02 19-51-19.747 [Info] (Snapserver) Using HTTP host name: 3e5f90798586
2024-09-02 19-51-19.747 [Debug] (parse) StreamUri: pipe:///tmp/snapfifo?name=default
2024-09-02 19-51-19.747 [Debug] (parse) StreamUri.toString: pipe:////tmp/snapfifo?name=default
2024-09-02 19-51-19.747 [Debug] (PcmStream) Chunk duration: 20 ms, frames: 960, size: 3840
2024-09-02 19-51-19.747 [Info] (PcmStream) PcmStream: default, sampleFormat: 48000:16:2
2024-09-02 19-51-19.747 [Debug] (PcmStream) Silence threshold percent: 0, silence threshold amplitude: 0
2024-09-02 19-51-19.747 [Debug] (AsioStream) Chunk duration: 20 ms, frames: 960, size: 3840
2024-09-02 19-51-19.747 [Info] (PipeStream) PipeStream mode: create
2024-09-02 19-51-19.747 [Info] (Server) Stream: {"fragment":"","host":"","path":"/tmp/snapfifo","query":{"chunk_ms":"20","codec":"flac","name":"default","sampleformat":"48000:16:2"},"raw":"pipe:////tmp/snapfifo?chunk_ms=20&codec=flac&name=default&sampleformat=48000:16:2","scheme":"pipe"}
2024-09-02 19-51-19.747 [Debug] (parse) StreamUri: pipe:///tmp/snapfifo?name=default
2024-09-02 19-51-19.748 [Debug] (parse) StreamUri.toString: pipe:////tmp/snapfifo?name=default
2024-09-02 19-51-19.748 [Debug] (PcmStream) Start: default, type: pipe, sampleformat: 48000:16:2, codec: flac
2024-09-02 19-51-19.748 [Info] (FlacEnc) Init - compression level: 2
2024-09-02 19-51-19.748 [Info] (ControlServer) Creating TCP acceptor for address: 0.0.0.0, port: 1705
2024-09-02 19-51-19.748 [Info] (ControlServer) Creating HTTP acceptor for address: 0.0.0.0, port: 1780
2024-09-02 19-51-19.748 [Info] (StreamServer) Creating stream acceptor for address: 0.0.0.0, port: 1704
2024-09-02 19-51-19.748 [Info] (Snapserver) Number of threads: 4, hw threads: 8
2024-09-02 19-51-19.749 [Error] (AsioStream) Error reading message: End of file, length: 0, ec: asio.misc:2
^C2024-09-02 19-51-23.373 [Info] (Snapserver) Received signal 2: Interrupt
2024-09-02 19-51-23.374 [Info] (Snapserver) Stopping streamServer
2024-09-02 19-51-23.374 [Info] (Snapserver) done
2024-09-02 19-51-23.375 [Notice] (Snapserver) Snapserver terminated.
```

**Comment by whatamesss** [comment]
strace snapserver
execve("/usr/bin/snapserver", ["snapserver"], 0x7ffd6bb63ea0 /* 45 vars */) = 0
brk(NULL)                               = 0x555ce3f36000
access("/etc/ld.so.preload", R_OK)      = 0
openat(AT_FDCWD, "/etc/ld.so.preload", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
close(3)                                = 0
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=132191, ...}) = 0
mmap(NULL, 132191, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f6075a90000
close(3)                                = 0
openat(AT_FDCWD, "/usr/lib64/libvorbis.so.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=182200, ...}) = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f6075a8e000
mmap(NULL, 180240, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f6075a61000
mmap(0x7f6075a64000, 94208, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x3000) = 0x7f6075a64000
mmap(0x7f6075a7b000, 69632, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1a000) = 0x7f6075a7b000
mmap(0x7f6075a8c000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2b000) = 0x7f6075a8c000
close(3)                                = 0
openat(AT_FDCWD, "/usr/lib64/libvorbisenc.so.2", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=616440, ...}) = 0
mmap(NULL, 618576, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f60759c9000
mmap(0x7f60759ca000, 12288, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1000) = 0x7f60759ca000
mmap(0x7f60759cd000, 487424, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x4000) = 0x7f60759cd000
mmap(0x7f6075a44000, 118784, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x7a000) = 0x7f6075a44000
close(3)                                = 0
openat(AT_FDCWD, "/usr/lib64/libogg.so.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=38768, ...}) = 0
mmap(NULL, 36880, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f60759bf000
mmap(0x7f60759c1000, 12288, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7f60759c1000
mmap(0x7f60759c4000, 12288, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x5000) = 0x7f60759c4000
mmap(0x7f60759c7000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x8000) = 0x7f60759c7000
close(3)                                = 0
openat(AT_FDCWD, "/usr/lib64/libFLAC.so.14", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=403408, ...}) = 0
mmap(NULL, 405536, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f607595b000
mmap(0x7f6075964000, 319488, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x9000) = 0x7f6075964000
mmap(0x7f60759b2000, 40960, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x57000) = 0x7f60759b2000
mmap(0x7f60759bc000, 12288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x60000) = 0x7f60759bc000
close(3)                                = 0
openat(AT_FDCWD, "/usr/lib64/libopus.so.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=399288, ...}) = 0
mmap(NULL, 397328, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f60758f9000
mmap(0x7f60758fb000, 311296, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7f60758fb000
mmap(0x7f6075947000, 73728, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x4e000) = 0x7f6075947000
mmap(0x7f6075959000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x60000) = 0x7f6075959000
close(3)                                = 0
openat(AT_FDCWD, "/usr/lib64/libasound.so.2", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=952928, ...}) = 0
mmap(NULL, 955760, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f607580f000
mmap(0x7f6075830000, 589824, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x21000) = 0x7f6075830000
mmap(0x7f60758c0000, 196608, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xb1000) = 0x7f60758c0000
mmap(0x7f60758f0000, 36864, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xe0000) = 0x7f60758f0000
close(3)                                = 0
openat(AT_FDCWD, "/usr/lib64/libjack.so.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=215200, ...}) = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f607580d000
mmap(NULL, 214424, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f60757d8000
mmap(0x7f60757de000, 147456, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x6000) = 0x7f60757de000
mmap(0x7f6075802000, 36864, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2a000) = 0x7f6075802000
mmap(0x7f607580b000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x33000) = 0x7f607580b000
close(3)                                = 0
openat(AT_FDCWD, "/usr/lib64/libexpat.so.1", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=165816, ...}) = 0
mmap(NULL, 163856, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f60757af000
mmap(0x7f60757b1000, 114688, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7f60757b1000
mmap(0x7f60757cd000, 32768, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1e000) = 0x7f60757cd000
mmap(0x7f60757d5000, 12288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x26000) = 0x7f60757d5000
close(3)                                = 0
openat(AT_FDCWD, "/usr/lib64/libsoxr.so.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=203688, ...}) = 0
mmap(NULL, 423072, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f6075747000
mmap(0x7f6075749000, 159744, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7f6075749000
mmap(0x7f6075770000, 28672, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x29000) = 0x7f6075770000
mmap(0x7f6075777000, 12288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2f000) = 0x7f6075777000
mmap(0x7f607577a000, 214176, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f607577a000
close(3)                                = 0
openat(AT_FDCWD, "/usr/lib/gcc/x86_64-pc-linux-gnu/14/libstdc++.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=2566712, ...}) = 0
mmap(NULL, 2580544, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f6075400000
mmap(0x7f6075497000, 1318912, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x97000) = 0x7f6075497000
mmap(0x7f60755d9000, 573440, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1d9000) = 0x7f60755d9000
mmap(0x7f6075665000, 57344, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x265000) = 0x7f6075665000
mmap(0x7f6075673000, 12352, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f6075673000
close(3)                                = 0
openat(AT_FDCWD, "/lib64/libm.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=702480, ...}) = 0
mmap(NULL, 704536, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f607569a000
mmap(0x7f60756a8000, 421888, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xe000) = 0x7f60756a8000
mmap(0x7f607570f000, 221184, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x75000) = 0x7f607570f000
mmap(0x7f6075745000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xaa000) = 0x7f6075745000
close(3)                                = 0
openat(AT_FDCWD, "/usr/lib/gcc/x86_64-pc-linux-gnu/14/libgcc_s.so.1", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=182272, ...}) = 0
mmap(NULL, 180712, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f60753d3000
mmap(0x7f60753d7000, 143360, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x4000) = 0x7f60753d7000
mmap(0x7f60753fa000, 16384, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x27000) = 0x7f60753fa000
mmap(0x7f60753fe000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2b000) = 0x7f60753fe000
close(3)                                = 0
openat(AT_FDCWD, "/lib64/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0000P\2\0\0\0\0\0"..., 832) = 832
pread64(3, "\6\0\0\0\4\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0"..., 784, 64) = 784
fstat(3, {st_mode=S_IFREG|0755, st_size=1794224, ...}) = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f6075698000
pread64(3, "\6\0\0\0\4\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0"..., 784, 64) = 784
mmap(NULL, 1825720, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f6075215000
mmap(0x7f6075238000, 1294336, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x23000) = 0x7f6075238000
mmap(0x7f6075374000, 331776, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x15f000) = 0x7f6075374000
mmap(0x7f60753c5000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1af000) = 0x7f60753c5000
mmap(0x7f60753cb000, 31672, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f60753cb000
close(3)                                = 0
openat(AT_FDCWD, "/lib64/libmvec.so.1", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=149376, ...}) = 0
mmap(NULL, 151568, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f60751ef000
mmap(0x7f60751f3000, 20480, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x4000) = 0x7f60751f3000
mmap(0x7f60751f8000, 110592, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x9000) = 0x7f60751f8000
mmap(0x7f6075213000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x23000) = 0x7f6075213000
close(3)                                = 0
openat(AT_FDCWD, "/usr/lib64/libpipewire-0.3.so.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=846848, ...}) = 0
mmap(NULL, 850752, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f607511f000
mmap(0x7f607512a000, 577536, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xb000) = 0x7f607512a000
mmap(0x7f60751b7000, 135168, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x98000) = 0x7f60751b7000
mmap(0x7f60751d8000, 90112, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xb9000) = 0x7f60751d8000
mmap(0x7f60751ee000, 2880, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f60751ee000
close(3)                                = 0
openat(AT_FDCWD, "/usr/lib/gcc/x86_64-pc-linux-gnu/14/libgomp.so.1", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=334704, ...}) = 0
mmap(NULL, 333424, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f60750cd000
mmap(0x7f60750d7000, 229376, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xa000) = 0x7f60750d7000
mmap(0x7f607510f000, 57344, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x42000) = 0x7f607510f000
mmap(0x7f607511d000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x50000) = 0x7f607511d000
close(3)                                = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f6075696000
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f6075694000
mmap(NULL, 45056, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f6075689000
arch_prctl(ARCH_SET_FS, 0x7f6075691880) = 0
set_tid_address(0x7f6075691b50)         = 3519
set_robust_list(0x7f6075691b60, 24)     = 0
rseq(0x7f60756921a0, 0x20, 0, 0x53053053) = 0
mprotect(0x7f60753c5000, 16384, PROT_READ) = 0
mprotect(0x7f607511d000, 4096, PROT_READ) = 0
mprotect(0x7f60751d8000, 86016, PROT_READ) = 0
mprotect(0x7f6075745000, 4096, PROT_READ) = 0
mprotect(0x7f6075213000, 4096, PROT_READ) = 0
mprotect(0x7f60753fe000, 4096, PROT_READ) = 0
mprotect(0x7f6075665000, 53248, PROT_READ) = 0
mprotect(0x7f6075777000, 8192, PROT_READ) = 0
mprotect(0x7f60757d5000, 8192, PROT_READ) = 0
mprotect(0x7f607580b000, 4096, PROT_READ) = 0
mprotect(0x7f60758f0000, 32768, PROT_READ) = 0
mprotect(0x7f6075959000, 4096, PROT_READ) = 0
mprotect(0x7f60759c7000, 4096, PROT_READ) = 0
mprotect(0x7f60759bc000, 8192, PROT_READ) = 0
mprotect(0x7f6075a8c000, 4096, PROT_READ) = 0
mprotect(0x7f6075a44000, 114688, PROT_READ) = 0
mprotect(0x555ccfa58000, 65536, PROT_READ) = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f6075687000
mprotect(0x7f6075aeb000, 8192, PROT_READ) = 0
prlimit64(0, RLIMIT_STACK, NULL, {rlim_cur=8192*1024, rlim_max=RLIM64_INFINITY}) = 0
munmap(0x7f6075a90000, 132191)          = 0
openat(AT_FDCWD, "/sys/devices/system/cpu/possible", O_RDONLY|O_CLOEXEC) = 3
read(3, "0-3\n", 1024)                  = 4
close(3)                                = 0
getrandom("\xac\xb1\x2a\x25\x79\xb7\x56\xc8", 8, GRND_NONBLOCK) = 8
brk(NULL)                               = 0x555ce3f36000
brk(0x555ce3f57000)                     = 0x555ce3f57000
sched_getaffinity(3519, 8, [0 1 2 3])   = 8
futex(0x7f60756736bc, FUTEX_WAKE_PRIVATE, 2147483647) = 0
getrandom("\xb8\x89\xae\xd7", 4, 0)     = 4
openat(AT_FDCWD, "/usr/lib64/spa-0.2/support/libspa-support.so", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=137496, ...}) = 0
mmap(NULL, 135456, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f60750ab000
mmap(0x7f60750ad000, 94208, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7f60750ad000
mmap(0x7f60750c4000, 24576, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x19000) = 0x7f60750c4000
mmap(0x7f60750ca000, 12288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1f000) = 0x7f60750ca000
close(3)                                = 0
mprotect(0x7f60750ca000, 8192, PROT_READ) = 0
ioctl(2, TCGETS, {c_iflag=ICRNL|IXON|IUTF8, c_oflag=NL0|CR0|TAB0|BS0|VT0|FF0|OPOST|ONLCR, c_cflag=B38400|CS8|CREAD, c_lflag=ISIG|ICANON|ECHO|ECHOE|ECHOK|IEXTEN|ECHOCTL|ECHOKE, ...}) = 0
sched_getaffinity(0, 128, [0 1 2 3])    = 8
openat(AT_FDCWD, "/etc/snapserver.conf", O_RDONLY) = 3
read(3, "################################"..., 8191) = 8062
read(3, "", 8191)                       = 0
close(3)                                = 0
mkdir("/root", 0775)                    = -1 EEXIST (File exists)
mkdir("/root/.config", 0775)            = -1 EEXIST (File exists)
mkdir("/root/.config/snapserver", 0775) = -1 EEXIST (File exists)
openat(AT_FDCWD, "/root/.config/snapserver/server.json", O_RDWR|O_CREAT, 0644) = 3
close(3)                                = 0
openat(AT_FDCWD, "/root/.config/snapserver/server.json", O_RDONLY) = 3
read(3, "{\"ConfigVersion\":2,\"Groups\":[{\"c"..., 8191) = 2880
brk(0x555ce3f78000)                     = 0x555ce3f78000
close(3)                                = 0
eventfd2(0, EFD_CLOEXEC|EFD_NONBLOCK)   = 3
epoll_create1(EPOLL_CLOEXEC)            = 4
timerfd_create(CLOCK_MONOTONIC, TFD_CLOEXEC) = 5
epoll_ctl(4, EPOLL_CTL_ADD, 3, {events=EPOLLIN|EPOLLERR|EPOLLET, data={u32=3824497744, u64=93857449849936}}) = 0
write(3, "\1\0\0\0\0\0\0\0", 8)         = 8
epoll_ctl(4, EPOLL_CTL_ADD, 5, {events=EPOLLIN|EPOLLERR, data={u32=3824497756, u64=93857449849948}}) = 0
--- SIGFPE {si_signo=SIGFPE, si_code=FPE_INTDIV, si_addr=0x555ccf68f214} ---
+++ killed by SIGFPE +++
Floating point exception
