### ISSUE TITLE
[Feature Request] Show metadata from steams & sources

### ISSUE THREAD

**Issue by pbros** [badaix/snapcast#129]
Hi,

I noticed that you are currently working on a release that supports spotify and airplay in the sportify branch. Have you considered adding support for metadata to snapcast? I know that in the case of shairport-sync, the metadata can be pushed to another pipe, which snapcast could use you read the info. I can only assume that other streams/sources should be able to supply metadata in one way or another.

I've already been able to integrate the shairport-sync metadata into HomeAssistant by using the shairport-decoder Python library, but a more "native" support for metadata would be nice :)

**Comment by artmg** [comment]
Hi I would like to bump this FR. The `snapserver` daemon at Info level logs `onMetaChanged (Spotify)` for each track  e.g. 

```
snapserver [Info] (Spotify) INFO:librespot_playback::player: Loading track "Cornfield Chase" with Spotify URI "spotify:track:6a8oa7GncjrVYZuUsNVEMu"
snapserver [Info] (Spotify) INFO:librespot_playback::player: Track "Cornfield Chase" loaded
snapserver [Info] metadata: <Cornfield Chase>
snapserver [Info] metadata={
snapserver [Info]     "STREAM": "Spotify",
snapserver [Info]     "TITLE": "Cornfield Chase"
snapserver [Info] }
snapserver [Info] onMetaChanged (Spotify)
snapserver [Info] onStateChanged (Spotify): 1
```

I have looked in the API but unfortunately none of the commands has a result set that includes track metadata. IMO it would be great if there were a way through the API to access the latest STREAM and TITLE from the `librespot` response. Thanks
