### ISSUE TITLE
Add Multipath TCP Support

### ISSUE THREAD

**Issue by ddimension** [badaix/snapcast#1299]
Hi!

To improve reliability over shaky connections there is the possibility to enable Multipath TCP Support. Multipath TCP is available in all linux kernels since 2020.
MPTCP can establish multiple subflows to the server. In case of a connection disruption, it will use another established subflow or both. Basic configuration of mptcp of the system is done via 'ip mptcp' commands.

I guess it should be able to set it via asio/ip/tcp.hpp via function tcp.protocol(IPPROTO_MPTCP) instead of the default in server and client sockets.

Currently I don't see the right place in the code as I'm new to boost.

If you could give me a hint, I could try to write a patch.

**Comment by badaix** [comment]
Sounds like this would make only sense if you have a Snapserver outside your LAN. Inside your LAN you might have a WiFi and a cable connection, then you should prefer the cable one. 
I would not implement MPTCP support in Snapcast, I've never used it, but I think it would make more sense to setup a virtual interface that does MPTCP and connect Snapcast via tihs interface.
