### ISSUE TITLE
Bitrate and bitdepth

### ISSUE THREAD

**Issue by vdbee** [badaix/snapcast#13]
Thanks for this very easy to use software.

Please can you give some directions on how to configure Mopidy and possibly also the server and client for a FLAC stream with higher bitrate (48kHz) and bitdepth (24bits) with a high quality resampling (default is 4, max is 10?) ?

**Comment by badaix** [comment]
Hi,
you have to configure the format (-s option on the server) according to the input source (it has to match the format you're feeding into the `/tmp/snapfifo pipe`). Default is `44100:16:2`.
Also there is no resampling in Snapcast. This must happen beforehand to have a fixed sample format.
You can configure the compression ratio of FLAC with `-c flac:x`. This is only the compression ratio - FLAC will always be loss less.
But: currently in the Flac encoder/decoder the 16 bit and 2 channels are hard coded. So you can actually only change the sampling rate to e.g. 48000 using `-s 48000:16:2`.
Support for different bit depths and channels is on the road map.

**Comment by badaix** [comment]
Snapcast [v0.7.0](https://github.com/badaix/snapcast/releases/tag/v0.7.0) now supports Hi-Res audio.
You can configure the sample format per stream or globally to e.g. 48 kHz,  24 bit, stereo: 
Per stream:
```-s "pipe:///tmp/snapfifo?name=Radio&sampleformat=48000:24:2"``` 
As default:
```--sampleformat 48000:24:2```
