### ISSUE TITLE
Dropouts on RPi B Snapclient

### ISSUE THREAD

**Issue by KraigoMpls** [badaix/snapcast#131]
I hesitate to even call this an issue.  Here's my system:

RPi 3 as SnapServer and SnapClient.
- Trendnet Gb wired networking
- HiFiBerry DAC+
- 32 GB Samsung EVO+ SD card
- Jessie OS with GUI disabled and small video buffer
- Mopidy and Musicbox as a source.
- 2.5A power supply

RPi 2 as a SnapClient (originally the client and server as above).
- Built in 10/100 wired networking
- HiFiBerry DAC+
- 32 GB Samsung EVO+ SD card
- Jessie OS with GUI disabled and small video buffer
- 2.5A power supply

Four RPi B's as SnapClients
- Edimax WiFi networking
- HiFiBerry DAC
- 32 GB Samsung EVO+ SD card
- JessieLite OS
- Turbo overclocked
- 2.5A power supply

The issue is (I'm sure you'll have guessed this) with the RPI B's.  There are regular drop outs across the system.  It'd be nice if there weren't.

In thinking and reading about this, my guess is that it's because of the single core processor on the RPi B's.  I've read that the USB interface eats up a chunk of the CPU power.  It's not an issue with the RPi 2 and 3 because they have other cores to keep things going.

I know that I get about half of the performance with the Edimax vs. the 10/100 wired, but wireless is a huge design goal and I'm not prepared to give it up.

I'm confident that the server is not an issue because I've never heard the Pi 2 drop out.  FWIW, the Pi3 was just put into service last weekend.

So I'm trying to maximize the CPU available to SnapClient.  The raw WiFi speeds are such that they shouldn't have a problem with the bandwidth.  I'm using the recommended x-raw settings, which I'm guessing means straight up PCM.  That would eat bandwidth, which we have plenty of and require little CPU for decoding.  That is probably the perfect setting for a multicore Pi.

I'm wondering if something like Vorbis might work better for the RPi B's though.  You pay for decoding time, but it might pay off in terms of less bandwidth on the USB/Wireless connection.

I'm pursuing multiple avenues here, partly out of joy of discovery, partly out of frustration.  I just tonight overclocked the RPi B's for the first time and I'll look for useless processes and other CPU eaters.

Ultimately I'm afraid I'm going to have to dump a chunk of change into replacing four RPi's with HiFiBerries.  It's enough money that I'd love to at least find a good interim solution.

The issue is an annoyance.  Mostly it works well.  I'd be happier if the whole system worked as smoothly as it does with the multi-core RPi's.

Thoughts?

**Comment by KraigoMpls** [comment]
I spent a bit of time playing with ogg vs. pcm vs. flac.  To my complete non-surprise, the flac (default) worked the best.  Lower network bandwidth and easy to decode.

I might also note that the Pi B's have the same image - I cloned them and then changed their hostnames and static IP addresses.

Suggestions welcomed.  I'm still pretty confident that the culprit is the USB interface eating most of the available CPU on the single core Pi's.  I'd love for that to not be the case.

**Comment by m-kloeckner** [comment]
I guess the Edimax WiFi dongle is the problem. I had similar problems with Realtek rtl8192cu
(USB: 0BDA:8178) chipsets. I only managed to get a stable WiFi connection (without dropouts and decent ping) by changing the USB dongle. Maybe it's a driver issue, maybe the Pi doesn't provide enough power on the USB port.

There are three things you could try:

1. Set `max_usb_current=1` in the config.txt to double the power provided at the USB ports. You need a sufficient power supply for that.
2. Use a powered USB hub for the WiFi dongle.
3. Buy different WiFi dongles. e.g., ones with BCM43143 chipset like the official Raspberry WiFi dongle.

Let me know if that helps. I made the mistake and bought several TL-WN823N which resulted in the same issues as you have. Even with a powered USB hub, they are still problematic.

**Comment by KraigoMpls** [comment]
I will try your three things first.  I tested with wire connections on a couple of the Pi B's yesterday, they went for hours very smoothly.  Four or five new wifi dongles are a lot cheaper than replacing the Pi's and HiFiBerries if I need to go that route..  I also have a different router that I started putting OpenWRT on, but never finished, it should have much better bandwidth.

Thanks for your tips - I'll give them a try today.

**Comment by twenta** [comment]
I share the experience with a Edimax Wifi dongle. I had serious "gaps" and when I changed to another WIFI dongle, exverything was running smoothly.

**Comment by KraigoMpls** [comment]
I truly appreciate the responses.  Can anyone be more explicit in a recommendation for new dongles?

**Comment by badaix** [comment]
Are the audio drops simultaneous on all PIs?
My FRiTZ!Box router needs a WiFi power cycle from time to time. 
Suddenly the players start dropping audio. In this case I can see that the WiFi traffic is on the upper limit. I guess the network is flooded with retransmissions then. This happens maybe up to once per week. Stopping audio (network traffic) doesn't help to recover.
From RPI CPU point of view, the first RIP generation is working fine in my setup.

**Comment by KraigoMpls** [comment]
At one point it seemed as though all the Pi B's were going at once.  I moved to a Pi 3 server last  weekend, running it into a Gb wired network adapter and moved the data to the SD card.  The previous server had the SnapServer disabled and became just a node.

I'm planning on moving to a new router, perhaps this week.  I abandoned it a few months when the performance with OpenWRT was very bad.  I'll pick it up again this week.

I picked up a couple of these to test:  https://www.amazon.com/gp/product/B005GSGPDM/ref=ox_sc_act_title_1?ie=UTF8&psc=1

So far the results are very promising.  I have a couple more in my Amazon shopping cart.

**Comment by KraigoMpls** [comment]
...so that's what "Close and Comment" means.  I'll leave this open for now.  I'm pretty confident that the new WiFi adapters are a good solution.  Thanks for all of the help folks!

**Comment by m-kloeckner** [comment]
Maybe a bit off topic, but instead of using raspberries I made good experiences with a couple of cheap TL-WR710N routers running openwrt and snapclient. You will need to attach a USB soundcard. Wifi reception is perfect and the CPU power of the tiny device is sufficient. They cost 20€ each + USB soundcard.

**Comment by KraigoMpls** [comment]
The Edimax adapters I linked to above seem to be doing the trick.  They required no configuration changes. I'm guessing they are pretty much a bigger antenna.  The system feels dropout free now. I'm closing the discussion. Thanks for the suggestions, folks.

**Comment by badaix** [comment]
as they are 802.11n adapters, you can even operate them at 5 GHz which will not be much less crowded than the 2.4 GHz WiFi

**Comment by renearts** [comment]
802.11n does not necessarily mean 5GHz support: it is just a protocol which can be used on both 2.4 and 5 GHz. According to the specs they do not support 5GHz.
