### ISSUE TITLE
No response from JSON-RPC API?

### ISSUE THREAD

**Issue by ryanjchr** [badaix/snapcast#132]
I'm attempting to write a remote control application for Snapcast which makes use of the built-in JSON-RPC API but for whatever reason I can't seem to get any responses out of Snapserver. The server outputs that it's at least received a Server.GetStatus message:
`[Notice] ControlServer::NewConnection: 192.168.1.182`
But no response is ever received by my client program - and it's not just my program, I cant get a response out of Snapserver using python-snapcast (https://github.com/happyleavesaoc/python-snapcast) either. The messages being sent are definitely well-formed so I'm not sure what the issue could be. Any ideas?

Extra info:
I just used Wireshark to capture traffic going in and out of the Snapserver control port, I can see that my message gets received by Snapserver, which then sends a response but the response contains no data:
(Message Received)
![screen shot 2016-11-20 at 12 52 18 pm](https://cloud.githubusercontent.com/assets/8773259/20459731/6a405bc4-af20-11e6-8b0d-550c585ffb56.png)

(Response from Snapserver)
![screen shot 2016-11-20 at 12 52 24 pm](https://cloud.githubusercontent.com/assets/8773259/20459738/a12e3a34-af20-11e6-8efd-90640f3b6f1d.png)

**Comment by LeoSum8** [comment]
Can you give an example of the JSON messages you are sending?
I myself had to fiddle with the format a bit until I was able to communicate correctly with the server.
Do you terminate the message with a newline character?

**Comment by badaix** [comment]
maybe this discussion can help you: #109 
Keep in mind that the server expects [ndjson](http://ndjson.org/), i.e. pure (not wrapped in HTTP) json messages in a single line, terminated by a newline character.

**Comment by unimatrix27** [comment]
I wrote an [FHEM Module](https://github.com/unimatrix27/fhemmodules/blob/master/96_Snapcast.pm) in perl to control Snapcast.

In order to understand the RPC JSON part I simply used tcpflow
`tcpflow -i eth0 port 1705`

This way you can use the Android APP, tryout all functions and see how the JSON is sent and received. This might also help your development.

**Comment by LeoSum8** [comment]
Great, an FHEM module! Looks more capable than what I was able to accomplish so far.
Watch out for feedback! ;)

**Comment by mrdago** [comment]
Based on the example (https://github.com/happyleavesaoc/python-snapcast) I've  created the following python script and it works fine for me. Just try it!

Usage:  snapctrl.py snapserver status|clients


```#!/usr/bin/python
# -*- coding: utf-8 -*-

import sys
import telnetlib
import json
import threading
import time

# get command line parameter
#
if len(sys.argv) == 1:
  print ("usage: %s <SERVERNAME> [<COMMAND> [PARAMETER]]" % sys.argv[0])
  sys.exit()
if len(sys.argv) >= 2:
  snap_server=sys.argv[1]
  snap_port   = 1705
command=None
if len(sys.argv) >= 3:
  command = sys.argv[2]
parameter=None
if len(sys.argv) >= 4:
  parameter = sys.argv[3]

# connect to snap server and read status entry
#
requestId = 1
telnet = telnetlib.Telnet(snap_server, snap_port)
telnet.write(json.dumps({'jsonrpc': '2.0', 'method': 'Server.GetStatus', 'id': requestId}) + "\r\n")

j = json.loads(telnet.read_until("\r\n", timeout=2))
if not j:
  print("No status entry received from: %s" % (snap_server))
  sys.exit()
  
telnet.close

print json.dumps(j, indent=4, sort_keys=True)

if not command:
  print( "Server:")
  print( j['result']['server']['host']['name'] + " - " + j['result']['streams'][0]['status'])
  print( "Clients:")
  for client in j["result"]["clients"]:
    print( client['host']['name'] + " - " + client['host']['ip'] + " connected: " + str(client['connected']))
elif command == "count":
  count = 0
  for client in j["result"]["clients"]:
    if str(client['connected']) == "True" :
        count = count + 1
  print count

elif command == "status" and parameter:
  for client in j["result"]["clients"]:
    if client['host']['name'] == parameter :
      print( client['host']['name'] + " - " + client['host']['ip'] + " connected: " + str(client['connected']))

elif command == "clients":
  for client in j["result"]["clients"]:
    if parameter == "connected":
      if str(client['connected']) == "True":
        print( client['host']['name'])
    elif not parameter:
      if str(client['connected']) == "True":
        print( client['host']['name'] + " - " + client['host']['ip'] + " - connected")
      else:
        print( client['host']['name'] + " - " + client['host']['ip'])

elif command == "server" and parameter == "status":
  print( j['result']['streams'][0]['status'] )```

**Comment by badaix** [comment]
Just to make you guys aware:
I'm currently changing the data structures and the JSON RPC.
There will be a "group" layer, gluing clients together. A stream is assigned to the group and can be changed for the whole group.

![unbenannt](https://cloud.githubusercontent.com/assets/10322999/21110128/59aab8f8-c09c-11e6-8a5f-55fd04e7d009.png)

**Comment by unimatrix27** [comment]
thanks for the notice. i understand its just an additional layer. This is not about one client being able to subscribe to more than 1 stream, right?

**Comment by happyleavesaoc** [comment]
I will be updated `python-snapcast` accordingly once that update is released.

**Comment by unimatrix27** [comment]
I checked out the group layer thing in the devel branch so I understand this is simply to make it easier to change the stream of a group of clients. I suggest also to implement a muting  on group level. In Android this could be the same volume button just left to the settings button. Volume for the whole group is more tricky so maybe that does not have to go there. 

I guess it is not trivial to implement a feature to have one group to subscribe to more than one channel, right? I guess the audio would have to be mixed together, not to talk about different sample rates, formats, etc.
