### ISSUE TITLE
snapclient configuration

### ISSUE THREAD

**Issue by jeroenjacobs1205** [badaix/snapcast#133]
Hi,

I'm trying to setup snapcast with home-assistant (home-assistant.io). I setup snap-server with Mopidy, and it seems to work.

However, the devices where I run snap-client on, show up as "Unnamed device" in the Home Assistant web UI.

I'm sure there must be a way to configure a name for a snap-client, but I'm unable to find such a command-line option.

The docs say there is a REST API (although it doesn't explain how to call it), and there is some Android device that should allow to configure clients. 

Since I don't intend to buy an Android device (or bother to install an emulator), just to configure my snap-client instances, can someone please explain me how to do this?

**Comment by twenta** [comment]
I have no experience with home assistant, but what is the output of
cat ~/.config/snapcast/server.json |grep name

(Maybe you have to adapt the path to the .config directory to your setup)?

**Comment by twenta** [comment]
I guess snapserver/-clients read the name in the /etc/hostname /etc/hosts. Try to change both files to your desired name like that
http://developpeers.com/blogs/change-the-hostname-of-your-raspberry-pi

 after rebooting, at least in snapserver should have changed. For issued with home-assistant you would probably get help at their issue-page...

**Comment by juzim** [comment]
You can also set "friendly" names for devices: https://home-assistant.io/getting-started/customizing-devices/
