### ISSUE TITLE
cannot make in Jessie (Rpi 3)

### ISSUE THREAD

**Issue by pbocsak** [badaix/snapcast#135]
Hi all,
I'm fairly new to the whole Linux/Raspbian/Jessie world, so my "issue" might be a little stupid, but either way here goes:
I cannot make the server and client.
I have followed all the steps, meaning:
```
sudo apt-get install git
git clone https://github.com/badaix/snapcast.git
cd snapcast/externals
git submodule update --init --recursive
sudo apt-get install build-essential
sudo apt-get install libasound2-dev libvorbisidec-dev libvorbis-dev libflac-dev alsa-utils libavahi-client-dev avahi-daemon
sudo apt-get install gcc
```

and when I try to run `make` from within the "snapcast" folder, I get the following:
```
make -C client
make[1]: Entering directory '/home/pi/snapcast/client'
/usr/bin/g++  -std=c++0x -Wall -Wno-unused-function -O3 -DASIO_STANDALONE -DVERSION=\"0.10.0\" -I. -I.. -I../externals/asio/asio/include -I../externals/popl/include -pthread -DHAS_OGG -DHAS_ALSA -DHAS_AVAHI -DHAS_DAEMON -c snapClient.cpp -o snapClient.o
snapClient.cpp:22:20: fatal error: popl.hpp: No such file or directory
 #include "popl.hpp"
                    ^
compilation terminated.
Makefile:68: recipe for target 'snapClient.o' failed
make[1]: *** [snapClient.o] Error 1
make[1]: Leaving directory '/home/pi/snapcast/client'
Makefile:9: recipe for target 'client' failed
make: *** [client] Error 2
```

I have recently upgraded Jessie, but I doubt that would have any interference whatsoever.

Am I missing something? Is there something I'm doing wrong?

Thank you all for you help, it will be much appreciated!

Best regards,

Peter

**Comment by badaix** [comment]
were there any externals cloned after issuing this command `git submodule update --init --recursive`?
It looks like externals are missing. Do you have this directory `<snapcast>/externals/popl/include`?

**Comment by pbocsak** [comment]
Hi, 

Wow! That was a quick reply! Thanks!

I did run it before. If I run it now, I get:
`No submodule mapping found in .gitmodules for path 'externals/vorbis'`
That's it.

`<snapcast>/externals/popl`

however is empty. How can I populate it with the required files?

**Comment by twenta** [comment]
Is there a specific reason, why you compile the source code instead of using the released packages https://github.com/badaix/snapcast/releases/latest and install via sudo dpkg -i 
Just pointing this out because you said that you are a newbie...

**Comment by pbocsak** [comment]
I've compiled some other programs before, so I figured that this was the way to go. I did `wget` the dpkg and it worked out great! Thanks! Now off to configuration!

However, for my own knowledge, could you explain why is it that I didn't get the whole source code? Why is it that parts of it (in this instance popl) were missing?

Thank you!

**Comment by badaix** [comment]
should be fixed now. Seems that I didn't completely remove the `vorbis` submodule.
Thanks for the hint
