### ISSUE TITLE
"Wrong SamplingRate" only with 4.x Android Clients

### ISSUE THREAD

**Issue by drdownload** [badaix/snapcast#136]
I have on a 4.4 Tablet and a 4.2 Radio the same Problem: It doesnt take the 48000 stream and errors with "stream not in native sample rate" and skips out after some seconds.

No problem with a device running 5.1.

**Comment by 1337sup3rh4x0r** [comment]
I am getting the same problem on an old Asus Transformer tf101 tablet running Android 6.0.1.

I think it has to do with the audio chipset or something, more than with the OS version.

**Comment by badaix** [comment]
Hi,

Snapcast doesn't skip out on purpose. 
While porting to Android, I figured that my test devices had hard times to keep the audio in sync. It's even worse when the display is switched off (the device will enter some sleep mode and snapclient is pushed into the background, getting less CPU. Yes, there is a CPU wakelock and a WiFi wakelock active during playback, but doesn't really help). 
Changing the sample rate from 44.1kHz to 48kHz solved the problem for all of my devices (Samsung Galaxy S5, Nexus 7 2013 and Amazon fire box).
It seems that Android tries to apply some resampling for non-DAC-native sample rates, and this resampling seems to be quite bad.
Therefor I've added the warning window in the App.

When I did the Android port I found some similar bug reports about some popular Apps. I cannot find the link now, but in the source code is a link to [stackoverflow](http://stackoverflow.com/questions/35730050/android-with-nexus-6-how-to-avoid-decreased-opensl-audio-thread-priority-rela?rq=1) with a discussion about this topic.

**Comment by drdownload** [comment]
The strange thing is: 
My Output is resampled by mopidy to 48000 and also snapcast is set to 48000.

However on 4.x Android, the error stream not in native sample rate is raised. This error doesnt come up on 5.x,

**Comment by badaix** [comment]
But your native sample rate is 44100?
You can switch Mopidy and Snapcast to use 44100

**Comment by drdownload** [comment]
the device sampling rate or the source I play in mopidy?

**Comment by badaix** [comment]
mopidy's output should be configured to 44100, as well as the sampleformat for the pipe, so that the Android can operate at 44.1kHz

**Comment by drdownload** [comment]
hi, with 44100 I get the error message on every android client. I assume since 48000 is the default this message is hardcoded.
