### ISSUE TITLE
Precompiled Raspberry Pi Version

### ISSUE THREAD

**Issue by 1337sup3rh4x0r** [badaix/snapcast#14]
Hi badaix,
I really like your project here! I think the best deployment of this would be within a minimalistic tinycore linux on a raspberry pi. This way very quick boot times could be achieved compared to a full-blown raspian and the risk of damaging the sd-card by simply cutting the power is zero. I have been trying to build such an image, but I didn't succeed in compiling this on the tinycore system. Also my knowledge is too limited to successfully cross-compile this on a different system myself.

Would it be possible for you to provide a precompiled arm version for the raspberry? I would then go ahead and try to put together an image that can be used for raspy clients.

**Comment by badaix** [comment]
Hi,
I'm planning to add pre-build Debian packages to the releases for the mayor architectures. The dpkg should also take care about the init.d/systemd setup.
I hope that I manage to set this up during the upcoming holidays.

**Comment by badaix** [comment]
The [latest release](https://github.com/badaix/snapcast/releases/latest) now contains `.deb` files for AMD64 and ARM. 
You can easily extract the binaries from the .deb files with `ar -x <FILE.deb>` or `dpkg -x <FILE.deb>`

**Comment by m-kloeckner** [comment]
Hi 1337sup3rh4x0r,
I created a PiCorePlayer extension for snapclient. Check the below repository for more info. This should be what you are looking for.

https://github.com/m-kloeckner/snapcast-tcz
