### ISSUE TITLE
Snapclient sometimes starts muted

### ISSUE THREAD

**Issue by axelsimon** [badaix/snapcast#140]
Hi,
(just realised there actually were 2 different issues, so I'm opening 2 issues)

First of all, I'd like to say this may very well be a bad configuration on my part, but I've looked it over many times and can't find any error in the way this setup is configured.

On this computer (192.168.0.7) I have snapserver + snapclient and a pulesaudio sink configured (using `pacmd load-module module-pipe-sink file=/tmp/snapfifo sink_name=Snapcast`). I've told Clementine to play to the Snapcast sink using pavucontrol.

As I have another computer on the network also running a Snapserver (192.168.0.2), I start snapclient with `-h localhost`.

Sometimes, this works fine and the music is played on the local speakers, via snapclient.
But most of the time, I get no sound. However, pavucontrol shows the sink is active and also shows snapclient outputting sound, as seen here:
![screenshot from 2016-11-24 13 10 59](https://cloud.githubusercontent.com/assets/1172256/20598618/22c70e5a-b24a-11e6-82aa-9d2c63e9c146.png)

The other clients on the network don't have problem playing.

Now, I've just understood this part of the problem: for some reason, snapclient sometimes starts muted, as shown by the command line output:
`[out] ServerSettings - buffer: 1000, latency: 0, volume: 81, muted: **1**`
However, this output isn't shown when snapclient is started automatically, which doesn't help.

(On that note, are there logs one can check? AFAICT, I can only see them on systems using systemd, via `journalctl -u snapclient`)

In the end I was able to understand and fix this problem by looking at the Android app's client list, and unmuting there.

Is there a reason a client would start muted? This was driving me a little crazy I must say.

Thanks

**Comment by badaix** [comment]
I just noticed that there might be the chance that during shutdown the server does not store the current config to disk. Maybe in the server's persistent config on disk the client is muted and this information is not updated.
Can you try out the develop branch? There the config is explicitly stored during server shutdown.

You can also use the master branch and add in `server/snapServer.cpp` in line 181:
````
Config::instance().save();
````

**Comment by axelsimon** [comment]
It hasn't happened to me since, it looks like a one-off, sorry. I can try the develop branch if it happens again or patch `server/snapServer.cpp` if I see this again.
But given I've upgraded the OS (Ubuntu 14.04 --> 16.04) that has also changed the environment.
I'll update this issue in any case.
