### ISSUE TITLE
endlessly logging [err] (PipeStream) Exception: end of file

### ISSUE THREAD

**Issue by quantenschaum** [badaix/snapcast#142]
When nothing is fed into the source pipe, snapserver endlessly logs

```
[err] (PipeStream) Exception: end of file
```

which causes the log to be filled with useless information. Would be nice, if this was logged once, and then silently ignored.

**Comment by quantenschaum** [comment]
This happens with mopidy, when it is stopped (not playing), but does not happen with mpd (when stopped).

Mpd seems to hold the pipe open, but does not feed data into it, when stopped/paused, whereas mopidy closes it, leading to this end of file exception. Snapserver should handle this more gracefully.

**Comment by badaix** [comment]
I noticed this also two days ago. It happens on an empty pipe. I will avoid this repeated logging in the next version.

**Comment by badaix** [comment]
done: 8cf069642d

**Comment by mbrgm** [comment]
@quantenschaum If this solves your problem, could you close the issue?

**Comment by quantenschaum** [comment]
I tried Version 0.10.0. It's not fixed there.

**Comment by badaix** [comment]
I tried version 0.11.0-beta-1. I only see the exception once?!?

**Comment by quantenschaum** [comment]
Yes! In 0.11.0-beta the issue does not occur anymore. Thanks.
