### ISSUE TITLE
Small OS for Raspberry Zero Clients

### ISSUE THREAD

**Issue by bjwelker** [badaix/snapcast#143]
This is a feature request ;) @badaix 
Issn´t it possible to build a small Distri for the Raspberry Zero so more people without the knowledge about Linux and so on can use Snapcast at home ? I think snapcast is enough for the most ppl not everyone needs sonos and snapcast works perfectly.

**Comment by badaix** [comment]
Hi, I also think that it would be cool to have a small distri. 
But this is out of scope now (at least for me. Contributions are always welcome). 
Even with a preconfigured distribution you can only serve the nerds and geeks who are knowing that a Raspberry Pi is not food and know how to flash an SD card, setup a WiFi on a Linux console, ...
Regarding the WiFi: it would be an interesting project to build some WiFi-setup-over-BT-framework.
A distribution for Raspi 3 (with build-in BT module) could be paired with a smartphone to get the WiFi-SSID and password pushed from an app.
Next problem is the MPD setup/fine-tuning. Maybe for a prebuild distribution it would be ok to have Spotify, AirPlay and UPnP. 
Easiest one: A Snapcast Android server that could be installed on FireTV, but it's hard run something like mpd on Android or to redirect Android audio (only possible on some rooted devices).

Snapclients are easy - they only have the problem of the WiFi configuration.

BTW: It seems that there are [wireless speakers](https://air.axiomaudio.com/) that are using Snapcast:
https://www.axiomaudio.com/boards/ubbthreads.php/topics/419543/Does_the_AA_use_Snapcast_for_s

**Comment by macmpi** [comment]
Volumio2 will provide a decently small & music oriented distribution when snapcast is fully integrated in it I guess...
It seems in the plan: can't wait for that!

**Comment by axelsimon** [comment]
Has anyone tried DietPi? it seems to target this sort of use case.

**Comment by bjwelker** [comment]
Just try it on a Raspberry Zero.
Boot fast and you can use the .deb package so no need for recompile or packing like piCore.
Maybe a small Webinterface to switch sound output and set WLAN and Hostname and this can be a nice Client OS

**Comment by badaix** [comment]
sounds promising :smiley: 

![DietPi](https://camo.githubusercontent.com/205178335c1d05ef19c328766140f0254cacdd8a/687474703a2f2f6469657470692e636f6d2f696d616765732f6469657470692d6c6f676f5f626c61636b5f3135302e706e67)

**Comment by 1337sup3rh4x0r** [comment]
What about your efforts of using piCore @bjwelker ?
Did you experience any downsides? 
I have a couple of piCore based Snapcast clients running on some pis in my house and it is all working rather good!

I like the idea of the system not using the SD at all card after boot and the extremely fast boot time

**Comment by bjwelker** [comment]
@1337sup3rh4x0r no not any downsides only one maybe that you have to build a new tcz everytime for the clients. Not that fast like the .deb you can get here and install it.
I have 2 piCore Snapclients running, build a webinterface and a easy install script for it but maybe i want something less time consuming ...

For what i have read the DietPi issnt using the SD Card all the time too.

**Comment by badaix** [comment]
Just a high level comment on this: a rock solid system should mount the sdcard read-only

**Comment by bjwelker** [comment]
I have no Clou how i Can make the Image feom picore with snapcast build in :-(
I Can make the tcz and the Webinterface but not the Image....

**Comment by P-D-G** [comment]
Maybe a good starting point would be [Buildroot](https://buildroot.org/). Main difficulties would be adding snapcast in the application tree and offering easy network configuration. Bonus would be that the solution could be compiled on all platforms supported by buildroot.

**Comment by bjwelker** [comment]
Maybe @nickaknudson Can Show how to make a Small Client Image with his pull request for buildroot.

**Comment by nickaknudson** [comment]
Buildroot supports raspberry pi zero out of the box:

https://git.busybox.net/buildroot/tree/board/raspberrypi/readme.txt#n27

Just shallow clone buildroot from the latest release tag:

    BUILDROOT_VERSION=2016.11.2
    git clone --branch $BUILDROOT_VERSION --depth=1 git://git.buildroot.net/buildroot

And then run make:

    cd buildroot
    make raspberrypi0_defconfig

If that is successful then follow my instructions to integrate Snapcast:

https://github.com/badaix/snapcast/blob/master/doc/build.md#buildroot-cross-compile

**Comment by bjwelker** [comment]
@nickaknudson did you use it as Client or Server ?
For Client i think you neues to add alsa and some Soundard drivers

**Comment by nickaknudson** [comment]
I've not actually tried it - just trying to give buildroot noobs a place to start.

I may have time to try it later this week and if so can add it to the guide.

**Comment by bjwelker** [comment]
That would be very nice. Then WE Can build very fast clients

**Comment by nickaknudson** [comment]
It builds for raspberry pi.

Tested on raspberry pi zero.

https://github.com/nickaknudson/snapcast-pi

**Comment by bjwelker** [comment]
Sorry I had no Time to test but I will do

**Comment by badaix** [comment]
last weekend I managed to merge some PRs, especially #212 that added CMake support. 
Great thanks to @joerg-krause !
Based on that, it was easy to make a first buildroot integration "[SnapOS](https://github.com/badaix/snapos)"
Feel tree to try it out. I'm happy about your feedback!

**Comment by palitu** [comment]
Great!  This will make life a bit easier for many single nodes!

**Comment by jaecksch** [comment]
Thanks to @badaix for his great work for snapcast as well as for snapos. I tried it it works fine. Boot time to audible audio is about 20sec. I'm also trying around with buildroot for a while to build a simple client system for snapclients. If you are interested please have a look to [snapcastbox](http://www.github.com/jaecksch/snapcastbox).

**Comment by 1337sup3rh4x0r** [comment]
Is it also planned to extend the support for SnapOS to OpenWRT/LEDE capable devices?

**Comment by nickaknudson** [comment]
You should consolidate changes between these two folders:

- https://github.com/badaix/snapos/tree/master/buildroot-external/package/snapcast
- https://github.com/badaix/snapcast/tree/master/buildroot/package/snapcast.

Right now you have duplicated code.

**Comment by badaix** [comment]
@1337sup3rh4x0r I've created an openwrt directory with a Makefile for the `snapcast` package in the SnapOS project. It will need some cleanup and some more dependencies and it should switch from using make to cmake. 

@nickaknudson fully agree, it's work in progress. Thanks a lot for your contributions to the buildroot support!

**Comment by Sieboldianus** [comment]
Wanted to add: I had to remove `alsa-lib` from `snapcast.mk` in order to `make` with buildroot. Otherwise, I got a [dependency warning](https://github.com/maximeh/buildroot/blob/master/Makefile#L549)

> alsa-lib is in the dependency chain of snapcast that has added it to its _DEPENDENCIES variable without selecting it or depending on it from Config.in

Afterwards, build worked!

**Comment by foxy82** [comment]
Sorry for posting on an old topic but not an easy way to pass the info on.

I've raised a PR against DietPi to add snapcast client as one of their standard software packages: https://github.com/MichaIng/DietPi/pull/4465

If you want a small distro for a Pi Zero W but are intimidated by the SnapOS building then that might be a good compromise.
