### ISSUE TITLE
How can I listen to different music in different rooms?

### ISSUE THREAD

**Issue by vtec83** [badaix/snapcast#147]
I don't understand how I should set up snapсast server to listen to different music in different room.
Can this setting?
Example:
music 1 -> kitchen
music 2 -> bedroom

Thanks and sorry for my best English

**Comment by bjwelker** [comment]
You need to start different pipes. If you want spotify Connect and MPD you can use
SNAPSERVER_OPTS="-d -s pipe:///tmp/snapspotify?name=Spotify&mode=read -s pipe:///tmp/snapvolumio?name=Volumio&mode=read"
Then you can put the Players via Android app into the different Rooms.

**Comment by vtec83** [comment]
Thank you, this is understandable.

**Comment by vtec83** [comment]
Thank you, this is understandable.
Is it possible to use only MPD? Еxample:
mpd -> music 1 -> kitchen
mpd -> music 2 -> bedroom
Maybe I need to use two MPD daemon on different ports?

Is it possible to listen to music with the android, bypassing the MPD?

**Comment by bjwelker** [comment]
Multiple streams out of one MPD is not possible you need a MPD for every room if the rooms should run different music.
MPD1 -> Music -> kitchen
MPD2 -> other music -> bedroom

What did you mean with listen to music on android ? You mean the snapcast client for android ?

**Comment by vtec83** [comment]
If i need a MPD for each room, then snapсast server too? Or I need to use two MPD daemon on different ports and config?

> What did you mean with listen to music on android ? You mean the snapcast client for android?
No, if the music is on android phone locally, how can I play it? (It may perhaps let flow as an example chromcast or air play?)

**Comment by badaix** [comment]
To play music from Android, I suggest to use the UPnP plugin for mpd:

```
$ apt-cache search upmpd
upmpdcli - UPnP Media Renderer front-end to MPD, the Music Player Daemon
```
It's not as general as Chromecast, but AFAIK there is no Chromecast emulator available for Linux. Airplay is running quite well in Snapcast, but it's not supported by Android.

You need one Snapserver and several MPDs, each one playing the audio into a different fifo file.

**Comment by pbros** [comment]
If your phone is rooted, you can use AirAudio (https://play.google.com/store/apps/details?id=eu.airaudio&hl=en) to stream your Android device's audio using AirPlay. I've been using it with a Nexus7 (2013) and it works very well with snapcast
