### ISSUE TITLE
Android Client doenst reconnect after Server restart

### ISSUE THREAD

**Issue by drdownload** [badaix/snapcast#151]
I have seen the following behaviour in all android versions:

I restart the snapserver and the clients are "blinking" in the android snapcast app. Also no audio is played. If I start and stop within the app everything is fine again.

Android 4.2/4.4/6.0 was used.

**Comment by 1337sup3rh4x0r** [comment]
I can confirm this. The same seems to happen if i have a wifi drop due to some energy saving functions in android.
I currently have to manually restart the app then.
It would be great if the app could handle this itself so the android phone could be burrieds someplace behind the speaker forever :)

**Comment by axelsimon** [comment]
May or may not be related but I do see some cases where long-running clients need to be manually restarted after a while (say, a couple of days). I'll grab the error next time it happens, currently `journalctl -u snapcast` only goes back to earlier today, for some reason 😕 (`Logs begin at Tue 2016-12-13 15:57:42 CET`)

**Comment by drdownload** [comment]
Maybe its related to this messages before it crashed (snapserver crashes quiete a lot on arch)

`Dez 18 12:08:04 archmini snapserver[17107]: Exception in StreamSession::reader(): read_some: End of file
Dez 18 12:08:05 archmini snapserver[17107]: StreamServer::NewConnection: 10.0.0.237
Dez 18 12:08:05 archmini snapserver[17107]: StreamServer::NewConnection: 10.0.0.237
Dez 18 12:08:05 archmini snapserver[17107]: received message of type 17735 to large: 808333361
Dez 18 12:08:05 archmini snapserver[17107]: received message of type 17735 to large: 808333361
Dez 18 12:08:05 archmini snapserver[17107]: StreamServer::NewConnection: 10.0.0.237
Dez 18 12:08:05 archmini snapserver[17107]: received message of type 17735 to large: 808333361
Dez 18 12:08:06 archmini systemd[1]: snapserver.service: Main process exited, code=killed, status=6/ABRT`

**Comment by drdownload** [comment]
This issue exists no matter what server (arch/debian) I use for snapcast. Also the Android Client seems to reconnect but never manages to. "grey blinking" 

Also there is the version of this error with not even "grey blinking" but real offline.
