### ISSUE TITLE
Clear fifo

### ISSUE THREAD

**Issue by drdownload** [badaix/snapcast#152]
Im Not sure if its an snapcast or mopidy Thing.

If i Hit stop Audio still plays on for 2 seconds.

Is there a way to avoid this in Kombination with mopidy?

**Comment by unimatrix27** [comment]
also, if you stop mopidy, stream status stays as playing, while it changes to idle when you hit pause in mopidy. might be related.

**Comment by ismailof** [comment]
There is an open [issue on mopidy](https://github.com/mopidy/mopidy/issues/1566) which can also be related to this. Not sure if it's because of mopidy itself or gstreamer filesink send to a fifo.
BTW I can confirm this behaviour too.

**Comment by drdownload** [comment]
For the record, I managed to get rid of most of the delays by using pulseaudio in between. > mopidy > pulseaudio > fifo

**Comment by nimonimonimo** [comment]
This solved similar error for me: https://unix.stackexchange.com/questions/503111/group-permissions-for-root-not-working-in-tmp
