### ISSUE TITLE
parse errors in json

### ISSUE THREAD

**Issue by drdownload** [badaix/snapcast#154]
Hi, I'm running snapcast on an antegos arch machine, and it works more or less (a bit unstable) - however In the json are always strange entries at the top:

{"error":{"code":-32700,"message":"parse error - unexpected 'G'"},"id":null,"jsonrpc":"2.0"}
{"error":{"code":-32700,"message":"parse error - unexpected 'H'"},"id":null,"jsonrpc":"2.0"}
{"error":{"code":-32700,"message":"parse error - unexpected 'C'"},"id":null,"jsonrpc":"2.0"}
{"error":{"code":-32700,"message":"parse error - unexpected 'C'"},"id":null,"jsonrpc":"2.0"}
{"error":{"code":-32700,"message":"parse error - unexpected 'U'"},"id":null,"jsonrpc":"2.0"}
{"error":{"code":-32700,"message":"parse error - unexpected 'U'"},"id":null,"jsonrpc":"2.0"}
{"error":{"code":-32700,"message":"parse error - unexpected 'A'"},"id":null,"jsonrpc":"2.0"}
{"error":{"code":-32700,"message":"parse error - unexpected 'A'"},"id":null,"jsonrpc":"2.0"}
{"error":{"code":-32700,"message":"parse error - unexpected 'A'"},"id":null,"jsonrpc":"2.0"}

and my only testroom:
SNAPSERVER_OPTS="-d -s pipe:///tmp/snapfifo1?name=Wohnzimmer&sampleformat=44100:16:2&codec=ogg"

**Comment by drdownload** [comment]
Maybe its all related and this should be viewed in connection with #151

**Comment by drdownload** [comment]
Dez 20 20:17:10 archmini snapserver[18347]: Exception in ControlSession::reader(): write: Broken pipe
Dez 20 20:17:10 archmini snapserver[18347]: Exception in ControlSession::reader(): write: Broken pipe

**Comment by drdownload** [comment]
I tried snapcast-.10 on arch and debian both in a virtualbox (bridged netwok) but its with I get the broken pipe messages when trying to pull the json and every second a end of file error

**Comment by badaix** [comment]
what json client are you using?
Do you have the messages that are causing the parse errors?

**Comment by drdownload** [comment]
I moved away from arch to debian, message is gone
