### ISSUE TITLE
Snapserver crashes when loading JSON in Browser (port 1705)

### ISSUE THREAD

**Issue by drdownload** [badaix/snapcast#163]
Jän 14 19:49:11 debianmini snapserver[15248]: Session inactive. Removing
Jän 14 19:49:13 debianmini snapserver[15248]: Exception in StreamSession::reader(): read_some: End of file
Jän 14 19:49:14 debianmini snapserver[15248]: StreamServer::NewConnection: 10.0.0.178
Jän 14 19:49:14 debianmini snapserver[15248]: received message of type 17735 to large: 808333361

SNAPSERVER_OPTS="-d -s pipe:///tmp/pulsefifo_1?name=Wohnzimmer&sampleformat=48000:16:2&codec=ogg&mode=read \
                    -s pipe:///tmp/pulsefifo_2?name=Badezimmer&sampleformat=48000:16:2&codec=ogg&mode=read"

**Comment by badaix** [comment]
What?
