### ISSUE TITLE
please add changelog

### ISSUE THREAD

**Issue by treaki** [badaix/snapcast#167]
from the time i have installed snapcast to steam music to my kitchen to now it has changed from version 0.7 to 0.10, but i dont know what has changed

could you add a changelog file?

thanks in advance

**Comment by twenta** [comment]
You can see the important changes logged here:
https://github.com/badaix/snapcast/releases

**Comment by badaix** [comment]
Same changelog can be found here:
https://github.com/badaix/snapcast/blob/master/client/debian/changelog
and here:
https://github.com/badaix/snapcast/blob/master/server/debian/changelog
