### ISSUE TITLE
Install on OpenWRT TL-WR710N

### ISSUE THREAD

**Issue by 1337sup3rh4x0r** [badaix/snapcast#168]
Hi there,
I got myself an OpenWRT TL-WR710N after reading that @m-kloeckner had some good experience with this device. I have hardware version 2.1

I installed OpenWRT on it (latest trunk from here: https://downloads.openwrt.org/snapshots/trunk/ar71xx/generic/openwrt-ar71xx-generic-tl-wr710n-v2.1-squashfs-factory.bin) and then tried to install the snapclient:

    opkg update
    opkg install snapclient_0.10.0_ar71xx.ipk

on the first try, it started installing a couple of dependencies and after being halfway through aborted that, reporting to be "Out of memory".

So I rebooted and ran the install snapclient command again, this time it went through without a problem

However I can't run snapclient now. It doesn't start on boot, nothing happens when I run `/etc/init.d/snapclient start` 

Trying to run it manually:

    root@OpenWrt:~# snapclient
    -ash: snapclient: not found

but:

    root@OpenWrt:~# which snapclient
    /usr/bin/snapclient

Did I forget something or why is this not running?

I uninstalled  and reinstalled different versions of snapclient a couple of times but to no avail.

Why ist this not running? Might this be due to the memory error during first install that some dependencies are misconfigured?

Please Help :)

**Comment by 1337sup3rh4x0r** [comment]
I reset the device to factory defaults and started setup from scratch.

This time I manually installed all dependencies in advance, paying close attention to not running out of memory:

	opkg update
	# opkg install libc # already present
	opkg install libstdcpp
	echo 3 > /proc/sys/vm/drop_caches
	opkg install libavahi-client
	echo 3 > /proc/sys/vm/drop_caches
	opkg install libatomic
	echo 3 > /proc/sys/vm/drop_caches
	opkg install libogg
	echo 3 > /proc/sys/vm/drop_caches
	opkg install libflac
	echo 3 > /proc/sys/vm/drop_caches
	opkg install alsa-lib
	echo 3 > /proc/sys/vm/drop_caches
	opkg install libvorbisidec
	echo 3 > /proc/sys/vm/drop_caches
	opkg install snapclient_0.10.0_ar71xx.ipk

sadly, the result is still the same:

**Comment by 1337sup3rh4x0r** [comment]
I read your build instructions for OpenWRT. If the .ipk file from your releases was built after those instructions, they were propably built for 15.05 so the binary is not recognized by my system.
I might be on to something here ;)

I will set up the build environment now to see if I can build it for Designated Driver.

**Comment by 1337sup3rh4x0r** [comment]
Do I really need to go through the whole building process for the system image before I can build snapcast? 

Looks like that will take a while ...

**Comment by 1337sup3rh4x0r** [comment]
The build process goes through without messages:

	user@ubuntu:~/OpenWrtBuildSystem/openwrt$ make package/sxx/snapcast/clean
	 make[1] package/sxx/snapcast/clean
	 make[2] -C package/sxx/snapcast clean
	user@ubuntu:~/OpenWrtBuildSystem/openwrt$ make package/sxx/snapcast/compile
	 make[1] package/sxx/snapcast/compile
	 make[2] -C package/libs/toolchain compile
	 make[2] -C package/firmware/linux-firmware compile
	 make[2] -C package/firmware/prism54-firmware compile
	 make[2] -C package/kernel/linux compile
	 make[2] -C feeds/packages/libs/alsa-lib compile
	 make[2] -C feeds/packages/libs/expat compile
	 make[2] -C feeds/packages/utils/dbus compile
	 make[2] -C package/libs/gettext-full host-compile
	 make[2] -C feeds/packages/libs/gdbm compile
	 make[2] -C feeds/packages/libs/intltool host-compile
	 make[2] -C feeds/packages/libs/libdaemon compile
	 make[2] -C feeds/packages/libs/avahi compile
	 make[2] -C feeds/packages/libs/avahi compile
	 make[2] -C feeds/packages/libs/avahi compile
	 make[2] -C feeds/packages/libs/avahi compile
	 make[2] -C feeds/packages/libs/avahi compile
	 make[2] -C feeds/packages/libs/flac compile
	 make[2] -C feeds/packages/libs/libogg compile
	 make[2] -C feeds/packages/libs/libvorbis compile
	 make[2] -C feeds/packages/libs/libvorbisidec compile
	 make[2] -C package/sxx/snapcast compile

However I can't find a snapclient.ipk under ``bin/ar71xx/packages/base/``

do I have to set something special in the ``make menuconfig`` dialog?

**Comment by 1337sup3rh4x0r** [comment]
I am advancing.
Slowly.

I figured out that the ``make menuconfig`` needs to be run AFTER the makefile and source directories of snapcast have been linked. 
Also in the menu, the snapcast package must be selected then.
I think this should be clarified in the wiki @badaix 

However if i try building after I did the above, I am finally getting an error:

<details>
    make[2]: Leaving directory '/home/user/OpenWrtBuildSystem/openwrt/feeds/packages/libs/libvorbisidec'
    make[2]: Entering directory '/home/user/OpenWrtBuildSystem/openwrt/package/sxx/snapcast'
    CFLAGS="-Os -pipe -mno-branch-likely -mips32r2 -mtune=34kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -iremap /home/user/OpenWrtBuildSystem/openwrt/build_dir/target-mips_34kc_musl-1.1.16/linux-ar71xx_generic/snapcast-0.10.0:snapcast-0.10.0 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro  -I/home/user/OpenWrtBuildSystem/openwrt/staging_dir/target-mips_34kc_musl-1.1.16/usr/include -I/home/user/OpenWrtBuildSystem/openwrt/staging_dir/target-mips_34kc_musl-1.1.16/include -I/home/user/OpenWrtBuildSystem/openwrt/staging_dir/toolchain-mips_34kc_gcc-5.3.0_musl-1.1.16/usr/include -I/home/user/OpenWrtBuildSystem/openwrt/staging_dir/toolchain-mips_34kc_gcc-5.3.0_musl-1.1.16/include/fortify -I/home/user/OpenWrtBuildSystem/openwrt/staging_dir/toolchain-mips_34kc_gcc-5.3.0_musl-1.1.16/include " CXXFLAGS="-Os -pipe -mno-branch-likely -mips32r2 -mtune=34kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -iremap /home/user/OpenWrtBuildSystem/openwrt/build_dir/target-mips_34kc_musl-1.1.16/linux-ar71xx_generic/snapcast-0.10.0:snapcast-0.10.0 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro  -I/home/user/OpenWrtBuildSystem/openwrt/staging_dir/target-mips_34kc_musl-1.1.16/usr/include -I/home/user/OpenWrtBuildSystem/openwrt/staging_dir/target-mips_34kc_musl-1.1.16/include -I/home/user/OpenWrtBuildSystem/openwrt/staging_dir/toolchain-mips_34kc_gcc-5.3.0_musl-1.1.16/usr/include -I/home/user/OpenWrtBuildSystem/openwrt/staging_dir/toolchain-mips_34kc_gcc-5.3.0_musl-1.1.16/include/fortify -I/home/user/OpenWrtBuildSystem/openwrt/staging_dir/toolchain-mips_34kc_gcc-5.3.0_musl-1.1.16/include " LDFLAGS="-L/home/user/OpenWrtBuildSystem/openwrt/staging_dir/target-mips_34kc_musl-1.1.16/usr/lib -L/home/user/OpenWrtBuildSystem/openwrt/staging_dir/target-mips_34kc_musl-1.1.16/lib -L/home/user/OpenWrtBuildSystem/openwrt/staging_dir/toolchain-mips_34kc_gcc-5.3.0_musl-1.1.16/usr/lib -L/home/user/OpenWrtBuildSystem/openwrt/staging_dir/toolchain-mips_34kc_gcc-5.3.0_musl-1.1.16/lib -znow -zrelro " make -j1 -C /home/user/OpenWrtBuildSystem/openwrt/build_dir/target-mips_34kc_musl-1.1.16/linux-ar71xx_generic/snapcast-0.10.0/. AR="mips-openwrt-linux-musl-gcc-ar" AS="mips-openwrt-linux-musl-gcc -c -Os -pipe -mno-branch-likely -mips32r2 -mtune=34kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -iremap /home/user/OpenWrtBuildSystem/openwrt/build_dir/target-mips_34kc_musl-1.1.16/linux-ar71xx_generic/snapcast-0.10.0:snapcast-0.10.0 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" LD=mips-openwrt-linux-musl-ld NM="mips-openwrt-linux-musl-gcc-nm" CC="mips-openwrt-linux-musl-gcc" GCC="mips-openwrt-linux-musl-gcc" CXX="mips-openwrt-linux-musl-g++" RANLIB="mips-openwrt-linux-musl-gcc-ranlib" STRIP=mips-openwrt-linux-musl-strip OBJCOPY=mips-openwrt-linux-musl-objcopy OBJDUMP=mips-openwrt-linux-musl-objdump SIZE=mips-openwrt-linux-musl-size CROSS="mips-openwrt-linux-musl-" ARCH="mips"  -C client TARGET=OPENWRT ENDIAN=BIG;
    make[3]: Entering directory '/home/user/OpenWrtBuildSystem/openwrt/build_dir/target-mips_34kc_musl-1.1.16/linux-ar71xx_generic/snapcast-0.10.0/client'
    mips-openwrt-linux-musl-g++ -Os -pipe -mno-branch-likely -mips32r2 -mtune=34kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -iremap /home/user/OpenWrtBuildSystem/openwrt/build_dir/target-mips_34kc_musl-1.1.16/linux-ar71xx_generic/snapcast-0.10.0:snapcast-0.10.0 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro  -I/home/user/OpenWrtBuildSystem/openwrt/staging_dir/target-mips_34kc_musl-1.1.16/usr/include -I/home/user/OpenWrtBuildSystem/openwrt/staging_dir/target-mips_34kc_musl-1.1.16/include -I/home/user/OpenWrtBuildSystem/openwrt/staging_dir/toolchain-mips_34kc_gcc-5.3.0_musl-1.1.16/usr/include -I/home/user/OpenWrtBuildSystem/openwrt/staging_dir/toolchain-mips_34kc_gcc-5.3.0_musl-1.1.16/include/fortify -I/home/user/OpenWrtBuildSystem/openwrt/staging_dir/toolchain-mips_34kc_gcc-5.3.0_musl-1.1.16/include   -std=c++0x -Wall -Wno-unused-function -O3 -DASIO_STANDALONE -DVERSION=\"0.10.0\" -I. -I.. -I../externals/asio/asio/include -I../externals/popl/include -DIS_BIG_ENDIAN -pthread -DNO_CPP11_STRING -DHAS_TREMOR -DHAS_ALSA -DHAS_AVAHI -DHAS_DAEMON -c snapClient.cpp -o snapClient.o
    In file included from ../externals/asio/asio/include/asio/detail/socket_types.hpp:61:0,
                     from ../externals/asio/asio/include/asio/impl/error_code.ipp:29,
                     from ../externals/asio/asio/include/asio/error_code.hpp:185,
                     from ../externals/asio/asio/include/asio/detail/throw_error.hpp:19,
                     from ../externals/asio/asio/include/asio/detail/impl/posix_tss_ptr.ipp:23,
                     from ../externals/asio/asio/include/asio/detail/posix_tss_ptr.hpp:74,
                     from ../externals/asio/asio/include/asio/detail/tss_ptr.hpp:27,
                     from ../externals/asio/asio/include/asio/detail/call_stack.hpp:20,
                     from ../externals/asio/asio/include/asio/impl/handler_alloc_hook.ipp:19,
                     from ../externals/asio/asio/include/asio/handler_alloc_hook.hpp:78,
                     from ../externals/asio/asio/include/asio/detail/handler_alloc_helpers.hpp:21,
                     from ../externals/asio/asio/include/asio/detail/bind_handler.hpp:19,
                     from ../externals/asio/asio/include/asio/detail/wrapped_handler.hpp:18,
                     from ../externals/asio/asio/include/asio/io_service.hpp:24,
                     from ../externals/asio/asio/include/asio/basic_io_object.hpp:19,
                     from ../externals/asio/asio/include/asio/basic_socket.hpp:20,
                     from ../externals/asio/asio/include/asio/basic_datagram_socket.hpp:20,
                     from ../externals/asio/asio/include/asio.hpp:19,
                     from clientConnection.h:27,
                     from controller.h:35,
                     from snapClient.cpp:23:
    /home/user/OpenWrtBuildSystem/openwrt/staging_dir/toolchain-mips_34kc_gcc-5.3.0_musl-1.1.16/include/sys/poll.h:1:2: warning: #warning redirecting incorrect #include <sys/poll.h> to <poll.h> [-Wcpp]
     #warning redirecting incorrect #include <sys/poll.h> to <poll.h>
      ^
    In file included from ../externals/asio/asio/include/asio/error_code.hpp:185:0,
                     from ../externals/asio/asio/include/asio/detail/throw_error.hpp:19,
                     from ../externals/asio/asio/include/asio/detail/impl/posix_tss_ptr.ipp:23,
                     from ../externals/asio/asio/include/asio/detail/posix_tss_ptr.hpp:74,
                     from ../externals/asio/asio/include/asio/detail/tss_ptr.hpp:27,
                     from ../externals/asio/asio/include/asio/detail/call_stack.hpp:20,
                     from ../externals/asio/asio/include/asio/impl/handler_alloc_hook.ipp:19,
                     from ../externals/asio/asio/include/asio/handler_alloc_hook.hpp:78,
                     from ../externals/asio/asio/include/asio/detail/handler_alloc_helpers.hpp:21,
                     from ../externals/asio/asio/include/asio/detail/bind_handler.hpp:19,
                     from ../externals/asio/asio/include/asio/detail/wrapped_handler.hpp:18,
                     from ../externals/asio/asio/include/asio/io_service.hpp:24,
                     from ../externals/asio/asio/include/asio/basic_io_object.hpp:19,
                     from ../externals/asio/asio/include/asio/basic_socket.hpp:20,
                     from ../externals/asio/asio/include/asio/basic_datagram_socket.hpp:20,
                     from ../externals/asio/asio/include/asio.hpp:19,
                     from clientConnection.h:27,
                     from controller.h:35,
                     from snapClient.cpp:23:
    ../externals/asio/asio/include/asio/impl/error_code.ipp: In member function 'virtual std::__cxx11::string asio::detail::system_category::message(int) const':
    ../externals/asio/asio/include/asio/impl/error_code.ipp:110:22: error: could not convert 'strerror_r(value, ((char*)(& buf)), sizeof (buf))' from 'int' to 'std::__cxx11::string {aka std::__cxx11::basic_string<char>}'
         return strerror_r(value, buf, sizeof(buf));
                          ^
    In file included from ../externals/asio/asio/include/asio/detail/impl/posix_tss_ptr.ipp:24:0,
                     from ../externals/asio/asio/include/asio/detail/posix_tss_ptr.hpp:74,
                     from ../externals/asio/asio/include/asio/detail/tss_ptr.hpp:27,
                     from ../externals/asio/asio/include/asio/detail/call_stack.hpp:20,
                     from ../externals/asio/asio/include/asio/impl/handler_alloc_hook.ipp:19,
                     from ../externals/asio/asio/include/asio/handler_alloc_hook.hpp:78,
                     from ../externals/asio/asio/include/asio/detail/handler_alloc_helpers.hpp:21,
                     from ../externals/asio/asio/include/asio/detail/bind_handler.hpp:19,
                     from ../externals/asio/asio/include/asio/detail/wrapped_handler.hpp:18,
                     from ../externals/asio/asio/include/asio/io_service.hpp:24,
                     from ../externals/asio/asio/include/asio/basic_io_object.hpp:19,
                     from ../externals/asio/asio/include/asio/basic_socket.hpp:20,
                     from ../externals/asio/asio/include/asio/basic_datagram_socket.hpp:20,
                     from ../externals/asio/asio/include/asio.hpp:19,
                     from clientConnection.h:27,
                     from controller.h:35,
                     from snapClient.cpp:23:
    ../externals/asio/asio/include/asio/error.hpp: At global scope:
    ../externals/asio/asio/include/asio/error.hpp:256:36: warning: 'asio::error::system_category' defined but not used [-Wunused-variable]
     static const asio::error_category& system_category
                                        ^
    ../externals/asio/asio/include/asio/error.hpp:258:36: warning: 'asio::error::netdb_category' defined but not used [-Wunused-variable]
     static const asio::error_category& netdb_category
                                        ^
    ../externals/asio/asio/include/asio/error.hpp:260:36: warning: 'asio::error::addrinfo_category' defined but not used [-Wunused-variable]
     static const asio::error_category& addrinfo_category
                                        ^
    ../externals/asio/asio/include/asio/error.hpp:262:36: warning: 'asio::error::misc_category' defined but not used [-Wunused-variable]
     static const asio::error_category& misc_category
                                        ^
    Makefile:74: recipe for target 'snapClient.o' failed
    make[3]: *** [snapClient.o] Error 1
    make[3]: Leaving directory '/home/user/OpenWrtBuildSystem/openwrt/build_dir/target-mips_34kc_musl-1.1.16/linux-ar71xx_generic/snapcast-0.10.0/client'
    Makefile:136: recipe for target '/home/user/OpenWrtBuildSystem/openwrt/build_dir/target-mips_34kc_musl-1.1.16/linux-ar71xx_generic/snapcast-0.10.0/.built' failed
    make[2]: *** [/home/user/OpenWrtBuildSystem/openwrt/build_dir/target-mips_34kc_musl-1.1.16/linux-ar71xx_generic/snapcast-0.10.0/.built] Error 2
    make[2]: Leaving directory '/home/user/OpenWrtBuildSystem/openwrt/package/sxx/snapcast'
    package/Makefile:196: recipe for target 'package/sxx/snapcast/compile' failed
    make[1]: *** [package/sxx/snapcast/compile] Error 2
    make[1]: Leaving directory '/home/user/OpenWrtBuildSystem/openwrt'
    /home/user/OpenWrtBuildSystem/openwrt/include/toplevel.mk:192: die Regel für Ziel „package/sxx/snapcast/compile“ scheiterte
    make: *** [package/sxx/snapcast/compile] Fehler 2
</details>

I think the most important thing is this line:

    ../externals/asio/asio/include/asio/impl/error_code.ipp:110:22: error: could not convert 'strerror_r(value, ((char*)(& buf)), sizeof (buf))' from 'int' to 'std::__cxx11::string {aka std::__cxx11::basic_string<char>}'

Some googling tells me that this can be due to different versions of GCC being used but, I have no clue about how I should approach this.

Do I need to use a different asio source?

Any ideas?

**Comment by 1337sup3rh4x0r** [comment]
I had the wild idea to simply delete the asio folder form externals and do a new checkout of the current asio master branch.

After this, building went through without issues and snapcast is now running on my Router.

Now I just need to figure out why the USB soundcard is not recognized ...

**Comment by badaix** [comment]
I had to install some usb audio packages:

https://wiki.openwrt.org/doc/howto/usb.audio

> 3. install usb.essentials
> 4. install the packages kmod-usb-audio and kmod-sound-core for Kernel audio support and ALSA drivers
>

**Comment by 1337sup3rh4x0r** [comment]
Thanks!
I already did some reading in that but I want to feel more comfortable first with what I am doing before I flash something that I compiled myself, not fully understanding what I am doing onto my Router :)

**Comment by 1337sup3rh4x0r** [comment]
So if compiling for my WR710N v2.1 is done with exactly the same steps as for WR710N v2.0, can I then not as well just flash an image that somebody else compiled for that older version? :)

Or why would different images for each hardware version be supplied by the maintainers?

**Comment by 1337sup3rh4x0r** [comment]
I found a ready to go Chaos Calmer image for my device here:
http://dl.eko.one.pl/chaos_calmer/ar71xx/

On that I could indeed just install the mentioned kernel modules required for sound (I had thought those would need to be included during compilation)

So now everything is working fine and I am listening to music from my new client at this very moment.

@badaix: do you think it would make sense to write down for the wiki the steps to get to this working client?
I think at ~20€ this is a snapclient price that is hard to beat. And after all it wasn't all too hard if I would have known from the beginning :)

**Comment by openwrt-user** [comment]
Hi, thanks for the download link. How is the root password for login in ssh console? It's not empty.

**Comment by 1337sup3rh4x0r** [comment]
I can't find it in my notes here, but have you tried initially connecting via telnet? I think for chaos calmer the root PW is empty but SSH connection is refused for empty pws. So you would have to connect via telnet and then change PW to use SSH later. 
But I'm not sure, please check the openwrt wiki

**Comment by sixtyfive** [comment]
FWIW, 8 years further down the line: https://github.com/openwrt/packages/issues/23924
