### ISSUE TITLE
Issue with airplay input for snapcast

### ISSUE THREAD

**Issue by fallenicarus** [badaix/snapcast#169]
I have a pi3 which is running shairport and mopidy both along with snapcast. I am triyng to figure out how to get this setup so that I can stream whichever source (mopidy or shairport) I need via snapcast. 

I had tried using the pipe method, but that causes issues with lags and audio dropouts. The suggested method works by itself but I cant get mopidy to kick on when I play a stream. 

I have a few questions regarding getting both to run together:
- Can snapcast work with a already running shairport service? 
- Can I change the device name in the "airplay:///shairport-sync?name=Airplay[&devicename=Snapcast][&port=5000]" to whatever I want? 
- does the shairport service use the standard config file that I make for shairport? (asking in case I want to check out statistics and stuff)
- Is the best way to get both running together "-s airplay:///shairport-sync?name=Airplay[&devicename=Snapcast][&port=5000] -s pipe:///tmp/snapfifo?name=default" in the snapserver settings?

**Comment by fallenicarus** [comment]
Actually I realized I didnt configure shairport with the stdout option - I am working on that now. However I have a few questions - 
 -  will using the snapserver option mentioned in the airplay portion will allow me to run mopidy audio as well as shairport audio over snapserver?
 - in the options "airplay:///shairport-sync?name=Airplay[&devicename=Snapcast][&port=5000]" is the name=airplay supposed to be the name of the airplay service? and whats the device name supposed to be.

**Comment by fallenicarus** [comment]
So I finally figured out that the last bullet point corresponds to playing streams in zones (duh!) and was able to get this working. 

However, I am not able to run the snapcast server as a service. I can run the snapserver with the command mentioned in the last bullet point and everything works well. The moment I copy that command into the /etc/default/snapserver file, I cannot run the server. 
The SNAPSERVER_OPTS portion looks like: 
`SNAPSERVER_OPTS="-d -s pipe:///tmp/snapfifo?name=Mopidy -s airplay:///shairport-sync?name=SnapAirplay[&devicename=Snapcast][&port=5001]"`
The journalctl log looks like this:

> Jan 25 19:15:07 YouMadBro systemd[1]: Starting Snapcast server...
Jan 25 19:15:07 YouMadBro snapserver[2544]: Settings file: /var/lib/snapcast/server.json
Jan 25 19:15:07 YouMadBro snapserver[2544]: pipe:///tmp/snapfifo?name=Mopidy
Jan 25 19:15:07 YouMadBro snapserver[2544]: airplay:///shairport-sync?name=SnapAirplay[&devicename=Snapcast][&port=5001]
Jan 25 19:15:07 YouMadBro snapserver[2546]: daemon started
Jan 25 19:15:07 YouMadBro systemd[1]: Started Snapcast server.
Jan 25 19:15:07 YouMadBro snapserver[2546]: StreamServer::start: shairport-sync not found
Jan 25 19:15:07 YouMadBro snapserver[2546]: Exception: shairport-sync not found
Jan 25 19:15:07 YouMadBro snapserver[2546]: daemon terminated.
Jan 25 19:15:07 YouMadBro systemd[1]: snapserver.service holdoff time over, scheduling restart.
Jan 25 19:15:07 YouMadBro systemd[1]: Stopping Snapcast server...
Jan 25 19:15:07 YouMadBro systemd[1]: Starting Snapcast server...
Jan 25 19:15:07 YouMadBro snapserver[2557]: Settings file: /var/lib/snapcast/server.json
Jan 25 19:15:07 YouMadBro snapserver[2557]: pipe:///tmp/snapfifo?name=Mopidy
Jan 25 19:15:07 YouMadBro snapserver[2557]: airplay:///shairport-sync?name=SnapAirplay[&devicename=Snapcast][&port=5001]
Jan 25 19:15:07 YouMadBro snapserver[2559]: daemon started
Jan 25 19:15:07 YouMadBro systemd[1]: Started Snapcast server.
Jan 25 19:15:07 YouMadBro snapserver[2559]: StreamServer::start: shairport-sync not found
Jan 25 19:15:08 YouMadBro systemd[1]: snapserver.service holdoff time over, scheduling restart.
Jan 25 19:15:08 YouMadBro systemd[1]: Stopping Snapcast server...
Jan 25 19:15:08 YouMadBro systemd[1]: Starting Snapcast server...
Jan 25 19:15:08 YouMadBro snapserver[2568]: Settings file: /var/lib/snapcast/server.json
Jan 25 19:15:08 YouMadBro snapserver[2570]: daemon started
Jan 25 19:15:08 YouMadBro systemd[1]: Started Snapcast server.
Jan 25 19:15:08 YouMadBro snapserver[2568]: pipe:///tmp/snapfifo?name=Mopidy
Jan 25 19:15:08 YouMadBro snapserver[2568]: airplay:///shairport-sync?name=SnapAirplay[&devicename=Snapcast][&port=5001]
Jan 25 19:15:08 YouMadBro snapserver[2570]: StreamServer::start: shairport-sync not found
Jan 25 19:15:08 YouMadBro systemd[1]: snapserver.service holdoff time over, scheduling restart.
Jan 25 19:15:08 YouMadBro systemd[1]: Stopping Snapcast server...
Jan 25 19:15:08 YouMadBro systemd[1]: Starting Snapcast server...
Jan 25 19:15:08 YouMadBro snapserver[2578]: Settings file: /var/lib/snapcast/server.json
Jan 25 19:15:08 YouMadBro snapserver[2580]: daemon started
Jan 25 19:15:08 YouMadBro systemd[1]: Started Snapcast server.
Jan 25 19:15:08 YouMadBro snapserver[2578]: pipe:///tmp/snapfifo?name=Mopidy
Jan 25 19:15:08 YouMadBro snapserver[2578]: airplay:///shairport-sync?name=SnapAirplay[&devicename=Snapcast][&port=5001]
Jan 25 19:15:08 YouMadBro snapserver[2580]: StreamServer::start: shairport-sync not found
Jan 25 19:15:09 YouMadBro systemd[1]: snapserver.service holdoff time over, scheduling restart.
Jan 25 19:15:09 YouMadBro systemd[1]: Stopping Snapcast server...
Jan 25 19:15:09 YouMadBro systemd[1]: Starting Snapcast server...
Jan 25 19:15:09 YouMadBro snapserver[2588]: Settings file: /var/lib/snapcast/server.json
Jan 25 19:15:09 YouMadBro snapserver[2588]: pipe:///tmp/snapfifo?name=Mopidy
Jan 25 19:15:09 YouMadBro snapserver[2588]: airplay:///shairport-sync?name=SnapAirplay[&devicename=Snapcast][&port=5001]
Jan 25 19:15:09 YouMadBro snapserver[2590]: daemon started
Jan 25 19:15:09 YouMadBro systemd[1]: Started Snapcast server.
Jan 25 19:15:09 YouMadBro snapserver[2590]: StreamServer::start: shairport-sync not found
Jan 25 19:15:09 YouMadBro systemd[1]: snapserver.service holdoff time over, scheduling restart.
Jan 25 19:15:09 YouMadBro systemd[1]: Stopping Snapcast server...
Jan 25 19:15:09 YouMadBro systemd[1]: Starting Snapcast server...
Jan 25 19:15:09 YouMadBro systemd[1]: snapserver.service start request repeated too quickly, refusing to start.
Jan 25 19:15:09 YouMadBro systemd[1]: Failed to start Snapcast server.
Jan 25 19:15:09 YouMadBro systemd[1]: Unit snapserver.service entered failed state.

**Comment by fallenicarus** [comment]
I have been playing around with it and cant understand why the snapserver fails when I try to start it as a service but works when I use the same SNAPSERVER_OPTS string on the command line. Kind of giving up on this for now. Not sure what else to try. Any help here would be great!

**Comment by painlessjeff** [comment]
I don't know what error you get when the service fails but make sure the user you specify is the same that you log with.

**Comment by fallenicarus** [comment]
Issue was resolved based on help by @hechi ([Issue 467 on shairport sync](https://github.com/mikebrady/shairport-sync/issues/467)). 
His answer on there is copied below for reference incase someone else has this issue:

```
this is my systemd configuration

# cat /etc/systemd/system/multi-user.target.wants/snapserver.service

[Unit]
Description=Snapcast server
After=network.target

[Service]
EnvironmentFile=-/etc/default/snapserver
Type=forking
ExecStart=/usr/sbin/snapserver $SNAPSERVER_OPTS
PIDFile=/var/run/snapserver.pid

[Install]
WantedBy=multi-user.target
and here my snapcastserver config

# cat /etc/default/snapserver

# defaults file for snapserver

# start snapserver automatically?
START_SNAPSERVER=true

SNAPSERVER_OPTS='-d -s "pipe:///tmp/snapfifo?name=Mopidy&sampleformat=48000:16:2&codec=flac&mode=read" -s "airplay:///usr/bin/shairport-sync?name=Airplay&devicename=SnapcastAir&port=5000]"'
```
