### ISSUE TITLE
Only getting noise output

### ISSUE THREAD

**Issue by m-hearn** [badaix/snapcast#17]
client and server are connected, tested with /dev/urandom.

mopidy config is writing to /tmp/snapfifo, but only delivering noise.

starting and stopping the server audio in mopidy does start/stop noise at client end.

local client (on same server as mopidy) also produces the same issue.

[running on Pi2 server and PiB on client]
- tried upgrading to dev instance of mopidy - from 1.1.1 - no improvement

**Comment by badaix** [comment]
Hi,
what version of snapcast are you using? Any specific release? Master or develop branch?
Can you try to directly feed in a live radio station without any Mopidy or MPD: 
In a root shell (`sudo su`) on the server Pi do:
`wget -q -O - http://1live.akacast.akamaistream.net/7/706/119434/v1/gnl.akacast.akamaistream.net/1live |mpg123 -w - - > /tmp/snapfifo` 
You might need to install mpg123 (`sudo apt-get install mpg123`).

**Comment by nokianhunter** [comment]
Hi,
when I directly launch gst-launch-0.10 (which is used by mopidy) and pipe a musicfile to `/tmp/snapfifo` I only hear noise, but using gst-launch-1.0 fixes the problem.
Hopefully mopidy will switch to gstreamer-1.0 in the near future.

 ```gst-launch-0.10 filesrc location=~/sample.mp3 ! decodebin ! audioconvert ! audioresample ! filesink location=/tmp/snapfifo```

 ```gst-launch-1.0 filesrc location=~/sample.mp3 ! decodebin ! audioconvert ! audioresample ! filesink location=/tmp/snapfifo```

**Comment by maosuyun2009** [comment]
Hi, 
I have a wav file, I want to know, When I Test with command like "cat 123.wav > /tmp/snapfifo", I only get noise, I think snapclient just read pcm data from snapfifo, when i try to cat 123.wav to snapfifo, why can't play it?

**Comment by Lakritzator** [comment]
@maosuyun2009 this is a different thing as the initial ticket was created for.

You are mixing up PCM, a digital representation of audio, with WAV as a file format.
A WAV file (https://en.wikipedia.org/wiki/WAV) can contain PCM, but is not necessary
PCM.

It also would be very inefficient to have uncompressed audio in a WAV file, so currently a lot of them are compressed. And PCM is not compressed audio data!

Even if you have PCM in the WAV, you still have a header and this might cause horrible noise.

In short PCM != WAV!

**Comment by maosuyun2009** [comment]
@Lakritzator Thanks, In oss architechture, i always cat wav file to /dev/oss, so I just think i can do it like oss

**Comment by badaix** [comment]
@maosuyun2009 actually for "normal"  (containing PCM data) WAV-files cat will work. A requirement for the cat method is that the wave header size is a multiple of 4 (usually it's 44 bytes). Otherwise left/right and upper/lower bytes are mixed up and cause noisy audio.

**Comment by mielleman** [comment]
Found a solution. Working on Ubuntu 15.10 (Wili Werewolf), mopidy 2.0.0-1 (jessie), snapcast (git-master) with standard gst-launch-1.0

From my `/etc/mopidy/mopidy.conf` in the audio section:
`[audio]`
`output = audioresample ! audio/x-raw, format=S16LE ! audioconvert ! wavenc ! filesink location=/tmp/snapfifo`

**Comment by badaix** [comment]
added this to the Readme.md (3a4bfbd9fea302a5545e94d466be160618ef6f54)
