### ISSUE TITLE
LEDE support

### ISSUE THREAD

**Issue by sven3** [badaix/snapcast#170]
Unfortunately, Snapclient does not compile under current LEDE (OpenWrt fork). The error I get is:
>In file included from player/player.h:29:0,
>                 from player/alsaPlayer.h:22,
>                 from player/alsaPlayer.cpp:19:
>../common/log.h:29:24: error: expected initializer before '<<' token
> #define logO std::clog << kOut
>                        ^
>In file included from ../common/strCompat.h:10:0,
>                 from player/alsaPlayer.cpp:22:
>/home/buildd/lede/staging_dir/toolchain-mips_24kc_gcc-5.4.0_musl-1.1.16/mips-openwrt-linux-musl/include/c++/5.4.0/cmath:353:11: error: '::log' has not been declared
>   using ::log;
>           ^
>Makefile:74: recipe for target 'player/alsaPlayer.o' failed
>make[3]: *** [player/alsaPlayer.o] Error 1`

Is support for LEDE planned?

Or does anybody has a clue how to get around this error?

Thanks!
Sven

**Comment by nickaknudson** [comment]
Currently Snapcast doesn't compile under GCC 5.x

Try falling back to 4.9.x

**Comment by badaix** [comment]
@celevra successfully compiled for lede. Maybe the fix #203 will work for you too
I'm not aware of any compilation problems with GCC 5.x

**Comment by badaix** [comment]
this one should be fixed with #146. Please try again with the latest version (develop and master should compile now)

> In file included from ../common/strCompat.h:10:0,
from player/alsaPlayer.cpp:22:
/home/buildd/lede/staging_dir/toolchain-mips_24kc_gcc-5.4.0_musl-1.1.16/mips-openwrt-linux-musl/include/c++/5.4.0/cmath:353:11: error: '::log' has not been declared

**Comment by sven3** [comment]
Thank you very much @nickaknudson and @badaix, I will give it a try!

**Comment by sven3** [comment]
I can confirm that snapclient compiles like a charm using an unmodified LEDE 17.01. Thank you very much!!

**Comment by gsalvati** [comment]
@sven3  where do you use the Snapcast? Omega2?
How do I compile it on my pc to use on omega2?

**Comment by celevra** [comment]
i've build it for the onion omega2+
use this docker container for a build root:
https://community.onion.io/topic/1592/project-docker-omega2-sdk-for-cross-compilation-cmake-support

and use this instructions for building:
https://github.com/badaix/snapcast/blob/master/doc/build.md

**Comment by sven3** [comment]
@gsalvati I use snapclient on LEDE supported boards and build it using my own build system, according to the notes found here: https://github.com/badaix/snapcast/blob/master/doc/build.md#openwrtlede-cross-compile
