### ISSUE TITLE
Airplay Snapclient

### ISSUE THREAD

**Issue by DerGrafausB** [badaix/snapcast#172]
Hi,

is it possible to stream to airplay with the snapclient.
So it would be possible to use Multiroom, for example 2 apple TV.

Bye

Chris

**Comment by fallenicarus** [comment]
You need to look at installing shairport-sync and setup snapcast with the instructions as discussed here: https://github.com/badaix/snapcast/blob/master/doc/player_setup.md#airplay

**Comment by 1337sup3rh4x0r** [comment]
I think he might want to use airplay clients with snapserver.
That is not possible.

**Comment by s1lvester** [comment]
Nope. Not possible.

**Comment by HVPereira** [comment]
Hello I want to open this one, I am testing and I guess I am reaching somewhere please take a look if you build shairport-sync this way:
$ ./configure --with-alsa --with-avahi --with-ssl=openssl --with-metadata --with-soxr --with-systemv

You are able to give shairport-sync the following config:

general = {
  name = "S.A.R.A.H.";
  output_backend = "pipe";
};

metadata = {
  enabled = "yes";
  include_cover_art = "yes";
  pipe_name = "/tmp/shairport-sync-metadata";
}

sessioncontrol = {
  allow_session_interruption = "yes";
  session_timeout = 20;
}

pipe = {
  name = "/tmp/snapfifo";
  audio_backend_buffer_desired_length = 48000;
}

I will test this now

**Comment by joerg-krause** [comment]
Yes, this schould work for using AirPlay with Snapclient. However, the issue is about playing from Snapclient to an AirPlay client like AppleTV, which is not possible.
