### ISSUE TITLE
Tunein streams and mopidy on snapcast have audio hiccups

### ISSUE THREAD

**Issue by fallenicarus** [badaix/snapcast#179]
Has anyone noticed issues with Tunein streams buffering a lot or showing "sync" on the mopidy now playing screen instead of progress bar. I see this happening a lot more when playing audio via snapcast vs when playing streams through mopidy default audio sources.

**Comment by fallenicarus** [comment]
My setup is basically mopidy and airplay feeding into snapcast and have 2 receivers - one is on the server itself and one across the room. 
The snapserver_opt is 
```
'-d -s "pipe:///tmp/snapfifo?name=Mopidy&sampleformat=48000:16:2&codec=flac&mode=create" -s "airplay:///home/pi/shairport-sync/shairport-sync?name=Airplay&devicename=SnapcastAir&port=5000]" --streamBuffer 40'
```
The streambuffer 40 helps a bit with the hiccup issue but overall the issue still exists. There are actually 2 issues running together
 - one is where the tunein stream gets stuck on sync and will not play unless I go ahead and reload the stream all together. 
- other one is where tunein keeps running and every once in a while there are audio skips for a portion of a second (clearly audible and noticeable). 

The relevant portion of mopidy.conf is copied below:
```
[audio]
mixer = software
mixer_volume = 50
output = audioresample ! audioconvert ! audio/x-raw,rate=48000,channels=2,format=S16LE ! wavenc ! filesink location=/tmp/snapfifo
```

Any help on this would be great.

**Comment by hechi** [comment]
Hey @fallenicarus i dont have really drop outs but the music is looped :( but i am not sure if this is more a hardware wifi problem on my side. Do you have also wifi or ethernet devices?

**Comment by fallenicarus** [comment]
Hey @hechi  - looks like it was a problem with that particular installation? Maybe a result of too many things running at the same time on a pi3 - I have since tried moving onto a new pi 3 and redoing things and it looks like things are working better. I will keep playing around with this.

**Comment by hechi** [comment]
ok cool but did you use wifi or ethernet?

**Comment by fallenicarus** [comment]
This is done over wifi.

**Comment by hechi** [comment]
ok thx :)

**Comment by badaix** [comment]
any news on this? 
Ok to close or still an issue?

**Comment by hechi** [comment]
@fallenicarus still problems?

**Comment by fallenicarus** [comment]
Sorry for the delayed response... yeah i would close this. The most probable cause was running too many things on one Rpi - I havent had the issue after I moved the snapcast server and mopidy installs to a different pi3.
