### ISSUE TITLE
stream state remains "playing"

### ISSUE THREAD

**Issue by happyleavesaoc** [badaix/snapcast#180]
I have a named pipe that I play audio to, like this:
`ffmpeg -y -i <file.mp3> -f u16le -acodec pcm_s16le -ac 2 -ar 48000 /tmp/snapcast_pipe`

The problem is that the stream's state never changes back to `idle` after the server has consumed the pipe.

Possibly related to https://github.com/badaix/snapcast/issues/152

**Comment by badaix** [comment]
I tried to reproduce this. I get the following:
1. ffmpeg starts
2. the state changes from idle to playing
3. ffmpeg finishes and exits
4. state changes back to idle

**Comment by ashwinvandijk** [comment]
I've got the same problem with librespot. It always says "playing" no matter what I'm doing. Pausing in Spotify, disconnecting from librespot from within Spotify, or just killing librespot all doesn't work.

**Comment by badaix** [comment]
should be fixed in v0.18
