### ISSUE TITLE
May be unrelated [MPD?]

### ISSUE THREAD

**Issue by mu3en** [badaix/snapcast#182]
Pretty standard setup on Arch using MPD, MPD and Snapserver happen to be in an lxc machine, but reproduced in different hardware and in/out of lxc.
When switching tracks, manually, automatically, any way, sometimes [often or mostly], the sound output becomes terribly garbled static, the sound is still there, and still some distorted version of the stream.
Pausing and Unpausing the playback in MPD resets/solves the sound issue.
Confusing, but maybe stream handoff or stream formats aren't meshing? I've tweaked some of the settings in mpd output and the snapserver stream, but no luck so far.

#snap:
SNAPSERVER_OPTS="-d -s pipe:///tmp/fifo-snd.fifo?name=MPDSnap&sampleformat=44100
:16:2"

#mpd:
audio_output {
    type            "fifo"
    name            "fifo_snd"
    path            "/tmp/fifo-snd.fifo"
    format          "44100:16:2"
    mixer_type      "software"
}

maybe the -s bug was affecting, but feel free to rewrite the line if ever.

Using with 4 way bluetooth on 4 machines so far, aiming for a total 6, but struggling with android clients and may order some Pi if any recommendations.

**Comment by flesk** [comment]
give format  "48000:16:2" a try

**Comment by mu3en** [comment]
Hey Flesk. Thanks for the feedback.
I maybe set like that originally, and changed to 44100 because it was in the Snapcast docs examples versus the 48000 in the [ArchWiki] MPD docs.
In the meantime, as part of the evolving set up, moved Snapcast, along with MPD, out of LXC and onto physical host. Apart from de-containerizing, this also moved the music folder to a NFS mount instead of a bind mount in the container.
Not sure what if anything has changed about the setup, but for now (and the last fifteen minutes at least) and with the 48000 setting, working great. 
I'll make the same change on the LXC container and re-test.
I'm beginning to suspect it may have to do with the throughput off the hard-drive/buffer into the MPD stream that gets borked and Snapcast is not directly involved - GIGO.
However, it may be revealing an MPD side effect so it's worth figuring out a cleaner explanation just to make a note.

**Comment by mu3en** [comment]
Answer is no. 48000 in the other set up did not solve the issue.
So other that something very dark in the bridge networking setup or LXC stack, it feels like disk spin down / bind mount related and probably isolated to this case and to MPD not Snapcast.
Safe to close off. Thanks.

**Comment by mu3en** [comment]
hm. just noticed the "close and comment", last time did not even figure could self-close. Leaving alone for now:

just RTFM like a champ. noted buffering options, in particular the input buffer. it's "short" in relative terms so maybe tweaking that can solve if issues are indeed around MPDs stream I/O.

testing gently and reporting back shortly.
