### ISSUE TITLE
snapserver error with airplay stream: [Err] Exception: stoi

### ISSUE THREAD

**Issue by 1337sup3rh4x0r** [badaix/snapcast#184]
Hi there,
i have compiled shairport-sync under FreeBSD after the guide given in the Readme here.

After enabling avahi-daemon and dbus i can successfully lauch the airplay receiver manually with:

    shairport-sync
    Successful Startup

It is then visible for any airport compatible devices on my network.

However if I try to link it to snapserver, I get the following error:

    # snapserver -s 'airplay:///shairport-sync?name=Airplay[&devicename=Snapcast][&port=5000]'
    airplay:///shairport-sync?name=Airplay[&devicename=Snapcast][&port=5000]
    Settings file: /root/.config/snapcast/server.json
    2017-02-12 13-06-39 [out] Adding service 'Snapcast'
    2017-02-12 13-06-39 [out] PcmStream sampleFormat: 48000:16:2
    2017-02-12 13-06-39 [Notice] StreamServer::start: stoi
    2017-02-12 13-06-39 [Err] Exception: stoi
    2017-02-12 13-06-39 [Notice] daemon terminated.

Anybody have a clue whats going wrong here?

**Comment by badaix** [comment]
Please remove the brackets. They are kind of EBNF notation for an optional value.
Either use
```
snapserver -s 'airplay:///shairport-sync?name=Airplay&devicename=Snapcast&port=5000'
```
or use the defaults by leaving the parameters away:
```
snapserver -s 'airplay:///shairport-sync?name=Airplay'
```
I think what happens in you case is that the server tries to convert the port number to an integer, which is "5000]"

**Comment by badaix** [comment]
I've added a note about the notation 8e080499
