### ISSUE TITLE
shairport-sync not found when starting server on boot time

### ISSUE THREAD

**Issue by yesman82** [badaix/snapcast#185]
When starting snapchat server during boot up time 
whether using systemv, cron or rc.local
I always get this error in the syslog
even if I set the PATH upfront.

It all works great when running it on command-line.

Device: Raspberry Pi 3
OS: Raspbian

 ```
$ cat /var/log/syslog | grep snap
Feb 12 15:54:54 raspberrypi-1 snapserver[540]: StreamServer::start: shairport-sync not found
Feb 12 15:54:54 raspberrypi-1 snapserver[540]: Exception: shairport-sync not found
Feb 12 15:54:54 raspberrypi-1 snapserver[540]: daemon terminated.
```

```
$ cat  /etc/default/snapserver
# defaults file for snapserver

# setting path for snapserver and shairport-sync
PATH=$PATH:/usr/local/bin:/usr/sbin:/

# start snapserver automatically?
START_SNAPSERVER=true

# Allowed options:
#   -h, --help                          produce help message
#   -v, --version                       show version number
#   -p, --port arg (=1704)              server port
#   --controlPort arg (=1705)           Remote control port
#   -s, --sampleformat arg (=48000:16:2)
#                                       sample format
#   -c, --codec arg (=flac)             transport codec [flac|ogg|pcm][:options]
#                                       Type codec:? to get codec specific options
#   -f, --fifo arg (=/tmp/snapfifo)     name of the input fifo file
#   -d, --daemon [=arg(=0)]             daemonize
#                                       optional process priority [-20..19]
#   -b, --buffer arg (=1000)            buffer [ms]
#   --pipeReadBuffer arg (=20)          pipe read buffer [ms]

SNAPSERVER_OPTS='-d -s "airplay:///shairport-sync?name=Airplay&devicename=Multiroom"'

**Comment by airdrummingfool** [comment]
If `shairport-sync` isn't in the current working directory and the path is not supplied directly, snapserver uses `whereis` to find the binary - what is output when you run `whereis shairport-sync` (and is it different when run from the context of systemv, cron or rc.local)?

You can also try supplying the path to `shairport-sync` directly:
```
SNAPSERVER_OPTS='-d -s "airplay:///usr/local/bin/shairport-sync?name=Airplay&devicename=Multiroom"'
```

**Comment by yesman82** [comment]
```whereis``` in rc.local
```
shairport-sync: /etc/shairport-sync.conf /usr/local/bin/shairport-sync /usr/local/etc/shairport-sync.conf
```

```whereis``` in cron at reboot
```
shairport-sync: /etc/shairport-sync.conf /usr/local/bin/shairport-sync /usr/local/etc/shairport-sync.conf
```

Your suggestion calling the shairport-sync binary directly through streaming URL seems to work good. I couldn't get any sound out of the client but I guess that's another problem. 👍

**Comment by airdrummingfool** [comment]
@yesman82 I think I've changed some code that affects the issue you had above. Would you be willing to test the `which` branch of [my fork](https://github.com/airdrummingfool/snapcast)? It should be able to find `shairport-sync` (as long as it is in your `PATH`), without you having to provide the full path to the binary (e.g. `SNAPSERVER_OPTS='-d -s "airplay:///shairport-sync?name=Airplay&devicename=Multiroom"'`.
