### ISSUE TITLE
Crash when run snapcast on Android phone

### ISSUE THREAD

**Issue by maotouying** [badaix/snapcast#186]
There is crash when I click " Refresh client list" on Android phone,I had try some different phones, the error is also occur,there is a null object.
the log is:

 02-18 10:40:55.557 E/AndroidRuntime(31401): FATAL EXCEPTION: main
 02-18 10:40:55.557 E/AndroidRuntime(31401): Process: de.badaix.snapcast, PID: 31401
02-18 10:40:55.557 E/AndroidRuntime(31401): java.lang.NullPointerException: Attempt to invoke virtual method 'void de.badaix.snapcast.control.TcpClient.sendMessage(java.lang.String)' on a null object reference
02-18 10:40:55.557 E/AndroidRuntime(31401): at de.badaix.snapcast.control.RemoteControl.getServerStatus(RemoteControl.java:189)
02-18 10:40:55.557 E/AndroidRuntime(31401): 	at de.badaix.snapcast.MainActivity.onOptionsItemSelected(MainActivity.java:248)

**Comment by badaix** [comment]
Please try again with 0.11.0. Maybe it's fixed.

**Comment by badaix** [comment]
any update?
