### ISSUE TITLE
Shairport sync and spotify

### ISSUE THREAD

**Issue by atze09** [badaix/snapcast#188]
Can i get both to output to clients? 
With two -s arguments or how can i handle this?

**Comment by airdrummingfool** [comment]
You cannot combine streams from two sources in either the server or the client. For streaming multiple (separate) sources, look at #147. You might be able to run separate clients on the same machine and assign each to a different stream.

You could also look into combining the inputs in some sort of mixer, and then using the mixer as the input to snapcast. It looks like there could be a [(hacky, unsupported) way to do this in PulseAudio](https://lists.freedesktop.org/archives/pulseaudio-discuss/2012-November/015153.html).

**Comment by atze09** [comment]
According to the answer from bjwelker it is possible to use two different pipes.
I could not get this running, does anyone else get this running?

Answer from bjwelker c:
You need to start different pipes. If you want spotify Connect and MPD you can use
SNAPSERVER_OPTS="-d -s pipe:///tmp/snapspotify?name=Spotify&mode=read -s pipe:///tmp/snapvolumio?name=Volumio&mode=read"
Then you can put the Players via Android app into the different Rooms.
