### ISSUE TITLE
Spotify Integration

### ISSUE THREAD

**Issue by noaht8um** [badaix/snapcast#189]
Hello,

I am currently trying to get the Spotify integration to work as outlined [here](https://github.com/badaix/snapcast/blob/master/doc/player_setup.md#spotify). I cloned the librespot repo (the badaix/librespot one) and built it using Cargo with the stdout-backend feature. I can run librespot by itself and it works fine, but I can't direct the output to snapserver.

This is my snapserver config:
SNAPSERVER_OPTS="-d -s spotify:///usr/local/bin/librespot?name=Spotify&username='myemail@domain.com'&password='mypassword'&devicename=Snapcast&bitrate=320"

When I check the journal of the service, I get no errors, but I can't see any Spotify Connect clients on my computer or iPhone.

When I run librespot by itself, it will show up in Spotify but I can't get the output to snapserver. I've tried changing the backend to stdout using "--backend stdout" but that doesn't seem to do anything. Should I be specifying the fifo after that flag as in "--backend stdout /tmp/snapfifo"? If so, that doesn't work either.

I also tried getting the latest version from plietar/librespot, but it doesn't have support for stdout either.

As a side note, @badaix I really appreciate all the work you have put into this project. The shairplay-sync feature works perfectly, and this is what I am mainly using now. I was truly amazed at how well the audio syncing works; hardly even any latency or drop-outs even with some clients on Wi-Fi.

Thanks!

**Comment by ashwinvandijk** [comment]
I ran into these issues, looks like you need to use the backend "pipe":

`/usr/local/bin/librespot --backend stdout`

**Comment by noaht8um** [comment]
@ashwinvandijk I actually did try that, but it says that's not a valid backend.

Apparently, badaix submitted a pull request to the main librespot repo and got the stdout backend rolled into master. Recently they changed the name to pipe instead of stdout. I'm using the badaix /librespot fork though which still uses "stdout" instead of "pipe", not the main plietar/librespot repo. Which repo are you using? I just didn't use the plietar/librespot repo because badaix's instructions said to use his fork.

Sorry if that's all convoluted. I'm still not very familiar with GitHub-speak ;)

**Comment by ashwinvandijk** [comment]
Ah, I see... I was still compiling, and thought this would fix it... I will look into it!

**Comment by supajason** [comment]
Are you compiling librespot for the rpi(1) as I'm having trouble. Im getting illegal instruction from the release.

**Comment by noaht8um** [comment]
@ashwinvandijk Thanks a bunch! It works now.

@badaix You can close this ticket, but it would still be nice to see the spotify username and password not being required, as librespot doesn't need them to work correctly.

**Comment by ashwinvandijk** [comment]
@noaht8um, if you compile snapclient from develop, the username and password aren't longer required :)

**Comment by noaht8um** [comment]
@ashwinvandijk Wow, I didn't realize that, thanks!
