### ISSUE TITLE
Include git submodules in tar.gz / zip releases (To ease building of packages)

### ISSUE THREAD

**Issue by vibbix** [badaix/snapcast#193]
I'm in the process of writing a brew script for snapcast, when I realized I could not build the source files from the release .tar.gz without manually having to include the .gitmodules file. For the next release, can submodules be included?

**Comment by badaix** [comment]
Isn't there any other way to automatically pull the externals?
I would not want to include a bundle with submodules, because it's against the idea of the submodules

**Comment by reno-** [comment]
Hi,
I don't know how to do without git.
Here is the single git command to do that for tag v0.10.0 : 
`git clone --recursive --depth 1 --branch v0.10.0 https://github.com/badaix/snapcast.git`

Note that there is an issue for the moment because of a submodule without address : 
`fatal: No url found for submodule path 'externals/vorbis' in .gitmodules
`

**Comment by tgurr** [comment]
I'm also running into this problem while packaging snapcast-0.11.0_beta1:

```
make[1]: Leaving directory '/var/tmp/paludis/build/net-apps-snapcast-0.11.0_beta1/work/snapcast-0.11.0-beta-1/server'
In file included from snapServer.cpp:33:0:
streamServer.h:30:22: fatal error: jsonrp.hpp: No such file or directory
 #include "jsonrp.hpp"
                      ^
compilation terminated.
```

Imho the release tarball should contain the required submodules. Or even better give us a (beta) release of jsonrpcpp that we can package and depend on the jsonrp.so shared library.

I've done some tinkering:
`edo ${CC} ${CFLAGS} -shared -isystem lib/externals -o lib/jsonrp.so -fPIC lib/jsonrp.cpp`
```
    insinto /usr/$(exhost --target)/include
    doins lib/jsonrp.hpp

    dolib lib/jsonrp.so

    dobin jsonrpctest
```
however snapcast doesn't look for the shared library and still fails with:

`make[1]: *** No rule to make target '../externals/jsonrpcpp/lib/jsonrp.o', needed by 'snapserver'.  Stop.`

**Comment by badaix** [comment]
No need for submodules anymore, just the external dependencies are currently bundled to ease the android build process
