### ISSUE TITLE
Librespot Discovery Mode without username

### ISSUE THREAD

**Issue by PhoGGy** [badaix/snapcast#197]
Hey!
First I want to thank you very much for making this great piece of software.
I´m using it since half a year already, without a single hickup.
Would it be possible to make the "username" and "password" argument optional.
AFAIK librespot does support it, but I think the parsing of those arguments are written too simple.
So if theres no username and password argument, remove the --username and --password argument from librespot call.
Shouldn´t be a too big hassle, but I´m not that good at it.

Thank You!

Greetings Phil

**Comment by badaix** [comment]
This is already implemented in the develop branch, see #181
I will release it a an official beta within the next few days

**Comment by PhoGGy** [comment]
Hey badaix, 
Thanks for the quick reply and sorry for not searching through the development branch. 
As I have problems getting the cargo build of the librespot to work, would it be possible to release a new snapshot of the library that is compatible with the upcoming release? I'm using a raspberry pi 2 on osmc/Debian Jessie. 
Thanks! 
Greetings Phil

**Comment by badaix** [comment]
Sorry, I just deleted my fork, since the pipe backend is now supported in the upstream version.
I don't think that is makes sense to provide precompiled snapshots from my side, as I don't have a Spotify account atm, so I even cannot test

**Comment by PhoGGy** [comment]
Okay, no worries.

I´m currently compiling librespot from plietar and I´ll test it shortly. 
I´ll notify you.

Greetings Phil


Am 05.03.2017 um 15:24 schrieb Johannes Pohl:
