### ISSUE TITLE
Volumio2 output on snapserver

### ISSUE THREAD

**Issue by atze09** [badaix/snapcast#199]
Hello together,

I now managed to get the Spotify connect output through snapserver on volumio2 machine (RPi3).
Now additionally i would like to also output the shairport-sync to snapserver.

i compiled the shairport-sync version with stoud like it's described.
But i cannot install, because shairport-sync is already running through volumio2 stock.

i already edited the mpd.conf to the following:

`#audio_output {
#
#       type       "alsa"
#       name       "Output"
#       device    "hw:0,0"
#       dop    "no"
#
#}

audio_output {
    type            "fifo"
    enabled       "yes"
    name            "my pipe"
    path            "/tmp/snapfifo"`

But i stuck at creating the right pipe for that, to get the airplay through snapserver.
I also tried with 
`-s "airplay:///shairport-sync?name=Airplay`
But get the message shairport-sync is not available in the folder.

Now i see two options:
1. work with a symbolic link for shairport-sync
2. add a -s pipe for the snapfifo

Can anyone help me please.
Thank you in advance

**Comment by badaix** [comment]
You can configure the complete path to shairport-sync in the URI, e.g. 
```
-s "airplay:///usr/local/bin/shairport-sync?name=..."
```
Also the release [0.11.0](https://github.com/badaix/snapcast/releases/tag/v0.11.0-beta-1) might work out of the box for you, see also PR #196 and Issue #185

**Comment by atze09** [comment]
You are awesome johannes!
This line works like a charm!
i tried to update to 0.11.0 but this had issues to start (maybe my failure) so i reverted back to 0.10.0 and took your line.
Thank you very much for your superb development of this great piece of software!!!
