### ISSUE TITLE
Multiple near-simultaneous requests crash snapserver

### ISSUE THREAD

**Issue by airdrummingfool** [badaix/snapcast#200]
When sending multiple volume change requests in a very short span of time, snapserver often crashes with this error:
`[Err] Exception in ControlSession::reader(): read_until: End of file`

This happens to me when using @atoomic's snapcast-volume-ui project, as I can scroll with my mouse wheel to adjust the volume, and it sends requests on each step change. I can also recreate it simply by clicking to change the volume a couple times in quick succession, or by using any of the "all rooms" buttons (Mute All Rooms, All Rooms 50%, All Rooms 100%) at the top. It's also reproducible using the `setVolume.py` control script in the snapcast repo (modified to work with the newest JSON-RPC message format) - simply run `python setVolume.py [host] [volume level]` from more than one terminal at the same time.

**Comment by airdrummingfool** [comment]
It looks like the error only happens when adjusting the volume and closing the connection between requests - I couldn't reproduce this with a vanilla `setVolume.py`, and then I realized `setVolume` kept a single telnet connection open until all commands were sent. Once I modified it to open and close the connection for each command, the crash was easily reproducible.

Here's a simplified test case (provide the address to snapserver as the first argument and the clientID as the second, e.g. `python script.py 192.168.1.1 12:34:56:ab:cd:ef`):

```python
#!/usr/bin/env python
import sys
import telnetlib
import json

for x in range(0, 10):
    telnet = telnetlib.Telnet(sys.argv[1], 1705)
    telnet.write(json.dumps({'jsonrpc': '2.0', 'method': 'Client.SetVolume', 'params': {'id':  sys.argv[2], 'volume': {'muted': False, 'percent': 10}}, 'id': x}) + "\r\n")
    response = telnet.read_until("\r\n", 2)
    print("recv: " + response)
    telnet.close
```

A couple of other interesting notes:
* Using an invalid clientID in the script above will prevent `snapserver` from crashing.
* It appears that `Server.GetStatus` does not crash if called repeatedly.
* Sending "bye" or "exit" before closing the connection doesn't help.
* When testing snapcast-volume-ui, a sleep of 498ms or greater after closing the connection (before opening a new one) avoids the crash, but sleeping 497ms or less does not. I have not been able to reproduce this in Python code.

**Comment by badaix** [comment]
Hi, I figured the same: the crash is (was) related to the shutdown of the ControlSession object. I was able to reproduce the issue with `setVolume.py`:
````
for i in {1..1000}; do python setVolume.py localhost $i; done
````
pulling the loop into the script is working fine, i.e. it must be related to quick connects/disconnects.
With commit df5f9bdea it seems to be fixed. Can you please try again with the develop branch?

**Comment by airdrummingfool** [comment]
Your fix is working great! I haven't been able to cause a crash with the new code.

I agree that, when possible, a new TCP connection shouldn't be used for every command - but that's not always feasible :)

Thank you!

**Comment by atoomic** [comment]
Hope this could make it to release of v0.11

**Comment by airdrummingfool** [comment]
@atoomic it's a part of 0.11.0~beta-2 :) See the [changelog](https://github.com/badaix/snapcast/blob/develop/client/debian/changelog)
