### ISSUE TITLE
Snapclient and Snapserver on one device

### ISSUE THREAD

**Issue by PhoGGy** [badaix/snapcast#201]
Isn´t it possible to run a server and Client on the same device?
Currently for testing I´m using mplayer to play an mp3 fil to /tmp/snapfifo
Streaming this to other client works as expected.
A Client is running on the same machine as the server, connecting to 127.0.0.1 or the same ip address as the other clients. Both doesn´t work.
systemctl status: snapclient[9520]: Exception in Controller::worker(): sum timeout exceeded 10s
nearly every second.
Do you have an idea?

Thanks!
Greetings Phil

**Comment by badaix** [comment]
Weird, this should work. Are both the same version?

**Comment by PhoGGy** [comment]
I think I found the error in my ip configuration.
I´ll keep you updated and close this issue, once its working.

**Comment by PhoGGy** [comment]
Works like a charm with your 0.11.0-beta1 release!
There are some problems with updating, you always have to unmask the systemd unit file un your own after uninstalling.
