### ISSUE TITLE
lede (openWRT Fork?) no package creation

### ISSUE THREAD

**Issue by celevra** [badaix/snapcast#203]
Hi,

i've followed your build instrunctions and setup a lede crossbuild environment, it is exactly the same as with openwrt, i think it is a fork.
i compiles without complain, but in the end there is no ipk file, 

these are the two commands i'm running:
```
omega@41e7bc810ee2:/lede$ make package/sxx/snapcast/clean
 make[1] package/sxx/snapcast/clean
 make[2] -C package/sxx/snapcast clean
omega@41e7bc810ee2:/lede$ make package/sxx/snapcast/compile
 make[1] package/sxx/snapcast/compile
 make[2] -C package/libs/toolchain compile
 make[2] -C package/firmware/linux-firmware compile
 make[2] -C package/firmware/prism54-firmware compile
 make[2] -C package/kernel/linux compile
 make[2] -C feeds/packages/libs/alsa-lib compile
 make[2] -C feeds/packages/libs/expat compile
 make[2] -C feeds/packages/utils/dbus compile
 make[2] -C package/libs/gettext-full host-compile
 make[2] -C feeds/packages/libs/gdbm compile
 make[2] -C feeds/packages/libs/intltool host-compile
 make[2] -C feeds/packages/libs/libdaemon compile
 make[2] -C feeds/packages/libs/avahi compile
 make[2] -C feeds/packages/libs/flac compile
 make[2] -C feeds/packages/libs/libogg compile
 make[2] -C feeds/packages/libs/libvorbis compile
 make[2] -C feeds/packages/libs/libvorbisidec compile
 make[2] -C package/sxx/snapcast compile
```

is there anything else i have to run like

make package/sxx/snapcast/package

?

regards

celevra

**Comment by celevra** [comment]
ok, my fault, you have to select it through menu config...
but now i get an comile error:
snapClient.cpp:22:20: fatal error: popl.hpp: No such file or directory

the popl.hpp isn't in this git repo, is it a system library?

**Comment by badaix** [comment]
this bug seems to be fixed by the Asio guys: https://github.com/chriskohlhoff/asio/issues/94
I've updated asio to 1-10-8. Please try to build again with the develop branch. 
Don't forget to update the submodules: `git submodule update`

**Comment by celevra** [comment]
now it is working, perfect, thank you! i will update the compile instructions
