### ISSUE TITLE
Android app crashes on connect

### ISSUE THREAD

**Issue by FilipLigaarden** [badaix/snapcast#207]
Client/server: Ubuntu 16.04
Android: Emulated and android 4.4?
Android app crashes on server connect when there are other clients on server.
Does not add itself as a client when pressing play when no other clients connected either.
Note that this was an emulation, but also tried on a regular LG tablet.

**Server:**
`2017-03-07 12-45-11 [Notice] ControlServer::NewConnection: 192.168.77.46
2017-03-07 12-45-11 [out] StreamServer::ProcessRequest method: Server.GetStatus, id: 0
Request:      {"id":0,"jsonrpc":"2.0","method":"Server.GetStatus"}
Response:     {"id":0,"jsonrpc":"2.0","result":{"server":{"groups":[{"clients":[{"config":{"instance":1,"latency":0,"name":"","volume":{"muted":false,"percent":100}},"connected":false,"host":{"arch":"x86_64","ip":"127.0.0.1","mac":"d4:be:d9:56:e0:2c","name":"Filip","os":"Ubuntu 16.04.2 LTS"},"id":"d4:be:d9:56:e0:2c","lastSeen":{"sec":1488886624,"usec":830918},"snapclient":{"name":"Snapclient","protocolVersion":2,"version":"0.11.0-beta-1"}}],"id":"0531cfaf-4651-fb86-ee1e-62731f8f5687","muted":false,"name":"","stream_id":"default"}],"server":{"host":{"arch":"x86_64","ip":"","mac":"","name":"Filip","os":"Ubuntu 16.04.2 LTS"},"snapserver":{"controlProtocolVersion":1,"name":"Snapserver","protocolVersion":1,"version":"0.11.0-beta-1"}},"streams":[{"id":"default","status":"idle","uri":{"fragment":"","host":"","path":"/tmp/snapfifo","query":{"buffer_ms":"20","codec":"flac","name":"default","sampleformat":"48000:16:2"},"raw":"pipe:///tmp/snapfifo?name=default","scheme":"pipe"}}]}}}
2017-03-07 12-45-13 [Err] Exception in ControlSession::reader(): read_until: End of file
2017-03-07 12-48-54 [Notice] ControlServer::NewConnection: 192.168.77.46
2017-03-07 12-48-54 [out] StreamServer::ProcessRequest method: Server.GetStatus, id: 0
Request:      {"id":0,"jsonrpc":"2.0","method":"Server.GetStatus"}
Response:     {"id":0,"jsonrpc":"2.0","result":{"server":{"groups":[{"clients":[{"config":{"instance":1,"latency":0,"name":"","volume":{"muted":false,"percent":100}},"connected":false,"host":{"arch":"x86_64","ip":"127.0.0.1","mac":"d4:be:d9:56:e0:2c","name":"Filip","os":"Ubuntu 16.04.2 LTS"},"id":"d4:be:d9:56:e0:2c","lastSeen":{"sec":1488886624,"usec":830918},"snapclient":{"name":"Snapclient","protocolVersion":2,"version":"0.11.0-beta-1"}}],"id":"0531cfaf-4651-fb86-ee1e-62731f8f5687","muted":false,"name":"","stream_id":"default"}],"server":{"host":{"arch":"x86_64","ip":"","mac":"","name":"Filip","os":"Ubuntu 16.04.2 LTS"},"snapserver":{"controlProtocolVersion":1,"name":"Snapserver","protocolVersion":1,"version":"0.11.0-beta-1"}},"streams":[{"id":"default","status":"idle","uri":{"fragment":"","host":"","path":"/tmp/snapfifo","query":{"buffer_ms":"20","codec":"flac","name":"default","sampleformat":"48000:16:2"},"raw":"pipe:///tmp/snapfifo?name=default","scheme":"pipe"}}]}}}
2017-03-07 12-48-55 [Err] Exception in ControlSession::reader(): read_until: End of file`

**Android:**

`03-07 12:45:11.146 I/ActivityManager(446): Start proc de.badaix.snapcast for activity de.badaix.snapcast/.MainActivity: pid=1645 uid=10037 gids={50037, 3003}
03-07 12:45:11.156 W/NetworkManagementSocketTagger(446): setKernelCountSet(10037, 1) failed with errno -13
03-07 12:45:11.156 I/dalvikvm(1645): ignoring registerObject request in thread=1
03-07 12:45:11.156 I/dalvikvm(1645): ignoring registerObject request in thread=1
03-07 12:45:11.166 D/FirebaseApp(682): Notifying background state change listeners.
03-07 12:45:11.186 I/dalvikvm(1645): Could not find method android.view.Window$Callback.onProvideKeyboardShortcuts, referenced from method android.support.v7.view.WindowCallbackWrapper.onProvideKeyboardShortcuts
03-07 12:45:11.186 W/dalvikvm(1645): VFY: unable to resolve interface method 21194: Landroid/view/Window$Callback;.onProvideKeyboardShortcuts (Ljava/util/List;Landroid/view/Menu;I)V
03-07 12:45:11.186 D/dalvikvm(1645): VFY: replacing opcode 0x72 at 0x0002
03-07 12:45:11.186 W/dalvikvm(1645): VFY: unable to find class referenced in signature (Landroid/view/SearchEvent;)
03-07 12:45:11.186 I/dalvikvm(1645): Could not find method android.view.Window$Callback.onSearchRequested, referenced from method android.support.v7.view.WindowCallbackWrapper.onSearchRequested
03-07 12:45:11.186 W/dalvikvm(1645): VFY: unable to resolve interface method 21196: Landroid/view/Window$Callback;.onSearchRequested (Landroid/view/SearchEvent;)Z
03-07 12:45:11.186 D/dalvikvm(1645): VFY: replacing opcode 0x72 at 0x0002
03-07 12:45:11.186 I/dalvikvm(1645): Could not find method android.view.Window$Callback.onWindowStartingActionMode, referenced from method android.support.v7.view.WindowCallbackWrapper.onWindowStartingActionMode
03-07 12:45:11.186 W/dalvikvm(1645): VFY: unable to resolve interface method 21200: Landroid/view/Window$Callback;.onWindowStartingActionMode (Landroid/view/ActionMode$Callback;I)Landroid/view/ActionMode;
03-07 12:45:11.186 D/dalvikvm(1645): VFY: replacing opcode 0x72 at 0x0002
03-07 12:45:11.186 I/dalvikvm(1645): Could not find method android.content.res.TypedArray.getChangingConfigurations, referenced from method android.support.v7.widget.TintTypedArray.getChangingConfigurations
03-07 12:45:11.186 W/dalvikvm(1645): VFY: unable to resolve virtual method 512: Landroid/content/res/TypedArray;.getChangingConfigurations ()I
03-07 12:45:11.186 D/dalvikvm(1645): VFY: replacing opcode 0x6e at 0x0002
03-07 12:45:11.186 I/dalvikvm(1645): Could not find method android.content.res.TypedArray.getType, referenced from method android.support.v7.widget.TintTypedArray.getType
03-07 12:45:11.186 W/dalvikvm(1645): VFY: unable to resolve virtual method 534: Landroid/content/res/TypedArray;.getType (I)I
03-07 12:45:11.186 D/dalvikvm(1645): VFY: replacing opcode 0x6e at 0x0008
03-07 12:45:11.206 I/dalvikvm(1645): Could not find method android.content.Context.getColorStateList, referenced from method android.support.v7.content.res.AppCompatResources.getColorStateList
03-07 12:45:11.206 W/dalvikvm(1645): VFY: unable to resolve virtual method 310: Landroid/content/Context;.getColorStateList (I)Landroid/content/res/ColorStateList;
03-07 12:45:11.206 D/dalvikvm(1645): VFY: replacing opcode 0x6e at 0x0006
03-07 12:45:11.216 D/dalvikvm(1645): JIT code cache reset in 0 ms (0 bytes 1/0)
03-07 12:45:11.216 D/dalvikvm(1645): GC_FOR_ALLOC freed 159K, 8% free 2971K/3196K, paused 3ms, total 3ms
03-07 12:45:11.216 I/dalvikvm-heap(1645): Grow heap (frag case) to 3.570MB for 635808-byte allocation
03-07 12:45:11.226 D/dalvikvm(1645): GC_FOR_ALLOC freed 3K, 7% free 3589K/3820K, paused 4ms, total 4ms
03-07 12:45:11.226 D/dalvikvm(1645): GC_CONCURRENT freed <1K, 7% free 3589K/3820K, paused 1ms+0ms, total 3ms
03-07 12:45:11.226 I/dalvikvm(1645): Could not find method android.content.res.Resources.getDrawable, referenced from method android.support.v7.widget.ResourcesWrapper.getDrawable
03-07 12:45:11.226 W/dalvikvm(1645): VFY: unable to resolve virtual method 475: Landroid/content/res/Resources;.getDrawable (ILandroid/content/res/Resources$Theme;)Landroid/graphics/drawable/Drawable;
03-07 12:45:11.226 D/dalvikvm(1645): VFY: replacing opcode 0x6e at 0x0002
03-07 12:45:11.226 I/dalvikvm(1645): Could not find method android.content.res.Resources.getDrawableForDensity, referenced from method android.support.v7.widget.ResourcesWrapper.getDrawableForDensity
03-07 12:45:11.226 W/dalvikvm(1645): VFY: unable to resolve virtual method 477: Landroid/content/res/Resources;.getDrawableForDensity (IILandroid/content/res/Resources$Theme;)Landroid/graphics/drawable/Drawable;
03-07 12:45:11.226 D/dalvikvm(1645): VFY: replacing opcode 0x6e at 0x0002
03-07 12:45:11.236 E/dalvikvm(1645): Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method android.support.v7.widget.AppCompatImageHelper.hasOverlappingRendering
03-07 12:45:11.236 W/dalvikvm(1645): VFY: unable to resolve instanceof 151 (Landroid/graphics/drawable/RippleDrawable;) in Landroid/support/v7/widget/AppCompatImageHelper;
03-07 12:45:11.236 D/dalvikvm(1645): VFY: replacing opcode 0x20 at 0x000c
03-07 12:45:11.306 D/dalvikvm(1645): GC_CONCURRENT freed 260K, 8% free 3776K/4104K, paused 1ms+4ms, total 19ms
03-07 12:45:11.356 D/libEGL  (1645): loaded /system/lib/egl/libEGL_emulation.so
03-07 12:45:11.356 D/        (1645): HostConnection::get() New Host Connection established 0xb988b080, tid 1645
03-07 12:45:11.356 D/libEGL  (1645): loaded /system/lib/egl/libGLESv1_CM_emulation.so
03-07 12:45:11.356 D/libEGL  (1645): loaded /system/lib/egl/libGLESv2_emulation.so
03-07 12:45:11.396 W/EGL_emulation(1645): eglSurfaceAttrib not implemented
03-07 12:45:11.396 D/OpenGLRenderer(1645): Enabling debug mode 0
03-07 12:45:11.446 I/ActivityManager(446): Displayed de.badaix.snapcast/.MainActivity: +318ms
03-07 12:45:11.456 W/ContextImpl(446): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1123 com.android.server.InputMethodManagerService.hideCurrentInputLocked:1880 com.android.server.InputMethodManagerService.windowGainedFocus:1968 com.android.internal.view.IInputMethodManager$Stub.onTransact:221 com.android.server.InputMethodManagerService.onTransact:818 
03-07 12:45:11.516 D/AndroidRuntime(1645): Shutting down VM
03-07 12:45:11.516 W/dalvikvm(1645): threadid=1: thread exiting with uncaught exception (group=0x94cc7b20)
03-07 12:45:11.526 D/dalvikvm(1645): GC_CONCURRENT freed 328K, 10% free 3963K/4356K, paused 2ms+0ms, total 5ms
03-07 12:45:11.526 D/dalvikvm(1645): WAIT_FOR_CONCURRENT_GC blocked 2ms
03-07 12:45:11.526 W/ActivityManager(446):   Force finishing activity de.badaix.snapcast/.MainActivity
03-07 12:45:11.545 D/dalvikvm(446): GC_FOR_ALLOC freed 256K, 11% free 7496K/8404K, paused 10ms, total 10ms
03-07 12:45:11.555 D/dalvikvm(446): GC_FOR_ALLOC freed 55K, 9% free 7736K/8460K, paused 7ms, total 7ms
03-07 12:45:11.555 I/dalvikvm-heap(446): Grow heap (frag case) to 8.228MB for 635808-byte allocation
03-07 12:45:11.565 D/dalvikvm(446): GC_FOR_ALLOC freed <1K, 9% free 8356K/9084K, paused 11ms, total 11ms
03-07 12:45:11.575 W/WindowManager(446): updateFocusedWindowLocked, focusedAppToken is null.
03-07 12:45:11.585 D/dalvikvm(1164): GC_CONCURRENT freed 95K, 15% free 8493K/9936K, paused 0ms+0ms, total 4ms
03-07 12:45:11.605 D/        (446): HostConnection::get() New Host Connection established 0xb9a06bf0, tid 463
03-07 12:45:12.055 W/ActivityManager(446): Activity pause timeout for ActivityRecord{4a9ddc10 u0 de.badaix.snapcast/.MainActivity t3 f}
03-07 12:45:12.065 D/FirebaseApp(682): Notifying background state change listeners.
03-07 12:45:12.085 W/EGL_emulation(682): eglSurfaceAttrib not implemented
03-07 12:45:12.105 D/dalvikvm(682): GC_CONCURRENT freed 1228K, 23% free 6422K/8304K, paused 3ms+1ms, total 11ms
03-07 12:45:12.545 W/NetworkManagementSocketTagger(446): setKernelCountSet(10037, 0) failed with errno -13
03-07 12:45:13.415 I/Process (1645): Sending signal. PID: 1645 SIG: 9
03-07 12:45:13.415 W/ContextImpl(446): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1123 com.android.server.am.ActivityManagerService.handleApplicationCrashInner:9640 com.android.server.am.ActivityManagerService.handleApplicationCrash:9614 android.app.ActivityManagerNative.onTransact:1311 com.android.server.am.ActivityManagerService.onTransact:2071 
03-07 12:45:13.415 W/InputDispatcher(446): channel '4a97d698 de.badaix.snapcast/de.badaix.snapcast.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
03-07 12:45:13.415 E/InputDispatcher(446): channel '4a97d698 de.badaix.snapcast/de.badaix.snapcast.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
03-07 12:45:13.415 W/InputDispatcher(446): Attempted to unregister already unregistered input channel '4a97d698 de.badaix.snapcast/de.badaix.snapcast.MainActivity (server)'
03-07 12:45:13.415 I/ActivityManager(446): Process de.badaix.snapcast (pid 1645) has died.`

**Comment by badaix** [comment]
did you build it yourself or did you use the official APK?

**Comment by FilipLigaarden** [comment]
Official APK

**Comment by FilipLigaarden** [comment]
Seems to not crash when no clients are connected

**Comment by badaix** [comment]
Can you try the attached apk?
[Snapcast-0.11.0-pre-beta-2.apk.zip](https://github.com/badaix/snapcast/files/839504/Snapcast-0.11.0-pre-beta-2.apk.zip)

**Comment by FilipLigaarden** [comment]
Works.
Thank you.
