### ISSUE TITLE
Spotify Multiroom Audio

### ISSUE THREAD

**Issue by palitu** [badaix/snapcast#208]
Wanted to say thanks!  I just got Spotify multiroom audio up and running.  the system isnt fullysetup for reboots, but once i have something for that i will let you know.

So - this gives me a single spotify account that i can control using any device, using the official spotify app(s), that is then beamed throughout my house as much as i want.

Install Spotify as normal.
Install Snapcast
Give your user access to the pulse system:
`sudo usermod -a -G pulse-access <username> `

modify the snapserver (/etc/default/snapserver) config to:
`SNAPSERVER_OPTS="-d -s pipe:///tmp/snapfifo?name=Spotify&mode=read&sampleformat=44100:16:2"`

modify /etc/pulse/system.pa  or /etc/pulse/default.pa to include:
```
load-module module-pipe-sink file=/tmp/snapfifo sink_name=Snapcast
update-sink-proplist Snapcast device.description=Snapcast
set-default-sink Snapcast
```

This should start a new channel for snapcast called "Spotify", and default Pulse Audio to pipe the audio to the snapfifo file.

Note that we need to set the sample format to 44.1k, otherwise everything sounds a bit high pitched and too fast.

**Comment by unimatrix27** [comment]
you can simply put the pulseaudio commands in the /etc/pa/system.pa (assuming you use pulseaudio in system mode) and also call set-default-sink in there to ensure that by default everything is routed to the pipe sink

to your snapcast config add "&mode=read" to the sink definition, by doing that, snapcast will not create the sinks and pulseaudio can be started at any time without complaining about an already existing file.

**Comment by palitu** [comment]
Thanks - i will update the post when i implement it.  As someone not particularly experienced with this, i found the instructions lacking, so hopefully this will help someone else.

**Comment by palitu** [comment]
Actually i just checked - i do not have a /etc/pa/ directory... i guess it is not in system mode.

**Comment by unimatrix27** [comment]
sorry, my mistake, of course its /etc/pulse/system.pa for system mode, or /etc/pulse/default.pa for user mode. If you dont know what system mode is, you are probably in user mode which is the default configuration if you are actually logging in on that system. system mode is mostly used for headless systems without interactive users actually using the system.

**Comment by palitu** [comment]
> If you dont know what system mode is

bingo - this is why i want to write this, hopefully make snapcast more accesible to people of my experience.

Thanks for the follow up.

**Comment by unimatrix27** [comment]
I wrote a WIKI document in the context of FHEM (home automation) where snapcast is used as a key component in an integrated home multiroom environment, supporting spotify through mopidy. The article is in german, but maybe you can still find something useable in the configuration examples. Its a complete walkthrough about how to set this up.

https://wiki.fhem.de/wiki/OpenMultiroom

**Comment by badaix** [comment]
To summarize:
we should add to the [Player-setup/PulseAudio section](https://github.com/badaix/snapcast/blob/master/doc/player_setup.md#pulseaudio):

> Load the module pipe-sink like this:
> 
> ````
> pacmd load-module module-pipe-sink file=/tmp/snapfifo sink_name=Snapcast
> pacmd update-sink-proplist Snapcast device.description=Snapcast
> ````
> 
To make the settings persistent, add these lines into
* ` /etc/pulse/system.pa` if PulseAudio is started in system mode
* `/etc/pulse/default.pa` if PulseAudio is started per-user

Is this ok?

**Comment by palitu** [comment]
@badaix I have updated the first post.  It looks about right.

Let me test it all out and i will let you know when i am happy to publish it as docs.

**Comment by axelsimon** [comment]
@badaix What happened to badaix/librespot? Is it deprecated in favour of the main librespot?
I'm currently using `SNAPSERVER_OPTS="-d -s spotify:///librespot?name=Spoti_pi&username=user&password=secret&devicename=Spoti_pi&bitrate=320"` and that has been working well.

Also, in passing, the pulse audio documentation often mentions they advise against using Pulse in system mode. But in our use cases (often, a dedicated device streaming sound), it seems ok.

**Comment by badaix** [comment]
yes, you have to use the official [librespot](https://github.com/plietar/librespot).
Snapcast is using the librespot's official `pipe` backend in version 0.11, instead of the `stdout` backend of my forked version.

**Comment by palitu** [comment]
@badaix 

cool, i am reasonably happy that the setup works:

can you put in the following info for your pulse config page:

Give your user access to edit the pulse system:
`sudo usermod -a -G pulse-access <username>`

modify the snapserver (/etc/default/snapserver) config to:
`SNAPSERVER_OPTS="-d -s pipe:///tmp/snapfifo?name=Spotify&mode=read&sampleformat=44100:16:2"`

modify pulse audio config, which will either be `/etc/pulse/system.pa` or `/etc/pulse/default.pa`, to include:
```
#create an audio sink for snapcast 
load-module module-pipe-sink file=/tmp/snapfifo sink_name=Snapcast
update-sink-proplist Snapcast device.description=Snapcast

# Set the snapcast output to be the default output
set-default-sink Snapcast
```

**Comment by badaix** [comment]
@palitu can you please make a pull request for this?

**Comment by bbalazs** [comment]
Picking this up, as it seems to be very close to what I want to solve: Multi-User Multi-Room Audio. I think I can try your approach but would like to know one thing: I would like to back multiple spotify accounts with this. So everyone can listen to "their" spotify in whatever room(s). How would I tackle this?

**Comment by palitu** [comment]
now that, i dont know.  I wanted this as a central server for all speakers in the house, all from the one account.

The multi account seems problematic.  you may need to use the Spotify integration, on for each account, and have each of these... nope this is where my thoughts fall over, how do you have one snapserver and multiple streams?

**Comment by badaix** [comment]
I think this can be closed: https://github.com/badaix/snapcast/blob/master/doc/player_setup.md#pulseaudio
