### ISSUE TITLE
In-tree Buildroot support

### ISSUE THREAD

**Issue by joerg-krause** [badaix/snapcast#209]
I am a maintainer of Buildroot and I'd like to add snapcast as a package to Buildroot without the need for using an external tree. Therefore, I already added popl and asio as packages (not mainline yet).

The snapcast Makefile needs some adjustments to get it into mainline:

- Remove of `-isystem` (not needed, not safe)
- Do not strip by default (Buildroot has an option for this)
- Use pkg-config for needed libraries
- Identify required and optional dependencies
- For optional dependencies, allow passing a variable through the environment, e.g. `HAVE_OGG`, if the build system has ogg enabled (this is what would be done by ./configure)
- Support static builds
- Allow building the server

Maybe it's time for autotools or CMake?

If this is done properly there is no need to distinguish between OpenWRT, Buildroot, or any other similar Linux system.

**Comment by joerg-krause** [comment]
I will come up with a CMake file instead of rewriting the current Makefile. This way, the Makefile still can be used...

**Comment by badaix** [comment]
Did you check @Outurnate's Windows port? He is porting the Makefile to CMake:
https://github.com/Outurnate/snapcast/tree/windows-cmake

**Comment by joerg-krause** [comment]
No, I haven't! Thanks! I will check it.

**Comment by joerg-krause** [comment]
@badaix I've some notes and questions about the client dependencies on Linux:

1. The ogg decoder is optional. If ogg support is enabled then libogg is required and either tremor (fixed-point) or vorbis (floating-point) as decoder.
2. The FLAC decoder is **not** optional. Why? If flac support is enabled then libflac is required.
3. For Bonjour Avahi (common) or mDNSResponder (not so common) can be used. Does it makes sense to use none (I don't think so)?
4. In which case should `HAS_DAEMON` be **not** set? From my understanding, it can be enabled if the architecture does have support for `fork()`, right? In which case `HAS_FORK` would be a better definition.
5. On Linux, ALSA is mandatory, right?

From my understanding, a minimal snapclient on Linux should have:
1. ALSA
2. Avahi
3. FLAC?

**Comment by Outurnate** [comment]
@joerg-krause CMake is done on my branch.  I will submit it as a PR soon...just cleaning up the windows installer and Android cmake build

**Comment by joerg-krause** [comment]
@Outurnate I'm already using it :smile: There are some changes I would suggest. Shall I add some comments to your branch?

**Comment by Outurnate** [comment]
@joerg-krause go ahead, yeah.  I'd like to get it merged in the next two weeks

I'm trying to hide all the platform-specific junk in the platform directory

**Comment by joerg-krause** [comment]
I've created a fork which adds Linux-only CMake files. I've added some package configurations to allow building Snap* without any codec support. However, this can be removed. If I've some spare time, I'll update the commits to build a full-blown Snap* thing.

**Comment by joerg-krause** [comment]
Closing this as I am not using snapcast anymore. Maybe someone else has the time to add snapcast to Buildroot.
