### ISSUE TITLE
Multi-Zone Support?

### ISSUE THREAD

**Issue by sashahilton00** [badaix/snapcast#21]
Sorry to put this in issues... Would someone be able to tell me if the server supports multi zone setups, or is going to in the future? (ie. Music in one room, and different music in the other rooms) What I would love to be able to do is call an API endpoint on the server with a Client/Speaker identifier, and tell the server to send a certain audio stream to the client...

**Comment by badaix** [comment]
Hi,
this is a planned feature for the upcoming v0.5. There is already an API and an Android implementation of the remote control in the develop branch. 
Multi-zone is currently worked on. I guess that I will release a first Beta during next week.
I think I will release the Remote control API of the Android client later as a separate Java lib. There is also a [Python lib](https://github.com/happyleavesaoc/python-snapcast)  available.

**Comment by badaix** [comment]
As the first v0.5 beta with multi zone feature has been released, I will close this ticket
