### ISSUE TITLE
Android bugs

### ISSUE THREAD

**Issue by FilipLigaarden** [badaix/snapcast#214]
In the android client(v0.11.0-beta-2) you are unable to separate clients in different groups when they are all connected to the same group.
My suggestion would be to always display all groups.
Muting a group should also show that all the clients in the group are muted, for clarity.

Streams: 
Spotify
Spotify-multibruker

Clients:
Musikk
Bruker

![first](https://cloud.githubusercontent.com/assets/26249138/23947169/d996b8c6-097d-11e7-9d3d-3ba1f1bdecd8.PNG)
Fresh server, starts with the clients connecting to the same copied stream (bug 1#)

![re](https://cloud.githubusercontent.com/assets/26249138/23947132/ad582236-097d-11e7-8d8a-97925b933beb.PNG)
Changed the clients to connect to different streams.
![fourth](https://cloud.githubusercontent.com/assets/26249138/23946950/cff02bb4-097c-11e7-8d11-e24a4674b3f4.PNG)
Changed both client to connect to same stream
![second](https://cloud.githubusercontent.com/assets/26249138/23946951/cff04b3a-097c-11e7-90a9-50e83bece245.PNG)

![third](https://cloud.githubusercontent.com/assets/26249138/23946949/cfef16e8-097c-11e7-9c05-ffd5249a2050.PNG)
Stream number two disappears, leaving no option to use both streams at the same time with different clients. (bug #2)

**Mind setting up a donation button?**

**Comment by badaix** [comment]
Bug #1: 
A new client is always in it's own group. A new group is always using the default stream.
I think this is a reasonable behavior. What would you expect?

Bug #2:
Why should the App show an empty group?

**Comment by FilipLigaarden** [comment]
1#You are right about nr 1.
#2 Because only one group is showing when all clients are connected to the same group, therefore you are unable to separate clients into other new groups, and a restart, or connecting a new client would be required, or am I missing something?

**Comment by badaix** [comment]
You can go into the group A configuration and de-select a client. 
This client will be removed from the group and put into it's own group B (group B inherits the stream of the client's previous group). 
In group B configuration you can add further clients and/or change the stream.
I think it's working the same way as in the Sonos App (as far as I could reverse it from YouTube videos :wink: )

**Comment by FilipLigaarden** [comment]
Okay, thank you :)
