### ISSUE TITLE
Using ALSA PCM devices which does not have a name hint section

### ISSUE THREAD

**Issue by joerg-krause** [badaix/snapcast#215]
As far as I understand, it is not possible to set the ALSA mixer which will be used by snapclient, right?

EDIT: I do not mean mixer, but PCM device.

**Comment by celevra** [comment]
```
~ # snapclient --help
Allowed options:
  --help                          produce help message
  -v, --version                   show version number
  -h, --host arg                  server hostname or ip address
  -p, --port arg (=1704)          server port
  -l, --list                      list pcm devices
  -s, --soundcard arg (=default)  index or name of the soundcard
  -d, --daemon [=arg(=-3)]        daemonize, optional process priority [-20..19]
  --user arg                      the user[:group] to run snapclient as when daemonized
  --latency arg (=0)              latency of the soundcard
  -i, --instance arg (=1)         instance id
```

try the -s option

**Comment by badaix** [comment]
...And check the available options with `-l`

**Comment by joerg-krause** [comment]
Sorry, my question was misleading. I didn't meant mixer, but PCM device. It is not possible to set PCM devices like "hw:0", "plughw:0", "softvol", "dmix".

**Comment by joerg-krause** [comment]
The problem is that `pcm_list()` only lists the PCM devices which have a name hint section. So, I would suggest to not use `pcm_list()` at all for setting the PCM device, but just use the string passed by the `-s` option.

**Comment by joerg-krause** [comment]
I changed the title (again) to better describe the actual issue.

**Comment by joerg-krause** [comment]
Sorry, this issue is no longer relevant to me.
