### ISSUE TITLE
Prevent startup from snapserver

### ISSUE THREAD

**Issue by spaltaner** [badaix/snapcast#230]
Hello, is it possible to prevent the snapserver from autostart, so that it must be activated manually?
My concrete problem is, that i want all of my snapclients to have the possibility to be also server, but only one should be active at one time.

Thank you in advance

**Comment by twenta** [comment]
Tried disabling it?
https://www.digitalocean.com/community/tutorials/how-to-use-systemctl-to-manage-systemd-services-and-units

**Comment by badaix** [comment]
or edit `/etc/defaults/snapserver`:

```
# defaults file for snapserver

# start snapserver automatically?
START_SNAPSERVER=false
```

**Comment by spaltaner** [comment]
Okay thank you i'll try it

**Comment by spaltaner** [comment]
Okay thank you i'll try it

**Comment by spaltaner** [comment]
The change in the default file had no impact on the startup from snapserver but it worked fine with systemctl Thanks

**Comment by badaix** [comment]
hmm, might be that the default file thing is only working for Sys-V init, but not for systemd. Grmpf...
