### ISSUE TITLE
any way to have two inputs?

### ISSUE THREAD

**Issue by lucasgelfond** [badaix/snapcast#232]
ie could I have Mopidy and Clementine both feed into Snapcast? Whichever started playing most recently would be what went to Snapcast.

ie I'm on my computer and I'm playing Song 1 through Clementine through my home stereo system. Someone gets home and swaps to Song 2 through Mopidy. Now song 2 is playing. I start Song 1 again, song 1 plays. Etc.

**Comment by PhoGGy** [comment]
I try to answer this to give you maybe a few hints.
I´d say there are a few methods to accomplish this:

1. Having two systemd snapserver services with different arguments
You´ve to detect which source is currently playing on the server and start the appropiate systemd service file. Disadvantage is maybe, that the server has to restart for each change.
2. route with pulseaudio
Take both sources as pulseaudio input and route it to one snapcast sink. You could either play both simultaneously or swap between the two by again detecting which of them is playing.

Maybe there is a much more obvious and simpler approach, but I thought I could maybe help somehow :)
Greetings Phil

**Comment by badaix** [comment]
I would also suggest something like the PhoGGy's second solution. 
Snapcast will use whatever is written to the pipe. It will not "mix" two sources. This can be done before, e.g. with pulseaudio.
