### ISSUE TITLE
Android app won't automatically connect when connection dies 

### ISSUE THREAD

**Issue by FilipLigaarden** [badaix/snapcast#233]
Thank you for this great work.
Small bug, won't affect a lot of people, but its nice to be able to use a phone to play music.

The app throws exceptions and won't reconnect if the snapcast app is open as a playing client and loses connection to the server.
This happens both when you lose connection to wifi:
"Error: Software caused connection abort" or the server restarting"
Or when the snapserver restarts.
It try to connect, get connected, but the server will output following in an endless loop:
`Apr 12 16:15:26 raspberrypi snapserver[1417]: StreamServer::NewConnection: 192.168.1.118
Apr 12 16:15:28 raspberrypi snapserver[1417]: Exception in StreamSession::reader(): read_some: End of file
Apr 12 16:15:29 raspberrypi snapserver[1417]: StreamServer::NewConnection: 192.168.1.118
Apr 12 16:15:31 raspberrypi snapserver[1417]: Exception in StreamSession::reader(): read_some: End of file
Apr 12 16:15:32 raspberrypi snapserver[1417]: StreamServer::NewConnection: 192.168.1.118`

The first ones are from turning off wifi, the last one restarting snapserver.

![screenshot_20170412-182057](https://cloud.githubusercontent.com/assets/26249138/24968428/7f4d920e-1fad-11e7-8a5f-1a92807cabbc.png)
![screenshot_20170412-182356](https://cloud.githubusercontent.com/assets/26249138/24968429/7f551de4-1fad-11e7-910f-c01b4fe4e1ad.png)
![screenshot_20170412-182446](https://cloud.githubusercontent.com/assets/26249138/24968430/7f573ea8-1fad-11e7-96e2-0439e6e548b4.png)

**Comment by HVPereira** [comment]
I confirm the bug
