### ISSUE TITLE
Snapserver with multiple pipes

### ISSUE THREAD

**Issue by w3ssisback** [badaix/snapcast#234]
I'm new to linux so trying to see if anyone can guide me or if this is an actual issue,

I have 2 raspberry pi 3s.

1) Pi3#1 - Volumio (MPD output to tmp/snapfifo), Snapserver, Snapclient

Snapserver setting
SNAPSERVER_OPTS="-d -s pipe:///tmp/snapfifo?name=Library -s pipe:///home/pi/snapfifo?name=Radio"

2) Pi3#2 - Raspian Jessie (ALSA output to home/pi/snapfifo) - trying play radio links fom browser (works fine if I install snapserver in this box)
a) tried nfs and sshfs mount.  Can see the folder and snapfifo.  ALSA configured to output to the snapfifo but its not updating (timestamp remains the same while playing audio)

Any ideas how I can get this to work?  End result is I want to have multiple pipes to the same snapserver

**Comment by m-kloeckner** [comment]
I am not sure if I understood this correctly. Do you want to "send" the pipe input from Pi3#2 (/home/pi/snapfifo) over NFS/SSHFS to Pi3#1 to make it available to the snapserver on Pi3#1?

**Comment by w3ssisback** [comment]
Yes that's what I'm trying to do. 
home/pi/snapfifo is local to pi3#1 where the server is running.

I've mounted the folder home/pi in pi3#2 and sending Alsa output to that folder. 

When server is started on pi3#1 the 2 snapfifo files are created. Pi3#2 doesn't write to the snapfifo (has the correct permissions) If I delete the snapfifo in the home/pi/ folder a new snapfifo file is created by pi3#2 and the file keeps growing fast. No sound output when testing that pipe (radio) from a client

**Comment by zeekoe** [comment]
Snapcast is for synchronous playback in multiple rooms. It seems like what you're trying to do is multiple inputs to a single set of speakers. If that's the case, PulseAudio seems more fit for what you want. I'm quite sure it's in Jessie installed by default, if not it's easy to do so.
