### ISSUE TITLE
Bad playback sound after hours without problems

### ISSUE THREAD

**Issue by Mugridge** [badaix/snapcast#239]
The following simplified situation:
snapserver and snapclient 0.11.1 are running on a raspberry pi v3 with a current raspian jessie lite image  using mpd und mpc. The playlist contains approximately 100 mp3 tracks.
Server and client are starting at boottime, the playback  works fine for ours without any problems. Then suddenly the sound is getting bad, you can listen to it in the attached mp3-file called bad.mp3.zip (remove the .zip ending). The sound is only  getting good again after restarting the snapclient by typing 'sudo service snapclient restart', as you can hear in the file good.mp3.zip.
The problem also appears on a remote snapclient connected to the server. It doesn't depend on the server, because the local client ouput can be good during the remote client is bad at the same time or vice versa. 
Some things I recognized:
It doens't depend on the track, it always takes a few ours or longer until it occurs, there are no hints in the logfiles, it seems to be more often when  using a USB soundcard. Any idea how to solve or to analyse this problem?

[bad.mp3.zip](https://github.com/badaix/snapcast/files/973545/bad.mp3.zip)
[good.mp3.zip](https://github.com/badaix/snapcast/files/973546/good.mp3.zip)

**Comment by vjdw** [comment]
I think I've heard exactly the same problem. I haven't been using snapcast for long, and I've only had this issue twice, but both times it was on the same client, which is a Raspberry Pi with a USB soundcard. I have other Raspberry Pi clients, but none of those others use a USB soundcard, so I wonder if this is somehow the cause?

**Comment by miLORD1337** [comment]
I encountered the problem as well. USB soundcard, too. 
For me, pausing and then playing again works as well as restarting the service.

**Comment by LambdaDriver** [comment]
I encounter the same issue on a Raspberry Pi 2 using a wifi adaptor and USB DAC. Using Shairport-sync for the time being and not having any of those issues at all using the same hardware and OS setup. Sadly, I have nothing useful to offer in the way of troubleshooting

**Comment by badaix** [comment]
should be solved in more recent versions
