### ISSUE TITLE
Question - Connect to specific stream (rpi)

### ISSUE THREAD

**Issue by Saiyato** [badaix/snapcast#242]
Hi,

Not really an issue, just a question after being unable to find it googling (may be missing something though). Is it possible to connect to a specific stream using the snapclient on a rpi?

Configuring multiple server streams is covered, I can connect to the server when there's a single stream, but connecting to a specific stream using that streams name seems impossible? Am I missing something, or am I trying to achieve the impossible maybe?

**Comment by Saiyato** [comment]
I don't think I really understand, how do I assign the group to the client? For example my client options are:

SNAPCLIENT_OPTS="-d -h 192.168.178.118 -s BossDAC"

Should I add another parameter?

Thanks for the quick reply though! :)

**Comment by happyleavesaoc** [comment]
Use one of the available applications to change the grouping. For example, the Android app will do it. I'm pretty sure you can't adjust stream via the initial command line arguments.

**Comment by Saiyato** [comment]
I see thanks, I was indeed looking to pre-configure the client via de config file in /etc/default/. It does save me trouble not having the option though :P 

Thanks for clarifying, which explains why I couldn't find it anywhere.

**Comment by xiubert** [comment]
How are groups created?
I have multiple streams that show up upon systemctl status snapserver
Only one stream/group is displayed in the android app.
My server.json file in /var/lib/snapserver only displays 1 group with 1 id.
I can change the stream there and via telnet and rpc-api, but how do I create a new group so that I can create multiple zones?  How do I know what ID to use for a new group?

**Comment by yannok** [comment]
Hello,
xiubert, I am really interested to know how you have managed to stream from subsonic to snapcast (I see that you have a pipe named Subsonic so I guess you could make it work). 

I have been fighting with this for days now and the only solution I have found so far is sending the output to ALSA first then redirecting ALSA to /tmp/snapfifo, as explained in this post: 
http://forum.subsonic.org/forum/viewtopic.php?f=2&t=17256&p=75009&hilit=snapcast#
It works, yet, this solution is not very clean and I would prefer to output PCM RAW data directly to snapfifo. 
I have tried creating a jukebox player with the following unique transcoding settings: (from mp3 & flac to PCM)  
ffmpeg -y -ss %o -i %s -f u16le -acodec pcm_s16le -ac 2 -ar 48000 /tmp/snapfifo
but that raised a java exception (too long to post here ;-))

Could you share your knowledge? Thanks!

**Comment by xiubert** [comment]
hi yannok, when I used this combo for multi-room audio I used the same approach that was posted in that thread you noted.
