### ISSUE TITLE
MDNS service name for jsonrpc too long.

### ISSUE THREAD

**Issue by happyleavesaoc** [badaix/snapcast#243]
Service names can be a max of 15 bytes: https://tools.ietf.org/html/rfc6763#section-7.2

The name `snapcast-jsonrpc` is one byte too long. This causes issues with discovery tools that implement the standard.

**Comment by badaix** [comment]
damn, snapcast goes beyond the limits :flushed:
Thanks for the hint. Seems I've to shorten the name, and maybe announce the deprecated old name for compatibility with legacy control apps...

**Comment by maweki** [comment]
I stumbled upon this now as well. The python zeroconf module does not support this, while other implementations do (avahi-tools for example).

Maybe we can just advertise the service twice? Once with the legacy name and once with a short name (lacking the dash for example). Should not be a problem then and your code easily supports adding another service.
