### ISSUE TITLE
Alexa Skill for controlling volume / audio stream?

### ISSUE THREAD

**Issue by ThYpHo0n** [badaix/snapcast#245]
I just want to double check that no one has done that yet, am I right?
I'm curious and interested in programming my first Alexa Skill and would love to tell Alexa to switch to my Spotify stream in the kitchen or lower the volume by x percentage, mute y...
Do you know any other use cases?

**Comment by badaix** [comment]
I don't know of any Snapcast Alexa Skill.
What programming languages are supported by the Alexa Skill API?
Would be cool to have an SDK for the Snapcast JSON RPC API

**Comment by happyleavesaoc** [comment]
You just need an HTTP endpoint.

**Comment by johnkareoke** [comment]
I've done this. Will drop back with a recipe when I have a moment.

**Comment by Catscrash** [comment]
Hi,

@johnkareoke any news on this? Would be great!
