### ISSUE TITLE
[not an issue] Nice stuff

### ISSUE THREAD

**Issue by mrwhale** [badaix/snapcast#25]
Hey Just wanted to say awesome stuff! Was searching for a while to try and find something to close the gap on mopidy and multi-room playback. Will be awesome once you get "zones" working, wont have to fork out hundreds for sonos!

Anyway, this was pretty easy to install (probably should note that I had to upgrade my rpi's to Jessie, as the wheezy repo was too far behind on some of the dependancies) once that was done setup was super easy and playback started immediately!

Nice stuff

**Comment by badaix** [comment]
Thanks, glad you like it :grinning:

**Comment by linuxguy123** [comment]
+1 on this.   I've been looking for a way to do multi room audio forever.  So happy to see this.  I'll start testing shortly.

**Comment by obliquid** [comment]
just tested with mopidy and seems to work perfectly!
more testing to come, but thanks for your awesome work!

**Comment by cosmo6110** [comment]
Hi!
I running moode and mopidy on same device.
Disabled mpc for mopidy, change the RW on /tmp/snapfifio so both prog can write to the fifo.
Working great. :) 
Spotify from mopidy and radio and NAS streams from moode.
Thank's
keep up your good working!

**Comment by proffalken** [comment]
Adding to this as I don't know where else to post it, I've written a blog post on using Snapcast and Mopidy to do multi-room home audio:

https://hackerdads.wordpress.com/2016/05/07/multi-room-audio-with-open-source-software-and-cheap-hardware/

Thanks for all the hard work that's gone into this so far!

**Comment by cosmo6110** [comment]
Nice!
I got snapclient on a modded (8mb) TP-Link TL-WR703N.
It's working right of the box with openwrt and the snapclient.ipk file and Sabre USB DAC. :)
What to say more :)
Awesome!
Thank's @badaix

**Comment by ConnyOnny** [comment]
Can you please add the mplayer command line from @cosmo6110 to the Readme.md? It works and is very easy to do (especially in comparison with the mentioned MPD, ALSA etc. setups).

To utilize my Windows computer's speakers at a house party, I just boot a Xubuntu from a live USB. No need to hurry Windows support ;-)

And a big thank you for doing this project!

**Comment by badaix** [comment]
Added cosmo's mplayer command line: d3d3f2179c898292acdd3ff93d71b1393d91de65

**Comment by axelsimon** [comment]
@VanushVaswani it's a fully software based solution, not a specific hardware + software solution. Also, and just as importantly, it's fully free and open source.

@badaix Let's close this issue, to start cleaning up :)
