### ISSUE TITLE
Save group and client names

### ISSUE THREAD

**Issue by mray** [badaix/snapcast#251]
Whenever I restart the machine that runs snapserver I lose all my group names and client names. They should remain saved even after a start.

Is there a way to "hardcode" them somehow in a config file?

**Comment by badaix** [comment]
That one bothers me too. I'm on it. 
It is related to wrong permissions in `/var/lib/snapcast`

**Comment by badaix** [comment]
should be fixed 3e0e6f33d89d58def43675dcf4576c4184702fba

**Comment by ncordell** [comment]
How does one set the group name? I'm making the change manually in /var/lib/snapserver/server.json, but that doesn't seem to stick.

**Comment by rwjack** [comment]
Still trying to figure that out 5 years later :sweat_smile:
