### ISSUE TITLE
Snapserver does not respond

### ISSUE THREAD

**Issue by bilakos** [badaix/snapcast#252]
Hi there,

first of all a big thank you for that great piece of software. Best so far tested.

Now to the issue I am having. Here is my setup:
- 2 x Raspberry PIs (1 Pi3 and 1 Pi2)
- Hifiberry
- Mopidy 2.1.0
- Snapserver v 0.11.1
- Snapclient v 0.11.1

When I fresh start Mopidy, Snapserver and Snapclient all works great. I can start/stop snapclient and attach my 2 Pis to the stream. However, I have experienced now a couple of times after hours or days that when I try to attach a Pi back again to the stream by starting the Snapclient it fails. When i now restart the Snapserver everything works again. Here is log output from the  

Snapserver:
Jun 21 06:27:58 raspberrypi snapserver[12858]: Exception in ControlSession::reader(): read_until: End of file
Jun 21 06:27:58 raspberrypi snapserver[12858]: StreamServer::NewConnection: 192.168.0.113
Jun 21 06:27:58 raspberrypi snapserver[12858]: Session inactive. Removing
Jun 21 06:28:04 raspberrypi snapserver[12858]: ControlServer::NewConnection: 192.168.0.113
Jun 21 06:28:06 raspberrypi snapserver[12858]: Exception in StreamSession::reader(): read_some: End of file
Jun 21 06:28:06 raspberrypi snapserver[12858]: Exception in ControlSession::reader(): read_until: End of file
Jun 21 06:28:09 raspberrypi snapserver[12858]: ControlServer::NewConnection: 192.168.0.113
Jun 21 06:28:09 raspberrypi snapserver[12858]: Session inactive. Removing
Jun 21 06:28:11 raspberrypi snapserver[12858]: Exception in ControlSession::reader(): read_until: End of file
Jun 21 06:28:11 raspberrypi snapserver[12858]: StreamServer::NewConnection: 192.168.0.113
Jun 21 06:28:11 raspberrypi snapserver[12858]: Session inactive. Removing
Jun 21 06:28:27 raspberrypi snapserver[12858]: ControlServer::NewConnection: 192.168.0.113
Jun 21 06:28:28 raspberrypi snapserver[12858]: Exception in StreamSession::reader(): read_some: End of file
Jun 21 06:28:29 raspberrypi snapserver[12858]: Exception in ControlSession::reader(): read_until: End of file
Jun 21 06:28:31 raspberrypi snapserver[12858]: ControlServer::NewConnection: 192.168.0.113
Jun 21 06:28:31 raspberrypi snapserver[12858]: Session inactive. Removing
Jun 21 06:28:31 raspberrypi `snapserver[12858]:`

and here from the Snapclient:
```
Jun 21 06:28:05 raspberrypi systemd[1]: Stopping Snapcast client...
Jun 21 06:28:05 raspberrypi snapclient[12137]: Received SIGTERM signal.
Jun 21 06:28:06 raspberrypi snapclient[12137]: daemon terminated.
Jun 21 06:28:06 raspberrypi systemd[1]: Stopped Snapcast client.
Jun 21 06:28:11 raspberrypi systemd[1]: Starting Snapcast client...
Jun 21 06:28:11 raspberrypi snapclient[12199]: daemon started
Jun 21 06:28:11 raspberrypi systemd[1]: Started Snapcast client.
Jun 21 06:28:11 raspberrypi snapclient[12199]: Connected to 192.168.0.101
Jun 21 06:28:11 raspberrypi kernel: [291000.796615] pcm512x 1-004d: No SCLK, using BCLK: -2
Jun 21 06:28:28 raspberrypi systemd[1]: Stopping Snapcast client...
Jun 21 06:28:28 raspberrypi snapclient[12199]: Received SIGTERM signal.
Jun 21 06:28:28 raspberrypi snapclient[12199]: daemon terminated.
Jun 21 06:28:28 raspberrypi systemd[1]: Stopped Snapcast client.
Jun 21 06:28:32 raspberrypi systemd[1]: Starting Snapcast client...
Jun 21 06:28:32 raspberrypi snapclient[12257]: daemon started
Jun 21 06:28:32 raspberrypi systemd[1]: Started Snapcast client.
Jun 21 06:28:32 raspberrypi snapclient[12257]: Connected to 192.168.0.101
Jun 21 06:28:33 raspberrypi kernel: [291022.525460] pcm512x 1-004d: No SCLK, using BCLK: -2
```

**Comment by bilakos** [comment]
Is there any way I can increase the debug level of snapserver in order to get more detailed information why it requires a restart ?

**Comment by bilakos** [comment]
No ideas ?

**Comment by zeekoe** [comment]
No help (at least not yet) from me, but I've had problems for quite some time that if I first start the client, then the server, then I need to restart the server for all to work well - else no sound. That's been with a version of around 1 year old. Now I also occasionally have no sound, randomly. I didn't bother checking logging yet, but maybe this might help you in your search...

**Comment by bilakos** [comment]
Thanks for your reply zeekoe. Strange behaviour.

Had this issue again a couple of times and sometimes it works with restarting the server and sometimes I have to restart the whole chain (Mopidy, Server, Client) to make it work again.

Appreciate further answers on this. Debugging support would also help, probably I can figure it out if I know how to turn on verbose logging mode.... But so far no idea how to increase debug level.

Regards,
Bilakos

**Comment by bilakos** [comment]
Hmmm.... Still no one with an idea.....

**Comment by palitu** [comment]
I have set up a cron job to restart the server every night.  seems to reduce the frequency of it causing issues.
