### ISSUE TITLE
Librespot

### ISSUE THREAD

**Issue by atze09** [badaix/snapcast#256]
Hello guys,
my setup stopped to work of course the spotify update.
i have now updated snapserver and client to version 0.11.1 but hadn't had success with the librespot update/compiling.
Can anyone help me and provide the latest libresport suitable for RPi3?
That would be awesome!
i love my setup with volumio2 snapcast and librespot, that was awesome.
Thank you in advance.
Regards,
Dominik
'

**Comment by twenta** [comment]
Try this one, I built it on a raspi2, but should work too
http://www79.zippyshare.com/v/6jGaDa9e/file.html
md5: 8664e579d67c71464b23df8c0f44965d
