### ISSUE TITLE
Making Mopidy-based multiroom speaker client and server at the same time

### ISSUE THREAD

**Issue by buzink** [badaix/snapcast#26]
Say I have several Mopidy-based Raspberry Pi's I use as multiroom speakers. Is it possible to play the audiostream from one of them through its speaker AND at the same time transmit it via the snapcast server to the other pi's? Something like this:

     Mopidy on device1 -> snapcast server on device 1 -> snapcast client on device1 -> autoaudiosink on device 1
                                                      -> snapcast client on device2 -> autoaudiosink on device 2
                                                      -> snapcast client on device3 -> autoaudiosink on device 3

The goal would be not to need a seperate server device for multiroom streaming, but to be able to use any speaker as the server while at the same time playing the multiroom stream on that speaker locally. Together with some kind of way to set the Mopidy output remotely on each device this could create a user friendly synchronised multiroom experience. You start playing a Spotify playlist in your bedroom and stream it to the bathroom. But you could also start in the kitchen, etc.

**Comment by mrwhale** [comment]
Just install both the snapcast server and client and it will stream to itself (like in your diagram) That's one way, or you can tell mopidy to output to snapfifo AND to local device (using tee command, can give example if you need), although this method may not be in sync with the other audio receivers as the server will receive the audio lots quicker then the recievers, but i've not tested this way

**Comment by buzink** [comment]
Thanks. The first option sounds good. I will try that as soon as I have set up my second Raspberry Pi.
