### ISSUE TITLE
Exception in StreamSession::reader(): read_some: End of file

### ISSUE THREAD

**Issue by atze09** [badaix/snapcast#265]
Hello guys,
I have a problem with my snapclient 0.11.1 on my RPi3 Volumio2 system.
I got the following issues after restart.
"Exception in StreamSession::reader(): read_some: End of file"

Other clients on my servers are working but the client on the server does not work.
Can anyone help me?
Thank you in advance
Best Regards,
Dominik

**Comment by tringler** [comment]
Hello Dominik,

I had the same issue solved with https://github.com/badaix/snapcast/issues/229#issuecomment-328167681
