### ISSUE TITLE
Client grouping

### ISSUE THREAD

**Issue by pdcmoreira** [badaix/snapcast#266]
Hi, I haven't tested snapcast yet, but I'm trying to figure out if some grouping streams would be possible, so my question is, is there a way to do the following requests on demand, maybe throught the JSON-RPC Api?

- Get list of connected clients
- Get list of created streams
- Delete a stream
- Create stream S1 with clients C1, C3 associated
- Create stream S2 with clients C2 associated
- Create stream S3 with clients C4, C5, C6 associated

I'm assuming that writing to the S1 stream, it would play on C1 and C3 clients in sync, writing to the S2 stream, it would play on C2 client (alone) and writing to the S3 stream, it would play on C4, C5 and C6 clients in sync.

**Comment by badaix** [comment]
yes, this is possible with the JSON-RPC API
