### ISSUE TITLE
snapserver crash

### ISSUE THREAD

**Issue by DaLinuxBua** [badaix/snapcast#267]
My Setup:
Running snapserver with 3 streams (MPD) as service on Linux (Ubuntu)

Problem:
When scanning the server with nmap from another machine, snapserver crashes and I need to manually start it again.

I am not sure if this only happens on my machine, maybe someone can try it out.

**Comment by badaix** [comment]
what parameters are you using for nmap?

**Comment by DaLinuxBua** [comment]
I did a portscan with -p-:
` nmap -p- 1.2.3.4`

Snapserver crash when scanning one of it's ports (1704 or 1705), changing to another port does not help.

Crash:
nmap -p- 1.2.3.4
nmap -p1704 1.2.3.4
nmap -p1705 1.2.3.4
...

No crash:
nmap -p-1703,1706- 1.2.3.4

**Comment by badaix** [comment]
fixed b1edc34f6e81f37c637f8f326e4d1708e0705fa1
