### ISSUE TITLE
rtsp stream as snapcast server

### ISSUE THREAD

**Issue by tringler** [badaix/snapcast#268]
Hello,

it is possible to pipe a rtsp stream into a snapcast server in any way? Thanks in Advance, Thomas

**Comment by mczerski** [comment]
You can use gstreamer to receive rtsp stream and direct it to snapfifo:
/usr/bin/gst-launch-1.0 rtspsrc location=rtsp://<url> ! decodebin ! audioresample ! audioconvert ! audio/x-raw,rate=48000,channels=2,format=S16LE ! wavenc ! filesink location=/tmp/snapfifo
