### ISSUE TITLE
snapcast server on android

### ISSUE THREAD

**Issue by erwanj** [badaix/snapcast#271]
Hello,

would it possible/feasible to have snapcast server on android so that we can stream from any android app?

Thank you for the great application.

Erwan

**Comment by psamim** [comment]
That would be great.

**Comment by badaix** [comment]
The good news: snapserver compiles and runs on Android
The bad news: you will need a at least a rooted device to redirect audio to the Snapserver. For this there is no standard way (as for example discussed on [stackoverflow](https://stackoverflow.com/questions/21024851/redirecting-audio-creating-alternate-sound-paths-in-android).

**Comment by guerman5** [comment]
Hi @badaix 
You've done an amazing tool, its beautiful! I thank you from the deepest of my heart. 
I've been playing weeks non-stop between RPi and old phones (rooted Androids and iPhones) with mpd and snapcast.

My use case is to be able to ride bicycle while broadcasting sync audio with snapserver, all my buddies can simply connect to a wifiAP and run snapclient on their phones. In practice, this is a Wifi radio I'm trying to put together.

From all the frankensteins i've built, an RPi3 with RaspAP, mpd, and Snapcast server, plus a 2TB harddrive all plugged into a 4x26650 battery pack seemed to be the one answer. 
A power instability issue emerged. The RPi battery pack was supposed to keep a stable 5.1+ voltage, but it doesn't, only running RaspAP without any external drive is enough to drop the network.

Then I tried an android with an OTG cable, battery and hhd and they can sustain operability. Wifi hotspot with mpd broadcasting on httpd. But the magic of snapcast is missing.

Then I wondered, could Android run snapserver? just as mpd in termux can do httpd.
I've found your post as a ray of light. _How can I compile snapserver for Android?_

If you read this far, thank you again.

**Comment by StuartIanNaylor** [comment]
@badaix https://developer.android.com/guide/topics/media/av-capture

Has this changed with [AudioPlaybackCapture API](https://developer.android.com/guide/topics/media/playback-capture) was introduced in Android 10 ?

As hell yes snapserver on android!

**Comment by pvi-github** [comment]
Hello there... 

Can we now have hopes about seing Sanpcast server run on android without rooting the phone ?

Kind regards,

**Comment by rfenouil** [comment]
Hi, Thanks for this great tool !

I would like to upvote this issue (or event better a server embedded in android snapcast app), that would make snapcast the ultimate solution for home audio :)
