### ISSUE TITLE
Snapcast fails to build under Arch Linux on ARM6vh (BCM2835)

### ISSUE THREAD

**Issue by slackline** [badaix/snapcast#274]
Fantastic piece of software, so much easier than using RTP sinks.  Bought a couple of Pi Zero W to extend music around the house and have found the build I'm using from the AUR repository (see https://aur.archlinux.org/packages/snapcast/) fails on the Pi Zero W with the following error(s)...

==> Starting build()...
make -C client
make[1]: Entering directory '/home/neil/build-repos/snapcast/src/snapcast/client'
g++ -march=armv6 -mfloat-abi=hard -mfpu=vfp -O2 -pipe -fstack-protector-strong -fno-plt  -std=c++0x -Wall -Wno-unused-function -O3 -DASIO_STANDALONE -DVERSION=\"0.11.1\" -I. -I.. -isystem ../externals/asio/asio/include -I../externals/popl/include -pthread -DHAS_OGG -DHAS_ALSA -DHAS_AVAHI -DHAS_DAEMON -o snapclient snapClient.o stream.o clientConnection.o timeProvider.o player/player.o decoder/pcmDecoder.o decoder/oggDecoder.o decoder/flacDecoder.o controller.o ../message/pcmChunk.o ../common/log.o ../common/sampleFormat.o player/alsaPlayer.o browseZeroConf/browseAvahi.o -lrt -lasound -logg -lvorbis -lFLAC -lavahi-client -lavahi-common -static-libgcc -static-libstdc++
controller.o: In function `Controller::worker()':
controller.cpp:(.text+0x1d58): undefined reference to `__atomic_load_8'
stream.o: In function `Stream::getPlayerChunk(void*, std::chrono::duration<long long, std::ratio<1ll, 1000000ll> > const&, unsigned long)':
stream.cpp:(.text+0x2af4): undefined reference to `__atomic_load_8'
stream.cpp:(.text+0x2d3c): undefined reference to `__atomic_load_8'
stream.cpp:(.text+0x3a7c): undefined reference to `__atomic_load_8'
stream.cpp:(.text+0x45c4): undefined reference to `__atomic_load_8'
timeProvider.o: In function `TimeProvider::setDiffToServer(double)':
timeProvider.cpp:(.text+0x244): undefined reference to `__atomic_store_8'
timeProvider.cpp:(.text+0x2e0): undefined reference to `__atomic_store_8'
timeProvider.o: In function `TimeProvider::setDiff(tv const&, tv const&)':
timeProvider.cpp:(.text+0x6a8): undefined reference to `__atomic_store_8'
timeProvider.cpp:(.text+0x73c): undefined reference to `__atomic_store_8'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:70: snapclient] Error 1
make[1]: Leaving directory '/home/neil/build-repos/snapcast/src/snapcast/client'
make: *** [Makefile:9: client] Error 2
==> ERROR: A failure occurred in build().
    Aborting...

If its something that might be related to gcc/cmake/etc. versions please let me know and I'll dig them out (not so familiar with Arch Linux as I normally use Gentoo where it builds from source fine, although thats on amd64 chipset).

Thanks,

slackline

**Comment by IVData** [comment]
Seems like this is the same as #255

**Comment by slackline** [comment]
Thank you for the cross reference, hadn't found this when searching (and missed its reference in the [AUR comments](https://aur.archlinux.org/packages/snapcast/) despite reading the rest of the comment to see that its the same error, oops!).
