### ISSUE TITLE
snapcast keeps turning on and off

### ISSUE THREAD

**Issue by bachoo786** [badaix/snapcast#276]
Just installed snapcast on my raspberry pi 2 and it keeps turning on and off. Can someone please help? 

Thanks.

**Comment by nealda4** [comment]
Need a little more data than that.  The audio keeps turning on and off or the raspberry pi keeps rebooting?

**Comment by IVData** [comment]
Have you installed snapserver, snapclient, or both on the pi? What is your audio source and how is it set up? What options have you set in snapcast?

**Comment by bachoo786** [comment]
@nealda4 I have download the snapcast app on my android and under the client list I see my raspberry pi which keeps turning on and off i.e. it keeps dissappearing and coming back on. This happens every 5-10 seconds.

@IVData I followed the instructions on how to install on raspberry pi and I have installed it both as a server and as a client. 

I cannot connect to the snapcast server as it keeps disappearing so I do not have an audio source at present. I tried playing a random file (following the instructions) from the raspberry pi but I couldn't hear anything.

I am fairly new to this and a noob so please bear with me.

**Comment by nealda4** [comment]
Are you attempting to stream audio to the android app or do you have a speaker connected to the raspberry pi?

is the raspberry pi rebooting during this process?

**Comment by bachoo786** [comment]
I have a speaker connected to raspberry pi. 

The raspberry pi is not rebooting. Just that on the Android app I can see the raspberry pi disappearing every 5 to 10 seconds and coming back on.

**Comment by nealda4** [comment]
i've not used the android app yet.  But perhaps the problem can be isolated.  Is there any syslog output on the raspberry pi for the snapserver?  If not or you cannot find it, can you run the snapserver manually in a terminal connection?  That should provide output.

**Comment by bachoo786** [comment]
How do I do that? And how can I get the log?

**Comment by nealda4** [comment]
the snapserver and client logs use the syslog.  common way to debug using the syslog is to use the _tail_ command and follow the output while running.
log into the rpi and run something like:
`tail +0 -f /var/log/syslog | grep -e snap`

**Comment by bachoo786** [comment]
this is what I get: tail: cannot open ‘+0’ for reading: No such file or directory
```
Sep 23 23:01:41 raspberry snapclient[737]: Exception in Controller::worker(): sum timeout exceeded 10s
Sep 23 23:01:41 raspberry snapserver[742]: Exception in StreamSession::reader(): read_some: End of file
Sep 23 23:01:42 raspberry snapclient[737]: Connected to 192.168.0.8
Sep 23 23:01:42 raspberry snapserver[742]: StreamServer::NewConnection: 192.168.0.8
Sep 23 23:01:54 raspberry snapclient[737]: Exception in Controller::worker(): sum timeout exceeded 10s
Sep 23 23:01:54 raspberry snapserver[742]: Exception in StreamSession::reader(): read_some: End of file
Sep 23 23:01:55 raspberry snapserver[742]: StreamServer::NewConnection: 192.168.0.8
Sep 23 23:01:55 raspberry snapclient[737]: Connected to 192.168.0.8
Sep 23 23:01:58 raspberry snapclient[737]: Exception in Controller::worker(): sum timeout exceeded 10s
Sep 23 23:01:58 raspberry snapserver[742]: Exception in StreamSession::reader(): read_some: End of file
Sep 23 23:01:59 raspberry snapclient[737]: Connected to 192.168.0.8
Sep 23 23:01:59 raspberry snapserver[742]: StreamServer::NewConnection: 192.168.0.8
Sep 23 23:02:01 raspberry snapclient[737]: Exception in Controller::worker(): sum timeout exceeded 10s
Sep 23 23:02:01 raspberry snapserver[742]: Exception in StreamSession::reader(): read_some: End of file
Sep 23 23:02:02 raspberry snapclient[737]: Connected to 192.168.0.8
Sep 23 23:02:02 raspberry snapserver[742]: StreamServer::NewConnection: 192.168.0.8
```
192.168.0.8 is the ip address of my pi on my network

**Comment by bachoo786** [comment]
any idea?

**Comment by badaix** [comment]
this `sum timeout exceeded 10s` message might hide the real cause. If you use the develop version, there might be a different reason logged. For example when the Client cannot properly open the DAC.
Please try the following: kill snapclient on the console: `sudo killall snapclient` and start the client manually (just call `snapclient`). There you can see some more debug output that could help to identify the problem.
Does the client reconnect only if audio is playing (i.e. the random file in your case)?

**Comment by bachoo786** [comment]
@badaix nope the client keeps on reconnecting. I have tried the random file and cannot hear anything !
Here is my log after killing snapclient on the console and starting it manually.

```
pi@raspberry:~ $ snapclient
2017-09-27 16-18-00 [out] (Browser) NEW: service 'Snapcast' of type '_snapcast._                                                                                      tcp' in domain 'local'
2017-09-27 16-18-00 [out] (Browser) CACHE_EXHAUSTED
2017-09-27 16-18-00 [out] Service 'Snapcast' of type '_snapcast._tcp' in domain                                                                                       'local':
2017-09-27 16-18-00 [out]       raspberry.local:1704 (192.168.0.8)
2017-09-27 16-18-00 [out] Found server 192.168.0.8:1704
2017-09-27 16-18-00 [out] Latency: 0
2017-09-27 16-18-00 [out] Connecting
2017-09-27 16-18-00 [Notice] Connected to 192.168.0.8
2017-09-27 16-18-00 [out] My MAC: "64:66:b3:23:15:9e", socket: 6
2017-09-27 16-18-01 [out] ServerSettings - buffer: 1000, latency: 0, volume: 100                                                                                      , muted: 0
2017-09-27 16-18-01 [out] Codec: flac
2017-09-27 16-18-01 [state] sampleformat: 48000:16:2
2017-09-27 16-18-01 [out] frames: 1440
2017-09-27 16-18-01 [out] Failed to get chunk
2017-09-27 16-18-01 [out] diff to server [ms]: 0
2017-09-27 16-18-06 [out] No chunk received for 5000ms. Closing ALSA.
2017-09-27 16-18-06 [out] time sync main loop
2017-09-27 16-18-11 [out] time sync main loop
2017-09-27 16-18-16 [out] time sync main loop
2017-09-27 16-18-21 [out] time sync main loop
2017-09-27 16-18-26 [out] time sync main loop
2017-09-27 16-18-31 [out] time sync main loop
2017-09-27 16-18-36 [out] time sync main loop
2017-09-27 16-18-41 [out] time sync main loop
2017-09-27 16-18-46 [Debug] 2017-09-27 16-18-51 [out] time sync main loop
2017-09-27 16-18-56 [out] time sync main loop
2017-09-27 16-19-01 [out] time sync main loop
2017-09-27 16-19-06 [out] time sync main loop
2017-09-27 16-19-11 [out] time sync main loop
2017-09-27 16-19-16 [out] time sync main loop
2017-09-27 16-19-21 [out] time sync main loop

```

the `time sync main loop ` keeps on going forever every 5 seconds.

**Comment by badaix** [comment]
the log looks like a normal idle client log (i.e. no audio is played)

**Comment by bachoo786** [comment]
Well but it keeps on disappearing as mentioned in my first post. 

And you think my log is fine? 

Wonder what "failed to get chunk" means?

**Comment by badaix** [comment]
The server splits audio into chunks and sends those chunks to the client. If playback is paused or stopped, this message will be logged. The client is waiting for new chunks and keeps synchronizing it's time with the server.
Could it be that systemd restarted the client so that you ended up with two clients?
Please try to stop the client not with a `kill` but with a `sudo service snapclient stop`, and then start another one on the command line.

**Comment by totti2** [comment]
Had the same issue...then... I realized my Snapclient-conf was empty -.-
I needed at least the `-h <IP.to.Snap.Server> argument.
