### ISSUE TITLE
Is this still being developed? as i love it

### ISSUE THREAD

**Issue by palitu** [badaix/snapcast#278]
I have noticed that development has stopped for the last 6 months.  Is that the end of snapcast?

I use it at home and i was looking at using it as a PA system for a 3rd world hospital, but if it is not being developed further i will have to look at a commercial solution.

i hope it isn't dead! as this is great.

**Comment by renearts** [comment]
As far as I know this is still quite actively developed. Have a look at the development branch, last commit was 5 days ago. Also the issue tracker shows a lot of activity. So I guess you shouldn't worry.

**Comment by badaix** [comment]
No worries, I'm just busy with other stuff. 
Snapcast is still running 24/7 @ home (I'm one of the biggest fans :wink:) and there are already some small fixes in develop branch, which I should turn into a release soon.

**Comment by synth3tk** [comment]
That's a relief. I'm looking to eventually get Snapcast setup and integrated with Home-Assistant, but the lack of a recent release gave me pause. I never thought to check the development branch.

**Comment by palitu** [comment]
yeah - didnt check the dev branch either.

@badaix - i have it running at home, though i am currently in Kiribati.  There hospital needs a PA system and im thinking that snapcast will work a treat for them to be able to use a push-to-talk microphone and pipe that to all the remote clients.  

Is there a web based control client that i could set them up with?

Thanks, and looking forward to the next release!

**Comment by badaix** [comment]
@palitu There are some web controls mentioned here: #116. I don't know if they will fit your needs.

**Comment by badaix** [comment]
Well, I'm using the v0.12 at home and it's released now since 16 days without any bug related to it (except #294, which I was not able to reproduce yet). So I would consider it stable.

**Comment by slackline** [comment]
Hi @palitu ,

I was wondering how you've fared with implementing Snapcast for hospital PA systems?

My father-in-law wishes to synchronise audio to additional rooms in a few churches he's involved with and has asked my advice as he was impressed with my deployment of Snapcast on Pi's at home for syncing audio in multiple rooms (and thank you @badaix for writing and maintaining Snapcast, its brilliant and everyone who I show the system to is impressed).

The main challenge I think will be getting things to fit in with the existing systems which I suspect places will be reluctant to ditch (would be great if I could say "Get a Pi + iQaudio DAC+ as master for each center and Pi-Zero W + iQaudio DAC+ for each additional room at each church).  Thus I was curious if or how you've integrated Snapcast into existing PA systems.

Thanks in advance and no worries if you've not done anything but I thought I'd ask.

Cheers,

slackline

**Comment by palitu** [comment]
@slackline, thanks for your interest

Unfortunately I am not integrating into an existing PA system.

What i have so far:
1. RPi as snapserver
1. a USB microphone with Push-to-talk
1. pulse audio loop-back device to send the microphone to the snapcast sink
1. cpiped to mute and unmute individual devices (cpiped tends to cause a number of breaks due to the way it is architected.  I am just using it currently to mute/unmute)

for each client, they are pretty straight forward
1. OPi Zero with case and Anologue output board
1. Speaker
1. power supply
1. wired ethernet

One thing that i am noticing is that data transfer per client is starting to creep up - and with 20+ nodes, that may start to cause issues on their network.

So far - i have tested up to 5 clients.

There are a number of things that you could do - inpout from existing system into server.

My biggest issue is the lack of webUI to control and discover Nodes.

Good luck!

**Comment by slackline** [comment]
@palitu thanks for the write-up thats all useful information.  

The biggest challenge I can see so far is where a Raspberry Pi slots into the existing system.  Useful to know that you can loop-back pulse-audio into snapserver, and as you say the rest (clients) are pretty straight forward.

Challenge will be that there are multiple heterogenous setups and my father-in-law is at the other end of the country.  I'm sure that can be overcome though one system at a time.

**Comment by SymanK83** [comment]
@palitu My first take of a web UI based on Node and angular is mostly done. If you are interested I could share the approach.

**Comment by palitu** [comment]
I'd Love it!

cheers

**Comment by SymanK83** [comment]
I‘ll get back to you in the next few days.
It‘s still a very rough cut and pretty ugly, but operational ;-)

**Comment by palitu** [comment]
ta

**Comment by SymanK83** [comment]
Hi @palitu, sorry, this took much longer than anticipated.
I had some issues with the telnet connection. This interface is pretty ugly, but it works for me until I have time for it. Basically the server prepares the snapserver data for the web ui and vice versa. The UI displays the different elements available in the snapcast environment in rows (streams, groups, clients). You can drag streams to groups to make the group play that stream. And you can drag and drop clients to groups (splitting groups does not yet work). The upper row is meant to link to a static list of players (e.g. Mopidy Iris frontends).
<img width="1323" alt="ohne titel" src="https://user-images.githubusercontent.com/20001548/37373826-9591b450-2718-11e8-8eab-5937612c9608.png">
https://github.com/SymanK83/simos

**Comment by palitu** [comment]
I like how you are thinking of the interface - not sure on the pink, but that is another topic ;)

Thanks, i will try and find some time to have a play.

**Comment by SymanK83** [comment]
I can relate to the color topic. I was hoping for my wife to be more inclined to use it. that worked ;-)
It‘s a heavy work in progress, and I‘m optimistic to make something worthwhile for daily use. Snapcast is a great platform for that. Maybe in a few weeks it will be worth showing to a wider audience using Snapcast and getting some feedback.
I‘m highly anticipating yours.
