### ISSUE TITLE
Distorted sound in combination with Mopidy on Pi Musicbox

### ISSUE THREAD

**Issue by buzink** [badaix/snapcast#28]
I installed Snapserver and client on my Pi Musicbox in preparation of a multiroom setup as described in issue https://github.com/badaix/snapcast/issues/26. The sound of Mopidy comes out of the speakers without much stuttering for most radio streams, but it is in all streams noticeably distorted. It's like the radio presenters are on antidepressants; they speak slower and lower. 

Could you point me in the right direction to debug and experiment with settings until its good again? I assume it has something to do with the sample rates, but I have only basic knowledge of digital sound and don't know where to start.  (I don't use pulseaudio by the way, so its not issue https://github.com/badaix/snapcast/issues/16).

**Comment by badaix** [comment]
Snapcast expects some (configurable) fixed sample rate (v0.4.x 44.1 kHz, v0.5 48 kHz).
You can configure resampling to 44.1 kHz in your `mopidy.conf` like this:
```
[audio]
#output = autoaudiosink
output = audioresample ! audioconvert ! audio/x-raw,rate=44100,channels=2,format=S16LE ! wavenc ! filesink location=/tmp/snapfifo
```
