### ISSUE TITLE
[MAC OS] client & server fail compiling on current master / develop

### ISSUE THREAD

**Issue by ThYpHo0n** [badaix/snapcast#286]
Just to raise awareness, didn't had a deeper look into that but these are the following errors:
Client:
> In file included from ./controller.h:29:
> ./player/alsaPlayer.h:23:10: fatal error: 'alsa/asoundlib.h' file not found
> #include <alsa/asoundlib.h>
>          ^~~~~~~~~~~~~~~~~~
> 1 warning and 1 error generated.
> make: *** [snapClient.o] Error 1

Server:
> ./publishAvahi.h:23:10: fatal error: 'avahi-client/client.h' file not found
> #include <avahi-client/client.h>
>          ^~~~~~~~~~~~~~~~~~~~~~~
> 3 warnings and 1 error generated.
> make: *** [snapServer.o] Error 1

On tags/v0.11.1 compiling works fine.

**Comment by badaix** [comment]
I recently compiled it for MAC OS. Did you forget to pass the `TARGET=MACOS` switch to make?

**Comment by ThYpHo0n** [comment]
Strange, I did pass the TARGET=MACOS and also checked out the submodules.

**Comment by badaix** [comment]
I tried again and could compile `master` without any issues: `make TARGET=MACOS -j 4`

**Comment by ThYpHo0n** [comment]
Current master is working fine for me now, thanks!

@badaix What do you think about adding TravisCI? Then we can build automatically agains gcc on Linux + Mac? I would be more than happy to create a PR with that :)

**Comment by badaix** [comment]
In a weak moment I was actually thinking of adding TravisCI, so I would really appreciate it!
Also I'm planning to swap from make to CMake. There are already at least two forks using CMake. I don't know when and what this would mean for TravisCI, but I guess it will not be a big effort to change this.
