### ISSUE TITLE
 Address family not supported by protocol

### ISSUE THREAD

**Issue by freedreamer82** [badaix/snapcast#288]
HI,

I compiled snapcast from sources with a raspbery pi 3.
Starting the server i have

[Err] Exception: open: Address family not supported by protocol

Any tips ?

thanks

**Comment by freedreamer82** [comment]
find a way to start it.
I modded the srcs in order to support again ipv4 : as a matter of fact if i revert this commit it works 5f06f705629624a7800a7081b6559a806bfa4cd0

On my machine there is no ipv6 support , I believe that we should check before binding to "::".

**Comment by badaix** [comment]
do you know how to reproduce this with a standard raspbian?
I tried `sudo sh -c 'echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6'`, but it's still working

**Comment by badaix** [comment]
should be fixed now 1a51833f0

**Comment by freedreamer82** [comment]
yes , solved.
thanks!
