### ISSUE TITLE
python client

### ISSUE THREAD

**Issue by happyleavesaoc** [badaix/snapcast#29]
Hi, I wrote a python client for snapcast (develop branch). It is still experimental, so it doesn't yet have synchronization. Decode and playback works via GStreamer 1.0.

There's also a module for control server communication.

https://github.com/happyleavesaoc/python-snapcast

**Comment by badaix** [comment]
Hi, really cool that you're working on the remote control!
As a general comment: the json remote control API is still under development and not yet final. As you might have noticed, lately I've e.g. changed the prefix `System.` to `Server.` 
What's also missing is a documentation of available commands and responses.

**Comment by happyleavesaoc** [comment]
Yes, I will continue to adapt the implementation to API changes. It is up to date as of 0.5.0-beta-1 right now.

**Comment by badaix** [comment]
I've started with this control protocol [spec](https://github.com/badaix/snapcast/blob/develop/control/spec.md). It's by far not complete or helpful, but rather a placeholder

**Comment by happyleavesaoc** [comment]
Note that I've updated my python control module to work with 0.6.0.
