### ISSUE TITLE
Prebuilt .ipk on LEDE

### ISSUE THREAD

**Issue by 1337sup3rh4x0r** [badaix/snapcast#290]
Will the prebuilt ipk from the releases section work for LEDE or do I have to build my own?

**Comment by badaix** [comment]
I have no clue. I would just try it out.

**Comment by 1337sup3rh4x0r** [comment]
hrmpf...
Something for the weekend then ;)

**Comment by badaix** [comment]
I thought that LEDE is discontinued and will be integrated back into OpenWRT :thinking: 
Please give an update when you found out if it's running on LEDE or not

**Comment by slackline** [comment]
LEDE will be the code base for the merge of OpenWRT and LEDE, the combined project will then go under the name of OpenWRT.  The last (v3) merge proposal I could find is quoted in [this post on the openWRT-devel mailing list](https://lists.openwrt.org/pipermail/openwrt-devel/2017-June/043104.html).

Progress seems to be *very* slow on merging, last post following up the above from June on the developer mailing list was in [September](https://lists.openwrt.org/pipermail/openwrt-devel/2017-September/043191.html).  [This post](https://www.reddit.com/r/openwrt/comments/76pfj5/an_open_letter_to_the_openwrtlede_devs_regarding/doh1m8x/) on reddit has some insight.

With regards to whether the prebuilt `snapserver_0.12.0_ar71xx.ipkg` or `snapclient_0.12.0_ar71xx.ipkg`  will work under LEDE there is, I think, a big clue in the name as the `ar71xx` suggests to me that they are built for routers with a specific chip.  There are [multiple targets](https://downloads.lede-project.org/releases/17.01.4/targets/) and [ar71xx](https://downloads.lede-project.org/releases/17.01.4/targets/ar71xx/) is one of many.  Unless your router has this chip/arch and you've installed the ar71xx branch of LEDE I expect you will have to [cross-compile your own](https://github.com/badaix/snapcast/blob/master/doc/build.md#openwrtlede-cross-compile).

I've a Linksys WRT1900ACSv2 which is [mvebu](https://downloads.lede-project.org/releases/17.01.4/targets/mvebu/) target so I doubt the packages will work for me (although I've not tried as I run snapserver on my Raspberry Pi2).

**Comment by badaix** [comment]
Thanks for the insights about the OpenWRT/LEDE status.
This is of course true: the ar71xx release is tailored for my good old [TL-WR1043ND v1](https://wiki.openwrt.org/toh/tp-link/tl-wr1043nd) router with an Atheros AR9132 SoC

**Comment by 1337sup3rh4x0r** [comment]
I still haven't come around to testing this with LEDE.

My TL-WR710N are currently running OpenWRT and there the prebuilt ipk is working fine.

I just don't want to update them to LEDE now to find out that it's not working there. I need Music! ;)
For this I want to plan some more time so I can also go through the manual cross compile process just in case.

**Comment by ns-ctru** [comment]
As much as you like music there is another very good reason to upgrade to LEDE-17.01.4 as it has had the [KRACK vulnerability patched](https://lede-project.org/releases/17.01/notes-17.01.4), although as noted you still need to patch any clients too.

**Comment by badaix** [comment]
That's interesting. LEDE really seems to have some regular releases :)

The latest OpenWRT for my router (and all others) is 19 month old:  
openwrt-15.05.1-ar71xx-generic-tl-wr1043nd-v1-squashfs-factory.bin
15-Mar-2016 17:48

while there was a LEDE release last week:  
tl-wr1043nd-v1-squashfs-factory.bin
Wed Oct 18 11:43:04 2017

**Comment by slackline** [comment]
I'd been waiting for the two to merge back before updating but when the KRACK vulnerability was announced I opted to bite the bullet and upgrade.  OpenWRT is fairly dead with no updates for ages and as LEDE will be the code-base if/when the re-merge takes place it won't be as huge a step as upgrading from OpenWRT.

I've dragged this off topic a bit, but if you use OpenWRT its sensible to upgrade to LEDE.

**Comment by badaix** [comment]
I was crazy enough to upgrade my OpenWRT firmware to LEDE (using the sysupgrade).
The upgrade process went smooth, but Snapclient was not working.  
Installation `opkg install snapclient_0.12.0_ar71xx.ipk` failed with `Packages found, but incompatible with the architectures configured`  
After downloading and installing the LEDE build-system, I could successfully compile Snapcast.
Find the gzipped ipk's here:
[snapclient_0.12.0_mips_24kc.ipk.gz](https://github.com/badaix/snapcast/files/1420211/snapclient_0.12.0_mips_24kc.ipk.gz)
[snapserver_0.12.0_mips_24kc.ipk.gz](https://github.com/badaix/snapcast/files/1420212/snapserver_0.12.0_mips_24kc.ipk.gz)

**Comment by 1337sup3rh4x0r** [comment]
Awesome! Thank you badaix!

KRACK was also the reason why I even looked into this. 
It is debatable whether it is really a security risk if someone can read the audio chunks and the JSON that are exchanged with the client. But nevertheless I like running up to date software.

**Comment by badaix** [comment]
Well, it might rather be a copyright issue rather than a security issue, if you "broadcast" audio :wink:
