### ISSUE TITLE
Librespot's cache argument

### ISSUE THREAD

**Issue by c0da** [badaix/snapcast#292]
Hello everyone,

It seems librespot works like a charm with the 'cache' option (you enter your password once, it saves your credentials to a file, and you don't have to type your password again or send it as an argument).

Is there any way to use the 'cache' argument on SNAPSERVER_OPTS, so we could use something like

    spotify:///librespot?name=Snapcast&devicename=Snapcast&cache=/var/lib/snapserver"'

instead of saving the plain text password to snapserver's config file?

Thanks in advance!

**Comment by ThYpHo0n** [comment]
Thats a good find! Didn't know about the cache option. I just opened a PR to add it :)

**Comment by coda4k** [comment]
Thank you very much @ThYpHo0n!
