### ISSUE TITLE
Lower volume when using snapserver 0.12

### ISSUE THREAD

**Issue by vhmx** [badaix/snapcast#294]
Hi, 

it seems that when using snapserver 0.12 and streaming from osmc to it the output volume is lower that when using 0.11.2. I've reinstalled the previous version and the volume went up by 3-4dB I'd say.don't know exactly by how much but it's notable. It affected AAC / MP3 / WAV streams. What may be causing this? Is there any switch/option that should be added to the server?

Cheers

**Comment by badaix** [comment]
I have no idea, there is at least no intentional change concerning the volume
