### ISSUE TITLE
Client listed twice after upgrading to v0.12.0

### ISSUE THREAD

**Issue by c0da** [badaix/snapcast#297]
After upgrading to v0.12.0 (deb package), for some reason my client is being listed twice:

2017-10-26 16:36:01,180 - snapcast.control.server - DEBUG - group found: Snapgroup (Spotify, a9745106-afa6-b6ef-af20-8be635e5f35c)
2017-10-26 16:36:01,180 - snapcast.control.server - DEBUG - client found: Snapclient 0.11.1 (nova, 00:0c:23:51:a2:23)
2017-10-26 16:36:01,180 - snapcast.control.server - DEBUG - group found: Snapgroup (Spotify, f5c8c082-ee46-09a7-1047-4414024b869d)
2017-10-26 16:36:01,181 - snapcast.control.server - DEBUG - client found: Snapclient 0.12.0 (nova, bcf9eab775e9405798bcd1ec3fe47f04)

I've tried by restarting the server/client (same hardware), and I can confirm that I only have v0.12.0 installed. I've also deleted /var/lib/snapserver/server.json, but after restarting snapserver the file is generated with both clients listed.

Does anyone have a clue?

**Comment by badaix** [comment]
It's because the 0.12 uses a more robust way to create GUIDs for the clients. Since the GUID is the identifier for a client, it was a "new client" with the same name from server point of view.
You could also simply delete the old offline client (purge did this for you be deleting the persistent config file).

**Comment by GMFalka** [comment]
> It's because the 0.12 uses a more robust way to create GUIDs for the clients. Since the GUID is the identifier for a client, it was a "new client" with the same name from server point of view.
> You could also simply delete the old offline client (purge did this for you be deleting the persistent config file).
Hi @badaix!

Can you tell me where is the persistant config file for the snapserver? (where it stores old, offline clients)  Ubuntu 18.04

Thank you!

**Comment by sixtyfive** [comment]
@badaix the more robust GUIDs are good and appreciated, but the duplicate (and sometimes, long-gone, dead-forever) client zombies are a nuisance. Would it be possible for you to provide, as @GMFalka, requested, the information about where those GUIDs are being stored? I tried finding out by read starting from https://github.com/badaix/snapcast/blob/develop/server/config.cpp#L151-L172, but without actually knowing C++ that's not so easy.

**Comment by badaix** [comment]
It should be logged at server start as 
```
[NOTICE] Settings file: "<filename>"
```

and be either `/var/lib/snapserver/server.json` of `~/.config/snapserver/server.json`.

You can also use a GUI like snapweb: activate "show offline clients" and delete all offline clients.

**Comment by sixtyfive** [comment]
Oh, perhaps a misunderstanding. For me, this is about clients that stubbornly keep reappearing when deleted. Even tho the hosts are down / have been down for longer already. One example is Raspberry Pis with WLAN + Ethernet, where somehow 2 exist and 1 becomes a zombie.
