### ISSUE TITLE
Issue with two raspi zero

### ISSUE THREAD

**Issue by maweki** [badaix/snapcast#299]
So this worked fine in 0.11.1 but seems broken in 0.12.0 but I have yet to really debug it.

I have two raspberry pi Zeros running the same os and basically the same image. Different hostnames. Different ways to connect (one wifi, one wired). I give them different clientIDs as per the new settings.

But I don't see both connected with the controller Android app. Once I connect one, the other one disappears and vice versa:

```
Nov 02 22:23:25 wohnzimmer snapserver[474]: Exception in StreamSession::reader(): read_some: End of file
Nov 02 22:23:25 wohnzimmer snapserver[474]: StreamServer::NewConnection: 192.168.1.202
Nov 02 22:27:10 wohnzimmer snapserver[474]: Exception in StreamSession::reader(): read_some: End of file
Nov 02 22:27:10 wohnzimmer snapserver[474]: StreamServer::NewConnection: 192.168.1.201
Nov 02 22:27:10 wohnzimmer snapclient[3483]: Connected to 192.168.1.201
```

The start settings look like this:

```
SNAPCLIENT_OPTS="-d -h 192.168.1.201  --clientID wohnzimmer "
```

and

```
SNAPCLIENT_OPTS="-d -s Device -h 192.168.1.201  --clientID badezimmer"
```

I orchestrate everything via ansible.

**Comment by badaix** [comment]
does it work without the `--clientID` parameter?

**Comment by maweki** [comment]
No, it does not. It worked perfectly with the last version though.

**Comment by maweki** [comment]
I've tried adding a third raspberry pi zero and connecting this one again kicks out any of the other two.

**Comment by badaix** [comment]
What ID do they have in the Android App? (click on `...`|`Details`, check what's written in `ID`)

**Comment by maweki** [comment]
All three do seem to have the same ID.

**Comment by maweki** [comment]
The id is 2e7311d7868244978f314762db251c8e

Googling for that has results :(

https://www.google.de/search?q=2e7311d7868244978f314762db251c8e&oq=2e7311d7868244978f314762db251c8e&aqs=chrome..69i57.21346j0j7&sourceid=chrome&ie=UTF-8

**Comment by maweki** [comment]
I readded the `--clientID` parameter but looking at the app it doesn't actually affect the id. Still the same id is shown for all entities. Does it need to be hex or something?

**Comment by ThYpHo0n** [comment]
@maweki If you use the same image on all of your raspi zeros they inherit the same machine id. You can generate a new one (I don't know the side effects though). For that you can use e.g. dbus-uuidgen and put that into /etc/machine-id and/or /var/lib/dbus/machine-id by hand.
There seems to be a Ansible recipe for doing that for you too (maybe https://github.com/ContainerSolutions/kubadm-ansible/blob/master/unique-machine-id.yml) but I've never used Ansible.

**Comment by maweki** [comment]
@ThYpHo0n 1) it would be most unfortunate if I had to add regeneration to my deployment and 2) it worked last version with the same systems, so there should be a way to get it to work this way

**Comment by maweki** [comment]
Ok, so the `--clientID` parameter that is mentioned in #249 doesn't actually do anything. The parameter is called `--hostID` and setting that, gives each client the respective ID, making it work.

Should still work automatically like last release

**Comment by badaix** [comment]
Seems I should prefer using the MAC address, and - if not available - use the new method (i.e. dbus uid or Android serial number or macOS serial number) as a fallback.  
The v0.12 already has a workaround for OpenWRT/LEDE, because there the dbus uid changed with every reboot. Yet another reason to prefer the MAC address.
