### ISSUE TITLE
systemd unit file

### ISSUE THREAD

**Issue by Kernald** [badaix/snapcast#3]
I plan to use snapcast on Archlinux, which uses systemd. It implies writting systemd unit files. Hence two questions:
 - Would you agree to include them? I'll probably be able to write them, but including them implies to maintain them in the future.
 - As far as I can see, starting snapcast client and server is simply a matter of running `snapclient -d` and `snapserver -d`, respectively, and a kill signal to stop them. Am I right?

There's also one point I don't realy get: how does the client know about the server's IP when running as a daemon? I don't see where the init script gives it, if it does.

**Comment by pille** [comment]
the server is detected in LAN via avahi/bonjour service discovery.

**Comment by badaix** [comment]
Right, the server's IP is published via avahi.  
My latest commit contains unit files for systemd. `Make install` will detect your init system and setup the correct init files. Also build instructions for Arch have been added to the `README.md`.
