### ISSUE TITLE
Allow muting and unmuting groups without id

### ISSUE THREAD

**Issue by maweki** [badaix/snapcast#300]
I have an analog input with some noise I pipe to snapcast with cpiped. Now I want to mute and unmute snapcast according to cpiped's silence detection. Getting the server status to get the group ids takes a lot of time.

I do know the group name so I would love to do something like this to mute all groups without knowing the id:

```
{"id":5,"jsonrpc":"2.0","method":"Group.SetMute","params":{"mute":true}}
```

**Comment by TekniskSupport** [comment]
As a small workaround you can mute all groups by looping thru and muting each one
for inspiration, look at the bash-script for deleting all disconnected clients

https://github.com/badaix/snapcast/commit/5723791f8aee501e26cb446d68acecfba7b304db

**Comment by maweki** [comment]
> Getting the server status to get the group ids takes a lot of time.

**Comment by TekniskSupport** [comment]
It really shouldn't take a lot of time, it takes me 10-20μs (ran a bunch of times) over the wifi to a really really slow server
/i
