### ISSUE TITLE
snapcast-0.12.0 fails to build

### ISSUE THREAD

**Issue by tgurr** [badaix/snapcast#301]
0.12.0 fails to build for me while 0.11.1 still builds fine. Attached is a build.log and you can also see our CI hitting the error: https://galileo.mailstation.de/jenkins/job/media/2383/console
[snapcast-0.12.0.log](https://github.com/badaix/snapcast/files/1447619/snapcast-0.12.0.log)

**Comment by badaix** [comment]
did you update the externals?

**Comment by tgurr** [comment]
AIXLOG_REV="f0b88927f146c1726835528711601deb87bf115b"
JSONRPCPP_REV="115296b2232ba8776467d74602d392d03409ad7e"

popl and asio are packaged libraries, here I use popl-0.3.0 and asio-1.10.8. It seems popl received some commits, I've just tried it with POPL_REV="df5a009b00a62053da7175576476555826efb228" and it works.

Could you please do a new release for popl so we can depend on that?

**Comment by badaix** [comment]
yes, making a release (i.e. a tag) was planned anyways. I will try to do it during the weekend.

**Comment by tgurr** [comment]
Thanks that would be great and very helpful and will also fix my problem. Feel free to just close this issue then.

**Comment by tgurr** [comment]
Thanks for doing proper releases of all the involved libraries!

I've updated our package of popl to 1.0.0 and also packaged the newly released aixlog and jsonrpcpp. I can build snapcast fine now depending on the packaged popl and aixlog packages, however I didn't succeed getting it compiled against the packaged version of jsonrpcpp. Here's what I tried

```
sed \
    -e 's:jsonrp.hpp:jsonrpcpp/jsonrp.hpp:g' \
    -i server/{controlServer.cpp,streamServer.h}
sed \
    -e 's:-lFLAC:-lFLAC -ljsonrpcpp:g' \
    -e 's: ../externals/jsonrpcpp/lib/jsonrp.o::g' \
    -i server/Makefile
```
Now I'm at the same outcome as in https://github.com/badaix/snapcast/issues/193. Might be better to close this one and continue over there for the remaining issue(s).

**Comment by tgurr** [comment]
I guess this can be closed now that the external module/dependency on jsonrpcpp is gone by https://github.com/badaix/snapcast/commit/a3f309e0da291dcbec14520f4f8f44a739184ddf
It would be nice however to not bundle this, is there any specific reason for that? Seems like there was some work done to get snapcast build against the external library by https://github.com/badaix/snapcast/commit/f28018ada708b2bf355358f828918c00118635a0 which was merged before.

**Comment by badaix** [comment]
i've bundled this to not only get rid of the dependency (while I was updating the makefiles for OpenWrt and Buildroot), but also because of the dependency to a patched json.hpp that is needed for the Android builds.
Last but not least: I use popl and aixlog in several other projects, while I'm using jsonrpc++ only in snapcast.

**Comment by tgurr** [comment]
Thanks for the explanation, just one question remaining. Do you still plan to do new releases for the standalone jsonrpc++ or should distributions remove that standalone package from their repositories?
