### ISSUE TITLE
Freature: Add dummy volume slider for a client

### ISSUE THREAD

**Issue by sqozz** [badaix/snapcast#302]
It would be nice if the volume slider simply could do nothing on a specific device connected to the snapcast pool. MPD for example also implements such a mixer called "null". This allows external scripts to monitor the "virtual value" of the snapcast volume while adjusting a different one e.g. a hardware audio receiver.

Do you think this could be a possible feature added to snapcast/snapclient?
btw; thx for this awesome piece of software!

**Comment by Mistico83** [comment]
Hi, I'm new to Github. Retired software engineer.

With the latest version of snapclient, Kubuntu 20.04, I have volume control not as dummy device, but as an app volume:

![Screenshot_20200519_105455](https://user-images.githubusercontent.com/65594686/82306786-c9b35d80-99bf-11ea-8252-9e4520eb6b40.png)

I can mute and also hear other things. Snapclient is configured manually as: `12: pulse
PulseAudio Sound Server`

By default, snapclient _seizes_ all sound output.

I hope it can be helpful for other users. Sorry if it's not posted in the right place.
