### ISSUE TITLE
Multiple streams not working

### ISSUE THREAD

**Issue by dantheperson** [badaix/snapcast#304]
Hello,

The docs state multiple streams can be created by passing multiple -s options.
In my /etc/default/snapserver i have:
`SNAPSERVER_OPTS="-s spotify:///librespot?name=Spotify2&devicename=Badlands -s pipe:///tmp/snapfifo?name=AirPlay&sampleformat=48000:16:2&codec`

syslog mentions the two streams:
Nov 10 16:03:08 rebirth systemd[1]: Starting Snapcast server...
Nov 10 16:03:08 rebirth snapserver[7412]: Settings file: "/var/lib/snapserver/server.json"
Nov 10 16:03:08 rebirth snapserver[7412]: spotify:///librespot?name=Spotify2&devicename=Badlands
Nov 10 16:03:08 rebirth snapserver[7412]: pipe:///tmp/snapfifo?name=AirPlay&sampleformat=48000:16:2&codec=flac
Nov 10 16:03:08 rebirth snapserver[7412]: 2017-11-10 16-03-08 [Notice] Settings file: "/var/lib/snapserver/server.json"
Nov 10 16:03:08 rebirth snapserver[7414]: daemon started
Nov 10 16:03:08 rebirth snapclient[1082]: Exception in Controller::worker(): read_some: End of file
Nov 10 16:03:08 rebirth systemd[1]: Started Snapcast server.

yet audio sent to the pipe does not get played, and the android mixer app only shows the Spotify stream.

If i have only one stream configured, they both work on their own.

Any ideas?  Is there a verbose log level?

**Comment by badaix** [comment]
clients are organized in groups (the first time a client is seen, it's member of it's own group), and to every group a stream is assigned (by default the first stream).
In the Android client you can click on the group's gear symbol and add more clients and change the stream of the group.

**Comment by dantheperson** [comment]
Excellent thanks, it wasn't obvious to me the stream field in the group
settings was editable.

Still it seems you can't have a client in multiple groups/streams?

That would mean when I switch from one source to another I need to use the
Android app to change the stream.

I might have a go running librespot standalone outputting to the FIFO Pipe.
That way I can stop one source and start another without needing to change
any settings.

Thx,
Dan.

**Comment by ThYpHo0n** [comment]
@dantheperson I read a feature request here like assigning a group to a "automatic" stream mode which just goest through all streams / a set of streams (would be more work) and checks if one is in state playing, then the client switches to that stream. Am I right? Sounds interesting, maybe someone wants to jump on that?
