### ISSUE TITLE
[Info] Addon service.snapcast for Libreelec/Kodi

### ISSUE THREAD

**Issue by frafall** [badaix/snapcast#307]
Just the basic compile of client/server and running snapclient as a service. 
Located [here](https://github.com/frafall/service.snapcast).

**Comment by axelsimon** [comment]
[LibreELEC](http://libreelec.tv/) is a Kodi distrubition (this comment is really to help people looking for the search term 'Kodi' to find this issue 😉)

**Comment by frafall** [comment]
Lol true :)

**Comment by awiouy** [comment]
Hi! I have written something [similar](https://github.com/LibreELEC/LibreELEC.tv/pull/2546), not aware of @frafall's work.
I think snapcast should be added to LibreELEC and somehow connected to Kodi and Librespot. Not sure of the best way, though. I am looking for working user configurations and use cases. Thank you in advance for your help.

**Comment by awiouy** [comment]
I have posted previews [here](https://forum.libreelec.tv/thread/11817-snapcast/).

**Comment by badaix** [comment]
You can make a PR to add a Kodi howto to the [Player setup guide](https://github.com/badaix/snapcast/blob/master/doc/player_setup.md)
