### ISSUE TITLE
[Fork] Metadata

### ISSUE THREAD

**Issue by frafall** [badaix/snapcast#310]
I'm looking into supporting metadata in Snapcast, first commit [done](https://github.com/frafall/snapcast/tree/develop). Basically I maintain a per stream struct containing (Artist, Album, Track) and push it to the listening clients, this should be possible to use for album art as well.
For testing I included track pattern search in the Libreelec stderr pattern matching to update the stream metadata. To support more I tags would need a modified [Librespot](https://github.com/plietar/librespot/issues/154). Simular could be implemented for Shairport-sync (Airplay) streams.
For generic named pipes I'm planning to add a generic json interface to set stream tags and client side some kind of  hooks to push stream tags (a callable script, a pipe? ideas?)

I would so wish that ppl who implemented audio interfaces pushed the metadata to the interface implementation, Pulseaudio has a relatively standard property interface for metadata, why haven't Shairport-sync and Libreelec implemented this in their pulseaudio interface? Or to stdout/stderr interface?

-frafall

**Comment by palitu** [comment]
that is great! keep it up!

**Comment by frafall** [comment]
Any ideas on where snapclient should send metadata?
Looking around there are solutions with named pipes, udp packets, scripts 'on_metadata_update.sh'.

To avoid complexity I', thinking about adding a command line '-m <script>' triggered on metadata update with metadata in environment.

Ideas?
