### ISSUE TITLE
Snapcast and ECASound

### ISSUE THREAD

**Issue by MightyMikeNL** [badaix/snapcast#311]
Hi All,

im building a sonos like solution based on snapcast.
This all works like a charm but there is one thing that i cant seem to get to work.

the speakers, or nodes, im building are all single channel. so each speaker or node plays one channel of the stream, either left or right.
My current setup is a RPI0W with a Allo MINI BOSS DAC. eache node had a 2 channel amp, one for the woofer and one for the tweeter. I'm using ECASound to split the input to a single channel with left as a low pass filtered output and right as a high pass filtered output. this all works great.

Now im trying to route the output of snapclient to ecasound but I cannot get it to work. any help would be appriciated!

Regards,

MightyMike

**Comment by renne** [comment]
`Snapclient -> ALSA loopback-device -> ECAsound -> ALSA sound device`

But I assume Snapclient will have trouble synchronizing the audio clock because of the delay in ECAsound.

**Comment by MightyMikeNL** [comment]
@renne any other solution you would advice?

**Comment by renne** [comment]
I don't know if multiple snapserver instances synchronize correctly, but you can try this
`SNAPSERVER_OPTS="-s pipe:///tmp/snapfifo.left?name=Left&sampleformat=48000:32:2&codec=flac -s pipe:///tmp/snapfifo.right?name=Right&sampleformat=48000:32:2&codec=flac"`
and run ECASound on the snapserver host.

`media-player (2 channels) -> ECASound (2x2 channels) -> snapserver`
