### ISSUE TITLE
Feature Request: Dynamic PCM byte-order, bit-length and sampling-rate for improved audio-quality

### ISSUE THREAD

**Issue by renne** [badaix/snapcast#313]
Resampling, especially up-sampling, reduces audio quality.

A FIFO allows to pass through the audio data but does not multiplex control messages (byte-order, bit-length, sampling-rate, number of audio channels). This enforces fixed PCM byte-order, bit-length, sampling-rate and number of audio channels which causes heavy re-sampling.

I suggest to use the [ALSA library](https://www.alsa-project.org/alsa-doc/alsa-lib/) in the snapcast-server to access the ALSA loopback-device as a source. That way the media-player can use the ALSA loopback-device as a sink and handshake PCM byte-order, bit-length, sampling-rate and number of audio channels dynamically according to the original media and the hardware-support in the snapcast-clients.

The ALSA loopback-device supports up to 8 subdevices which allows up to 8 streaming groups on one ALSA loopback-device.

**Comment by renne** [comment]
The capabilities of the audio hardware on the snapcast-clients can be queried via [libasound2](https://www.alsa-project.org/alsa-doc/alsa-lib/). Have a look into [alsacap](http://www.volkerschatz.com/noise/alsa.html#alsacap) for code examples.

**Comment by renne** [comment]
Another advantage of native ALSA support would be audio/video synchronization with video players. In my current setup the audio lags about 1 second which is awful in dialogues.

**Comment by gimesketvirtadieni** [comment]
Hello

@renne, you spotted exactly the reason I have started a 'sister' project - [SlimStreamer](https://github.com/gimesketvirtadieni/slimstreamer). As long as SnapCast uses pipes, it will always resample, which is not helping for quality. SlimStreamer captures PCM stream in a bit-perfect way and broadcasts it to Squeezebox (including squeezelite) clients (although SlimProto is still under development).  Reason is very simple: SlimProto does not require resampling, it supports DSD over PCM and it is way more established streaming protocol. Any comments about alternative approach is more than welcome ;)

P.S. SlimStreamer is C++17 and it is in Public Domain ;)

**Comment by badaix** [comment]
Snapcast relies on a constant bitrate. You can use high quality resampler, which might do a better job than a cheap DSP will do
