### ISSUE TITLE
Question about playing audio between server and clients synchronously.

### ISSUE THREAD

**Issue by Quanwei-Pan** [badaix/snapcast#316]
Hi, I want to play audio stream locally, and use snapcast to make stream multi-roomed to clients. I kwon that Snapcast works well for ervery clients in multi-room function. Does Snapcast provide some APIs or configurations to  make the streams both in server and clients synchronous?

**Comment by Outurnate** [comment]
Best way to do this is to run a snapclient on your server device as well, then mute the feed going into snapserver

**Comment by Quanwei-Pan** [comment]
Thank you for replying. I've thought about this method, and it works well. But I want to know that, are there some ways to play audio streams by using local palyer, not the snapclient.

**Comment by renne** [comment]
If a soundcard is not used via snapclient there is no way to synchronize audio. So I use the following approach:

/etc/default/snapserver:
`SNAPSERVER_OPTS="--sampleformat 48000:32:2 --codec pcm"`

/etc/asound.conf:
```
 pcm.snapcast {
    type    file
    file    /tmp/snapfifo    # Snapcast server FIFO
    format    raw
    hint {
        show on
        description "Snapcast server"
    }

    # Dummy soundcard to define format/sampling-rate and channel number
    slave.pcm {

        # Any unused local soundcard, Snapcast nodes are delayed about 1 second
        type    hw
        card    0
        device  9

        # Snapserver settings
        format      S32_LE
        rate        48000
        channels    2
    }
}
```

/etc/pulse/default.pa:
```
load-module  module-alsa-sink  sink_name=Snapcast  sink_properties=device.description=Snapcast  device=snapcast
set-default-sink Snapcast
```

Now start a snapclient-instance for each soundcard you want to use - either locally or remote. All your audio sources/media-players connected to pulseaudio will be audible via snapcast. ;-)

**Comment by Outurnate** [comment]
@Quanwei-Pan I can't see why you'd want to that.  What advantage would that have?

**Comment by tadly** [comment]
I'm curious about the same thing, using my HTPC as master.

The idea would be to use the HTPC just the way I always do (5.1 setup for music, movies, tv-shows) but when I'm in the kitchen or bathroom, I'd like to only press a button (e.g. android table, rpi) to than have multiroom audio going.

I obviously don't want to loose 5.1 nor do I want to take a dip in audio quality or add unnecessary audio delay when watching movies/shows.

I could automate the master-side of things by have a script which re-configures pulse to output into a loopback device and start a local snapclient (and reverse it upon second call or with arguments)
With Android however things get a bit more tricky for various reasons.

All in all this feels kinda hacky and I'm curious as to how others would solve this.

The core idea of having a HTPC which additionally can broadcast it's audio doesn't seem far fetched IMO :)

**Comment by badaix** [comment]
@Outurnate is completely right. There is no other way than using snapclients only for playback.
