### ISSUE TITLE
[Feature Request] Hardware volume control in snapclient

### ISSUE THREAD

**Issue by renne** [badaix/snapcast#318]
Each room has another size, furniture and wall materials and each speaker model has another structure. So each room has it's own specific volume level with lowest resonances and distortions which means a lower volume often leads to better audibility than turning up the volume.

Hardware mixers are usually electrically optimized for their DACs which means better sound quality than software mixers.

There is also no API to integrate hardware volume controls (e.g. rotary encoders, IR/radio remote controls, ...) in the software mixer of snapclient.

The ALSA API uses the hardware volume control by default with a fall back to software volume control if no hardware based volume control is available. That way the hardware mixer with better quality is used. Synchronizing the current ALSA volume with the snapcast controllers will not only allow remote control of the volume by snapcast-controllers but also with hardware controllers directy accessing the ALSA volume controls. If e.g. a rotary encoder changes the master volume of an ALSA mixer all snapcast controllers would be updated automatically.

So I suggest to use the ALSA mixer controls in snapclient instead.

**Comment by tomtaylor** [comment]
I'd love this feature too. It would ensure that I could keep a hardware rotary volume control in sync with the remote JSON-RPC control through `snapserver`.

**Comment by ytzelf** [comment]
would greatly appreciate that as well 👍

**Comment by badaix** [comment]
This is slightly related to #302 
Patches are always welcome.

**Comment by badaix** [comment]
The develop branch introduces the new option `--mixer` (currently just for Linux/alsa), which can be 
- `software` [default]
- `hardware` [:<mixer control, default "PCM">]
- `script` the script will be executed with the parameters `--volume <volume> --mute <true|false>`
- `none`

Testers are welcome :)

**Comment by dflvunoooooo** [comment]
I am struggling to get the mixer set up. Snapclient can not find the mixer, even if I try every mixer from `snapclient -l`. If I run `snapclient --mixer hardware`, it results in the following error:
``
…
2021-11-15 08-56-40.362 [Error] (Alsa) Exception: Failed to find mixer: PCM, code: 0
2021-11-15 08-56-40.363 [Fatal] (Snapclient) Exception: Failed to find mixer: PCM
…
``

If I specify the mixer, it doesn't change a thing. For the option `--mixer hardware:2` or `--mixer hardware:sysdefault:CARD=Headphones` or `--mixer hardware:sysdefault` or `--mixer hardware:CARD=Headphones` or `--mixer hardware:Headphones` results in the same error, just that the error states the specified mixer and not "PCM".

Can someone please help or tell me, where I can find more information about the mixer option?

**Comment by kingosticks** [comment]
The `-l` option lists playback devices. These are not the same as alsa (mixer) controls. To display the controls available on your system run `amixer scontrols`.

**Comment by dflvunoooooo** [comment]
Thank you very much. This worked perfectly.

**Comment by dflvunoooooo** [comment]
Hm, it does work if the mixer is `Headphone` on card 0. But if I list the controls for a different card, which is the HifiBerry board, it returns `Simple mixer control 'Tx Source',0`. Which seems fine, but when I try to set that mixer with snapclient, snapclient can't find that mixer again. 
`snapclient --mixer hardware:'Tx Source'` results in
```
Do I have to set the mixer differently if it is not on card 0?
…
2021-11-15 12-45-33.049 [Error] (Alsa) Exception: Failed to find mixer: Tx Source, code: 0
2021-11-15 12-45-33.049 [Fatal] (Snapclient) Exception: Failed to find mixer: Tx Source
…
```

**Comment by kingosticks** [comment]
Mixers are per card. If not using the default card then you'll need to also explicltly set which card using the `--soundcard` option.

**Comment by dflvunoooooo** [comment]
Thank you for your quick answer again! It is working now, though snapclient is prompting some errors
```
…
2021-11-15 14-20-14.128 [Error] (Alsa) Failed to mute, error: Invalid argument
2021-11-15 14-20-14.128 [Error] (Alsa) Resizing buffer from 0 to 14112
2021-11-15 14-20-14.128 [Error] (Alsa) Exception: Failed to get playback volume range, error: Invalid argument
…
2021-11-15 14-20-26.567 [Error] (Alsa) XRUN while waiting for PCM: Broken pipe
…
```
But I expect that to be a problem with the soundcard configuration in alsa, right?

**Comment by kingosticks** [comment]
Sorry, I don't know about those but it doesn't seem very happy trying to use the mixer. Are you sure your hifiberry board supports hardware mixing? Not all of them do.

**Comment by dflvunoooooo** [comment]
Thank you again for pointing that out. It would seem, that the HifiBerry Digi's do in fact not support volume control. I simply assumed that a soundcard does that. My bad. 

For the standard soundcard of the Raspberry Pi everything is working fine, thank you again for the explanation.

**Comment by kingosticks** [comment]
I was bitten by that myself a few years back. They are cheap for a reason! I wish HiFiBerry would make it clearer.

**Comment by dflvunoooooo** [comment]
Just in case someone stumbles about this. With the Hifiberry AMP2 it is possible to set the hardware mixer, but only if you _disable_ all other sound (even HDMI) via config.txt. In my case I had to remove `dtparam=audio=on` and for HDMI `dtoverlay=vc4-kms-v3d`. Only after that the `amixer scontrols` command will return the controls from the AMP2 board. Of which only the 'Digital',0 is useful according to the [Hifiberry documentation](https://www.hifiberry.com/docs/archive/mixer-controls-on-the-hifiberry-boards/). 

So with the above changes to config.txt and the  `--soundcard default:CARD=sndrpihifiberry --mixer hardware:'Digital'` snapclient options, a change in snapclients volume changes the volume of the board.

**Comment by DesertRider** [comment]
> Just in case someone stumbles about this. With the Hifiberry AMP2 it is possible to set the hardware mixer, but only if you _disable_ all other sound (even HDMI) via config.txt. In my case I had to remove `dtparam=audio=on` and for HDMI `dtoverlay=vc4-kms-v3d`. Only after that the `amixer scontrols` command will return the controls from the AMP2 board. Of which only the 'Digital',0 is useful according to the [Hifiberry documentation](https://www.hifiberry.com/docs/archive/mixer-controls-on-the-hifiberry-boards/).
> 
> So with the above changes to config.txt and the `--soundcard default:CARD=sndrpihifiberry --mixer hardware:'Digital'` snapclient options, a change in snapclients volume changes the volume of the board.

Thank you for the comment, it helped me!

**Comment by dflvunoooooo** [comment]
> Just in case someone stumbles about this. With the Hifiberry AMP2 it is possible to set the hardware mixer, but only if you _disable_ all other sound (even HDMI) via config.txt. In my case I had to remove `dtparam=audio=on` and for HDMI `dtoverlay=vc4-kms-v3d`. Only after that the `amixer scontrols` command will return the controls from the AMP2 board. Of which only the 'Digital',0 is useful according to the [Hifiberry documentation](https://www.hifiberry.com/docs/archive/mixer-controls-on-the-hifiberry-boards/).
> 
> So with the above changes to config.txt and the `--soundcard default:CARD=sndrpihifiberry --mixer hardware:'Digital'` snapclient options, a change in snapclients volume changes the volume of the board.

This is not necessary anymore with debian trixie. Snapcast works without deactivating thuse modules in the `config.txt`.
