### ISSUE TITLE
Allow to compile without submodules

### ISSUE THREAD

**Issue by languitar** [badaix/snapcast#323]
In response to badaix/jsonrpcpp/issues/2 I have tried again to provide a snapcast package for homebrew. However, I am stuck again because the build system of snapcast always expects to find its upstream dependencies in git submodules. I could get around most of the issues (by simply not pulling the submodules and using installed upstream versions), but am stuck with a compilation problem regarding jsonrpcpp:

```
g++  -std=c++0x -Wall -Wno-unused-function -O3 -DASIO_STANDALONE -DVERSION=\"0.12.0\" -I. -I.. -isystem ../externals/asio/asio/include -I../externals/popl/include -I../externals/aixlog/include -I../externals/jsonrpcpp/lib -I../externals -DMACOS -DFREEBSD -DHAS_BONJOUR -DHAS_DAEMON -Wno-deprecated -I/usr/local/include -o snapserver snapServer.o config.o controlServer.o controlSession.o streamServer.o streamSession.o streamreader/streamUri.o streamreader/streamManager.o streamreader/pcmStream.o streamreader/pipeStream.o streamreader/fileStream.o streamreader/processStream.o streamreader/airplayStream.o streamreader/spotifyStream.o streamreader/watchdog.o encoder/encoderFactory.o encoder/flacEncoder.o encoder/pcmEncoder.o encoder/oggEncoder.o ../common/sampleFormat.o ../message/pcmChunk.o ../common/daemon.o publishZeroConf/publishBonjour.o -lvorbis -lvorbisenc -logg -lFLAC -L/usr/local/lib -framework CoreFoundation -framework IOKit -L/usr/local/Cellar/jsonrpcpp/1.0.0/lib -ljsonrpcpp
Undefined symbols for architecture x86_64:
  "Config::getServerStatus(nlohmann::basic_json<std::__1::map, std::__1::vector, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, bool, long long, unsigned long long, double, std::__1::allocator, nlohmann::adl_serializer> const&) const", referenced from:
      StreamServer::ProcessRequest(std::__1::shared_ptr<jsonrpcpp::Request>, std::__1::shared_ptr<jsonrpcpp::Entity>&, std::__1::shared_ptr<jsonrpcpp::Notification>&) const in streamServer.o
      StreamServer::onMessageReceived(StreamSession*, msg::BaseMessage const&, char*) in streamServer.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [snapserver] Error 1
make: *** [server] Error 2
```

I have no real clue so far what is causing this. However, things would be much easier if there was a real build system that does installed upstream dependencies instead of submodules.

The current experiments can be found here: https://github.com/languitar/homebrew-core/tree/snapcast

**Comment by ThYpHo0n** [comment]
As far as I know, Homebrew does checkout submodules automatically if you don't use the release tar.gz archive but instead point to the git repo.
Is there a particular reason you don't want to point to the git repo?

**Comment by languitar** [comment]
There was a PR for snapcast once on homebrew and it got reject also because of the use of submodules with software that is already packaged in homebrew (for instance asio). I can perfectly understand that reasoning because software becomes duplicated then on the systems and cannot be maintained correctly to receive security updates etc.

**Comment by ThYpHo0n** [comment]
**Offtopic**: I can understand the concerns and makes sense to me to embrace that, though rejecting a Formula to enforce handling dependencies via Homebrew seems a bit harsh to me. In the end it's the projects responsibility to handle dependencies. You would end up with different versions of the same dependency anyway because each project may pin to a specific version/ git ref of the dependency anyway and should be responsible to update in case of security issues.

But anyway, I'm not a Homebrew expert but seems like we need to go the hard way then ;)
I'll try to reproduce your problem later and will report back.

**Comment by ThYpHo0n** [comment]
Hey,
sorry took a bit more time for me to finally come back to this issue.
Disclaimer: I'm really not that familiar with C build systems maybe I'm totally wrong here...

The difference I can see is that in the the snapcast/server/Makefile depends on jsonrp.o (https://github.com/badaix/snapcast/blob/master/server/Makefile#L36)
but after installing your jsonrpcpp forumla via homebrew my /usr/local/include/jsonrpcpp folder only contain the header files (json.hpp & jsonrp.hpp).

**Why is there no jsonrp.o?**
In the formula you do "cmake ." first and then "make install".
If I checkout https://github.com/badaix/jsonrpcpp and just do make I get the jsonrp.o file but if I do "cmake ." and then make I don't get the jsonrp.o file anymore. I dunno if it's possible to generate/install .o files via cmake?

@badaix Can you have a look into the cmake configuration for the jsonrpcpp project, in case im right here?

**Comment by badaix** [comment]
Hi, meanwhile I've converted jsonrpcpp into a header only lib and use a copy instead of a submodule of it
