### ISSUE TITLE
How does it communicate between snapserver and snapclient in the same device

### ISSUE THREAD

**Issue by lszhou0126** [badaix/snapcast#324]
If I run a snapserver and snapclient in the same device, how the communication is achieved? If using WIFI, the snapserver send to the router, and the router send to the snapclient? Or just local communication, which means the snapserver send to the snapclient directly and needn't router to provide transit?

**Comment by raneri** [comment]
I'm experiencing a similar problem: I'm running Pulseaudio on a Raspberry PI, along Snapserver. On this device I also have Snapclient, that outputs sound locally. As soon I start a sound source (e.g.: a web radio with VLC) music start and enter a loop where the FIFO file outputs sound to Pulseaudio, that routes it to Snapserver; it sends it back to Pulseaudio output that routes it to the FIFO and renders it with Snapclient, causiing an infinite loop, with noticeable echo.

How I avoid this?

**Comment by BaReinhard** [comment]
I originally had this issue, i would setup snapclient to use sysdefault card number in place of  Pulseaudio.

**Comment by badaix** [comment]
the signal will go through your loopback interface and will not leave your host
