### ISSUE TITLE
[Question] Pulseaudio environment variable PULSE_LATENCY_MSEC

### ISSUE THREAD

**Issue by hanoba** [badaix/snapcast#327]
The Snapcast documentation includes the following sentence related to **pulseaudio** installation: "It might be necessary to set the pulse audio latency environment variable to 60 msec: PULSE_LATENCY_MSEC=60".

In the **pulseaudio** man page the PULSE_LATENCY_MSEC environment variable is not described. What is exactly the purpose and why should it be changed for Snapcast?

Many thanks in advance for clarification!

Harald

**Comment by hanoba** [comment]
@badaix: Could you please answer this question?
Thanks Harald

**Comment by badaix** [comment]
I don't know the details and I'm not familiar with pulseaudio, but source of this parameter must be Issue #16

**Comment by DJJo14** [comment]
After looking in the source of pulseaudio i [found](https://github.com/pulseaudio/pulseaudio/commit/d09099526220fb87ac8c4f6bae298b23744d0dae) that it has been inplemended, but i am still figeringout if it works.

```
export PULSE_LATENCY_MSEC=400
pulseaudio -k
and if it does not restart automatic
pulseaudio -D
```

**Comment by TheMackster** [comment]
Game launches with a black screen with only audio. I'm using Ubuntu 18.04.
