### ISSUE TITLE
snapserver buffer below 400ms

### ISSUE THREAD

**Issue by deisi** [badaix/snapcast#329]
It is not possible to set a snapserver buffer below 400ms. A value below 400ms gets ignored and is relpaced by 400ms.

Start the server with:
```
snapserver -s "pipe:///tmp/snapfifo?name=default&mode=read&codec=pcm&sampleformat=48000:16:2" -b 200
```
And on the client one gets:

```
Dec 21 21:15:03 serv snapclient[940]: 2017-12-21 21-15-03 [Info] ServerSettings - buffer: 400, latency: 0, volume: 100, muted: 0

```

ah I found where this is hardcoded but why:

https://github.com/badaix/snapcast/blob/f0a71a9e9467c8f2d5faa2bf2dc7511e5a09e197/server/snapServer.cpp#L183-L191

**Comment by badaix** [comment]
it's basically to avoid bug reports saying that the client doesn't play audio. Maybe i will allow smaller buffers and log a warning.

**Comment by deisi** [comment]
As the minimum required buffer is out of the scope of snapcast, it should be left to the user to try and decide what works for his/her setup and situation. I would very much appreciate a change here :)

**Comment by vroland** [comment]
@badaix I second this. Maybe at least make it configurable during build time for experienced users?

**Comment by zaneclaes** [comment]
Would really appreciate this, as well. My setup appears to be able to handle much smaller buffers (everything is 1gbps ethernet with RCA cables; no wifi or bluetooth). As it stands, I cannot use snapcast for streaming live music playing as the 400ms delay is too large, but I suspect ~100-200ms would be fine.

**Comment by mbrgm** [comment]
> it's basically to avoid bug reports saying that the client doesn't play audio. Maybe i will allow smaller buffers and log a warning.

@badaix PR welcome for this?

**Comment by badaix** [comment]
I can lower it to let's say 50ms in the next release
