### ISSUE TITLE
snapserver segfault if $HOME is not set

### ISSUE THREAD

**Issue by j0s** [badaix/snapcast#33]
Running snapserver on command line works fine, but when running it as a systemd service it segfaults. Debugging led me to `string dir = getenv("HOME") + string("/.config/Snapcast/");` in `Config::Config()` which will segfault if HOME is not set in the environment. Adding `HOME=/root` to /etc/default/snapserver solved this problem for me, but maybe `settings.json` should be stored somewhere else when running as a systemd service?

I'm running Snapcast v0.5.0-beta-1.

**Comment by badaix** [comment]
should be fixed in `develop` branch with commit 3a02bc3dde704494a06db1e37b406a22dc1256fd: 
if `$HOME` is not set, the config will be stored in `/var/lib/snapcast/server.json` instead of `~/.config/snapcast/server.json`
