### ISSUE TITLE
Control Clients with IR using LIRC

### ISSUE THREAD

**Issue by Suz2905** [badaix/snapcast#330]
I would like to control clients using the same ir remote I use to control snapserver and mopidy, only need to mute and vol + or - but can't puzzle out how to do it. If anybody can point me in the right direction I would be grateful.
I have LIRC installed and working well to control Mopidy and master volume.

I usually control through laptop and home assistant - but over Christmas laptop must be packed away!! I also have app on phone but if I'm out nobody else can adjust volume.  

Thanks for looking and thanks for all the effort that goes into Snapcast - it's great to find something that just works straight out of the box.

**Comment by badaix** [comment]
Changing the volume is possible with the control API.
