### ISSUE TITLE
[Feature Request] Volumio Plugin?

### ISSUE THREAD

**Issue by PhoGGy** [badaix/snapcast#333]
Hey badaix and all other contributers!
I´ve used librespot together with snapcast for a long time to get Spotify Multiroom audio.
It worked perfectly but the setup was complicated and very static.
What about adding the snapcast capability to Volumio to use the Volumio WebUI for setup?
I really like the volumio project, and I would love to see a snapcast plugin for it :)
Think about it!
Greetings Phil

**Comment by cortegedusage** [comment]
Look no further!
https://github.com/Saiyato/volumio-snapcast-plugin

Works like a charm for me.

Op 24 dec. 2017 12:30 p.m. schreef "PhoGGy" <notifications@github.com>:

**Comment by PhoGGy** [comment]
Thanks for the quick response, i just found it myself :)
Maybe link it in the readme as well?

**Comment by mray** [comment]
So this can be closed, right?

**Comment by PhoGGy** [comment]
Yes please :)

**Comment by PhoGGy** [comment]
Yes please :)
