### ISSUE TITLE
Snapserver on a FreeBSD 11.1 not listening

### ISSUE THREAD

**Issue by sebastianrakel** [badaix/snapcast#336]
Hello, 

i'm running snapserver on a FreeBSD 11.1. and want connect a client both a version 0.12.0.

Snapserver IP: 192.168.11.3
Snapclient IP: 192.168.11.5

I can connect to the snapserver with telnet on the snapserver host: telnet localhost 1705
but if i connect from the client with: telnet 192.168.11.3 1705 it doesn't work

I looked at the code and changed following lines in streamServer.cpp and controlServer.cpp
from:
`asio::ip::address address = asio::ip::address::from_string("::");`
to
`asio::ip::address address = asio::ip::address::from_string("192.168.11.3");`

and it worked. it works also with 0.0.0.0...
so maybe a good feature is a config parameter to provide a binding address

**Comment by badaix** [comment]
fixed in release [v0.14.0](https://github.com/badaix/snapcast/releases/tag/v0.14.0)
