### ISSUE TITLE
Is there a way to remotely trigger a restart of the snapserver service?

### ISSUE THREAD

**Issue by FHoevi** [badaix/snapcast#338]
After successfully setting up a snapcast environment with one snapserver (RPi3 running LibreELEC/Kodi with snapserver plugin) and 3 synchronized snapclients (RPi3 running raspbian stretch) I ran into the following problem: When switching within Kodi from, e.g., an internet radio stream (where no audio/video syncing is necessary, only audio syncing across clients which works pretty well) to a locally (via LAN) broadcasted audio/video stream audio and video get out of sync which could only be solved by a manual `systemctl restart snapserver`. Does anyone know about a way to do that remotely and/or tiggered? I already learned that this switching procedure within Kodi could be used to trigger events, so my main question refers to a remote restart of the service.

**Comment by FHoevi** [comment]
BTW, as far as I can see every volume adjustment, e.g. via the Android app, desynchronizes audio from video, and needs to be adjusted by a `sudo systemctl restart snapclient`. After that anything works well again.

**Comment by FHoevi** [comment]
When I look at JSON RPC responses to, e.g., `{"id":8,"jsonrpc":"2.0","method":"Client.GetStatus","params":{"id":"6bce177925da431f8c253f4e9d1efb23"}}` I do see that the latency which I set for each client in the corresponding client's snapclient config file (`--latency 486`) is set to 0.

With `{"id":7,"jsonrpc":"2.0","method":"Client.SetLatency","params":{"id":"6bce177925da431f8c253f4e9d1efb23","latency":486}}` the latency gets adjusted, at least as far as I can see.

@badaix: Would it be possible to expand the Android app by an opportunity to adjust the latency as well? That would probably solve the issue.

**Comment by FHoevi** [comment]
One problem with latency is that in my configuration with a number of sychronized clients the latency of individual clients changes over time independently of the others which leads to echoes. With happyleavesaoc/python-snapcast I created a very simple python script which is run every 10 minutes via crontab to readjust the latency parameter for all clients first to 1msec and then back to 0msec.

**Comment by badaix** [comment]
Clients shouldn't get out of sync. Please update to v0.19.0. There are some improvements regarding synchronization.
