### ISSUE TITLE
snapserver exception when control Session is set inactive

### ISSUE THREAD

**Issue by maweki** [badaix/snapcast#340]
Snapcast server becomes unresponsive when the ControlSession suddenly ends

```
Jan 13 11:34:45 wohnzimmer snapserver[11330]: Exception in ControlSession::reader(): read_until: Connection reset by peer
Jan 13 11:38:30 wohnzimmer snapserver[11330]: ControlServer::NewConnection: 192.168.1.101
Jan 13 11:38:30 wohnzimmer snapserver[11330]: Session inactive. Removing
Jan 13 11:38:41 wohnzimmer snapserver[11330]: Exception in ControlSession::reader(): read_until: End of file
```

After that, it's impossible to restart snapserver without killing it. It no longer reacts to SIGTERM (from systemd) and doesn't output audio etc...

**Comment by hersche** [comment]
i think i ran into the same. do you have any idea how to reproduce this?
i try something to surround it (it nerves me), but since i don't know when it appears, it's difficult (once, it appears after 2 minutes, another time after a hour..)

**Comment by maweki** [comment]
Referencing #334 you could try starting a control session with your phone and while it is on, disconnect the wifi. Don't know whether this works or not.

**Comment by maweki** [comment]
This was still an issue on 0.14 but maybe 297d74aae91fd072ae925aa9ee4f881b7ffe522e solves this. I have yet to try.

**Comment by armageddon421** [comment]
I basically have this problem whenever a client unexpectedly disconnects. I can reproduce it almost every time by unplugging the power of one of the raspberry pi clients. The music continues to play on all other devices, but the control interface is unresponsive then. I also have to kill it hard in this state.
I would appreciate if the server could be made stable against sudden disconnects, as I also have "mobile" clients that are meant to be moved and plugged in on demand.
