### ISSUE TITLE
Module load failed.

### ISSUE THREAD

**Issue by deisi** [badaix/snapcast#35]
The readme tells:

    pacmd load-module module-pipe-sink file=/tmp/snapfifo

but this doesn't work when a `snapfifo` file already exists. Was this working at some point? Is one supposed to first star the pulseaudio snapfifo file and then start `snapserver`?

**Comment by pille** [comment]
this command creates the FIFO. if you've created it manually before, remove it.
if it was created by pulseaudio, you can unload the module to remove it: `pacmd unload-module module-pipe-sink`

you'd start the server after loading the module (creating the FIFO).

**Comment by deisi** [comment]
Ahhh okay, thats how it works. Thanks. So I think I still have an old FIFO around.

**Comment by deisi** [comment]
Maybe you should give a hint in the readme, that the fifo must be created by pulseaudio first. Thus the order of starting the progamms is important.

- pulseaudio with fifio
- snapcast {server, client}

when one wants to automate the start, one has to consider this.

In any case, I close this, since the issue was due to wrong usage and not programming.
