### ISSUE TITLE
Distortion in the played audio

### ISSUE THREAD

**Issue by lszhou0126** [badaix/snapcast#350]
When I hear the music played by client, I can feel some distortion like click. And I dump the data that sent to alsa device, sometimes a data sample is same as the previous and sometimes not. Is this normal, and can this distortion be solved.

**Comment by maweki** [comment]
Are you sure you're using the same sample rate in the settings for the channel and the output of the audio application?

**Comment by lszhou0126** [comment]
@maweki Yes, I am sure the samplerate is the same. Am I find out what's the problem.

**Comment by Urik1488** [comment]
@lszhou0126 how did you solve it? Have the same (

**Comment by badaix** [comment]
should be fixed in v0.19.0
