### ISSUE TITLE
Sending audio stream from a remote client

### ISSUE THREAD

**Issue by tech4life2015** [badaix/snapcast#355]
I am currently testing Snapcast for my home and would like to send a audio stream from my snapcast client raspberrypi. I was able to successfully do it by piping shairport-sync to a local fifo file then cat the file over ssh to the snapcast server snapfifo file. There was a massive delay but worked. I was wondering if there were plans to make this easier to input audio stream from remote clients into the snapcast server? I find this useful because then I could bring in audio from my TV and also have a separate airplay audio stream per room that then could be distributed throughout the house on the file.

**Comment by fuchsmich** [comment]
You could try a pulseaudio stream via network to the device with snapserver running and make a pulseaudio loopback to the fifo there.
Would be interesting, if LAN has enough bandwith for this.

**Comment by badaix** [comment]
You can send audio via TCP using the TCP stream plugin, as described in `snapserver.conf`:
```
tcp server: tcp://<listen IP, e.g. 127.0.0.1>:<port>?name=<name>[&mode=server]
tcp client: tcp://<server IP, e.g. 127.0.0.1>:<port>?name=<name>&mode=client
```

**Comment by erahhal** [comment]
What does "server" mean in this case? Would one node have a server stream, and the other a client stream, and the client stream would stream from the server stream?
