### ISSUE TITLE
can t redirect to usb card

### ISSUE THREAD

**Issue by karba78** [badaix/snapcast#356]
Hello
i am trying to redirect sound output to my usb card, but not succeeding
not sure i am doing it right here
any help on how to do this is appreciated

find below snapclient file
and snapclient -l output

--------------------------------------------------------------------------------

# defaults file for snapclient

# start snapclient automatically?
START_SNAPCLIENT=true

# Allowed options:
#   --help                          produce help message
#   -v, --version                   show version number
#   -h, --host arg                  server hostname or ip address
#   -p, --port arg (=1704)          server port
#   -l, --list                      list pcm devices
#   -s, --soundcard arg (=default)  index or name of the soundcard
#   -d, --daemon [=arg(=-3)]        daemonize, optional process priority [-20..$
#   --user arg                      the user[:group] to run snapclient as when $
#   --latency arg (=0)              latency of the soundcard
#   -i, --instance arg (=1)         instance id

USER_OPTS="--user snapclient:audio"

SNAPCLIENT_OPTS="--daemon 1 --host 192.168.0.242 --soundcard 11"
------------------------------------------------------------------------------------------

 snapclient -l
0: null
Discard all samples (playback) or generate zero samples (capture)

1: pulse
PulseAudio Sound Server

2: sysdefault:CARD=ALSA
bcm2835 ALSA, bcm2835 ALSA
Default Audio Device

3: dmix:CARD=ALSA,DEV=0
bcm2835 ALSA, bcm2835 ALSA
Direct sample mixing device

4: dmix:CARD=ALSA,DEV=1
bcm2835 ALSA, bcm2835 IEC958/HDMI
Direct sample mixing device

5: dsnoop:CARD=ALSA,DEV=0
bcm2835 ALSA, bcm2835 ALSA
Direct sample snooping device

6: dsnoop:CARD=ALSA,DEV=1
bcm2835 ALSA, bcm2835 IEC958/HDMI
Direct sample snooping device

7: hw:CARD=ALSA,DEV=0
bcm2835 ALSA, bcm2835 ALSA
Direct hardware device without any conversions

8: hw:CARD=ALSA,DEV=1
bcm2835 ALSA, bcm2835 IEC958/HDMI
Direct hardware device without any conversions

9: plughw:CARD=ALSA,DEV=0
bcm2835 ALSA, bcm2835 ALSA
Hardware device with all software conversions

10: plughw:CARD=ALSA,DEV=1
bcm2835 ALSA, bcm2835 IEC958/HDMI
Hardware device with all software conversions

11: sysdefault:CARD=A10
ARCAM USB Audio 1.0, USB Audio
Default Audio Device

12: front:CARD=A10,DEV=0
ARCAM USB Audio 1.0, USB Audio
Front speakers

13: surround21:CARD=A10,DEV=0
ARCAM USB Audio 1.0, USB Audio
2.1 Surround output to Front and Subwoofer speakers

14: surround40:CARD=A10,DEV=0
ARCAM USB Audio 1.0, USB Audio
4.0 Surround output to Front and Rear speakers

15: surround41:CARD=A10,DEV=0
ARCAM USB Audio 1.0, USB Audio
4.1 Surround output to Front, Rear and Subwoofer speakers

16: surround50:CARD=A10,DEV=0
ARCAM USB Audio 1.0, USB Audio
5.0 Surround output to Front, Center and Rear speakers

17: surround51:CARD=A10,DEV=0
ARCAM USB Audio 1.0, USB Audio
5.1 Surround output to Front, Center, Rear and Subwoofer speakers

18: surround71:CARD=A10,DEV=0
ARCAM USB Audio 1.0, USB Audio
7.1 Surround output to Front, Center, Side, Rear and Woofer speakers

19: iec958:CARD=A10,DEV=0
ARCAM USB Audio 1.0, USB Audio
IEC958 (S/PDIF) Digital Audio Output

20: dmix:CARD=A10,DEV=0
ARCAM USB Audio 1.0, USB Audio
Direct sample mixing device

21: dsnoop:CARD=A10,DEV=0
ARCAM USB Audio 1.0, USB Audio
Direct sample snooping device

22: hw:CARD=A10,DEV=0
ARCAM USB Audio 1.0, USB Audio
Direct hardware device without any conversions

23: plughw:CARD=A10,DEV=0
ARCAM USB Audio 1.0, USB Audio
Hardware device with all software conversions

**Comment by karba78** [comment]
it works if i launch command line
snapclient --host 192.168.0.242 --soundcard 11

but dont know how to automate launch with these parameters

**Comment by fuchsmich** [comment]
How would you like to launch snapclient?

**Comment by karba78** [comment]
Autmatically at boot but would love to be able to see output

**Comment by fuchsmich** [comment]
So, I guess you want to use the systemd unit?
`systemctl start snapclient`

**Comment by karba78** [comment]
tried that,, but seems syntax pb
 
systemctl start snapclient --host 192.168.0.242 --soundcard 11
systemctl: unrecognized option '--soundcard'

**Comment by P-D-G** [comment]
systemctl is part of systemd (replacement for init.d) and is only used to manage the snapclient service, not to configure it.
You can modify the snapclient daemon configuration by editing the file "/etc/default/snapclient". In your case, the snapclient configuration seems ok.
You can then restart the snapclient daemon with the proper configuration by launching "systemctl restart snapclient.service". If you want it to start at boot, launch "systemctl enable snapclient.service". Both commands require root permissions.

Another way to do it would be to redirect all alsa output to your USB card. There is a bunch of example configuration as this online.

**Comment by fuchsmich** [comment]
Maybe this thread #344 (especially this post https://github.com/badaix/snapcast/issues/344#issuecomment-365536871) can help you.

**Comment by praul** [comment]
Add -s 11 to /etc/default/snapclient  USER_OPTS
so it looks something like this
`USER_OPTS="--user snapclient:audio -s 11"`
