### ISSUE TITLE
snapclient CP15 barrier message spamming the logs on arm64

### ISSUE THREAD

**Issue by dantheperson** [badaix/snapcast#357]
Hi, 

Im running Armbian on a rock64 and have installed snapclient on it.   

When running syslog is totally getting spammed with this error messages:

[ 1865.309855] cp15barrier_handler: 9732 callbacks suppressed
[ 1865.309880] "snapclient" (1121) uses deprecated CP15 Barrier instruction at 0x5b5a0
[ 1865.309898] "snapclient" (1121) uses deprecated CP15 Barrier instruction at 0x5b5ac
[ 1865.309934] "snapclient" (1121) uses deprecated CP15 Barrier instruction at 0x32838
[ 1865.309956] "snapclient" (1121) uses deprecated CP15 Barrier instruction at 0x32a04
[ 1865.309979] "snapclient" (1121) uses deprecated CP15 Barrier instruction at 0x31174
[ 1865.309995] "snapclient" (1121) uses deprecated CP15 Barrier instruction at 0x31180
[ 1865.310013] "snapclient" (1121) uses deprecated CP15 Barrier instruction at 0x3123c
[ 1865.310029] "snapclient" (1121) uses deprecated CP15 Barrier instruction at 0x31244
[ 1865.310045] "snapclient" (1121) uses deprecated CP15 Barrier instruction at 0x31288
[ 1865.310061] "snapclient" (1121) uses deprecated CP15 Barrier instruction at 0x312a4
[ 1870.326756] cp15barrier_handler: 9719 callbacks suppressed
[ 1870.326781] "snapclient" (1030) uses deprecated CP15 Barrier instruction at 0x3805c
[ 1870.326800] "snapclient" (1030) uses deprecated CP15 Barrier instruction at 0x686e4
[ 1870.326816] "snapclient" (1030) uses deprecated CP15 Barrier instruction at 0x686fc
[ 1870.326833] "snapclient" (1030) uses deprecated CP15 Barrier instruction at 0x686e4
[ 1870.326848] "snapclient" (1030) uses deprecated CP15 Barrier instruction at 0x686fc
[ 1870.326865] "snapclient" (1030) uses deprecated CP15 Barrier instruction at 0x686e4
[ 1870.326880] "snapclient" (1030) uses deprecated CP15 Barrier instruction at 0x686fc
[ 1870.326896] "snapclient" (1030) uses deprecated CP15 Barrier instruction at 0x66aa8
[ 1870.326912] "snapclient" (1030) uses deprecated CP15 Barrier instruction at 0x66ac0
[ 1870.326927] "snapclient" (1030) uses deprecated CP15 Barrier instruction at 0x66ac8

Any ideas?  Seems there some CPU instruction that has been deprecated that snapclient is calling.  Would a recompile to ARM64/aarch64 fix it?

dantheperson@rockski:/etc/resolvconf/resolv.conf.d$ uname -a
Linux rockski 4.4.77-rk3328 #29 SMP Mon Nov 20 03:26:28 CET 2017 aarch64 aarch64 aarch64 GNU/Linux

Thanks,
Dan.

**Comment by badaix** [comment]
Maybe recompiling would help. Can try to do so?

**Comment by dantheperson** [comment]
OK finally gave building from source a go and confirm a native arm64 build solves this issue.  So any plans to add an arm64 build to your standard release set?

**Comment by dantheperson** [comment]
Alternatively just found you can disable the kernel warnings.

echo 2 >/proc/sys/abi/cp15_barrier

**Comment by paulolc** [comment]
To persist across reboots (sysctl -a| grep cp15):

`echo abi.cp15_barrier = 2 >> /etc/sysctl.d/snapserver.conf`

Since there are not (yet?) native arm64 builds available, shouldn't this be added to the armhf builds somehow?
