### ISSUE TITLE
Develop Running 100% cpu on one core

### ISSUE THREAD

**Issue by cosmo6110** [badaix/snapcast#36]
Hi!
Thank's for a great program.
I'm using the master bransh with a Rasperry PI, it's working very good.
But when i try the devel bransh i have problem with the processor load,
its only using one core 100% and the rest about 5-10% and the sound is jittering.
I'm running Volumio 1.5 with iqaudio Pi-dac+  Server and client. 
It's it anything i can try to avoid the jittering?
I compiled from the source code, Kernel 3.18.5-v7+, no pulse audio, gcc version 4.9.2 (Raspbian 4.9.2-10). I got same problem with the deb package.
br
Tommy

**Comment by badaix** [comment]
Which process is causing the load? Client or server?
Does is make a difference if audio is playing or not?

**Comment by cosmo6110** [comment]
It's /usr/sbin/snapserver -d
7364 root  20   0 51844 2420 2148 S _** CPU100,0 %**_  0,2   4:15.62 snapserver
It's 100 % all the time.
It's make no difference if audio is playing.

**Comment by badaix** [comment]
can you see something suspicious in syslog?
`cat /var/log/syslog`

You can also stop the service and start snapserver manually on the command line to see, if an error is logged.

**Comment by cosmo6110** [comment]
I got this when i start the service manually.
2016-03-04 22-47-51 [err] Exception: end of file.

This is from Master bransh
2016-03-04 22-49-02 [out] Adding service 'SnapCast'
2016-03-04 22-49-02 [out] Service name collision, renaming service to 'SnapCast #2'
2016-03-04 22-49-02 [out] Adding service 'SnapCast #2'
2016-03-04 22-49-03 [5] ControlServer::NewConnection: 192.168.2.103
2016-03-04 22-49-03 [out] Service 'SnapCast #2' successfully established.

**Comment by cosmo6110** [comment]
Hi!
After i restart again the problem is gone.
The **[err] Exception: end of file** is gone.
and it's working, strange error.
br
Tommy

**Comment by cosmo6110** [comment]
Little more info, when i start from /etc/init.d/snapserver start
i got 100% cpu on one core.
If i start manually it's working.

**Comment by cosmo6110** [comment]
Hi!
The problem is gone with your latest release. :)
br Tommy

**Comment by badaix** [comment]
Cool, acutally I wasn't able to reproduce the issue (using the latest version)

**Comment by 1337sup3rh4x0r** [comment]
Actually I am now seeing exactly the same behaviour with the latest snapserver 0.10 on FreeBSD. If I run it as deamon, load rises to 100% as soon as a client is connected. 
If I run it manually, all is good.

Syslogs don't show anything. How could I help debugging this?
