### ISSUE TITLE
Multiple snapserver in lan

### ISSUE THREAD

**Issue by fuchsmich** [badaix/snapcast#360]
Hi,

Some people (like me) don't have all their sound sources on one device.
In my case I got one RPi which streams mpd (and librespot) and at my openwrt-router there is an old turntable.
There are two solutions, which come to my mind:
1. Having one central snapserver: stream (via pulseaudio or other) from openwrt to RPi with snapserver on it. In this case you have a lot more traffic in the network.
2. Have multiple snapservers (on openwrt and RPi), but then it's more difficult to manage the clients.

So: Wouldn't it be nice to have one master server, which manages all streams (also from other snapservers in the lan)? Or all snapservers manage all available streams (also the ones from other servers) in the lan.

Do you think something like this is possible and worth implementing?

**Comment by peperjohnny** [comment]
Couldn't you put the clients via the app to the snapserver that is currently streaming?

**Comment by fuchsmich** [comment]
It's no solution to my question, but I have a setup now, which makes me very happy so I wanted to share it:

# Machines:
* livingroom-pi (snapserver, mpd)
* kitchen-pi (snapclient)
* openwrt-router (usb-soundcard with phono line-in connected to the turntable)

## kitchen-pi
It's just a simple snapclient, plugged to a cheap soundmachine via line-out.

## openwrt-router
Installed kernel module for usb-soundcard (kmod-usb-alsa), alsa-utils and sox.

## livingroom-pi
RaspberryPI 3 running arch and connected to my Onkyo receiver via hifiberry DIGI+ and coax cable.

`$ grep SNAPSERVER_OPTS /etc/default/snapserver
SNAPSERVER_OPTS="-s pipe:///tmp/snapfifo?name=mpd&sampleformat=48000:16:2&codec=flac -s pipe:///tmp/vinyl?name=Vinyl"
`
`cat /etc/systemd/system/vinyl.service 
[Unit]
Description=Vinyl2FIFO
Requires=snapserver.service
After=snapserver.service

[Service]
User=snapserver
Group=snapserver
ConditionPathExists=/tmp/vinyl
ExecStart=/usr/bin/sh -c '/bin/ssh -C vinyl@openwrt.home.fuxl.info sox -q -t alsa default  -p silence 1 0.2 0.05% -1 0.2 0.05% | sox -q -p -t wav -r 48k -b 16 -c 2  /tmp/vinyl'
Restart=always

[Install]
WantedBy=multi-user.target
`

Of course no HIFI afficionado would do this. But I'm quiet happy with the sound quality.

What I first didn't like was the fact, that ssh and sox and snapserver would constantly keep streaming, because there is always some kind of signal at the line in of the usb soundcard. But then I found the silence filter.

This part `-1 0.2 0.05%` filters silence in the middle of the stream. So when I take the needle of the record, the sox stream stops, snapserver stops streaming and snapclient stops playing sound (of course) and after some seconds releases the alsa device.

Issues:
* vinyl.service starts too early. It should wait till openwrt is reachable via ssh. A restart delay could help.
* When restarting vinyl.service sometimes the sound is scrambled. But after restart snapserver OR vinyl.service, the sound is fine again.

**Comment by fuchsmich** [comment]
@peperjohnny That's the thing I'm asking for. ;)
snapserver (e.g. the one the app is connected to) is not aware of other snapserver's streams. That's one reason why there is no command to connect one client to another server's stream.

**Comment by badaix** [comment]
You can use the TCP stream plugin (see #511) to forward audio to the Snapserver
