### ISSUE TITLE
How can I know whether the music is played time synchronized between all clients?

### ISSUE THREAD

**Issue by lszhou0126** [badaix/snapcast#364]
Is there a method to judge the synchronization, since I can't only believe my ears.
And I found a problem, after one client plays silence and start music, it's out of synchronization which can be hear clearly. The out-sync will last about ten seconds and come to synchronization slowly. I wish the synchronization can be achieved as quick as possible. Is there anything I can do?

**Comment by Suz2905** [comment]
I had similar problem and put it down to poor wifi connections - when hard wired the synchronization ran almost perfectly (still get a slight gap occasionally). Now I've replaced the wifi adapters, use hard wired where possible and where using the Pi0 have put a wifi network range extender close to it. Works well now.

**Comment by badaix** [comment]
when you start snapclient manually on a console, you can see the sync quality logged in 4 columns in tens of a millisecond (the 0-s in this case, next is some ALSA buffer size followed by the DACs playout buffer size):
```
2017-12-06 17-06-10 [out] Chunk: 0      0       0       0       500     119
2017-12-06 17-06-11 [out] Chunk: 0      0       0       0       500     89
```

**Comment by Suz2905** [comment]
Thanks - that's really interesting, trouble is I could sit and watch the figures go by, it's a bit hypnotic.

**Comment by lszhou0126** [comment]
@badaix  Thanks. BTW, what does these logs mean:
2018-03-12 10-21-14 [Info] sleep < -bufferDuration/2: -111 < -85, sleep: -111
2018-03-12 10-21-14 [Info] sleep < -bufferDuration/2: -111 < -85, sleep: 58
2018-03-12 10-21-14 [Info] Sleep 58, age: 58, bufferDuration: 170

**Comment by Urik1488** [comment]
2018-03-12 10-21-14 [Info] sleep < -bufferDuration/2: -111 < -85, sleep: -111
2018-03-12 10-21-14 [Info] sleep < -bufferDuration/2: -111 < -85, sleep: 58
2018-03-12 10-21-14 [Info] Sleep 58, age: 58, bufferDuration: 170

Also, have to mention that when this happens on the snapclient side (sleep), it causes hiss from the soundcard if there is a range 5k-10kHz been playing.

**Comment by badaix** [comment]
Please try again with v0.19.0. it has several improvements regarding synchronization.
Bad news for @Suz2905: for trouble shooting there is still only the advise to watch the numbers as a measure for synchronization.
