### ISSUE TITLE
What's the functions of these threshold values.

### ISSUE THREAD

**Issue by lszhou0126** [badaix/snapcast#366]
In stream.cpp, for buffer, shortbuffer and minibuffer, there are three thresholds (1ms, 5ms, and 50ms). Can I modify these values? Since my job always print log as buffer->full.
My bufferDuration is about 170ms, bufferDuration/2 is 85ms, it make the clients come to sync slowly. Can I modify "if (sleep_ < -bufferDuration/2)" to "if (sleep_ < -bufferDuration/6)"?

**Comment by badaix** [comment]
Please check with a recent version. It should sync a lot quicker. These values are still there and you can try to tweak them to meet your needs.
The different buffers are there to react quickly to sync issues. The larger the buffer, the smaller are the allowed deviations.
