### ISSUE TITLE
HDMI-CEC

### ISSUE THREAD

**Issue by dougmoscrop** [badaix/snapcast#369]
I have a Nexus Player and an nVidia Shield TV and one of the nice things that they do is power on the attached amplifiers when I start casting using Google Cast.

I think it could be possible for the Android (and perhaps others) to make use of the HDMI-CEC feature if present to do the same. Is this something you'd consider? I can't promise I would be able to make the PR, but I'd at least hope to know that you would accept something like that if I were.

**Comment by IVData** [comment]
I don't think that Snapcast should concern itself with HDMI-CEC as that's a very specific integration and not really Snapcast's job.

I have the setup you're asking for, and I do it by checking when my media player starts playing (mopidy) and issuing the HDMI-CEC commands then.

**Comment by dougmoscrop** [comment]
Oh, I see. I think maybe I just don't understand how any of this works ;)

When you say checking / issuing what's doing the that? A daemon on the device (e.g. Nexus Player)?

Or do you mean you have some kind of generic RPC bridge (for example Home Assistant or some other remote process notices the playback and ensures the speaker/amp/whatever) is on?

**Comment by dougmoscrop** [comment]
The same Rpi or two separate ones? I guess it doesn't matter..

Hmm, my case was to use snapcast on a Nexus Player (so not quite as open as an Rpi) 

Thanks for the info. I'm gonna to take more time to think about this.
