### ISSUE TITLE
Adding an new Group

### ISSUE THREAD

**Issue by SymanK83** [badaix/snapcast#370]
Hello,
I‘m currently developing a web application to control Snapcast. It‘s the perfect software for my home application and I‘m really happy to have found it.
Maybe the UI will be helpful for others as well in a few weeks.
On my way to add the desired functionality I ran into a problem with grouping the clients.

When I added all my clients to a group, I know no way of splitting that group afterwards. Is there a way to assign a client to a new group that is created for that reason? I could not find a function in the JSON-RPC API...

Your help is greatly appreciated.
Thank you for this software :-)

**Comment by fuchsmich** [comment]
A new group gets created by the server, when you remove a client from an existing group.

**Comment by fuchsmich** [comment]
Yes, that's how I'm doing it in my app.

**Comment by SymanK83** [comment]
That‘s working. Great!
Thanks for helping out.
