### ISSUE TITLE
Gstreamer errors when airplay is enabled in config file

### ISSUE THREAD

**Issue by vash3d** [badaix/snapcast#371]
Hi all,
I'm trying to setup mopidy and Snapcast to use them in combination with home assistant tts service, but I can't get this to work.

If I let mopidy create the snapfifo file, when I use the tts service I can hear the voice repeated in an infinite loop.
Indeed I read in other posts that should be Snapcast to create the snapfifo file.
But if I let Snapcast create the file I can't here nothing from mopidy and I got this error 

`GStreamer error: gst-resource-error-quark: Error while seeking in file "/tmp/snapfifo". (11)`

Instead if I manually create the file with `mkfifo /tmp/snapfifo` I get this error 

```
Mar 24 14:13:31 hassbian mopidy[17603]: ERROR    GStreamer error: gst-resource-error-quark: Could not open file "/tmp/snapfifo" for writing. (6)
Mar 24 14:13:31 hassbian mopidy[17603]: WARNING  Setting GStreamer state to GST_STATE_PLAYING failed
Mar 24 14:13:31 hassbian mopidy[17603]: WARNING  Track is not playable: http://192.168.1.152:8123/api/tts_proxy/f0fa9097a41d357ca711da49ab4f935720e67a52_it_-_google.mp3
```

I've this in my Snapcast configuration now

```
SNAPSERVER_OPTS="-d -s airplay:///usr/bin/shairport-sync?name=Airplay&devicename=Multiroom&port=5000] -s pipe:///tmp/snapfifo?name=Mopidy&sampleformat=48000:16:2&codec=flac&mode=read"
```

the airplay part works flawlessly.

Any advice is really appreciated,
thanks

**Comment by Suz2905** [comment]
I think I've got a similar setup to you, Hassbian, Mopidy and Snapserver with 4 clients attached on a Rpi 3, I don't use airplay.
I've just checked and I can use the tts service, unfortunately waking my wife in the process, I forgot to mute the client in the bedroom!!
Let me know if you want any of the details of my setup that may help you.

**Comment by vash3d** [comment]
Thanks for the help.
If you can share your configuration of mopidy and snapcast server maybe I could see If I have something wrong in my setup.
What about the snapfifo file? Do you know if in your setup it is created by snapcast or mopidy?

p.s.
sorry for you wife :/

**Comment by vash3d** [comment]
Mopidy config file looks the same as mine.
So the issue is in the airplay part in the snapcast server configuration.
I've updated the the title to match the problem more closely, maybe someone has had similar experiences.

thanks anyway

**Comment by Suz2905** [comment]
I don't know if this link is of any use https://nik.re/2016/09/04/mopidy-shairport-sync-and-snapcast-is-a-gread-combo

**Comment by vash3d** [comment]
Already seen that, but didn't solve.
I'm out of ideas...
I'll wait for someone with a similar setup or give up trying using both mopidy and airplay and stick to only one. 

thanks for your time.

**Comment by nimonimonimo** [comment]
This solved similar error for me: https://unix.stackexchange.com/questions/503111/group-permissions-for-root-not-working-in-tmp

sysctl fs.protected_fifos=0
