### ISSUE TITLE
snapclient doesn't list pulseaudio output on libreelec

### ISSUE THREAD

**Issue by Catscrash** [badaix/snapcast#373]
Hi,

when I start "snapclient -l" on my ubuntu system, I have the following output:

```
0: default
Playback/recording through the PulseAudio sound server

1: null
Discard all samples (playback) or generate zero samples (capture)

2: pulse
PulseAudio Sound Server
[...]
```

If I use 0, snapclient becomes a source for pulseaudio and outputs the stream properly to pulseaudio.

Now there is a really greate libreelec snapclient addon. But when I run snapclient -l here, only ALSA output is being shown:

```
0: null
Discard all samples (playback) or generate zero samples (capture)

1: default:CARD=ALSA
bcm2835 ALSA, bcm2835 ALSA
Default Audio Device

2: sysdefault:CARD=ALSA
bcm2835 ALSA, bcm2835 ALSA
Default Audio Device
```

On Libreelec runs a pulseaudio server, which I need snapclient to use, pactl info gives a proper output with the correct sink selected.

```
pactl info
Server String: /var/run/pulse/native
Library Protocol Version: 32
Server Protocol Version: 32
Is Local: yes
Client Index: 60
Tile Size: 65496
User Name: root
Host Name: kodi-bad
Server Name: pulseaudio
Server Version: 11.1
Default Sample Specification: s16le 2ch 44100Hz
Default Channel Map: front-left,front-right
Default Sink: bluez_sink.40_EF_4C_B4_1F_69.a2dp_sink
Default Source: bluez_sink.40_EF_4C_B4_1F_69.a2dp_sink.monitor
Cookie: ba49:1d5d

```

What is the mechanism that allows snapclient to find the pulseaudio output, that might not be working on libreelec? I'm happy to try and recompile the snapclient addon with different settings, if I have some kind of starting point

thanks!

**Comment by fuchsmich** [comment]
1. Is pulseaudio available to the user, which runs snapclient? (run `pactl info` with the same user as you run `snapcast -l`)
2. Is pulseaudio-alsa plugin available and configured? (in Arch the config is in `/etc/asound.conf`

**Comment by Catscrash** [comment]
@fuchsmich  thanks for your answer

1. yes, snapcast is running as root - so is pactl info

2. I'm not sure, does pactl list help? There's no /etc/asound, but that's not the case on my ubuntu as well. pactl list output is here: https://pastebin.com/HEFisYME

The pulseaudio server is being used by the rest of the system and output is working properly for everything except for snapclient

**Comment by fuchsmich** [comment]
I don't know how ubuntu or libreelec are configured. But somehow you got to tell alsa to not access the soundcard directly but use pulse plugin.
I guess, you can do this by creating an [/etc/asound.conf](https://git.archlinux.org/svntogit/packages.git/tree/trunk/asound.conf?h=packages/pulseaudio-alsa)

**Comment by fuchsmich** [comment]
I couldn't find a lot of documentation on libreelec, but it seems to be based on JeOS, which is based on SUSE. So the correct package should be `alsa-plugins-pulse`. Check, if it's installed. There should be a file `/etc/asound-pulse.conf` with similar content as posted above.

**Comment by Catscrash** [comment]
yep, you're right alsa-plugins is missing completely, alsa-plugins-pulse as well. I'll try to get that in there, thanks a lot for your help
