### ISSUE TITLE
Compilation errors on FreeBSD 11.1

### ISSUE THREAD

**Issue by jonahquark81** [badaix/snapcast#374]
Building the server on FreeBSD 11.1 with `gmake TARGET=FREEBSD HAS_EXPAT=1 server` I received these 2 compilation errors.

    In file included from encoder/oggEncoder.cpp:25:0:
    ../common/utils/string_utils.h: In function 'std::__cxx11::string utils::string::uriDecode(const string&)':
    ../common/utils/string_utils.h:83:48: error: 'sscanf' was not declared in this scope
        sscanf(src.substr(i+1, 2).c_str(), "%x", &ii);

    streamreader/airplayStream.cpp: In constructor 'AirplayStream::AirplayStream(PcmListener*, const StreamUri&)':
    streamreader/airplayStream.cpp:48:52: error: 'to_string' was not declared in this scope
      pipePath_ = "/tmp/shairmeta." + to_string(getpid());
                                                    ^

**Comment by badaix** [comment]
fixed in release [v0.14.0](https://github.com/badaix/snapcast/releases/tag/v0.14.0)
