### ISSUE TITLE
Feature request: Group Volume

### ISSUE THREAD

**Issue by aawsome** [badaix/snapcast#376]
Hi,

I'm about to write a mopidy extension to control snapcasts volumes as a mixer. My basic idea is to identify the group which is connected to the stram which mopidy is feeding and handle the according group mute and volume status.
At the moment, each group has a mute status which can be read and set. However, to get and set the "group volume" I have to find out the volumes of all clients connected to this group.
Besides being quite some overhead, there are some side effects when changing the artificial "group volume": E.g. when lowering the volume to Zero and raising it again, the original ratios between client volumes is lost. The same effect applies when raising the volume to 100% and lowering it again.

So, my question is: Could a group volume be added (and controlled controlled by the API) which simply multiplies with each client's volume?

**Comment by aawsome** [comment]
Just for information: The initial release of my Mopidy snapcast mixer Extension is now available, see [mopidy-snapcast](https://github.com/aawsome/mopidy-snapcast)

**Comment by badaix** [comment]
for group volumes you can use a batch jsronrpc command to change the volume of several clients with a single request. There is no unique way of how to change the group volume. Snapdroid does it in a similar way as sonos does.
