### ISSUE TITLE
How do I have snapclient up

### ISSUE THREAD

**Issue by comarius** [badaix/snapcast#377]
Hi,
How do I have snapclient up all the time so it would play when snapserver broadcasts
Thx.

**Comment by fuchsmich** [comment]
Please provide some more information on your system. My best guess is you run it as a system service.

**Comment by palitu** [comment]
use systemd to start the service when you boot up, after the netwrok.

**Comment by comarius** [comment]
Hi, is running as a service already, but does not play by default when the server starts.
    ps ax | grep snap ... 
    /usr/bin/snapclient -d --user snapclient:audio

**Comment by palitu** [comment]
is it muted in the app?

**Comment by comarius** [comment]
It was the Orange Pi distro. problem. I removed allsa + pusle, and reinstalled them again.
I rebuild and reinstalled snap package, and now stars every time. Thank you
