### ISSUE TITLE
[Question] Setting up Bluetooth A2DP audio sink

### ISSUE THREAD

**Issue by herrwusel** [badaix/snapcast#379]
I have a pi3 which runs snapserver and snapclient. Mopidy and librespot both run well. Now I wanted to add a2dp to the pi3. I followed this [gist](https://gist.github.com/mill1000/74c7473ee3b4a5b13f6325e9994ff84c) which is using bluealsa.

So my understanding is that I need to configure Alsa to write another fifo file in /tmp. But when I add /etc/asound.conf as described [here](https://github.com/badaix/snapcast/blob/master/doc/player_setup.md#alsa) I dont hear anything from my pi3. Only snapclients connected play correctly. When reverting the changes to asound.conf everything except bluetooth is working again. Can someone give me an hint what I did wrong? Thanks!

**Comment by fuchsmich** [comment]
I guess, the error is in the first line of /etc/asound.conf, it makes /tmp/snapfifo the systemwide default sink for players using alsa. So snapclient is playing back to snapserver.

Suggestion: On Pi3 run snapclient and bluez-alsa with different users and put /etc/asound.conf as ~/.asoundrc into the home of the user which runs bluez-alsa.

**Comment by herrwusel** [comment]
Setting up a new user did the trick. Thanks for the hint @fuchsmich !

**Comment by fuchsmich** [comment]
Just to be sure: you are streaming via bluetooth to RPi3 and from there via snapserver to other clients?

If yes, this is an awesome idea and does it work fine?

**Comment by derglaus** [comment]
Awesome idea, but didn't work flawless for me. Always had some hickups, seems to be related to RPi3 and using both build in bluetooth and wifi at the same time. My solution is to use an external bluetoth receiver and feed it by a line in into the RPi and Snapcast

**Comment by herrwusel** [comment]
It is working that way @fuchsmich.  I'm mainly using spotify (librespot) but also have other sources like google music, german radio audio library and some youtube playlist. For these I wanted a bluetooth connection to the rpi3. I testest all my usecases and it's working well. I didn't notice any problems at all (besides my technical shortcomings). 

@derglaus: Known problem which is easy to fix. I'm using the ethernet connection of my pi since it is near my router. Do you experience issues with your external receiver?

In general I really like the multiroom solution. I recently added nodes and was surprised how cheap and easy the process was. Buy a zero w, PCM5102A, PAM8610 and throw in some old speakers and a psu (I 3d printed cases as well). Since I had another node I just needed to take an image and flash it to the new ones. Change the hostname - that's it. Very convenient :)

**Comment by fuchsmich** [comment]
Snapcast is such an amazing project. It's a pity, that my falt is so small. ;) I'm just using it for living room and kitchen.

But I defenitly got to try this streaming via bluetooth.

**Comment by derglaus** [comment]
I'm using the pi zero,  so no cable lan... 
For now it works fine. Pi zero + fe-pi as server,  pi zero + hifiberry as client,  either the android app or my own webinterface (on any client and/or a dedicated pi+touchscreen) to control the system

**Comment by dmckminard** [comment]
@herrwusel can you explain me a bit how did you manage to run snapclient and bluez-alsa to different user please ?

**Comment by herrwusel** [comment]
Sure.
Create a user and place said config inside the newly created home directory:
```bash
$ cat /home/bluemusic/.asoundrc 
pcm.!default {
        type plug
        slave.pcm rate48000Hz
}

pcm.rate48000Hz {
        type rate
        slave {
                pcm writeFile # Direct to the plugin which will write to a file
                format S16_LE
                rate 48000
        }
}

pcm.writeFile {
        type file
        slave.pcm null
        file "/tmp/bluesnapfifo"
        format "raw"
}
```
Change the service file from the gist to the newly created user:
```bash
$ cat /etc/systemd/system/a2dp-playback.service 
[Unit]
Description=A2DP Playback
After=bluealsa.service syslog.service
Requires=bluealsa.service

[Service]
ExecStartPre=/bin/sleep 3
ExecStart=/usr/bin/bluealsa-aplay --profile-a2dp 00:00:00:00:00:00
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=A2DP-Playback
User=bluemusic

[Install]
WantedBy=multi-user.target
```

That should be it.

**Comment by dmckminard** [comment]
Ok ! And I can let the settings needed for my sound card :

```
pcm.!default {
type hw
card 0
}
ctl.!default {
type hw
card 0
}
```

In my /etc/asound.conf so ?

**Comment by herrwusel** [comment]
I didn't change it iirc.

**Comment by dmckminard** [comment]
And your configuration in /etc/default/snapserver seems like this no ? :
`SNAPSERVER_OPTS="-d -s pipe:////tmp/bluesnapfifo?name=Bluetooth&mode=read"`
Cause i still get no sound, even for my slave :/

**Comment by herrwusel** [comment]
`SNAPSERVER_OPTS="-d -s pipe:///tmp/bluesnapfifo?name=Bluetooth"`
This works for me. You might have a `/` too many.

**Comment by stvnmbr1** [comment]
I managed to get this working in buster :D but how do you resolve choppy music in snapclient if music is sent through BT to snapserver?

**Comment by mbrebion** [comment]
I'm trying to follow your path
My problem is about files acces rights
the bluesnapfifo is created by another user (which I named btstreamer) and snapserver started by the main user (pi) cannot access it
The problem is that I don't know how to change the permissions on the bluesnapfifo file once its created as this is done from the .asoundrc file

**Comment by dmckminard** [comment]
And if you try to add the user pi to the group bluetooth by 
`sudo adduser pi bluetooth` ?

**Comment by mbrebion** [comment]
Its already the case ;-)
The only temporary solution I've found is to chmod the file bluesnapfifo after its created but I 'd like to get a clean solution instead.

**Comment by dmckminard** [comment]
Of course ! 
You should try to re-install the Bluetooth side with this kind of thing : https://github.com/nicokaiser/rpi-audio-receiver
I've use it, and everything is working for me

**Comment by mbrebion** [comment]
I think that the problem does not come from the bluetooth stack but from file permissions !

**Comment by daftmab** [comment]
I'm getting audio from bluetooth to raspberry but not to the fifo file.
bluetooth audio playing directly over headphonejack. not over snapcast. what am I doing wrong?
**/etc/asound.conf deleted.**

```
/home/bluemusic# cat .asoundrc
pcm.!default {
        type plug
        slave.pcm rate48000Hz
}

pcm.rate48000Hz {
        type rate
        slave {
                pcm writeFile # Direct to the plugin which will write to a file
                format S16_LE
                rate 48000
        }
}

pcm.writeFile {
        type file
        slave.pcm null
        file "/tmp/bluesnapfifo"
        format "raw"
}
```

and

```
/home/bluemusic# cat /etc/systemd/system/a2dp-playback.service
[Unit]
Description=A2DP Playback
After=bluealsa.service syslog.service
Requires=bluealsa.service

[Service]
ExecStartPre=/bin/sleep 3
ExecStart=/usr/bin/bluealsa-aplay --profile-a2dp 00:00:00:00:00:00
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=A2DP-Playback
User=bluemusic

[Install]
WantedBy=multi-user.target
```

any idea?
I would really appreciate it!

**Comment by daftmab** [comment]
GOT IT!
in case someone trips over it:
> adding bluemusic to audio group.
> edit a2dp-playback.service
```
cat /etc/systemd/system/a2dp-playback.service -> ExecStart
[Unit]
Description=A2DP Playback
After=bluealsa.service syslog.service
Requires=bluealsa.service

[Service]
ExecStartPre=/bin/sleep 3
ExecStart=/usr/bin/bluealsa-aplay -d writeFile --profile-a2dp 00:00:00:00:00:00
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=A2DP-Playback
User=bluemusic

[Install]
WantedBy=multi-user.target
```
Sound was stuttering. Edit the pipe in /etc/snapserver.conf and add &sampleformat=44100:16:2&mode=read.
```source = pipe:///tmp/bluesnapfifo?name=Bluetooth&sampleformat=44100:16:2&mode=read```

**Comment by daftmab** [comment]
why do we use the fifo file and not loopback alsa?
I tried it and it seems to work flawless. And no I/O on the SD card. -> longer lifespan.
With fifo I've got a delay, too.

**Comment by ssieb** [comment]
A fifo "file" is not really a file.  All data is transferred in memory, so there's no disk access.

**Comment by daftmab** [comment]
realy? didn't know that. anyway, performance is much better with loopback alsa. At least in my case. Raspberry 4 Snapserver and client. Onboard Bluetooth. Lan. no Wifi.

**Comment by aatoma** [comment]
hi daftmab,

can you, please, share your snapserver source configuration for loopback alsa? I'm trying to implement the same use case, but without success so far

**Comment by daftmab** [comment]
Sorry for the delay.
It has been a while. Don't know what you realy need from this. /etc/asound.conf for sure.
Snapserver.conf
`source = alsa://?name=Bluetooth&device=hw:0,1,1&send_silence=true&idle_threshold=100`

```
root@Galerie:/home/pi# cat /lib/systemd/system/snapserver.service
[Unit]
Description=Snapcast server
Documentation=man:snapserver(1)
Wants=avahi-daemon.service
After=network.target time-sync.target avahi-daemon.service bluesalsa-aplay

[Service]
EnvironmentFile=-/etc/default/snapserver
ExecStart=/usr/bin/snapserver --logging.sink=system --server.datadir=${HOME} $SNAPSERVER_OPTS
User=snapserver
Group=snapserver
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

```
root@Galerie:/home/pi# cat /etc/systemd/system/bt-agent-a2dp.service
[Unit]
Description=A2DP Bluetooth Agent
After=bluetooth.service
Wants=bluetooth.service

[Service]
ExecStartPre=/bin/sh -c "echo discoverable on | bluetoothctl"
ExecStart=/usr/bin/python -u /usr/local/bin/a2dp-agent
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=A2DP-Agent

[Install]
WantedBy=bluetooth.service
```
```
root@Galerie:/home/pi# cat /lib/systemd/system/snapclient.service
[Unit]
Description=Snapcast client
Documentation=man:snapclient(1)
Wants=avahi-daemon.service
After=network.target time-sync.target sound.target avahi-daemon.service

[Service]
EnvironmentFile=-/etc/default/snapclient
ExecStart=/usr/bin/snapclient -s 33  $SNAPCLIENT_OPTS
User=_snapclient
Group=_snapclient
# very noisy on stdout
StandardOutput=null
Restart=on-failure

[Install]
WantedBy=multi-user.target
```
```
root@Galerie:/home/pi# cat /etc/systemd/system/a2dp-playback.service
[Unit]
Description=A2DP Playback
After=bluealsa.service syslog.service snapserver
Requires=bluealsa.service

[Service]
ExecStartPre=/bin/sleep 3
ExecStart=/usr/bin/bluealsa-aplay -d bluetooth --profile-a2dp 00:00:00:00:00:00
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=A2DP-Playback
#User=bluemusic

[Install]
WantedBy=multi-user.target
```

```
root@Galerie:/home/pi# cat /etc/asound.conf

pcm.snd_card {
    type hw
    card 0
    device 0
    subdevice 1
}

ctl.snd_card {
    type hw
    card 0
    device 0
    subdevice 1
}

pcm.bluetooth {
    type plug
    slave.pcm "snd_card"
}
```

**Comment by aatoma** [comment]
Wow! There's a whole lot I was missing, especially the BT agent and alsa configuration part. Let me see if I get this correctly (I need to adapt this to n Odroid C2 running Arch):
you are routing bluealsa output to an alsa device called 'bluetooth' and then configuring the 'bluetooth' alsa device as a source in snapserver, right?

**Comment by daftmab** [comment]
I'm more the "fire and forget guy". Sorry :-D. 
But seems correct to me.

**Comment by marfis89** [comment]
Hi @daftmab is there a typo ? 

`source = alsa://?name=Bluetooth&device=hw:0,1,1&send_silence=true&idle_threshold=100`

if i add your source to the snapserver.conf i get an error from the snapserver.service `1005 ExecStart=/usr/bin/snapserver --logging.sink=system --server.datadir=${HOME} $SNAPSERVER_OPTS (code=exited, status=1/FAILURE)`

Iam using a pi3 with a fresh setup and the `pipe:///tmp/bluesnapfifo` sulution "works" so far. But the delay is awful.  

pi 3 and 4 are equal for your solution?

Danke für deine Arbeit!

Regards
Martin

**Comment by daftmab** [comment]
It's a direct copy of my config.
the hardware device might differ in your case.

**Comment by abelmatser** [comment]
@marfis89 @aatoma I just got it working. I gave a small explanation on the gist which allowed me to use bluetooth as a sink in the first place: [https://gist.github.com/qcasey/5bd4943b27320e65a033948fafb86d19#gistcomment-3746240](https://gist.github.com/qcasey/5bd4943b27320e65a033948fafb86d19#gistcomment-3746240). I have only tested this on my Orange Pi Zero SBC, but plan to try in a VM as well.
