### ISSUE TITLE
logs show synchronization while there is out-sync audibly

### ISSUE THREAD

**Issue by lszhou0126** [badaix/snapcast#383]
Tow clients show logs about Chunk: 4 3 0 3 500 119 and Chunk: 0 2 0 0 500 119, which mean synchronization. However I can hear out-sync. I think it maybe due to the poor network, right?

**Comment by mczerski** [comment]
Do You have the same audio paths on both client ? If not then You probably need to set the latency parameter accordingly. If the delay between clients is not changing over time i guess that the latency setting would be a solution.

**Comment by lszhou0126** [comment]
The out-sync is not constant. At the beginning, the clients playing synchronously, while some time later out-sync arise, and the logs show synchronization. So I don't known what's the issue.

**Comment by christf** [comment]
@lszhou0126 do you use ntp?

**Comment by badaix** [comment]
please try the current master branch, which is using a monotonic clock instead of system time
