### ISSUE TITLE
Scroll position lost after device rotation

### ISSUE THREAD

**Issue by calbee633810** [badaix/snapcast#384]
Click About in the menu to open WebView, scroll article and rotate screen. WebView rolls back to top after screen orientation change, but it should keep it.

![screen shot 2018-04-12 at 7 54 37 pm](https://user-images.githubusercontent.com/38213896/38675750-5f263d7a-3e8b-11e8-8bc1-18a5ba429f6d.png)
Screenshot before rotation

![screen shot 2018-04-12 at 7 54 45 pm](https://user-images.githubusercontent.com/38213896/38675754-6530a9c6-3e8b-11e8-8bf3-ab0406d16317.png)
Screenshot after rotation

**Comment by badaix** [comment]
This issue was moved to badaix/snapdroid#4
