### ISSUE TITLE
Why sometimes IPV6 address

### ISSUE THREAD

**Issue by lszhou0126** [badaix/snapcast#385]
Sometimes IPV6 address server found and transport endpoint is not connected. Is there some way to solve this?

**Comment by badaix** [comment]
Please elaborate this. Does the client find via zeroconf an IPv6 address and cannot connect?
The server is broadcasting both, the IPv4 and the IPv6 address. The client will use the first address found.

**Comment by lszhou0126** [comment]
It happens occasionally. Most of the time are IPv4 address and works well. I just check my version and found that it's 0.10.0. Maybe this is the problem. I will update and test it. Thank you.
