### ISSUE TITLE
cannot connect to jsonrpc in any way (other than telnet)

### ISSUE THREAD

**Issue by ehudkaldor** [badaix/snapcast#386]
and while telnet is nice, I'm writing a javascript application and am looking to connect it.
I tried doing a fetch on the url/port, tried curl, nothing works. the logs on SnapCast show this:

```
2018-04-13 06:29:51.383197500  2018-04-13 06-29-51 [Notice] ControlServer::NewConnection: ::ffff:172.18.0.1
2018-04-13 06:29:51.383268500  2018-04-13 06-29-51 [Err] Session inactive. Removing
2018-04-13 06:29:51.597723500  2018-04-13 06-29-51 [Err] Exception in ControlSession::reader(): read_until: End of file
```

this is my curl request. doing the same with telnet works:
```
curl -iv 127.0.0.1:1705 -X POST -H "Content-Type: text/plain" -d "{'id':1,jsonrpc:'2.0',method:'Server.GetRPCVersion'}" -H "Accept: application/json"
```

please help

**Comment by mczerski** [comment]
curl is for http protocol and on the first sentence in the snapcast api documentation it says it is using "raw TCP-Socket" so I don't think You can use curl to connect to snapcast server.

**Comment by ehudkaldor** [comment]
Is there any way someone knows of, to connect with JavaScript?

**Comment by derglaus** [comment]
The only way I found was to translate the telnet to websockets by websockify.

https://github.com/derglaus/snapcast-websockets-ui

**Comment by xabolcs** [comment]
@ehudkaldor try it with `echo` and `socat`!
Note the `-ne` switches of `echo` and the `\r\n` suffix of the payload!
```
$ echo -ne '{"id":1,"jsonrpc":"2.0","method":"Server.GetRPCVersion"}\r\n' | socat - TCP:127.0.0.1:1705
{"id":1,"jsonrpc":"2.0","result":{"major":2,"minor":0,"patch":0}}
```

**Comment by badaix** [comment]
since version 0.17 you can use not only telnet on port 1705, but also HTTP on port 1780, as written in issue #481
