### ISSUE TITLE
No sound from snapclient

### ISSUE THREAD

**Issue by Silver-Centurion** [badaix/snapcast#387]
I am trying to pipe output from MPD to snapserver and listen to the stream with snapclient all on the same machine.  However, there is no sound output to my speakers.

With MPD alone I can play music through the PC speakers just fine.  I have installed both snapserver and snapclient on an Ubuntu 16.04 LTS machine.  That seemed to go fine with no problems.  

### Configuration for the snapserver is the default:
`/etc/default/snapserver`
     START_SNAPSERVER=true
     USER_OPTS="--user snapserver:snapserver"
     SNAPSERVER_OPTS=""

### Configuration for the snapclient is basically the default:
`/etc/default/snapclient`
     START_SNAPCLIENT=true
     USER_OPTS="--user snapclient:audio"
     SNAPCLIENT_OPTS="--host 192.168.0.3"

### Configuration for MPD is:
`/etc/mpd.conf`
     audio_output {
         type            "fifo"
         name            "SnapCast"
         path            "/tmp/snapfifo"
         format          "48000:16:2"
         mixer_type      "software"
     }

### The output of `snapclient --list` is this:
0: default
Playback/recording through the PulseAudio sound server

1: null
Discard all samples (playback) or generate zero samples (capture)

2: pulse
PulseAudio Sound Server

3: sysdefault:CARD=PCH
HDA Intel PCH, ALC892 Analog
Default Audio Device
...

### Status for snapserver looks good:
`/etc/init.d/snapserver status`
● snapserver.service - Snapcast server
   Loaded: loaded (/lib/systemd/system/snapserver.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2018-04-13 15:00:43 MDT; 4s ago
  Process: 5168 ExecStart=/usr/bin/snapserver -d $USER_OPTS $SNAPSERVER_OPTS (code=exited, status=0/SUCCESS)
 Main PID: 5170 (snapserver)
   CGroup: /system.slice/snapserver.service
           └─5170 /usr/bin/snapserver -d --user snapserver:snapserver

Apr 13 15:00:43 dark-tower systemd[1]: Starting Snapcast server...
Apr 13 15:00:43 dark-tower snapserver[5168]: Settings file: "/var/lib/snapserver/server.json"
Apr 13 15:00:43 dark-tower snapserver[5168]: 2018-04-13 15-00-43 [Notice] Settings file: "/var/lib/snapserver/server.json"
Apr 13 15:00:43 dark-tower snapserver[5170]: daemon started
Apr 13 15:00:43 dark-tower systemd[1]: Started Snapcast server.
Apr 13 15:00:44 dark-tower snapserver[5170]: StreamServer::NewConnection: ::ffff:192.168.0.3

### Status for snapclient has some failures:
`/etc/init.d/snapclient status`
● snapclient.service - Snapcast client
   Loaded: loaded (/lib/systemd/system/snapclient.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2018-04-13 15:02:14 MDT; 6s ago
  Process: 5299 ExecStart=/usr/bin/snapclient -d $USER_OPTS $SNAPCLIENT_OPTS (code=exited, status=0/SUCCESS)
 Main PID: 5301 (snapclient)
   CGroup: /system.slice/snapclient.service
           └─5301 /usr/bin/snapclient -d --user snapclient:audio --host 192.168.0.3

Apr 13 15:02:14 dark-tower systemd[1]: Starting Snapcast client...
Apr 13 15:02:14 dark-tower snapclient[5301]: daemon started
Apr 13 15:02:14 dark-tower systemd[1]: Started Snapcast client.
**Apr 13 15:02:14 dark-tower pulseaudio[5305]: [autospawn] core-util.c: Failed to create secure directory (/var/lib/snapclient/.config/pulse): No such file or directory
Apr 13 15:02:14 dark-tower pulseaudio[5324]: [autospawn] core-util.c: Failed to create secure directory (/var/lib/snapclient/.config/pulse): No such file or directory
Apr 13 15:02:14 dark-tower pulseaudio[5324]: [autospawn] lock-autospawn.c: Cannot access autospawn lock.
Apr 13 15:02:14 dark-tower pulseaudio[5324]: [pulseaudio] main.c: Failed to acquire autospawn lock**
Apr 13 15:02:14 dark-tower snapclient[5301]: Connected to 192.168.0.3

### If I run snapclient in non-daemon mode the output I see is this (I condensed output with ellipses):
`snapclient --user snapclient:audio --host 192.168.0.3`
2018-04-13 15-05-24 [Info] Latency: 0
2018-04-13 15-05-24 [Notice] Connected to 192.168.0.3
2018-04-13 15-05-24 [Info] My MAC: "XX:XX:XX:XX:XX:XX", socket: 6
2018-04-13 15-05-24 [Info] ServerSettings - buffer: 1000, latency: 0, volume: 100, muted: 0
metadata:{"STREAM":"default"}
2018-04-13 15-05-24 [Info] Codec: flac
2018-04-13 15-05-24 [Notice] sampleformat: 48000:16:2
2018-04-13 15-05-24 [Info] frames: 1440
2018-04-13 15-05-24 [Info] age > 200: -957
2018-04-13 15-05-24 [Info] sleep < -bufferDuration/2: -957 < -15, sleep: -957
...
2018-04-13 15-05-24 [Info] sleep < -bufferDuration/2: -828 < -15, sleep: -797
2018-04-13 15-05-24 [Info] diff to server [ms]: 0.001
2018-04-13 15-05-24 [Info] sleep < -bufferDuration/2: -797 < -15, sleep: -767
...
2018-04-13 15-05-25 [Info] sleep < -bufferDuration/2: -17 < -15, sleep: 12
2018-04-13 15-05-25 [Info] Sleep 12, age: 12, bufferDuration: 30
2018-04-13 15-05-25 [Info] Chunk: 126	126	126	126	1	123
2018-04-13 15-05-25 [Info] Sleep 11, age: 11, bufferDuration: 30
2018-04-13 15-05-25 [Info] Sleep 10, age: 10, bufferDuration: 30
2018-04-13 15-05-26 [Info] Chunk: 102	102	102	102	1	139
2018-04-13 15-05-26 [Info] Sleep 9, age: 9, bufferDuration: 30
2018-04-13 15-05-26 [Info] Sleep 7, age: 8, bufferDuration: 30
2018-04-13 15-05-26 [Info] Sleep 6, age: 7, bufferDuration: 30
2018-04-13 15-05-27 [Info] Chunk: 76	76	76	76	1	136
2018-04-13 15-05-27 [Info] Sleep 5, age: 6, bufferDuration: 30
2018-04-13 15-05-27 [Info] Sleep 4, age: 5, bufferDuration: 30
2018-04-13 15-05-27 [Info] Sleep 3, age: 4, bufferDuration: 30
2018-04-13 15-05-28 [Info] Chunk: 48	48	48	48	1	130
2018-04-13 15-05-28 [Info] Sleep 1, age: 3, bufferDuration: 30
2018-04-13 15-05-28 [Info] Sleep 0, age: 2, bufferDuration: 30
2018-04-13 15-05-28 [Info] Sleep 0
2018-04-13 15-05-29 [Info] Chunk: 27	27	27	27	4	135
2018-04-13 15-05-30 [Info] Chunk: 30	30	30	30	37	137
...
2018-04-13 15-05-51 [Info] Chunk: 2	2	2	2	500	127
...just keeps listing chunks

So, from what I can tell MPD is talking to snapserver fine.  snapserver is talking to snapclient fine.  Perhaps the issue lies with snapclient talking to pulse audio?  I don't know that for sure as I'm not a Linux audio expert.

**Comment by fuchsmich** [comment]
I assume, you ran `snapclient --list` with your normal login. But you are running snapclient with snapclient:audio. So you got to check, if pulseaudio is available for this user.

    $ sudo -u snapclient -g audio snapclient --list

**Comment by Silver-Centurion** [comment]
@fuchsmich 
The output of `sudo -u snapclient -g audio snapclient --list` is this:
No protocol specified
xcb_connection_has_error() returned true
Home directory not accessible: Permission denied
W: [pulseaudio] core-util.c: Failed to open configuration file '/home/colin/.config/pulse//daemon.conf': Permission denied
W: [pulseaudio] daemon-conf.c: Failed to open configuration file: Permission denied
No protocol specified
xcb_connection_has_error() returned true
Home directory not accessible: Permission denied
W: [pulseaudio] core-util.c: Failed to open configuration file '/home/colin/.config/pulse//daemon.conf': Permission denied
W: [pulseaudio] daemon-conf.c: Failed to open configuration file: Permission denied
0: null
Discard all samples (playback) or generate zero samples (capture)

1: pulse
PulseAudio Sound Server

2: default:CARD=PCH
HDA Intel PCH, ALC892 Analog
Default Audio Device

3: sysdefault:CARD=PCH
HDA Intel PCH, ALC892 Analog
Default Audio Device
...

### My thoughts
There seems to be some issues with PusleAudio and permissions.  Not sure if this is really a problem or not.
With my configuration above, I believe snapclient will try to use the 'default' soundcard.  Which in this case is different from the 'default' under my normal user.  The card listed just above seems legit, so I'm not sure why it doesn't work (but again I'm not a Linux sound expert).

**Comment by Silver-Centurion** [comment]
@gerroon 
If I run snapclient as my normal user in non-daemon mode the output I see is this (I condensed output with ellipses):
`snapclient --user myself:audio --host 192.168.0.3`
2018-04-16 08-14-37 [Info] Latency: 0
2018-04-16 08-14-37 [Notice] Connected to 192.168.0.3
2018-04-16 08-14-37 [Info] My MAC: "XX:XX:XX:XX:XX:XX", socket: 6
2018-04-16 08-14-37 [Info] ServerSettings - buffer: 1000, latency: 0, volume: 100, muted: 0
metadata:{"STREAM":"default"}
2018-04-16 08-14-37 [Info] Codec: flac
2018-04-16 08-14-37 [Notice] sampleformat: 48000:16:2
2018-04-16 08-14-37 [Info] frames: 1440
2018-04-16 08-14-37 [Info] age > 200: -953
2018-04-16 08-14-37 [Info] sleep < -bufferDuration/2: -953 < -15, sleep: -953
...
2018-04-16 08-14-37 [Info] sleep < -bufferDuration/2: -832 < -15, sleep: -801
2018-04-16 08-14-37 [Info] diff to server [ms]: 0
2018-04-16 08-14-37 [Info] sleep < -bufferDuration/2: -801 < -15, sleep: -771
...
2018-04-16 08-14-38 [Info] sleep < -bufferDuration/2: -20 < -15, sleep: 9
2018-04-16 08-14-38 [Info] Sleep 8, age: 9, bufferDuration: 30
2018-04-16 08-14-38 [Info] Chunk: 91	91	91	91	1	119
2018-04-16 08-14-38 [Info] Sleep 8, age: 8, bufferDuration: 30
2018-04-16 08-14-38 [Info] Sleep 7, age: 7, bufferDuration: 30
2018-04-16 08-14-39 [Info] Chunk: 75	75	75	75	1	120
2018-04-16 08-14-39 [Info] Sleep 6, age: 6, bufferDuration: 30
2018-04-16 08-14-39 [Info] Sleep 5, age: 5, bufferDuration: 30
2018-04-16 08-14-39 [Info] Sleep 4, age: 4, bufferDuration: 30
2018-04-16 08-14-40 [Info] Chunk: 45	45	45	45	1	143
2018-04-16 08-14-40 [Info] Sleep 3, age: 3, bufferDuration: 30
2018-04-16 08-14-40 [Info] Sleep 1, age: 2, bufferDuration: 30
2018-04-16 08-14-40 [Info] Sleep 0, age: 1, bufferDuration: 30
2018-04-16 08-14-41 [Info] Chunk: 18	18	18	18	1	138
2018-04-16 08-14-41 [Info] Sleep 0
2018-04-16 08-14-42 [Info] Chunk: 12	12	12	12	28	142
...
2018-04-16 08-15-00 [Info] Chunk: 0	-1	-2	0	500	133
...just keeps listing chunks

### And the sound does come out of my speakers!

So, based on this and the above listing for the user 'snapclient', it seems to me there is a problem with user 'snapclient' permissions for PulseAudio.  However, due to my lack of Linux audio knowledge, I don't know what to change to allow snapclient to work while being run as user 'snapclient'.

**Comment by Silver-Centurion** [comment]
@fuchsmich 
I forgot to mention above that I tried setting the option "--soundcard pulse" and "--soundcard 1" while still using the 'snapclient' user.  And that didn't fix anything.  Which again is making me believe there is a permission problem for user 'snapclient'.

**Comment by fuchsmich** [comment]
The sudo command I provided doesn't seem to be 100% correct. Somehow snapclient still thinks it's called by "myself". Maybe this generates less errors:

    $ sudo --user snapclient --group audio -s /bin/bash
    $ snapclient --list

If there's still no pulseaudio device available, pulseaudio is probably running in user mode on your system. You got to switch to system mode then.

**Comment by Silver-Centurion** [comment]
`$sudo --user snapclient --group audio -s /bin/bash`
`snapclient$ snapclient --list`
No protocol specified
xcb_connection_has_error() returned true
Home directory not accessible: Permission denied
W: [pulseaudio] core-util.c: Failed to open configuration file '/home/myself/.config/pulse//daemon.conf': Permission denied
W: [pulseaudio] daemon-conf.c: Failed to open configuration file: Permission denied
No protocol specified
xcb_connection_has_error() returned true
Home directory not accessible: Permission denied
W: [pulseaudio] core-util.c: Failed to open configuration file '/home/myself/.config/pulse//daemon.conf': Permission denied
W: [pulseaudio] daemon-conf.c: Failed to open configuration file: Permission denied
0: null
Discard all samples (playback) or generate zero samples (capture)

1: pulse
PulseAudio Sound Server

2: default:CARD=PCH
HDA Intel PCH, ALC892 Analog
Default Audio Device

3: sysdefault:CARD=PCH
HDA Intel PCH, ALC892 Analog
Default Audio Device




Output of snapclient when running as user 'snapclient
`sudo -u snapclient -g audio snapclient --user snapclient:audio --soundcard pulse --host 192.168.0.3`
No protocol specified
xcb_connection_has_error() returned true
Home directory not accessible: Permission denied
W: [pulseaudio] core-util.c: Failed to open configuration file '/home/myself/.config/pulse//daemon.conf': Permission denied
W: [pulseaudio] daemon-conf.c: Failed to open configuration file: Permission denied
No protocol specified
xcb_connection_has_error() returned true
Home directory not accessible: Permission denied
W: [pulseaudio] core-util.c: Failed to open configuration file '/home/myself/.config/pulse//daemon.conf': Permission denied
W: [pulseaudio] daemon-conf.c: Failed to open configuration file: Permission denied
2018-04-16 09-17-43 [Info] Latency: 0
2018-04-16 09-17-43 [Notice] Connected to 192.168.0.3
2018-04-16 09-17-43 [Info] My MAC: "XX:XX:XX:XX:XX:XX", socket: 6
2018-04-16 09-17-43 [Info] ServerSettings - buffer: 1000, latency: 0, volume: 100, muted: 0
metadata:{"STREAM":"default"}
2018-04-16 09-17-43 [Info] Codec: flac
2018-04-16 09-17-43 [Notice] sampleformat: 48000:16:2
No protocol specified
xcb_connection_has_error() returned true
Home directory not accessible: Permission denied
W: [pulseaudio] core-util.c: Failed to open configuration file '/home/myself/.config/pulse//daemon.conf': Permission denied
W: [pulseaudio] daemon-conf.c: Failed to open configuration file: Permission denied
ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused

2018-04-16 09-17-43 [Err] Controller::onException: Can't open pulse PCM device: Connection refused
2018-04-16 09-17-45 [Warn] timeout while waiting for response to: 2, timeout 2000
2018-04-16 09-17-45 [Err] Exception in Controller::worker(): Can't open pulse PCM device: Connection refused

I will look into which mode PluseAudio is running (user vs. system).  Thanks.

**Comment by Silver-Centurion** [comment]
@fuchsmich 
So my PulseAudio is running in per-user mode.  Which seems to be the recommended way to run it for security reasons.  So, I probably don't want to change to system wide mode just to get snapclient working.  Thus, I will stick with running snapclient as my normal user instead of user 'snapclient'.
However, my normal user doesn't belong to the 'audio' group whereas user 'snapclient' does.  Things seem to be working fine so far this way.  But is there any reason I would need to add myself to the 'audio' group for snapclient to function properly?

**Comment by fuchsmich** [comment]
I also think, it is the right way to go, not to mess too much with pulseaudio config.

(At least in Archlinux) It is *not* recommended to add your user to the audio group, if you have pulseaudio running. The audio group is needed for direct access to hardware audio devices, which in your case should be done exclusivly by pulse.

Maybe I find some time to figure out, how to start pulse for the snapclient user, before snapclient starts. I will tell you then.

**Comment by Silver-Centurion** [comment]
Just for my understanding of how things are pieced together...
So it sounds like when the snapclient starts it is trying to start an instance of pulseaudio for the user which the snapclient is runnaing as?  And in my case where I was running the snapclient as user 'snapclient', starting the instance of pulseaudio failed.  And that is why I didn't have any sound out of the speakers.  But if I had somehow already gotten an instance of pulseaudio running for the user 'snapclient' before I started the snapclient, things would have worked just fine and I would get sound out of the speakers?

**Comment by fuchsmich** [comment]
I guess there are a lot of ways to start pulse automatically. E.g. on your [distro ](https://packages.ubuntu.com/xenial/amd64/pulseaudio/filelist) it's started automatically with your DE via autostart script (`/etc/xdg/autostart/pulseaudio.desktop`). But it can also be activated via socket (`/usr/lib/systemd/user/pulseaudio.socket`) or dbus.

But I'm quite sure it's not enough to output sound to the pulseaudio-alsa-plugin to trigger pulseaudio. 

So, yes pulseaudio has to run for user snapclient before start of snapclient.

You could try to make the following unit `/etc/systemd/system/pulse-snap.service`:

```
[Unit]
Description=Sound Service for snapclient user

[Service]
# Note that notify will only work if --daemonize=no
User=snapclient
Group=audio
Type=notify
ExecStart=/usr/bin/pulseaudio --daemonize=no
Restart=on-failure

[Install]
WantedBy=default.target
```

then 

```
$ sudo systemctl daemon-reload
$ sudo systemctl start pulse-snap
$ sudo systemctl start snapclient
```

**Comment by Silver-Centurion** [comment]
As I'm not a Linux expert, some of that I don't quite understand.  Regardless, I got my question answered.  Thanks!
Bottom line is my original issue of not getting sound out of the speakers from the snapclient is fixed by running the snapclient as my normal user, so I will close this issue.
Thanks again!

**Comment by brammeleman** [comment]
I've ran into similar troubles. The actual problem is that the home directory of the system user `snapclient` does not exist. Pulse tries to write in that directory and shows the message:
```
Failed to create secure directory (/var/lib/snapclient/.config/pulse): No such file or directory
```
According to `/etc/passwd`, the home directory of `snapclient` is `/var/lib/snapclient`. The problem was solved by creating the homedir:
```
$ sudo mkdir /var/lib/snapclient
$ sudo chown snapclient: /var/lib/snapclient
```
This will likely solve your problem. 

> I was running in to this problem when trying to use snapclient in combination with the Alsa equalizer plugin (`plugequal`). The plugin fails to create a file in the users' home dir and snapclient reports that it has no access to the PCM device.

**Comment by uchagani** [comment]
@partofthething that worked perfectly for me, thanks!

**Comment by adamcstephens** [comment]
`sudo usermod -aG pulse-access snapclient`
AND
changing the group to `pulse-access` in _/etc/default/snapclient_ got it started for me.

**Comment by gerroon** [comment]
> `sudo usermod -aG pulse-access snapclient`
> AND
> changing the group to `pulse-access` in _/etc/default/snapclient_ got it started for me.

Which distro?

**Comment by partofthething** [comment]
Ubuntu. I'm struggling a bit more with it on Pop OS 21.04 for some reason now.
