### ISSUE TITLE
.deb package: Dependency conflict on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by pfink** [badaix/snapcast#39]
When trying to install snapcast on Ubuntu 14.04 LTS, there is a dependency problem with the package `init-system-helpers`. Snapcast requires version `1.18`, but only `1.14` is available. Maybe it's possible to decrease the required version aiming to support also Ubuntu 14.04? Currently I'm running snapclient on 14.04 without any problem, but atm my package management is broken due to the conflict...

**Comment by badaix** [comment]
You're talking about Snapclient v0.4.1 .deb package?
This is really strange. I'm running it on Linux Mint 17.3 Rosa, which is based on Ubuntu 14.04.
Also the packaging is done on Mint 17.3. `apt-cache show init-system-helpers` shows it's version `1.14`.
Can you paste the complete output of your failed `dpkg --install`?

**Comment by pfink** [comment]
I tested it with `v0.4.1` and `v0.5.0~beta-2`. Here the output of `dpkg -i`:
```
Selecting previously unselected package snapclient.
(Reading database ... 87401 files and directories currently installed.)
Preparing to unpack snapclient_0.4.1_armhf.deb ...
Unpacking snapclient (0.4.1) ...
dpkg: dependency problems prevent configuration of snapclient:
 snapclient depends on init-system-helpers (>= 1.18~); however:
  Version of init-system-helpers on system is 1.14.

dpkg: error processing package snapclient (--install):
 dependency problems - leaving unconfigured
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Processing triggers for ureadahead (0.100.0-16) ...
Errors were encountered while processing:
 snapclient
```
To be more precisely, I'm trying to install it on [UDOObuntu](http://www.udoo.org/downloads/) which is based on 14.04. Interestingly, I couldn't reproduce it with the amd64 package one a Virtualbox VM. Here the output of `apt-rdepends snapclient | grep init-system-helpers` with different devices / distributions:

Virtualbox Ubuntu 14.04 amd64: `Depends: init-system-helpers (>= 1.13~)`
UdooNeo UDOObuntu RC1 / 14.04 armhf: `Depends: init-system-helpers (>= 1.18~)`
RPI 2 OSMC armhf: `Depends: init-system-helpers (>= 1.18~)`

So I guess the dependency to 1.18 is only present within the *.armhf.deb packages.

**Comment by badaix** [comment]
the ARM builds are packaged on Raspbian Jessie with init-system-helpers 1.22 installed.
Maybe you can install a [backport of version 1.21](https://launchpad.net/~ondrej/+archive/ubuntu/cyrus-imapd/+sourcepub/4380965/+listing-archive-extra) on your UDOO?

**Comment by pfink** [comment]
Good idea, I installed a [backport of 1.18](https://launchpad.net/ubuntu/utopic/powerpc/init-system-helpers/1.18) which works fine :)
