### ISSUE TITLE
Hear Crackling Using Snapclient With WiFi

### ISSUE THREAD

**Issue by Silver-Centurion** [badaix/snapcast#391]
When I listen to music over WiFi using Snapclient there is a pronounced "crackle" or static noise along with the music.  Kind of similar to how if you aren't tuned into an AM/FM station very well, you get static with the music.  But not exactly like that.  More of a crackle than static.  If I switch to using ethernet, there is no crackle or static.  The music is clear as a bell.

My setup is Snapserver being fed by MPD  both running on Ubuntu 16.04 LTS.  Snapclient running on Raspberry Pi 3 Model B+ with the latest (as of last week) version of Raspian Stretch Lite.  I am using the onboard DAC included with the Pi.  My WiFi router is the venerable WRT54GL running in 802.11g mode.  There is no skipping or dropouts so I don't think WiFi speed/throughput is the issue.  Also, my WiFi network is good enough to play music through a Chromecast Audio and play video through a Roku without any problems.  So, again I really don't think this is a WiFi network issue.

**Comment by Silver-Centurion** [comment]
I should have tested with multiple sets of speakers before I opened an issue.  The crackle goes away when I switch to different speakers.  It seems the issue is with the interaction of the WiFi radio signal and the speakers.  Although the problem speakers work just fine with a Chromecast Audio over WiFi, so perhaps the Raspberry Pi itself is also a contributing factor.

I think it is safe to say this is not a Snapclient issue.

**Comment by swiders2** [comment]
This is a known issue (also drive me insane with 10 Rpi's around the house.  https://dbader.org/blog/crackle-free-audio-on-the-raspberry-pi-with-mpd-and-pulseaudio

**Comment by Silver-Centurion** [comment]
@swiders2  Thanks for the info.  I will check that out.
