### ISSUE TITLE
Enable support for Android TV

### ISSUE THREAD

**Issue by voltagex** [badaix/snapcast#392]
![image](https://user-images.githubusercontent.com/159567/39392909-cdeaf7f0-4b01-11e8-846b-1963b38f0551.png)

Could you please enable Android TV support in the Store version of the app? I'll probably recompile it for my TV but it'd be nice to be able to just install it.

**Comment by badaix** [comment]
please move this issue to [snapdroid](https://github.com/badaix/snapdroid/issues)

**Comment by badaix** [comment]
This issue was moved to badaix/snapdroid#3
