### ISSUE TITLE
Dependeny of snapclient.service on avahi-daemon.service should be optional

### ISSUE THREAD

**Issue by MagicMuscleMan** [badaix/snapcast#393]
The Avahi build dependency is optional since [#378](https://github.com/badaix/snapcast/pull/378). However, the service file contains a hard dependency since [#348](https://github.com/badaix/snapcast/pull/348), although snapcast works perfectly fine without Avahi.

Thus, in snapclient.service, the
`Requires=avahi-daemon.service`
should be changed into
`Wants=avahi-daemon.service`
to get an optional dependency so that snapclient does not fail to start if Avahi is not installed.

**Comment by badaix** [comment]
thanks! It's changed in develop branch 2be2b4b and will be fixed in the next release

**Comment by PureTryOut** [comment]
The last release was made after that commit, so I suppose this issue can be closed can it not?

**Comment by MagicMuscleMan** [comment]
Thanks for the hint. Yes, I can confirm after testing: issue solved.
