### ISSUE TITLE
snapclient fails if started before usb sound card

### ISSUE THREAD

**Issue by eprst** [badaix/snapcast#396]
snapclient fails to start correctly for me from init.d script, I'm getting no audio.
I suspect that's because my system uses a USB dac which doesn't get fully initialized at the right moment. Restarting service manually makes it work. Snapclient is configured to use default audio card, which is selected system-wide using `/etc/asound.conf`

this is what syslog looks like
```
May  9 23:33:48 pi3 snapclient[647]: Exception in Controller::worker(): Can't open default PCM device: No such file or directory
May  9 23:33:49 pi3 snapclient[647]: Connected to 192.168.1.155
May  9 23:33:49 pi3 kernel: [  298.213012] usb 1-1.1.3: new full-speed USB device number 7 using dwc_otg
May  9 23:33:49 pi3 kernel: [  298.359983] usb 1-1.1.3: New USB device found, idVendor=08bb, idProduct=2704
May  9 23:33:49 pi3 kernel: [  298.359998] usb 1-1.1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=0
May  9 23:33:49 pi3 kernel: [  298.360006] usb 1-1.1.3: Product: USB Audio DAC
May  9 23:33:49 pi3 kernel: [  298.360014] usb 1-1.1.3: Manufacturer: Burr-Brown from TI
May  9 23:33:49 pi3 kernel: [  298.380291] input: Burr-Brown from TI               USB Audio DAC    as /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.1/1-1.1.3/1-1.1.3:1.2/0003:08BB:2704.0003/input/input2
May  9 23:33:50 pi3 kernel: [  298.443484] hid-generic 0003:08BB:2704.0003: input,hidraw0: USB HID v1.00 Device [Burr-Brown from TI               USB Audio DAC   ] on usb-3f980000.usb-1.1.3/input2
May  9 23:33:50 pi3 mtp-probe: checking bus 1, device 7: "/sys/devices/platform/soc/3f980000.usb/usb1/1-1/1-1.1/1-1.1.3"
May  9 23:33:50 pi3 mtp-probe: bus: 1, device: 7 was not an MTP device
May  9 23:33:50 pi3 systemd-udevd[668]: Process '/usr/sbin/th-cmd --socket /var/run/thd.socket --passfd --udev' failed with exit code 1.
May  9 23:33:51 pi3 snapclient[647]: Exception in Controller::worker(): Can't open default PCM device: Permission denied
May  9 23:33:52 pi3 snapclient[647]: Connected to 192.168.1.155
```

I'm not sure why it gets `Permission denied`, it is started as `snapclient:audio` and should have `rw` rights on `/dev/pcm/*`. A race for exclusive device access with something else?

any hints?

**Comment by praul** [comment]
As a workaround you could put

> @reboot sleep 5s; service snapclient restart
in your root's crontab.

I myself disabled the service and use this script running in a tmux terminal, since default soundcard changes at every reboot on my system

`sleep 10
soundkarte=$(snapclient -l | grep  default:CARD=Device | head -c 2)
until /usr/bin/snapclient -h 192.168.2.200 -p 1704 -s $soundkarte; do
    echo "snapclient crashed with exit code $?.  Respawning.." >&2
    sleep 1
done
`
and start it via users crontab
`@reboot` tmux new-session -d -s "snapclient"  sh PATHTOSCRIPT

**Comment by vKnmnn** [comment]
Assuming you use systemd you could add the following to the snapclient.service file (find -type f -name "snapclient.service"). This makes the service
```
[Service]
ExecStartPre=/bin/sleep 30
```

Or you could create a udev rule that mentions that it "wants" a certain service when it's device is detected, as described [here](https://stackoverflow.com/questions/18463755/linux-start-daemon-on-connected-usb-serial-dongle)
