### ISSUE TITLE
Help needed - How to crosscompile?

### ISSUE THREAD

**Issue by praul** [badaix/snapcast#397]
Hi, I'm somehow a beginner to crosscompiling and I'm wondering how to crosscompile snapcast (mainly for aarch64). There is no configure script to adjust the makefile. When trying to crosscompile, libraries cannot be found.

I installed the dependencies for arm64, and I'm trying to compile using dockcross (https://github.com/dockcross/dockcross) but I don't know how to pass compiler and lib-paths for arm64 without ./configure.

The wiki-article about crosscompiling with buildroot seems outdated, and the link to defconfig file is broken (https://github.com/badaix/snapcast/blob/master/buildroot/configs/snapcast_defconfig)

Any advice and/or easy instructions? 
Thank you so much

**Comment by badaix** [comment]
Sorry, seems that no one can help
