### ISSUE TITLE
Is the delay return by snd_pcm_delay credible?

### ISSUE THREAD

**Issue by lszhou0126** [badaix/snapcast#399]
In order to synchronize, the pcm delay is calculated by snd_pcm_delay(handle_, &framesDelay). But sometimes I found the value has a sudden change, e.g., from 170 to 320, which cause out-sync. I want to know whether the value return by snd_pcm_delay() is credible. Thanks.

**Comment by badaix** [comment]
Well, according to the alsa documentation, this is exactly the what want:

https://www.alsa-project.org/alsa-doc/alsa-lib/group___p_c_m.html#ga012e8b999070e72ab23514f25e7d6482

> For playback the delay is defined as the time that a frame that is written to the PCM stream shortly after this call will take to be actually audible. It is as such the overall latency from the write call to the final DAC.

I think this value will be more or less reliable for different DACs and drivers. Usually, if you just want to playback some audio, you must not care about this, but simply feed your DAC with audio and it will block when the buffer is full. If you want to have two sources synchronized, then the reliability of this value is crucial.
