### ISSUE TITLE
Snapclient breaks up after ~30 minutes when using alsa plugins

### ISSUE THREAD

**Issue by pfink** [badaix/snapcast#40]
On the following setup, I'm experiencing short but continuous dropouts (ca. 1 sec every 5 - 25 seconds):

Two armhf devices, one with snapclient + snapserver 0.4.1 + Mopidy 2.0.0 (configured like suggested in README.md) installed, the other with just snapclient. Reproducing is possible, but sometimes it works some minutes fine until the problem begins.

The dropouts are mostly occuring on just one of the two devices (so one device has continous dropouts, other works fine). It's not clear to me why, but the problem mostly occurs on the system where snapclient connects to localhost. Sometimes, localhost works fine, but then remote host has the dropouts. Less often, both devices have these dropouts. Often, the problem also occurs if I just run server + client standalone on the same device without any additional client.

I already tried some things out including:
- increasing buffers
- changing codecs

On mopidy / gstreamer side I tried:
`output = audioresample ! audioconvert ! audio/x-raw,rate=44100,channels=2,format=S16LE ! wavenc ! filesink location=/tmp/snapfifo`
and
`output = audioresample ! audioconvert ! wavenc ! filesink location=/tmp/snapfifo`

everything without success.

I could reproduce the problem on the following system combinations:
- RPI3 OSMC server + UDOObuntu client
- RPI3 OSMC server + RPI2 OSMC client
- RPI3 Raspbian Jessie server + UDOObuntu client

Tomorrow I'll test RPI3 Raspbian Jessie server + RPI2 Raspbian Jessie client with v0.5.0-beta-2. Any advices what could be wrong? Maybe permormance of these devices is just to low? Average Load on server is up to ~0.7...

This is a typically log output of snapclient from the device with dropouts:

[v0.4 client dropouts.txt](https://github.com/badaix/snapcast/files/186951/v0.4.client.dropouts.txt)

**Comment by pfink** [comment]
Spending some further hours with testing, I found out that the problem occurs only on devices on which I don't lead sound directly to the soundcard, but through some alsa plugins instead (equalizer, loopback audio for visualizations etc.).

Also, I tested it with v0.5.0-beta-2 now, where the problem does not occur, although I have other problems there (it's harder to reproduce them, I'll do some further investigation on it and check if they're also related to my alsa configuration within the next week).

**Comment by badaix** [comment]
Are you sure that with the sample rates is everything ok? There shouldn't be any difference between v0.4 and v0.5, except that the default sampleformat in v0.5 is 48000:16:2 compared to 44100:16:2.
Can you try to run the v0.4 at 48kHz samplerate?

**Comment by badaix** [comment]
Anything special on server side? Can you see those "onResync" events on stdout?

**Comment by pfink** [comment]
I tested with the default sample rate respectively, so 44,1kHz on 0.4 and 48kHz on 0.5 (of course I changed mopidy config accordingly). With 0.4, I have the dropouts mentioned above (just the client with my alsa configuration in place, nothing special on server side). With 0.5, I don't have the (client-only) dropouts, but I have more frequently some onResync events on server side, which has impact on all clients (but not as frequent as the dropouts). Typical log server log with 0.5:

[v0.5 server log.txt](https://github.com/badaix/snapcast/files/186915/v0.5.server.log.txt)

But looking at my recent tests - unlike the client-only dropouts on 0.4) I think the frequent onResync's in 0.5 are not related to the alsa configuration. Additonally, there is a second problem on 0.5 after a longer time of continuous playing (~30 minutes): One client completely breaks up which looks like this:

[v0.5 client log after 30 minutes.txt](https://github.com/badaix/snapcast/files/186917/v0.5.client.log.after.30.minutes.txt)

I think this problem only occurs on devices on which I have my alsa configuration in place (so maybe it's the same cause like in 0.4 just showing other symptoms)

This is the alsa configuration I'm talking about:

[asound.txt](https://github.com/badaix/snapcast/files/184879/asound.txt)

Kernel module snd-aloop has to be activated and libasound2-plugin-equal installed. If you like I could also provide complete images for reproducing or my [ansible ](http://ansible.com) scripts which I use to provision the configuration to my RPI.

Tomorrow I'll have some time to test 0.4 with 48kHz.

**Comment by pfink** [comment]
Running 0.4 with 48kHz shows exactly the same symptoms as running it with default samplerate.

**Comment by pfink** [comment]
Doing some further testing, I can confirm that the problem with 0.5 only occurs if I use alsa plugins. So I think it's the same issue as in 0.4 just showing other symptoms. I changed the title accordingly, as 0.5 is now the current stable version.

**Comment by badaix** [comment]
Closing old, non reproducible issue. Please reopen if the problem still exists.

**Comment by pfink** [comment]
Problem still exists, tested it today. Did you try to reproduce with the alsa configuration in place?
