### ISSUE TITLE
Add stream while running

### ISSUE THREAD

**Issue by ehud-swiftstack** [badaix/snapcast#401]
is there an option to add a stream after SnapServer already started?
I am looking for a way to add a new Mopidy stream dynamically. One option is to add it to the conf file and restart SnapServer, but that means anyone listening currently will experience the stop.

a better way would be to have a command to add a new stream to a live SnapServer, or maybe to set to watch a directory and automatically add any new file added there as stream.

is there such an option? or a better one?

**Comment by badaix** [comment]
this should be possible with the `Stream.AddStream` command
```
// Request:      {"id":4,"jsonrpc":"2.0","method":"Stream.AddStream","params":{"streamUri":"uri"}}
// Response:     {"id":4,"jsonrpc":"2.0","result":{"stream_id":"Spotify"}}
```
