### ISSUE TITLE
[Feature Request] Auto stream select

### ISSUE THREAD

**Issue by Daargajedan** [badaix/snapcast#402]
Can we make snap server more intelligent, what i mean is that snap server could automatically manage incoming streams. For example i have Mopidy and Airplay. Mopidy is always playing and if i want to airplay something from my macbook i need to set this on my mac (Audio -> to Airplay) and in snapcast i need to change the stream. 

It would be ideal if i can give a order number to the streams, and let snap cast decide which stream must be used. When both or multiple stream have audio input. 

An other example:

Music is playing on my Raspberrypi and i'm sitting in front of my mac. Now I wanna AirPlay something to the same player. Now I need to go to snapcast to set it to AirPlay.(other stream). It would be Nice if snapcast recognize the other stream is playing so it sets it to that stream. If that stream is done Its going back to Mopidy.

**Comment by tgurr** [comment]
I'd appreciate a feature like this as well. My use case is also streaming via Mopidy to ceiling speakers, but also having a stream for the doorbell which would be nice if snapcast would be able to automatically switch to as soon as it plays something and have it as some kind of stream with the highest priority.

**Comment by benedikt-bartscher** [comment]
I would love this feature for TTS of my Snips installation!

**Comment by vKnmnn** [comment]
in the meantime you can solve this by playing all sounds to a single pulseaudio server and have the pulseaudio server output all streams at once to snapcast. of course then you have to make sure only one source is playing audio.
I've done this for my snips installation. the cork-module should help with snips in particular.

**Comment by badaix** [comment]
I would not change any logic in the audio routing or stream readers. What you need is some kind of meta streamreader, taking the input of other streams (in some fallback hierarchy manner: when the first one player, use this signal, else if the second is playing, take this, ...).
Would be nice to have. Patches are welcome :)

**Comment by d-xtich** [comment]
I wrote a little service in Python wich connecting to Snapcast's JSON-RPC API and switching to the new playing stream on Stream.OnUpdate. 
@Daargajedan @tgurr @benedikt-bartscher Your welcome to use it.
[https://github.com/d-xtich/snapcast_stream_switch](https://github.com/d-xtich/snapcast_stream_switch)

**Comment by Howaner** [comment]
> I wrote a little service in Python wich connecting to Snapcast's JSON-RPC API and switching to the new playing stream on Stream.OnUpdate.
> @Daargajedan @tgurr @benedikt-bartscher Your welcome to use it.
> https://github.com/d-xtich/snapcast_stream_switch

Works wonderful! Thank you :+1:

**Comment by badaix** [comment]
Meta streams will be part of v0.22 => see #666
