### ISSUE TITLE
Debian Failed to start Snapcast server

### ISSUE THREAD

**Issue by gerroon** [badaix/snapcast#403]
Hi

I just upgraded Snapserver using the Debian repo on Debian Testing, then  Snapserver started failing :(  It was wokring until this update.

 systemctl status snapserver.service
● snapserver.service - Snapcast server
   Loaded: loaded (/lib/systemd/system/snapserver.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2018-07-08 21:13:52 CDT; 44s ago
     Docs: man:snapserver(1)
  Process: 7034 ExecStart=/usr/bin/snapserver $SNAPSERVER_OPTS (code=exited, status=1/FAILURE)
 Main PID: 7034 (code=exited, status=1/FAILURE)

Jul 08 21:13:52 XXX systemd[1]: snapserver.service: Failed with result 'exit-code'.
Jul 08 21:13:52 XXX systemd[1]: snapserver.service: Service RestartSec=100ms expired, scheduling restart.
Jul 08 21:13:52 XXX systemd[1]: snapserver.service: Scheduled restart job, restart counter is at 5.
Jul 08 21:13:52 XXX systemd[1]: Stopped Snapcast server.
Jul 08 21:13:52 XXX systemd[1]: snapserver.service: Start request repeated too quickly.
Jul 08 21:13:52 XXX systemd[1]: snapserver.service: Failed with result 'exit-code'.
Jul 08 21:13:52 XXX systemd[1]: Failed to start Snapcast server.

**Comment by badaix** [comment]
You are using this debian package: [snapcast (0.14.0-1)](https://packages.debian.org/source/buster/snapcast)?

**Comment by gerroon** [comment]
Yeah it looks like it updated both the server and the client to that one.

**Comment by badaix** [comment]
Seems that the debian systemd file didn't change.
What about uninstall/install? (not a good solution, but maybe it helps)

**Comment by gerroon** [comment]
Weird :( I will look into this.

**Comment by gerroon** [comment]
Ok, this is weird. I removed both the client and the server and built them from the github and they are installed perfectrly and both of their systemd scripts seems to work flawless.
