### ISSUE TITLE
Always statically links against libstdc++

### ISSUE THREAD

**Issue by debfx** [badaix/snapcast#404]
The Makefiles always add `-static-libgcc -static-libstdc++` to LDFLAGS.
Is there a particular reason why statically linking them is necessary?

At least on general purpose Linux distros it shouldn't be necessary and is considered bad practice (increases binary size, doesn't benefit from updates after building).

It would be great to at least have an option to disable static linking.

**Comment by badaix** [comment]
I don't really remember, I guess this was neccessary for OpenWRT builds.
It's removed now in 6b5307b
