### ISSUE TITLE
Feature request: Authentication and transport encryption

### ISSUE THREAD

**Issue by fuesschen** [badaix/snapcast#408]
Snapcast is realy nice at the moment but if you use it in a network which is not only used by you alone it would be nice to be able to encrypt the audiostream and the control traffic via TLS and set the snapserver to enforce snapclients to authenticate against the snapserver.

**Comment by vKnmnn** [comment]
if you're on a network that doesn't belong to you ( you're not alone there)  you probably shouldn't be streaming audio to a few clients simultaneously. I understand the need to encrypt music, but it's just music in most cases. do you really need to encrypt that? i know that's not a good argument, but still.
it might be easier to have access control in snapserver to only allow a few clients to connect to the control api, that at least makes it more difficult to attack you by changing the volume of your streams.

**Comment by badaix** [comment]
Snapcast is intended to be used in a LAN. TLS is not planned before v2.0. Patches are welcome.
