### ISSUE TITLE
S24_3LE format not supported?

### ISSUE THREAD

**Issue by rdamen** [badaix/snapcast#409]
Hi,

I'm trying to setup a Raspberry Pi connected to an USB DAC as a Snapclient but I'm getting this error:
Exception in Controller::worker(): Can't set format: Invalid argument, supported: S24_3LE

Even though in the Snapserver I have:
SNAPSERVER_OPTS="-d -s pipe:///tmp/snapfifo?name=MPD&sampleformat=192000:24_3:2"

I have also tried with the same result:
SNAPSERVER_OPTS="-d -s pipe:///tmp/snapfifo?name=MPD --sampleformat=192000:24_3:2"

Am I doing something wrong or could this be a bug?

Great project, hope I can get it working.

Thanks,
Ron

**Comment by badaix** [comment]
No guarantee that 192kHz will work at all, but the source code says:
```c++
void SampleFormat::setFormat(uint32_t rate, uint16_t bits, uint16_t channels)
{
	//needs something like:
	// 24_4 = 3 bytes, padded to 4
	// 32 = 4 bytes
	this->rate = rate;
	this->bits = bits;
	this->channels = channels;
	sampleSize = bits / 8;
	if (bits == 24)
		sampleSize = 4;
	frameSize = channels*sampleSize;
//	LOG(DEBUG) << "SampleFormat: " << rate << ":" << bits << ":" << channels << "\n";
}
```
so currently only integer values are supported for the sample size (i.e. 8, 16, 24, 32) and that 24 are supposed to be padded to 4 bytes (24_4). This means that 24_3 is not supported. I would call the missing documentation and error message a bug, and the support for 24_3 a missing feature.

**Comment by rdamen** [comment]
Thanks for the quick response. I probably should've set the samplerate to the default in the example.
It's too bad 24_3 is not supported as the only format accepted by the device.
I suppose it's not going to be as easy as to change the sampleSize to 3 in the SampleFormat::setFormat function you pasted for it to work? Or is it?

**Comment by rdamen** [comment]
Sorry if this is obvious I'm not an expert. I think I actually just made a configuration error.
Before I had MPD write 24_3 to the FIFO, I now changed it to 24 and it just works.
I think because of ALSA software conversion.
Maybe it would be preferable to have Snapcast support 24_3 directly but I'm already happy right now.
