### ISSUE TITLE
Not documented dependencies for building snapcast

### ISSUE THREAD

**Issue by pfink** [badaix/snapcast#41]
The `libasio-dev` package and [badaix/popl](/badaix/popl) are required for building against current master but are not mentioned within the README. I think it would be a good idea to add them.

**Comment by pille** [comment]
yeah, the README in the develop branch already contains it: https://github.com/badaix/snapcast/commit/69a12a7f77ca0cc68d8d419490384de39075a197.

**Comment by pfink** [comment]
You're right!
