### ISSUE TITLE
Seg Fault when running make

### ISSUE THREAD

**Issue by fallenicarus** [badaix/snapcast#413]
Kinda weird issue here -but I had a fresh install of raspibian and was installing snapcast. I have done this before on previous attempts but when I enter make - I get segmentation fault. Even sudo make installclient or installserver do the same thing. What am I doing wrong here... its obvious its something basic - but i cant figure out what..

**Comment by rage2dev** [comment]
Without logs hard to tell. Why not using the release for armhf? They are working fine.
