### ISSUE TITLE
Mac OS Config file locations

### ISSUE THREAD

**Issue by yajrendrag** [badaix/snapcast#414]
Installed on mac and server and client up and running.  But i don't see a config file - ie, no /etc/default/snapserver or /etc/default/snapclient.   there is no /etc/default directory in macos... /private/etc has a defaults directory but not there either.  /var/lib/snapserver/server.json exists.   no snap related files in ~/.config either.

running a find at / but it's not returned anything yet.

thanks for any help.

**Comment by yajrendrag** [comment]
maybe macos doesn't use a default config file?  possibly you just edit the launchd plist file?  either that or the /tmp/snapfifo pipe is configured automatically and no configuration is required for that

**Comment by Johnr24** [comment]
I'd like to reopen this with the suggestion to add this to the documentation?
