### ISSUE TITLE
Snapclient select alsa custom mix

### ISSUE THREAD

**Issue by benedikt-bartscher** [badaix/snapcast#421]
My asound.conf look similar to this one:
https://gitlab.com/CaptnsTech/aec-alsa/blob/master/MicArray_NC_Music.md
So now i can play Audio via aplay or mpv to tts_playback or music_playback like this:
aplay -D plug:music_playback test.wav
But how do i select "music_playback" or "tts_playback" as audio device for snapclient? snapclient -l gives me a very long list of my audio devices, not including tts_playback or audio_playback...
I have already tried something like this: "snapclient --soundcard jack:music_playback" or this: "snapclient --soundcard plug:music_playback" but it does not work.

**Comment by badaix** [comment]
snapclient can only use devices that are in the list. You can choose a certain device with "-s <index>"
