### ISSUE TITLE
Alsa equalizer with raspotify and snapcast

### ISSUE THREAD

**Issue by mrpete69** [badaix/snapcast#424]
Hi! I haven't found an answer when googling this question and I find alsa really tricky. I have a snapserver and two clients, based on Raspberry pi with soundcards. How can we enable alsa equalizer on each client? It works when streaming through raspotify on a single device, but when I try to add alsaeq through snapclient, I'm stuck. Trying 'sudo alsamixer -u snapclient alsamixer -D equal' responds 'Failed to open controls file /home/snapclient/alsaequal.bin. cannot open mixer: Operation not permitted'. I've tried some other users including sudo but nothing happens (as expected). Creating the folder makes it possible to open the equalizer as snapclient but the sound is unchanged. Is it not possible to use alsa equalizer with snapcast or what am I doing wrong?

**Comment by mrpete69** [comment]
Well, I figured it out. So here’s what to do to get alsa equalizer to your snapclient:
Install alsaequal 
https://www.hifiberry.com/build/documentation/guide-adding-equalization-using-alsaeq/
Create a directory `sudo mkdir /var/lib/snapclient`
Make snapclient the owner of the directory `sudo chown snapclient:audio /var/lib/snapclient`
Find out which soundcard is eqaul in `snapclient -l`
Change soundcard in configuratioon`sudo nano /etc/default/snapclient` 
In last line change it to `SNAPCLIENT_OPTS="-s 1"` if equal is 1 in your soundcard list
Start alsaequal as snapclient `sudo -u snapclient alsamixer -D equal`
And there you go, adjust it the way your client needs to get better sound.

**Comment by PaulFH** [comment]
Thank you, mrpete69!!

I've been spending all weekend and your answer makes it all work wonderfully!!!

Opened a case with wifiberry, but i closed it with a link to your answer if you don't mind
