### ISSUE TITLE
Raspotify multiroom

### ISSUE THREAD

**Issue by Hydro8** [badaix/snapcast#425]
Hi
I don't know if it's possible with snapcast but I want to achieve this kind of setup :
- multiroom audio
- each player can play Spotify separately
- multi groups of player.

I can set the multi room with Android app. I have two times my player under Spotify. One for raspotify and the second for snapcast. Is it normal ?

Is it possible to have multi group ? For example : my wife listen on kitchen and living room and me I listen on garage + bedroom.

Thank for your help.

**Comment by Hydro8** [comment]
If I understand well, we can't have multi groups for the same stream right ?

And it's not possible for a client to easily change snapcast server ?

**Comment by axelsimon** [comment]
> And it's not possible for a client to easily change snapcast server ?
No, not at this point. You have to manually change server in the Android app or restart `snapclient` and tell it to connect to a different server (if anything has changed, please correct me).

**Comment by herrwusel** [comment]
You can define multiple sources for your snapserver. If you want 3 spotify sources, I would copy the librespot binary 3x and define them as source. Something like this:
```bash
SNAPSERVER_OPTS="-d  -s spotify:///librespot1?name=Spotify1&devicename=Snapcast -s spotify:///librespot2?name=Spotify1&devicename=Snapcast ... -s spotify:///librespotn?name=Spotify1&devicename=Snapcast"
```
I don't know if it's working but you can try ;)

**Comment by Hydro8** [comment]
At this moment I didn't have time to try but I wil with the holiday. I'll report my progress.

**Comment by Hydro8** [comment]
Do you know how to easy launch multiple librespot X3 ?

**Comment by Hydro8** [comment]
It seems to work (need more test) without copying anything.

Do you know how to set up and manage different group in snapcast ??

**Comment by unimatrix27** [comment]
I did a similar setup using pulseaudio as a layer before snapcast. I am playing with native librespot to pulseaudio and snapcast is streaming the pulseaudio FIFOs to the snapclients. 

This way you can also define combined sinks in pulseaudio as additional sources, e.g. one source being "garage + living room" and then as a snapclient just listen to this predefined combined source.

**Comment by adnion** [comment]
@unimatrix27: Could you please add some information about your setup? What tasks does it solve and how is it controlled by end users?
- multiroom audio
- each player can play Spotify separately
- multi groups of player

**Comment by unimatrix27** [comment]
My setup uses a central linux server which I use for many other services anyway.

Multi-User Spotify of course requires several Spotify Accounts ( i have a family account)

I am running a librespot instance per user.

WIth Pulseaudio  module-pipe-sink I create a sink for each librespot instance, and then I configure each librespot instance to play to its according pulseaudio sink

I am also creating combined sinks in pulseaudio with the module-combine-sink in which I then put for example both children and call it "children" sink

I am serving all those streams with snapserver using the .fifo file.

like this:
`/usr/bin/snapserver -s pipe:///tmp/child1.fifo?name=child1 -s pipe:///tmp/child2.fifo?name=child2 -s pipe:///tmp/livingroom.fifo?name=livingroom -s pipe:///tmp/kitchen.fifo?name=kitchen` -s pipe:///tmp/children.fifo?name=children`

The clients are using the snapcast app on their phones and spotify on their phones where they can chose their librespot instance as playing device.

**Comment by mrpete69** [comment]
Seems like a nice solution. I have a family account too, and a few RPi’s as clients, but only one stream thruog pipe. Could you please tell us how you install and run several instances of Raspotify (or other librespot) on the snapserver?
