### ISSUE TITLE
Can't configure multiple streams in terminal

### ISSUE THREAD

**Issue by vjdw** [badaix/snapcast#434]
If I specify multiple streams with the following options in `/etc/default/snapserver` then things work as expected.

`SNAPSERVER_OPTS="-s pipe:///tmp/librespotfifo?name=spotify&sampleformat=44100:16:2 -s pipe:///tmp/mopidy?name=mopidy&mode=read"`

However, if I start snapserver in the terminal with multiple `-s` arguments then only whichever stream is given first will be used, and the other stream is not visible (e.g. in snapcast android app). So in the following example, only the spotify stream would be available.

`snapserver -s pipe:///tmp/librespotfifo?name=spotify&sampleformat=44100:16:2 -s pipe:///tmp/mopidy?name=mopidy&mode=read`

I am using snapserver v0.15.0 and Ubuntu Linux 4.15.0-42-generic x86_64

**Comment by m9racz** [comment]
try this:
`snapserver -s "pipe:///tmp/librespotfifo?name=spotify&sampleformat=44100:16:2" -s "pipe:///tmp/mopidy?name=mopidy&mode=read"`
