### ISSUE TITLE
RFC: Threads in snapcast

### ISSUE THREAD

**Issue by christf** [badaix/snapcast#438]
snapcast uses many different threads. This is helpful when each core is barely fast enough to encode one stream and multiple streams are to be encoded.

On my i3 encoding to ogg utilizes roughly 2.5% of a cpu core. This means 40 concurrent streams can be handled by a single core. My raspberry Pi A+ encodes ogg much faster than playing speed. Fully utilizing its only core it can encode 3 ogg-streams concurrently.

At the same time, using many threads complicates the code base and debugging.

In the client a tcp stream, filling the buffer and time synchronization have to be handled. All of this can be done asynchronously inside a single thread.

I do not think many threads are actually needed even for unusual use cases like sustaining 40 concurrent streams. Changing the threading model could be of benefit for maintaining snapcast.

What do you think? Should the threading model be adjusted?

**Comment by badaix** [comment]
I started adjusting it in the current develop branch. The control connections are sharing a single thread from the asio io context thread pool. I will make this stable (currently hunting a hard to reproduce segfault) and release it. Afterwards I will attack the streaming threads.
The good thing about asio is that it is using a thread pool, so the number of threads can be easily adjusted.
