### ISSUE TITLE
Heavy distortion on stream when playing certain files

### ISSUE THREAD

**Issue by axelsimon** [badaix/snapcast#440]
Hi,
I was playing some music from a Raspberry Pi 2 with Kodi (Libreelec) + Snapcast (installed with the Libreelec addon) and configured to stream ogg vorbis. (To be exact, the music is played from an NFS mount from a third computer, now that I think of it).

Some of the music comes out heavily distorted on the laptop getting the stream via snapclient.

It's more noticeable with certain songs than others, the heavier the music in itself, the more the distortion is noticeable. I'm not sure either, I need to test more but it seems like it's more noticeable when Kodi is playing from FLAC files.

I know this is a bit of a quirky setup, but I thought I would share anyway.
Has anyone else had this issue?

**Comment by thecb1** [comment]
To recap, snapserver is running on an RPi streaming the output from Kodi?

I don't have much experience with snapserver on RPi but I remember having noticeable distortions and crackling depending on the used resampler with MPD as source. Soxr gave me the best results with flac, but it is utilizing around 2.3% CPU on a first gen intel i3. I don't know about resampler implementations for the RPi and how well they work.

Is Kodi even doing resampling? :-)
