### ISSUE TITLE
dropouts/distorted sound when using a small alsa buffer size

### ISSUE THREAD

**Issue by stanelie** [badaix/snapcast#442]
On a system running several audio apps, I've adjusted the alsa buffer size in /etc/asound.conf to `period_size 64` in order to get low latency with another software. However, when Snapclient uses this same audio device (alone or while the other app also uses it), I get distorted/chopped up sound and a lot of text scrolling in the console, including many XRUN and such adjustments.

I suspect a wrong buffer size requested by snapclient, mismatching the one provided by alsa. Is there a switch to specify a matching buffer size in snapclient? Shouldn't snapclient adjust automatically to the alsa provided buffer size?

**Comment by christf** [comment]
have you tried lowering the readms value?

**Comment by stanelie** [comment]
Is this a command line option for snapclient?

Btw, where can I find documentation about de various command line options?

**Comment by christf** [comment]
it is an option for the server.
