### ISSUE TITLE
Snapclient not working at fresh Open-WRT (TP-Link Archer C7 v2)

### ISSUE THREAD

**Issue by potter-91** [badaix/snapcast#444]
Hi
I have a problem to install snapclient at Archer C7.

Yesterday Evening it worked, powered the router off, whis morning back on and it didn't work anymore.
Here my Terminal outbut when i try to start snapclient:

BusyBox v1.28.3 () built-in shell (ash)

  _______                     ________        __
 |       |.-----.-----.-----.|  |  |  |.----.|  |_
 |   -   ||  _  |  -__|     ||  |  |  ||   _||   _|
 |_______||   __|_____|__|__||________||__|  |____|
          |__| W I R E L E S S   F R E E D O M
 -----------------------------------------------------
 OpenWrt 18.06.1, r7258-5eb055306f
 -----------------------------------------------------
=== WARNING! =====================================
There is no root password defined on this device!
Use the "passwd" command to set up a new password
in order to prevent unauthorized SSH logins.
--------------------------------------------------
root@OpenWrt:~# snapclient
2019-01-27 12-59-22 [Info] (Browser) CACHE_EXHAUSTED
2019-01-27 12-59-23 [Info] (Browser) ALL_FOR_NOW
2019-01-27 12-59-27 [Info] (Browser) CACHE_EXHAUSTED
2019-01-27 12-59-27 [Info] (Browser) ALL_FOR_NOW

MPD works without any problem...

Greetings

**Comment by xabolcs** [comment]
Point your snapclient to your server manually, if it doesn't find the server by itself!

Check `/etc/default/snapclient` for more!
