### ISSUE TITLE
Different sources.. No issue, more of end-user support really.

### ISSUE THREAD

**Issue by micgus** [badaix/snapcast#447]
Hello fellow Snapcastians.
I'd like to set the scene a bit by explaining that i am a total noob that probably have lots of basic misunderstandings, resulting in me not being able to solve my issues. 
So I'm reaching out to you pros out there.

**What i want to achieve:** 
- Multi Room Audio from either Spotify Connect or AirPlay sources.

**Failed attempts:**
- Super Simple Raspberry Pi Audio Receiver. (Not getting this to work at all pretty much)
- Misc manual installations of Librespot, Shairport-sync & snapcast.

**What I've done so far that is almost working:**
- Raspbian Jessie LITE.
- Installed Shairport-Sync. 
- Installed Raspotify.
- Installed Snapcast server & client.

My shairport-sync is configured to: _output_backend = "pipe"_ 
(The only way i could get snapserver to start streaming any audio.)

The main issue for me is that i cannot get both Shairport & Librespot working at the same time, its either or.
The current SNAPSERVER_OPTS i've been trying are:
_'-s "airplay:///usr/local/bin/shairport-sync?name=Airplay&devicename=AName&port=5000]" -d -s "spotify:///librespot?name=Spotify&username=USER&password=PASSWORD&devicename=AName&bitrate=320"'_

Each option works on its own, but i cannot get both running at the same time.
I also tried to configure Shairport & Libresport to pipe and then configure multiple pipes in snapserver but all i get is "cache exhausted" and nothing else on the snapclient.

Sorry for my noobster questions, just need some1 to point me in the right direction here.

Much appreciated.

**Comment by r0k** [comment]
Migus,

This is what I collected from various sources and posts, No colons inside the server string and (just to be safe) `mode=create` on the main fifo source so the two others can use it. 

```sh
SNAPSERVER_OPTS="-s pipe:///tmp/snapfifo?name=default&mode=create -s spotify:///librespot?name=spotify&username=USER&password=PASSWORD&devicename=Airplay&volume=100 -s spotify:///librespot?name=Spotify&...."
```
Once the server is starting you can also check its visible interface to the clients via the [snapdroid](https://github.com/badaix/snapdroid) tool from badaix.  It is also very handy to remote control the volume of your devices. 

Good Luck.

**Comment by micgus** [comment]
Thanx for the reply. No luck with that either. Did you actually try that configuration and got it to work? 
Anyone else that has a similar setup that wants to share their config perhaps?

Cheeers.

**Comment by vjdw** [comment]
This looks the same as my issue #434 
I didn't find a fix but instead direct both my sources to the same fifo and just make sure I don't have both playing at the same time!

**Comment by unimatrix27** [comment]
Pulseaudio with module-combine-sink is your friend

Vince <notifications@github.com> schrieb am Do., 21. März 2019, 14:52:

**Comment by micgus** [comment]
> This looks the same as my issue #434
> I didn't find a fix but instead direct both my sources to the same fifo and just make sure I don't have both playing at the same time!

That would do!
Could you maybe post more details on how the component configurations? 
Cheers.

**Comment by vjdw** [comment]
@micgus This is from the notes I've kept on how to configure Pulseaudio to send both mopidy and an ALSA line-in (for chromecast audio) to the snapcast sink. Hopefully some of it applies to what you're trying to do.

Create ~/.config/pulse/default.pa with contents:
```
.include /etc/pulse/default.pa

# snapcast sink used by both alsa loopback below, and mopidy.
load-module module-pipe-sink file=/tmp/snapfifo rate=48000 sink_name=snapcast

# Backplate line-in.
# !!! hw:0,2 might not be what you want, look up your source name with 'arecord -l'
load-module module-alsa-source device=hw:0,2 source_name=AlsaLineIn

# Hook-up backplate analog source to snapcast sink
load-module module-loopback sink=snapcast source=AlsaLineIn
```
Edit /etc/pulse/daemon.conf:
```
# Copy/paste and edit around line 77 to give:
default-sample-rate = 48000

# And optionally, change the default resampler for a higher quality one:
resample-method = src-sinc-best-quality
```
Restart Pulseaudio:
	`pulseaudio -k`

Using the pavucontrol GUI you can redirect any active audio app to any sink. It also remembers the last used sink after the app is closed and re-opened. So now this is what I'm doing with the Spotify desktop client. But alternatively, if you happen to be using mopidy then to point it to the snapcast sink edit ~/.config/mopidy/mopidy.conf to include:
```
[audio]
output=pulsesink device=snapcast
```

**Comment by micgus** [comment]
Awsome! I'll give it a go. Thnx!
