### ISSUE TITLE
actively developed fork

### ISSUE THREAD

**Issue by artmg** [badaix/snapcast#451]
Hi fellow snapcast fans,

@badaix has put a lot of effort into the snapcast ecosystem, but [since last summer his github development](https://github.com/badaix/snapcast/graphs/commit-activity) has been a little quiet. I wonder if perhaps a new job has engulfed him and left him with little spare time for community projects. 

Are any of you aware of any forks that are being more actively maintained, that users with issues might want to check out in the meantime? We stay in hope that he will be able to come back and incorporate PRs into the master here, but in the mean time is there anyone who has working builds that fix any issues reported in this list?

There has been recent [activity in a number of forks](https://github.com/badaix/snapcast/network), and @christf seems to be the most prolific with several active branches. However I cannot find any published builds and his focus seems to be [a revised implementation](https://github.com/christf/snapcastc) (could perhaps be interesting one day!). 

Does anyone else in the community know where users could go to look for bugfix updates whilst we wait for @badaix to come back (like he did [before](https://github.com/badaix/snapcast/issues/278))? Thanks

**Comment by badaix** [comment]
Hi,

challenge accepted :)
Actually I've been quite busy with other stuff for the last couple of month, but workload is going down now, so I will be able to spend more time to further maintain and develop Snapcast. Personally, I'm using snapcast everyday, and will be happy to merge the open PRs.

**Comment by christf** [comment]
@artmg While snapcastc does not provide builds yet it is very much usable already if you are wiling to build it. packaging is on the near-time todo list. It already provides some interesting features for audio playback as well. 
That being said, snapcast is more mature at this point and it does work well if your equipment - especially the server - is not otherwise loaded.

**Comment by artmg** [comment]
Many thanks to both developers for coming back with updates on their projects. I'm sure that speak for many happy users (some active too) when I say how much we appreciate the effort you have put in, and your continuing dedication to such useful and enjoyable projects. Well done!
