### ISSUE TITLE
Adapt examples to avoid hitting new systemd default for fs.protected_fifos

### ISSUE THREAD

**Issue by languitar** [badaix/snapcast#452]
Systemd 241 has opted to enable the kernel security feature `fs.protected_fifos` by default.  This feature is described as:
> Disallows open of FIFOs or regular files not owned by the user in world writable sticky directories, unless the owner is the same as that of the directory or the file is opened without the O_CREAT flag. The purpose is to make data spoofing attacks harder

On my machine this results in the fact that mopidy couldn't write anymore to `snapfifo` placed in `/tmp`, where this restriction hits. Maybe it would be a good idea to adapt the examples to avoid ending in this trap.

**Comment by nimonimonimo** [comment]
Done now, see: https://github.com/badaix/snapcast/pull/478
