### ISSUE TITLE
sound feeling from one direction of two loudspeaker

### ISSUE THREAD

**Issue by lszhou0126** [badaix/snapcast#455]
Hi. When I use two loudspeaker to play and sit in the middle, it sounds that the music just from one direction, maybe the left or the right. I am sure the volume set is the same and no much hardware difference. I wonder this is caused by the delay between these two loudspeaker, and a phenomenon called auditory masking. Is there any way to solve this issue, or just because I use the snapcast in a wrong way?

**Comment by vKnmnn** [comment]
did you test whether this only happens when playing sound via snapcast?

**Comment by badaix** [comment]
no response => assuming to be solved
