### ISSUE TITLE
Is the project going to die?

### ISSUE THREAD

**Issue by semaf** [badaix/snapcast#457]
Last update 10 month ago. Is the project going to die?

**Comment by IVData** [comment]
See #278 and #451

**Comment by axelsimon** [comment]
There are also 16 unmerged pull requests. Some of them going back to 2015.

@badaix This project is really great, could you update us regarding your current outlook on it?
Would you be willing to transfer it to someone else or a team if you don't have time or don't want to maintain it anymore?

**Comment by CodeCutterUK** [comment]
@axelsimon Given that @badaix public GitHub interactions have all but disappeared, we might be at the stage of considering forking to a org....that's assuming we have enough people interested in keeping this alive.

I personally get a good amount of value out of Snapcast, and would be interested in supporting an effort.

**Comment by palitu** [comment]
Yeah, I love it and would really love a user interface to be implemented.

**Comment by palitu** [comment]
Actually, what I really want is some cheap hardware that will come together
to run snapcast, or an image that you can bung into a rpi and had an easy
and flexible setup (GUI for WiFi, setup scripts for hardware) and an
improved API.

**Comment by CodeCutterUK** [comment]
Okay - I've grabbed the Snapcast GH org working on the assumption that it's likely we'll need to fork in order to take the project forward.
Equally I'm really keen to get @badaix involved so that it's a aligned move, but I guess in the 4 months this issue has been open we've not heard anything.

@palitu I can't see why a user interface, image or even dedicated hardware couldn't be created....assuming that's permitted within the license.

**Comment by palitu** [comment]
Cool, happy to jump in to assist, though I'm not a developer by trade. I
might try and get some rpi images created to make it easier to setup a node.

**Comment by palitu** [comment]
And what's the address you have?

**Comment by CodeCutterUK** [comment]
@palitu - I've grabbed [Snapcast](https://github.com/Snapcast)

Given it's been 10 days since this route was suggested, I think we should get on with it.....perhaps the community could give a simple 👍 or 👎 to help us gauge support

Equally if anybody is interested in helping to maintain things going forward, please post or contact me directly

**Comment by palitu** [comment]
well, seems like there are a few people interested in it :)

**Comment by TurtleForGaming** [comment]
Well there is a few on github only but if the project evolve I think that the diy home automation community would bé very happy especially if there's a very easy way to implement it

**Comment by palitu** [comment]
> Well there is a few on github only but if the project evolve I think that the diy home automation community would bé very happy especially if there's a very easy way to implement it

yeah, i use home-assistant integration for a webui, and the app.  but people still use the hardware volume, computer volume or spotify volume to change it, which is annoying.  I have just put together a little node, with an rpi zero, justboom amp zero and a couple of speakers, and it was straight forward, tohugh some stuffing around.

I would love to have a web config presented, and have the rpi start as an AP so you can simply plug in, connect to the device and configure the wifi.

pretty much what every commercial product does.

**Comment by johnyfarrar** [comment]
I'm not sure I can help with this repo but I think I could help with a web ui as that's where my skill lie. I'm subscribing to this thread and happy to help any way I can

**Comment by CodeCutterUK** [comment]
Okay - I've forked the repo....I'll take a few days to get things like the readme, build system, etc set-up.....but I guess we can officially say the ball is rolling.

**Comment by palitu** [comment]
nice!

im in Australia, GMT+8, not sure of the rest of you guys,

**Comment by axelsimon** [comment]
I'd just like to point out that @badaix has [merged some pull requests in the past days](https://github.com/badaix/snapcast/pulls?q=is%3Apr+is%3Aclosed). So it appears he is active again and maybe we can have a better conversation together about the future of Snapcast :)

**Comment by johnyfarrar** [comment]
@badaix My offer to help is for you also - I've not set up this system yet but when I do I'm sure there might be things I can do

**Comment by CodeCutterUK** [comment]
Thanks for highlighting this @axelsimon 

I'm more than happy to back out from forking, or indeed working with @badaix to formally migrate over to the org, equally as @johnyfarrar says, I'm happy to help out here.

**Comment by palitu** [comment]
I think with the lack of comms in the 5 days since, that we can safely assume it is worth pushing forward with a migration to the snapcast organisation that has been built.

It is probably worth mentioning that there snapcast has been functioning really well for the last few years with minimal changes!

**Comment by CodeCutterUK** [comment]
It looks like some changes are being made on the develop branch.....I'll press ahead anyway, the worst that happens is we delete the new org.
I've created a Gitter space for more fluid comes (link in the new repo)

**Comment by palitu** [comment]
i couldnt see the link.

I really like the continuous referral to @badaix.  (s)he is really the reason we are all together.

**Comment by CodeCutterUK** [comment]
Should be as a Gitter badge on the readme linking here: [Gitter - Snapcast](https://gitter.im/Snapcast/community)
