### ISSUE TITLE
how to update/refresh server.json file?

### ISSUE THREAD

**Issue by dddesign** [badaix/snapcast#458]
I use snapcast as plugin for volumio and I have different snapclients (on raspberry pis and openwrt routers) whic will connect to the snapserver. I don't shut down the clients by command but switch off the client's current (I know this is not the proper way). If I check the status of all clients in server.json file I still see the turn off clients for a quite a long time (5-15min). Is there a way (e.g. cli command) to update/refresh all status so I get a updated server.json file?

**Comment by badaix** [comment]
no, it's some TCP timeout that eventually happens after 5-15min
