### ISSUE TITLE
Compile errors on Raspberry Pi

### ISSUE THREAD

**Issue by lamby01** [badaix/snapcast#46]
Hi
I am getting compile errors in both the server and client.
Here is the output after trying to make all:
```
/usr/bin/g++ -std=c++0x -static-libgcc -static-libstdc++ -Wall -Wno-unused-function -O3 -pthread -DASIO_STANDALONE -DVERSION=\"0.5.0\" -I.. -I../externals/asio/asio/include -I../externals/popl/include -c controlServer.cpp -o controlServer.o
controlServer.cpp: In member function ‘void ControlServer::handleAccept(socket_ptr)’:
controlServer.cpp:106:21: error: ‘class asio::basic_stream_socket<asio::ip::tcp>’ has no member named ‘native’
  setsockopt(socket->native(), SOL_SOCKET, SO_RCVTIMEO, &tv, sizeof(tv));
                     ^
controlServer.cpp:107:21: error: ‘class asio::basic_stream_socket<asio::ip::tcp>’ has no member named ‘native’
  setsockopt(socket->native(), SOL_SOCKET, SO_SNDTIMEO, &tv, sizeof(tv));
                     ^
In file included from ../externals/asio/asio/include/asio/detail/impl/posix_mutex.ipp:24:0,
                 from ../externals/asio/asio/include/asio/detail/posix_mutex.hpp:71,
                 from ../externals/asio/asio/include/asio/detail/mutex.hpp:25,
                 from ../externals/asio/asio/include/asio/detail/service_registry.hpp:20,
                 from ../externals/asio/asio/include/asio/impl/execution_context.hpp:20,
                 from ../externals/asio/asio/include/asio/execution_context.hpp:406,
                 from ../externals/asio/asio/include/asio/detail/scheduler.hpp:21,
                 from ../externals/asio/asio/include/asio/system_executor.hpp:19,
                 from ../externals/asio/asio/include/asio/associated_executor.hpp:21,
                 from ../externals/asio/asio/include/asio.hpp:19,
                 from controlServer.h:22,
                 from controlServer.cpp:19:
../externals/asio/asio/include/asio/error.hpp: At global scope:
../externals/asio/asio/include/asio/error.hpp:256:36: warning: ‘asio::error::system_category’ defined but not used [-Wunused-variable]
 static const asio::error_category& system_category
                                    ^
../externals/asio/asio/include/asio/error.hpp:258:36: warning: ‘asio::error::netdb_category’ defined but not used [-Wunused-variable]
 static const asio::error_category& netdb_category
                                    ^
../externals/asio/asio/include/asio/error.hpp:260:36: warning: ‘asio::error::addrinfo_category’ defined but not used [-Wunused-variable]
 static const asio::error_category& addrinfo_category
                                    ^
../externals/asio/asio/include/asio/error.hpp:262:36: warning: ‘asio::error::misc_category’ defined but not used [-Wunused-variable]
 static const asio::error_category& misc_category
                                    ^
make: *** [controlServer.o] Error 1
make: Leaving directory `/root/snapcast-master/server'
```

-------------
Any help much appreciated.

**Comment by badaix** [comment]
On which RasPi? (1, 2, 3)?
What distribution are you using? 
Which gcc version?

Shouldn't help, but you could try to `cd` into `client` and call `make` from there. I didn't use this `make all` for a long time.

**Comment by lamby01** [comment]
RPi 1 B+
Volumio 1.5

I went into client and tried make, but got same error.
Not sure what version my g++ is, so I edited Makefile to use g++-4.9 and still got the error.

I had problems downloading the submodules - `git submodule update --init --recursive` did nothing. I had to use git submodule add for each of the three directories. Not sure if that would cause compilation errors?

**Comment by Kernald** [comment]
I don't know exactly what happened here, but here's a hint: `asio::basic_socket::native` has been deprecated a while ago in asio. [Here](http://www.boost.org/doc/libs/1_60_0/doc/html/boost_asio/reference/basic_stream_socket/native.html)'s the relevant page on the latest boost version's documentation.

The asio referenced in submodules [still has it](https://github.com/chriskohlhoff/asio/blob/c466dc46d55755d38ee1831e95207d6b329c4976/asio/include/asio/basic_socket.hpp#L388).

However, the master branch of this asio repository doesn't have it anymore, but only [`native_handle()`](https://github.com/chriskohlhoff/asio/blob/master/asio/include/asio/basic_socket.hpp#L391) (I don't know if that would work as a simple drop-in replacement, I didn't use asio in years).

You should probably check your asio submodule, it should point to `5e73285` and not to `master`.

**Comment by lamby01** [comment]
OK.  I looked at the submodules:
```
root@volumio:~/snapcast-master/externals# git submodule status
 722f7e2be05a51c69644662ec514d6149b2b7ef8 asio (asio-1-10-2-178-g722f7e2)
 50af1bcf63481f63a01da53e4c58b8d0dbe8c07a flac (1.3.1-172-g50af1bc)
 59fddc997e405249708b9d6c9a611eaa8da8e983 popl (heads/master)
```
This suggests the asio module is old.
Could someone please suggest how to update to the 1-10-6 version?
`git submodule update` doesn't seem to do anything!

Thanks

**Comment by lamby01** [comment]
I think I've sorted it.
I originally downloaded snapcast using `wget https://github.com/badaix/snapcast/archive/master.zip`

I tried on another Pi using git clone, and it seems to be compiling just fine. All the submodules updated properly.
Sorry to have wasted people's time.

**Comment by badaix** [comment]
Thanks for the hint @Kernald. I simply used the most recent tag 1.10.6. This version has:
```c++
  /// (Deprecated: Use native_handle().) Get the native socket representation.
  /**
   * This function may be used to obtain the underlying representation of the
   * socket. This is intended to allow access to native socket functionality
   * that is not otherwise provided.
   */
  native_type native()
  {
    return this->get_service().native_handle(this->get_implementation());
  }

  /// Get the native socket representation.
  /**
   * This function may be used to obtain the underlying representation of the
   * socket. This is intended to allow access to native socket functionality
   * that is not otherwise provided.
   */
  native_handle_type native_handle()
  {
    return this->get_service().native_handle(this->get_implementation());
  }
```
So `native_handle()` is indeed a drop-in replacement for `native()`. I will for now stick to this revision of Asio, but change Snapcast to use `native_handle()`.

@lamby01: this way I've learned that the zip doesn't contain the submodules ;).  
I'm adding a small [howto](https://github.com/badaix/snapcast/blob/develop/doc/build.md) for the build process in native Linux and for cross-compilation. It will be mentioned there to clone the whole project.
