### ISSUE TITLE
Pulseaudio wrong sink format (sounds like noise and only one channel in stereo)

### ISSUE THREAD

**Issue by topas-rec** [badaix/snapcast#460]
What works:
Tested a fresh Linux Mint with Snapcast and it works with Pulseaudio using the [instructions](https://github.com/badaix/snapcast/blob/master/doc/player_setup.md#pulseaudio) directly - nice.

Where there are problems:
Since I live together with JACK,  Snapcast didn't work out of the box with Pulseaudio routed to  JACK (3rd option under http://jackaudio.org/faq/pulseaudio_and_jack.html) on my machine. Additionally I let Cadence ([kx.studio](kx.studio)) start my Studio on login. Through this JACK manages my Pulseaudio and sets the format of the pipe sink to a wrong format. (Format is float32le) With this setting one can guess the original signal on one channel which is slowed down and covered by noise and hear pure noise on the second channel.

How to avoid it:
When I explicitly create the sink with the format needed by Snapcast it works like expected also on a machine that uses Linux Mint with JACK.

Commands suggested for the readme file:
`pacmd load-module module-pipe-sink file=/tmp/snapfifo sink_name=Snapcast format=s16le rate=48000`
`pacmd update-sink-proplist Snapcast device.description=Snapcast`
(Just the `format=s16le` was added)

Awesome idea and thanks for putting it open source!

**Comment by badaix** [comment]
thanks, readme is updated
