### ISSUE TITLE
Listen to original stream on snapcastserver machine / device using pulseaudio

### ISSUE THREAD

**Issue by topas-rec** [badaix/snapcast#461]
# General
I found a way to listen to the stream that goes to the snapserver on the server machine itself. I use this to play music on my main computer in the living room to which my stereos are connected. (I want minimalistic modified sound here) That main machine acts also as the snapcast server. I use the snapcast client somewhere in my flat. (I use my android phone together with a bluetooth speaker as a client - that way I don't need addtional hardware)

# Partly solution
I combined my Snapcast sink in pulseaudio (see [PulseAudio section in Snapcast](https://github.com/badaix/snapcast/blob/master/doc/player_setup.md#pulseaudio)) with my main listening sink (in my case a Jack sink, but this can be any sink available like a soundcard). When sound goes into the combined sink both slave sinks will get the sound simultaneously. Then I set the combined sink as the default sink. (I disabled the time adjustment in pulseaudio combined sink - sounded slow and awful)

Commands to use AFTER applying the general pulseaudio configuration mentioned above:
`pacmd load-module module-combine-sink sink_name=something_and_Snapcast slaves=something,Snapcast adjust_time=0`
(Change "something" to your sink name)

To find all your sink available use `pacmd list`
To find more information visit: https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/Modules/#index11h3

Why this is a partly solution?
Snapcast introduces a delay in the sound which is not present when directly listening to the sound on the snapserver machine. Therefore one has to add a configurable static delay to that sound. I think there are some tools for that out there. I have to search myself, but I'm convinced that this is just a search away.

I would like to get some feedback to that. If this is a general use case it might be documented somewhere.

**Comment by topas-rec** [comment]
I found a way to delay the audio in pulseaudio: loopback sinks with latency

One can create a null sink, then combine it with the Snapcast sink so that both get the same signal at once.
After that is done one can load a loopback module with a latency and route it to the desired sink for the speakers. (I used two null sinks and two loopbacks to extend the maximum delay / latency time from 2 seconds to 4 seconds)
Here are my commands for this
`pacmd load-module module-null-sink sink_name=delayed`
`pacmd load-module module-null-sink sink_name=delayed1`
`pacmd load-module module-combine-sink sink_name=JACK_delayed_and_Snapcast slaves=delayed,Snapcast`
`pacmd set-default-sink JACK_delayed_and_Snapcast `
`pacmd load-module module-loopback source=delayed.monitor sink=delayed1 latency_msec=2000`
`pacmd load-module module-loopback source=delayed1.monitor sink=jack_out latency_msec=200`

So it is possible to create, but the result is not satisfying. The two audio signals (Snapcast client and audio directly from the server) can be made synchronous initially, but after a short time (one MiInute) they drift apart from each other.

I would like to test or discuss this further if anyone has some ideas.

**Comment by vjdw** [comment]
To do this I run snapclient on my server that's also running snapserver. This would then solve the two audio signals drifting out of sync. However, the bluetooth connection from your phone to your speaker will introduce a delay that snapcast can't automatically account for so you'd need to add an offset to the snapclient on your phone to force that snapclient to play stuff sooner than it thinks it should.

**Comment by topas-rec** [comment]
> To do this I run snapclient on my server that's also running snapserver. This would then solve the two audio signals drifting out of sync

In this case (this issue) one uses pulseaudio. If one plays an audio signal it will be routed to pulseaudio. Pulseaudio will route it to its default sink. This is most likely a pipesink for snapserver. Let's now say that a snapclient also is activated on that machine. Then it will also use pulseaudio on that machine. Pulseaudio will do the same with the audio signal from snapclient than it did with the original audio signal. It will route it to the default sink which will create a loop. This loop creates a horrible echo in the audio signal.

If it would be possible to select a specific sink to in pulseaudio to play to from snapclient like in the [module-rtp-recv](https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/Modules/#index39h3) from pulseaudio the suggested method would work.
I don't know a method for selecting the sink in pulseaudio to play to from snapclient. It can only select `pulse` as output, not pulse:sink1 or similar.

The module-rtp-recv does something similar than snapcast.

**Comment by topas-rec** [comment]
> However, the bluetooth connection from your phone to your speaker will introduce a delay that snapcast can't automatically account for so you'd need to add an offset to the snapclient on your phone to force that snapclient to play stuff sooner than it thinks it should.

True, used an audio jack instead.
With the mentioned pulseaudio module one can define the latency as parameter which pulseaudio will try to use. This works at least initially. The audio signals drift out of sync sometimes.

**Comment by topas-rec** [comment]
Solved this thing with a really easy and straight forward solution.

- Listen to the audio on the server can be done by

  - also using snapclient on server (snapserver is also running and setup with Pulseaudio)
  
    - without arguments and
    
    - as user (not as deamon which runs at root and has no access to Pulseaudio) and
    
  - by using Pulseaudio Volume Controls playback tab to set Snapclient sink for each app that should go through Snapcast

![image](https://user-images.githubusercontent.com/20391449/82140266-fe43df80-982e-11ea-8c40-0b3da6f687a6.png)
