### ISSUE TITLE
Check notifications of snapclient (API)

### ISSUE THREAD

**Issue by dmckminard** [badaix/snapcast#468]
Hello,

I wish I could retrieve API notifications on Python programs.
In more detail, I would like, for example, to be able to retrieve notifications of volume changes in a Python program, but I can not do it.

I saw that I could see these notifications by running snapclient manually, but I prefer to run it as a service.
I can also see json frames in netcat, but can not see them in python.
When I try to see them via telnetlib in python, a delay of about 4 seconds is added ...

How can we see the notifications, especially the volume change, easily (and retrieve them in python)?

**Comment by A----** [comment]
There's an API, there are notifications: https://github.com/badaix/snapcast/blob/master/doc/json_rpc_api/v2_0_0.md#clientonvolumechanged

**Comment by dmckminard** [comment]
Yes, and I can see them via a nc localhost 1705 for example. But can I see them directly in python ?

**Comment by happyleavesaoc** [comment]
Try this python module: https://github.com/happyleavesaoc/python-snapcast

For example, https://github.com/happyleavesaoc/python-snapcast/blob/master/snapcast/control/server.py#L268 is where volume changes are received and handled. There will also be a message printed to the log.

**Comment by dmckminard** [comment]
I've already tried this solution but I had some issues (there is no doc and sometimes the program is crashing), and some functions needed by me aren't implemented.

**Comment by badaix** [comment]
The current develop branch introduces json rpc over websockets, maybe this is easier to implement in Python. It's basically the same, but wrapped in a http tunnel, so there is more overhead. I can't imagine where your 4s delay is coming from. Is it also delayed in netcat?
Maybe you're reading until timeout and not until reception of an newline
