### ISSUE TITLE
Android App crashed with more then 2 Input Sources

### ISSUE THREAD

**Issue by bjwelker** [badaix/snapcast#47]
I have made 3 Input Sources, one for Volumio, one for Spotify-Connect and one for Airplay. When i switch the input channels in the app the app crash. When i disable Airplay in the config everything is fine.

**Comment by badaix** [comment]
This should be fixed with b196f442adfb4769630f7f1e968f375c1adcd1b0. Will be part of the v0.6 that will be released the next days.

**Comment by bjwelker** [comment]
perfect

**Comment by badaix** [comment]
Fixed in [v0.6.0](https://github.com/badaix/snapcast/releases/tag/v0.6.0)
