### ISSUE TITLE
snapserver calling lsb_release -d multiple times

### ISSUE THREAD

**Issue by FrankyGT** [badaix/snapcast#470]
I see spikes of high CPU usage when using snapserver. There seems to be some code that executes "lsb_release -d" in a loop.

Especially at startup I see hundreds of calls, but also when playing media

[pid 32731] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=32732, si_uid=999, si_status=0, si_utime=25, si_stime=4} ---
[pid 32731] +++ exited with 0 +++
[pid 32724] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=32731, si_uid=999, si_status=0, si_utime=0, si_stime=1} ---
strace: Process 32742 attached
[pid 32742] execve("/bin/sh", ["sh", "-c", "arch 2> /dev/null"], [/* 9 vars */]) = 0
strace: Process 32743 attached
[pid 32743] execve("/usr/bin/arch", ["arch"], [/* 10 vars */]) = 0
[pid 32743] +++ exited with 0 +++
[pid 32742] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=32743, si_uid=999, si_status=0, si_utime=0, si_stime=0} ---
[pid 32742] +++ exited with 0 +++
[pid 21595] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=32742, si_uid=999, si_status=0, si_utime=0, si_stime=1} ---
strace: Process 32746 attached
[pid 32746] execve("/bin/sh", ["sh", "-c", "lsb_release -d 2> /dev/null"], [/* 9 vars */]) = 0
strace: Process 32748 attached
[pid 32748] execve("/usr/bin/lsb_release", ["lsb_release", "-d"], [/* 10 vars */]) = 0
[pid 32748] +++ exited with 0 +++
[pid 32746] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=32748, si_uid=999, si_status=0, si_utime=25, si_stime=5} ---
[pid 32746] +++ exited with 0 +++
[pid 32724] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=32746, si_uid=999, si_status=0, si_utime=0, si_stime=0} ---
strace: Process 32749 attached
[pid 32749] execve("/bin/sh", ["sh", "-c", "arch 2> /dev/null"], [/* 9 vars */]) = 0
strace: Process 32750 attached
[pid 32750] execve("/usr/bin/arch", ["arch"], [/* 10 vars */]) = 0
[pid 32750] +++ exited with 0 +++
[pid 32749] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=32750, si_uid=999, si_status=0, si_utime=0, si_stime=0} ---
[pid 32749] +++ exited with 0 +++
[pid 32724] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=32749, si_uid=999, si_status=0, si_utime=0, si_stime=1} ---

Since lsb_release is implemented in python3, this will severely hurt a raspberry pi

**Comment by FrankyGT** [comment]
my workaround for now is to rename the original lsb_release python script and replace with : 

#!/bin/bash
if [[ $* == '-d' ]]
then
        echo "Description:    Raspbian GNU/Linux 9.9 (stretch)"
else
        /usr/bin/lsb_release.org $*
fi

**Comment by badaix** [comment]
It should be called just once at startup on the clients and on the server every time someone requests the server status via the RPC interface.
Are you using some special UI?
The result of `lsb_release` is no cached and so it should be called only once: a8d1769
