### ISSUE TITLE
Groups Question

### ISSUE THREAD

**Issue by hav0ck** [badaix/snapcast#471]
I am playing with Snapcast and in my testing with a single client it has worked really well.

I am a bit confused by groups though. From what I've read and hopefully understood each client needs to be added to a group using an app like snapcast.

So my real world setup i envisioned having these clients:
- Deck
- Kitchen
- Living Room
- Dining Room 
- Bedroom 1
- Bedroom 2
- Bedroom 3

Now assuming my above understanding is correct I foresee issues implementing this, hopefully I'm missing an important piece here. 
I had hoped that I could set different groups say Summer-Party, Party, diner-time, Time-for-school etc. Then place the clients in various groups, So if I select Summer-Party group the Deck, Kitchen, Dining Room, and Living Room clients would play the music, but if it gets late with fewer people then I change to Kitchen-Party group with only Kitchen, and Dining Room clients would play the music.

That's just a simple example but my understanding is that you have to manually move clients from group to group. Is this correct? If so what is the difference between groups and streams then? 
Is this not the same as going to each client and selecting the stream to play?

**Comment by m-kloeckner** [comment]
Actually there is no such thing as groups. You define streams and each client connects to a stream. All clients listening to the same stream kind of form a group.

For your scenario you would need to disconnect some clients from the stream or mute some of the clients.

I would love to have it the other way around, too. It would be great to be able to define groups and streams separately, so that you can assign streams to groups.

**Comment by elnkosc** [comment]
I built a setup by connecting the snapcast server to Spotify and 2 snapcast clients listening to the same stream. In the snapdroid app I get to see 2 times the Spotify group and in both groups 1 client is attached and the other one not. I would have expected a single group with both clients connected. 

Am I missing a concept here?

**Comment by badaix** [comment]
Clients are grouped together in "anonymous" groups and to each group a stream is assigned. 
By default a newly connected client is in its own group and the default stream is assigned to this group.
It's basically working like in the Sonos app: https://www.youtube.com/watch?v=zL7-1vs_fuE
What you're asking for are some predefined groups, which are not supported.

**Comment by winterscar** [comment]
Is there a way to automatically assign all clients playing the same source to the same group?
