### ISSUE TITLE
snapserver build error on Mac OS 10.14.6

### ISSUE THREAD

**Issue by Ashaman-** [badaix/snapcast#474]
Build Log:

make TARGET=MACOS
g++  -std=c++0x -Wall -Wno-unused-function -O3 -DHAS_FLAC -DHAS_OGG -DHAS_VORBIS -DHAS_VORBIS_ENC -DASIO_STANDALONE -DVERSION=\"0.15.0\" -I. -I.. -isystem ../externals/asio/asio/include -I../externals/popl/include -I../externals/aixlog/include -I../externals -I../common -DMACOS -DFREEBSD -DHAS_BONJOUR -DHAS_DAEMON -Wno-deprecated -I/usr/local/include -c snapServer.cpp -o snapServer.o
In file included from snapServer.cpp:39:
../externals/aixlog/include/aixlog.hpp:30:39: warning: extra tokens at end of #ifdef directive [-Wextra-tokens]
#ifdef __MAC_OS_X_VERSION_MAX_ALLOWED >= 1012
                                      ^
                                      //
snapServer.cpp:52:9: warning: Warning: the macOS support is experimental and might not be maintained [-W#pragma-messages]
#pragma message "Warning: the macOS support is experimental and might not be maintained"
        ^
In file included from snapServer.cpp:34:
In file included from ./streamServer.h:30:
In file included from ./jsonrpcpp.hpp:27:
../common/json.hpp:1204:9: error: static_assert failed "could not find from_json() method in T's namespace"
        static_assert(sizeof(BasicJsonType) == 0,
        ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~
../common/json.hpp:1219:16: note: in instantiation of function template specialization
      'nlohmann::detail::from_json_fn::call<nlohmann::basic_json<std::map, std::vector, std::__1::basic_string<char>, bool, long long, unsigned long
      long, double, std::allocator, adl_serializer>, std::__1::basic_string_view<char, std::__1::char_traits<char> > >' requested here
        return call(j, val, priority_tag<1> {});
               ^
../common/json.hpp:9663:9: note: in instantiation of function template specialization
      'nlohmann::detail::from_json_fn::operator()<nlohmann::basic_json<std::map, std::vector, std::__1::basic_string<char>, bool, long long, unsigned
      long long, double, std::allocator, adl_serializer>, std::__1::basic_string_view<char, std::__1::char_traits<char> > >' requested here
        ::nlohmann::from_json(std::forward<BasicJsonType>(j), val);
        ^
../common/json.hpp:12184:36: note: in instantiation of function template specialization 'nlohmann::adl_serializer<std::__1::basic_string_view<char,
      std::__1::char_traits<char> >, void>::from_json<const nlohmann::basic_json<std::map, std::vector, std::__1::basic_string<char>, bool, long long,
      unsigned long long, double, std::allocator, adl_serializer> &, std::__1::basic_string_view<char, std::__1::char_traits<char> > >' requested here
        JSONSerializer<ValueType>::from_json(*this, ret);
                                   ^
../common/json.hpp:12446:16: note: in instantiation of function template specialization 'nlohmann::basic_json<std::map, std::vector,
      std::__1::basic_string<char>, bool, long long, unsigned long long, double, std::allocator, adl_serializer>::get<std::__1::basic_string_view<char,
      std::__1::char_traits<char> >, std::__1::basic_string_view<char, std::__1::char_traits<char> >, 0>' requested here
        return get<ValueType>();
               ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string:875:29: note: in instantiation of function
      template specialization 'nlohmann::basic_json<std::map, std::vector, std::__1::basic_string<char>, bool, long long, unsigned long long, double,
      std::allocator, adl_serializer>::operator basic_string_view<std::__1::basic_string_view<char, std::__1::char_traits<char> >, 0>' requested here
        {__self_view __sv = __t; return assign(__sv);}
                            ^
./jsonrpcpp.hpp:872:12: note: in instantiation of function template specialization 'std::__1::basic_string<char, std::__1::char_traits<char>,
      std::__1::allocator<char> >::operator=<nlohmann::basic_json<std::map, std::vector, std::__1::basic_string<char>, bool, long long, unsigned long
      long, double, std::allocator, adl_serializer>, void>' requested here
                message_ = json["message"];
                         ^
2 warnings and 1 error generated.
make: *** [snapServer.o] Error 1

**Comment by badaix** [comment]
please try again with the develop branch

**Comment by badaix** [comment]
any news? Can I close this issue?
