### ISSUE TITLE
+1sec latency until clients receives music

### ISSUE THREAD

**Issue by TurtleForGaming** [badaix/snapcast#477]
I was tryn to setup a mini test environement with two sound cards on my pc and my phone (3clients total) + the server on the same machine. I've loaded the pulse audio file sink pipe but when I try to watch a video / film or even play music I takes about 1.5sec for the audio to be distributed. Is there any way to reduce that I seen the PULSE_LATENCY_MSEC reference when loading the module but it does nothing at all.
(Edit) The audio IS sync between clients
Help would be apreciated.

**Comment by deisi** [comment]
There is some hardcoded delay in snapserver see:
https://github.com/badaix/snapcast/issues/329

I have once tried to compile my own version where I changed that number. However it didn't work at all so i stopped looking into this. Currently I just don't watch videos with snapcast, as pulse audio cant handle delay on fifos. But, if I remember correctly that might be available in a future version of pulse-audio.

**Comment by badaix** [comment]
Snapcast is not designed to sync audio and video, but only to sync different audio clients.

**Comment by badaix** [comment]
You can reduce it to 400ms (the buffer setting in `snapserver.conf`).
I recommend changing the volume using the snapcast API to have it changed instantly (you can use e.g.  [Snapdroid](https://github.com/badaix/snapdroid)).
When you just change the volume of your input signal, you will have of course the configured latency.
