### ISSUE TITLE
Any RaspberryPi webinterface distros have builtin support for snapcast?

### ISSUE THREAD

**Issue by nimonimonimo** [badaix/snapcast#483]
Hi,

This is not any bug, but I wonder if anyone has a good overview over which already audio pre-configured webinterface based distros for Raspberry Pi that has either bultin or available as module/extension support for snapcast?

Example of audio pre-configured webinterface based distros are:
Volumio
Runeaudio
Pi MusicBox
etc...

**Comment by badaix** [comment]
I stumbled upon [Iris](https://github.com/jaedb/Iris), it's not a ready made RPi image and I didn't test it, but it looks quite interesting to me.

**Comment by palitu** [comment]
I am also looking for something like this to make my rpi players more like an appliance than a whole computer.  Also make it easier to install and maintain (ie the Wifi setup).
