### ISSUE TITLE
OpenWrt - DWR-921 - .ipk-compability and cross-compiling

### ISSUE THREAD

**Issue by totti2** [badaix/snapcast#489]
Hi,

I want to use my d-link dwr with openwrt 18.06 as a snapserver.

Using the prebuilt ipk gives me
```
root@OpenWrt:~# opkg install snapclient_0.15.0_mips_24kc.ipk 
Unknown package 'snapclient'.
Collected errors:
 * pkg_hash_fetch_best_installation_candidate: Packages for snapclient found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package snapclient.
```

Trying to build it myself stops because there is no OpenWrt-directory
```
git clone https://github.com/badaix/snapcast.git
cd snapcast/externals/
git submodule update --init --recursive 
cd ../../openwrt/
mkdir -p package/sxx/snapcast
cd package/sxx/snapcast/
ln -s ../../../../snapcast/ src
ln -s ../../../../snapcast/openWrt/Makefile.openwrt Makefile
cd ../../../../openwrt/
make defconfig
make menuconfig

grep: package/sxx/snapcast/Makefile: No such file or directory
```
Is the router even compatible?
Do I have to copy the openwrt files somewhere?

**Comment by badaix** [comment]
Seems that the router is supported by OpenWrt: [DWR-921](https://openwrt.org/toh/d-link/d-link_dwr-921). From the specs it should work (580 MHz MIPS, 16MB of RAM ought to be enough for anybody)
You should be able to build it for your router when you follow this [guide](https://github.com/badaix/snapos/tree/master/openwrt)

**Comment by xabolcs** [comment]
@totti2 do a `opkg print-architecture` on your router, and you will see that you need snapcast for `mipsel_24kc` and not for `mips_24kc`! :) 

As @badaix wrote, you have to build it yourself.
