### ISSUE TITLE
Android Client without Controller

### ISSUE THREAD

**Issue by bjwelker** [badaix/snapcast#49]
Is it possible to get a Android Client without the Controller thing ?
So you can run it on a FireTV, FireTV Stick or old Smartphone.
Maybe only a big streamlist and a mute/unmute button.

**Comment by badaix** [comment]
well, the controlling app simply installs and starts/stops a snapclient binary. So it's already there.
To automate the startup it's most convenient to wrap it into an app. Whats missing is some autostart mode, such that the player-service (it's already implemented as a service) is startet when receiving the BOOT_COMPLETED broadcast event.

BTW: I like the Snapcast GUI on my 47" screen, running on FireTV :wink:

**Comment by bjwelker** [comment]
Ok so i don´t need to start the gui ?
Would be a nice addon for the ecosystem and this fantastic piece of code :)

Im on the way to finish my Snap:Cast One Speaker. Raspberry Zero with Phatdac build into a small speaker. Readonly Raspian so you can put off the poweroutlett when you need. perfect for Kitchen and Outside ;)

**Comment by badaix** [comment]
At the moment you have to start the GUI. I will keep this autostart option in Mind for upcoming versions.

Snap:Cast One :smiley: nice!
I didn't know about the pHAT DAC. Like it - small and affordable.
Maybe it's worth for you to take a look at issue #14 and this [PiCorePlayer extension](https://github.com/m-kloeckner/snapcast-tcz).

**Comment by bjwelker** [comment]
Nice. But it dowsn´t install on the piCore with the howto on the page. Would be the perfekt and fast System for a speaker.

**Comment by badaix** [comment]
I wonder how fast this piCore can boot

**Comment by bjwelker** [comment]
Mi start in about 25 seks :)

but i can´t get snapclient compiled to 0.6.0 only 0.4.1 :(

**Comment by bjwelker** [comment]
@badaix  when i try to complie snapclient i get

snapClient.cpp:22:20: fatal error: popl.hpp: No such file or directory
 #include "popl.hpp"
                    ^
compilation terminated.

Wich debian package did i need to install to compile this on a raspberry ?

**Comment by happyleavesaoc** [comment]
Assuming you `git clone`d the repo, init and update the submodules, which includes `popl`: `git submodule update --init --recursive`

**Comment by bjwelker** [comment]
damm i need to remember RTFM ....

**Comment by badaix** [comment]
Simply follow this [FM](https://github.com/badaix/snapcast/blob/master/doc/build.md):

> Clone Snapcast:
> 
>     $ git clone https://github.com/badaix/snapcast.git
> 
> this creates a directory `snapcast`, in the following referred to as `<snapcast dir>`.  
> Next clone the external submodules:
> 
>     $ cd <snapcast dir>/externals
>     $ git submodule update --init --recursive
>

**Comment by bjwelker** [comment]
Ok up and running 0.6.0
From boot to show up in controller app 16 sec. :)
Nice and fast for some speaker building

**Comment by badaix** [comment]
Below 10s would be better. 
But on a good way already. ;)

**Comment by bjwelker** [comment]
In 10 sec i don't get my Smartphone out of the Pants to Controll the player ;)

**Comment by bjwelker** [comment]
I have made a small script to install avahi and snapcast client version 0.6.0 on piCorePlayer
https://github.com/bjwelker/Snapcast-piCore

i´m on the way to make the script running with piCore only so that the image boots faster then now.

**Comment by bjwelker** [comment]
ok build a complete new piCore image with only the things needed. Faster boot not possible. DHCP takes to long :(

**Comment by badaix** [comment]
Thanks for the info. It is actually quite interesting how fast it can boot. I usually have already some web radio running. If I now power an additional Snap:Cast One, it will start playing independently of the time it takes to get my mobile out of my pocket :wink:

**Comment by bjwelker** [comment]
If Setup 3 Raspberry now with this image. Working so perfect. Will finetune the image a bit but for now I build some snacast multiroom Speaker. I do t now about the design Let's See

**Comment by m-kloeckner** [comment]
Nice to your progress! I used an image from https://sites.google.com/site/picoreplayer/home because I was using a SqueezeBox before switching over to snapcast..
I haven't measured how fast my setup boots, though. ;-) Also running 3 raspis in different rooms now.

**Comment by bjwelker** [comment]
@m-kloeckner it´s only a normal piCore with a little script ;) and snapcast 0.6.0

**Comment by badaix** [comment]
Regarding the original question: Snapcast [v0.7.0](https://github.com/badaix/snapcast/releases/tag/v0.7.0) introduces an auto start option in the Android client. You have to activate it once in the settings. Once activated you can use your stationary Android device headless. It will start playing after being powered on.

**Comment by Kernald** [comment]
And with this setting, Snapcast works great on Android TV too! The first launch is not obviously simple, but it works. Thanks 👍
