### ISSUE TITLE
Radio stream drifts in and out of sync between Raspberry Pi 3B (Mopidy serverl, Snapserver, and Snapclient) and Raspbery Pi Zero W (Snapclient)

### ISSUE THREAD

**Issue by alexjmccoy** [badaix/snapcast#498]
I have an NPR radio stream saved in an `.m3u` file which I send to the snapserver via Mopidy:

Relevant section of `/etc/mopidy/mopidy.conf`:
```
[audio]
output = audioresample ! audio/x-raw,rate=44100,channels=2,format=S16LE ! audioconvert ! wavenc ! filesink location=/tmp/snapfifo
```
and `/etc/snapserver.conf`:
```
[stream]
stream = pipe:///tmp/snapfifo?name=Picast&sampleformat=44100:16:2&codec=flac
```

There are two clients: 
* a snapclient on the same Raspberry Pi 3 B running the Mopidy server and Snapserver instance
* a snapclient on a Raspberry Pi Zero W

When I stream the radio station it is very often out of sync in the beginning and I have to adjust the latency in the Snapcast Android app to something like 50 ms. This solves the problem for a bit, but after a while the two clients drift apart. I fix the latency again (without adjusting the volume or anything else) which provides another temporary fix until it drifts out of sync again after a few minutes.

This issue seems limited to the http radio stream. I downloaded an mp3 file of a metronome to the Mopidy instance and played it for 10 minutes without any sync issues. The radio stream works just fine on multiple Chromecast clients so I don't think it's inherent to the radio stream.

Please let me know if I can provide any additional information, and thanks!

**Comment by badaix** [comment]
Can you try with 48000 Hz samplerate?

**Comment by ashwinvandijk** [comment]
I experience the same issues. From time to time playback stops, and when it continues i'm not able to get in sync again unless I restart the stream (ie: stop playback from Spotify so all clients "reset"). I'm using 48000hz samplerate.

**Comment by alexjmccoy** [comment]
So I changed the sampling rate to 48000 Hz and the problem has not recurred. Seems that was the issue! Thank you for the suggestion!

I have a follow-up question. I'll post it here, but if you prefer I open a new issue we can close this one and I'll make a new one.

I use [raspotify](https://github.com/dtcooper/raspotify/) to make my Snapcast speakers work with Spotify connect. This is why I originally used 44100 Hz. Here is the relevant section of the raspotify config:

`/etc/default/raspotify.conf`:
```
DEVICE_NAME="Picast"
BITRATE="320"
BACKEND_ARGS="--backend pipe --device /tmp/snapfifo"
```

Best case scenario is that I could have two pipes for the Snapserver, i.e.:

`/etc/snapserver.conf`
```
[stream]
stream = pipe:///tmp/snapfifo?name=Spotify&sampleformat=44100:16:2&codec=flac
stream = pipe:///tmp/snapfifo?name=Piradio&sampleformat=48000:16:2&codec=flac
```

Such that the web radio stream from Mopidy is passed to Snapserver at 48 kHz and raspotify is passed through at 44.1 kHz. Is such a setup possible?
