### ISSUE TITLE
Snapserver only plays audio for the first stream in config file

### ISSUE THREAD

**Issue by FlyingBollards** [badaix/snapcast#501]
I have a snapserver.conf file with 3 streams in it.

The default one, a spotify:/// one and an airplay:/// one

The default one is used for Mopidy and works perfectly.

The other two I can see are initialised when Snapserver starts in a console window, and I can see onStateChanged events when clients connect / play music.

However, the second 2 streams never produce any audio. The clients don't receive chunks when audio is playing through either Spotify or Airplay.

However, if I comment (#) out the default stream, which is first in the list, then start Snapserver again, the Spotify stresm now works. Same behaviour in the Snapserver console but this time, when music is played from a client, the Snapclients receive chunks.

But while Spotify is first in the list, the Airplay stream still produces no audio.

But if I comment out the Spotify stream too, so that Airplay is the only stream in the conf file, then Airplay plays audio too.

So it looks like, for, some reason, Snapserver only plays audio for the first stream in the conf file. And while it does pick up other stream entries and initialises them - even recognised connections from clients - it never plays any audio from them.

**Comment by badaix** [comment]
I've just tested version 0.16 with two streams (both pipes) and it's working as expected. Can you post your `[stream]` section?

**Comment by FlyingBollards** [comment]
Hi,

Thanks - of course.

[stream]
# address to listen on, can be specified multiple times
# use "0.0.0.0" to bind to any IPv4 address or :: to bind to any IPv6 address
# or "127.0.0.1" or "::1" to bind to localhost IPv4 or IPv6, respectively
# use the address of a specific network interface to just listen to and accept
# connections from that interface
#bind_to_address = 0.0.0.0

# which port the server should listen to
#port = 1704

# stream URI of the PCM input stream, can be configured multiple times
# Format: TYPE://host/path?name=NAME[&codec=CODEC][&sampleformat=SAMPLEFORMAT]
stream = pipe:///tmp/snapfifo?name=default
stream = pipe:///tmp/librespotfifo?name=spotifypipe
stream = airplay:///shairport-sync?name=Airplay&devicename=Snapcast
stream = spotify:///librespot?name=Spotify&devicename=Snapcast&bitrate=320&sampleformat=44100:16:2
# Default sample format
#sampleformat = 48000:16:2

So with that config, all services appear and are initialised, and are available on my network.

But only mopidy, which uses the default stream, produces any audio. All the other lines work, and accept connections, but never send audio to the snapclients.

But if I comment out the mopidy / default line and start snapcast again, then the second line - the pipe for raspotify - will start producing audio.

And so on.

**Comment by badaix** [comment]
I've tested now with two streams, one mpd, the other mopidy (I don't have spotify or airplay available):
```
stream = pipe:///tmp/snapfifo?name=mpd
stream = pipe:///tmp/mopidyfifo?name=mopidy
```
This setup is working, both streams are playing and I have two clients connected and can dynamically assign the streams in any order.

**Comment by FlyingBollards** [comment]
Thanks. 

I've tested again and am now seeing the problem slightly differently.

Different streams are playing to different clients.

So if I play Mopidy to the default pipe, it plays on my mobile phone (using the Snapcast app) but not the client I'm testing with.

If I play spotify to the librespotify stream, it plays on the client I'm testing with but not on the Snapcast app.

So, basically, each stream plays on a different combination of clients. 

Stream 1 might play on 1 and 3.

Stream 2 might play on 2 and 3.

Stream 3 might play on 1 and 2.

But none of the streams play on all clients, and which clients each stream does play on seems to be random.

**Comment by FlyingBollards** [comment]
Actually, I tried again to try and be more clear.

The first stream, to the default pipe, from Mopidy, plays to the Snapcast app on Android, but none of the Raspberry Pi Snapclients.

The second stream, the librespot pipe, plays to  all snapclients on the Raspberry Pis, but not to the Snapcast app on Android.

The last stream, and Airplay one, plays to no clients.

**Comment by FlyingBollards** [comment]
I made a video, I hope it helps.

The laptop mic was on.

You can see, when the Spoyify is playing, the clients are getting chunks.

But when Mopidy is playing, no clients are getting chunks.

When I connect the Snapcast app on the phone, it plays Mopidy audio. You can hear it feintly in the background, playing Oasis, while none of the clients are getting chunks.

Then when I connect Airplay, nothing happens anywhere.

https://youtu.be/KPCbupJfDyA

**Comment by FlyingBollards** [comment]
OK so this seems to be down to groups, and it seems that it's coming from the Snapcast Android App.

What I want is a bunch of streams, as I have in my conf file, that play to all clients.

But the Android app seems to prevent this. Because of groups.

It seems the app only has one group. I don't know how to add another. And groups seem to be a one to tone relationship between clients and streams.

So if a client belongs to one stream, it can't belong to another.

is there a way to configure groups so all streams play to all clients?

At the moment a client can only seem to belong to one stream or another.

**Comment by FlyingBollards** [comment]
So this is down to groups - I think it was my misunderstanding of how they work and everything works as intended.

Thanks for looking into the issues and helping me work it all out!

**Comment by badaix** [comment]
yep, that's it, every client is in exactly one group (by default all clients are in their own group), and to each group a stream is assigned (by default the first stream in the list). 
It's not possible to assign several streams to a group. You can configure all this with the Android App. The configuration might look a bit implicit

**Comment by tmigone** [comment]
Hey @badaix, stumbled upon this issue since I want to do pretty much the same thing. As far as I understand it then, there is no way to have clients playing from different sources? @FlyingBollards did you find any workaround?

**Comment by tmigone** [comment]
Can I have the clients switch group/stream with the API?

**Comment by badaix** [comment]
The clients play their group's stream, and the group's stream can be changed, and you can switch groups as well as streams using the API. The Android client for example relies completely on the API and can do all of this.

**Comment by tmigone** [comment]
Awesome, thanks for the answer. Fantastic piece of software by the way!
