### ISSUE TITLE
Simple way to modify the volume on the client side

### ISSUE THREAD

**Issue by mbrebion** [badaix/snapcast#502]
I've set up a multiroom configuration with three RPI's.
Each of them are associated with buttons and a lcd display and can thus, be operated on their own. 
My problem is that I want to be able to modify the volume of a client from the client side.
As some devices are based on a hifiberry mini amp, I can't rely on hardware volume control for this task. For the moment, I've made a script which is called whenever the volume control is used, and relies on telnet to ask the server to change the volume of the desired client. 
``
#!/bin/bash
telnet $2.local 1705 << EOF
{"id":8,"jsonrpc":"2.0","method":"Client.SetVolume","params":{"id":"$1","volume":{"muted":false,"percent":$3}}}
EOF
``

For some reasons, it appears to work half of the time and I still don't know why.

Is there a simpler solution to change the volume locally ? I'm mean without asking the server and without using hardware volume control ?

Thanks in advance

**Comment by FlyingBollards** [comment]
[https://play.google.com/store/apps/details?id=de.badaix.snapcast&hl=en](url)

I use the Snapcast app for Android.

You can see all the clients, and adjust their volume, on one screen.

**Comment by mbrebion** [comment]
Well, I would like a solution working within the terminal (a bash script) and which can be automatized.

**Comment by badaix** [comment]
No, there is no possibility to change the volume in the client, it must be looped over the server.
Your telnet solution should work, maybe a newline is missing at the end. Another approach would be using the http post interface with curl (same json requests using http post on port 1780)

**Comment by mbrebion** [comment]
Ok thank you,
I'm trying to get rid of the bash script and do it directly from python code using telnet lib.
