### ISSUE TITLE
"exception unknown codec ogg" When setting codec = ogg

### ISSUE THREAD

**Issue by Hergeirs** [badaix/snapcast#504]
As the title states. *snapserver* throws this error when setting
`code = ogg`
in /etc/snapserver.conf

Running on Archlinux. Installed from the AUR snapcast package.

**Comment by quantenschaum** [comment]
Same here using https://github.com/badaix/snapcast/releases/tag/v0.17.0 on Ubuntu 18.04.

Did you remove it in favour for opus and forgot to update the help text?

**Comment by badaix** [comment]
damn, it's a typo in the Makefile (`-DHAS_VORBISENC` vs `-DHAS_VORBIS_ENC`). The cmake builds will work. I will fix that...

**Comment by quantenschaum** [comment]
working again in 0.17.1
