### ISSUE TITLE
systemd fails to start snapserver

### ISSUE THREAD

**Issue by JayGatsby7** [badaix/snapcast#505]
new arm package - snapcast service fails to start

**Comment by badaix** [comment]
This might be due to
>   * General
    -debian scripts: change usernames back to snapclient and snapserver

please do `dpkg --purge snapserver` and install again

**Comment by quantenschaum** [comment]
The snapserver.service definition changed because the options are different now. Adjust them manually or purge and reinstall.

**Comment by JayGatsby7** [comment]
> This might be due to
> 
> > * General
> >   -debian scripts: change usernames back to snapclient and snapserver
> 
> please do `dpkg --purge snapserver` and install again

Thanks - That worked.  Appreciate your help and the great software.
