### ISSUE TITLE
Install man files when using CMake

### ISSUE THREAD

**Issue by PureTryOut** [badaix/snapcast#507]
When straight up using the Makefile, [the man file gets installed](https://github.com/badaix/snapcast/blob/master/client/Makefile#L134). However, this is not the case with CMake, and I can not find an option for it. Please also allow installing any documentation, like man files, when using CMake.

**Comment by vladdoster** [comment]
I can work on this if you want @PureTryOut

**Comment by badaix** [comment]
cmake doesn't have an install target at all right now. Why do you need this?

**Comment by PureTryOut** [comment]
I'm sorry for the late response. CMake most definitely does have an install target, I use it [in the Alpine packaging](https://git.alpinelinux.org/aports/tree/community/snapcast/APKBUILD#n40).

**Comment by badaix** [comment]
done: 579d422b7db2f1ef3dc645e63987b2df0e7478f4
