### ISSUE TITLE
Update F-Droid build (optionally provide Android downloads on release page?)

### ISSUE THREAD

**Issue by PureTryOut** [badaix/snapcast#508]
The current F-Droid build is [on the really old 0.7.0 version](https://gitlab.com/fdroid/fdroiddata/blob/master/metadata%2Fde.badaix.snapcast.yml#L24), and doesn't seem to work with modern snapservers anymore, at least not on my system. I'm not sure if you were the one that originally submitted it, but please update it so it's usable again.

**Comment by rcmcronny** [comment]
For Downloads have a look here:  https://github.com/badaix/snapdroid/releases

**Comment by PureTryOut** [comment]
Ah I didn't realize it was a separate repository, I'll move this issue there.
