### ISSUE TITLE
cannot set flac compression level

### ISSUE THREAD

**Issue by quantenschaum** [badaix/snapcast#509]
Using snapserver v0.17.1 binary release on Linux x64.

In `/etc/snapserver.conf` I tried setting (one at at time)

```
codec = flac:compression level:8
codec = flac:compression\ level:8
codec = flac:compression%20level:8
codec = flac:compressionlevel:8
codec = flac:compression:8
codec = flac:level:8
```

All of them result in `[Err] Exception: Invalid codec option: "compression level:8"`, but the help text says when setting `codec=flac:?`

```
Options for codec "flac":
  compression level: [0..8]
  Default: "2"
```

**Comment by badaix** [comment]
It's just the number: `flac:0` ... `flac:8`

Where levels 0-2 have a latency of ~26.1224ms
and levels 3-8 ~92.8798ms
Compression whise it should not really matter what level to use (8 will be slightly better than 0), all of them are lossless.

**Comment by quantenschaum** [comment]
:man_facepalming: OK, thanks. Would be nice, if the help text contained an example. The `Default: "2"` actually is an example, but that's not really clear. `flac:2` would be more explicit. I was comparing it to the opus options, where you need to write `BITRATE:`, which is not necessary having a single option only. 

```
Options for codec "opus":
  BITRATE:[6000 - 512000|MAX|AUTO],COMPLEXITY:[1-10]
  Default: "BITRATE:192000,COMPLEXITY:10"
```
