### ISSUE TITLE
No sound on snapclient RaspberryPi 3B with HiFiBerry DAC+

### ISSUE THREAD

**Issue by sturd** [badaix/snapcast#524]
I'm sorry if this is just a duplicate, but I _have_ searched the closed issues and have not found my answer.

I am using [this Docker project](https://gitlab.com/sturd/docker-snapcast) to launch a set of containers which host SnapServer (v0.17.1) and MPD with a shared pipe via a common mount.

My SnapClient (v0.17.1) is running on a Raspberry Pi 3B connected via WiFi to the local network.  The Pi is fitted with a HiFiBerry DAC+ which has been configured and tested to prove it works.  If I run `speaker-test -c 2`, I get the test tones playing through Left and Right alternatively.

`snapclient --list` returns;
```
0: null
Discard all samples (playback) or generate zero samples (capture)

1: default


2: sysdefault:CARD=sndrpihifiberry
snd_rpi_hifiberry_dacplus, 
Default Audio Device

3: dmix:CARD=sndrpihifiberry,DEV=0
snd_rpi_hifiberry_dacplus, 
Direct sample mixing device

4: dsnoop:CARD=sndrpihifiberry,DEV=0
snd_rpi_hifiberry_dacplus, 
Direct sample snooping device

5: hw:CARD=sndrpihifiberry,DEV=0
snd_rpi_hifiberry_dacplus, 
Direct hardware device without any conversions

6: plughw:CARD=sndrpihifiberry,DEV=0
snd_rpi_hifiberry_dacplus, 
Hardware device with all software conversions

```
When the Docker containers are up and running, I can `telnet` in to the SnapServer container via port `1705` and observe the `Client.OnConnect` event, proving that the connection has been established between client and server.

When I play music in MPD, I can call `cat mpdstatus/snapfifo`, on the Docker host, and see that data is being written in to the buffer by the MPD container.

Running `sudo tcpdump -nnSX port 1704`, on the Docker host, and on the Raspberry PI shows some traffic, but it's by no means the flood of packets I would have expected, with audio data streaming over the network.

I'm at a loss as to why there doesn't appear to be data being streamed over the network.  I should add, I have not installed PulseAudio on the Raspberry PI, is that something which must be explicitly added in order for SnapClient to work?

Thanks in advance,
Craig

**Comment by fuchsmich** [comment]
I don't have much to say about your snapserver. Maybe you could test the connection to your snapserver with some android phone running snapcast (snapclient) this way you could test, if there is audio data at all.

The default configuration for snapclient aims on setups _without_ pulseaudio.

If you run `snapclient` from CLI be sure to run them with the same privileges (user, group) as your startup code (init system) does.

**Comment by sturd** [comment]
I'll get that Android snapclient installed--I hadn't realised it could double as a diagnostic tool for the setup.

**Comment by sturd** [comment]
Just tried the Android client, connected it up to my server and attempted to play audio to it.  No sound coming from Android client either.

**Comment by sturd** [comment]
Going to close this issue as tested a self-built snapserver instance against the clients on my network and managed to play sound out of both with the `cat /dev/urandom > /tmp/snapfifo` command.  Will look elsewhere for answers as to why my Docker configuration is faulty.

**Comment by sturd** [comment]
Thanks very much for your time.
