### ISSUE TITLE
Exception: failed to open file "/var/lib/snapserver/server.json", permission denied (error 13)

### ISSUE THREAD

**Issue by c0da** [badaix/snapcast#526]
After upgrading from **0.15** to **0.17.1** I've got the following error while trying to start snapserver: 

``Exception: failed to open file "/var/lib/snapserver/server.json", permission denied (error 13)``

For some reason the owner/group was changed to **998**.**997**:

```
root@pand0ra:/tmp# ls -l /var/lib/snapserver/server.json
-rw-r--r-- 1 998 997 5650 Jan 12 01:15 /var/lib/snapserver/server.json
```

After changing file's owner and group to 'snapcast', everything worked as expected.

**Comment by fuchsmich** [comment]
Which distribution? My best guess: this is a problem about packaging. You should contact the maintainer of the package.

**Comment by c0da** [comment]
> Which distribution? My best guess: this is a problem about packaging. You should contact the maintainer of the package.

I'm using Debian 10 (buster). So far, I've always updated snapserver using the precompiled packages from the [release page](https://github.com/badaix/snapcast/releases/tag/v0.17.1).

**Comment by fuchsmich** [comment]
Ah ok, so you're in the right place but I'm the wrong person to answer cause I'm not too familiar with debian packaging.
A similar issue was mentioned [here](https://github.com/badaix/snapcast/issues/481#issuecomment-545149977).

**Comment by badaix** [comment]
maybe this was due to the `snapserver_` and `snapclient_` users that were there for some releases in-between.
