### ISSUE TITLE
Allow dynamically changing the snapclient hostname 

### ISSUE THREAD

**Issue by tmigone** [badaix/snapcast#527]
I don't think there is a way of doing this currently. Would be nice to be able to change the hostname to which the snapclient is connected to without restarting it.

**Comment by badaix** [comment]
I don't really understand what you mean. You want to change the server's hostname while a client is connected? Should work, since the client has already resolved the IP of the server.

**Comment by tmigone** [comment]
Sorry, I meant the target server to which the client is connected to. Say I start the client and it connects to IP 1.2.3.4, but then I want to change it to listen to another server with IP 5.6.7.8. Currently it's only possible to do so by restarting the client.

**Comment by badaix** [comment]
This is not possible. You maybe can start two clients, one connected to host1 and the other to host2.
