### ISSUE TITLE
Raspotify playback is too fast, sounds weird

### ISSUE THREAD

**Issue by nolsnols** [badaix/snapcast#529]
I have the latest Snapcast Server and Client (3 Raspberrys, 3,2 and B+)
I user Raspotify on all Clients and have one instance on the Snapcast Server with the output to the Snapcast Server.

Raspotify conf (/etc/default/raspotify):
`BACKEND_ARGS="--backend pipe --device /tmp/snapfifo"`

Snapcast Config is standard, nothing changed.

The spotify playback is working, but the songs are played faster than normal. It is  like  the speed is faster. The Raspotify playback to the audiojack  is working normal.

When I play a MPD stream like webradio, the speed is ok. Checked with a laptop playback at the same time.

My old config for Snapcast worked well. The sound was ok.
`SNAPSERVER_OPTS="-d  -s spotify:///librespot1?name=Spotify1&devicename=Snapcast`

**Comment by badaix** [comment]
The Spotify stream implicitly sets the Samplerate to 44.1kHz (the native Spotify rate), you should change the Samplerate of the fifo stream to 44.1kHz. otherwise it consumes the audio signal at 48kHz.

**Comment by nolsnols** [comment]
Thank you.
I have to change the samplerate in the /etc/snapserver.conf because the settings in etc/default/snapserver didnt change anything...but it works now.

**Comment by badaix** [comment]
yep `snapserver.conf`, as it is written in [docs](https://github.com/badaix/snapcast#configuration)

**Comment by scheleaap** [comment]
Just for reference, this issue shows how to solve this problem: https://github.com/dtcooper/raspotify/issues/355
