### ISSUE TITLE
Adding volume control using Phat DAC

### ISSUE THREAD

**Issue by web-sto** [badaix/snapcast#53]
Hello,

first of all thanks for the litte piece of magic work delivering after 30min of setup, what more than 2 days of pusleaudio & co. could not deliver. Great work!!!

I'd say I have a rather standard setup.

- Ubuntu server running snapserver & mpd
- 2 raspi clients running snapclient

Using the 3.5mm audio jack the setup on clients was running fine, with the issue of the well known bad quality of the sound using this output mode of a raspi. So I invested in 2 Phat DACs. The new setup run out of the box.

But, no volume control anymore possible. Some recherche told me this is normal behavior of this hardware. Well some more recherche introduced the ALSA plugin softvol to me being an option to try.

I managed to get this plugin to work, meaning I've got a volume control able to control volume of application except snapclient. (applying -s parameter pointing on the new plugin device).

Any help possible from the experts out there for a new user of snapcast?

Thanks in advance

STO

Some output:
pi@raspberrypi:~ $ snapclient -l
0: null
Discard all samples (playback) or generate zero samples (capture)
1: default
2: softvole
3: sysdefault:CARD=sndrpihifiberry
snd_rpi_hifiberry_dac, 
Default Audio Device
4: dmix:CARD=sndrpihifiberry,DEV=0
snd_rpi_hifiberry_dac, 
Direct sample mixing device
5: dsnoop:CARD=sndrpihifiberry,DEV=0
snd_rpi_hifiberry_dac, 
Direct sample snooping device
6: hw:CARD=sndrpihifiberry,DEV=0
snd_rpi_hifiberry_dac, 
Direct hardware device without any conversions
7: plughw:CARD=sndrpihifiberry,DEV=0
snd_rpi_hifiberry_dac, 
Hardware device with all software conversions

pi@raspberrypi:~ $ vi /home/pi/.asoundrc
pcm.!default    {
        type            plug
        slave.pcm       "softvole"
        }
pcm.softvole {
        type    softvol
        slave   {
                pcm     "sysdefault"
        }
        control {
                name    "softvolume"
                card    0
        }
}

**Comment by badaix** [comment]
The Snapclient can adjust the volume with it's build-in SW mixer. You can control it with the [Android App](https://github.com/badaix/snapcast/releases/download/v0.6.0/Snapcast_0.6.0.apk) or e.g. with this [Python client](https://github.com/happyleavesaoc/python-snapcast), see #29

**Comment by happyleavesaoc** [comment]
Just to be accurate, there are two pieces to that project:

1) Python-based control: This part adjusts the volume, mute, etc
2) Python-based client: This part actually connects to the server and plays music like the C++ and Android clients. Note that its based on the 0.5.0 beta.

**Comment by web-sto** [comment]
Thanks for the quick feedback.

As I'm planning a sort of Multi-room application not being keen running snapclient on android hardware, I was not aware what the android client provides. But at the end it is what I was looking for.

I even became aware of the server site server.json file. I suppose being a sort of the config file. I was able to achieve volume control playing with the parameters (snapserver not running), so android client would be necessary. Is this correct ?

As the little raspberry pi recently step into my technical live, of course python starts to get more space in my programming live, I will have a look on the python-based applications. 

Thanks.
