### ISSUE TITLE
Multi-instance with --soundcard option and ALSA channel mapping

### ISSUE THREAD

**Issue by eoware** [badaix/snapcast#533]
I am running two snapclient instances using --instance so that I can play two different streams to a 2-channel hifiberry amp set up in dual mono mode as described here:
https://www.hifiberry.com/docs/software/dual-mono-setup/

One instance has --soundcard 2 and the other instance uses --soundcard 3. My snapserver -l is below. When I set stream to the group one of them is in, it plays the stream to what I believe is just default which ends up being the unmapped audio. If I set stream to both, I get what sounds like both streams playing on the unmapped audio (as if I were running two instances to the same sound card). I can't tell if it's a mixing issue (although using aplay -D I can play sounds to either output independently with no issue), soundcard selection issue, or instance issue. I have verified in the logs that each process starts with the correct soundcard option. Here is my asound.conf:

```
pcm.hifiberry {
 type hw card 0
}

pcm.hifimain {
 type plug
 slave.pcm "dmixer"
 ttable.0.0 1;
 ttable.1.1 1;
 ttable.0.1 0;
 ttable.1.0 0;
}

pcm.hifialt {
 type plug
 slave.pcm "dmixer"
 ttable.0.0 0;
 ttable.1.1 0;
 ttable.0.1 1;
 ttable.1.0 1;
}

pcm.dmixer {
 type dmix
 ipc_key 1024
 slave {
  pcm "hifiberry"
  channels 2
 }
}

ctl.dmixer {
 type hw
 card 0
}
```

snapserver-l output
```
0: null
Discard all samples (playback) or generate zero samples (capture)

1: hifiberry


2: hifimain


3: hifialt


4: dmixer


5: default:CARD=sndrpihifiberry
snd_rpi_hifiberry_dacplus,
Default Audio Device

6: sysdefault:CARD=sndrpihifiberry
snd_rpi_hifiberry_dacplus,
Default Audio Device

7: dmix:CARD=sndrpihifiberry,DEV=0
snd_rpi_hifiberry_dacplus,
Direct sample mixing device

8: dsnoop:CARD=sndrpihifiberry,DEV=0
snd_rpi_hifiberry_dacplus,
Direct sample snooping device

9: hw:CARD=sndrpihifiberry,DEV=0
snd_rpi_hifiberry_dacplus,
Direct hardware device without any conversions

10: plughw:CARD=sndrpihifiberry,DEV=0
snd_rpi_hifiberry_dacplus,
Hardware device with all software conversions
```

**Comment by eoware** [comment]
I installed snapserver on the client and repointed at 127.0.0.1 to isolate everything to the one device, and I am still seeing the same result. If something is streaming to one, it plays on both channels and if something is streaming to both, it plays both streams on both channels together. It's like the --soundcard option isn't being applied for the instance.

**Comment by eoware** [comment]
I am going to try this with a different approach of setting up a simple python API to remotely change the balance to all left, all right, or balanced since I don't need both speakers playing different music at the same time, but I would still like to revisit this at some point because the original plan would have fewer moving parts.

**Comment by eoware** [comment]
And I am back to where I started. I switched from a pi zero w/ DAC to pi 3 with amp+, now I am going back to the zero with dac which has no alsa volume controls, which means I can't set the balance through ALSA. I know the option is 'soundcard' but all the code looks like it properly gets, sets, and uses a 'pcm device'. The only thing I could figure is maybe snapcast falls back to the default sound card because the pcm device is a plug instead of a card, but I can't find anywhere that would happen.

**Comment by badaix** [comment]
sound card it just the name (when I was young, these things were called sound cards :wink: ), any PCM device should work. I have no clue what's wrong with your setup. When I find the time, I will try to reproduce it.

**Comment by eoware** [comment]
Right, I was just saying the option is called 'soundcard', so I thought maybe me trying to use a PCM device was incorrect usage, but I could tell from the code that it's all PCM device based. This is kind of kicking my butt and I'm a little annoyed that the card doesn't have PCM volume controls, but it's my fault for not reading the specs. It's also my fault for not running these last couple zones as home runs, but I was running behind and the drywall was going up. Snapcast is working rock solid with the other 99% rest of my setup that uses a dedicated a/v matrix/amp to manage things like balance and volume -- I am so glad I found this project. I went from running and managing a bunch of pi's all running their own librespot, shairport, mopidy, etc. to all of that being managed on the snapcast server, with the pi's being simple clients. Management is SO much easier.

**Comment by eoware** [comment]
I am back in business using the softvol ALSA plugin, configured as described here: https://support.hifiberry.com/hc/en-us/articles/205377202-Adding-software-volume-control

I think this will actually work better for me because it is more analogous to how I control my matrix device -- using balance to switch between speakers in a two-speaker zone -- so if you aren't ever able to reproduce, feel to close this issue.
