### ISSUE TITLE
Stream definition with unnamed parameter, quotes, ampersands, etc.

### ISSUE THREAD

**Issue by eoware** [badaix/snapcast#545]
Could an example be provided of how to turn the mplayer command that plays directly to the snapserver pipe in the examples into a stream definition?

I am trying to create a process-based stream like this:
stream = process:///mplayer&name=tv-wthr&novideo&ao="pcm:file=/dev/stdout"&channels=2&srate=48000&af="format=s161e"&cache=8000&cache-min=2&"http://myurl.com/example?test=abc&test2=def"

Snapserver doesn't even recognize it or try to load it as far as I can tell. I'm not 100% sure how to specify unnamed parameters like the url or if parameters with quotes, equal signs, ampersands, etc. need to be escaped so that snapserver doesn't think they are part of the process command list.

**Comment by badaix** [comment]
please separate the parameters with a `?`. Command line parameters are passed with `params`. I've just tried this simple case:
```
stream = process:///bin/cat?name=Cat&params=/home/johannes/Musik/test.wav
```
I don't know how space separated params are behaving. Maybe you have to put it in quotes.
