### ISSUE TITLE
Music plays to fast

### ISSUE THREAD

**Issue by warllo54** [badaix/snapcast#552]
My audio is playing too fast and is garbled. Not sure what I have configured wrong. I am using snapserver, snapclient and mopidy with iris. Here are my configs, hoping someone can help. Thanks in advance!

Mopidy Config related to snapcast:

https://pastebin.com/1yHUwea7

Snapserver config:

https://pastebin.com/gRWh7yB4

**Comment by herrwusel** [comment]
The sample rate seems to be different - mopidy has 48k and snapserver has 44.1k.

**Comment by badaix** [comment]
yes, sample rates are different, although in this case audio should be playing too slow

**Comment by warllo54** [comment]
Thanks for the feedback. I updated the configs so the sample rates matched, however my issue still persisted after restarting Mopidy and Snapserver so I removed both and started fresh and everything worked. Thanks for your help!
