### ISSUE TITLE
Faster volume changes / muting

### ISSUE THREAD

**Issue by SeanDS** [badaix/snapcast#553]
First of all, excellent work with Snapcast - I love it.

I wonder if it's possible to make volume changes faster on clients, like Sonos where it's effectively instant within human perception. Right now changing the volume on the server leads to a delay of around a second, presumably because of the buffer. I guess Sonos must implement some additional control protocol on top of their streaming protocol, which sends volume change / mute requests to clients immediately, bypassing the buffer. I wonder if this would be possible with Snapcast too.

**Comment by badaix** [comment]
What control client are you using to change the volume? Snapcast does instantly change the volume. Up to version 0.16 there were some milliseconds delay when changing volume of large groups.

**Comment by SeanDS** [comment]
Ah, interesting, you are right. Using the Snapcast mobile app I am able to adjust volume instantly, but in Mopidy Mobile (the client I normally use) I am not - there is a delay. So it looks like indeed Snapcast is instant and the problem is with Mopidy Mobile. Thanks for clearing that up, I'll close this.

**Comment by badaix** [comment]
Right, mopidy will change the stream's volume and the stream is played delayed by 1s, so also the volume change will be delayed.

**Comment by SeanDS** [comment]
Makes sense. Is there an easy way for external applications (e.g. Mopidy Mobile) to tell Snapcast to change or mute master volume? I could investigate submitting a patch to Mopidy Mobile.
