### ISSUE TITLE
Just a notification about HifiberryOS

### ISSUE THREAD

**Issue by fuchsmich** [badaix/snapcast#555]
Got a notification from Hifiberry about their OS, which includes snapcast:

https://www.hifiberry.com/hifiberryos/

https://github.com/hifiberry/hifiberry-os

greetings, Michael.

**Comment by badaix** [comment]
I'm aware of it. Smart move by HifiBerry ;)
As snapcast is only a small piece of a multiroom audio solution, I'm excited to see if HifiBerry OS will become an end user ready distribution.

**Comment by fuchsmich** [comment]
Congrats to this. :)

Just out of curiosity: did they contact you before they included snapcast?

**Comment by badaix** [comment]
No, they didn't contact me
