### ISSUE TITLE
Feature request - unhide debug option

### ISSUE THREAD

**Issue by artmg** [badaix/snapcast#561]
Hi, I see in the [snapclient source](https://github.com/badaix/snapcast/blob/master/client/snapclient.cpp#L91) there is a hidden debug option, which is currently only mentioned in a changelog, not in any docs.

Could I suggest that this option be unhidden, so it appears when running `snapclient --help` - that way people will know it is there :)   Thanks

**Comment by badaix** [comment]
done in a2311df
There are the client settings:
* `--logsink`: `null`, `system`, `stdout`, `stderr`, `file:<filename>`
when left empty (default): if running as daemon `system` else `stdout`
* `--logfilter`: `<tag>:<level>[,<tag>:<level>]*`, with tag = `*` or `<log tag>` and `level` = `trace`, `debug`, `info`, `notice`, `warning`, `error`, `fatal`
default: `*:info`, chunk statistics can be viewed with `Stats:debug`

For the server there are the same options available in `snapserver.conf`:
```
# Logging options #############################################################
#
[logging]

# log sink [null,system,stdout,stderr,file:<filename>]
# when left empty: if running as daemon "system" else "stdout"
#sink = 

# log filter <tag>:<level>[,<tag>:<level>]* 
# with tag = * or <log tag> and level = [trace,debug,info,notice,warning,error,fatal]
#filter = *:info
#
###############################################################################
```
