### ISSUE TITLE
soxr dependency missing from build instructions

### ISSUE THREAD

**Issue by maweki** [badaix/snapcast#563]
In my ansible deployment I build (at least for Fedora) `snapclient` from source. I get a missing `soxr.h` error. I think the `soxr-devel` package (and corresponding for debian) is missing from the build instructions.

This must have been added as a dependency for 0.19.

**Comment by badaix** [comment]
Fixed: 3a8023ab9348f4bd78ab98749753e2eb3c2824ce

**Comment by nmeum** [comment]
Are the benefits of the soxr dependency document somewhere? Currently packaging snapcast for a distro and wondering whether or not it should be enabled.

**Comment by badaix** [comment]
Well, documentation is a general flaw of Snapcast.
Purpose is to resample the signal on the client before it's sent to the DAC. It's used on Android where only 16bit is supported and to guarantee a constant latency on pre-Android 8 devices by using the device specific low-latency sample rate.
It might be useful on non-Android devices for exotic or really cheap DACs that do not support certain sample rates (I have an USB DAC "Behringer UCA202, only supporting 32kHz, 44.1kHz and 48kHz, but for example no 96kHz) and heard about DACs that can only do 44,1kHz.
So it's a not too important feature, if the soxr dependency is causing pain or headaches from packaging point of view, it's ok to leave it out. Most users will not notice if it's missing.

**Comment by xabolcs** [comment]
_(Behringer UCA202 for the win! :heart_eyes: They are doing awesome work plugged into my `ath79` based routers :sunglasses: )_
