### ISSUE TITLE
Snapcast build failure on FreeBSD

### ISSUE THREAD

**Issue by nick-orton** [badaix/snapcast#565]
The codebase is currently missing the rc.d/ file that the Makefile expects for installation.

    $  doas gmake TARGET=FREEBSD install
    echo BSD
    BSD
    install -s -g wheel -o root -m 555 snapserver /usr/local/bin/snapserver
    install -g wheel -o root -m 555 snapserver.1 /usr/local/man/man1/snapserver.1
    install -g wheel -o root -m 555 ../debian/snapserver.bsd /usr/local/etc/rc.d/snapserver
    install: ../debian/snapserver.bsd: No such file or directory
    gmake: *** [Makefile:126: install] Error 71

**Comment by badaix** [comment]
Could be fixed: dac7c8f
I cannot test, my FreeBSD VM got lost

**Comment by nick-orton** [comment]
I can confirm that this fixed it.  Thank you for the fast response!
