### ISSUE TITLE
Snapcast (client) and Stereo upmixing to 5.1

### ISSUE THREAD

**Issue by steals** [badaix/snapcast#566]
I'm trying to configure upmixing stereo audio stream received by snapclient into 5.1 audo stream using Alsa. For that purpose I've created corresponding pcm device in asound conf. (Actually the same asound.conf I use last several years without any issues on ArchLinux, but on LibreELEC it doesn't work)

I've also confirmed that upmixing pcm device works with "speaker-test -D upmix_20to51 -c 2" command.
But when I start snapclient and specify "upmix_20to51" as sound card (snapclient -s upmix_20to51) the sound doesn't go through this device and go through the pcm.default one.
In the snapcast log I can see the following error: "soundcard "upmix_20to51" not found"

Any suggestions what can be wrong?

**Comment by badaix** [comment]
What is the output of `snapclient -l`?

**Comment by steals** [comment]
`snapclient -l` doesn't show this custom `upmix_20to51` pcm device as well as `aplay -l`. But still  I can hear sound if I manually specify this device in speaker-test

**Comment by badaix** [comment]
snapclient can only use devices that are listed in `snapclient -l`, which should be the same as `aplay -l`. No idea how `speaker-test` is working.

**Comment by steals** [comment]
The original issue was fixed by adding hint.descrtiption attribute into custom the pcm device. After that modification new pcm device appeared in the list of `aplay -L` and snapclient is able to use it now.

**Comment by StuartIanNaylor** [comment]
@badaix Anychance you might support more channels to natively send 5.1?
