### ISSUE TITLE
how to redirect all sound to snapcast client

### ISSUE THREAD

**Issue by vinniec** [badaix/snapcast#568]
This is not a bug in your program, it's me who can't make it work, so I apologize in advance for my inability.

I'll explain the situation quickly:
I have a pc from which I access remotely (wifi, same network) with vnc through an android tablet, but vnc doesn't share the audio.
I would like to use snapcast because it gives me the possibility to use multiroom in the future and it seems very smart to me because I like music.
I installed the app on tablet (I should ask fdroid people to update it instead of be forced to using the playstore version) and it works, I tried to follow your instructions with mpv and I hear the audio (it goes a bit slow but it's early to try to understand why).
So I thought I would like to configure snapcast to play all the sounds of the system and so I did these operations:
1) added at the end of ~/.profile `export PULSE_LATENCY_MSEC=60` to export the system variable. (Actually it seems that the variable is not loaded at startup the same, anyway for now for a test I just can use the export command)
2) give these two commands (they are executed without any problem):
`pacmd load-module module-pipe-sink file=/tmp/snapfifo sink_name=Snapcast format=s16le rate=48000`
`pacmd update-sink-proplist Snapcast device.description=Snapcast`
3)this is my /etc/default/snapserver: 
```
START_SNAPSERVER=true
SNAPSERVEcR_OPTS="-d -s pipe:///tmp/snapfifo?name=Snapcast&mode=read"
```

When I try to play an audio, however, I don't hear anything (even if mpv launched with the parameters of your example continues to work good).
I forgot to tell you that I use Kali linux (which is a derivative of Debian), so I think the audio server I use is pulse.

**Comment by herrwusel** [comment]
I remember that I wanted to achieve something similar but just dropped the idea. This is one of my [booksmarks](https://schneefux.xyz/tech/audio-output-to-input/). Maybe it's helping you - especially the [alsa monitor source](https://wiki.archlinux.org/index.php/PulseAudio/Examples#ALSA_monitor_source).

**Comment by badaix** [comment]
In recent versions the input stream is configured in `/etc/snapserver.conf`, the `-s` on command line will be ignored. Also you have a typo in your `/etc/default/snapserver`: `SNAPSERVEcR_OPTS`

**Comment by badaix** [comment]
closing ticket due to no response

**Comment by vinniec** [comment]
sorry, I know that is not really good but In this weeks I had not time, I tried to making other attempts but without success. For me is not problem if leave the issue closed, but if it's good for you, when I have time, i can continue to update here the progress

**Comment by uSpike** [comment]
Similar to https://github.com/badaix/snapcast/issues/511#issuecomment-570462437 ?

**Comment by badaix** [comment]
@vinniec did you solve it? Again: `SNAPSERVEcR_OPTS="-d -s pipe:///tmp/snapfifo?name=Snapcast&mode=read"` will not work, you have to add/edit the stream in your `/etc/snapserver.conf`

**Comment by vinniec** [comment]
I try thisnight and I'm sorry, but I haven't been able to turn on the computer for three weeks I think :|

**Comment by vinniec** [comment]
I put this line `stream = pipe:///tmp/snapfifo?name=Snapcast&mode=read` in `/etc/snapserver.conf`.
2) I launched snapserver on pc and connected the other devices as clients 
3) if I start this command I can hear the music `mpv ~/Musica/example_file_MP3_700KB.mp3 --audio-display=no --audio-channels=stereo --audio-samplerate=48000 --audio-format=s16 --ao=pcm --ao-pcm-file=/tmp/snapfifo`.
4) but if I run this other command I don't hear anything `mpv ~/Musica/example_file_MP3_700KB.mp3`.

I think I missing something in the server configuration, probably I need to say somewhere to redirect all the audio to snapcast

**Comment by TekniskSupport** [comment]
You need to follow the guides from 
https://github.com/badaix/snapcast/blob/master/doc/player_setup.md#alsa
or 
https://github.com/badaix/snapcast/blob/master/doc/player_setup.md#pulseaudio
(depending on if you use pusleaudio or alsa directly)

**Comment by vinniec** [comment]
Okay, I ran some tests, and this time it looks good:
1) I added this line `stream = pipe:///tmp/snapfifo?name=Snapcast&mode=read` to the file `/tmp/snapserver.conf`.
2) executed these commands:
`pacmd load-module module-pipe-sink file=/tmp/snapfifo`
`pacmd load-module module-combine-sink slaves=0,fifo_output`
`pacmd set-default-sink combined`
3) started `snapserver` and connected clients
4) I can hear sound

somethimes the two clients lose synchronization but after a bit they resume it, is there any way to improve performance at the expense of quality?
