### ISSUE TITLE
Video/audio synchronization

### ISSUE THREAD

**Issue by vouzico** [badaix/snapcast#57]
Hi all,

thanks for this great add-on, I had been looking for that for months!
I am running a media server on the following config:
Media server -> pulseaudio -> snapserver -> network -> snapclient

Besides issue #52 (I just need to remove the /tmp/snapfifo file and restart pulseaudio at the beginning of the session to make everything work), I still have the following issues: 

Playing music is fine and perfectly synchronized, but whenever I play a video 
1) there seems to be a sound distortion, the pitch is much higher than usually (setting a fixed bitrate in the media server to match snapserver's might help?)
2) There is a lag of a couple of seconds which makes it impossible to look at the video if there are dialogues

I'd like to keep a consistent config for my media server for both video and audio so helping me resolve these two issues would be awesome.

**Comment by badaix** [comment]
Hi, I'm afraid that `Snapcast` is not meant to be used to play video and audio in sync. There is some random but small and constant delay when reading from the pipe and a (by default) 1000ms second buffer (= delay) on the client. 
For audio only this is not an issue, you will only notice it when trying to keep in sync with video :wink:

**Comment by datamaskinen** [comment]
I understand that but i can not stop thinking about how much i would want snapcast to as well manage the video/screen casting with sync.... to have video output device in the same way as i have snapcast output device in kde (pulseaudio) list and synced with audio streamed to all smal screens in the house would be so madly nice..... 

is there a other project out there that does exactly what snapcast does but for streaming the video/screen.... and if that exist can that be synced with snapcast audio?
