### ISSUE TITLE
Add stream for URL (WebRadio)

### ISSUE THREAD

**Issue by dmckminard** [badaix/snapcast#570]
Hello,

I would like to be able to add, via the Snapcast API and the `Stream.AddStream` method, the **URL of a stream**.

This could easily **read WebRadio from a given url** (http://129.122.92.10:88/broadwavehigh.mp3 for example) **directly thanks to the API**, indicating the URL of the WebRadio in the JSON frame.

This would allow, thanks to the `Stream.RemoveStream` method to easily add and remove WebRadio via the API.

Is it possible ?

If so, what parameters should we indicate in the **streamUri field**?

Thank you !

**Comment by badaix** [comment]
I've never used the `Stream.AddStream` and `Stream.RemoveStream` methods, but with help of the [player setup guide](https://github.com/badaix/snapcast/blob/master/doc/player_setup.md), this seems to work quite well:
Add in `snapserver.conf` in the `[stream]` section (this should also be possible using the `Stream` RPC command):
```
stream = process:///usr/bin/mpv?name=Webradio&sampleformat=48000:16:2&params=http://129.122.92.10:88/broadwavehigh.mp3 --no-terminal --audio-display=no --audio-channels=stereo --audio-samplerate=48000 --audio-format=s16 --ao=pcm --ao=pcm:file=/dev/stdout
```
Of course, you need to have `mpv` installed.

**Comment by badaix** [comment]
interpreting the :+1: reaction as the problem is solved
