### ISSUE TITLE
5.1 audio transmission

### ISSUE THREAD

**Issue by GlebOlden** [badaix/snapcast#571]
Can I use Snapserver to transmit audio in 5.1 format to several snapclients? Transmit to different channels (front left and right, center, rear left and right, LFE). The idea is to make a wireless home theater. Is it possible?

**Comment by badaix** [comment]
I've only tested with 1 and 2 channels, you probably have to use PCM codec (i.e. not FLAC, ogg or opus) and remember that the audio signal will have a latency of at least 400ms and might not be in sync with video.

**Comment by GlebOlden** [comment]
OK, thanks! I have already tried playing video with audio streaming via snapcast server in stereo mode. The audio delay is really there. I used VLC where I was able to configure the audio delay settings. As a result, the audio was synchronized with the video.

I will try to do as you say with multi-channel sound.

**Comment by lucianm** [comment]
Just an idea, if such a thing might be implemented, additionally to multichannel PCM, a passthrough mode would be very useful if that is even possible with the snapcast concept, where the snapclient would then pass the encoded format through to the remote SPDIF or HDMI for decoding.
