### ISSUE TITLE
Groups not working

### ISSUE THREAD

**Issue by sickpig89** [badaix/snapcast#572]
Hi badaix :)

First of all, thank you for all your great work you are doing here. It is amazing that nearly everything works flawlessly - even if you are not familiar with linux like me.

So i am running snapserver on a Rpi4 (and have 3 pi zeros with snapclient in other rooms) and i cant manage to have multiple groups for the clients. 

When i look at the image of the snapdroid app, i see multiple groups listed. when i open my snapcast app on android i only see one group which all clients are connected to. With the app i cant create more groups or reassign clients. I achieve this with mopidy-iris (but this is not the way i want to go).
So i read about SNAPSERVER_OPTS and i added one line of code as shown below. But even after i added it, i only get one group. 

Is there a way to add, lets say, one group per stream per default so i can listen to different streams in different rooms without the need of iris?

version: snapserver v0.17.1

my /etc/snapserver.conf:
```
[stream]
stream = airplay:///shairport-sync?name=Airplay&devicename=Multiroom
stream = spotify:///librespot?name=Spotify&bitrate=320&devicename=Multiroom
stream = pipe:///tmp/snapfifo?name=Mopidy
```

my /etc/default/snapserver:
```
SNAPSERVER_OPTS="-s spotify:///librespot?name=Spotify -s airplay:///shairport-sync?name=Airplay -s pipe:///tmp/snapfifo?name=Mopidy
```
(in the config examples here is and -d option shown, but when i add it, my snapserver wont even start)

I hope i did not forget anything and you can help me to have multiple groups per stream so i can listen to different music on different roooms without the need of the mopidy frontend (which is quite annoying on mobile).

**Comment by mjvotaw** [comment]
I've been working through some similar issues, so I might be able to lend you a hand. 

So your issue is that you only see one group that you're able to assign a stream to, but you'd like to have one group for each client, so you could, for instance, listen to airplay on one, and spotify on another? Or are you trying to achieve something more complex?

I believe, by default, Snapcast should create separate groups for each client that you create, but that sounds like maybe that didn't happen in your case. The group configuration is stored in /var/lib/snapserver/server.json, or possibly /var/lib/snapserver/.config/snapserver/server.json
If something went weird with your setup, you could try deleting this file and letting Snapserver regenerate it.

**Comment by miLORD1337** [comment]
You could try to remove clients from the group, they should be assigned to a new group automatically. Besides the group name there is a gear symbol. When you press that, you can remove the tick from the tick box of your client, which should be assigned to a different group. Then go back and (hopefully) find it in another group, which you can then rename.

**Comment by sickpig89** [comment]
So i managed to resolve my issue in following way: 

- tried out mjvotaw solution: delete server.json -> no new file could be generated automatically by snapserver. i figured around for about 2h but i have not seen any solution to fix my problem.
- fresh install of os (raspbian buster lite)
- installed new version of snapserver / snapclient (0.19), librespot and shair-sync
- removed android app & reinstalled it form appstore

-> everything working like a charm now.

i can now assign different streams through android or mopidy-iris without any problems.
fo example now i am playing via spotify on the balkony and via airplay in my office room.

what i try next: there must be some way for the client to get assigned to any stream which is active. currently i have to change the stream manually via app. but in case just one stream is playing i want all of my clients to play this streams automatically. any suggestions?

thanks to you all :)

**Comment by miLORD1337** [comment]
I'd write a script that is watching both streams. If one is empty for a longer period of time, it could issue an JSON-RPC Get.Status command to the server to get all clients and then Group.SetClients to add them to the group with the running stream. There is a python 3 implementation for snapcast control [here](https://github.com/happyleavesaoc/python-snapcast/), that could get you started.

**Comment by badaix** [comment]
I guess @mjvotaw did something similar in #569
