### ISSUE TITLE
Popping sound on client every 15 - 20s

### ISSUE THREAD

**Issue by lucianm** [badaix/snapcast#573]
Hello,

first of all thanks for this awesome software!
I do not know if this is snapcast related, or just the hardware of my client (RPI3 + Hifiberry AMP2 running latest snapclient v0.19.0 over latest DietPi distro, for now connected via WiFi to my Fritzbox router), but sometimes after listening to mopidy streams for a while, one can hear loud pops in the speakers like every 15 - 20s, really annoying. I then stopped the snapclient service and started the client in a Putty session to look at the output, which I pasted in this [Gist](https://gist.github.com/lucianm/b25a385bda821555e9ca282b244f6399). Could you tell if those -1 values printed could indicate something related to what I'm hearing? I've peeked in the code and to me those values of age.count() or miniBuffer_.median() look like it could be related to re-synchronizing the stream.

For now, my other clients are an Android tablet which for sure did not experience this at that time, also connected via Wifi, then a snapclient running on the NAS where also the snapserver is running, with an optical SPDIF routed to the livingroom AV receiver, also not experiencing this. My plan is to add few more raspberries which I would mainly connect to LAN, but I thought there should be no problems over WiFi either, right?

The other possibility would be a hardware issue with my Hifiberry AMP2, I've read others had that too and the manufacturer is aware of that, they're replacing them, or I could to it at the online store I bought it. But I wanted to ask for your opinions first. What do you think?

**Comment by badaix** [comment]
the -1's are looking good. In the last column you can see how many sample are inserted (duplicated) or removed, looks like ~5 samples every 30s, so in 30s 1440005 samples are played instead of 1440000. This will not cause loud pops. I suggest to try a different player, e.g. `aplay` to check if it's hardware related.

**Comment by lucianm** [comment]
Thanks for the feedback, indeed, I managed to let an internet radio stream play in mpg123 all night at reasonable, not at all too loud volume in the kitchen all night long, and in the morning it was popping again, so this is as suspected, not snapcast related.
