### ISSUE TITLE
Advise airplay software version requirements

### ISSUE THREAD

**Issue by brunosmmm** [badaix/snapcast#575]
As far as I can tell, commit 6ad6467e73601d64375180fde79238d1f37f2c77 introduces the usage of the ```--use-stderr``` parameter when calling ```shairport-sync```. This caused my server configuration to fail when I updated to 0.19 because I was inadvertently using a manually built older version of ```shairport-sync``` built as per the instructions in the README, which did not have support for such a parameter.

**Comment by badaix** [comment]
Hi, seems that this was introduced with [version 3.3](https://github.com/mikebrady/shairport-sync/releases/tag/3.3) (I'm not able to test it), player setup section is updated accordingly: 7e47207
