### ISSUE TITLE
Setting sound card argument with daemon setting fails

### ISSUE THREAD

**Issue by hazardlabs** [badaix/snapcast#577]
I've using an alsa equaliser plugin on my Hifiberry setup, running on a Pi zero, Raspbian Buster and V0.19.0 Snapcast (client and server, server on a different pi) .

If I run `snapclient -s 1`,  its works as expected and I'm very happy with the result.

I then added `-s 1` to my /etc/default/snapclient file, 

`START_SNAPCLIENT=true`
`SNAPCLIENT_OPTS="-s 1"`

However, the audio stream sounds as if it is bypassing the equaliser plugin.

If I run 'snapclient -s 4', I get the same result as the service as it is directly accessing the hifiberry dac.

Now, if I run:
`snapclient -daemon -s 1`
I get the result where the equaliser is bypassed.

Kill it and run
`snapclient -s 1`
Everything works as expected.

Is there something when running as a daemon that causes this behaviour?

Output of `snapclient -l` below:
0: null
Discard all samples (playback) or generate zero samples (capture)

1: default

2: plugequal

3: equal

4: sysdefault:CARD=sndrpihifiberry
snd_rpi_hifiberry_dac, HifiBerry DAC HiFi pcm5102a-hifi-0
Default Audio Device

5: dmix:CARD=sndrpihifiberry,DEV=0
snd_rpi_hifiberry_dac, HifiBerry DAC HiFi pcm5102a-hifi-0
Direct sample mixing device

6: dsnoop:CARD=sndrpihifiberry,DEV=0
snd_rpi_hifiberry_dac, HifiBerry DAC HiFi pcm5102a-hifi-0
Direct sample snooping device

7: hw:CARD=sndrpihifiberry,DEV=0
snd_rpi_hifiberry_dac, HifiBerry DAC HiFi pcm5102a-hifi-0
Direct hardware device without any conversions

8: plughw:CARD=sndrpihifiberry,DEV=0
snd_rpi_hifiberry_dac, HifiBerry DAC HiFi pcm5102a-hifi-0
Hardware device with all software conversions

Any hints are kindly appreciated.

**Comment by fuchsmich** [comment]
I guess it's because alsa is configured for your current user (e.g. when you run `snapclient -s1`).

If you run snapclient as daemon it usually runs as different user and thus can't use your .asoundrc.

**Comment by hazardlabs** [comment]
Ah, that sounds like a good call.

I'll move my alsa config and see what the result is.

**Comment by badaix** [comment]
seems to be solved
