### ISSUE TITLE
Feature request: Modern scalable web client

### ISSUE THREAD

**Issue by badaix** [badaix/snapcast#579]
It's almost not possible to configure groups and streams without using [Snapdroid](https://github.com/badaix/snapdroid). 
There are Web frontends available which are using the JSON-RPC Api (via telnet or Websockets), there is also an example Web UI shipped with Snapcast (in `server\etc\interface.html`), which is a fork of the [snapcast-websockets-ui](https://github.com/derglaus/snapcast-websockets-ui), but there is no modern, scaleable Web UI available that looks equally good on a PC as well as on mobile phones.
Such a Web UI would enable the control of Snapcast on iOS, Android, Phones, and Tablets.

The UI could look similar to Snapdroid:

![Snapcast for Android](https://raw.githubusercontent.com/badaix/snapcast/master/doc/snapcast_android_scaled.png)

**Comment by mjvotaw** [comment]
If you're looking for help with this, I've been working on and off (mostly off) on a web client for a lot of these same reasons. (I hate having to modify the server.json by hand any time I add/change a client).

**Comment by badaix** [comment]
Thanks for the offer, Michael :)
I had some days off last week and used the time to learn some typescript and started creating a web client [Snapweb](https://github.com/badaix/snapweb). 
It's already usable, some code cleanup is missing (e.g. returning a `promise` when sending a request) and hiding/deletion of offline clients is also missing yet.

**Comment by mjvotaw** [comment]
Oh, even better. I'll take it for a spin.
