### ISSUE TITLE
Bluetooth connectivity?

### ISSUE THREAD

**Issue by ringzer** [badaix/snapcast#58]
Do you know if there is any way you could connect a bluetooth speaker to a RPi running Snapcast? I know snapcast generates a temp file to pipe the audio to which is consumed by a snapcast client. But could you pipe to that file as well as whatever is required to pipe to bluetooth?

**Comment by badaix** [comment]
Do you want to connect bluetooth speakers to your Snapclient Raspberry or do you want to turn your Snapserver into a "virtual bluetooth speaker"?

**Comment by ringzer** [comment]
I'm not exactly sure what you mean by a virtual bluetooth speaker but let
me explain my setup and what I would like to do.

I have a Pi (#1) in my kitchen running a snapcast server and client. I have
another Pi (#2) in my living room running a client do I have multi room
music playing which is great.

I would now like to be able to connect a bluetooth speaker to my setup so
that I can have music in the garden.

So the change in my limited understanding of Bluetooth and snapcast is
either

#1 have the server pipe to the Bluetooth audio output or

#2 have the client take the current temp file audio and distribute it to
the 3.5mm audio output and Bluetooth output.

Hopefully this is fairly straight forward and doesn't need any major
development.

Thanks

**Comment by badaix** [comment]
I think the bluetooth speakers should be somehow connected to the server (don't know how (Google :wink:). Parallel to Snapcast). Whatever you do, they will not be in sync with the Snapclients, as bluetooth introduces it's own latency that can't be controlled by Snapcast. 
See also [here](https://github.com/badaix/snapcast/issues/50)

**Comment by ioangogo** [comment]
There may be a way to get this program to be tricked into passing the sound through Pulse audio allowing you to send it to a bluetooth speaker, otherwise i dont know
