### ISSUE TITLE
Feature request: Command line client

### ISSUE THREAD

**Issue by badaix** [badaix/snapcast#580]
It's almost not possible to configure groups and streams without using Snapdroid.
It would be very convenient to have a command line client to control snapcast from the console.
Could be an ncurses client or some hand crafted python client using the Websockets JSON RPC API

**Comment by klundry** [comment]
I would love to have a command line client for using in scripts or with my terminal dashboard.

**Comment by badaix** [comment]
Me too, but I don't have time and it seems that no one else is keen enough to implement command line client.

**Comment by klundry** [comment]
No worries. I don't have the skill to implement one or the time really. Maybe someone will tackle it in the future. 

In the mean time would it be possible to add some curl command examples for controlling through json rpc to the documentation? I'm having a heck of a time getting a valid curl http post command.

**Comment by tremby** [comment]
I have written a very alpha client in nodejs to control volume. It's not very feature-complete but I've been using it for months. Currently it gives too much debug output, so I generally start it with `2>/dev/null`. It becomes unresponsive once in a while (maybe every few weeks on average, possibly when the sever restarts?), at which point I restart it.

https://github.com/tremby/snapmixer

F1 or ? for help.

Patches welcome.
