### ISSUE TITLE
snapclient name fingerprinting is brittle in containerized environments — which breaks snapserver grouping

### ISSUE THREAD

**Issue by zaneclaes** [badaix/snapcast#581]
I run several `snapclients` and a single `snapserver` in a Kubernetes environment at home. In this context, each pod is given a new hostname, IP & mac address upon restarting. This appears to break the `snapserver`s ability to fingerprint a client, thereby creating a new entry in `server.json` for every pod restart. It also results in client names like `audio-family-room-mpjs6` (the pod name). AFAICT, there are no CLI flags which would avoid this problem (please correct me if wrong).

My proposed solution would be to add a `snapclient` flag `--name` which allows me to uniquely identify the client which is connecting, overriding the built-in fingerprinting and assigning that name to the client (also overwriting any existing client of that name).

**Comment by badaix** [comment]
I think ` --hostID` is what you are looking for

**Comment by zaneclaes** [comment]
> I think --hostID is what you are looking for

Sure enough! Thanks. I overlooked this due to the term `host` being overloaded in the docs — referring at one point to the host which the client connects to, and in this case to the host ID of the client which is doing the connecting. Confirmed working after a couple pod restarts :)
