### ISSUE TITLE
[question] Add streaming url as source?

### ISSUE THREAD

**Issue by herrwusel** [badaix/snapcast#583]
Is it possible? I thought I read about it in one of the issues but can't find it anymore.

Since I listen to only two radio stations I want to add their opus streams directly as source in snapsever.

**Comment by badaix** [comment]
It's not natively supported, but you can use a process stream: #570

**Comment by herrwusel** [comment]
Thanks! I couldn't find it...
With: 
```
stream = process:///usr/bin/mpv?name=Dradio&sampleformat=48000:16:2&params=https://st01.sslstream.dlf.de/dlf/01/128/mp3/stream.mp3 --no-terminal --audio-display=no --audio-channels=stereo --audio-samplerate=48000 --audio-format=s16 --ao=pcm:file=/dev/stdout
```
I get 
```
snapserver[19706]: 2020-04-11 14-24-02 [Error] (ProcessStream) Error while reading from stderr: End of file
```

Any idea what's causing the error? I can play the stream with mpv in a terminal just fine.

**Comment by herrwusel** [comment]
Needed to change ```--ao=``` to ```--ao=pcm:file=/dev/stdout```
