### ISSUE TITLE
Changing Streams ignores Latency Value

### ISSUE THREAD

**Issue by almostserious** [badaix/snapcast#588]
Hi, i just realized that when i change streams on a client, the latency settings are ignored / reset.

How to replicate:
1. Play sound on 2 synced clients
2. Change on of the clients to a different source
3. Change the client back to the original source

You will find that the client that switched the source is now out of sync.
However, the latency setting in the server.json will not have changed. Setting it again to the previous value via JSON RPC will fix the sync. In the Snapdroid app, you need to first change it to a different value, and then back to the original value which will also make both clients play in sync again.

This happens on both the snapdroid as well as the current test windows client so i think it is related to the server.

**Comment by badaix** [comment]
This should be fixed now in master: 827cfb7985e5c2e7e6d1725f3e33bbf81ac8ab9e
Can you please test it?
