### ISSUE TITLE
Stream to multiple virtual outs on same client

### ISSUE THREAD

**Issue by paparapapapapa** [badaix/snapcast#594]
Hello there, I can't wrap my head around this problem. Please help alleviate my headache :)

What's working right now:
I have a NUC server running Ubuntu 18.04. I can stream Mopidy to every smart speaker and even my smart TV through `pulseaudio-dlna`, which shows my DLNA devices as virtual outputs in system audio preferences or `pavu`. This way I can stream with almost no latency (with `--codec wav` argument) to one or more devices at time. I can only control speakers through system though, because Mopidy's Iris volume slider only controls current virtual device, and I have no list of outputs in Iris as well.
`Mopidy - > pulseaudio sink -> pulseaudio-dlna -> multiple DLNA 1/2/3`

What I want to achieve:
Multi-room synced audio to DLNA speakers but with full control of speakers through Iris, that from my understanding is fully compatible with Snapcast.
Ideally I guess this would be the pipeline, but I can be wrong there:
`Mopidy - > some stream sink? -> snapserver -> snapclient (same machine) -> pulseaudio-dlna -> MULTIPLE pulseaudio sink 1/2/3 ->  multiple DLNA 1/2/3`
If there is a simpler way, please share it.

When `pulseaudio-dlna` is running, this is the result of `$pacmd list-sinks`:
```
3 sink(s) available.
    index: 1
	name: <alsa_output.pci-0000_00_1f.3.analog-stereo>
	driver: <module-alsa-card.c>
[...]
    index: 2
	name: <soggiornosonossymfoniskmediarenderer_dlna>
	driver: <module-null-sink.c>
	flags: DECIBEL_VOLUME LATENCY DYNAMIC_LATENCY
	state: SUSPENDED
	suspend cause: IDLE 
	priority: 1000
	volume: front-left: 65536 / 100% / 0,00 dB,   front-right: 65536 / 100% / 0,00 dB
	        balance 0,00
	base volume: 65536 / 100% / 0,00 dB
	volume steps: 65537
	muted: no
	current latency: 0,00 ms
	max request: 344 KiB
	max rewind: 344 KiB
	monitor source: 3
	sample spec: s16le ch 2 44100 Hz
	channel map: front-left,front-right
	             Stereo
	used by: 0
	linked by: 0
	configured latency: 0,00 ms; range is 0,50 .. 2000,00 ms
	module: 32
	properties:
		device.description = "Soggiorno - Sonos SYMFONISK Media Renderer (DLNA)"
		device.class = "abstract"
		device.icon_name = "audio-card"
  * index: 3
	name: <studiosonossymfoniskmediarenderer_dlna>
	driver: <module-null-sink.c>
	flags: DECIBEL_VOLUME LATENCY DYNAMIC_LATENCY
	state: SUSPENDED
	suspend cause: IDLE 
	priority: 1000
	volume: front-left: 34483 /  53% / -16,73 dB,   front-right: 34483 /  53% / -16,73 dB
	        balance 0,00
	base volume: 65536 / 100% / 0,00 dB
	volume steps: 65537
	muted: no
	current latency: 0,00 ms
	max request: 344 KiB
	max rewind: 344 KiB
	monitor source: 4
	sample spec: s16le ch 2 44100 Hz
	channel map: front-left,front-right
	             Stereo
	used by: 0
	linked by: 0
	configured latency: 0,00 ms; range is 0,50 .. 2000,00 ms
	module: 33
	properties:
		device.description = "Studio - Sonos SYMFONISK Media Renderer (DLNA)"
		device.class = "abstract"
		device.icon_name = "audio-card"

```
PS: please don't ask me why I want to feed overpriced Sonos speakers with Snapcast :)

Thank you in advance!
R.

**Comment by badaix** [comment]
Feeding the signal via DLNA will break the sync
