### ISSUE TITLE
Fatal error <soxr.h> does'nt exsist.

### ISSUE THREAD

**Issue by Dlankheet** [badaix/snapcast#596]
Dear Snapcast community, I'm trying to create a snapcast server/client but when i try to use te make command Ill get this error:

`pi@deskrasPI:~/snapcast $ make
make -C client
make[1]: Map '/home/pi/snapcast/client' wordt binnengegaan
g++ -O2  -std=c++14 -Wall -Wextra -Wpedantic -Wno-unused-function -DBOOST_ERROR_CODE_HEADER_ONLY -DHAS_FLAC -DHAS_OGG -DHAS_OPUS -DVERSION=\"0.19.0\" -I. -I.. -I../common -pthread -DHAS_VORBIS -DHAS_ALSA -DHAS_AVAHI -DHAS_DAEMON -DHAS_SOXR -c snapclient.cpp -o snapclient.o
In file included from player/player.hpp:25,
                 from player/alsa_player.hpp:22,
                 from controller.hpp:29,
                 from snapclient.cpp:27:
./stream.hpp:30:10: fatal error: soxr.h: Bestand of map bestaat niet
 #include <soxr.h>
          ^~~~~~~~
compilation terminated.
make[1]: *** [Makefile:121: snapclient.o] Fout 1
make[1]: Map '/home/pi/snapcast/client' wordt verlaten
make: *** [Makefile:14: client] Fout 2
`

I'm using the tutorial of this website and the last version of raspbian.
https://www.whirlwind.nl/nieuw/bericht/multi-room-spotify-via-raspberry-pi
And also tried installing the following packages: sox libcurl4-openssl-dev clang libopencv-dev libsox-dev

Thanks in advance!

**Comment by badaix** [comment]
This tutorial seems outdated, you should rather follow the official [guide](https://github.com/badaix/snapcast/blob/master/doc/build.md#linux-native), which will tell you to install `libsoxr-dev` (with "r")

**Comment by Dlankheet** [comment]
Hi man, I've deleted the snapcast folder on my Pi and tried it over with your guide but now I get a new (similar) one? 
`make
make -C client
make[1]: Map '/home/pi/snapcast/client' wordt binnengegaan
g++ -O2  -std=c++14 -Wall -Wextra -Wpedantic -Wno-unused-function -DBOOST_ERROR_CODE_HEADER_ONLY -DHAS_FLAC -DHAS_OGG -DHAS_OPUS -DVERSION=\"0.19.0\" -I. -I.. -I../common -pthread -DHAS_VORBIS -DHAS_ALSA -DHAS_AVAHI -DHAS_DAEMON -DHAS_SOXR -c snapclient.cpp -o snapclient.o
In file included from controller.hpp:43,
                 from snapclient.cpp:27:
client_connection.hpp:25:10: fatal error: boost/asio.hpp: Bestand of map bestaat niet
 #include <boost/asio.hpp>
          ^~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:121: snapclient.o] Fout 1
make[1]: Map '/home/pi/snapcast/client' wordt verlaten
make: *** [Makefile:14: client] Fout 2
`
Thanks for your respond!

**Comment by badaix** [comment]
Just follow the guide:

> Snapcast depends on boost 1.70 or higher. Since it depends on header only boost libs, boost does not need to be installed, but the boost include path must be set properly: download and extract the latest boost version and add the include path, e.g. calling make with prepended ADD_CFLAGS: ADD_CFLAGS="-I/path/to/boost_1_7x_0/" make.
For cmake you must add the path to the -DBOOST_ROOT flag: cmake -DBOOST_ROOT=/path/to/boost_1_7x_0

**Comment by Dlankheet** [comment]
Ah I think I get it, already tought it had to do with that. But I need to download a package with boost then? Sorry for the dumb questions, I'm kind-off a linux noob.

**Comment by herrwusel** [comment]
Go to https://www.boost.org/ and download the current release. Extract the archive and edit your -DBOOST_ROOT flag accordingly.

**Comment by Dlankheet** [comment]
> Go to https://www.boost.org/ and download the current release. Extract the archive and edit your -DBOOST_ROOT flag accordingly.

I've tried the following command but still gives the error message:
 ADD_CFLAGS="-I/home/pi/boost/boost_1_72_0" make

I have downloaded the boost .tar.bz2 and extracted it in a folder named boost.  /home/pi/boost/boost_1_72_0

Still don't see what I'm doing wrong?

Thanks for helping me out so far!!
