### ISSUE TITLE
Multi Room / Multi User / Multi Stream

### ISSUE THREAD

**Issue by bbalazs** [badaix/snapcast#598]
Thanks for all the great work you are doing here. I seek for advice how to tackle a problem:

I would like that different people here at home can carry their own music with them. Imagine the kitchen as a room where the owner and by this the wanted music constantly changes. I am running Home Assistant and by this always know the owner of a room. Also, I have snapclients on Raspis in every room. I manage to install mopidy and snapserver fine on another server Raspi and are able to play one stream. So multi-room single user seems not be a problem. But I am absolutely puzzled how to tackle the multi-user problem.
Everyone needs their own music server. I thought about creating different mopidy instances for each user (spotify, soundcloud etc. hooked to this). And this looks doable. But how would I stream these into the snapserver? And could the snapserver feed different modipy streams at the same time to different groups of snapclients?
Or do I even need different snapserver per user? But as far as I understand a snapclient can only connect to one snapserver, right?
Or do I even need different snapclients per raspi? But how can this work?

Questions over questions...

Thanks for advice!

**Comment by herrwusel** [comment]
Have one Snapserver with multiple sources: Spotify_1, spotify_2, mopidy_1 etc. Implement present detection in Home Assistant and then create an automation accordingly.

**Comment by bbalazs** [comment]
Thanks for your answer. I have hoped for this solution.

I am currently failing at adding multiple mopidys to snapserver. I have tried to adjust the pipe in modipy and snapserver to /tmp/snapfifo_1 and also created this pipe with the same rights / owners as the regular /tmp/snapfifo - but snapcast does not seem to recognize it. So, practically, how do add two modipys to snapserver? (all are running on the same raspi server).

Again, thanks for advice!

**Comment by herrwusel** [comment]
Do you have multiple instances running? My guess is that you need different mopidys running. 

<details>
<summary>Just an idea</summary>
If that's too difficult you could try to install mopidy on every "satellite" and maybe writing to the server via sftp - sounds hacky but might work.
</details>

**Comment by bbalazs** [comment]
Creating multiply mopidys looks kind of promising. I simply don't understand how configure the pipes. I just read something about /read and create mode. Did not play around with this, yet. Both mopidys cannot stram/pipe  into /tmp/snapfifp I assume. I will need separate pipes for this. And currently I am failing on this step.

**Comment by herrwusel** [comment]
You would create different fifos. So mopidy1 outputs to /tmp/fifo1, mopidy2 to /tmp/fifo2 etc.

**Comment by bbalazs** [comment]
Do I need to manually create these fifos in the file system or will snapserver do this or modipy once configured?

**Comment by bbalazs** [comment]
Ok, seems to work. I had some issues with right owners and permissions - but I think it is working. Thanks for your advice.
