### ISSUE TITLE
ESP32 client is being made

### ISSUE THREAD

**Issue by monte-monte** [badaix/snapcast#599]
Maybe it's a wrong place to post it, but I wanted to attract attention to the fact that Jørgen Jakobsen has wrote a ESP32 client for snapcast: https://github.com/jorgenkraghjakobsen/snapclient

I haven't tested it myself but he reports that it works smoothly. The only thing for now is that he uses uncommon i2s dac/amplifier that makes it hard to try his code without additional work to adapt it to something more common (if I understand correctly).
Hope to see ESP32 support in mainline sometime.

**Comment by miLORD1337** [comment]
Yep, see #520

**Comment by badaix** [comment]
I'm aware of Jørgen's project and I'm really excited about it!
But I don't see official support now in context of this "mainline" project. This (badaix/Snapcast) is just one (C++) implementation of the Snapcast protocol, while Jørgen's Snapclient is a C implementation for the ESP32 SoC (the real bare metal embedded stuff - ARM is for beginners :wink: ).
And there is yet another [Snapclient implementation in Python](https://github.com/happyleavesaoc/python-snapcast) available.
I think the best we can do at the moment to support each is to add links to the project's Readmes.

**Comment by jorgenkraghjakobsen** [comment]
Yes - My implementation is still work in progress and ESP-IDF FreeRTOS tailored code. I use the library https://github.com/bridadan/libsnapcast that @bridadan has created and yes I use an odd codec/amplifier because I made one my self :-)

I also ripped it out of the ESP32 ADF (Audio framework) - be cause I have something better in the making as well. One day it mite get back when code start to mature. 

All my respect goes to Badaix who is the goal keeper of the protocol and concepts. His C++ implementation is highly abstracted and space grade build. Not easy for me to follow as I am just an IC designer and use to build thing from custom made transistors, resistors and caps. 

But the code is a good reference model and I am getting there feature by feature.  

Add the end of my tunnel is see an snapclient ESP-IDF component that do partial protocol support and fit into an open source multiroom audio streaming eco system. 
/J

**Comment by StuartIanNaylor** [comment]
@jorgenkraghjakobsen That would be so great as had the idea but the implentation never got further than the  ESP32-Audio-Kit board that has been gathering dust for some time.

PS my alternative was a https://wiki.radxa.com/RockpiS which is sort of Pi ZeroW price with built in audio codec and also an Cortex-A35.
PS my interest is Voice AI where speaker satellites are both media capable multi-channel audio that also mic capable.
It would be so good if a client could have multiple instances and be able to connect to multiple servers and output through different sink devices.
Thinking of using docker and loopbacks as read this is not possible?

Would be great to see ESP32-Snapcast as thought the same but for any others those Rockchip RK3308 chips are also great value.
Would also be great to get a Aaarch64 as can compile but a .deb would be great.

**Comment by jorgenkraghjakobsen** [comment]
That RockpiS is cute - But much bigger power and system footprint the needed for a snapclient.

**Comment by monte-monte** [comment]
@StuartIanNaylor I want to try MT7688 it's the chipset that is used in Onion Omega 2, and is available in bare modules similar to ESP32 (only slightly bigger) for around 10$. It runs Openwrt which already has snapcast in its repository and has I2S for external DAC.
But anyway ESP32 would be so much more accessible for simple projects and due to its low price and wide availability it can be a single-function device

**Comment by StuartIanNaylor** [comment]
> That RockpiS is cute - But much bigger power and system footprint the needed for a snapclient.
@jorgenkraghjakobsen 
Guess so but it does have embedded single channel VAD that wakes it from deep sleep its actually quite low power when not providing service.
But ESP32-audio-kit would be great and bow down to your efforts as looked at was enatiled and far, far too much for me :)

@monte-monte
I just purchased a a 512mb RockpiS for $13.99 and you prob want to take a look at the spec sheet.
https://dl.radxa.com/rockpis/docs/hw/datasheets/Rockchip%20RK3308TRM%20V1.1%20Part1-20180810.pdf

Its not a general purpose arm chip is a specific low price audio soc very similar to the allwinner R328 but cortex-a35.
Its sort of great for me as it has enough oomf to do software AEC without hardware DSP.

**Comment by jorgenkraghjakobsen** [comment]
Hi All  
I succeeded add a large sample buffer to the ESP32 client. 
On ESP32 with external ram the buffer will be allocated in PSRAM and allow all the buffers sized needed. 
On ESP32 with internal ram we can do only around 200 ms - Snapcast is default 1000ms with a minimum of 400 ms. 
My code has been updated to current ESP-IDF release and builds using legacy make and new Cmake/ninja build flow. 
Still a lot of coding to be done - but added a dynamic second size buffer has been that last task on prove of concept. /Jakobsen

**Comment by palitu** [comment]
Awesome! Well done!

**Comment by miLORD1337** [comment]
> On ESP32 with external ram
> On ESP32 with internal ram
Just a quick sum up buyers guide:
WROVER has 8 MB of PSRAM
WROOM, which has no PSRAM

So if you want to be on the safe side regarding buffering, definitely go for the WROVER.

**Comment by badaix** [comment]
FYI just read about this ESP32 based audio kit in the news:
https://www.aliexpress.com/i/32957553086.html?spm=a2g0x.12057483.1000001.8.72af21fdeYSPU0

**Comment by TekniskSupport** [comment]
Looks very similar to the LyraT from espressif
https://www.mouser.com/Search/Refine?Keyword=lyraT

**Comment by palitu** [comment]
that looks promising for a low cost device!  includes 3W ampl it would seem,
