### ISSUE TITLE
Mopidy compatibility

### ISSUE THREAD

**Issue by 1337sup3rh4x0r** [badaix/snapcast#6]
Hi, I am looking for a setup for streaming from Google Play Music to multiple outpus (raspberries) and snapcast is looking very interesting. As mopidy is based on MPD, is snapcast compatible to mopidy? How would I go about adding the fifo sink for snapcast there?
The snapcast and mopidy server would be running on a debian system.

**Comment by badaix** [comment]
Hi,

as for MPD you have to redirect the audio stream into the snapserver's fifo. You can do this by configuring a filesink as audio output in your `mopidy.conf`:

```
[audio]
#output = autoaudiosink
output = audioresample ! audioconvert ! wavenc ! filesink location=/tmp/snapfifo
```

BR,
Johannes
