### ISSUE TITLE
Snapserver executes onResync frequently in the android background

### ISSUE THREAD

**Issue by leeyex** [badaix/snapcast#601]
I run snapserver on android just like you run snapclient. I use localhost tcpstream.  when i run it in the android backgroud, it executes onResync frequently. But if i execute snapserver manually, everything is OK.It seems to reading data from localhost tcp too slowly when it run in backgroud. I don‘t know what reason cause it. Could you give me some suggestions？By the way, It's a excellent software.

**Comment by badaix** [comment]
So you cross compiled the server for Android? How do you start it "in the background" and how "manually"?
You can try to use more threads e.g. `--server.threads = 4`. Or you're feeding the input stream not fast enough, e.g. the stream might be configured with 48kHz and is fed with 44.1kHz.

**Comment by leeyex** [comment]
Thanks for you response. Yes i had cross compiled the server for android.
I run snapserver in the backgroud like, eg
    process = new ProcessBuilder() .command(binary.getAbsolutePath(),  "--stream.stream", "\"tcp://127.0.0.1:9999?name=default&mode=client\"").redirectErrorStream(true).start();
manually is like, eg
./snapserver --logging.filter debug --stream.stream "tcp://127.0.0.1:9999?name=default&mode=client"
i had checked it, the default server.threads is 4. If it caused by the no corresponding rate, 
The above two would be the same performance.

**Comment by badaix** [comment]
so manually means on an ADB shell?
AFAIK this project includes a server in an APP: https://github.com/mjaggard/snapcast
Maybe it does some magic, some other wakelocks or something.

**Comment by leeyex** [comment]
oh. I did't use wakelocks. It probably caused by this. Thanks you again. you are an awsome author.
