### ISSUE TITLE
[help] Capture audio from line-in different machine

### ISSUE THREAD

**Issue by lealoureiro** [badaix/snapcast#603]
Hello,

Thanks for all great work!

I saw on documentation that is possible to capture audio from Line-In and send to a FIFO to send to Snapcast server, but if line-in input and snapcast server are not in same physical machine, there is a way to send over the network?

Kind regards,
Leandro Loureiro

**Comment by TekniskSupport** [comment]
Hi,

I would use snapcast for that, Just fire up a snapserver on the machine with the audio jack, then run a client on your main server and you are set.

PulseAudio is another alternative;
https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/Network/
https://superuser.com/questions/432894/pipe-system-sound-to-another-computer

Kind regards
Iesus

**Comment by StuartIanNaylor** [comment]
@TekniskSupport 

If I can ask for your knowledge as server to multiple clients works great but have mic/line in on each client that I would like all to be available on the server.
Is there a way to have multiple servers on a single client so that the client is picking from designated IP address but also concurrent streams?

**Comment by TekniskSupport** [comment]
Hi,

Wait, you want same device to be streaming the sound and be the source to itself?
That would cause a feedback loop resulting in just horrible noise.

I think you need to set up multiple streams to choose from in your main stream, and *not* have the same source and output.

An option i can come up with is to spin up multiple dockerized clients that each listens to different sources and outputs the stream to a file/fifo per microphone/server that you can use those fifos as sources in the main server

That might work, or explain your use case better and there's probably a better solution.

**Comment by StuartIanNaylor** [comment]
Its for a voice AI probably rhasspy, the soc I am using will be running software AEC but the Mic is just for recognition and not transmitted to the speaker stream.
The stream is cancelled from the mic pickup though, but purely to capture only voice. Being differing servers and no latency correlation latency saves the feedback day in this case as have run before and feedback doesn't seem to be a problem but the media playing does saturate the mic capture without AEC.

Yeah I was thinking docker as can use a loopback subdevice for each container and guessing on the host they will just be an array of sources on the oppiste side of the loopback matching the subdevice.

**Comment by lealoureiro** [comment]
The idea is to have a stream on snapcast server that will have what is playing in my Turntable.

The phone pre amp of the turntable has a digital output capable of record 96Khz/24Bit and Linux sees it as input audio device.

The problem is that where i have my turntable i dont have the server where my Snapserver is running, so i want to use a Raspberry pi to capture the audio from Turntable phone pre amp and send it over the network to the machine where snapserver is running and then be available as another stream for all my snapclient clients as already have for Spotify Connect, Airplay, etc.

**Comment by xabolcs** [comment]
@lealoureiro, there is a nice input plugin in development: TCP stream. 

See #511 for the details!

**Comment by badaix** [comment]
It's not in development, it has been released in v0.18

**Comment by lealoureiro** [comment]
It means i can already create a TCP stream in mode server and connect remotely parec to create a snapcast stream from mic/audio input from another machine?

**Comment by badaix** [comment]
yes, you should find a line like this in your `snapserver.conf`:
```
[stream]
...
# tcp server: tcp://<listen IP, e.g. 127.0.0.1>:<port>?name=<name>[&mode=server]
```

**Comment by lealoureiro** [comment]
cool! what would be the command for `parec`?

**Comment by badaix** [comment]
Don't know what parec is

**Comment by lealoureiro** [comment]
In Snapcast configuration guide for to get audio from Line-In there is this suggestion:

```
PulseAudio
parec >/tmp/snapfifo (defaults to 44.1kHz, 16bit, stereo) 
```

But this send to a fifo...

How can we adjust the command to sent to snapcast tcp stream?

**Comment by badaix** [comment]
Maybe google can help you? 
Something like `parec | netcat <host> <port>`

**Comment by lealoureiro** [comment]
i will try.

But which audio format tcp stream is expecting? because i saw people using nc but command also allows to connect to a server

**Comment by badaix** [comment]
as all streams, it expects raw pcm in the configured sample format

**Comment by lealoureiro** [comment]
it worked this way:

`stream = tcp://0.0.0.0?name=Turntable&port=4956&&sampleformat=44100:16:2`

and 

`parec -d <input-device> --rate=44100 --format=s16le | nc <ip-address> 4956`

I used microphone to test and sound was okay, just a few seconds delay tough
