### ISSUE TITLE
sampleformat issue

### ISSUE THREAD

**Issue by tdesaules** [badaix/snapcast#606]
Hi Guys !

I try to change the sampleformat from the server and/or client without success.
sampleformat look lock on "48000:16:2"

I find the issue working on mopidy then I try directly using an alsa raw file. Still look the same... my DAC show up "48KHz / 16bits" stream.

asound.conf 
```
pcm.writeFile {
    type file
    slave.pcm null
    file "/tmp/snapcast/snapfifo"
    format "raw"
}
pcm.test {
    type rate
    slave {
        pcm writeFile
        format S32_LE
        rate 96000
    }
}
```

snapserver.conf
```
[stream]
bind_to_address = 127.0.0.1
port = 1704
stream = pipe:///tmp/snapcast/snapfifo?name=local&sampleformat=96000:32:2&codec=pcm
sampleformat = 44100:24:2
chunk_ms = 20
buffer = 1000
```

snapclient cmd
```
snapclient --host 127.0.0.1 --soundcard D10 --sampleformat 192000:32:2
```

aplay cmd
```
flac -c -d /root/sound/sample_24bit-96kHz.flac | aplay -D test
```

I try different sampleformat from alsa, snapserver and snapclient from 44100 to 192000 and 16 to 32 bit. Still have the same output on my dac 48KHz / 16bit. I also try to play some flac directly using aplay without snacast and the samplerate is correct.

Infra : 
Raspberry PI 3 A+
Topping D10 DAC
Alpine Linux 3.11
Advanced Linux Sound Architecture Driver Version k4.19.71
Snapcast 0.19.0

**Comment by badaix** [comment]
There is no `--sampleformat` option for the client. Are you sure that you've assigned the stream "local" to your client? The client log should show what samplerate is used.

**Comment by tdesaules** [comment]
Really, the changelog isn't correct ? (https://github.com/badaix/snapcast/blob/master/changelog.md)

I just look from the client log : 
```
04.05.20 22:07:56 (+0200)  snapcast-agent  2020-05-04 20-07-56 [Info] (main) Adding stream: pipe:///tmp/snapcast/snapfifo?name=local&sampleformat=44100:16:2&codec=pcm
04.05.20 22:07:56 (+0200)  snapcast-agent  2020-05-04 20-07-56 [Notice] (init) Settings file: "/root/.config/snapserver/server.json"
04.05.20 22:07:56 (+0200)  snapcast-agent  2020-05-04 20-07-56 [Error] (init) Error reading config: [json.exception.parse_error.101] parse error at 1: syntax error - unexpected end of input; expected '[', '{', or a literal
04.05.20 22:07:56 (+0200)  snapcast-agent  2020-05-04 20-07-56 [Error] (Avahi) Failed to create client: Daemon not running
04.05.20 22:07:56 (+0200)  snapcast-agent  2020-05-04 20-07-56 [Info] (start) Creating TCP acceptor for address: 0.0.0.0, port: 1705
04.05.20 22:07:56 (+0200)  snapcast-agent  2020-05-04 20-07-56 [Info] (PcmStream) PcmStream sampleFormat: 44100:16:2
04.05.20 22:07:56 (+0200)  snapcast-agent  2020-05-04 20-07-56 [Info] (PcmStream) metadata={
04.05.20 22:07:56 (+0200)  snapcast-agent  2020-05-04 20-07-56 [Info] (PcmStream)     "STREAM": "local"
04.05.20 22:07:56 (+0200)  snapcast-agent  2020-05-04 20-07-56 [Info] (PcmStream) }
04.05.20 22:07:56 (+0200)  snapcast-agent  2020-05-04 20-07-56 [Info] (onMetaChanged) onMetaChanged (local)
04.05.20 22:07:56 (+0200)  snapcast-agent  2020-05-04 20-07-56 [Info] (PipeStream) PipeStream mode: create
04.05.20 22:07:56 (+0200)  snapcast-agent  2020-05-04 20-07-56 [Info] (start) Stream: {"fragment":"","host":"","path":"/tmp/snapcast/snapfifo","query":{"chunk_ms":"20","codec":"pcm","name":"local","sampleformat":"44100:16:2"},"raw":"pipe:////tmp/snapcast/snapfifo?chunk_ms=20&codec=pcm&name=local&sampleformat=44100:16:2","scheme":"pipe"}
04.05.20 22:07:56 (+0200)  snapcast-agent  2020-05-04 20-07-56 [Info] (start) Creating stream acceptor for address: 127.0.0.1, port: 1704
04.05.20 22:07:56 (+0200)  snapcast-agent  2020-05-04 20-07-56 [Info] (main) number of threads: 4, hw threads: 4
04.05.20 22:07:57 (+0200)  snapcast-agent  2020-05-04 20-07-57 [Info] (main) Latency: 0
04.05.20 22:07:57 (+0200)  snapcast-agent  2020-05-04 20-07-57 [Notice] (start) Connected to 127.0.0.1
04.05.20 22:07:57 (+0200)  snapcast-agent  2020-05-04 20-07-57 [Info] (getMacAddress) My MAC: "b8:27:eb:eb:59:68", socket: 5
04.05.20 22:07:57 (+0200)  snapcast-agent  2020-05-04 20-07-57 [Notice] (handleAccept) StreamServer::NewConnection: 127.0.0.1
04.05.20 22:07:57 (+0200)  snapcast-agent  2020-05-04 20-07-57 [Info] (onMessageReceived) Hello from b8:27:eb:eb:59:68, host: ce4e023, v0.19.0, ClientName: Snapclient, OS: Alpine Linux v3.11, Arch: armv7l, Protocol version: 2
04.05.20 22:07:57 (+0200)  snapcast-agent  2020-05-04 20-07-57 [Info] (onMessageReceived) ServerSettings - buffer: 1000, latency: 0, volume: 100, muted: 0
04.05.20 22:07:57 (+0200)  snapcast-agent  metadata:{"STREAM":"local"}
04.05.20 22:07:57 (+0200)  snapcast-agent  2020-05-04 20-07-57 [Info] (onMessageReceived) Codec: pcm
04.05.20 22:07:57 (+0200)  snapcast-agent  2020-05-04 20-07-57 [Notice] (state) sampleformat: 44100:16:2
04.05.20 22:07:57 (+0200)  snapcast-agent  2020-05-04 20-07-57 [Info] (Alsa) frames: 940
04.05.20 22:07:57 (+0200)  snapcast-agent  2020-05-04 20-07-57 [Info] (Alsa) Resizing buffer from 0 to 15052
04.05.20 22:07:57 (+0200)  snapcast-agent  2020-05-04 20-07-57 [Info] (worker) diff to server [ms]: 0.044
04.05.20 22:07:57 (+0200)  snapcast-agent  2020-05-04 20-07-57 [Info] (Stream) Chunk: 0  0       0       0       1       64      0
04.05.20 22:07:58 (+0200)  snapcast-agent  2020-05-04 20-07-58 [Info] (Stream) Chunk: 1  1       1       1       2       62      0
04.05.20 22:07:59 (+0200)  snapcast-agent  2020-05-04 20-07-59 [Info] (Stream) Chunk: 12 9       6       6       48      63      0
04.05.20 22:07:59 (+0200)  snapcast-agent  2020-05-04 20-07-59 [Info] (getPlayerChunk) Exception
04.05.20 22:07:59 (+0200)  snapcast-agent  2020-05-04 20-07-59 [Info] (Alsa) Failed to get chunk
04.05.20 22:08:04 (+0200)  snapcast-agent  2020-05-04 20-08-04 [Notice] (Alsa) No chunk received for 5000ms. Closing ALSA.
```
I also check if the stream correctly assigned. That part is good. I have only one stream and it is selected.

I also adapt my conf to deliver only 44100Hz / 16Bit. But the stream still output from my DAC with 48000Hz. I also try another DAC, still the same.

So maybe my issue is other. I think Snapcast doesn't take the good alsa pcm device I configured. Another strange think if I launch the snapclient without "--soundcard" it doesn't take the default alsa device I configure in /etc/alsa.conf : 
```
bash-5.0# cat /etc/asound.conf 
# PCM Configuration

# # Default device

pcm.!default {
    type plug
    slave.pcm D10
}

# # Internal ALSA Device

# # # Base PCM device

pcm.ALSA {
    type plug
    slave ALSA
}

# # # Base Card Def

pcm_slave.ALSA {
    pcm 'hw:ALSA'
    format S16_LE
    rate 44100
}

# # Topping D10 Dac

# # # Base PCM device

pcm.D10 {
    type plug
    slave D10
}

# # # Base Card Def

pcm_slave.D10 {
    pcm 'hw:D10'
    format S32_LE
}

# # Raw snapfifo test conf

pcm.writefile {
    type file
    slave.pcm null
    file "/tmp/snapcast/snapfifo"
    format "raw"
}

pcm.test {
    type rate
    slave {
        pcm writefile
        format S16_LE
        rate 44100
    }
}

# CTL Configuration

# # Default

ctl.!default {
    type hw
    card ALSA
```
The device listed by snapcast : 
```
bash-5.0# snapclient -l
0: null
Discard all samples (playback) or generate zero samples (capture)

1: samplerate
Rate Converter Plugin Using Samplerate Library

2: speexrate
Rate Converter Plugin Using Speex Resampler

3: oss
Open Sound System

4: upmix
Plugin for channel upmix (4,6,8)

5: vdownmix
Plugin for channel downmix (stereo) with a simple spacialization

6: sysdefault:CARD=ALSA
bcm2835 ALSA, bcm2835 ALSA
Default Audio Device

7: usbstream:CARD=ALSA
bcm2835 ALSA
USB Stream Output

8: sysdefault:CARD=D10
D10, USB Audio
Default Audio Device

9: front:CARD=D10,DEV=0
D10, USB Audio
Front speakers

10: surround21:CARD=D10,DEV=0
D10, USB Audio
2.1 Surround output to Front and Subwoofer speakers

11: surround40:CARD=D10,DEV=0
D10, USB Audio
4.0 Surround output to Front and Rear speakers

12: surround41:CARD=D10,DEV=0
D10, USB Audio
4.1 Surround output to Front, Rear and Subwoofer speakers

13: surround50:CARD=D10,DEV=0
D10, USB Audio
5.0 Surround output to Front, Center and Rear speakers

14: surround51:CARD=D10,DEV=0
D10, USB Audio
5.1 Surround output to Front, Center, Rear and Subwoofer speakers

15: surround71:CARD=D10,DEV=0
D10, USB Audio
7.1 Surround output to Front, Center, Side, Rear and Woofer speakers

16: iec958:CARD=D10,DEV=0
D10, USB Audio
IEC958 (S/PDIF) Digital Audio Output

17: usbstream:CARD=D10
D10
USB Stream Output
```
So what should I configure in the soundcard option : 
```
snapclient --host 127.0.0.1 --soundcard xxxx
```
I made another test by changing the defaults.pcm.dmix.rate from /usr/share/alsa/alsa.conf to 48000KHz to 44100KHz and the rate change using snapclient from my dac... So the the snapclient doesn't take the good soundcard (or I add the wrong device)

**Comment by badaix** [comment]
Sorry, you're right, there is actually a `sampleformat` setting for the client :)
Snapcast will by default use the sound device out of the list with the subtring `default`, so the one with idx 6, I guess. 
I lately learned that you have to add the [`hint.description`](https://github.com/badaix/snapcast/issues/566#issuecomment-614781246) field to the pcm device in your `alsa.conf` to make the device visible to snapcast (`aplay -L` should work in the same way, maybe you can use this for further cross checks)

**Comment by tdesaules** [comment]
Hi ! thanks for the answer.

I get to it... selecting the wrong device from the --soundcard option. And both dac only support S32_LE not S16_LE so when I made test the sound device souldn't be use.

on snapcast.conf I use :
```
sampleformat=96000:32:2  
codec=pcm
chunk_ms=5
buffer=1000
```
and from my test alsa fifo asound.conf : 
```
pcm.writefile {
    type file
    slave.pcm null
    file "/tmp/snapcast/snapfifo"
    format "raw"
}

pcm.snapfifo {
    type rate
    slave {
        pcm writefile
        format S32_LE
        rate 96000
    }
}
```
I will take a look to the hint.description (never use it)

Another strange thing : I can't increase the rate more than 96KHz (should be enough of course) but when I made test over than that (192KHz or 352KHz). I check the CPU it look good. Any ideas ?

**Comment by badaix** [comment]
Sorry, I don't get it, is 96kHz working or not?
I never tested with 352kHz, I only successfully tested with 192kHz.
I always recommend to test with aplay, because this should be kind of a reference implementation of an alsa player.

**Comment by tdesaules** [comment]
Sorry, Yeah it is working fine with 96kHz + S32_LE.

Get lot of lag after that over 192kHz or 352kHz can't use it. that's strange I made test locally and CPU look fine. It work pretty fine with those rate ( 192kHz or 352kHz ) using aplay with test flac : 
```
flac -d -c 'file.flac' | aplay
```

**Comment by badaix** [comment]
well, 96kHz should be enough

**Comment by badaix** [comment]
Just tested with 192kHz 32bit on mpd without any problems. Maybe it's related to the alsa forwarding.

**Comment by tdesaules** [comment]
Of course, was just for info :)

Thank you

**Comment by tdesaules** [comment]
@badaix what hardware / os are you using for your test ? wondering if it is not just Raspberri Pi 3A+ /  alpine linux my problem.
should be working if you made it using : 
```
snapcast > MPD > ALSA
```
I test directly : 
```
snapcast > ALSA
```

**Comment by badaix** [comment]
I do mpd -> pipe -> snapserver -> snapclient -> alsa
Please pipe your 352kHz flac to the snapserver's pipe:
```flac -d -c 'file.flac' > /tmp/snapfifi```

> should be working if you made it using:
```snapcast > MPD > ALSA```

I don't understand this. What is the problem?

**Comment by tdesaules** [comment]
yes I already try : 
```
flac -d -c 'file.flac' > /tmp/snapfifo > snapserver (192kHz + S32_LE) > snapclient
```
and got lag

From my last post I mean if it working for you using MDP it should work for me cause I pass the audio flac stream directly to ALSA. 

Maybe something with my hardware / os (Raspberri Pi 3A+ / alpine linux) I'm using snapcast in a alpine container writing the fifo to a docker volume from the host (just for info)

**Comment by badaix** [comment]
yes, maybe it's related to your setup (352000:32:2 needs 2.8 MB/sec bandwidth), on my containerless Raspbian I don't experience such a lag.
