### ISSUE TITLE
Release Aarch64 version

### ISSUE THREAD

**Issue by StuartIanNaylor** [badaix/snapcast#607]
Running Ubuntu 20.04 Aarch64 Raspberry Pi 4.

No probs will try compile but would be great and simple to have a .deb.

Thanks
Stuart

**Comment by badaix** [comment]
packaging is not in the focus of this project, and is causing already enough trouble.
I have to check if this can be automated with travis.
You can also install snapcast from the official debian/Ubuntu repositories (https://packages.debian.org/source/sid/snapcast)

**Comment by StuartIanNaylor** [comment]
Didn't know it was in the Debian repo v15 with 18 being in the new ubuntu.
Should of checked.
