### ISSUE TITLE
Allow client to multiple server connections

### ISSUE THREAD

**Issue by StuartIanNaylor** [badaix/snapcast#608]
I have a series of speaker/mic satellites and from server to multiple clients snapcast is just perfect.
What I would like to do though is on each client host run a server for the mic and send mic back to the snapcast speaker server from each snapcast speaker/mic host.

I have read that a client can not connect to several servers but actually would be great if it could as then I could playback to a loopback device with each stream going to a subdevice and on the server on the other side just pick up the source side if it was a mic.

I am guessing docker might have to come to the rescue here as the use of loopbacks and access to /dev/snd should mean on the host out of the container if set correctly the multiple docker instances should all be present on the source side of the loopback.

Is it possible to have client to multiple servers with multiple streams to multiple devices or is it a matter of using docker and containers as I say?

**Comment by badaix** [comment]
I'm afraid I don't completely get what you want to achieve. 
It's not possible to connect a client to more than one server, and it's not planned to be supported.
Maybe it helps to start two clients on each host? And to have for each client a dedicated TCP input stream on the server?

**Comment by StuartIanNaylor** [comment]
Yeah prob badaix as presume its all a matter of network time? If that is synced then clients are ?

I actually got round to actually thinking and trying with a `snapclient -h` and should stop asking pointless noob questions :)

I am getting there slowly as yeah I can run multiple clients to multiple servers and that is all I need.
I just have to start them up with the options set to point at correct server rather than what avahi might try and attach.

Another question is channel volumes but guess I can preset that on each device.
