### ISSUE TITLE
Feature request: SRTP (Secure Real-Time Transport Protocol or Secure RTP)

### ISSUE THREAD

**Issue by StuartIanNaylor** [badaix/snapcast#610]
I just thought I would ask if its possible or if that a whole load of further problems or even if is it somewhere already available?

Doesn't have to be SRTP but is secure snapcast possible?

I have been mulling over using snapcast as audio system but also the mic system in a voice AI.
I was talking about this in the Rhasspy community and the usual doom and gloom security trolls began to surface.
I can use IP tables and make things pretty secure and its only on the local subnet but just thought I would mention it as not essential but could quiet the security trolls slightly.

**Comment by badaix** [comment]
No, it's not planned at the moment (neither RTP nor SRTP). You can use IPSec if you need to have the traffic encrypted.
