### ISSUE TITLE
kill snapserver and snapclient

### ISSUE THREAD

**Issue by dinuchiriac** [badaix/snapcast#612]
I'm running into an issue where `snapserver` and `snapclient` starts in the background as a daemon once the system is booted and every time  I'm trying to kill them the processes keeps reopening.

I'm running on MacOS Catalina 10.15.4

Anu clue how do I properly stop snapserver and client on mac?

**Comment by badaix** [comment]
Fortunately, I don't have macOS, so I can just guess: Snapcast is running as a daemon, and daemons are managed by launchd according to their `plist` files:
```
/Library/LaunchAgents/de.badaix.snapcast.snapclient.plist
/Library/LaunchAgents/de.badaix.snapcast.snapserver.plist
```
Both have the key KeepAlive set, which I think will cause launchd to restart the daemons when they are killed.
It seems that you can control daemons with `launchctl`:
https://apple.stackexchange.com/questions/37188/stopping-launchagents-and-daemons
