### ISSUE TITLE
white noise

### ISSUE THREAD

**Issue by dinuchiriac** [badaix/snapcast#613]
I'm trying to feed a pcm audio stream to `/tmp/snapfifo`  directly from the microphone however on the player side I can only hear "broken" white noise. Here is what I am doing:

```
import sounddevice as sd
import os, time

f = open('/tmp/respeaker', 'wb')


sd.default.samplerate = 44100
sd.default.device = 1
cahnnels = 1

def audio_callback(indata, frames, time, status):
    if status:
        print(status)
    f.write(bytes(indata))

with sd.RawInputStream(channels=cahnnels, dtype='int24', callback=audio_callback):
    try:
        while True:
            time.sleep(0.1)
    except KeyboardInterrupt:
        pass

f.close()
```

and here is my snapserver config:

```
stream = pipe:///tmp/snapfifo?name=default
sampleformat = 44100:24:1
codec = pcm
chunk_ms = 20
buffer = 2000
```

I am able to decode the same recording through audacity so the audio stream is fine, I guess I'm just missing something from the config side.

**Comment by dinuchiriac** [comment]
It turns out only 16bit audio works. 
Anyone knows the reason why? And if this is a hardcoded limitation it should be documented in the README?

**Comment by badaix** [comment]
Snapcast expects 24 bit in 4 bytes, python uses packed 24 bit format, which is 24 bits in 3 bytes. You can use 16 or 32 bit.

**Comment by dinuchiriacsonos** [comment]
Thanks 👍
