### ISSUE TITLE
Provide armv6 release builds (for RPi 1 and zero)

### ISSUE THREAD

**Issue by oyv** [badaix/snapcast#614]
Raspberry pi zero w is a perfect client for snapcast, so builds for it would be highly appreciated, especially since raspbian seems stuck on snapcast 0.15.

**Comment by badaix** [comment]
aren't the provided deb packages working on RPi1 or 0?

**Comment by A----** [comment]
I do use Snapcast 0.19 client on Rasp Pi Zero W. 🤷‍♂️

**Comment by oyv** [comment]
Sorry, yes it seems to be working. I just assumed it wouldn't since librespot needs to be compiled differently. Thanks.
