### ISSUE TITLE
Documentation request for TCP streeams

### ISSUE THREAD

**Issue by MCHellspawn** [badaix/snapcast#617]
Hello, the default config file shows the possibility of setting up a TCP stream but I cannot find any documentation as to how this should work? I am looking to send the audio for a remote device to the snapcast server. At some point there may be several devices going to multiple TCP streams (not all at once) if possible. I have the server working with Mopidy over the the standard snapfifo stream. I have added another stream to the server using the example in the config file. I know this may be slightly out of scope for this post but how can i send audio to that stream? For example a Kodi box hooked to my TV.

**Comment by xabolcs** [comment]
Maybe #511 could help you!

**Comment by badaix** [comment]
done: https://github.com/badaix/snapcast/blob/master/doc/configuration.md#tcp-server
