### ISSUE TITLE
Snapclient stops playing after a few seconds

### ISSUE THREAD

**Issue by ambientsound** [badaix/snapcast#62]
Hi,

This problem occurs upon booting a Raspberry Pi with a Raspbian Jessie system, with systemd and the snapclient enabled. Snapclient starts playing, but after a few seconds, it stops emitting audio. A service restart is required to make it play again, and then it will behave normally.

Regards, Kim

**Comment by badaix** [comment]
Did you install it from the debian package or with `make`, `make install`?
Can you see anything "unusual" in the syslog? (`cat /var/log/syslog`)?
Is the client visible to the Android app?
Is the Raspberry connected over WiFi or ethernet?

**Comment by ambientsound** [comment]
I'm using the Debian package. The problem occurs both on ethernet and WiFi. I can try the Android client - although lately, the problem has been rather hard to reproduce. Very strange. However, syslog says nothing:

```
May 22 15:42:58 ultrasound snapclient[525]: daemon started
May 22 15:42:58 ultrasound snapclient[525]: Connected to 10.0.0.3
```

**Comment by ambientsound** [comment]
Can't reproduce this error anymore.
