### ISSUE TITLE
Cloning external submodules fails, xiph.org git repos appear to have moved to gitlab

### ISSUE THREAD

**Issue by klundry** [badaix/snapcast#620]
New location is https://gitlab.xiph.org/xiph and updating the paths in ~/snapcast/.git/config seems to work fine except for tremor.

`Submodule path 'flac': checked out 'f764434a39e8a8715d5871bb263189e5a7298280'
Submodule path 'oboe': checked out '56854b88dd54a8bf7c511800ecf9f991e02cf3de'
Submodule path 'ogg': checked out 'bada45718453ac27b56773ae663f7e65112f6a6e'
Submodule path 'opus': checked out '93b373e884915e802188cec844a7dda2fa184ebc'
error: Server does not allow request for unadvertised object 7c30a66346199f3f09017a09567c6c8a3a0eedc8
Fetched in submodule path 'tremor', but it did not contain 7c30a66346199f3f09017a09567c6c8a3a0eedc8. Direct fetching of that commit failed.`

**Comment by badaix** [comment]
This this already fixed in develop branch and will be merged to master soon

**Comment by klundry** [comment]
Excellent. :)

**Comment by klundry** [comment]
Also, apologies. I probably should have checked the dev branch or PRs and I would have seen it. Thanks again for all your work on snapcast.

**Comment by badaix** [comment]
It's not your fault ;)
The master should be assumed stable, I will reopen this issue to make it visible for others who stumble upon this.

**Comment by xabolcs** [comment]
FYI: #616

**Comment by xabolcs** [comment]
They [added](https://gitlab.xiph.org/xiph/tremor/-/issues/2298#note_51899) the [missing commits](https://gitlab.xiph.org/xiph/tremor/-/tree/7c30a66346199f3f09017a09567c6c8a3a0eedc8).

Commit dd70827fc6e532390bc9e3bae28553f901c9c2e8 on `developer` branch can be reverted now.

**Comment by badaix** [comment]
Sweet! Thanks for the notification. I'm offline this week, will change it next week.
