### ISSUE TITLE
Cant start snapserver on boot DIETPI it was working fine on snapserver.0.15.0-1 i just updated it

### ISSUE THREAD

**Issue by sealteam666** [badaix/snapcast#621]
dietpi@DietPi:/etc$ sudo nano /etc/default/snapserver
dietpi@DietPi:/etc$ sudo systemctl restart  snapserver
dietpi@DietPi:/etc$ sudo systemctl status snapserver
● snapserver.service - Snapcast server
   Loaded: loaded (/lib/systemd/system/snapserver.service; enabled; vendor preset: enabled)
   Active: failed (Result: signal) since Sat 2020-05-16 15:30:44 +09; 2s ago
     Docs: man:snapserver(1)
  Process: 1701 ExecStart=/usr/bin/snapserver $SNAPSERVER_OPTS (code=killed, signal=ABRT)
 Main PID: 1701 (code=killed, signal=ABRT)

May 16 15:30:44 DietPi systemd[1]: snapserver.service: Service RestartSec=100ms expired, scheduling restart.
May 16 15:30:44 DietPi systemd[1]: snapserver.service: Scheduled restart job, restart counter is at 5.
May 16 15:30:44 DietPi systemd[1]: Stopped Snapcast server.
May 16 15:30:44 DietPi systemd[1]: snapserver.service: Start request repeated too quickly.
May 16 15:30:44 DietPi systemd[1]: snapserver.service: Failed with result 'signal'.
May 16 15:30:44 DietPi systemd[1]: Failed to start Snapcast server.

**Comment by sealteam666** [comment]
also when i start with snapserver on command line it works fine

**Comment by badaix** [comment]
How did you update? 
- Via package manager?
- Did you install an apk from the release page?
- Did you install it from source?

How does you unit file look like? (`/lib/systemd/system/snapserver.service`)
Is there anything suspicious in your syslog?

**Comment by badaix** [comment]
Closed due to inactivity

**Comment by happyleavesaoc** [comment]
I had a similar problem. I checked `syslog` as suggested, and found:
`snapserver[28136]: Exception: failed to open file "/var/lib/snapserver/server.json", permission denied (error 13)`

Correcting the permissions fixed the problem.
