### ISSUE TITLE
Audio Cutting Out on Clients

### ISSUE THREAD

**Issue by hav0ck** [badaix/snapcast#627]
I've been playing with snapcast on and off for a bit and I've gotten some time to really set things up and I've noticed an issue.
The audio cuts out occasionally on clients. I was running .15 so I updated to .19 and I thought the update had resolved the issue as client 1 was stable. I activated client 2 and about 2 minutes later client 2 had a loud buzz noise coming from it which lasted about 20ish seconds. Then client 1 went silent and then both returned to playing the stream.
I disabled client 2 and client 1 still blanks out but not as frequently.

My clients are both Android phones and running the Snapcast app available from the Play Store.
My server is running on Ubuntu 18.04 and was installed via the .deb file. I ran it from the CLI with no options and when the clients don't behave there are no issues/errors showing up in the details being displayed.

I'm happy to provide whatever details that would help.

**Comment by miLORD1337** [comment]
This might be a known problem regarding fifos. You could try a TCP input stream (#511) if you haven't already and see if that solves the issues.

**Comment by hav0ck** [comment]
Made the config changes. I'll have to wait until tonight to test the changes out.
Thanks and hope it works :)

**Comment by hav0ck** [comment]
I made the changes to mopidy.conf and snapcast.conf but I am getting errors like "mopidy.audio.actor: Setting GStreamer state to GST_STATE_PLAYING failed" and "mopidy.audio.gst: GStreamer error: gst-resource-error-quark: Could not open resource for reading"

I'm guessing the issue lies with Mopidy but I'm not sure.

**Comment by badaix** [comment]
could it be WiFi related? Can you switch to 5g network? Can you test on a "normal" device, e.g. PC or Raspberry?
If the problem is due to the input stream, both clients should be affected in the same way. To make sure that it's not an input stream problem, you can feed in a wave file:
`stream = file:///<path/to/wavefile.wav>?name=file&sampleformat=44100:16:2`

**Comment by hav0ck** [comment]
I think the errors where that I was running an older version of Mopidy. Seems it didn't get updated when I ran 'sudo apt update'.
I was able to get updated to Mopidy 3 this weekend and TCP Stream is working with one client. I haven't been able to test with multiple clients yet.
