### ISSUE TITLE
Allow setting volume above 100 to boost signal

### ISSUE THREAD

**Issue by tmp6154** [badaix/snapcast#629]
Hello! When playing normalized audio, sometimes I would like to set volume on one snapclient to some value above 100 (I know what I'm doing, and I'm sure there's enough headroom for amplified signal without clipping).

Technically, it's currently possible to set volume of snapclient via direct request (I'm using a self-written script for managing volume) to values above 100, and they get saved, but they have no effect, playing at same volume as on volume 100.

I wonder, if it's possible to allow volume boosting, if it's set to something above 100. It would be useful for some use cases.

**Comment by jorgenkraghjakobsen** [comment]
Hi Vitaly 
I would call for the option that each client can do this kind of headroom adjustment per client. We need to add a layer where we can communicate and modify advance client settings like this - I have a long list of advanced feature I would like to add to this party. EQ, bass boost etc. 
Jakobsen

**Comment by tmp6154** [comment]
Hi Jørgen
Yes, that sounds like most universal solution. Would be nice to be able to fine tune various per-client options.

For my usecase I've ended up recompiling snapclient, changing condition here from _volume < 1.0_ to 100.0. This essentially lifts restriction of volume being attenuation-only option, allowing to specify values way over the 100 in order to achieve amplification of signal, easily granting capability to double or even triple original signal's strength, if needed.

https://github.com/badaix/snapcast/blob/9b0c27df7bfe5e57e08fb8ff318848a727c9b045/client/player/player.cpp#L68
