### ISSUE TITLE
[fix/workaround] Select server with a valid IP when 'Multiple servers found.'

### ISSUE THREAD

**Issue by constant-flow** [badaix/snapcast#632]
Somehow the client on MacOS detects/lists up multiple Snapcast servers.
The issue is the first entry has an empty ip `mDNSResult` and as this is picked by default, nothing is played back.

I added a little fix/workaround to [`browse_bonjour.cpp`](https://github.com/badaix/snapcast/blob/3f58875cddd468905d715a9680ae0c1487561000/client/browseZeroConf/browse_bonjour.cpp) after `l.244` to only pick a non-zero IP from all possibilities.

```
for (auto resultOption : resultCollection)
    {
        if (resultOption.ip.length() > 0)
        {
            result = resultOption;
            return true;
        }
    }
```

Doing this, I was able to connect to my RPi's snapcast server.

An alternative fix, would be to filter them out upfront.

Cheers for that great project and work 🙇‍♂️

**Comment by badaix** [comment]
Thanks, should be fixed with 79b14aa
