### ISSUE TITLE
No openwrt folder while Readme.md has reference to it

### ISSUE THREAD

**Issue by thanxx** [badaix/snapcast#633]
Hi, thanks for the awesome project

Just wanted to build snapclient for my router and discovered the lack of `openwrt` folder in the present code, however the readme file has the Openwrt section with `openwrt/Makefile` path .
Has something changed or am I missing something?

Would be thankful for the reply

**Comment by xabolcs** [comment]
OpenWrt build instructuons are in a separate repo:

https://github.com/badaix/snapos/blob/master/openwrt/README.md

Yeah,  the current doc is a little bit outdated, here in snapcast repo.

**Comment by badaix** [comment]
This is already fixed in [develop](https://github.com/badaix/snapcast/blob/develop/doc/build.md#openwrtlede-cross-compile) branch: the OpenWrt section is replaced by a link to [Snapos](https://github.com/badaix/snapos/blob/master/openwrt/README.md)
