### ISSUE TITLE
snapserver "unknown configuration option" messages in log

### ISSUE THREAD

**Issue by jonahquark81** [badaix/snapcast#635]
When I start snapserver I get 'unknown configuration' messages:

> Jun  6 10:11:53 multimedia snapserver[46496]: unknown configuration option: logging.filter
> Jun  6 10:11:53 multimedia snapserver[46496]: unknown configuration option: -d
> Jun  6 10:11:53 multimedia snapserver[46496]: unknown configuration option: -c
> Jun  6 10:11:53 multimedia snapserver[46496]: Settings file: "/var/lib/snapserver/server.json"
> Jun  6 10:11:53 multimedia snapserver[46496]: daemonizing
> Jun  6 10:11:53 multimedia snapserver[46497]: daemon started

I'm running on FreeBSD within an IOCage jail.  Despite the messages the options are being used - it is daemonizing and the config file is being read, although I'm not convinced the logging.filter is working as I've tried setting to debug and don't see any difference in the log.

FreeBSD rc options:
`# grep snap  /etc/rc.conf`
`snapserver_enable="YES"`
`snapserver_opts="-d -c /usr/local/etc/snapserver.conf"`

Logging section from /usr/local/etc/snapserver.conf

`# Logging options 
#############################################################`
`#`
`[logging]`
`#sink = system`
`filter = *:debug`
`#`
`###############################################################################`

**Comment by badaix** [comment]
this is fixed in develop branch fce34d82c8896683620b3f1ef9e47a7a62971102
