### ISSUE TITLE
Build fails because of changed links in externals

### ISSUE THREAD

**Issue by thanxx** [badaix/snapcast#637]
```
fatal: unable to access 'https://git.xiph.org/opus.git/': Failed to connect to ... port 443: Connection refused
```

https://www.opus-codec.org/development/
On the xiph dev page there are links to gitlab
`$ git clone https://gitlab.xiph.org/xiph/opus.git`

**Comment by badaix** [comment]
This is fixed in develop branch. Also you most probably don't need the externals, on a regular Linux distribution you can install the dependencies with your package manager.
