### ISSUE TITLE
Snapserver crashes

### ISSUE THREAD

**Issue by thanxx** [badaix/snapcast#639]
Just compiled snapclient for openwrt, it worked fine for some time with other android clients.
But recently I opened the android snapclient app and everything stopped. The server crashed.
I restarted the server in stdout mode and gathered some logs:

[snapcast.log](https://github.com/badaix/snapcast/files/4770885/snapcast.log)

snapserver v0.19.0

**Comment by badaix** [comment]
This should be fixed with b23255389ff1ab1ad3f17623200526c0ad745df1. Please try again with current master. The main problem seems to be that your OpenWRT client keeps disconnecting, I think it crashes and gets respawned.
