### ISSUE TITLE
Music crackling or stopping for miliseconds

### ISSUE THREAD

**Issue by rbuffi** [badaix/snapcast#641]
Hello,

I'm using the balenasound project (that's using badaix/snapcast) on a RPI3B with bluetooth disabled and USB sound card/speakers. I'm experiencing short crackling and stops during playback. The logging shows the following:

pMiniBuffer->full() && (abs(pMiniBuffer->mean()) > 50): -188630
pMiniBuffer->full() && (abs(pMiniBuffer->mean()) > 50): -183723

I'm not seeing any network drops.

Can you please help me to resolve this, because I really love this project!

Regards,

Ronald

**Comment by badaix** [comment]
Can you post logs with some more context?

**Comment by rbuffi** [comment]
Can you work with the following?

[balena_kef_egg_rpi-15.06.20_16_09_44_(+0200).txt](https://github.com/badaix/snapcast/files/4780773/balena_kef_egg_rpi-15.06.20_16_09_44_.%2B0200.txt)

**Comment by badaix** [comment]
Looks wires, as if your DAC would only play out 44050 samples per second instead of 44100. Snapclient is trying it's best to keep up sync, by removing 22 samples per second (that's the hard coded maximum: samplerate * 1.0005, i.e. play 0.5% faster, by dropping 22 samples per second).
Can you check if it happens with the RPI internal DAC?
Maybe your USB DAC performs better at 48kHz. You can configure resampling on command line with `--sampleformat 48000:16:*`

**Comment by rbuffi** [comment]
Hello I tried with --sampleformat 48000:16:2 and logs look better and no crackling or stops. But music is playing to fast now :)
How do I know the correct sampleformat for my DAC (Kef Egg)??

**Comment by rbuffi** [comment]
Attached the logfile
[balena_kef_egg_rpi-15.06.20_19_47_23_(+0200).txt](https://github.com/badaix/snapcast/files/4782010/balena_kef_egg_rpi-15.06.20_19_47_23_.%2B0200.txt)

**Comment by badaix** [comment]
you must use `--sampleformat 48000:16:*` as snapclient command line argument (`SNAPCLIENT_OPTS="--sampleformat 48000:16:*"` in `/etc/default/snapclient`), not as stream option. 
Don't know about your Kef Egg, google? Spec?

**Comment by rbuffi** [comment]
I will try in the client.
What I can find is (24-bit/96 kHz)max

**Comment by badaix** [comment]
And obviously quite bad at 44,1kHz ;)

**Comment by rbuffi** [comment]
I tried with --sampleformat 96000:24:* and sounding very good!
I will let you know ASAP if this is solved for good now!
Thank you very mutch!!
Speak to you soon!!

**Comment by badaix** [comment]
I would use 48kHz as it will use less CPU and seemed to be very precise (the numbers were close 0, especially the last one)

**Comment by rbuffi** [comment]
I changed to 48Khz and looking very good!!
You made my day.
Thank you so mutch for the quick and helpful responses!

librespot_playback::player] <Lonely Together (feat. Rita Ora)> loaded
16.06.20 00:27:28 (+0200) <snapcast-server> 2020-06-15 22-27-28 [Info] (onStateChanged) onStateChanged (default): 2
16.06.20 00:27:29 (+0200) <snapcast-client> 2020-06-15 22-27-29 [Info] (Stream) Chunk: -11	-11	-11	-11	1	63	0
16.06.20 00:27:30 (+0200) <snapcast-client> 2020-06-15 22-27-30 [Info] (Stream) Chunk: -10	-11	-11	-11	27	63	0
16.06.20 00:27:31 (+0200) <snapcast-client> 2020-06-15 22-27-31 [Info] (Stream) Chunk: -11	-11	-11	-11	58	43	0
16.06.20 00:27:32 (+0200) <snapcast-client> 2020-06-15 22-27-32 [Info] (Stream) Chunk: -11	-11	-11	-11	88	63	0
16.06.20 00:27:33 (+0200) <snapcast-client> 2020-06-15 22-27-33 [Info] (Stream) Chunk: -7	-9	-11	-11	119	43	13
16.06.20 00:27:34 (+0200) <snapcast-client> 2020-06-15 22-27-34 [Info] (Stream) Chunk: -3	-4	-10	-10	151	43	25
16.06.20 00:27:35 (+0200) <snapcast-client> 2020-06-15 22-27-35 [Info] (Stream) Chunk: 0	0	-6	-10	182	63	17
16.06.20 00:27:36 (+0200) <snapcast-client> 2020-06-15 22-27-36 [Info] (Stream) Chunk: 0	0	-1	-9	213	43	0
16.06.20 00:27:37 (+0200) <snapcast-client> 2020-06-15 22-27-37 [Info] (Stream) Chunk: 0	0	0	-6	245	43	0
16.06.20 00:27:38 (+0200) <snapcast-client> 2020-06-15 22-27-38 [Info] (Stream) Chunk: 0	0	0	-3	276	63	0
16.06.20 00:27:39 (+0200) <snapcast-client> 2020-06-15 22-27-39 [Info] (Stream) Chunk: 0	0	0	-2	307	43	0
16.06.20 00:27:40 (+0200) <snapcast-client> 2020-06-15 22-27-40 [Info] (Stream) Chunk: 0	0	0	0	338	63	0
16.06.20 00:27:41 (+0200) <snapcast-client> 2020-06-15 22-27-41 [Info] (Stream) Chunk: 0	0	0	0	369	43	0
16.06.20 00:27:42 (+0200) <snapcast-client> 2020-06-15 22-27-42 [Info] (Stream) Chunk: 3	0	0	0	401	43	0
16.06.20 00:27:43 (+0200) <snapcast-client> 2020-06-15 22-27-43 [Info] (Stream) Chunk: 0	0	0	0	432	63	0
16.06.20 00:27:44 (+0200) <snapcast-client> 2020-06-15 22-27-44 [Info] (Stream) Chunk: 0	0	0	0	463	43	0
16.06.20 00:27:45 (+0200) <snapcast-client> 2020-06-15 22-27-45 [Info] (Stream) Chunk: 0	0	0	0	495	43	0
16.06.20 00:27:46 (+0200) <snapcast-client> 2020-06-15 22-27-46 [Info] (Stream) Chunk: 0	0	0	0	500	63	0
16.06.20 00:27:47 (+0200) <snapcast-client> 2020-06-15 22-27-47 [Info] (Stream) Chunk: 0	0	0	0	500	43	0
16.06.20 00:27:48 (+0200) <snapcast-client> 2020-06-15 22-27-48 [Info] (Stream) Chunk: 0	0	0	0	500	63	0
16.06.20 00:27:49 (+0200) <snapcast-client> 2020-06-15 22-27-49 [Info] (Stream) Chunk: 0	0	0	0	500	43	0
16.06.20 00:27:50 (+0200) <snapcast-client> 2020-06-15 22-27-50 [Info] (Stream) Chunk: 0	0	0	0	500	43	0
16.06.20 00:27:51 (+0200) <snapcast-client> 2020-06-15 22-27-51 [Info] (Stream) Chunk: 0	0	0	0	500	63	0
16.06.20 00:27:52 (+0200) <snapcast-client> 2020-06-15 22-27-52 [Info] (Stream) Chunk: 9	0	0	0	500	43	0
16.06.20 00:27:53 (+0200) <snapcast-client> 2020-06-15 22-27-53 [Info] (Stream) Chunk: 0	0	0	0	500	43	0
16.06.20 00:27:54 (+0200) <snapcast-client> 2020-06-15 22-27-54 [Info] (Stream) Chunk: 0	0	0	0	500	63	0
16.06.20 00:27:55 (+0200) <snapcast-client> 2020-06-15 22-27-55 [Info] (Stream) Chunk: 0	0	0	0	500	43	0
16.06.20 00:27:56 (+0200) <snapcast-client> 2020-06-15 22-27-56 [Info] (Stream) Chunk: 0	0	0	0	500	63	0
16.06.20 00:27:57 (+0200) <snapcast-client> 2020-06-15 22-27-57 [Info] (Stream) Chunk: 0	0	0	0	500	43	0
16.06.20 00:27:58 (+0200) <snapcast-client> 2020-06-15 22-27-58 [Info] (Stream) Chunk: 2	0	0	0	500	43	0
16.06.20 00:27:59 (+0200) <snapcast-client> 2020-06-15 22-27-59 [Info] (Stream) Chunk: 0	0	0	0	500	63	0
16.06.20 00:28:00 (+0200) <snapcast-client> 2020-06-15 22-28-00 [Info] (Stream) Chunk: -1	0	0	0	500	43	0
16.06.20 00:28:01 (+0200) <snapcast-client> 2020-06-15 22-28-01 [Info] (Stream) Chunk: 0	0	0	0	500	43	0
16.06.20 00:28:02 (+0200) <snapcast-client> 2020-06-15 22-28-02 [Info] (Stream) Chunk: 0	0	0	0	500	63	0
16.06.20 00:28:03 (+0200) <snapcast-client> 2020-06-15 22-28-03 [Info] (Stream) Chunk: 0	0	0	0	500	43	0
16.06.20 00:28:04 (+0200) <snapcast-client> 2020-06-15 22-28-04 [Info] (Stream) Chunk: 0	0	0	0	500	63	0
16.06.20 00:28:05 (+0200) <snapcast-client> 2020-06-15 22-28-05 [Info] (Stream) Chunk: 0	0	0	0	500	43	0
16.06.20 00:28:06 (+0200) <snapcast-client> 2020-06-15 22-28-06 [Info] (Stream) Chunk: 0	0	0	0	500	43	0
16.06.20 00:28:07 (+0200) <snapcast-client> 2020-06-15 22-28-07 [Info] (Stream) Chunk: 0	0	0	0	500	63	0
16.06.20 00:28:08 (+0200) <snapcast-client> 2020-06-15 22-28-08 [Info] (Stream) Chunk: 0	0	0	0	500	43	0
16.06.20 00:28:09 (+0200) <snapcast-client> 2020-06-15 22-28-09 [Info] (Stream) Chunk: 0	0	0	0	500	43	0
16.06.20 00:28:10 (+0200) <snapcast-client> 2020-06-15 22-28-10 [Info] (Stream) Chunk: -1	0	0	0	500	63	0
16.06.20 00:28:11 (+0200) <snapcast-client> 2020-06-15 22-28-11 [Info] (Stream) Chunk: 0	0	0	0	500	43	0
16.06.20 00:28:12 (+0200) <snapcast-client> 2020-06-15 22-28-12 [Info] (Stream) Chunk: 23	0	0	0	500	47	0
16.06.20 00:28:13 (+0200) <snapcast-client> 2020-06-15 22-28-13 [Info] (Stream) Chunk: 0	0	0	0	500	43	0
16.06.20 00:28:14 (+0200) <snapcast-client> 2020-06-15 22-28-14 [Info] (Stream) Chunk: 0	-1	0	0	500	43	0
16.06.20 00:28:15 (+0200) <snapcast-client> 2020-06-15 22-28-15 [Info] (Stream) Chunk: 0	-1	0	0	500	63	0
16.06.20 00:28:16 (+0200) <snapcast-client> 2020-06-15 22-28-16 [Info] (Stream) Chunk: 0	-1	-1	0	500	43	0
16.06.20 00:28:17 (+0200) <snapcast-client> 2020-06-15 22-28-17 [Info] (Stream) Chunk: -1	-1	-1	0	500	43	0
16.06.20 00:28:18 (+0200) <snapcast-client> 2020-06-15 22-28-18 [Info] (Stream) Chunk: 7	0	-1	0	500	43	1
16.06.20 00:28:19 (+0200) <snapcast-client> 2020-06-15 22-28-19 [Info] (Stream) Chunk: 0	0	0	0	500	43	1
16.06.20 00:28:20 (+0200) <snapcast-client> 2020-06-15 22-28-20 [Info] (Stream) Chunk: -1	0	0	0	500	63	0
16.06.20 00:28:21 (+0200) <snapcast-client> 2020-06-15 22-28-21 [Info] (Stream) Chunk: -1	0	0	0	500	43	0
16.06.20 00:28:22 (+0200) <snapcast-client> 2020-06-15 22-28-22 [Info] (Stream) Chunk: 0	0	0	0	500	43	0
16.06.20 00:28:23 (+0200) <snapcast-client> 2020-06-15 22-28-23 [Info] (Stream) Chunk: 0	0	0	0	500	63	0
16.06.20 00:28:24 (+0200) <snapcast-client> 2020-06-15 22-28-24 [Info] (Stream) Chunk: 0	0	0	0	500	43	0
16.06.20 00:28:25 (+0200) <snapcast-client> 2020-06-15 22-28-25 [Info] (Stream) Chunk: -1	0	0	0	500	43	0
16.06.20 00:28:26 (+0200) <snapcast-client> 2020-06-15 22-28-26 [Info] (Stream) Chunk: -1	-1	0	0	500	63	0
16.06.20 00:28:27 (+0200) <snapcast-client> 2020-06-15 22-28-27 [Info] (Stream) Chunk: -1	0	0	0	500	43	0
16.06.20 00:28:28 (+0200) <snapcast-client> 2020-06-15 22-28-28 [Info] (Stream) Chunk: 0	0	0	0	500	63	0

**Comment by rbuffi** [comment]
Every few minutes I stil observe some hickups and see the same error:

16.06.20 00:36:25 (+0200)  snapcast-client  2020-06-15 22-36-25 [Info] (Stream) pMiniBuffer->full() && (abs(pMiniBuffer->mean()) > 50): -323024

I attached some new logfiles.

[balena_kef_egg_rpi-16.06.20_00_39_07_(+0200).txt](https://github.com/badaix/snapcast/files/4783326/balena_kef_egg_rpi-16.06.20_00_39_07_.%2B0200.txt)

**Comment by badaix** [comment]
It's not the same error, it rather looks like an issue with your librespot or how balena is connecting librespot with the snapserver. Librespot doesn't send audio for some > 100ms to the server, or it takes the server > 100ms to read 20ms audio, so the server has to "resync":
```
15.06.20 19:40:08 (+0200) <snapcast-client> 2020-06-15 17-40-08 [Info] (Stream) Chunk: 0	0	0	0	500	43	0
15.06.20 19:40:08 (+0200) <snapcast-server> 2020-06-15 17-40-08 [Info] (onResync) onResync (default): 150 ms
15.06.20 19:40:09 (+0200) <snapcast-client> 2020-06-15 17-40-09 [Info] (Stream) Chunk: -2302	0	0	0	500	43	0
15.06.20 19:40:09 (+0200) <snapcast-client> 2020-06-15 17-40-09 [Info] (Stream) pMiniBuffer->full() && (abs(pMiniBuffer->mean()) > 50): -230278
```

This doesn't happen with snapcast's librespot plugin and recent versions of snapcast/librespot.

**Comment by rbuffi** [comment]
I just tested and I don't think it's librespot related because I experience the same issue with airplay

**Comment by badaix** [comment]
and i assume that you're again not using the snapcast's airplay plugin. I don't know how balena forwards the audio to the pipe. Please try again without balena, but with pure snapcast server.

**Comment by chiefy** [comment]
Just a note: I was having an issue with crackling doing VLC output, and changed the snapserver default to `44000:16:2` to match my source and it sounds perfect now.
