### ISSUE TITLE
Is Snapcast Patent-free ?  

### ISSUE THREAD

**Issue by a22894** [badaix/snapcast#642]
I would like to check if Snapcast can be used for commercial products without patent issues . Does this has any conflicts with Sonos multi-room audio patents ?

**Comment by palitu** [comment]
i think you should check the license in which it is released.

**Comment by palitu** [comment]
https://github.com/badaix/snapcast/blob/master/LICENSE

**Comment by a22894** [comment]
Thanks. However I would like to know if snapcast implementation has ever used some technologies or approaches that have been patented by Sonos.

**Comment by badaix** [comment]
I hope not, I don't know of any Sonos patents, nor have I seen the Sonos sources. 
Snapcast can be used for commercial products, but mind the GPL copyleft: you have to make your source code available if you're using GPL licensed code.

**Comment by a22894** [comment]
Thanks for the info. For GPL , understood and definitely will follow when use it.

**Comment by a22894** [comment]
Sonos sued Google Chromecast about multi room  audio

https://www.cnbc.com/2020/02/06/sonos-ceo-patrick-spence-on-suing-google-over-patent-infringement.html

This was why I came up with this question about snapcast

**Comment by a22894** [comment]
https://www.geekwire.com/2020/sonos-vs-google-amazon-granted-patent-distributed-speaker-synchronization-four-years-ago/

**Comment by badaix** [comment]
yes, heard about that too. And last week [Google contersued Sonos](https://www.theverge.com/2020/6/11/21288161/google-countersues-sonos-patents-infringement)
Every synced audio server will have some kind of time sync and time stamped audio chunking in common. I hope that Sonos and other commercial products will have more sophisticated protocols than Snapcast, which is very simple.
