### ISSUE TITLE
Support for JACK audio system?

### ISSUE THREAD

**Issue by mxmilkiib** [badaix/snapcast#644]
Might it be possible to request a Snapcast [JACK](https://jackaudio.org) client app? For a Snapcast source in a JACK patchbay routing graph.

**Comment by badaix** [comment]
Don't even know if you're talking about the snapclient or server, but I'm always open for contributions :)

**Comment by mxmilkiib** [comment]
Thanks, I'm not a developer, but I thought I'd make the suggestion in case anyone might want to take up the task :)

I was meaning either a JACK backend to `snapclient`, or a simple standalone JACK client that acts as a `snapclient`.

Though, with you saying that, a JACK sink for Snapcast would be something interesting compared to the other [networked JACK](https://wiki.thingsandstuff.org/Audio#JACK_2) solutions.

**Comment by badaix** [comment]
Seems that no one is wanting to take this up

**Comment by mawe42** [comment]
@mxmilkiib Just a heads-up: I've created a draft PR with a Jack streamreader (#1241) and would love to get some more testing and feedback, if you are still interested.
