### ISSUE TITLE
Homebridge plugin for Snapcast

### ISSUE THREAD

**Issue by noelhibbard** [badaix/snapcast#646]
I wrote a homebridge plugin that lets you mute/unmute and change the volume of Snapclient's. If you aren't familiar with [Homebridge ](https://github.com/homebridge/homebridge) it is an opensource framework for making HomeKit accessories. The HomeKit API has a Speaker accessory type but for some reason Apple didn't implement it in the Home App. To work around this I am treating the snapclients are dimmable light bulbs. It's working well at my house.

Anyways, here is a link to my repo if anyone is interested:
https://github.com/noelhibbard/homebridge-snapcast

![](https://i.imgur.com/xalWqIw.png)

**Comment by artmg** [comment]
Thanks, that looks interesting. @badaix I wonder if there could be a `/doc/integrations.md` where we can include references to third party integrations like this.

**Comment by badaix** [comment]
Good point @artmg 
@noelhibbard there is a new file `doc/contributions.md`. You can add a short description in README.md#contributions and optionally add some more information and a screenshot in `doc/contributions.md` and link in README.md to it.
Please do this in the develop branch
