### ISSUE TITLE
Failure to build on ARMv61

### ISSUE THREAD

**Issue by slackline** [badaix/snapcast#651]
Hi,

I'm trying to build Snapcast on RaspberryPi ZeroW (ARMv61 chips) running [ArchLinux ARM](https://archlinuxarm.org/) using the [AUR : snapcast](https://aur.archlinux.org/packages/snapcast/) package.

The build fails (consistently across four devices, although thats not surprising since they are all identical!) with the following error...

```
...
make -C server                                                                                                                                                
make[1]: Entering directory '/home/user/aur/snapcast/src/snapcast-0.20.0/server'                                                                              
g++ -march=armv6 -mfloat-abi=hard -mfpu=vfp -O2 -pipe -fstack-protector-strong -fno-plt -O2  -std=c++14 -Wall -Wextra -Wpedantic -Wno-unused-function -DBOOST_ERROR_CODE_HEADER_ONLY -DHAS_FLAC -DHAS_OGG -DHAS_VORBIS -DHAS_VORBIS_ENC -DHAS_OPUS -DVERSION=\"0.20.0\" -I. -I.. -I../common -DHAS_AVAHI -DHAS_DAEMON -pthread -c snapserver.cpp -o snapserver.o
{standard input}: Assembler messages:
{standard input}:65959: Warning: end of file not at end of a line; newline inserted
{standard input}:66226: Error: unknown pseudo-op: `.asci'
g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[1]: *** [Makefile:110: snapserver.o] Error 1
make[1]: Leaving directory '/home/user/aur/snapcast/src/snapcast-0.20.0/server' 
make: *** [Makefile:11: server] Error 2 
==> ERROR: A failure occurred in build().
   Aborting...
```

If I then try the build again it fails a second time but with a different error message...

```
g++ -march=armv6 -mfloat-abi=hard -mfpu=vfp -O2 -pipe -fstack-protector-strong -fno-plt -O2  -std=c++14 -Wall -Wextra -Wpedantic -Wno-unused-function -DBOOST_ERROR_CODE_HEADER_ONLY -DHAS_FLAC -DHAS_OGG -DHAS_VORBIS -DHAS_VORBIS_ENC -DHAS_OPUS -DVERSION=\"0.20.0\" -I. -I.. -I../common -DHAS_AVAHI -DHAS_DAEMON -pthread -c control_server.cpp -o control_server.o
{standard input}: Assembler messages:
{standard input}:8731: Warning: end of file not at end of a line; newline inserted
{standard input}:8732: Error: ARM register expected -- `ldr'
g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[1]: *** [Makefile:110: control_server.o] Error 1
make[1]: Leaving directory '/home/user/aur/snapcast/src/snapcast-0.20.0/server'
make: *** [Makefile:11: server] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```

I've had no such problem when building on a RaspberryPi 3B also running ArchLinux, but the chip is ARMv71 rather than ARMv61.

If I can provide any more information that might help please let me know.

**Comment by badaix** [comment]
No idea, also the top google results don't help, maybe @mogwa1 can help you with this?

**Comment by mogwa1** [comment]
I don't know about this particular error; I haven't seen it myself.  I don't have any armv6 hardware actively running at the moment.  I could dig up an old Pi2 from the basement.  :-)

However, what I have noticed occasionally in the past was that the build fails because it runs out of RAM (also on armv7h by the way).  You can easily test this by temporarily creating and enabling a swapfile (https://wiki.archlinux.org/index.php/Swap#Swap_file).
If the package builds with a swapfile, then you know that the device was simply running out of memory.

**Comment by slackline** [comment]
Thank you @badaix and @mogwa1 for having a look at this.

It appears it is a memory issue as enabling a swapfile has allowed compilation.  Thanks again for your help @mogwa1
