### ISSUE TITLE
Snapclient sound distortion in jetson nano

### ISSUE THREAD

**Issue by cristianpb** [badaix/snapcast#655]
Hello, 

Thanks for this amazing project!

---

I installed snapcast in a Jetson Nano. Since there was no `.deb` package for arm64 architecture I had to compile from source. 

Snapserver works fine, I had some raspberrypi with snapclients connected and there is no problem.

However, when I install the snapclient in the Jetson Nano, everything seems fine, but the sound is distortioned. I recorded and audio playing a song with snapclient and with mplayer, it's attached in the following file: [sound-test.zip](https://github.com/badaix/snapcast/files/4872814/sound-test.zip)

I don't know if there is a special configuration or parameters that could help solving this problem.

**Comment by badaix** [comment]
can you run snapclient on command line with `--logfilter debug` and post the output of the first few seconds (until you can hear the distortions)?

**Comment by badaix** [comment]
No response, assuming to be solved
