### ISSUE TITLE
Deleting old clients

### ISSUE THREAD

**Issue by lealoureiro** [badaix/snapcast#656]
Hello!

I'm trying to delete old clients that don't exist anymore, they were created based on wifi mac address that i dont use anymore.

I tried to delete the client on server.json, but after reboot it appears again.

What is the best wait to delete/cleanup the client structure?

Regards,
Leandro

**Comment by TekniskSupport** [comment]
I use the android client, just press the three dots -> delete

Regards a random user / Iesus

**Comment by badaix** [comment]
There are several ways:
1. The easiest way is to use [Snapdroid](https://github.com/badaix/snapdroid) (on [Google Play](https://play.google.com/store/apps/details?id=de.badaix.snapcast&hl=gsw))
2. Write a script for it, there is an example how to fetch all client names [here](https://github.com/badaix/snapcast/blob/master/control/scripts.md). This list could be filtered by offline clients and piped to a delete script, PRs welcome :)
3. Edit server.json. Make sure to end the snapserver service before editing
4. Add this still missing feature to [Snapweb](https://github.com/badaix/snapweb), and make a PR, the logic is easy, but for me as a complete JS novice it's a several hours task to extend the UI in pure JS/CSS. The web UI will probably be shipped with future versions of Snapserver, and will then be the default way to get rid of old clients.

**Comment by TekniskSupport** [comment]
I created a pull request for 
- 2

check it out here
 https://github.com/badaix/snapcast/pull/658

Kind regards

**Comment by lealoureiro** [comment]
Thanks for all help! I will try the script!
