### ISSUE TITLE
Add libboost-dev to build instruction

### ISSUE THREAD

**Issue by TheStaticTurtle** [badaix/snapcast#660]
Just tried to build snapcast on my Kbuntu (Ubuntu with kde preinstalled) and could I just had to install libboost-dev.
Unfortunately it was too old 1.67 (required 1.7) So I also had to install it manually  using the testing source (https://packages.debian.org/bullseye/libboost-dev)

**Comment by badaix** [comment]
It's already stated in the build instructions:

> Snapcast depends on boost 1.70 or higher. Since it depends on header only boost libs, boost does not need to be installed, but the boost include path must be set properly: download and extract the latest boost version and add the include path, e.g. calling make with prepended ADD_CFLAGS: ADD_CFLAGS="-I/path/to/boost_1_7x_0/" make.
For cmake you must add the path to the -DBOOST_ROOT flag: cmake -DBOOST_ROOT=/path/to/boost_1_7x_0

**Comment by radusuciu** [comment]
@badaix I'm trying to compile snapcast (great project btw!) from source on a Raspi running Ubuntu 20.04, and have been running into issues surrounding boost. I've downloaded the boost sources and added the include path pointing to the directory where boost was downloaded but it does not work. I imagine there are some steps here that are implied in your instruction which may be obvious to someone more experienced compiling for source or working with boost, but they are not obvious to me. I'm now trying the following:

```bash
git clone --recursive https://github.com/boostorg/boost.git
cd boost 
./bootstrap.sh --prefix=/usr
./b2 headers
./b2 stage -j4 threading=multi
```

Per your instructions, I'm not doing `./b2 install`. Unfortunately, I'm running into other issues and it's a bit slow to debug. Is the above necessary?

Thanks!

**Comment by badaix** [comment]
What does not work?

**Comment by radusuciu** [comment]
@badaix I deleted my original comment since I came across your github workflow files which I believe I can use to get things running. Earlier I was naively adding the boost source directory to the includes via `ADD_CFLAGS`.

I can update once successful.
