### ISSUE TITLE
built-in stream merge and/or snapclient listen to multiple streams

### ISSUE THREAD

**Issue by jgabriel98** [badaix/snapcast#666]
This is a feature request motivated by the idea of having the possibility to give specific streams to the clients, but also a global stream.

The feature would be the capability to join two or more streams into one.
This would happen in the SnapServer process, and it would be configured in the `/etc/snapserver.conf` like this:
```
...
[stream]
# raspotify pipe stream
stream = pipe:///tmp/snapfifo?name=Spotify&sampleformat=44100:16:2
# shairport pipe stream
stream = pipe:///tmp/snapfifo_shairport?name=AirPlay&sampleformat=44100:16:2

stream = merge://Spotify,AirPlay?name=AllStreams
```

so it would be a functionality where it merges a list of named streams, into one new stream.

Requiring the sampleformat to be the same would make the implementation easier (i guess?)

this would solve a lot of issues and current workarrounds, since it is not possible to a single SnapClient to listen to multiple streams (at the same time). And looks more cleaner and lighter than to run multile snapClients in the same device ( one snapclient for each stream)

### Another possible solution:
It would solve the same problems, and add similar capabilities if it was possible to an client to listen/play multiple streams simultaneously.
So instead of a internal kind of mixer at **snapserver**, where it would join streams and create a new one from them.
The new feature would be to **snapclient** be capable of listening to more than one stream (from the same server).

**personal note**: Thanks for this amazing software! for real!

**Comment by badaix** [comment]
I've just added a `meta` stream source in develop branch: 27a9e710a215034b549f0ac352a031959ebccafe

```
[stream]
source = meta:///Spotify/Airplay/MPD?name=Meta&codec=flac
```

The meta stream has the usual settings like `sampleformat` or `codec`. It will apply resampling of the input streams if necessary.
Input streams are prioritized: first has highest priority, last has lowest priority. The above example would play web radio with MPD and whenever Spotify is started, it will become the active source.
There is still some fine tuning in the code and documentation to be done, but it's already usable.
