### ISSUE TITLE
[FR] Persistant Volumes/Muted Clients

### ISSUE THREAD

**Issue by diabl0w** [badaix/snapcast#667]
Would it be possible to have a persistent server.json in daemon mode? I have snapserver running on my openwrt router. I am not sure how to run it in not daemon mode or if that is even desirable, but I reboot my router every night so the next day when I play music it plays on every snapclient in my house which I do not want by default. I believe that server.json is stored in /var so it is lost every night at reboot.

**Comment by badaix** [comment]
It's configurable in `snapserver.conf`:
```
# directory where persistent data is stored (server.json)
# if empty, data dir will be
#  - "/var/lib/snapserver/" when running as daemon
#  - "$HOME/.config/snapserver/" when not running as daemon
#datadir = 
```

**Comment by diabl0w** [comment]
> It's configurable in `snapserver.conf`:
> 
> ```
> # directory where persistent data is stored (server.json)
> # if empty, data dir will be
> #  - "/var/lib/snapserver/" when running as daemon
> #  - "$HOME/.config/snapserver/" when not running as daemon
> #datadir = 
> ```

amazing! thanks! i must be running an old version
