### ISSUE TITLE
Mute 100% and random 100% on 1 core Snapclient

### ISSUE THREAD

**Issue by bjornstevens** [badaix/snapcast#669]
Today i made the following setup:

- Modipy(not RPI3) -> Snapcast Server(not RPI3) -> Snapcast Client (RPI3) -> Bluetooth(RPI3)  -> Bluetooth Speaker
- On my tablet i also have installed the snapcast client.

At the moment the snapcast client works really well on my tablet, no dropouts or any weird glitching.
The real problem i am facing right now is that the client on my RPI3 sometimes hits 100% on 1 core randomly (or when i mute the device) and sounds stops.
Usual cpu usage around 15%

After this happens i just restart the snapclient and it works for a random amount of time or when i mute it.

Here are some configuration items:
Server side: not really a lot to tell about (running on a snapcast docker) bitrate 44100
- snapserver -s pipe:///data/snapfifo?name=Mopidy_stream&sampleformat=44100:16:2

Client side: 
- Using onboard wifi for internet communication
- Using seperate USB Bluetooth dongle
- command: snapclient --host 10.10.0.1 --soundcard bluealsa --latency 150

**Comment by bjornstevens** [comment]
> 
> 
> Today i made the following setup:
> 
>     * Modipy(not RPI3) -> Snapcast Server(not RPI3) -> Snapcast Client (RPI3) -> Bluetooth(RPI3)  -> Bluetooth Speaker
> #########################################
> Here are some configuration items:
> Server side: not really a lot to tell about (running on a snapcast docker) bitrate 44100
> 
> Client side:
> 
>     * Using onboard wifi for internet communication

It might also be important to note that the tablet and RPI3 client are  in a different LAN than the server and modipy are. But as said before, tablet client works flawless.

**Comment by badaix** [comment]
Can you try the 0.18.1 client? The alsa player changed in v0.19 and caused 100% CPU usage on some systems which got fixed in v0.20, while keeping the updated playback logic of the v0.19.

**Comment by bjornstevens** [comment]
> 
> 
> Can you try the 0.18.1 client? The alsa player changed in v0.19 and caused 100% CPU usage on some systems which got fixed in v0.20, while keeping the updated playback logic of the v0.19.

Allright, will try that out. 
Any idea yet on the release date of 0.20?

**Comment by bjornstevens** [comment]
> 
> 
> Can you try the 0.18.1 client? The alsa player changed in v0.19 and caused 100% CPU usage on some systems which got fixed in v0.20, while keeping the updated playback logic of the v0.19.

i actually upgraded to 0.20, seems stable sometimes except for the muting. 
![afbeelding](https://user-images.githubusercontent.com/23235234/89225758-0c59fe80-d5db-11ea-984b-694a30771e65.png)


0.18.1 doesn't seem to work with this command:
> snapclient --host 10.10.0.203 --soundcard bluealsa --latency 150 -b 2000
i don't get any audio

**Comment by bjornstevens** [comment]
still sometimes seeing this and then sometime later connection loses. any way to fix this?
![afbeelding](https://user-images.githubusercontent.com/23235234/89448850-7ea41d80-d758-11ea-813d-8a3f34a7bb71.png)

**Comment by badaix** [comment]
Well, it's open source, you can try to fix it :).
There is a similar issue open on Snapdroid, maybe bluetooth is just not reliable enough to report buffer latencies.

**Comment by bjornstevens** [comment]
I am actually trying to increase the buffer with -b but can't seem to get it to work in snapserver.conf

**Comment by bjornstevens** [comment]
Figured the buffer out now 👍

**Comment by badaix** [comment]
A larger buffer will not help. The sync mechanism must be more tolerant. But this is unrelated to the 100% CPU, here a newer kernel might fix the problem. Anyways with BT you will never be able to play in sync, it's highly recommended to use line out.
