### ISSUE TITLE
snapcast on Fedora workstation 32

### ISSUE THREAD

**Issue by monkey3d** [badaix/snapcast#671]
Hello,
Installation tested on a Fedora workstation 32 64 bits system with boost version 1.74: ok.
Warning Fedora 32 is with boost 1.69 and you must therefore do the workaround suggested in the documentation.
The installation of snapserver and snapclient indicated in the doc does not work: sudo make install works.
Thank you

**Comment by badaix** [comment]
> The installation of snapserver and snapclient indicated in the doc does not work: sudo make install works

What is not working?

**Comment by monkey3d** [comment]
Hi,
[snapcast]$ sudo make installserver[sudo] Mot de passe : make: ***
Aucune règle pour fabriquer la cible « installserver ».
Arrêt.[snapcast]$ 
[snapcast]$ sudo make installclientmake: *** Aucune règle pour
fabriquer la cible « installclient ». Arrêt.[snapcast]$

	
	
	


[snapcast]$ sudo make install

[sudo]
Mot de passe: 


[
 6%] Built target common

[
67%] Built target snapserver

[100%]
Built target snapclient

Install
the project...

--
Install configuration: ""

--
Installing: /usr/local/bin/snapserver

--
Installing: /usr/local/bin/snapclient

[snapcast]$


Best regards.

**Comment by badaix** [comment]
I think you're mixing `cmake` and `make`. The guide refers to `make`.

**Comment by monkey3d** [comment]
Yes, it's true, sorry ! 
snapserver and snapclient work fine under Fedora 32 workstation.I
tested a configuration with 3 simultaneous clients.
I plan to test snapserver on Fedora 32 server 64 bits and Fedora 32
server on raspberry.
Best regards.
