### ISSUE TITLE
Feature Request : Allow snapclient to use hardware volume control, if present

### ISSUE THREAD

**Issue by fatg3erman** [badaix/snapcast#675]
Title says it all. I'm on a raspberry pi using a Pi DAC Pro, which has a hardware volume control.

Mopidy is capable of adjusting the volume on this device using its alsamixer plugin, but I can't see an option that permits snapclient to do the same.

**Comment by badaix** [comment]
hardware mixer can be enabled with the `--mixer` command line flag. `--mixer ?` should print some more information.

**Comment by fatg3erman** [comment]
Is there a minimum version required for that? 'snapclient -h' doesn't list a --mixer option, and --mixer ? just starts it running.

Rapsbian Buster only has 0.15.0.

Thanks.

**Comment by badaix** [comment]
You will need the 0.20, there are pre-built debian packages in [releases](https://github.com/badaix/snapcast/releases/tag/v0.20.0)

**Comment by fatg3erman** [comment]
Nice one, thanks. Works a treat.

--mixer=hardware:Digital
