### ISSUE TITLE
Add VLC example to the documentation

### ISSUE THREAD

**Issue by alessio-papi** [badaix/snapcast#676]
Hi,

I was able to configure VLC client on Raspberry PI in headless mode in order to use snapcast.
The VLC interface is telnet and also it's integrated in Home Assistat.

The command line is something like this:

vlc -I telnet --telnet-password your_password --no-video --aout afile --audiofile-file /tmp/snapfifo 

maybe it could be added to the client configuration guide.

HTH
Alessio

**Comment by TekniskSupport** [comment]
This is not an issue but a contribution, make a pull request instead

**Comment by alessio-papi** [comment]
Thanks, I tried to create the pul request... be patient... I'm a rookie on git.

**Comment by badaix** [comment]
Thanks, it's merged :)

**Comment by gribouk** [comment]
> Thanks, I tried to create the pul request... be patient... I'm a rookie on git.

Hi there! I am using VLC and want to have it with snapcast. Would you share a few words for a people like me if it could be a replacement for Mopidy?

**Comment by hrch3k** [comment]
I have tried alessio-papi's method but audio pitch is higher then the original and the stream is breaking. So i come up with shell script method. It can be found [Here](https://github.com/hrch3k/youtube-snapcast) if anyone wants to try it.
