### ISSUE TITLE
Snapserver issues

### ISSUE THREAD

**Issue by hbers** [badaix/snapcast#68]
Firstly I congratulate you for this great program. It's easy to set up and really easy to use but I have encountered some problems using snapserver. While the snapserver daemon is running, watching videos or playing music in the web browser is too laggy and most of the time video/audio doesn't even play. I'm not broadcasting a music player by the way, it's alsa being broadcasted to snapclient.

**Comment by badaix** [comment]
sorry, Snapcast is not intended to sync audio and video. By default the audio signal has a delay of 1s.
