### ISSUE TITLE
Intercom feature

### ISSUE THREAD

**Issue by jasonben** [badaix/snapcast#680]
What do you all think about implementing an intercom feature for snapclients? Google home has this feature.

**Comment by badaix** [comment]
Could you be a bit more specific?

**Comment by jasonben** [comment]
An option to broadcast a microphone input from snapclients to the snapserver.

**Comment by badaix** [comment]
in Snapcast audio is captured on the server and broadcasted to the clients. You can configure this using the alsa source plugin.
The other way round will not be supported (audio from client to server).
