### ISSUE TITLE
FR: snapclient as a source (output raw samples to stdout/pipe)

### ISSUE THREAD

**Issue by Zopieux** [badaix/snapcast#681]
Hello,

I've just learned about Snapcast, and this project is already running on my home server, phones & computers. This works just fine, thanks for developing this.

Here is a feature request: I need to read the audio stream, as snapclient would do, but then output the raw samples to stdout (instead of a sound card) so I can pipe it to another audio processing pipeline (say ffmpeg), with the end-goal of streaming to devices not supported by Snapcast today. One example that comes to mind is

    snapserver → snapclient "raw mode" → ffmpeg/gstreamer with hls sink → <any HLS-enabled device>

As you can see, the missing element is `snapclient "raw mode"`, a snapclient that would output S16LE samples directly to stdout so I could pipe them. Could this be added to snapclient as one of the (currently undocumented) `--player`? I've seen [file_player.cpp](https://github.com/badaix/snapcast/blob/master/client/player/file_player.cpp#L59-L68) but  couldn't get it to output samples that ffmpeg could read (distorted audio).

**Comment by badaix** [comment]
It should work to write the buffer_.data() to stdout (this is undocumented, because it's not finished, PRs are welcome ;)). Maybe the distortion comes from logging (going to stdout by default). You can use a different log sink with `--logsink`, e.g. `null` or `stderr`.
Or you play the audio into an alsa loopback device, and record the looped audio in gstreamer (the idea is described here: https://github.com/badaix/snapcast/blob/master/doc/configuration.md#alsa)

**Comment by Zopieux** [comment]
Thanks for the quick reply. I did exactly what you mentioned, aka. output data() to stdout & remove stdout clutter (I didn't both with --logsink, I just hacked the code) and piping to `ffplay -f u16le -ar 44100 -ac 2` (also tried signed & big-endian). I tried with and without calling `adjustVolume`. Sadly all my attempts resulted in basically noise garbage.

@badaix, I'd be happy to contribute a PR, but may I suggest you give it a try too and share the changes & format flags you used for playback, because at this point I'm not sure what to try next for this to work. Thanks for your help.

**Comment by badaix** [comment]
I've added this line `fwrite(buffer_.data(), 1, needed, stdout);` to master dcd8ddbf4369bcecbc97af39ce8868563e8bfe3e
When I pipe the output to aplay, I can hear cristal clear audio:
```
snapclient -h 192.168.0.3 --logsink null --player file |aplay -f dat
```

**Comment by Zopieux** [comment]
Amazing thanks! Not sure what I did wrong, but `ffplay -f s16le -ac 2 -ar 44100 -` works flawlessly now. I guess `--player file` covers my FR for now. This could use some documentation though.

**Comment by daniel-j** [comment]
I just tried it and I get bad stdout data from snapclient, compared to using a file or fifo. Snapclient prints `PCM device "default" not found` before the actual PCM data.
This line is the issue: https://github.com/badaix/snapcast/blob/7eff45fda7cadea9a5ce8829340d78da61da233d/client/snapclient.cpp#L388
Tested with `snapclient --logsink stderr --player file > file.raw`
I tried using -s null but still got the extra output.
A quick workaround I found was to pipe it through `tail -n +2`, which skips the first line of output.

**Comment by badaix** [comment]
Fixed with commit c88b2d1

**Comment by Zopieux** [comment]
Thanks, that `cout` gone lgtm. For your information @daniel-j.

**Comment by nadigo** [comment]
Hey, 

I'm trying to use this solution to pipe stream to [owntone](https://github.com/owntone/owntone-server) library folder. 
ownton is auto-playing music when it detects a stream in the folder, and the idea is to keep that stream pipe connected to a snapserver 'stream' so when there's music. owntone will play it automatically. 

For testing, I'm using am an airplay stream on snapserver and a snapclient with the below arg.

snapserver's /etc/snapserver.conf:
stream = airplay:///shairport-sync?name=Airplay&devicename=Airplay

Snapcient computer:
snapclient -h testvm.local --logsink null --player file | tail -n +2 > /srv/music/stream

How do I keep the stream ongoing while removing the 2 lines that are added every time I skip a song?
Any advice of the get such continuous pipe output with snapclient?

Thanks, 
Nadav
