### ISSUE TITLE
snapclient default audio output

### ISSUE THREAD

**Issue by bwaddington** [badaix/snapcast#683]
can someone help with snapclient default audio output will only play though hdmi how do i get it to play though 3.5mm please

**Comment by badaix** [comment]
You should at least write what hardware you're using.
Maybe the readme can help you: https://github.com/badaix/snapcast#test

**Comment by bwaddington** [comment]
Raspberry pi

**Comment by badaix** [comment]
Maybe the readme can help you: https://github.com/badaix/snapcast#test

**Comment by bwaddington** [comment]
That doesn't help i even reinstalled raspbian with the desktop so i could click on the speaker and change 3.5mm from hdmi and still it plays though hdmi everything thing else play though 3.5mm kodi vlc youtube on chrome

**Comment by badaix** [comment]
did you restart snapclient afterwards? 
If it doesn't help then you can still select the output device with the `-s` option. Available options are listed with the `-l` option.
