### ISSUE TITLE
3 clients running - the 4th (merus MA12070) is not recognized

### ISSUE THREAD

**Issue by 0x0lli** [badaix/snapcast#684]
badaix- thank you very much for your work, it has been a pleasure so far.

Due to a lack of linux understanding I was not able to fix the issues with Volumio v2.806 with SnapCast v2.4.3 and Volumio Spotify Connect2 v1.0.4 to run the setup the way I imagined when I started to realize my little multiroom project.

so I installed raspotify and snapcast on a Raspberry Pi OS and everything worked from the get-go.

The server is:
1. rPi4/hifiberry DAC+ (PiOS)

clients are: 
2. rpi3B+/ hifiberry AMP2 (volumio)
3. rpi0 / hifiberry miniamp (volumio)
4. rpi0 / infineon merus audio amp HAT ZW (volumio)

As SnapDotNet and Snapdroid were able to play every device in my network, I was impressed. (headphones, screen-speaker etc)

my problem is: The fourth device (with the merus 12070p-chipset) can be directly addressed from Spotify via the VolumioSpotifyConnect2-plugin and it works but due to something far from my understanding, that device, using the exact same settings as the other three running ones (server is running a client instance aswell) is neither identified by the snapserver, nor SnapDotNet or Snapdroid. I cannot start the service because "the service is masked" (the other two devices running volumio are not interested in this error.

Except for the server, all devices are running in WiFi mode. 
Is there a limit to the number of attachable wireless devices ?

The only thing that differs in the settings is the parameter in the client instance.
Due to my lack of ideas I appreciate your help.
Thanks in advance

![snapclients](https://user-images.githubusercontent.com/68810626/92405534-17520280-f136-11ea-8d4c-ba25c1df4a15.png)

**Comment by badaix** [comment]
There is no Snapcast version 2.4.3.
Can you start snapclient on the command line?
- Once without parameters (maybe with `-h`, but the host should be auto-detected)
- and once with `-s sndrpimerusamp`
and watch the log output for any errors.

What is the output of `snapclient -l`?
How did you install snapclient? Is it started by systemd? Then you also will not need the `-d` option (although it should work).

**Comment by 0x0lli** [comment]
thank you very much badaix.
Sorry for having mistakenly mixed up the dynfunctional Volumio-install-script for your work with your actual work.
Due to not being able to run some basic commands within volumio shell, I installed raspberry OS lite, snapclient (wget, then sudo apt install, configured dtoverlay=merus-amp and everything is running fine from the get-go. I might have picked up a bit more noise than before but that could be the speaker blown by the initial volume- merus hit it hard in the beginning, groundshaking :)
so I reckon the issue I had is either one with Volumio or the merus driver implementation for RaspberryOS. You might simply delete this thread as it is irrelevant for your work. Thank you very much for snapcast, it is a blessing. I envy you for your skills. Good luck with your projects!
