### ISSUE TITLE
Playing to the local Pulse over the network to Snapcast server does not work

### ISSUE THREAD

**Issue by gerroon** [badaix/snapcast#685]
Hi

I have a working Snapcast setup where I can divert Pulse streams to the Snapcast Pulse setup. This works perfect locally (where Snapserver is running)  but for some reason a network Pulse client cant seem to be able to play to this Snapcast stream setup. 

Remote  Pulse clients can play to the local Pulseserver alright but when I set the stream to the Snapcast's one (I use the Pulseaudio setup https://github.com/badaix/snapcast/blob/master/doc/player_setup.md#pulseaudio)  no audio is coming. 

This is the line that runs Airsonic. This setup can play to my local Pulseserver's outputs, except the Snapcast output.

`192.168.1.100` is the Pulseserver and the server that is running both the Snapserver and the Snapclient.

```

export PULSE_SERVER=192.168.1.100:4713
/usr/bin/java -Xmx768m  -Dserver.port=8282 -Dserver.context-path=/airsonic -jar /var/airsonic/airsonic.war 

```

**Comment by badaix** [comment]
Maybe you can use the [alsa plugin](https://github.com/badaix/snapcast/blob/master/doc/player_setup.md#alsa)

**Comment by gerroon** [comment]
Thanks but hitting an issue


```
stream = pipe:///tmp/snapfifo?mode=read&name=PCCast
stream = alsa://?name=PCAlsa&sampleformat=48000:16:2&device=hw:0,1,0

```

```

020-09-10 18-56-35.374 [Info] (PipeStream) PipeStream mode: read
2020-09-10 18-56-35.374 [Info] (start) Stream: {"fragment":"","host":"","path":"/tmp/snapfifo","query":{"chunk_ms":"20","codec":"flac","mode":"read","name":"PCCast","sampleformat":"48000:16:2"},"raw":"pipe:////tmp/snapfifo?chunk_ms=20&codec=flac&mode=read&name=DebToshCast&sampleformat=48000:16:2","scheme":"pipe"}
2020-09-10 18-56-35.374 [Notice] (start) StreamServer::start: Unknown stream type: alsa
2020-09-10 18-56-35.374 [Error] (main) Exception: Unknown stream type: alsa
2020-09-10 18-56-35.374 [Notice] (main) daemon terminated.

```

**Comment by brodie-g** [comment]
@gerroon . You may need to upgrade to the most recent snapcast version supporting alsa plugin. I believe you'll need 0.21.0. There are builds in the Actions page, for example armhf https://github.com/badaix/snapcast/actions/runs/247646771

**Comment by rio-** [comment]
Instead of going via ALSA you can use `module-pipe-sink` to have PulseAudio write chunks into a FIFO for snapcast. In my case, I configure PulseAudio as follows:

    load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1;192.168.178.0/24
    load-module module-zeroconf-publish
    load-module module-pipe-sink file=/tmp/pulsefifo sink_name=snapcast sink_properties=device.description=Snapcast

And snapcast:

    source = pipe:///tmp/pulsefifo?name=PulseAudio
