### ISSUE TITLE
snapcast server audio simultaneous output to snapcast clients and airplay speakers?

### ISSUE THREAD

**Issue by ioerror** [badaix/snapcast#688]
If I understand the shairplay-sync support for snapcast, it allows an airplay device to stream audio to the snapcast server which in turn plays to all the audio devices known to the snapcast server. This is useful but does not allow snapcast server to stream audio to airplay enabled devices which are unable to run the snapcast client. If I misunderstand the current shairplay-sync support, please correct me. I think this is an enhancement request as I would like to do the opposite. Specifically I would like to output snapcast server audio to all snapcast clients and also to all AirPlay devices.

By using pulseaudio and by configuring the snapcast server to read from pulseaudio, it seems possible to route audio data to a pulseaudio raop-sink or a set of them, as well as all the snapcast clients. I suspect that while the pulseaudio raop-sink module does its own latency measurement, it won't be properly in sync with the snapcast client latency measurements.

I'm curious if anyone has tried this approach and if it would be useful to explore? Is there any plan to enable the snapcast server to directly use AirPlay devices when the device cannot run the snapcast client?

**Comment by badaix** [comment]
The snapcast way of achieving this is to add an AirPlay audio sink in the snapclient. (could e.g. run on the same device as the server and configured to use an AirPlay sink towards a specific iDevice).
