### ISSUE TITLE
FR: Variable Sample Format

### ISSUE THREAD

**Issue by fatg3erman** [badaix/snapcast#689]
Firstly, the new ALSA loopback feature is fantastic, it's the answer to all my Mopidy-related problems so thank you for the work on that.

I'm wondering whether, now we can everything in ALSA-land, if this means we could have a stream that is not fixed to one audio format. I play music in 44100:16, 48000:16, and 96000:24 sample formats and (as a bit of an audio nerd) I'm never really happy with the fact that some of my listening is being resampled.

Is it feasible to have a stream the adjusts its parameters on the fly based on the source material?

**Comment by badaix** [comment]
This will not be possible without loosing synchronization between clients. All clients must close and reopen the audio device and get in sync again. 
After all, your DAC will have some native sample rate and will resample the input signal internally, as for example written [here](https://thewelltemperedcomputer.com/Intro/SQ/BitPerfectPlayback.htm):

> Many DACs do up-sampling. Often everything is up-sampled to e.g. 24/192.
Your data might be as bit perfect as possible, inside the DAC it is altered.
This is done by a DSP-chip, a microprocessor.
Compared with a PC they are down in power and precision. A PC can do everything in 64 bit float or even 128.

**Comment by fatg3erman** [comment]
Thanks for the reply, I thought it was worth asking. Not all DACs have a fixed native sample rate, many support automatic sample rate switching - the DAC Im using does, so when I'm using it directly with Mopidy I always get the DAC set to the same sample rate as the source so there is no resampling going on.

But I understand the difficulties regarding sync between clients, that would be hard i'm sure. I don't even know whether the resampling makes any audible difference, I just don't like it in principle :)
