### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [badaix/snapcast#69]
[An extra null pointer check is not needed in functions](http://dietmar-kuehl.de/mirror/c++-faq/freestore-mgmt.html#faq-16.8 "Do I need to check for NULL before delete p?") like the following.
* [FlacEncoder](https://github.com/badaix/snapcast/blob/a692e79ab560fd7e685fcc55e52916e023bc1590/server/encoder/flacEncoder.cpp#L37 "Destructor for FlacEncoder")
* [OpenslPlayer::uninitOpensl](https://github.com/badaix/snapcast/blob/a692e79ab560fd7e685fcc55e52916e023bc1590/client/player/openslPlayer.cpp#L340 "OpenslPlayer::uninitOpensl function")

**Comment by badaix** [comment]
How about a pull request? :wink:

**Comment by badaix** [comment]
done 21b4c6b9822b5109e0987aafc096e808676392db

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/badaix/snapcast/commit/21b4c6b9822b5109e0987aafc096e808676392db "Deletion of an unnecessary check").
Are there [a few update candidates left over](https://github.com/badaix/snapcast/blob/9e67b2ffe2624064a4c359548406a6c7fe279254/client/player/openslPlayer.cpp#L383 "Update candidate: OpenslPlayer::uninitOpensl()")?

**Comment by badaix** [comment]
Done. Wasn't aware that it's save to call `delete []` on a NULL pointer.

**Comment by elfring** [comment]
Thanks for [another small source code improvement](https://github.com/badaix/snapcast/commit/7a1c5d60aa9f890c09720d9a7518bf4787e0e1dd "Deletion of a few unnecessary checks").
