### ISSUE TITLE
Snapcast (snapclient) android randomly stops/ disconnects

### ISSUE THREAD

**Issue by bjornstevens** [badaix/snapcast#690]
Since a couple of days i have been a very active user of snapcast and I am experiencing random stops/disconnects from the android app. 
Sometimes after like 10 minutes it just randomly stops, I then go to the app, and my device shows up as disconnected/ not listening.
Is there any way to see where the issue is comming from? I also have another client that is connected via network cable (running on Linux Mint) that is working flawlessly.
Devices:
- Snapserver: Running in a docker (Linux) v 0.20
- Snapclient: running on Linux Mint V0.20
- Snapclient: running on android (latest update)

I have set the buffer on the server to 1000, did not make a change.

Any idea on what to do?
Thanks!

**Comment by gtsteffaniak** [comment]
I have also noticed latency values of 1000 or greater causing issues.

**Comment by badaix** [comment]
this looks rather like a [Snapdroid](https://github.com/badaix/snapdroid) issue.
Let's start with the basic questions: what phone, what android version, what APK version (from where)?
Please provide logs from your android device:
```
adb logcat --pid=`adb shell pidof -s de.badaix.snapcast`
```

**Comment by bjornstevens** [comment]
> this looks rather like a [Snapdroid](https://github.com/badaix/snapdroid) issue.
> Let's start with the basic questions: what phone, what android version, what APK version (from where)?
> Please provide logs from your android device:
> 
> ```
> adb logcat --pid=`adb shell pidof -s de.badaix.snapcast`
> ```

Running latest version (v 0.20.0) from the google play store.
My android device is an Samsung Galaxy Tab S5e running android 10 (samsung oneui 2.0)

I can't seem to figure out how to get the logs. I installed a terminal emulator app, but it did not understand the command. 

If interested; my wifi connection is running on 5GHz with a speed of around 400mbps and latency to my snapcast server of around 1 to 2ms.

**Comment by badaix** [comment]
you must run adb on a PC and connect with it to your device, e.g https://stackoverflow.com/questions/2604727/how-can-i-connect-to-android-with-adb-over-tcp
Can you check if there is some battery optimization active that could be disabled? Samsung is known to be quite aggressive with this.

**Comment by bjornstevens** [comment]
HI, I wasn't able to try out the logging thing. But I did try to run it on my phone, worked flawless there, while my tablet kept disconnecting. I think this has something to do with the tablet or so. I will post another update if I find something more.

**Comment by bjornstevens** [comment]
saw it got closed, haven't tested either. I switched from my tablet to a Linux machine. Works fine there (Ubuntu).
