### ISSUE TITLE
snapclient bluez-alsa support

### ISSUE THREAD

**Issue by gtsteffaniak** [badaix/snapcast#691]
The current implementation requires PulseAudio support which directly conflicts with bluez-alsa drivers. This has caused problems because I cannot get a snapcast client service running and output audio to a bluetooth speaker.

Example conflict:

```
root@host > apt install bluez-alsa
The following packages will be REMOVED:
  alsa-utils bluez libasound2 libasound2-dev libasound2-plugins pulseaudio pulseaudio-module-bluetooth snapclient
The following NEW packages will be installed:
  bluez-alsa

```

This appears because snapclient has libasound2 as a dependancy. I believe this is important because bluez-alsa is a more modern driver that will likely be more widely used than pulseaudio as time goes by.

**Comment by badaix** [comment]
What is this? A feature request, a bug report, a praise, a question, a comment?
