### ISSUE TITLE
Unknown stream type: alsa (in AUR package)

### ISSUE THREAD

**Issue by rio-** [badaix/snapcast#692]
I just built snapcast 0.21.0 for an x86_64 ArchLinux using the [AUR package](https://aur.archlinux.org/packages/snapcast/).

However, having a `source = alsa://…` entry in my config, the snapserver won't start anymore:

    2020-09-17 11-04-47.969 [Notice] (Server) Server::start: Unknown stream type: alsa
    2020-09-17 11-04-47.969 [Error] (main) Exception: Unknown stream type: alsa

The output of `snapserver -v` starts with `snapserver v0.21.0`, so it is indeed the new version.

Maybe some configuration went wrong during the build, but I'd need help to figure that out.

**Comment by badaix** [comment]
The AUR package is built using `make`, since I'm mainly using `cmake`, I forgot to add a flag in the makefile. It's now in, so the 0.21.1 or 0.22.0 AUR package should have support for `alsa` stream sources

**Comment by rio-** [comment]
Thanks, I've patched the makefile and rebuilt the package. ALSA sources are working now!

**Comment by mogwa1** [comment]
Hi, I'm the maintainer of the AUR package.
Just for my information: should I change the implementation to use `cmake`?  If so, could the documentation be updated as well, because currently it's only mentioning `make` as the build mechanism.
Thanks in advance!

**Comment by badaix** [comment]
Hi @mogwa1 , 
yes, `cmake` is the preferred way. I use it during development and recently changed the debian packaging to use cmake. Some things still need to be migrated to cmake, e.g. Android, the documentation and clang sanitizer builds.
I will update the documentation soon.
