### ISSUE TITLE
Making snapclient friendlier to other software using the same audio device

### ISSUE THREAD

**Issue by blauerbatzen** [badaix/snapcast#693]
I tried to run snapclient and shairport-sync on a RPi with raspian and ALSA. The goal is that snapcast streams continuously and if I stream with AirPlay it should be possible. My attempts with an ALSA dmix device were not succesful (no clear shairport output, snapclient error messages), but as I understand correctly it will never be as good as direct hardware access. So I experimented with the shairport-sync options to run a script before and after playback and came nearer to a solution:

Snapclient plays on the audio device. Then I start streaming to shairport-sync (same audio device configured). Shairport-sync runs a script to mute the snapclient. After 5sec the device becomes free and shairport-sync starts playing.

This works, if no hardware volume control in snapclient is used. If it is used muting the client will mute the device. So I suggest the following new features/enhancements:

1. Making the hw mixing mute part configurable (bidir as now,off,stream2device,device2stream)
2. Releasing the alsa device immediately after the mute command is arrived at the snapclient (and not wait 5seconds)

I have examined the code and I would be happy to contribute the changes at least for the hardware muting (1) part.

Thanks for your opinion.

**Comment by blauerbatzen** [comment]
@badaix What do you think about it? The Mute part is ready to merge.

**Comment by gtsteffaniak** [comment]
AFAIK snapcast's audio is all managed by .asoundrc linux file. You can either customize that file, use different linux users with seperate sound files, or perhaps run snapcast in a container to avoid conflict?

**Comment by badaix** [comment]
I'm struggling with this. It seems to be very special and it's hard to understand the muting options (stream2device, device2stream). Maybe pulse audio would be a solution for your setup.
