### ISSUE TITLE
Support for very high simulated latency >1s

### ISSUE THREAD

**Issue by Zopieux** [badaix/snapcast#695]
Hello,

I have a use-case where I need distribute the Snapcast stream to a device which does a fair bit of buffering – buffering that is out of my control.

Snapcast already allows me to introduce a positive 1000ms (1s) latency for that client at maximum – meaning other clients will have a simulated latency of 1s. This is not enough: I need more than 2s (maybe up to 6s) of fake latency for that slow device to be in sync with other devices in my home.

Is the maximum 1s latency a hard/physical limitation or some implementation detail? What's the rationale for that number, buffering memory usage on the server?

Could that limit be removed or increased? I don't mind spending more RAM, it's cheap!

Thanks for your help.

**Comment by almostserious** [comment]
You could try to set all the other clients to -6000ms.

**Comment by badaix** [comment]
I'm not aware of any limitation to 1000ms, maybe there is a check that a device latency should not exceed the global latency value.
In `snapserver.conf` is the end to end delay configured as

```
# Stream settings #############################################################
#
[stream]# Buffer [ms]
buffer = 1000
```
You must change this value to 6000ms, then it should be possible to configure a device latency of > 5000ms

**Comment by Zopieux** [comment]
Uh sorry should have checked my

**Comment by badaix** [comment]
Latency in Snapweb can now be configured in a range between -10s and +10s: 69c7c1d

**Comment by Zopieux** [comment]
Thanks, I suppose this is solved!
