### ISSUE TITLE
Feature Request - Install Snapcast on Steam Link

### ISSUE THREAD

**Issue by Hoerli1337** [badaix/snapcast#697]
Hello!
I just have a Steam Link here that is just lying around uselessly.
You can get SSH access via SSH file which is on a USB stick.
Then you have root access to the system.

Is it possible to install Snapcast on a Steam Link?
That would be great, because you could connect it to an AV receiver and play the stream via HDMI.
Kodi is already installed, but there is no working plugin for it, which works on the Steam Link.

**Comment by badaix** [comment]
Providing binaries is not in the scope of this project. It should be possible to compile snapcast for this device, maybe there is a tool chain available?
