### ISSUE TITLE
librespot kicks my soundcards (hifiberry DAC+) snapclient works only after restarting the client

### ISSUE THREAD

**Issue by 0x0lli** [badaix/snapcast#698]
hi,
after updating all devices within my setup to snapcast v.0.21, I wanted to switch the server from raspotify to librespot directly as raspotify had a lot of connection problems that were bugging me. A lot of recommendations in the official librespot-documentation were not working for the newest raspian image, 2020-08-20-raspios-buster-armhf-lite.

I used an entry in rc.local to run librespot from startup as it would not start with snapcast:
/home/pi/librespot/target/debug/librespot --backend pipe --device /tmp/snapfifo -n MUL71R00M

my /etc/snapserver.conf looks like this in the stream section, I did not change anything else:
pipe:///tmp/snapfifo?name=MUL71R00M&mode=read&dryout_ms=2000&sampleformat=44100:16:2
librespot:///home/pi/librespot/target/debug/?name=MUL71R00M&dryout_ms=2000&devicename=M111&bitrate=320&volume=100&nomalize=false&autoplay=false

thing is, as soon as the server (pi4) is finished booting, the LED on my hifiberry-DAC+-soundcard turns off and I have to manually restart the snapcast-client via "sudo /etc/init.d/snapclient restart" in order to have sound firing my primary stereo setup.
what I dont understand is that every other device running a client-instance of snapcast is served with music, only the server fails to directly start sound. I did try to manage the restart via rc.local and a few seconds of sleep in between but neither before nor after the starting sequence of librespot would work for the restart, the LED would light up a few seconds and then fade.
I am a beginner in linux and I read that one shouldnt use rc.local at all but that was my only chance to get librespot working as I didnt understand the dependencies that were required.
Any help would be appreciated, maybe its just my limited understanding of the parameter. I do not know what name and password are used for: spotify login? works without. OS-login? also, works without.

**Comment by badaix** [comment]
The filename for Librespot is missing:
```
source = librespot:///home/pi/librespot/target/debug/librespot?name=MUL71R00M&dryout_ms=2000&devicename=M111&bitrate=320&volume=100&nomalize=false&autoplay=false
```
Don't start librespot, Snapcast will start it for you (once you provide the full path and filename).

username and password are of course your optional spotify credentials.

**Comment by 0x0lli** [comment]
thank you very much for your fast response. 
I emptied rc.local and changed snapserver.conf to

pipe:///tmp/snapfifo?name=MUL71R00M&mode=read&sampleformat=44100:16:2
source = librespot:///home/pi/librespot/target/debug/librespot?name=MUL71R00M&devicename=MUL71&bitrate=320&volume=100&nomalize=false&autoplay=false

I tried a lot of settings with name and devicename. Now I am still stuck
In snapdroid, the device was named "MUL71R00M&dryout_ms=2000", so I removed this parameter, as I dont know what it is used for, now the name is MUL71R00M but still no action for the snapclient
