### ISSUE TITLE
to much logging

### ISSUE THREAD

**Issue by pille** [badaix/snapcast#7]
when i start snapclient on a limited resource pc running mint-14.04, after a while it starts logging several dozen lines per second:
```
[err] Failed to create simple poll object.
```

that uses CPU and RAM up to the point where the system swaps itself to death.
the whole time nothing is streamed to the box.

**Comment by badaix** [comment]
Hi, 

is this reproducable on your system? What HW is it exactly?
It might be fixed in the `develop` branch 635daabd8ce5b1167753ea5468572c2a799efb83:
* if it fails, the resources will be properly freed
* the client will wait 500ms before the next retry

**Comment by pille** [comment]
reported against 48ac9d2209f2eae01cc83c0c3d658d3d38081ceb, but not sure whether i actually tested an older binary on samsung SQ40S (32bit).
suggested 635daabd8ce5b1167753ea5468572c2a799efb83 seems not to trigger the bug for 1h now.
