### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [badaix/snapcast#70]
I guess that a different program design will be needed for your function "[signal_handler](https://github.com/badaix/snapcast/blob/c38f431d75fcb2a374fbcd6014d2b1107668e27c/common/signalHandler.h#L25 "Check signal handling implementation.")".
* The variable "g_terminated" should [use the data type "sig_atomic_t"](https://www.securecoding.cert.org/confluence/display/c/SIG31-C.+Do+not+access+shared+objects+in+signal+handlers "Do not access shared objects in signal handlers.") (instead of "bool").
* The function "[syslog](http://pubs.opengroup.org/onlinepubs/9699919799/functions/syslog.html "Log a message.")" does not belong to the list of [async-signal-safe functions](https://www.securecoding.cert.org/confluence/display/c/SIG30-C.+Call+only+asynchronous-safe+functions+within+signal+handlers "Call only asynchronous-safe functions within signal handlers.").

**Comment by badaix** [comment]
done

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/badaix/snapcast/commit/0e4bb57cfff2529dac45fa93b8ceba67721aa4e4 "Usage of sig_atomic_t").
Are there [a few update candidates left over](https://github.com/badaix/snapcast/blob/0e4bb57cfff2529dac45fa93b8ceba67721aa4e4/common/signalHandler.h#L27 "Check signal handling implementation once more.")?

**Comment by badaix** [comment]
What about a pull request?

**Comment by elfring** [comment]
Would you like to consider other software design options?
* [sigwaitinfo()](http://pubs.opengroup.org/onlinepubs/9699919799/functions/sigwaitinfo.html "wait for queued signals")
* [Self-pipe trick](http://cr.yp.to/docs/selfpipe.html "Use case description by Daniel J. Bernstein")
* [Signal-safe locks](http://locklessinc.com/articles/signalsafe_locks/ "lock-free algorithms")
