### ISSUE TITLE
Windows Client 0.21.0 not working

### ISSUE THREAD

**Issue by Hoerli1337** [badaix/snapcast#703]
Downloaded and unzipped the client.
After I first manually downloaded all DLL data for the codecs, I get the following error message:
The application could not start correctly (0xc000007b). Click "OK" to close the application.

Tried it on two Windows clients.

**Comment by rcmcronny** [comment]
I use the snap.net client https://github.com/stijnvdb88/Snap.Net/releases
And it seems in the snapcast win64 release archiv here, there are the codec dlls and some other missing ? 
Try the snap.net client, there should be all dlls included  :)

**Comment by badaix** [comment]
Yes, please use snap.net. I will remove the Windows version from releases, because I don't have a Windows machine available and cannot test if it's working (I once heard it's working).
