### ISSUE TITLE
OOM because chunks get buffered indefinitely

### ISSUE THREAD

**Issue by entropia1** [badaix/snapcast#708]
I have snapclient running on Linux, connected to a USB audio device. Whenever I turn off the audio device, it gets disconnected entirely, so ALSA doesn‘t know about it anymore. The first thing you notice is a whole lot of error messages like the following:

```
[Error] (Alsa) Exception in initAlsa: Can't open front:CARD=Device,DEV=0, error: No such device
```

The bigger problem, though, is that snapclient continues to buffer audio chunks, but never gets to use any of them, so the system quickly runs out of memory.

**Comment by badaix** [comment]
Actually, snapclient discards chunks older than 5 seconds. Does it really run out of memory on your system?

**Comment by entropia1** [comment]
I logged the `stream_`‘s `chunk_.size()` right where the above error gets logged and it kept increasing. It gets reset whenever I reconnect the USB device and playback resumes.
