### ISSUE TITLE
Snapcast optimizing

### ISSUE THREAD

**Issue by KraigoMpls** [badaix/snapcast#709]
I've been using Snapcast for quite a while now.  My initial experiences were not great.  Things got a lot better when I addressed network bandwidth.

Today I moved my server from a Pi3 to a Pi4 with its true GB throughput.  What was already pretty stable (a Pi3 with an external NIC to at least get past 100 Mb/s) seems much more stable.  Of course, this also makes a much more powerful CPU platform.  All the same, since I had a spare Pi4 sitting around, this was a really good move.

Since I'm writing, can I switch the server for the TCP stream without touching every client? I have almost a dozen clients and it's a large time commitment to go through all of them.  But I'm in server mode right now anyway.

Thanks for all of the joy you've given me.

**Comment by badaix** [comment]
The TCP stream (if you're talking about the server sided stream source) is not related to any client connection, it's a connection between your audio source and the server. Clients don't care about stream sources.
