### ISSUE TITLE
Snapweb not reachable?

### ISSUE THREAD

**Issue by jreusch** [badaix/snapcast#711]
I have just installed the latest snapcast version 0.22 on my raspberry pi and tried to reach the snapweb UI, but seem to have problems?

```
$ curl http://localhost:1780
The resource '/' was not found.
```
This error message seems to come directly from snapcast, but i cannot explain why it does not deliver snapweb?

Snapcast running with the following options
```
 [...] /usr/bin/snapserver --logging.sink=system --server.datadir=/var/lib/snapserver
```

Running snapserver with debug logging enabled only gives:
```
snapserver[24622]: ControlServer::NewConnection: 192.168.64.11
couchpi snapserver[24622]: ControlSessionHttp
couchpi snapserver[24622]: read: 82, method: GET, content type: , target: /, body:
couchpi snapserver[24622]: ControlSessionHttp::~ControlSessionHttp()
```

**Comment by badaix** [comment]
your `[http] doc_root` in `/etc/snapserver.conf` should point to your snapweb directory (default `/usr/share/snapserver/snapweb`).

**Comment by jreusch** [comment]
thx that fixed my problem! sorry i should have diffed the new config.
would try to make a PR to log something when snapweb is served/not served, would this be ok for you?

**Comment by l3d00m** [comment]
At least I would appreciate it @jreusch, I had the same issue as you and felt pretty dumb after figuring that out after a few hours.

**Comment by badaix** [comment]
Maybe we could serve a default web page if doc_root is not set or if the directory doesn't exist.
On the default page could be described where and how to configure the doc root.

**Comment by jreusch** [comment]
damn, just started to make a patch proposal but before creating a PR (and realizing that i should have branched of develop) saw that there is already some code in to handle it since a few days.
even more sophisticated! ;)
so thanks for taking this up!
