### ISSUE TITLE
alsa stream and snapserver daemon result in snapserver close

### ISSUE THREAD

**Issue by WMei0303** [badaix/snapcast#713]
**Describe the bug**

When I use alsa stream and start snapserver with daemon, snapserver would autoly close.
If I change the stream with pipe, it execute regularly.

**Steps to Reproduce**

This is my setting.

snapserver.conf
```
source = alsa://?name=test&device=snapout
codec = pcm
```

shell
` snapserver -d `

**Environment details**
- Linux buildroot 4.9.113 
- Snapcast version 2020/10/20 17:00 github master
- Installed from command `git clone https://github.com/badaix/snapcast.git`

**Attach logfile if applicable**

shell `snapserver -d --logging.filter debug`

```log
2020-10-20 10-13-27.802 [Info] (main) Adding source: alsa://?name=test&device=snapout
2020-10-20 10-13-27.803 [Notice] (init) Settings file: "/var/lib/snapserver/server.json"
2020-10-20 10-13-27.803 [Notice] (main) daemonizing
```
and then snapserver close.

**Comment by badaix** [comment]
That's what `-d` is meant for: daemonize, as the last log line states. I.e. fork and close yourself.

**Comment by WMei0303** [comment]
> daemonize

but I use shell  `ps | grep $(cat /var/run/snapserver/pid)`  it doesn't display anything

**Comment by badaix** [comment]
please start without `-d` to test on command line, maybe you have the same problem as #710
