### ISSUE TITLE
Snapclient service "snd_pcm_avail_delay failed: Broken pipe" Error

### ISSUE THREAD

**Issue by isakosh** [badaix/snapcast#714]
On a raspberry pi the latest (to 29/10/2020) version of snapserver and snapclient are installed.
The snapserver runs on a raspberry pi 1.
The snapclient runs on a raspberry pi 4.

When running the snapclient as a service the sound skips and the log outputs the following errors:

pi@raspberrypi:~ $ tail -f /var/log/syslog |grep -e snap
Oct 29 20:44:10 raspberrypi snapclient[1516]: snd_pcm_avail and snd_pcm_delay failed: Broken pipe, avail: -32, delay: 1016
Oct 29 20:44:11 raspberrypi snapclient[1516]: snd_pcm_avail_delay failed: Broken pipe, avail: 6000, delay: 6000, retrying.
Oct 29 20:44:11 raspberrypi snapclient[1516]: snd_pcm_avail_delay failed again: Broken pipe, avail: 6000, delay: 6000, using snd_pcm_avail and snd_pcm_delay.
Oct 29 20:44:11 raspberrypi snapclient[1516]: snd_pcm_avail and snd_pcm_delay failed: Broken pipe, avail: -32, delay: 6000
Oct 29 20:44:11 raspberrypi snapclient[1516]: snd_pcm_avail_delay failed: Broken pipe, avail: 10984, delay: 1016, retrying.
Oct 29 20:44:11 raspberrypi snapclient[1516]: snd_pcm_avail_delay failed again: Broken pipe, avail: 10984, delay: 1016, using snd_pcm_avail and snd_pcm_delay.
Oct 29 20:44:11 raspberrypi snapclient[1516]: snd_pcm_avail and snd_pcm_delay failed: Broken pipe, avail: -32, delay: 1016
Oct 29 20:44:12 raspberrypi snapclient[1516]: snd_pcm_avail_delay failed: Broken pipe, avail: 10992, delay: 1008, retrying.
Oct 29 20:44:12 raspberrypi snapclient[1516]: snd_pcm_avail_delay failed again: Broken pipe, avail: 10992, delay: 1008, using snd_pcm_avail and snd_pcm_delay.
Oct 29 20:44:12 raspberrypi snapclient[1516]: snd_pcm_avail and snd_pcm_delay failed: Broken pipe, avail: -32, delay: 1008
Oct 29 20:44:12 raspberrypi snapclient[1516]: snd_pcm_avail_delay failed: Broken pipe, avail: 6000, delay: 6000, retrying.
Oct 29 20:44:12 raspberrypi snapclient[1516]: snd_pcm_avail_delay failed again: Broken pipe, avail: 6000, delay: 6000, using snd_pcm_avail and snd_pcm_delay.
Oct 29 20:44:12 raspberrypi snapclient[1516]: snd_pcm_avail and snd_pcm_delay failed: Broken pipe, avail: -32, delay: 6000
Oct 29 20:44:12 raspberrypi snapclient[1516]: pMiniBuffer->full() && (abs(pMiniBuffer->mean()) > 50): 84348
Oct 29 20:44:13 raspberrypi snapclient[1516]: snd_pcm_avail_delay failed: Broken pipe, avail: 10984, delay: 1016, retrying.
Oct 29 20:44:13 raspberrypi snapclient[1516]: snd_pcm_avail_delay failed again: Broken pipe, avail: 10984, delay: 1016, using snd_pcm_avail and snd_pcm_delay.
Oct 29 20:44:13 raspberrypi snapclient[1516]: snd_pcm_avail and snd_pcm_delay failed: Broken pipe, avail: -32, delay: 1016
Oct 29 20:44:13 raspberrypi snapclient[1516]: snd_pcm_avail_delay failed: Broken pipe, avail: 10984, delay: 1016, retrying.
Oct 29 20:44:13 raspberrypi snapclient[1516]: snd_pcm_avail_delay failed again: Broken pipe, avail: 10984, delay: 1016, using snd_pcm_avail and snd_pcm_delay.
Oct 29 20:44:13 raspberrypi snapclient[1516]: snd_pcm_avail and snd_pcm_delay failed: Broken pipe, avail: -32, delay: 1016
Oct 29 20:44:14 raspberrypi snapclient[1516]: snd_pcm_avail_delay failed: Broken pipe, avail: 10992, delay: 1008, retrying.
Oct 29 20:44:14 raspberrypi snapclient[1516]: snd_pcm_avail_delay failed again: Broken pipe, avail: 10992, delay: 1008, using snd_pcm_avail and snd_pcm_delay.
Oct 29 20:44:14 raspberrypi snapclient[1516]: snd_pcm_avail and snd_pcm_delay failed: Broken pipe, avail: -32, delay: 1008
Oct 29 20:44:14 raspberrypi snapclient[1516]: snd_pcm_avail_delay failed: Broken pipe, avail: 10984, delay: 1016, retrying.
Oct 29 20:44:14 raspberrypi snapclient[1516]: snd_pcm_avail_delay failed again: Broken pipe, avail: 10984, delay: 1016, using snd_pcm_avail and snd_pcm_delay.
Oct 29 20:44:14 raspberrypi snapclient[1516]: snd_pcm_avail and snd_pcm_delay failed: Broken pipe, avail: -32, delay: 1016
Oct 29 20:44:15 raspberrypi snapclient[1516]: snd_pcm_avail_delay failed: Broken pipe, avail: 10984, delay: 1016, retrying.
Oct 29 20:44:15 raspberrypi snapclient[1516]: snd_pcm_avail_delay failed again: Broken pipe, avail: 10984, delay: 1016, using snd_pcm_avail and snd_pcm_delay.
Oct 29 20:44:15 raspberrypi snapclient[1516]: snd_pcm_avail and snd_pcm_delay failed: Broken pipe, avail: -32, delay: 1016
Oct 29 20:44:15 raspberrypi snapclient[1516]: snd_pcm_avail_delay failed: Broken pipe, avail: 6000, delay: 6000, retrying.
Oct 29 20:44:15 raspberrypi snapclient[1516]: snd_pcm_avail_delay failed again: Broken pipe, avail: 6000, delay: 6000, using snd_pcm_avail and snd_pcm_delay.
Oct 29 20:44:15 raspberrypi snapclient[1516]: snd_pcm_avail and snd_pcm_delay failed: Broken pipe, avail: -32, delay: 6000
Oct 29 20:44:16 raspberrypi snapclient[1516]: snd_pcm_avail_delay failed: Broken pipe, avail: 10976, delay: 1024, retrying.
Oct 29 20:44:16 raspberrypi snapclient[1516]: snd_pcm_avail_delay failed again: Broken pipe, avail: 10976, delay: 1024, using snd_pcm_avail and snd_pcm_delay.
Oct 29 20:44:16 raspberrypi snapclient[1516]: snd_pcm_avail and snd_pcm_delay failed: Broken pipe, avail: -32, delay: 1024
Oct 29 20:44:16 raspberrypi snapclient[1516]: snd_pcm_avail_delay failed: Broken pipe, avail: 10992, delay: 1008, retrying.
Oct 29 20:44:16 raspberrypi snapclient[1516]: snd_pcm_avail_delay failed again: Broken pipe, avail: 10992, delay: 1008, using snd_pcm_avail and snd_pcm_delay.
Oct 29 20:44:16 raspberrypi snapclient[1516]: snd_pcm_avail and snd_pcm_delay failed: Broken pipe, avail: -32, delay: 1008
Oct 29 20:44:17 raspberrypi snapclient[1516]: snd_pcm_avail_delay failed: Broken pipe, avail: 10992, delay: 1008, retrying.
Oct 29 20:44:17 raspberrypi snapclient[1516]: snd_pcm_avail_delay failed again: Broken pipe, avail: 10992, delay: 1008, using snd_pcm_avail and snd_pcm_delay.
Oct 29 20:44:17 raspberrypi snapclient[1516]: snd_pcm_avail and snd_pcm_delay failed: Broken pipe, avail: -32, delay: 1008
Oct 29 20:44:17 raspberrypi snapclient[1516]: snd_pcm_avail_delay failed: Broken pipe, avail: 10936, delay: 1064, retrying.
Oct 29 20:44:17 raspberrypi snapclient[1516]: snd_pcm_avail_delay failed again: Broken pipe, avail: 10936, delay: 1064, using snd_pcm_avail and snd_pcm_delay.
Oct 29 20:44:17 raspberrypi snapclient[1516]: snd_pcm_avail and snd_pcm_delay failed: Broken pipe, avail: -32, delay: 1064
Oct 29 20:44:18 raspberrypi snapclient[1516]: pMiniBuffer->full() && (abs(pMiniBuffer->mean()) > 50): 105311
Oct 29 20:44:18 raspberrypi snapclient[1516]: snd_pcm_avail_delay failed: Broken pipe, avail: 10976, delay: 1024, retrying.
Oct 29 20:44:18 raspberrypi snapclient[1516]: snd_pcm_avail_delay failed again: Broken pipe, avail: 10976, delay: 1024, using snd_pcm_avail and snd_pcm_delay.
Oct 29 20:44:18 raspberrypi snapclient[1516]: snd_pcm_avail and snd_pcm_delay failed: Broken pipe, avail: -32, delay: 1024
Oct 29 20:44:18 raspberrypi snapclient[1516]: snd_pcm_avail_delay failed: Broken pipe, avail: 10944, delay: 1056, retrying.
Oct 29 20:44:18 raspberrypi snapclient[1516]: snd_pcm_avail_delay failed again: Broken pipe, avail: 10944, delay: 1056, using snd_pcm_avail and snd_pcm_delay.
Oct 29 20:44:18 raspberrypi snapclient[1516]: snd_pcm_avail and snd_pcm_delay failed: Broken pipe, avail: -32, delay: 1056
Oct 29 20:44:19 raspberrypi snapclient[1516]: snd_pcm_avail_delay failed: Broken pipe, avail: 10992, delay: 1008, retrying.
Oct 29 20:44:19 raspberrypi snapclient[1516]: snd_pcm_avail_delay failed again: Broken pipe, avail: 10992, delay: 1008, using snd_pcm_avail and snd_pcm_delay.
Oct 29 20:44:19 raspberrypi snapclient[1516]: snd_pcm_avail and snd_pcm_delay failed: Broken pipe, avail: -32, delay: 1008
Oct 29 20:44:19 raspberrypi snapclient[1516]: snd_pcm_avail_delay failed: Broken pipe, avail: 10992, delay: 1008, retrying.
Oct 29 20:44:19 raspberrypi snapclient[1516]: snd_pcm_avail_delay failed again: Broken pipe, avail: 10992, delay: 1008, using snd_pcm_avail and snd_pcm_delay.
Oct 29 20:44:19 raspberrypi snapclient[1516]: snd_pcm_avail and snd_pcm_delay failed: Broken pipe, avail: -32, delay: 1008

when running from the command line the sound is OK
pi@raspberrypi:~ $ snapclient -s 15
2020-10-29 20-47-10.273 [Info] (Avahi) (Browser) NEW: service 'Snapcast' of type '_snapcast._tcp' in domain 'local'
2020-10-29 20-47-10.274 [Info] (Avahi) (Browser) CACHE_EXHAUSTED
2020-10-29 20-47-10.275 [Info] (Avahi) Service 'Snapcast' of type '_snapcast._tcp' in domain 'local':
2020-10-29 20-47-10.275 [Info] (Avahi)  LobiPi.local:1704 (10.100.102.10)
2020-10-29 20-47-10.277 [Info] (Controller) Found server 10.100.102.10:1704
2020-10-29 20-47-10.278 [Info] (Connection) Resolving host IP for: 10.100.102.10
2020-10-29 20-47-10.278 [Info] (Connection) Connecting
2020-10-29 20-47-10.281 [Notice] (Connection) Connected to 10.100.102.10
2020-10-29 20-47-10.281 [Info] (Connection) My MAC: "dc:a6:32:a8:d8:fb", socket: 8
2020-10-29 20-47-10.436 [Info] (Controller) ServerSettings - buffer: 1000, latency: 0, volume: 45, muted: 0
metadata:{"STREAM":"default"}
2020-10-29 20-47-10.438 [Info] (Controller) Codec: flac, sampleformat: 48000:16:2
2020-10-29 20-47-10.438 [Info] (Player) Player name: alsa, device: sysdefault:CARD=seeed2micvoicec, description: seeed-2mic-voicecard, bcm2835-i2s-wm8960-hifi wm8960-hifi-0
2020-10-29 20-47-10.438 [Info] (Player) Default Audio Device, idx: 15, sharing mode: unspecified, parameters: <none>
2020-10-29 20-47-10.438 [Info] (Player) Mixer mode: software, parameters: <none>
2020-10-29 20-47-10.438 [Info] (Player) Sampleformat: 48000:16:2, stream: 48000:16:2
2020-10-29 20-47-10.712 [Info] (Stream) no chunks available
2020-10-29 20-47-10.712 [Info] (Alsa) Failed to get chunk
2020-10-29 20-47-10.941 [Info] (Controller) diff to server [ms]: 3.46841e+06

**Environment details**
Raspbian (latest version)

the configuration file at /etc/temp/snapclient is :
START_SNAPCLIENT=true
SNAPCLIENT_OPTS=""

On the server the  asound.conf file is:

# The IPC key of dmix or dsnoop plugin must be unique
# If 555555 or 666666 is used by other processes, use another one

# use samplerate to resample as speexdsp resample is bad
defaults.pcm.rate_converter "samplerate"

pcm.!default {
    type asym
    playback.pcm "playback"
    capture.pcm "capture"
}

pcm.playback {
    type plug
#    slave.pcm rate48000Hz
    slave.pcm "dmixed"
}

pcm.rate48000Hz {
    type rate
    slave {
        pcm writeFile # Direct to the plugin which will write to a file
        format S16_LE
        rate 48000
    }
}

pcm.writeFile {
    type file
    slave.pcm "dmixed"
    file "/tmp/snapfifo"
    format "raw"
}

pcm.capture {
    type plug
    slave.pcm "array"
}

pcm.dmixed {
    type dmix
    slave.pcm "hw:seeed2micvoicec"
    ipc_key 555555 
}

pcm.array {
    type dsnoop
    slave {
        pcm "hw:seeed2micvoicec"
        channels 2
    }
    ipc_key 666666
}

Any help would be appreciated.

**Comment by badaix** [comment]
From your logs it's not visible what sound device is used when running as service, but maybe you should use the same: `SNAPCLIENT_OPTS="-s 15"`

**Comment by isakosh** [comment]
Tried it and that's the output:

Oct 30 11:29:39 raspberrypi snapclient[1620]: Exception: Can't set format: Invalid argument, supported: S32_LE
Oct 30 11:29:39 raspberrypi snapclient[1620]: daemon terminated.
Oct 30 11:29:39 raspberrypi systemd[1]: snapclient.service: Main process exited, code=exited, status=1/FAILURE
Oct 30 11:29:39 raspberrypi systemd[1]: snapclient.service: Failed with result 'exit-code'.
Oct 30 11:29:39 raspberrypi systemd[1]: snapclient.service: Service RestartSec=100ms expired, scheduling restart.
Oct 30 11:29:39 raspberrypi systemd[1]: snapclient.service: Scheduled restart job, restart counter is at 5.
Oct 30 11:29:39 raspberrypi systemd[1]: snapclient.service: Start request repeated too quickly.
Oct 30 11:29:39 raspberrypi systemd[1]: snapclient.service: Failed with result 'exit-code'.

that's the list of devices:

pi@raspberrypi:~/winshare $ snapclient -l
0: null
Discard all samples (playback) or generate zero samples (capture)

1: jack
JACK Audio Connection Kit

2: pulse
PulseAudio Sound Server

3: playback


4: capture


5: dmixed


6: array


7: default


8: output


9: sysdefault:CARD=Headphones
bcm2835 Headphones, bcm2835 Headphones
Default Audio Device

10: dmix:CARD=Headphones,DEV=0
bcm2835 Headphones, bcm2835 Headphones
Direct sample mixing device

11: dsnoop:CARD=Headphones,DEV=0
bcm2835 Headphones, bcm2835 Headphones
Direct sample snooping device

12: hw:CARD=Headphones,DEV=0
bcm2835 Headphones, bcm2835 Headphones
Direct hardware device without any conversions

13: plughw:CARD=Headphones,DEV=0
bcm2835 Headphones, bcm2835 Headphones
Hardware device with all software conversions

14: usbstream:CARD=Headphones
bcm2835 Headphones
USB Stream Output

15: sysdefault:CARD=seeed2micvoicec
seeed-2mic-voicecard, bcm2835-i2s-wm8960-hifi wm8960-hifi-0
Default Audio Device

16: dmix:CARD=seeed2micvoicec,DEV=0
seeed-2mic-voicecard, bcm2835-i2s-wm8960-hifi wm8960-hifi-0
Direct sample mixing device

17: dsnoop:CARD=seeed2micvoicec,DEV=0
seeed-2mic-voicecard, bcm2835-i2s-wm8960-hifi wm8960-hifi-0
Direct sample snooping device

18: hw:CARD=seeed2micvoicec,DEV=0
seeed-2mic-voicecard, bcm2835-i2s-wm8960-hifi wm8960-hifi-0
Direct hardware device without any conversions

19: plughw:CARD=seeed2micvoicec,DEV=0
seeed-2mic-voicecard, bcm2835-i2s-wm8960-hifi wm8960-hifi-0
Hardware device with all software conversions

20: usbstream:CARD=seeed2micvoicec
seeed-2mic-voicecard
USB Stream Output

**Comment by badaix** [comment]
Whatever your seeed2micvoicec device is, it seems to support only 32 bit. Either use resamling or change the device, to e.g. 9

**Comment by isakosh** [comment]
I don't think so.
It works when i open it directly snapclient -s 15.
I changed to stream to S32_LE and it still outputs the same error.
I can see that when i'm running snapclient as server it goes by default to output number 3 : playback which causes this errors and skips.
if i run snapclient -s 3 It is reproduced (the skips).
It seems that going thru playback causes it and i cannot redirect it to anything else because of the error.

**Comment by badaix** [comment]
You should attach the full log, the startup phase is especially interesting. You can either grep more from you syslog or let the client log to file (`--logsink file:<filename> --logfilter *:trace`). How did you change the stream to "S32_LE"? With `--sampleformat 48000:32:2`?
Is you asound.conf global or per user? This would make a difference between "direct" `-s 15` and service `-s 15`, because it's a different user.

**Comment by isakosh** [comment]
I tried changing the stream from the server redirecting to the pipe with 32 bits.

I'll get the log file an post it.
I'll have to check the asound.conf thing.
Linux isn't me "native language" so I'm still figuring things out.

**Comment by isakosh** [comment]
Hello,
So, I solved it.
the log file showed the same thing :

> 2020-10-31 12-59-42.726 [Info] (Connection) Resolving host IP for: Pi.local
> 2020-10-31 12-59-42.732 [Info] (Connection) Connecting
> 2020-10-31 12-59-42.734 [Notice] (Connection) Connected to 10.100.102.10
> 2020-10-31 12-59-42.735 [Info] (Connection) My MAC: "dc:a6:32:a8:d8:fb", socket: 9
> 2020-10-31 12-59-42.853 [Debug] (Connection) outstanding async_write
> 2020-10-31 12-59-42.853 [Trace] (Connection) Wrote 249 bytes to socket
> 2020-10-31 12-59-42.853 [Trace] (Connection) Wrote 34 bytes to socket
> 2020-10-31 12-59-42.868 [Info] (Controller) ServerSettings - buffer: 1000, latency: 0, volume: 49, muted: 0
> 2020-10-31 12-59-42.871 [Info] (Controller) Codec: flac, sampleformat: 48000:16:2
> 2020-10-31 12-59-42.871 [Info] (Player) Player name: alsa, device: dmix:CARD=seeed2micvoicec,DEV=0, description: seeed-2mic-voicecard, bcm2835-i2s-wm8960-hifi wm8960-hifi-0
> 2020-10-31 12-59-42.871 [Info] (Player) Direct sample mixing device, idx: 15, sharing mode: unspecified, parameters: <none>
> 2020-10-31 12-59-42.871 [Info] (Player) Mixer mode: software, parameters: <none>
> 2020-10-31 12-59-42.871 [Info] (Player) Sampleformat: 48000:16:2, stream: 48000:16:2
> 2020-10-31 12-59-43.148 [Error] (Alsa) Exception: Can't set format: Invalid argument, supported: S32_LE , code: 0
> 2020-10-31 12-59-43.148 [Debug] (Connection) Disconnecting
> 2020-10-31 12-59-43.148 [Debug] (Connection) Disconnected
> 2020-10-31 12-59-43.148 [Fatal] (Snapclient) Exception: Can't set format: Invalid argument, supported: S32_LE
> 2020-10-31 12-59-43.148 [Notice] (Snapclient) daemon terminated.

The only difference I could see is the user that starts the process vs the CLI.
**so I changed the user in the service to pi**
Using 
> sudo nano /lib/systemd/system/snapclient.service
I Set the following : 
**User=pi
Group=audio**

Now it works, not sure why and how but works...

**Comment by badaix** [comment]
maybe your asound.conf is in `/home/pi/.asound.conf` and not in `/etc/asound.conf` then it will only affect the pi user

**Comment by isakosh** [comment]
Nope,
it is in /etc/

I'll mark the case closed.
If you can recreate it maybe you'll see something i'm missing.

**Comment by badaix** [comment]
While searching for another issue, I found this one and the logs you attached in your first post look like the ones in #722 #727, maybe the current develop version fixes your issue.
