### ISSUE TITLE
"Failed to connect to host" when snapclient is running in same device than snapserver

### ISSUE THREAD

**Issue by jgabriel98** [badaix/snapcast#715]
### Bug description
**Only when** :

- just after powering up the machine
**_and_** 
- the machine have both snapclient and snapserver installed

, **sometimes** the snapclient fails to connect to the snapserver, and keeps trying (and failing) forever, unless i restart the service.

### Logs
given the following 2 logs from journalctl, where the first is when the snapclient fails, and the second is after it restarted

1º. when it fails (the bug):
<pre>
nov 03 19:57:30 raspberrypi snapclient[454]: (Browser) CACHE_EXHAUSTED
nov 03 19:57:30 raspberrypi snapclient[454]: (Browser) ALL_FOR_NOW
nov 03 19:57:31 raspberrypi snapclient[454]: (Browser) NEW: service 'Snapcast' of type '_snapcast._tcp' in domain 'local'
nov 03 19:57:31 raspberrypi snapclient[454]: (Browser) CACHE_EXHAUSTED
nov 03 19:57:32 raspberrypi snapclient[454]: (Browser) NEW: service 'Snapcast' of type '_snapcast._tcp' in domain 'local'
nov 03 19:57:32 raspberrypi snapclient[454]: (Browser) CACHE_EXHAUSTED
nov 03 19:57:32 raspberrypi snapclient[454]: <b>Service 'Snapcast' of type '_snapcast._tcp' in domain 'local':</b>
nov 03 19:57:32 raspberrypi snapclient[454]: <b>        raspberrypi.local:1704 (fe80::7382:f90f:ad93:46c7)</b>
nov 03 19:57:32 raspberrypi snapclient[454]: <b>Found server fe80::7382:f90f:ad93:46c7%4:1704</b>
nov 03 19:57:32 raspberrypi snapclient[454]: <b>Resolving host IP for: fe80::7382:f90f:ad93:46c7%4</b>
nov 03 19:57:32 raspberrypi snapclient[454]: <b>Connecting</b>
nov 03 19:57:32 raspberrypi snapclient[454]: <b>Failed to connect to host 'fe80::7382:f90f:ad93:46c7%4', error: Connection refused</b>
nov 03 19:57:32 raspberrypi snapclient[454]: <b>Error: Connection refused</b>
nov 03 19:57:32 raspberrypi snapclient[454]: <b>Error in socket shutdown: Transport endpoint is not connected</b>

nov 03 19:57:33 raspberrypi snapclient[454]: <b>Resolving host IP for: fe80::7382:f90f:ad93:46c7%4</b>
nov 03 19:57:33 raspberrypi snapclient[454]: <b>Connecting</b>
nov 03 19:57:33 raspberrypi snapclient[454]: <b>Failed to connect to host 'fe80::7382:f90f:ad93:46c7%4', error: Connection refused</b>
nov 03 19:57:33 raspberrypi snapclient[454]: <b>Error: Connection refused</b>
nov 03 19:57:33 raspberrypi snapclient[454]: <b>Error in socket shutdown: Transport endpoint is not connected</b>
...
the last 5 lines keeps repeating
....
</pre>

2º. when it works fine (in this example, after restarting the service/process):
<pre>
nov 03 19:58:40 raspberrypi systemd[1]: Started Snapcast client.
nov 03 19:58:40 raspberrypi snapclient[918]: (Browser) NEW: service 'Snapcast' of type '_snapcast._tcp' in domain 'local'
nov 03 19:58:40 raspberrypi snapclient[918]: (Browser) NEW: service 'Snapcast' of type '_snapcast._tcp' in domain 'local'
nov 03 19:58:40 raspberrypi snapclient[918]: (Browser) CACHE_EXHAUSTED
nov 03 19:58:40 raspberrypi snapclient[918]: <b>Service 'Snapcast' of type '_snapcast._tcp' in domain 'local':</b>
nov 03 19:58:40 raspberrypi snapclient[918]: <b>        raspberrypi.local:1704 (192.168.1.15)</b>
nov 03 19:58:40 raspberrypi snapclient[918]: <b>Found server 192.168.1.15:1704</b>
nov 03 19:58:40 raspberrypi snapclient[918]: <b>Resolving host IP for: 192.168.1.15</b>
nov 03 19:58:40 raspberrypi snapclient[918]: <b>Connecting</b>
nov 03 19:58:40 raspberrypi snapclient[918]: <b>Connected to 192.168.1.15</b>
nov 03 19:58:40 raspberrypi snapclient[918]: My MAC: "dc:a6:32:7a:10:c2", socket: 8
nov 03 19:58:40 raspberrypi snapclient[918]: ServerSettings - buffer: 1000, latency: 0, volume: 100, muted: 0
nov 03 19:58:40 raspberrypi snapclient[918]: Codec: flac, sampleformat: 48000:16:2
nov 03 19:58:40 raspberrypi snapclient[918]: metadata:{"STREAM":"Music"}
</pre>

### My guess:
We can see that in the first log (the one wich the bug occours) it connects to an _weird_ ipv6 ip, and fails. And in the second it connects to the "good" ipv4 and succeeds.

I think that, since both snap server and client are starting up, they **didn't connect to the network** yet, but the **snapclient found the snapserver internal/local tcp socket**, and tries to connect to it.\
and then we have two possibilities:
- snapclient and/or snapserver gets connected to the network, and somehow disturbs/break the ongoing connection from snapclient to snapserver
- or there is some bug (about permissions maybe?) for internal/local connection between snap client and server, when in the same machine.

and then it just keeps trying the same failed connection again and again.

## Steps to Reproduce
1. have both snapclient and snapserver on your system (set up as services) -> just install the .deb files
2. reboot your system.
3. check if the snapclient failed (the bug happened)
4. repeat step 2 and 3 until you get the bug.

**Environment details**
- OS: Raspbian
- Snapcast version 0.22.0
- Installed from .deb
- snapserver have two hidden(`&codec=null`) pipe streams\
and one meta stream, joining those 2 streams

**Comment by jgabriel98** [comment]
### Solutions that i think that would solve it

- Fix local/internal connection between snapclient and snapserver. (in other words: make snapclient and snapserver in the same machine possible, even without beeing connected to some external network)
- Make the snapclient stop trying to connect to the same server ip non-stop, and let it look for in the network when it becomes available.

**Comment by badaix** [comment]
This is a duplicate of #518 
The server is per default listening on IPv4 only (which is admittedly not the best choice for a default regarding that the server broadcasts it's IPv4 and IPv6 addresses).

You can either configure the server's IP address by adding `-h 127.0.0.1` to the client or let the server listen on both IPv4 and IPv6 addresses, with `bind_to_address = ::`:

```ini
# Stream settings #############################################################
#
[stream]
# address to listen on, can be specified multiple times
# use "0.0.0.0" to bind to any IPv4 address or :: to bind to any IPv6 address
# or "127.0.0.1" or "::1" to bind to localhost IPv4 or IPv6, respectively
# use the address of a specific network interface to just listen to and accept
# connections from that interface
bind_to_address = ::
#bind_to_address = 0.0.0.0
```

**Comment by jgabriel98** [comment]
Thanks for the quick response.

Oh i see, couldn't find the other issue because my assumptions where wrong.

Thank you very much, i will close this issue
