### ISSUE TITLE
Configuration of reverse proxy

### ISSUE THREAD

**Issue by rogorido** [badaix/snapcast#718]
**Is your feature request related to a problem? Please describe.**
Not strictly a problem, just a security concern.

**Describe the solution you'd like**
I would like to have reverse proxy (nginx if possible) in order to not open port 1780 in my server.

**Describe alternatives you've considered**

**Additional context**

(actually a question like this should be posed in a IRC channel, but...)

**Comment by badaix** [comment]
Is this Snapcast related or rather Snapweb?
Will this solve your problem? https://github.com/badaix/snapweb/pull/20

**Comment by TekniskSupport** [comment]
@rogorido 

If you're looking for help with nginx i don't think thats this is the correct forum, but would something like this do?

```
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}
server {
    listen 443 http2 ssl; 
    listen 4433 http2 ssl;
    server_name yoururl.tld;

    access_log /var/log/nginx/hass.access.log;
    error_log /var/log/nginx/hass.error.log;
    proxy_buffering off; 

    location / { 
       proxy_pass http://internal-ip:1780;
       proxy_set_header Host $host;
       proxy_redirect http:// https://;
       proxy_http_version 1.1;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       proxy_set_header Upgrade $http_upgrade;
       proxy_set_header Connection $connection_upgrade;
    }
    include /etc/nginx/snippets/tls.conf;
}

```

**Comment by rogorido** [comment]
@TekniskSupport thanks. This is the right direction. I get an error about resource not found, but I can investigate on my own.
