### ISSUE TITLE
Looking for a snapcast status monitor 

### ISSUE THREAD

**Issue by mrdago** [badaix/snapcast#72]
At the moment I'm building up a snapcast system consisting of  3 Raspberry PI2. Every PI is running Volumio 1.55 and spotify connect. One PI is setup as snapcast server&client, the others are configured as snapcast client only. The client only systems can be switched between multiroom and standalone mode. In multiroom mode snapclient is started and running , in standalone mode snapclient is stopped and mpd or spotify connect is active.

Changing the mode is done by running a bash script launched by a GPIO event or triggered from a GUI (actual I've ist only available on shell level). 
For more easy use it would be nice to have a small program "i.e. snapstatus" comparable to "mpc" to get status information from the snapserver and snapclient program.
- number of connected clients
- current status of snapclient (playing, waiting, ...)
- used audio channel by snapclient
- name of hosting snapserver
- ...

Currently I get this information using the following bash commands:

```
function mrm_get_status {
  if [ -z "$(pgrep -f snapclient)" ]
  then
    printf "stopped"
  else  
    if [ "$(grep RUNNING /proc/asound/card*/*p/sub*/status | wc -l)" == "1" ]
    then  
      printf "playing"
    else
      printf "active"
    fi
  fi
```

and

```
myip=$(sudo ifconfig  | grep 'inet addr:'| grep -v '127.0.0.1' | cut -d: -f2 | awk '{ print $1}')
mrm_client_count=$(sudo netstat -np | grep $myip:1704 | grep -c snapserver)
printf "$mrm_client_count"
```

Unfortunatley my programing skills are based on the the early nineties and I have no idea how much effort is behind such an implementation, but would appreciate if someone could spent the time for this task.

**Comment by badaix** [comment]
there is a not yet fully documented [JSON RPC API](https://github.com/badaix/snapcast/tree/develop/doc/json_rpc_api) for this purpose,
Maybe you can use this python lib: https://github.com/happyleavesaoc/python-snapcast

**Comment by happyleavesaoc** [comment]
You can get much of this information with that library as-is. You can also modify it to expose more data, as it fetches everything available. If you do, please feel free to submit a pull request.

**Comment by guikubivan** [comment]
I ended using that python library as well to run a bash script whenever a stream starts playing and a target client is not muted:

```
import asyncio
import snapcast.control
import subprocess

loop = asyncio.get_event_loop()
server = loop.run_until_complete(snapcast.control.create_server(loop, '192.168.0.66'))

def get_name(client):
    return client.friendly_name

client_names = list(map(get_name, server.clients))
target_client_index = client_names.index('raspberrypi')

def try_activate_audio_output():
    if not server.clients[target_client_index].muted:
        streams_status = list(map(lambda x: x.status, server.streams))
        print('checking')
        if 'playing' in streams_status:
            #print('activate')
            subprocess.run(["/usr/local/bin/activate_hdmi_source.sh"], shell=True)


def client_update(client):
    #print(client.muted)
    try_activate_audio_output()

def stream_update(stream):
    #print(stream)
    print(stream.status)
    if stream.status == 'playing':
        try_activate_audio_output()

server.clients[target_client_index].set_callback(client_update)

for stream in server.streams:
    stream.set_callback(stream_update)

# keep loop running to receive callbacks and to keep background task alive
loop.run_forever()
```


/usr/local/bin/activate_hdmi_source.sh:
```
if grep -q closed "/proc/asound/card1/pcm0p/sub0/status"; then
        exit 0
fi

echo 'on 3.0.0.0' | cec-client -s -d 1                                 
echo 'as 3.0.0.0' | cec-client -s -d 1  
```
