### ISSUE TITLE
add librespot device-type parameter

### ISSUE THREAD

**Issue by Digl** [badaix/snapcast#726]
Add librespot device-type parameter --> to display different icons in Spotify...

**Comment by badaix** [comment]
A feature request in imperative form?
You can follow the documentation and use the `params` parameter for this or add this feature and open a PR.

From the [docs](https://github.com/badaix/snapcast/blob/master/doc/configuration.md#librespot):
> params: Optional string appended to the librespot invocation. This allows for arbitrary flags to be passed to librespot, for instance params=--device-type%20avr. The value has to be properly URL-encoded.

**Comment by Digl** [comment]
ahh nice, sorry!!
Thanks
