### ISSUE TITLE
Possible to assign no source to a zone?

### ISSUE THREAD

**Issue by whc2001** [badaix/snapcast#730]
**Is your feature request related to a problem? Please describe.**
Is it possible to assign nothing to a zone (no sound at all for all speakers in that zone)?

**Describe the solution you'd like**
Something like "None" inside the Snapweb source picker would be nice.

**Comment by TekniskSupport** [comment]
You can mute a zone or speaker, or you can create a stream of nothing. Perhaps something like:
`stream = pipe:///dev/null?name=Silent`

**Comment by whc2001** [comment]
That worked, thanks!
