### ISSUE TITLE
Latency Client/Server about 1s

### ISSUE THREAD

**Issue by ralfluebben** [badaix/snapcast#731]
**Describe the bug**
The streaming latency between the client and server is at about 1s. The setup is Libreelec with snapserver 0.15 and HifiberryOS with snapclient 0.17.1. 

The audio is sent via pulseaudio to /tmp/snapfile and streamed via Wifi to the client.

Is this the default latency? Are there any knobs to tune for latency? May a more recent version reduce the latency?

**Steps to Reproduce**
1. Play a video with the default Libreelec/Kodi player.
2. System sounds are delayed, too.

**Environment details**
- OS: Libreelec/Kodi on Raspberry PI 
- Snapcast server version 0.15 /  HifiberryOS snapclient 0.17.1
- Installed from Libreelec repo, HifiberryOS default install

**Comment by rcmcronny** [comment]
Why did you nut try a more recent version ? 0.15  / 0.17 is very old, try it with 0.22 which is a much improved in many ways.
You do not really expect, to get help for such old stuff, do you ?

**Comment by ralfluebben** [comment]
Libreelec and HifiberryOS provide these versions by default. Reading the changelog of snapcast I haven't found any details on latency improvement on newer version. In another setup, I have on the server site version 0.22 with the same effect. At least for the libreelec setup the delay is easy quantifiable by adjusting the video/audio delay.

So my question is just, if there are any snapcast, pulseaudio, network configurations, which may improve this.

**Comment by rcmcronny** [comment]
That must not be note in changelogs, the last version did improve many things and got many new features. In the "Actions" is the 0.23 dev version with a pulse player and adjustable alsa functions (for example, see: https://github.com/badaix/snapcast/issues/722)

**Comment by badaix** [comment]
Please check #663 for an analysis where the latency is comming from.
In `snapserver.conf` the end to end latency can be configured with 
```
# Buffer [ms]
#buffer = 1000
```
Your version doesn't support the config file, but only command line arguments. Don't remember what argument it is, probably `--buffer`. You can check with `snapserver --help` or consult the man page.

**Comment by ralfluebben** [comment]
Using the recent development version, ALSA source and PCM encoding at the server reduces the delay to about 400ms.

Finally, reducing the minimum allowed buffer in snapserver.c below 400ms to 100ms reduces the delay obviously. Nevertheless, a bad network connection leads to late chunks at the receiver and audio outages.
