### ISSUE TITLE
Snapcast to Airport Express

### ISSUE THREAD

**Issue by vecchiae** [badaix/snapcast#744]
I have a whole house system with about 10 Airport Express driving my amp, which drives in wall wired speakers. The Airport Express are discovered through my network as Airplay.
As I am moving to Home Assistant  and I installed Snapserver on a Ubuntu VM. Obviously  I cannot install Snapclient on my airport express. 
Questions:
1. Would Snapserver be able to send music to my Airport Express Airplay ? 
2. I read, but I am unclear if I understand it correctly, that if I install Snapclient on the same VM of my Snapserver, I can use Snapclient to send music from the Snapserver to the Airport Express , but I couldn't find any examples, tutorial of the configuration necessary on Snapclient. Our maybe I misunderstood , and it can't be done.

**Comment by badaix** [comment]
What is an Airport Express?

**Comment by vecchiae** [comment]
An [Airport Express](https://en.wikipedia.org/wiki/AirPort_Express) an Apple Ethernet/wifi adapter that has two properties:
1. It has a Analog/digital audio output jack
2. it is a Airplay receiver

Airport Express adapters are used  to create a whole house audio:  you connect a number of  Airport Express to an ethernet switch (or via WiFI) and then you connect the audio jack of each of them to the input of a multi-room amplifier, which in turns drives speakers in different rooms.

Thus from any Apple product these adapters show up as Airplay receivers and you can pipe music from any device to any room without any additional software.

An Airport Express is what people replicate with a Raspberry + Shairport when they create a "Raspberry Airplay Receiver". The big difference is that I have no access to the Airport Express OS.

My issue is that I am not finding any tutorials on how Snapserver can "discover" an Airplay device (such as an iPad, an iPhone or an Apple TV - in my case the device is an Airport Express), and how to pipe music to them when you cannot install Snapclient on the device (as I assume is the case with an iPad or Apple TV, for example)

Sorry for the professorial, lengthy explanation

**Comment by badaix** [comment]
I'm afraid that this is not possible. The Snapclients do the audio rendering by using low level audio APIs (Linux: ALSA, Pulse, MacOs: CoreAudio, Windows: WASAPI, Android: AAudio, OpenSL ES) to be able to play in sync (by having low level control over the PCM device). It will not run on Airport devices. 
What snapcast can do is to receive audio from shairport and stream it to the connected Snapcast clients. If you want to feed audio into Airport receivers, you could add another audio sink in Snapclient that can connect to an Airport receiver (you can use `file_player.cpp` as starting point).

**Comment by vecchiae** [comment]
Thanks very much, will find a different path.
