### ISSUE TITLE
multiple librespot source

### ISSUE THREAD

**Issue by hiousi** [badaix/snapcast#746]
hi,

my setting:
```
source = librespot:///librespot?name=zone1&devicename=zone1&bitrate=320
source = librespot:///librespot?name=zone2&devicename=zone2&bitrate=320
```
Does not work, only one source will listen, the last one.

But if I use a process it's ok:
```
source = process:///librespot?name=zone1&params=--name%20zone1%20--bitrate%20320%20--backend%20pipe%20--initial-volume%20100%20--verbose
source = process:///librespot?name=zone2&params=--name%20zone2%20--bitrate%20320%20--backend%20pipe%20--initial-volume%20100%20--verbose
```

Do not know if it's a lot of work to make it work.

**Comment by Torgee** [comment]
Note that you need to set "killall=false" for all librespot streams - worked for me

**Comment by hiousi** [comment]
@Torgee you are right. It worked.
I did not notice this option.
Thanks

**Comment by badaix** [comment]
I will change the default to false in the next release. It's a legacy option that rather causes trouble than help.
