### ISSUE TITLE
Separate L/R channel transfer

### ISSUE THREAD

**Issue by GlebOlden** [badaix/snapcast#747]
Сan I transmit the right and left channel separately to 2 snapclients to organize a stereo pair?

**Comment by ashwinvandijk** [comment]
You can set them up as separate clients and let alsa only emit the left/right channel. I've done it the other way around: mixing both channels into 1 stream, as I have only one speaker in most of my clients. Take a look at `ttable`: https://wiki.archlinux.org/index.php/Advanced_Linux_Sound_Architecture/Configuration_examples

**Comment by GlebOlden** [comment]
@ashwinvandijk ok, thank you!

**Comment by badaix** [comment]
Separating channels is not possible, as suggested by @ashwinvandijk, you can configure your client to output just one channel.
