### ISSUE TITLE
snapcast looping fifo file from spotify-connect infinitely

### ISSUE THREAD

**Issue by 1337sup3rh4x0r** [badaix/snapcast#75]
Hi there,
i installed snapserver and snapclient (0.6.0) alongside with spotify-connect-web (https://github.com/Fornoth/spotify-connect-web) on a raspberry pi b+ running debian jessie.

Inside the spotify-connect-web-chroot, I created an asound.conf file in order to make spotify-connect use a file sink:
``/home/pi/spotify-connect-web-chroot/etc/asound.conf``

	pcm.!default {
	    type plug
	    slave.pcm rate48000Hz
	}

	pcm.rate48000Hz {
	    type rate
	    slave {
	        pcm writeFile # Direct to the plugin which will write to a file
	        format S16_LE
	        rate 48000
	    }
	}

	pcm.writeFile {
	    type file
	    slave.pcm null
	    file "/tmp/snapfifo"
	    format "raw"
	}

I changed the SNAPSERVER_OPTS inside the ``/etc/default/snapserver`` to ``SNAPSERVER_OPTS="-d -s pipe:///home/pi/spotify-connect-web-chroot/tmp/snapfifo?name=Spotify&mode=read"``
I also tried removing the ``&mode=read"`` part.

Basically everything is working fine now, when I start up spotify-connect and stream music to it, the music plays at all connected clients. 
I can watch the size of ``/home/pi/spotify-connect-web-chroot/tmp/snapfifo`` growing. 
But when I pause the playback in spotify, the snapserver starts playing the snapfifo file over again and again. 
The file keeps the same size at this point.
When I stop spotify-connect-web on the raspberry, snapcast keeps playing. 
The snapfifo file size still stays the same.
Only when I restart spotify-connect-web on the raspberry, the playback halts and the file size changes back to 0 until I stream something new.

What is going wrong here? Should spotify-connect delete the file content on pause?
How is the usual behaviour of the snapfifo file? Will it grow infinitely or should the content that has been streamed by the server be deleted by snapserver?

**Comment by mojitomo** [comment]
Hi,

Had the same problem today and found the solution:
you have to create snapfifo as a pipe. Otherwise just a normal file is created.
just run: 
`mknod spotify-connect-web-chroot/tmp/fifo p`

you may have to remove the old snapfifo file first.

**Comment by 1337sup3rh4x0r** [comment]
Thanks! I figured out that it is also solved when I deleted the file and then made sure I Start Snapserver before Spotify Connect web. Tgat also creates the correct fifo. I think The alsa conf file from the spotify chroot just creates a normal file if nothing by the defined Name is already there.
