### ISSUE TITLE
stream to existing sonos 

### ISSUE THREAD

**Issue by rmalchow** [badaix/snapcast#751]
hi,

i've been watching OSS multiroom audio solutions, and it used to be quite a mess. at it has been getting into shape more and more. so recently, i have started playing with a combo of jellyfin, mopidy and snapcast - and i have to say, it looks great so far.

now - i have had some sonos speakers for a long time. and when i start doing this migration, i would really love to have some way to keep using them with snapcast. is there any way to do this? basically using them as i would use other snapcast clients? 

.rm

**Comment by badaix** [comment]
Merged into #750
