### ISSUE TITLE
Build Fail on FreeBSD 12.2

### ISSUE THREAD

**Issue by dj-bauer** [badaix/snapcast#752]
**Description**
I just tried to build snapcast in a fresh freebsd jail.
I followed the general and for freebsd specifical guidelines.
But When I try to gmake, I get a compilation Error when trying to compile streamreader/pipe_stream.cpp

```
streamreader/pipe_stream.cpp: In member function 'virtual void streamreader::PipeStream::do_connect()':
streamreader/pipe_stream.cpp:61:27: error: 'F_GETPIPE_SZ' was not declared in this scope
   61 |     pipe_size = fcntl(fd, F_GETPIPE_SZ);
```

**Steps to Reproduce**
1. pkg install git
2. git clone https://github.com/badaix/snapcast.git
3. cd snapcast/externals
4. git submodule update --init --recursive
5. cd ../server
6. pkg install gmake gcc bash avahi libogg libvorbis opus flac libsoxr
7. gmake TARGET=FREEBSD

**Environment details**
- OS: FreeBSD 12.2-RELEASE
- Snapcast version: Latest git commit (bf7f986faa6e3920df24421a37b673947aa15735)
- Installation Method: Self compiling

I hope I am not doing something obvious wrong, and thanks for your help

**Comment by badaix** [comment]
Should be fixed with f254d59, can you please retry using the `develop` branch?

**Comment by dj-bauer** [comment]
Yeah, this works now.
When I now run 'gmake TARGET=FREEBSD install'
it throws the error
```
install -g wheel -o root -m 644 etc/index.html -Dt /usr/share/snapserver/
install: target directory `/usr/share/snapserver/' does not exist
```
when I manually create the directory, it fails at the same make step

```
install -g wheel -o root -m 644 etc/index.html -Dt /usr/share/snapserver/
install: -Dt: No such file or directory
gmake: *** [Makefile:128: install] Error 71
```

**Comment by badaix** [comment]
This is related to #720 (difference between Linux and Unix/BSD like commands).
As I don't have a BSD or macos available, it would be great if someone could fix it and make a PR.
