### ISSUE TITLE
Password support for airplay

### ISSUE THREAD

**Issue by chapterjason** [badaix/snapcast#754]
**Is your feature request related to a problem? Please describe.**
I'm currently working on a sound system which wraps the snapcast services and set configuration and restart the services.
Adding authentication for airplay is actually not possible, cause the query is not applied if I use this stream: `airplay:///shairport-sync?name=Airplay&devicename=Node-Test&password=admin`

**Describe the solution you'd like**
`shairport-sync` supports setting password via argument .

https://github.com/mikebrady/shairport-sync/blob/272b3db5ffdc7be6d21216c0b602fe02f0cdf3b6/man/shairport-sync.7.xml#L50

Copy the password from the query like the `devicename` would be a solution.

https://github.com/badaix/snapcast/blob/9fd61eeda3eea731cc0f48ca9365dfc1846ea89c/server/streamreader/airplay_stream.cpp#L55

**Describe alternatives you've considered**
Already thought about change the airplay default configuration, but I think it is easier to add support for the argument.

**Additional context**
-

**Comment by badaix** [comment]
Fixed ae16e74
