### ISSUE TITLE
dropouts / buffer size issue on Raspberry Pi

### ISSUE THREAD

**Issue by amitkeret** [badaix/snapcast#755]
Let me first say that I absolutely love Snapcast for its flexibility and have been using it for over a year. It can usually deal with anything I throw at it 👍 
I know there have been multiple previous bug reports on this buffer/dropout thing, but I haven't found one quite similar to my use case.

**Environment details**
- Snapcast server+client 0.20.0 installed on RPi 2 B v1.1
- Snapcast client 0.20.0 installed on RPi Zero W v1.1 (Raspbian Buster), connected to a BT speaker via `alsa`
```
/etc/snapserver.conf
stream = pipe:///tmp/snapfifo?name=SnapcastStereo

/etc/default/snapclient
START_SNAPCLIENT=true
SNAPCLIENT_OPTS="-s 1"
```

**Describe the bug**
Once I start playing to the RPi Zero client, the audio drops out almost immediately. This happens consistently and about 3-5 seconds after playback starts on the client. At the same time, the RPi 2 client plays without issues.

**Snapclient log**
```log
Jan 01 13:41:22 RPiZero snapclient[3221]: Codec: flac, sampleformat: 48000:16:2
Jan 01 13:41:22 RPiZero snapclient[3221]: Player name: alsa, device: btspeaker, description: Bluetooth Speaker, id
Jan 01 13:41:22 RPiZero snapclient[3221]: Mixer mode: software, parameters: <none>
Jan 01 13:41:22 RPiZero snapclient[3221]: Sampleformat: 48000:16:2, stream: 48000:16:2
Jan 01 13:41:23 RPiZero snapclient[3221]: diff to server [ms]: 9.6866e+08
Jan 01 13:41:27 RPiZero snapclient[3221]: No chunk received for 5000ms. Closing ALSA.
...
...
(playback starts here)
...
Jan 01 13:41:32 RPiZero snapclient[3221]: pShortBuffer->full() && (abs(shortMedian_) > 5): -8939
...
...
Jan 01 13:41:33 RPiZero snapclient[3221]: Exception: 0
Jan 01 13:41:33 RPiZero snapclient[3221]: Failed to get chunk
...
...
Jan 01 13:41:37 RPiZero snapclient[3221]: outputBufferDacTime > bufferMs: 27516200 > 1000
Jan 01 13:41:37 RPiZero snapclient[3221]: Failed to get chunk
```

I've read the issues #472 #442 #430 #428 which mention buffer size on the server, but please see the attached logs - it seems `outputBufferDacTime` is MUCH longer and unrealistic to define on the server.
I don't believe it's a network issue since I can play music synchronously by other means (eg. GHome speaker group)

Any ideas would be greatly appreciated.

**Comment by badaix** [comment]
Please try the latest develop version. A debian package is available under "actions"

**Comment by amitkeret** [comment]
Same issue with snapserver and snapclient 0.22.0

**Comment by badaix** [comment]
0.22 or latest snapshot?

**Comment by badaix** [comment]
Please attach a debug log (`--logfilter *:debug`). It seems that alsa cannot provide reliable latency information for the BT device.

**Comment by amitkeret** [comment]
I'm using 0.22.0, the release as I downloaded it from [here](https://github.com/badaix/snapcast/releases/latest).

Here's the output of `--logfilter *:debug`:
```
PCM device "default" not found
2021-01-03 12-01-33.707 [Info] (Avahi) (Browser) NEW: service 'Snapcast' of type '_snapcast._tcp' in domain 'local'
2021-01-03 12-01-33.718 [Info] (Avahi) (Browser) CACHE_EXHAUSTED
2021-01-03 12-01-33.723 [Info] (Avahi) Service 'Snapcast' of type '_snapcast._tcp' in domain 'local':
2021-01-03 12-01-33.725 [Info] (Avahi)  SnapcastServer.local:1704 (192.168.1.198)
2021-01-03 12-01-33.727 [Debug] (Avahi)         TXT=
2021-01-03 12-01-33.727 [Debug] (Avahi)         Proto=0
2021-01-03 12-01-33.728 [Debug] (Avahi)         cookie is 0
2021-01-03 12-01-33.729 [Debug] (Avahi)         is_local: 0
2021-01-03 12-01-33.731 [Debug] (Avahi)         our_own: 0
2021-01-03 12-01-33.731 [Debug] (Avahi)         wide_area: 0
2021-01-03 12-01-33.734 [Debug] (Avahi)         multicast: 1
2021-01-03 12-01-33.734 [Debug] (Avahi)         cached: 1
2021-01-03 12-01-33.744 [Info] (Controller) Found server 192.168.1.198:1704
2021-01-03 12-01-33.748 [Info] (Connection) Resolving host IP for: 192.168.1.198
2021-01-03 12-01-33.750 [Info] (Connection) Connecting
2021-01-03 12-01-33.840 [Notice] (Connection) Connected to 192.168.1.198
2021-01-03 12-01-33.840 [Info] (Connection) My MAC: "[ redacted :) ]", socket: 8
2021-01-03 12-01-36.054 [Debug] (Connection) outstanding async_write
2021-01-03 12-01-36.562 [Info] (Controller) ServerSettings - buffer: 1000, latency: 0, volume: 33, muted: 0
metadata:{"STREAM":"Snapcast"}
2021-01-03 12-01-36.565 [Info] (Controller) Codec: flac, sampleformat: 48000:16:2
2021-01-03 12-01-36.567 [Info] (Player) Player name: alsa, device: default, description: <none>, idx: -1, sharing mode: unspecified, parameters: <none>
2021-01-03 12-01-36.569 [Info] (Player) Mixer mode: software, parameters: <none>
2021-01-03 12-01-36.571 [Info] (Player) Sampleformat: 48000:16:2, stream: 48000:16:2
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5047:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM default
2021-01-03 12-01-36.631 [Error] (Alsa) Exception: Can't open default, error: No such file or directory, code: -2
2021-01-03 12-01-36.637 [Debug] (Connection) Disconnecting
2021-01-03 12-01-36.640 [Debug] (Connection) Disconnected
2021-01-03 12-01-36.646 [Fatal] (Snapclient) Exception: Can't open default, error: No such file or directory
2021-01-03 12-01-36.648 [Notice] (Snapclient) daemon terminated.
```

**Comment by TekniskSupport** [comment]
It doesn't seem to find your sound card, make sure that the the user you are running snapclient as has access to the sound card device

what is the output of `snapclient -l`

**Comment by amitkeret** [comment]
Thanks for chipping in @TekniskSupport 
I run `snapclient` as a `systemd` service, As I'm only using the BT speaker, I don't have a `pcm.!default` definition, but have defined the BT speaker and specified it in the `-s` switch for `snapclient`.

Contents of `/etc/asound.conf`
```
defaults.bluealsa {
        interface "hci0"
        device "[MAC address of my BT speaker]"
        profile "a2dp"
}

pcm.btspeaker {
        type plug
        slave.pcm {
                type bluealsa
                device "[MAC address of my BT speaker]"
                profile "a2dp"
        }
        hint {
                show on
                description "Bluetooth Speaker"
        }
}
ctl.btspeaker.type bluetooth
```

Output of `sudo snapclient -l`
```
0: null
Discard all samples (playback) or generate zero samples (capture)

1: btspeaker
Bluetooth Speaker
```

Contents of `/etc/default/snapclient`
```
START_SNAPCLIENT=true
SNAPCLIENT_OPTS="-s 1"
```

Just to clarify, I can get other programs to pass sound to the BT speaker with this configuration in `asound.conf`. For example, `omxplayer -o alsa:btspeaker music.mp3` works just fine.

**Comment by TekniskSupport** [comment]
Hi again,

systemd services can run as any user, default from package install i belive is the snapclient user.

So in order to make sure it works with snapclient -l
you need to do sudo -u snapclient snapclient -l

You can also try running the snapclient manually as root with
`sudo snapclient -s 1`

if that works you may need to add the group audio to whichever user that needs to use it with something like
`usermod -Ag audio user`

**Comment by amitkeret** [comment]
Thanks again @TekniskSupport
Your reply made me realise that I didn't add snapclient to `bluetooth` group... unfortunately that's made no difference 😞 

```
$ sudo -u snapclient snapclient -l
0: null
Discard all samples (playback) or generate zero samples (capture)

1: btspeaker
Bluetooth Speaker

$ sudo adduser snapclient audio
The user `snapclient' is already a member of `audio'
$ sudo adduser snapclient bluetooth
Adding user `snapclient' to group `bluetooth' ...
Adding user snapclient to group bluetooth
Done.
```

Here's the log from `systemctl status snapclient`
```
...
...
Jan 04 23:27:22 RPiZero snapclient[26127]: pShortBuffer->full() && (abs(shortMedian_) > 5): -13510
Jan 04 23:27:32 RPiZero snapclient[26127]: pBuffer->full() && (abs(median_) > 2): 2219
Jan 04 23:27:40 RPiZero snapclient[26127]: pBuffer->full() && (abs(median_) > 2): 2071
Jan 04 23:27:49 RPiZero snapclient[26127]: pBuffer->full() && (abs(median_) > 2): 2242
Jan 04 23:27:58 RPiZero snapclient[26127]: pBuffer->full() && (abs(median_) > 2): 2350
Jan 04 23:28:06 RPiZero snapclient[26127]: Failed to get chunk
Jan 04 23:28:06 RPiZero snapclient[26127]: outputBufferDacTime > bufferMs: 27439828 > 1000
Jan 04 23:28:06 RPiZero snapclient[26127]: Failed to get chunk
Jan 04 23:28:06 RPiZero snapclient[26127]: outputBufferDacTime > bufferMs: 27439827 > 1000
Jan 04 23:28:06 RPiZero snapclient[26127]: Failed to get chunk
Jan 04 23:28:06 RPiZero snapclient[26127]: outputBufferDacTime > bufferMs: 27439827 > 1000
Jan 04 23:28:06 RPiZero snapclient[26127]: Failed to get chunk
Jan 04 23:28:06 RPiZero snapclient[26127]: outputBufferDacTime > bufferMs: 27439827 > 1000
Jan 04 23:28:06 RPiZero snapclient[26127]: Failed to get chunk
Jan 04 23:28:06 RPiZero snapclient[26127]: outputBufferDacTime > bufferMs: 27439826 > 1000
Jan 04 23:28:09 RPiZero snapclient[26127]: Failed to get chunk
Jan 04 23:28:09 RPiZero snapclient[26127]: outputBufferDacTime > bufferMs: 27410204 > 1000
...
...
(outputBufferDacTime error keeps repeating)
```
Running snapcast as root made no difference, resulted in same error.

Here's `--logfilter *:debug` again, seems not to have improved
```
...
...
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5047:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM default
2021-01-04 23-38-00.697 [Error] (Alsa) Exception: Can't open default, error: No such file or directory, code: -2
2021-01-04 23-38-00.698 [Debug] (Connection) Disconnecting
2021-01-04 23-38-00.700 [Debug] (Connection) Disconnected
2021-01-04 23-38-00.701 [Fatal] (Snapclient) Exception: Can't open default, error: No such file or directory
2021-01-04 23-38-00.702 [Notice] (Snapclient) daemon terminated.
```

**Comment by badaix** [comment]
@TekniskSupport also told you to start Snapclient with `-s 1`, so that it will actually use your bluetooth speaker, just as you did in your `SNAPCLIENT_OPTS`. So please stop the service `sudo service snapclient stop` and start it manually in a terminal with `snapclient -s 1 --logfilter *:debug`.

**Comment by badaix** [comment]
Regarding the other software that plays just fine: other players will not try to synchronize audio by using the latency reported by alsa, which is in your BT case for example 27410204ms = 7.6 hours (exptected is rather something around 200ms): 
```
Jan 04 23:28:09 RPiZero snapclient[26127]: outputBufferDacTime > bufferMs: 27410204 > 1000
```
So please attach a log, to see if these are just outliers.

**Comment by amitkeret** [comment]
Hi @badaix , thanks for helping.
I'm sorry if it wasn't clear earlier - I've been using the `-s 1` switch every time I run snapclient.

I stopped the service. Here's a [pastebin](https://pastebin.com/zEzStWvg) of `sudo -u snapclient snapclient -s 1 --logfilter *:debug`. Looks like it is indeed indentifying the btspeaker, as you can see on line 21.
Running under root user produced similar results.

> So please attach a log, to see if these are just outliers.

Sorry I don't quite understand - are you asking for another log of something else other than the above? If so, what?
I also don't understand what you mean by "outliers".

Thanks

**Comment by badaix** [comment]
With outlier I mean if this line `Jan 04 23:28:09 RPiZero snapclient[26127]: outputBufferDacTime > bufferMs: 27410204 > 1000`just happens occasionally or regularly.
It seems to occur regularly.
I'm afraid that this bluealsa driver doesn't properly report the latency of the audio device to alsa. Snapclient relies on reliable latencies to accomplish synced playback.
So I would simply say that this device is not supported. The only bluetooth I've tested so far is a BT speaker connected to an Android phone. which is working not as good as a "real" soundcard, but OK.

**Comment by badaix** [comment]
BTW: just tested on my Linux Mint notebook to play audio to a BT speaker using PulseAudio (support added in v0.23) and this is working without a flaw. I've paired the speaker using the GUI, don't know how to do this on command line. The PulseAudio device is called `bluez_sink.<MAC>.a2dp_sink`. 
You can try this approach, maybe it's working better.
