### ISSUE TITLE
PulseAudio -> Snapserver over the network?

### ISSUE THREAD

**Issue by jessesheidlower** [badaix/snapcast#756]
I assume this is entirely possible, but the docs (e.g. [here](https://github.com/badaix/snapcast/blob/master/doc/player_setup.md#pulseaudio)) only give specific examples of connecting different players etc. to Snapcast on the same machine. Could someone share guidelines for how to connect PulseAudio running on one computer with a Snapserver running on another machine on the local network? I get confused by the many different ways of both outputting from Pulse and inputting in Snapserver.

I have a working setup with Snapserver and Mopidy running in a VM, sending audio to multiple Snapclients. But I prefer a different music player than the ones that directly interface with Mopidy, and if I can run my own music player on my desktop and direct the Pulse output into the Snapserver, that would be the best of both worlds.

**Comment by rmalchow** [comment]
hi jesse,

when you say "player" ... i am assuming you are actually talking about the control UI (the interface to chose what to play etc., such as iris in mopidy) rather than the "player" as the thing that actually renders audio to a sound device. for this, you can install (and expose) mopidy-mpd and then use any mpd player to select what's being played. there are many clients that can do this. 

.rm

**Comment by jessesheidlower** [comment]
Yes, that is what I mean. Unfortunately, the player I like is older, not able to do this, and abandoned by its developer. It's also exceptionally fast with large libraries, otherwise highly configurable, and something I'd like to keep using.

Beyond that, though—and I realize that that's a personal quirk that no one has to jump through hoops to support—I already have a familiar UI in the form of Pulse Volume Control. This lets me easily choose among different output devices (including virtual ones), and having a Snapserver as one of these would be really convenient, and, in this case, one that I expect would be of use to many people, given that Pulse is now the default on most Linux desktops.

**Comment by rmalchow** [comment]
snapcast will accept a lot of different sources. i am not that familiar with pulse audio - but this line in mopidy:

`output = audioresample ! audioconvert ! audio/x-raw,rate=48000,channels=2,format=S16LE ! wavenc ! filesink location=/tmp/snapcast/snapfifo`

is actually a gstreamer pipeline. it should be possible to grab the pulse output, pipe it through this (or a similar) pipeline, and then send the output to snapcast (either through a fifo socket or through a tcpsink -> https://gstreamer.freedesktop.org/documentation/tcp/tcpclientsink.html?gi-language=c). essentially, all the pipeline does is conform the stream to a specific format, then send it off to snapcast.

**Comment by kingosticks** [comment]
Pulseaudio already has a TCP sink doesn't it? `module-simple-protocol-tcp`. Can't you use that on your desktop (with the `source` set to your output monitor) and configure snapcast with a TCP (client?) stream?
