### ISSUE TITLE
refer a client to another server via json RPC

### ISSUE THREAD

**Issue by rmalchow** [badaix/snapcast#758]
i would like to be able to have the players act standalone, rather than with a centralized server. for this to work, i am currently trying to run mopidy, snapserver and snapclient on each node. in this scenario, each player can either play it's own stream or join the stream of another player (as opposed to one server serving all streams). 

this would be great because you could simply add another player to the network without reconfiguring everything. this would also allow for a cleaner experience during setup and configuration, because you wouldn't have to think about any grouping or number of streams - inherently, you have enough snapservers to play a custom stream to each client, and if you don't, then the unused mopidy / snapserver instances don't actually cost very much.

i have tested to see how many clients a single instance can handle - on a rockpi s, rockpi 4, and raspberries 4,3,2 and zero. they all can happily server 10 streams - thanks to your code, even the puniest CPU doesn't even break a sweat. 

i am currently implementing a workaround in python (i.e. start the snapclient process from python, deal with the zeroconf lookups, and kill & restart the client with a different host if necessary. but since you already have a control channel to each client, it would be great to be able to issue `Client.connectTo(client_id, ip,port)` and simply have the client cleanly exit and reconnect. 

here's a picture. 

![Untitled Diagram-Page-12](https://user-images.githubusercontent.com/4213287/103475600-c209c300-4dae-11eb-9410-8d4c9f52d3e9.png)
- 
1. a control client collects information about available instances, and issues a (connectTo) command
2. snapserver forwards this to one or more clients
3. client reconnects to a different snapserver

**Comment by badaix** [comment]
This is a very special use case. And what to do if the new server is unavailable? Then the client is lost, maybe it could return to the original server. What to do after client restart? Is the client supposed to connect to the least connected server?
