### ISSUE TITLE
Music is Played at Higher Pitch than Original

### ISSUE THREAD

**Issue by 19kestier** [badaix/snapcast#77]
For some reason, when playing music through snapcast, it seems quicker and more high-pitched than normal. I've tested and confirmed it does this on the Android and RPi clients and both Pulse Output and WAV output.

**Comment by HazWard** [comment]
I've been experiencing the same issue but I haven't found a fix. Using ALSA (asound.conf or .asoundrc) works perfectly for me but websites like YouTube won't output audio without PulseAudio.

**Comment by 19kestier** [comment]
So, what applications can you use with ALSA, and what would it take to make it work?

**Comment by pille** [comment]
i had a similar problem, that was solved via https://github.com/badaix/snapcast/issues/32#issuecomment-181991560

**Comment by badaix** [comment]
as pille says, the server seems to expect a higher sample rate. Either feed the server with 48kHz or try to use `--sampleformat 44100:16:2`.
