### ISSUE TITLE
Support for i386 (x86)?

### ISSUE THREAD

**Issue by kerta1n** [badaix/snapcast#770]
**Is your feature request related to a problem? Please describe.**
I have a lot of x86 Linux machines in my house, with most of them being unused and collecting dust. Is there any way that I can use these as clients for Snapcast instead of buying a fleet of RPi0's?

**Describe the solution you'd like**
Deb package for i386 (x86) as a client.

**Describe alternatives you've considered**
forked-daapd, but I'm not too sure how multi room streaming works on there

**Comment by TekniskSupport** [comment]
Hi,

You can compile both the snapclient and snapserver for i386 from source (using this guide)[https://github.com/badaix/snapcast/blob/master/doc/build.md]. I am actually currently using an old i386 as my main snapserver, and it works well.

**Comment by badaix** [comment]
Yes, please compile Snapcast on your target machine, also debian offers prebuilt packages: https://packages.debian.org/unstable/source/snapcast
Providing packages is not in the scope of this project. What you can find in releases is coming from GitHub's CI/CD pipeline (called [actions](https://github.com/badaix/snapcast/actions)).

**Comment by kerta1n** [comment]
Ah ok, just wanted to know since I didn't see i386 on the wiki. Also, is SnapOS available for i386 too?

**Comment by badaix** [comment]
Sorry, no idea about volumio
