### ISSUE TITLE
Snapserver v0.23.0 still seems to include an old Snapweb version

### ISSUE THREAD

**Issue by patagonaa** [badaix/snapcast#783]
**Describe the bug**
The release notes of v0.23.0 include "Snapweb: Update to v0.1.0", but it doesn't seem to be the case. The snapserver packages still include an older version of Snapweb.

**Steps to Reproduce**
1. Install latest snapserver (0.23.0)
2. Open the web interface
3. New Snapweb-features aren't working (auto-reconnect, running behind a reverse proxy, ability to stop stream and still control other clients in Firefox)

**Environment details**
- OS: Debian
- Snapcast version 0.23.0
- amd64 Debian package

**Comment by badaix** [comment]
Damn, you're right. I will fire this QA guy ;)

**Comment by efung1232** [comment]
I git checkout remote/origin/develop and build a couple hours ago. Now, I have snapserver v0.23.103 running. The problem I have is with the snapweb. But, I don't know how to identify the version of snapweb. I can only see blank page in my fedora linux desktop's Firefox and Chrome; it worked fine with snapserver release ver 0.23.0. The snapweb comes with "develop" build v0.23.103 works on my iPhone IOS version 14.3,  Android tablet OS version 9 and Windows 10's Edge, Firefox and Chrome.

**Comment by badaix** [comment]
Snapweb is not really versioned, as you can see in this [issue](https://github.com/badaix/snapweb/issues/15).
I've recently added a version meta tag in index.html: `<meta name="version" content="0.2.0">`, this is also logged at startup, but you cannot see it in the GUI.
You can also checkout a version from git and refer to the git revision id.
What is your problem? Everything works in every browser, but not in Fedora? Can you try to debug/fix this? On my systems this is not reproducible, or at least past logs from the debug console?
And please open Snapweb related issues in the [Snapweb project](https://github.com/badaix/snapweb).

**Comment by efung1232** [comment]
The debugger said "SyntaxError: expected expression, got '.' "
It is the period between the two words: versionElem?.content  in the follow function show()
function show() {
    // Render the page
    const versionElem = document.getElementsByTagName("meta").namedItem("version");
    console.log("Snapweb version " + versionElem?.content);

**Comment by efung1232** [comment]
Forget to mention the file. It is /usr/share/snapserver/snapweb/snapcontrol.js

**Comment by badaix** [comment]
Thanks! Seems the optional chaining (`?.`) operator needs at least Chrome 80 / Firefox 74.
Should be fixed now 2a1fde8, you can download the new version `Update snapweb ` in [Actions](https://github.com/badaix/snapcast/actions)

**Comment by efung1232** [comment]
Thanks badaix. Great jobs!
