### ISSUE TITLE
Snapserver not respecting arguments sent

### ISSUE THREAD

**Issue by HazWard** [badaix/snapcast#79]
When I run snapserver with `--samplerate 44100:16:2` as an argument, it still uses 48000Hz as the sample rate. I've tried adding this to the `/etc/default/snapserver` file but it does work.

Also, if I use CTRL+C to close snapserver and try to restart it again I get this error:
```
hazward@HP-Laptop ~ $ snapserver
Settings file: /home/hazward/.config/snapcast/server.json
sh: lsb_release: command not found
cat: /etc/openwrt_release: No such file or directory
sh: arch: command not found
2016-06-22 14-46-35 [err] Failed to create client: Daemon not running
Segmentation fault (core dumped)
hazward@HP-Laptop ~ $ 
```

**Comment by badaix** [comment]
Well, the name of the parameter is `sampleformat`:
```--sampleformat arg (=48000:16:2)    Default sample format```
This default setting can be over-riden per stream, when you add it as a stream parameter, like
```-s pipe:///tmp/snapfifo?name=Radio&sampleformat=48000:16:2```

Concerning the other messages:
These ones shouldn't hurt. The server just tries to find out where he is running:
> sh: lsb_release: command not found
cat: /etc/openwrt_release: No such file or directory
sh: arch: command not found

This one means that the avahi daemon is not running (and so the snapcast service can not be published):

> 2016-06-22 14-46-35 [err] Failed to create client: Daemon not running
Segmentation fault (core dumped)

Snapcast could live without the avahi service (clients will not auto-detect the server's IP) and shouldn't crash. I will try to reproduce this.

**Comment by HazWard** [comment]
Using ``-s pipe:///tmp/snapfifo?name=Radio&sampleformat=44100:16:2`` as an option doesn't work because of the **&** symbol. Is it supposed to be a **?**. It keeps using the default settings.

**Comment by badaix** [comment]
so we can close the issue?

**Comment by HazWard** [comment]
I recently installed Snapcast on Docker and it doesn't seem to use ``/etc/default/snapserver`` when I run ``/usr/sbin/snapserver``

This is what I have in my ``snapserver`` config:
```
SNAPSERVER_OPTS="-d -s pipe:///pipes/mopidy?name=Mopidy&mode=read"
```
But it seems like it is completely ignoring the file
