### ISSUE TITLE
snapserver reacting to 2 inputs, but not playing audio

### ISSUE THREAD

**Issue by freezir12** [badaix/snapcast#794]
Hey, thanks for that awesome piece of software!
I have setup two inputs for snapserver (bluetooth via .asoundrc file (write raw file) and airplay via stdout shairport-sync)
Both alone are working fine. But i wanna be able to use both of them:
Like this: my Snapserver.conf:

source = pipe:///tmp/shairplayfifo?name=Bluetooth
source =  airplay:///shairport-sync?name=AirPi[&dryout_ms=2000][&port=5000]

i can see the in the snapserver output that it changes between those outputs:
State changed: AirPi, state: 2 => 1
State changed: Bluetooth, state: 1 => 2

But the audio i hear is not changing, the audio output just stops.
Any help. any hints, any advice much appreciated! :)

Greetz!

**Comment by badaix** [comment]
You must switch the input to the active source or use a [meta source](https://github.com/badaix/snapcast/blob/master/doc/configuration.md#meta)

**Comment by freezir12** [comment]
> You must switch the input to the active source or use a [meta source](https://github.com/badaix/snapcast/blob/master/doc/configuration.md#meta)

Could you explain to me what you mean with "switching the input"?

using the meta source like that in the snapserver config?: 
source = meta:///pipe:///tmp/shairplayfifo?name=Bluetooth#1/airplay:///shairport-sync?name=AirPi#2
(obviously i did it wrong cause snapserver gets terminated :/

**Comment by freezir12** [comment]
I made the meta stream be recognized without errors with this config:

**Comment by freezir12** [comment]
I made the meta stream be recognized without errors with this config:

source = pipe:///tmp/shairplayfifo?name=AirPlay&sampleformat=44100:16:2
source = pipe:///tmp/Bluetoothfifo?name=BtAirPi&sampleformat=48000:16:2
source = meta:///BtAirPi/AirPlay?name=Meta&mode=recent

But still i only get audio from the first named pipe :(

**Comment by badaix** [comment]
In snapcast you have groups of clients and each group has a stream assigned. If you do nothing, the group will play the default stream. You must either manually assign the bt stream or the meta stream.
I recommend snapweb (http://<server host>:1780) or Snapdroid to do this runtime configuration.

**Comment by freezir12** [comment]
Jesus Christ! Without your direct help i would have never found this! Did not even recognize that these are buttons in SnapWeb! It is running fine now. Thanks a lot!

**Comment by badaix** [comment]
I will close this for you
