### ISSUE TITLE
Limit maximum volume for individual source

### ISSUE THREAD

**Issue by hanneshier** [badaix/snapcast#799]
**Is your feature request related to a problem? Please describe.**
When I play music from Mopidy, the sound is very very loud, so I need to regulate the volume down a lot. When I play via AirPlay its normal. So when I change between the two sources, I always have keep in mind to lower the volume first.

**Describe the solution you'd like**
Ability to limit the maximum volume for the mopidy source (for example to 30%), so that the volume slider is comparable to  the AirPlay source.

**Describe alternatives you've considered**
I could limit the output source in Mopidy, but I haven't really found an option that is working for me yet.

**Additional context**
I'm using a raspberry pi 3 with the hifiberry amp2 as my main audio setup.

**Comment by badaix** [comment]
Mopidy uses gstreamer, so it should be possible to add the [volume element](https://gstreamer.freedesktop.org/documentation/volume/index.html?gi-language=c) to the audio output queue

**Comment by kingosticks** [comment]
Mopidy already has a software volume element in the pipeline. It is the default. Feel free to create a post at https://discourse.mopidy.com/c/qna/8 if you are having problems using it.
