### ISSUE TITLE
Garbled sound on Banana Pi connected to receiver via HDMI out

### ISSUE THREAD

**Issue by htpc-helper** [badaix/snapcast#80]
I am really liking Snapcast with Mopidy however I am having some issues and I am not sure whether it is my configuration or a bug in Snapcast. I have Mopidy, Snapserver and Snapclient running on a Banana Pi running Bananian 16.04 (Debian 8). If I pause the music and try to resume an hour later, the music is garbled as if it is a codec that the receiver cannot understand (possibly FLAC). The issue is resolved with the command `sudo service snapclient restart`

I also have Snapclient running on a Raspberry Pi with audio output over 3.5mm jack and I am not experiencing any issues.

Relevant config sections on the Banana Pi are shown below:

/etc/default/snapclient
`SNAPCLIENT_OPTS="-d -s 7"`

/etc/default/snapserver
`SNAPSERVER_OPTS="-d -c pcm"`

/etc/mopidy/mopidy.conf
`output = audioresample ! audioconvert ! audio/x-raw,rate=48000,channels=2,format=S16LE ! wavenc ! filesink location=/tmp/snapfifo`

Running the command `sudo snapclient -l` gives the following output:
0: null
Discard all samples (playback) or generate zero samples (capture)

1: pulse
PulseAudio Sound Server

2: sysdefault:CARD=sunxicodec
sunxi-CODEC, sunxi PCM
Default Audio Device

3: dmix:CARD=sunxicodec,DEV=0
sunxi-CODEC, sunxi PCM
Direct sample mixing device

4: dsnoop:CARD=sunxicodec,DEV=0
sunxi-CODEC, sunxi PCM
Direct sample snooping device

5: hw:CARD=sunxicodec,DEV=0
sunxi-CODEC, sunxi PCM
Direct hardware device without any conversions

6: plughw:CARD=sunxicodec,DEV=0
sunxi-CODEC, sunxi PCM
Hardware device with all software conversions

7: sysdefault:CARD=sunxisndhdmi
sunxi-sndhdmi, sunxi HDMI PCM
Default Audio Device

8: dmix:CARD=sunxisndhdmi,DEV=0
sunxi-sndhdmi, sunxi HDMI PCM
Direct sample mixing device

9: dsnoop:CARD=sunxisndhdmi,DEV=0
sunxi-sndhdmi, sunxi HDMI PCM
Direct sample snooping device

10: hw:CARD=sunxisndhdmi,DEV=0
sunxi-sndhdmi, sunxi HDMI PCM
Direct hardware device without any conversions

11: plughw:CARD=sunxisndhdmi,DEV=0
sunxi-sndhdmi, sunxi HDMI PCM
Hardware device with all software conversions

When music is playing, running the command `sudo snapclient` gives the following output:
2016-06-23 11-26-04 [out](Browser) NEW: service 'Snapcast' of type '_snapcast._tcp' in domain 'local'
2016-06-23 11-26-04 [out](Browser) CACHE_EXHAUSTED
2016-06-23 11-26-04 [out] Service 'Snapcast' of type '_snapcast._tcp' in domain 'local':
2016-06-23 11-26-04 [out]   snapcast.local:1704 (10.0.1.139)
2016-06-23 11-26-04 [out] Found server 10.0.1.139:1704
2016-06-23 11-26-04 [out] Latency: 0
2016-06-23 11-26-04 [out] Connecting
2016-06-23 11-26-04 [Notice] Connected to 10.0.1.139
2016-06-23 11-26-04 [out] My MAC: "xx:xx:xx:xx:xx:", socket: 6
sh: 1: lsb_release: not found
cat: /etc/openwrt_release: No such file or directory
2016-06-23 11-26-04 [out] ServerSettings - buffer: 1000, latency: 0, volume: 100, muted: 0
2016-06-23 11-26-04 [out] Codec: flac
2016-06-23 11-26-04 [state] sampleformat: 48000:16:2
2016-06-23 11-26-04 [out] frames: 1440
2016-06-23 11-26-04 [out] no chunks available
2016-06-23 11-26-04 [out] Failed to get chunk

I am thinking that the statement above `Codec: flac` may be the issue but I am not sure why this is the case given that /etc/default/snapserver is set `-c pcm` and /etc/mopidy/mopidy.conf is set `wavenc`.

I appreciate any light that anyone is able to shed on this issue.

**Comment by badaix** [comment]
regarding codec settings: seems that the global `-c` option is not working.
You can still configure the codec per stream. Please use this in your `/etc/default/snapserver`:
````
SNAPSERVER_OPTS="-d -s pipe:///tmp/snapfifo?name=default&codec=pcm"
````
Also you can try to use sound card nr 9: `9: dsnoop:CARD=sunxisndhdmi,DEV=0`

**Comment by badaix** [comment]
Just found out that there is no option `-c` in the server, but there is `--codec` ;)

**Comment by htpc-helper** [comment]
Thanks for the update. Due to numerous problems with the Banana Pi I ended up migrating my Mopidy server to a Raspberry Pi 2 instead. Snapserver was experiencing 100% CPU load on the BPi compared to <10% on the RPi2. I wonder if others experienced similar problems?

**Comment by badaix** [comment]
You can send/spend me your Banana. I will make it compatible. :wink:

**Comment by htpc-helper** [comment]
Sure, send me your address details and I'll mail the BPi to you.

**Comment by badaix** [comment]
with "spend" I actually meant "donate" (the german word is "spenden" :wink:).
If you still want to donate it (I would use it to fix the issue and for regression and compatibility tests in upcoming releases), please send me your email address to snapcast@badaix.de. I will send you my address details via mail.

Thanks :+1:

**Comment by htpc-helper** [comment]
This is excellent software and I'm happy to make a donation. How do I do that?
