### ISSUE TITLE
Do something when there is sound and is not?

### ISSUE THREAD

**Issue by whc2001** [badaix/snapcast#800]
**Is your feature request related to a problem? Please describe.**
So this one is kinda a low priority feature request but still nice to have. I am making an outdoor speaker which will be powered on all the time. I am running SnapOS on OpenWrt, and the board has some LEDs. I wanted to power off the amplifier board with one of the LED pins when there is no sound to decrease standby power and static noise.

**Describe the solution you'd like**
To have some "hook" on the client that when there is sound received from the stream then execute a script, and when there is not (sound data below a certain threshold) execute another. This way I can simply make scripts to toggle the GPIO pin to control the amplifier.

**Describe alternatives you've considered**
Actually I think there is another route which is to tap into the ALSA to get the current sound intensity. However I looked at many examples and almost all of them are about getting the sound intensity of input device (e.g. microphone) rather than output. 

**Additional context**
If REALLY non of these would work out, I can still do some other hacks like creating a hardware circuit to detect the voltage on the audio cable.

**Comment by badaix** [comment]
Snapcast will connect/release the audio device when playing/idle.
In #741 the approach was to watch the status of the device:

> On the client side I have orangepilite (armbian) driving a pcm5142 DAC and a small python daemon watching the /proc/asound/card*/*p/sub*/status to turn the power amp on or off (via a relay driven by a GPIO pin).

I will think about a configurable script or something.

**Comment by Torgee** [comment]
I'm using https://github.com/happyleavesaoc/python-snapcast to actively query the idle/active state of the client for a similar use-case (power-on/-off if external power-amp). Running smoothly and robust for a few weeks now with snapserver v0.22

**Comment by whc2001** [comment]
> Snapcast will connect/release the audio device when playing/idle.
> In #741 the approach was to watch the status of the device:
> 
> > On the client side I have orangepilite (armbian) driving a pcm5142 DAC and a small python daemon watching the /proc/asound/card*/_p/sub_/status to turn the power amp on or off (via a relay driven by a GPIO pin).
> 
> I will think about a configurable script or something.

Interesting, I'll try that later.

**Comment by whc2001** [comment]
> I'm using https://github.com/happyleavesaoc/python-snapcast to actively query the idle/active state of the client for a similar use-case (power-on/-off external power-amp). Running smoothly and robust for a few weeks now with snapserver v0.22

I'll look into it. I wonder when the client is not muted but there is no audio stream it will report idle or active? As I also want the amplifier to be shutdown if there isn't any sound.

**Comment by Torgee** [comment]
From my experience, a stream with no sound should be reported 'idle', e.g. pausing a librespot stream makes it 'idle'. I don't use it for anything else at the moment, tho, unfortunately. I'm combining 'idle'-stream with client-muted, and switch off the amp when either is the case. See script here: https://github.com/Torgee/home_automation/blob/main/avrsync.py

**Comment by badaix** [comment]
It's actually the state of the stream, not of the client. So a paused/inactive stream is reported as idle.

**Comment by Torgee** [comment]
Yeah, should have made this clear, too. The script basically does this:
(Client -> Group -> Stream -> idle state) || (Client -> mute state)

**Comment by whc2001** [comment]
Quickly spun up a test shell script using soundcard status method and it does work, but seems like when I start this script the output begin to emit random pop, crackling and static noise.

```
SOUNDCARD_STATUS_NODE="/proc/asound/card0/pcm0p/sub0/status"
SHUTDOWN_TIMEOUT=3
POWER_ON() { echo "Turn ON Amplifier"; echo "1" >> /sys/class/leds/yk1:blue:usb/brightness; }
POWER_OFF() { echo "Turn OFF Amplifier"; echo "0" >> /sys/class/leds/yk1:blue:usb/brightness; }

lastStatus=0
nowStatus=0
lastIdle=-1

CheckStatus()
{
    status=$(head -n 1 $SOUNDCARD_STATUS_NODE)
    if echo $status | grep -q "closed"; then
        return 0
    elif echo $status | grep -q "RUNNING"; then
        return 1
    else
       return 2
    fi
}

while true; do
    CheckStatus
    nowStatus=$?
    if [[ $nowStatus == 1 ]]; then
        if [[ $lastStatus == 0 ]]; then
            echo "Soundcard Working"
            POWER_ON
            lastStatus=1
        fi
    elif [[ $nowStatus == 0 ]]; then
        if [[ $lastStatus == 1 ]]; then
            echo "Soundcard Released"
            lastStatus=0
            lastIdle=$(date +%s%N | cut -b1-13)
        elif [[ $lastStatus == 0 ]] && [[ $lastIdle != -1 ]]; then
            if [ $(( $(date +%s%N | cut -b1-13) - $lastIdle )) -gt $SHUTDOWN_TIMEOUT ]; then
                echo "Timeout reached"
                POWER_OFF
                lastIdle=-1
            fi
        fi
    fi
    sleep 0.01
done
```

Gonna try python or use the stream&mute status method instead.

**Comment by whc2001** [comment]
Seems like the noise is because the bash script using too much CPU. After switching to Python the peak CPU utilization of the script is about 5% and worked flawlessly. Good enough for me, thanks everyone!

```
#!/usr/bin/python3

SOUNDCARD_DEVICE_FILE = "/proc/asound/card0/pcm0p/sub0/status"
GPIO_DEVICE_FILE = "/sys/class/leds/yk1:blue:usb/brightness"
SHUTDOWN_TIMEOUT = 3

def POWER_ON_DELEGATE():
    print("Power ON Amplifier")
    with open(GPIO_DEVICE_FILE, "w") as fs:
        fs.write("1")

def POWER_OFF_DELEGATE():
    print("Power OFF Amplifier")
    with open(GPIO_DEVICE_FILE, "w") as fs:
        fs.write("0")

#-----------------------------------
import os
import time

def Now():
    return int(time.time())

def CheckSoundcardStatus():
    global deviceFile
    buf = ""
    lastException = None
    for i in range(3):
        try:
            os.lseek(deviceFile, 0, os.SEEK_SET)
            buf = os.read(deviceFile, 14)
            return (len(buf) == 14 and buf[7] == 82 and buf[8] == 85 and \
                buf[9] == 78 and buf[10] == 78 and buf[11] == 73 and \
                buf[12] == 78 and buf[13] == 71)
        except Exception as ex: # Attempt to open device file again
            try:
                os.close(deviceFile)
            except:
                pass
            try:
                deviceFile = os.open(SOUNDCARD_DEVICE_FILE, os.O_RDONLY)
            except Exception as ex:
                lastException = ex
    raise lastException # All attempt failed

def CheckGpioStatus():
    try:
        with open(GPIO_DEVICE_FILE, "r") as fs:
            buf = fs.read()
            return int(buf) == 1
    except:
        return False

deviceFile = None
lastStatus = CheckGpioStatus()
nowStatus = lastStatus
lastIdle = -1

while True:
    try:
        nowStatus = CheckSoundcardStatus()
    except Exception as ex:
        print(ex)
        time.sleep(1)
        continue

    if nowStatus:
        if not lastStatus:
            print("Soundcard Working")
            POWER_ON_DELEGATE()
            lastStatus = True
    else:
        if lastStatus:
            print("Soundcard Released")
            lastStatus = False
            lastIdle = Now()
        elif (not lastStatus) and (lastIdle != -1):
            if Now() - lastIdle >= SHUTDOWN_TIMEOUT:
                print("Timeout Reached")
                POWER_OFF_DELEGATE()
                lastIdle = -1
    time.sleep(0.01)

```

**Comment by whc2001** [comment]
> Snapcast will connect/release the audio device when playing/idle.
> In #741 the approach was to watch the status of the device:
> 
> > On the client side I have orangepilite (armbian) driving a pcm5142 DAC and a small python daemon watching the /proc/asound/card*/_p/sub_/status to turn the power amp on or off (via a relay driven by a GPIO pin).
> 
> I will think about a configurable script or something.

I think maybe add something like JSON-RPC to snapclient? Like having unsolicited message when audio packet is received and not, which can do better than the polling method I am using (it's totally acceptable for my use case for now, just nice to have). Also the server can also have this if possible, as I am considering to do a whole house audio system with a centralized audio server (running snapserver + multiple snapclient on a single multi soundcard machine) and multiple amplifiers. This way I can has one daemon monitoring the messages from snapserver and toggle the power of corresponding amplifier. Nevertheless it's pretty awesome for me now, thanks again for bringing such a great piece of software!
