### ISSUE TITLE
Sending audio to snapcast from Linux pc

### ISSUE THREAD

**Issue by 6i6i** [badaix/snapcast#802]
Hello,

I am currentl figuring out how to send any audio from a pc with linux os to snapcast as input source.
Currently I have following working:

Linux PC _->_ Pulsaudio (module-tunnel-sink) _-Ethernet with cable>_ Server (module-native-protocol-tcp) -> Server module-pipe-sink file=/tmp/pulse sink_name=Snapcast -> Snapcast stream = pipe:///tmp/pulse?name=pulseaudio _-Ethernet with cable>_ Snapcast Client (Raspberry)

This works very well, except of the latency. I have approximately 500ms latency when playing something on the Linux PC until I hear the sound from Snapcast Client.

I think there is some buffer value probably to large. 

Does someone has the same setup or an different one with the same outcome?

I saw there is a configuration option:
```
# Buffer [ms]
buffer =
```
for the snapcast server. I didn't find a documentation what buffer this value represents?

I found also following in the documentation:
_"It might be neccessary to set the PulseAudio latency environment variable to 60 msec: PULSE_LATENCY_MSEC=601"_

Where should this variable be set? On the Linux PC that plays the audio? Or on the server that receives the pulseaudio stream?

Thank you
BR
Martin

**Comment by badaix** [comment]
Snapcast will add a latency of `buffer = 1000` ms. Pulse will probably add something on top.

**Comment by 6i6i** [comment]
OK. Thank you,
Is this value of 1000ms configureable?

**Comment by badaix** [comment]
As you've quoted this setting from the configuration file: yes, of course

**Comment by 6i6i** [comment]
OK great. I set this to 10msec and it works for all streams. 
So I think pulseaudio will add the 500ms. 
Can you explain the suggested variable in the documentation:
**"It might be neccessary to set the PulseAudio latency environment variable to 60 msec: PULSE_LATENCY_MSEC=60"**

Thank you
Martin

**Comment by badaix** [comment]
Snapcast will set a minimum buffer of 400ms. No chance to achieve 10ms. Even your soundcard will need 100ms and the network, the stream capture, the codec, ...
No idea about PulseAudio latency. It's not my comment.

**Comment by 6i6i** [comment]
Ok. I see. Than the latency will come from the 400ms snapcast buffer + some latency regarding pulse audio.

The 10ms were just a test value. 
Did you ever check to use a lower value than 400ms?

**Comment by badaix** [comment]
Not really, you can remove it somewhere in `snapserver.cpp`, should be easy to find. You can also start a client wirh `--latency <some negative value in ms>`, e.g. `--latency -300`, to get an overall latency of 100ms. But this is of course a per client setting. 
I also recommend using `pcm` as codec.

**Comment by 6i6i** [comment]
OK. I tried it setting the latency to -300 in the client options via snapdroid. This added even more latency to the whole chain. Then I tried to put +150ms and now I got more or less a accepatable latency.
That means watching videos is now possible and they are lip-sync. 

I didn't change the codec or anything in snapserver.cpp
Thank you very much for your help.

**Comment by badaix** [comment]
Oh, yes, of course it must be a positive latency

**Comment by badaix** [comment]
Let me close this for you
