### ISSUE TITLE
Suggestions for flooded 2.4 GHz WiFi

### ISSUE THREAD

**Issue by daniele-athome** [badaix/snapcast#804]
I'm running snapclient on Raspberry Pi Zero W and having buffering issues on my 2.4 GHz WiFi home network. I live in an apartment so it's probably a flooding issue (ping latency suddendly increase up to 800 ms - per packet! - every 30 seconds or so). I've been able to reproduce the latency issue with other WiFi clients (even a laptop), so the problem is indeed the 2.4 GHz band. This means that every 30 seconds I get holes in the sound because packets are not coming in.

Since I can't use the 5 GHz band (unless I plug a USB WiFi adapter, but that's another story) and my ISP modem (which I'm forced to use at the moment) doesn't allow me to change WiFi channel, do you have any suggestion for configuring snapcast (server or client) for having a clean sound? I tried to increase snapserver `buffer` parameter: I had to increase it to 3000 ms to produce a smooth and continuous sound.
Also, it's not clear how `chunk_ms` can impact on performance. It would be great to have a documentation article to read about tuning `buffer` and `chunk_ms`.
Thanks!

**Comment by daniele-athome** [comment]
For anyone reading this: I was able to drop my router and buy a new one. I configured it to use a 20MHz WiFi channel (1, 6 or 11, analyze your area with a WiFi analyzer to choose the best one for you). The situation has improved dramatically: I'm now able to use a 500 ms buffer and I had like one brief skip in maybe 10-12 days.

Anyway, documentation about the relation between `buffer` and `chunk_ms` would still be great :-)

**Comment by duhow** [comment]
@daniele-athome can you share the settings you're using on snapserver?
Sounds like you're using default codec FLAC, you may try by using Opus, which uses way less data, and should not cause this network issues.

**Comment by daniele-athome** [comment]
I tried Opus too, but without getting any improvement. Generally speaking my WiFi settings suggestions above will definitely help in any application (you can find them anywhere on the Internet).

Also I did a more thorough analysis of my old (carrier-provided) router and I found out it was using a 20/40 MHz channel width and it was constantly changing channel, using also the overlapping ones which is clearly a problem in 2.4 GHz networks. Sometimes hardware is the problem :-)
