### ISSUE TITLE
Sync problem when multiple clients are run on same device.

### ISSUE THREAD

**Issue by gribouk** [badaix/snapcast#805]
**Describe the bug**

I ran snapserver on comp. A, two instances of snapclient on comp B, which is RPi4 with wired speakers and BT speker - one instance per each device to be able to stream sound to both, and one instance of snapclient on comp. C, which is my phone (Android). The problem is as follows: comp. C is perfectly synchronized with comp.B-wired speakers - instance id=1, but instance id =2 is behind in time compared to both, comp.C and comp.B.1 - no metter what I tried there is nothing I coud do with it?

**Steps to Reproduce**
1. Have snapcliend run with id=1 on comp.A
2. Have two instances run on comp. B with id = 1, 2
3. A.1 and B.1 - synchronized, A/B.1 and B.2 not

**Environment details**
- OS: comp.A - Debian 20.04, comp.B - Rassbein, Comp.C - Android 
- Snapcast version 23.0-1
- Installed from a package

**Comment by badaix** [comment]
You can adjust the latency of a single instance with the `--latency <latency in ms>` or with Snapdroid parameter. But don't expect a bluetooth device to play 100% in sync.

**Comment by gribouk** [comment]
Ohh.. that simple. 
Thanks alot!
