### ISSUE TITLE
Duplicate hostID for two Mac clients with touch bar

### ISSUE THREAD

**Issue by sfiera** [badaix/snapcast#807]
I have a home MacBook and a work MacBook. I run snapclient on both, and have an external dock that I use at home with both. For some reason, both default to the same hostID. I believe it’s because they are both picking up a network interface from the dock, and using the dock’s MAC address as their UUID. Built-in WiFi is en0, but snapclient is using a different enX (X > 0 but ordered earlier in `ifconfig`).

Workaround is to check `ifconfig en0` and pass `--hostID $(EN0_MAC_ADDRESS?)`, since en0 should be unique for each machine.

I see that this code is Mac-specific and you probably won’t be able to do much investigation on your end:
https://github.com/badaix/snapcast/blob/9fd61eeda3eea731cc0f48ca9365dfc1846ea89c/common/utils.hpp#L430-L438

**Steps to Reproduce**
1. Connect two Mac computers to the same dock
2. Run snapclient on both
3. Look for `My MAC: "…"` in logs

**Environment details**
- OS: MacOS
- Snapcast version: v0.23.0 (self-compiled at tag)

**Comment by sfiera** [comment]
Oh, this is worse. I didn’t mention the specific MAC address as a privacy matter, but it’s `ac:de:48:00:11:22`, which appears to be [present on any MacBook with a touch bar](https://discussions.apple.com/thread/7763102).

**Comment by badaix** [comment]
`snapclient --help`

```
Allowed options:
  --help                          produce help message
  -v, --version                   show version number
  -h, --host arg                  server hostname or ip address
  -p, --port arg (=1704)          server port
  -i, --instance arg (=1)         instance id when running multiple instances on the same host
  --hostID arg                    unique host id, default is MAC address
  -l, --list                      list PCM devices
  -s, --soundcard arg (=default)  index or name of the pcm device
  --latency arg (=0)              latency of the PCM device
  --sampleformat arg              resample audio stream to <rate>:<bits>:<channels>
  --player arg (=alsa)            alsa|pulse|file[:<options>|?]
  --mixer arg (=software)         software|hardware|script|none|?[:<options>]
  -e, --mstderr                   send metadata to stderr
  -d, --daemon [=arg(=-3)]        daemonize, optional process priority [-20..19]
  --user arg                      the user[:group] to run snapclient as when daemonized
  --logsink arg                   log sink [null,system,stdout,stderr,file:<filename>]
  --logfilter arg (=*:info)       log filter <tag>:<level>[,<tag>:<level>]* with tag = * or <log tag> and level = [trace,debug,info,notice,warning,error,fatal]
```

=> try `--hostID <my unique id>`

**Comment by badaix** [comment]
I've added an exception for this Mac address, as already done for Android:

```c++
static std::string getHostId(const std::string defaultId = "")
{
    std::string result = strutils::trim_copy(defaultId);

    if (!result.empty()                    // default provided
        && (result != "00:00:00:00:00:00") // default mac returned by getMaxAddress if it fails
        && (result != "02:00:00:00:00:00") // the Android API will return "02:00:00:00:00:00" for WifiInfo.getMacAddress()
        && (result != "ac:de:48:00:11:22") // iBridge interface on new MacBook Pro (later 2016)
    )
        return result;
```
Can you please try the head of the develop branch? It should use the Mac specific fall back code

**Comment by sfiera** [comment]
Yes, that causes fallback correctly. I get a Hello from a UUID.

I’m investigating a way to get a “primary” interface’ ̑ MAC addresses on macOS, but the fallback resolves this issue.

**Comment by badaix** [comment]
It must not be a MAC address, the requirement is to have a unique ID for a certain machine, that will not change over time.
The MAC supposed to be a good first choice, but it turned out to be not always unique, so the hostId was introduced, defaulting to the MAC address.
