### ISSUE TITLE
multiple snapclient.service instances for different devices

### ISSUE THREAD

**Issue by gribouk** [badaix/snapcast#809]
**Describe the bug**

I am running several snapclients on a RPi , each corresponding to it's own speaker since I am streaming individual output to every of these clients.

When I start those from the command line, all clients connect to the server no problem.
When I try to create a service for them to start on boot, I run into problem that only the first client starts and the rest fall into ERROR.
Below are my service.service files. Firs, the one that starts:

```

[Unit]
Description=Snapcast client wire speakers
Documentation=man:snapclient(1)
Wants=avahi-daemon.service
After=network-online.target time-sync.target sound.target avahi-daemon.service

[Service]
EnvironmentFile=-/etc/default/snapclient
ExecStart=/usr/bin/snapclient --logsink=system --soundcard=11 $SNAPCLIENT_OPTS
User=snapclient
Group=snapclient
Restart=on-failure

[Install]
WantedBy=multi-user.target

```

Then, I've created the exact copy of previous one with a different params and file name. And no metter how I edit that one, it never starts. Below is my last version:

```

[Unit]
Description=Snapcast client for BT speakers 1
Documentation=man:snapclient(2)
Wants=avahi-daemon.service
After=network-online.target time-sync.target sound.target avahi-daemon.service

[Service]
EnvironmentFile=-/etc/default/snapclient
ExecStart=/usr/bin/snapclient --instance=2 --logsink=system --soundcard=4
User=snapclient
Group=snapclient
Restart=on-failure

[Install]
WantedBy=multi-user.target

```

 Would someone hint me what is wrong with that? Below is the status message for the unsuccessfull script.

```

● snapclient_speker_bt_1.service - Snapcast client for BT speakers 1
   Loaded: loaded (/lib/systemd/system/snapclient_speker_bt_1.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2021-02-19 21:46:43 EET; 26min ago
     Docs: man:snapclient(2)
  Process: 1700 ExecStart=/usr/bin/snapclient --instance=2 --logsink=system --soundcard=4 (code=exited, status=1/FAILURE)
 Main PID: 1700 (code=exited, status=1/FAILURE)

Feb 19 21:46:43 raspberrypi systemd[1]: snapclient_speker_bt_1.service: Service RestartSec=100ms expired, scheduling restart.
Feb 19 21:46:43 raspberrypi systemd[1]: snapclient_speker_bt_1.service: Scheduled restart job, restart counter is at 6.
Feb 19 21:46:43 raspberrypi systemd[1]: Stopped Snapcast client for BT speakers 1.
Feb 19 21:46:43 raspberrypi systemd[1]: snapclient_speker_bt_1.service: Start request repeated too quickly.
Feb 19 21:46:43 raspberrypi systemd[1]: snapclient_speker_bt_1.service: Failed with result 'exit-code'.
Feb 19 21:46:43 raspberrypi systemd[1]: Failed to start Snapcast client for BT speakers 1.


```

**Comment by gribouk** [comment]
The least I can mention that I am absolutely confused. Just few days ago I did same thing on another RPi in another room. But this time I was exploring the PulseAudio rather than ALSA, and for that reason opted to use PiOS Full instead of light - the only difference. Apart from that, service.service files look identical. Couple of days ago this thing worked as second service:

```
[Unit]
Description=Snapcast client for BT speakers 1
Documentation=man:snapclient(1)
Wants=avahi-daemon.service
After=network-online.target time-sync.target sound.target avahi-daemon.service

[Service]
EnvironmentFile=-/etc/default/snapclient
ExecStart=/usr/bin/snapclient --instance=2 --soundcard=4 --logsink=system $SNAPCLIENT_OPTS
User=snapclient
Group=snapclient
Restart=on-failure

[Install]
WantedBy=multi-user.target

```

And for some reason, same thing refuses to start as service today. Is there something I am missing? Maybe I need to run some command bere to enable multi-client mode?

**Comment by badaix** [comment]
I think you should use two environment files, but I'm not an expert in systemd. But this is not a snapcast issue
