### ISSUE TITLE
[Feature Request] present the android app as a media route provider using the media router on android

### ISSUE THREAD

**Issue by ioangogo** [badaix/snapcast#81]
This will allow android apps to play through snapcast.

Documentation: https://developer.android.com/guide/topics/media/mediarouteprovider.html

**Comment by badaix** [comment]
actually the snapserver (not the Android App) must be a MediaRouteProvider, or not?
Seems that the API is only available as part of the Android SDK for Android and not for Linux.

**Comment by renne** [comment]
@badaix 
I assume @ioangogo wants a Snapcast server integrated into the Android app to stream multiroom-audio by any Android app.
