### ISSUE TITLE
cmake doesn't install rc script on FreeBSD

### ISSUE THREAD

**Issue by yurivict** [badaix/snapcast#814]
**Describe the bug**

Here https://github.com/badaix/snapcast/blob/master/doc/build.md#freebsd-native docs say that rc script is installed, but it actually isn't.

**Environment details**
- OS: FreeBSD 12.2
- Snapcast version 0.23.0
- Installed from the port

**Comment by badaix** [comment]
it says `gmake`, not `cmake`. PRs are welcome.
