### ISSUE TITLE
Automate Windows client build process to nightly

### ISSUE THREAD

**Issue by chiefy** [badaix/snapcast#818]
**Is your feature request related to a problem? Please describe.**
I hate Windows, but I have a gaming machine on my main stereo. I spent almost 2 hours compiling snapcast client for Windows. It worked, but it was quite painful.  Is it possible to somehow automate this, hopefully for as little $ as possible?

**Describe the solution you'd like**
This project artifacts Windows x86_64 binaries/installer etc. on push to master or otherwise prescribed. 

**Describe alternatives you've considered**
Snapcast is best.

**Comment by badaix** [comment]
There is a nightly build for Windows: https://github.com/badaix/snapcast/actions/workflows/windows.yml

**Comment by chiefy** [comment]
@badaix sorry - I didn't see it. Derp.
