### ISSUE TITLE
[Feature Request] snapclient - control block/unblock audio device

### ISSUE THREAD

**Issue by mrdago** [badaix/snapcast#82]
I've build a network consisting of several Raspberry PI running Volumio1.55. With snapcast every player can now run in 'standalone' or 'multiroom' mode. In Multiroom Mode one of the player is acting as server (snapserver) and the others are synchronized by snapclient. Toggling between the two modes is done by starting/stoping other player (spotify connect, mpd) and to stop/start the snapclient from a event handler script. --> (switch multiroom mode on --> start snapclient, switch multiroom mode off -- stop snapclient) 

For better stability and performance it would be an improvement if the blocking/unblocking of the audio device by snapclient could be controlled by a network command instead of starting/stoping the daemon, similar as other players behave with a remote 'play' or 'pause' command. 

Any chance to implement such an feature in future?

**Comment by badaix** [comment]
I will think about it. Basically the state of the stream is known to the client (Idle, Playing, Unknown. Although it is quite implicit. The server assumes the stream to be Idle if there is no data to be read from the pipe).
This could also lower energy consumption and allow higher c-states.

**Comment by badaix** [comment]
Will be freed now (cbdc850be1f8092d03cc0237067dbce22f545dac) after 5s idle time
