### ISSUE TITLE
Sharp popcorn noise (ticks and tags) in background when sample rate is set to 24-bit/192kHz

### ISSUE THREAD

**Issue by efung1232** [badaix/snapcast#820]
**Describe the bug**
popcorn noise in the background when 16-bit/44.1kHz FLAC or ALAC music stream is upsampled to 24-bit/192kHz; no such problem when upsampled to 24-bit/176.4kHz or 16-bit/192kHz. Also there is no such problem if upsample from 24-bit/96kHz to 24-bit/192kHz. Down sample from 24-bit/192kHz to 24-bit/176.kHz is fine.

**Steps to Reproduce**
1. Streaming music with difference tracks that have difference sample rates to Raspberry Pi with upmpdcli-Qobuz and I2S sound card. Running server and client in the same RPi 4B (also happened in RPi-3B+) board with Raspbian OS.
2. Streaming ALAC CD music from local network shared drive to the RPi-4B board with Raspbian OS. The problem will be promptly reproduced when Snapserver's sample rate is set to 24-bit/192kHz; no such problem if sample rate is set to 24-bit/176.4kHz.
3.

**Environment details**
- Raspbian OS
- Snapcast version 0.24.0
- Self compiled.

**Attach logfile if applicable**
Generate logs with `snapclient --logfilter debug` or `snapserver --logging.filter debug` if possible and paste them in the following codeblock

```log
# Replace this with your logs
```

**Comment by badaix** [comment]
I don't understand your setup. What is Snapserver's samplerate? How does your configuration look like? What is the audio source?
How do you downsample/upsample?

**Comment by efung1232** [comment]
@badaix , I am sorry to confuse you. I set the audio format in Snapserver streaming to 24-bit/192k in snapserver.conf and by setting the pipe file's audio format in mpd.conf. As a result, MPD will do the upsampling automatically if necessary. The buffer size is 4M bytes. The problem was not eliminated in a larger buffer situation. I have the snapserver and snapclient running in the same Raspbery Pi 4B board. I play music from the my CD's ALAC music files stored in a USB SSD drive attached in my router as "windows share" as well as online streaming from Qobuz which has various music formats from 16-bit/44.1k to 24-bit/192k.

message from executing "systemctl status snapclient": snapclient[3150]: PCM name: Sampleformat: 192000:24:2, stream: 192000:24:2    default:CARD=sndrpihifiberry, sample rate: 192000 Hz, channels: 2, buffer time: 80000 us, periods: 4, period time: 20000 us, period frames: 3840

Note: 1) sample rates in both /etc/mpd.conf and /etc/snapserver.conf must be the same. Otherwise, there will be no audio output. 2) I could not find 48k tracks from Qobuz.

case 1) If I disable both snapserver and snapclient in the same RPi and run MPD only with upsampling from CD's 16-bit/44.1kHz to 24-bit/192kHz, and no EQ by running software in RPi, the music playback is excellent with inaudible electronic background noise. So, the problem is not in the MPD's upsampling.

case 2) if I enable both snapserver and snapclient in the same RPi, the upampling from 16-bit/44.1k is only good to 24-bit/176.4k. This is true on both 16-bit/44.1k ALAC files from the LAN shared folder as well as music from online streaming.

case 3) setting same as #2 with various formats of source music except 16-bit/44.1kHz selected from Qobuz; yes, 24-bit/44.1k works fine. When the sample rate of snapserver set to 24-bit/192k, the playback music is excellent with inaudible electronic background noise.

case 4) setting the sample rate in snapserver to 16-bit/192k works perfectly fine for all cases.

**Comment by chrusty0** [comment]
I have same "popcorn" noise when using native 16-bits/192kHz stream (1 or 2 channels)

I think it has to do with adjusting the sampling frequency. Hope that following debug log may help @badaix  to understand.

"popcorn" noise varies between ±50 and ±100ms according to values in the 2, 3 and 4th column.

```
Mar  8 12:45:47 db0-test user.debug snapclient[8205]: Chunk: 0     -1      -1      -1      500     6       9
Mar  8 12:45:48 db0-test user.debug snapclient[8205]: Chunk: -2    -1      -1      -1      500     6       8
Mar  8 12:45:49 db0-test user.debug snapclient[8205]: Chunk: -1    -1      -1      -1      500     7       9
Mar  8 12:45:50 db0-test user.debug snapclient[8205]: Chunk: 0     -1      -1      -1      500     7       9
Mar  8 12:45:51 db0-test user.debug snapclient[8205]: Chunk: 0     -1      -1      -1      500     6       8
Mar  8 12:45:52 db0-test user.debug snapclient[8205]: Chunk: -1    -1      -1      -1      500     6       9
Mar  8 12:45:53 db0-test user.debug snapclient[8205]: Chunk: -1    -1      -1      -1      500     6       9
Mar  8 12:45:54 db0-test user.debug snapclient[8205]: Chunk: -2    -1      -1      -1      500     6       8
Mar  8 12:45:55 db0-test user.debug snapclient[8205]: Chunk: -2    -1      -1      -1      500     7       8
Mar  8 12:45:56 db0-test user.debug snapclient[8205]: Chunk: -1    -1      -1      -1      500     7       8
Mar  8 12:45:57 db0-test user.debug snapclient[8205]: Chunk: -2    -1      -1      -1      500     7       8
Mar  8 12:45:58 db0-test user.debug snapclient[8205]: Chunk: -1    -1      -1      -1      500     7       9
Mar  8 12:45:59 db0-test user.debug snapclient[8205]: Chunk: -2    -1      -1      -1      500     7       8
Mar  8 12:46:00 db0-test user.debug snapclient[8205]: Chunk: -1    -1      -1      -1      500     6       8
Mar  8 12:46:01 db0-test user.debug snapclient[8205]: Chunk: -2    -1      -1      -1      500     6       7
Mar  8 12:46:02 db0-test user.debug snapclient[8205]: Chunk: 0     -1      -1      -1      500     6       8
Mar  8 12:46:03 db0-test user.debug snapclient[8205]: Chunk: -1    -1      -1      -1      500     6       9
Mar  8 12:46:04 db0-test user.debug snapclient[8205]: Chunk: -1    -1      -1      -1      500     7       8
Mar  8 12:46:05 db0-test user.debug snapclient[8205]: Chunk: 2     -1      -1      -1      500     7       8
Mar  8 12:46:06 db0-test user.debug snapclient[8205]: Chunk: 0     -1      -1      -1      500     6       8
```

BTW, my alsa buffer is set to 10ms (period rate ratio of 5) without hiccups. "popcorn" noise still here even with more standard (like 40 or 100ms) buffer time and period rate ratio...

**Comment by chrusty0** [comment]
@badaix Attached file contains 45s of a 32kHz sinewave from WAV file source sent through snapserver and exported to a file using snapclient `--player file` option. So we can rule out an issue related to alsa or DAC.

[snapclient_s16-192khz_popcorn.zip](https://github.com/badaix/snapcast/files/6117933/snapclient_s16-192khz_popcorn.zip)

Hope that help :+1:

**Comment by chrusty0** [comment]
Disagree. It is exactly because of **one** duplicated sample that we have "popcorn" noise.

Take a look at the audio sample I put above. We can clearly see the same duplicate sample when it "pops", especially on a sine waveform.

**Comment by efung1232** [comment]
@badaix  I use Raspberry Pi 4B to run MPD and Snapcast client-server plus a I2S DAC sound card.  I think the problem is due to the upsampling of non-2x-4x-multiple by MPD. I guess if MPD and Snapserver are run in a mid-grade x86 processor, there won't be such problem. If I play the FLAC copies of my CD music with 4x upsampling (16bit/44.1k to 24bit/176.4k) by MPD in Raspberry Pi, there is no such problem. Upsampling from 16-bit/44.1k to 24-bit/192k will be done by floating point math instead of bit shifting and integer math. So, it will take more time.

**Comment by chrusty0** [comment]
@efung1232 Maybe our popcorn is different. Yours is sweet and mine is salty but it's still popcorn anyway... :-D

**Comment by badaix** [comment]
@chrusty0 if you can hear one removed sample, then Snapcast is not suited for you

**Comment by efung1232** [comment]
Just to share my experience in using Raspberry Pi for high-end audio application. There is power saving feature "CPU governor" which will automatically adjust the CPU clock depends on the work load. But, the normal clock speed will be set to 600MHz. I have experienced losing connection to the local 24-bit/176.4k music streaming from MPD when I use Snapweb to switch between Airplay stream (always 16-bit/44.k) and MPD stream. I have spent a couple days to try and think the possible cause of the problem. I finally made the try to change it to "performance" and the problem has disappeared.

**Comment by chrusty0** [comment]
@badaix I generated 1sec of 32kHz sinewave and duplicated manually **one** sample somewhere near 0,6s. Let's popin'...

[test.zip](https://github.com/badaix/snapcast/files/6118865/test.zip)

**Comment by badaix** [comment]
I think the `--player file` does not remove or add samples, because it doesn't sync with your DACs clock

**Comment by chrusty0** [comment]
From what i can see, file player sync with steady clock which is the same as CLOCK_MONOTONIC.

**Comment by chrusty0** [comment]
@badaix I think replacing remove/duplicate samples method at L203/L211 in stream.cpp by soxr variable resampling may be the easiest and mostly the best approach (since soxr lib is already used for `--sampleformat` option and consequently can combine two jobs) as the setRealSampleRate almost already compute resampling ratio ?

**Comment by badaix** [comment]
Insertion of a sample takes place when the stream deviates 0.1 ms, most of the time (on my 48kHz systems), there is a single sample inserted every 5 or ten seconds. Nothing you want (or can) achieve with resampling. Also resampling needs a certain buffer, 20ms as far as I remember.

**Comment by badaix** [comment]
@efung1232 good to hear that the problem is solved for you. Please close your tickets that have been solved.  
@chrusty0 you must be kidding me, your "let's popin'..." test signal is a purely synthetic binary `0 1 1 0 -1 -1 0 1 1 0 -1 -1` 192kHz signal.
![audacity](https://user-images.githubusercontent.com/10322999/117030880-5a359b80-ad00-11eb-9a17-25ed924c07c3.png)
It really feels stupid to waste time with such "issues"
