### ISSUE TITLE
trouble synchronizing 12 clients

### ISSUE THREAD

**Issue by smires-hamza** [badaix/snapcast#826]
Hello,

I want to thank you for this great SNAPCAST ​​project that you have developed.

Currently I have set up a snapServer v0.22.0 raspberry pi3 Model B with MPD wired in RJ45

And I have 12 Client SnapClient v0.22.0 under raspberry pi3 in WIFI

I'm having trouble synchronizing the 12 clients, I don't know if it's a WIFI problem? Do I have to wire all 12 clients?

The interest of the project is to create a communication system to send voice messages.

I would be extremely grateful if you could help me achieve this project

**Comment by badaix** [comment]
I don't know what you expect? You're writing that you have "trouble synchronizing your 12 clients" running some older Snapcast version and want the community to diagnose if you're having WiFi problems?
How about adding one by one and checking when your trouble begins. If it's your throughput, you could use a different codec, like ogg or opus.
