### ISSUE TITLE
Android client: ogg not supported

### ISSUE THREAD

**Issue by snake785** [badaix/snapcast#83]
I am using the latest Android client (v0.7.0) on a Blackberry Priv and Samsung Galaxy Note 8 and whenever I try to listen to a stream using ogg, I'm receiving the following message:

"Controller::onException: codec not supported: ogg"

I have also used a FLAC stream and it works just fine on both Android devices.

Will ogg become supported in a future version of the client?

**Comment by badaix** [comment]
Ogg will be supported in the next release (hope to release the v0.8 soon). It's already available in the Develop branch: f316a9f645e4217b305b526b3e652bfa6961bbb5

**Comment by badaix** [comment]
Released in v0.8.0
