### ISSUE TITLE
Installation on OpenRC system

### ISSUE THREAD

**Issue by PureTryOut** [badaix/snapcast#84]
Currently running `make install` (trying with the snapclient) fails on an OpenRC system like Gentoo Linux.

```
/bin/bash: systemctl: command not found
/sbin/init: invalid option -- '-'
cannot tell
```

I guess the Makefile does not account for OpenRC.

**Comment by badaix** [comment]
No, seems not to be compatible to OpenRC.
Can you support to adapt it?

**Comment by PureTryOut** [comment]
Support to adapt it? Sorry what do you mean?

**Comment by badaix** [comment]
I mean: add support for OpenRC. I don't have such a system available.

**Comment by thecb1** [comment]
I'm currently working on snapcast Gentoo ebuilds and wrote basic openrc init scripts.
Please see https://github.com/thecb1/cb1-overlay/tree/master/media-sound/snapcast/files

Openrc (at least on Gentoo) is sourcing /etc/conf.d/<service name>, so I moved the debian/snap*.default to /etc/conf.d/.

USER_OPTS and SNAP*_OPTS are working but START_SNAP* is boldly ignored ;-)
What's the purpose behind this? The Init is deciding whether to start the service.
