### ISSUE TITLE
(Avahi) Service name collision

### ISSUE THREAD

**Issue by MrTiptop** [badaix/snapcast#845]
Hello, I am running to Snapservers and for some reason the Avahi service is always naming the Service "Snapcast" in my snapserver config i have "source = librespot:///librespot?name=Outdoor" which works, i can see that when i start snapserver, it is starting librespot (this is should) but for some reason it is always using the name "Snapcast"

`snapser+  9890  5.1  0.7  50964  7268 ?        Ssl  09:57   0:00 /usr/bin/snapserver --logging.sink=system --server.datadir=/var/lib/snapserver
snapser+  9893  0.4  0.4  12588  4684 ?        Sl   09:57   0:00 /usr/bin/librespot --name **Snapcast** --bitrate 320 --backend pipe --initial-volume 100 --verbose`

What am i missing here?

I would like to make snapserver call librespot /usr/bin/librespot --name **foo**

**Environment details**
- OS: debian
- Snapcast version [e.g. 0.24.0]
- Installed from a package.

**Comment by MrTiptop** [comment]
I have done this already. my /etc/snapserver.conf looks like this
source = airplay:///shairport-sync?name=AirPlay[&devicename=foo][&port=5000]
ps aux looks like this.

snapser+ 10461  6.0  0.8  50964  8196 ?        Ssl  11:24   0:00 /usr/bin/snapserver --logging.sink=system --server.datadir=/var/lib/snapserver
snapser+ 10467  0.3  0.3  12588  3660 ?        Sl   11:24   0:00 /usr/bin/librespot --name Snapcast --bitrate 320 --backend pipe --initial-volume 100 --verbose

**Comment by kingosticks** [comment]
Setting devicename for your airplay source is separate to setting devicename for your librespot source.

```
source = librespot:///librespot?name=Outdoor&devicename=foo"
```

**Comment by badaix** [comment]
@MrTiptop please close your issues when they are solved
@kingosticks thanks for your support
