### ISSUE TITLE
[alsa stream] Detect idle state based on dBFS threshold

### ISSUE THREAD

**Issue by cmelbye** [badaix/snapcast#846]
**Is your feature request related to a problem? Please describe.**
I use an ADC (HifiBerry DAC+ ADC Pro) connected to a Turntable as input for the following ALSA stream:

```source = alsa://?name=Turntable&device=sysdefault&send_silence=true&sampleformat=48000:32:2&idle_threshold=10```

The problem I'm seeing is that Snapcast always reports its state as "playing", even if the Turntable is not playing anything. I assume this is because it constantly outputs some low-level noise.

I set `send_silence` and `idle_threshold` in an attempt to fix the issue, but it doesn't change anything. After looking at the source code, it seems like `idle_threshold` is expecting "true silence" from ALSA.

**Describe the solution you'd like**
It would be great if there were an alternate way to specify an idle threshold. I looked at the HifiBerry forums, and a thread seemed to suggest that using a dBFS threshold could work to detect "silent" noise.

I'm not experienced with this, so I could definitely be misunderstanding how this works. If it is possible, whether via that solution or something else, it would be a great improvement to get accurate state information from these types of ALSA sources.

For example, the snapclient web UI could accurately report whether or not the source is playing, or users could build automations that react to the stream moving from idle to playing.

**Comment by Thyself17** [comment]
I'd like to jump in and +1 this issue.  I have the non-pro Hifiberry DAC+ADC hat on a raspberry pi 3.  The alsa source always indicates that the stream is playing.  Using some sort of noise detection would be great for these devices.

**Comment by badaix** [comment]
@Thyself17 are you also talking about a line-in/mic-in analog stream?

**Comment by Thyself17** [comment]
> @Thyself17 are you also talking about a line-in/mic-in analog stream?

Correct! Just as @cmelbye has setup with their also source, I am using the line-in input on the Hifiberry ADC as the source for my snapserver instance. Even when there is no media playing, the alsa source in the web UI always shows the alsa stream is playing- never idle. I have also tried unplugging line-in, but snapserver still does not detect silence, and therefore, never idles.

As the OP states, I imagine there is still some inaudible noise passing through the ADC signal converter, so it never is 100% silent. Thus the proposal for some dB or volume threshold for detecting silence

**Comment by badaix** [comment]
Added with commit 216714b, you can find an automated build in [actions](https://github.com/badaix/snapcast/actions).
It introduces a new parameter `silence_threshold_percent` for the alsa stream source. It's not in dBFS, but in percent of the maximum amplitude. So for a line-in something like `0.1` should work.


> ### alsa
> 
> Captures audio from an alsa device
> 
> ```sh
> alsa://?name=<name>&device=<alsa device>[&send_silence=false][&idle_threshold=100][&silence_threshold_percent=0.0]
> ```
> 
> #### Available parameters
> 
> - `device`: alsa device name or identifier, e.g. `default` or `hw:0,0` or `hw:0,0,0`
> - `idle_threshold`: switch stream state from playing to idle after receiving `idle_threshold` milliseconds of silence
> - `silence_threshold_percent`: percent (float) of the max amplitude to be considered as silence 
> - `send_silence`: forward silence to clients when stream state is `idle`
>

**Comment by Thyself17** [comment]
@badaix I'll have to test in the next couple weeks when I get home from travel. I'll be sure to follow up with results!

This is an amazing feature for my use case. Thank you!

**Comment by Mohawi** [comment]
@cmelbye Thanks for the idea and @badaix Thanks for implementing it! 
I have it running for a few hours now and it works just great! I have three analog devices connected to my pi and am now able to see where a signal comes from! For my connected vinyl player I put a `silence_threshold_percent=0.2` to achieve a robust idle detection. With a value of 0.1 it oscillates a bit on status changes from playing to idle.

**Comment by badaix** [comment]
@Mohawi thanks for the feedback

**Comment by badaix** [comment]
Released in [Snapcast v0.25.0](https://github.com/badaix/snapcast/releases/tag/v0.25.0)

**Comment by Thyself17** [comment]
Chiming in to say this feature has worked flawlessly and has been an amazing feature for my usecase.  thanks!

**Comment by disi33** [comment]
OMG I have the exact same use case (HiFiBerry DAC+ ADC Pro - actually two of them, one for the turntable, another one for a long-distance Bluetooth receiver) and this has been bothering me for the longest time! Asked in the HiFiBerry forums for solutions etc.
I just had some time to kill and was gonna look at the code and see if there was a way I could contribute this feature, only to find that this has recently been added and it works flawlessly!
