### ISSUE TITLE
No output to PCM slave device

### ISSUE THREAD

**Issue by graybiggins** [badaix/snapcast#847]
I'm a long time user, first time problem.  My setup has 8 clients running on the same hardware as the server, which uses two 7.1 sound cards split into 8 stereo devices.  After updating my system to Ubuntu 20.04LTS and Snapcast to 0.24, it seems that my ability to output to a PCM slave device results in an error.  I can output to default ASLA devices fine and aplay can output to the slave devices ok too, but snapclients cannot output to the slave devices.  I have a couple other remote clients on v0.24 that use the ALSA defaults, and they continue to work fine.  I'm not an alsa expert, so not sure where the issue is, but this setup was running for about 2 years and now it's stopped after updating everything.

Copy of my alsainfo [here](https://pastebin.pl/view/b892c37c)

output of snapclient -l

> 0: surround21
> 
> 2.1 Surround output to Front and Subwoofer speakers
> 
> 1: surround40
> 4.0 Surround output to Front and Rear speakers
> 
> 2: surround41
> 4.1 Surround output to Front, Rear and Subwoofer speakers
> 
> 3: surround50
> 5.0 Surround output to Front, Center and Rear speakers
> 
> 4: surround51
> 5.1 Surround output to Front, Center, Rear and Subwoofer speakers
> 
> 5: surround71
> 7.1 Surround output to Front, Center, Side, Rear and Woofer speakers
> 
> 6: null
> Discard all samples (playback) or generate zero samples (capture)
> 
> 7: stereo1
> 
> 
> 8: stereo2
> 
> 
> 9: stereo3
> 
> 
> 10: stereo4
> 
> 
> 11: stereoA
> 
> 
> 12: stereoB
> 
> 
> 13: stereoC
> 
> 
> 14: stereoD
> 
> 
> 15: default:CARD=CMedia_1
> HDA C-Media, Generic Analog
> Default Audio Device
> 
> 16: sysdefault:CARD=CMedia_1
> HDA C-Media, Generic Analog
> Default Audio Device
> 
> 17: front:CARD=CMedia_1,DEV=0
> HDA C-Media, Generic Analog
> Front speakers
> 
> 18: surround21:CARD=CMedia_1,DEV=0
> HDA C-Media, Generic Analog
> 2.1 Surround output to Front and Subwoofer speakers
> 
> 19: surround40:CARD=CMedia_1,DEV=0
> HDA C-Media, Generic Analog
> 4.0 Surround output to Front and Rear speakers
> 
> 20: surround41:CARD=CMedia_1,DEV=0
> HDA C-Media, Generic Analog
> 4.1 Surround output to Front, Rear and Subwoofer speakers
> 
> 21: surround50:CARD=CMedia_1,DEV=0
> HDA C-Media, Generic Analog
> 5.0 Surround output to Front, Center and Rear speakers
> 
> 22: surround51:CARD=CMedia_1,DEV=0
> HDA C-Media, Generic Analog
> 5.1 Surround output to Front, Center, Rear and Subwoofer speakers
> 
> 23: surround71:CARD=CMedia_1,DEV=0
> HDA C-Media, Generic Analog
> 7.1 Surround output to Front, Center, Side, Rear and Woofer speakers
> 
> 24: iec958:CARD=CMedia_1,DEV=0
> HDA C-Media, Generic Digital
> IEC958 (S/PDIF) Digital Audio Output
> 
> 25: dmix:CARD=CMedia_1,DEV=0
> HDA C-Media, Generic Analog
> Direct sample mixing device
> 
> 26: dmix:CARD=CMedia_1,DEV=1
> HDA C-Media, Generic Digital
> Direct sample mixing device
> 
> 27: dsnoop:CARD=CMedia_1,DEV=0
> HDA C-Media, Generic Analog
> Direct sample snooping device
> 
> 28: dsnoop:CARD=CMedia_1,DEV=1
> HDA C-Media, Generic Digital
> Direct sample snooping device
> 
> 29: hw:CARD=CMedia_1,DEV=0
> HDA C-Media, Generic Analog
> Direct hardware device without any conversions
> 
> 30: hw:CARD=CMedia_1,DEV=1
> HDA C-Media, Generic Digital
> Direct hardware device without any conversions
> 
> 31: plughw:CARD=CMedia_1,DEV=0
> HDA C-Media, Generic Analog
> Hardware device with all software conversions
> 
> 32: plughw:CARD=CMedia_1,DEV=1
> HDA C-Media, Generic Digital
> Hardware device with all software conversions
> 
> 33: default:CARD=CMedia
> HDA C-Media, Generic Analog
> Default Audio Device
> 
> 34: sysdefault:CARD=CMedia
> HDA C-Media, Generic Analog
> Default Audio Device
> 
> 35: front:CARD=CMedia,DEV=0
> HDA C-Media, Generic Analog
> Front speakers
> 
> 36: surround21:CARD=CMedia,DEV=0
> HDA C-Media, Generic Analog
> 2.1 Surround output to Front and Subwoofer speakers
> 
> 37: surround40:CARD=CMedia,DEV=0
> HDA C-Media, Generic Analog
> 4.0 Surround output to Front and Rear speakers
> 
> 38: surround41:CARD=CMedia,DEV=0
> HDA C-Media, Generic Analog
> 4.1 Surround output to Front, Rear and Subwoofer speakers
> 
> 39: surround50:CARD=CMedia,DEV=0
> HDA C-Media, Generic Analog
> 5.0 Surround output to Front, Center and Rear speakers
> 
> 40: surround51:CARD=CMedia,DEV=0
> HDA C-Media, Generic Analog
> 5.1 Surround output to Front, Center, Rear and Subwoofer speakers
> 
> 41: surround71:CARD=CMedia,DEV=0
> HDA C-Media, Generic Analog
> 7.1 Surround output to Front, Center, Side, Rear and Woofer speakers
> 
> 42: iec958:CARD=CMedia,DEV=0
> HDA C-Media, Generic Digital
> IEC958 (S/PDIF) Digital Audio Output
> 
> 43: dmix:CARD=CMedia,DEV=0
> HDA C-Media, Generic Analog
> Direct sample mixing device
> 
> 44: dmix:CARD=CMedia,DEV=1
> HDA C-Media, Generic Digital
> Direct sample mixing device
> 
> 45: dsnoop:CARD=CMedia,DEV=0
> HDA C-Media, Generic Analog
> Direct sample snooping device
> 
> 46: dsnoop:CARD=CMedia,DEV=1
> HDA C-Media, Generic Digital
> Direct sample snooping device
> 
> 47: hw:CARD=CMedia,DEV=0
> HDA C-Media, Generic Analog
> Direct hardware device without any conversions
> 
> 48: hw:CARD=CMedia,DEV=1
> HDA C-Media, Generic Digital
> Direct hardware device without any conversions
> 
> 49: plughw:CARD=CMedia,DEV=0
> HDA C-Media, Generic Analog
> Hardware device with all software conversions
> 
> 50: plughw:CARD=CMedia,DEV=1
> HDA C-Media, Generic Digital
> Hardware device with all software conversions

output of snapclient -s 7 --logfilter *:trace

> 2021-04-02 13-12-49.521 [Info] (Snapclient) Version 0.24.0, revision 7eff45fd
> 2021-04-02 13-12-49.525 [Info] (Avahi) (Browser) NEW: service 'Snapcast' of type '_snapcast._tcp' in domain 'local'
> 2021-04-02 13-12-49.526 [Info] (Avahi) (Browser) NEW: service 'Snapcast' of type '_snapcast._tcp' in domain 'local'
> 2021-04-02 13-12-49.526 [Info] (Avahi) (Browser) NEW: service 'Snapcast' of type '_snapcast._tcp' in domain 'local'
> 2021-04-02 13-12-49.527 [Info] (Avahi) (Browser) NEW: service 'Snapcast' of type '_snapcast._tcp' in domain 'local'
> 2021-04-02 13-12-49.527 [Info] (Avahi) (Browser) NEW: service 'Snapcast' of type '_snapcast._tcp' in domain 'local'
> 2021-04-02 13-12-49.528 [Info] (Avahi) (Browser) CACHE_EXHAUSTED
> 2021-04-02 13-12-50.234 [Info] (Avahi) (Browser) NEW: service 'Snapcast' of type '_snapcast._tcp' in domain 'local'
> 2021-04-02 13-12-50.235 [Info] (Avahi) (Browser) NEW: service 'Snapcast' of type '_snapcast._tcp' in domain 'local'
> 2021-04-02 13-12-50.236 [Info] (Avahi) (Browser) NEW: service 'Snapcast' of type '_snapcast._tcp' in domain 'local'
> 2021-04-02 13-12-50.237 [Info] (Avahi) (Browser) NEW: service 'Snapcast' of type '_snapcast._tcp' in domain 'local'
> 2021-04-02 13-12-50.237 [Info] (Avahi) (Browser) NEW: service 'Snapcast' of type '_snapcast._tcp' in domain 'local'
> 2021-04-02 13-12-50.238 [Info] (Avahi) (Browser) CACHE_EXHAUSTED
> 2021-04-02 13-12-50.238 [Info] (Avahi) Service 'Snapcast' of type '_snapcast._tcp' in domain 'local':
> 2021-04-02 13-12-50.238 [Info] (Avahi) 	gray-server.local:1704 (172.19.0.1)
> 2021-04-02 13-12-50.238 [Debug] (Avahi) 	TXT=
> 2021-04-02 13-12-50.238 [Debug] (Avahi) 	Proto=0
> 2021-04-02 13-12-50.238 [Debug] (Avahi) 	cookie is 0
> 2021-04-02 13-12-50.238 [Debug] (Avahi) 	is_local: 1
> 2021-04-02 13-12-50.238 [Debug] (Avahi) 	our_own: 0
> 2021-04-02 13-12-50.239 [Debug] (Avahi) 	wide_area: 0
> 2021-04-02 13-12-50.239 [Debug] (Avahi) 	multicast: 1
> 2021-04-02 13-12-50.239 [Debug] (Avahi) 	cached: 1
> 2021-04-02 13-12-50.240 [Info] (Controller) Found server 172.19.0.1:1704
> 2021-04-02 13-12-50.240 [Info] (Connection) Resolving host IP for: 172.19.0.1
> 2021-04-02 13-12-50.240 [Info] (Connection) Connecting
> 2021-04-02 13-12-50.240 [Notice] (Connection) Connected to 172.19.0.1
> 2021-04-02 13-12-50.240 [Info] (Connection) My MAC: "30:85:a9:0f:ff:57", socket: 8
> 2021-04-02 13-12-50.327 [Debug] (Connection) outstanding async_write
> 2021-04-02 13-12-50.327 [Trace] (Connection) Wrote 237 bytes to socket
> 2021-04-02 13-12-50.327 [Trace] (Connection) Wrote 34 bytes to socket
> 2021-04-02 13-12-50.328 [Info] (Controller) ServerSettings - buffer: 900, latency: 0, volume: 11, muted: 0
> 2021-04-02 13-12-50.328 [Info] (Controller) Codec: flac, sampleformat: 48000:16:2
> 2021-04-02 13-12-50.328 [Info] (Player) Player name: alsa, device: stereo1, description: <none>, idx: 7, sharing mode: unspecified, parameters: <none>
> 2021-04-02 13-12-50.328 [Info] (Player) Mixer mode: software, parameters: <none>
> 2021-04-02 13-12-50.328 [Info] (Player) Sampleformat: 48000:16:2, stream: 48000:16:2
> 2021-04-02 13-12-50.328 [Info] (Alsa) Using default buffer_time: 80 ms, default fragments: 4
> 2021-04-02 13-12-50.330 [Debug] (Alsa) ACCESS:  MMAP_INTERLEAVED MMAP_NONINTERLEAVED MMAP_COMPLEX RW_INTERLEAVED RW_NONINTERLEAVED
> 2021-04-02 13-12-50.330 [Debug] (Alsa) FORMAT:  S8 U8 S16_LE S16_BE U16_LE U16_BE S24_LE S24_BE U24_LE U24_BE S32_LE S32_BE U32_LE U32_BE FLOAT_LE FLOAT_BE FLOAT64_LE FLOAT64_BE MU_LAW A_LAW IMA_ADPCM S20_LE S20_BE U20_LE U20_BE S24_3LE S24_3BE U24_3LE U24_3BE S20_3LE S20_3BE U20_3LE U20_3BE S18_3LE S18_3BE U18_3LE U18_3BE
> 2021-04-02 13-12-50.330 [Debug] (Alsa) SUBFORMAT:  STD
> 2021-04-02 13-12-50.330 [Debug] (Alsa) SAMPLE_BITS: [4 64]
> 2021-04-02 13-12-50.330 [Debug] (Alsa) FRAME_BITS: [4 640000]
> 2021-04-02 13-12-50.330 [Debug] (Alsa) CHANNELS: [1 10000]
> 2021-04-02 13-12-50.330 [Debug] (Alsa) RATE: [4000 4294967295)
> 2021-04-02 13-12-50.330 [Debug] (Alsa) PERIOD_TIME: (42666 42667)
> 2021-04-02 13-12-50.330 [Debug] (Alsa) PERIOD_SIZE: (170 183253370)
> 2021-04-02 13-12-50.330 [Debug] (Alsa) PERIOD_BYTES: (85 4294967295)
> 2021-04-02 13-12-50.330 [Debug] (Alsa) PERIODS: (0 2155906)
> 2021-04-02 13-12-50.330 [Debug] (Alsa) BUFFER_TIME: [1 4294967295]
> 2021-04-02 13-12-50.330 [Debug] (Alsa) BUFFER_SIZE: [341 366503875]
> 2021-04-02 13-12-50.330 [Debug] (Alsa) BUFFER_BYTES: [171 4294967295]
> 2021-04-02 13-12-50.330 [Debug] (Alsa) TICK_TIME: ALL
> 2021-04-02 13-12-50.330 [Info] (Alsa) Period time too small, changing from 20000 to 42666
> 2021-04-02 13-12-50.330 [Info] (Alsa) Buffer time smaller than 3 * periods: 80000 us < 127998 us, raising buffer time
> 2021-04-02 13-12-50.330 [Info] (Alsa) PCM name: stereo1, sample rate: 48000 Hz, channels: 2, buffer time: 85333 us, periods: 2, period time: 42666 us, period frames: 2048
> 2021-04-02 13-12-50.330 [Debug] (Player) setVolume exp with base 10: 0.11 => 0.0320277
> 2021-04-02 13-12-50.331 [Warn] (Alsa) snd_pcm_avail_delay failed: File descriptor in bad state (-77), avail: 0, delay: 0, using snd_pcm_avail amd snd_pcm_delay.
> 2021-04-02 13-12-50.331 [Trace] (Connection) Wrote 34 bytes to socket
> 2021-04-02 13-12-50.331 [Trace] (Connection) Wrote 34 bytes to socket
> 2021-04-02 13-12-50.332 [Debug] (Alsa) snd_pcm_avail failed: File descriptor in bad state (-77), using 2048
> 2021-04-02 13-12-50.332 [Debug] (Alsa) Resizing buffer from 0 to 8192
> 2021-04-02 13-12-50.332 [Info] (Stream) Wrote 34 bytes to socket

and it continues on, yet no sound output.

output of snapclient --logfilter *:debug

> 2021-04-02 13-26-28.529 [Info] (Snapclient) Version 0.24.0, revision 7eff45fd
> 2021-04-02 13-26-28.533 [Info] (Avahi) (Browser) NEW: service 'Snapcast' of type '_snapcast._tcp' in domain 'local'
> 2021-04-02 13-26-28.534 [Info] (Avahi) (Browser) NEW: service 'Snapcast' of type '_snapcast._tcp' in domain 'local'
> 2021-04-02 13-26-28.534 [Info] (Avahi) (Browser) NEW: service 'Snapcast' of type '_snapcast._tcp' in domain 'local'
> 2021-04-02 13-26-28.534 [Info] (Avahi) (Browser) NEW: service 'Snapcast' of type '_snapcast._tcp' in domain 'local'
> 2021-04-02 13-26-28.535 [Info] (Avahi) (Browser) NEW: service 'Snapcast' of type '_snapcast._tcp' in domain 'local'
> 2021-04-02 13-26-28.535 [Info] (Avahi) (Browser) CACHE_EXHAUSTED
> 2021-04-02 13-26-28.535 [Info] (Avahi) Service 'Snapcast' of type '_snapcast._tcp' in domain 'local':
> 2021-04-02 13-26-28.535 [Info] (Avahi) 	gray-server.local:1704 (172.19.0.1)
> 2021-04-02 13-26-28.535 [Debug] (Avahi) 	TXT=
> 2021-04-02 13-26-28.535 [Debug] (Avahi) 	Proto=0
> 2021-04-02 13-26-28.535 [Debug] (Avahi) 	cookie is 0
> 2021-04-02 13-26-28.535 [Debug] (Avahi) 	is_local: 1
> 2021-04-02 13-26-28.535 [Debug] (Avahi) 	our_own: 0
> 2021-04-02 13-26-28.535 [Debug] (Avahi) 	wide_area: 0
> 2021-04-02 13-26-28.535 [Debug] (Avahi) 	multicast: 1
> 2021-04-02 13-26-28.535 [Debug] (Avahi) 	cached: 1
> 2021-04-02 13-26-28.536 [Info] (Controller) Found server 172.19.0.1:1704
> 2021-04-02 13-26-28.536 [Info] (Connection) Resolving host IP for: 172.19.0.1
> 2021-04-02 13-26-28.536 [Info] (Connection) Connecting
> 2021-04-02 13-26-28.536 [Notice] (Connection) Connected to 172.19.0.1
> 2021-04-02 13-26-28.536 [Info] (Connection) My MAC: "30:85:a9:0f:ff:57", socket: 8
> 2021-04-02 13-26-28.612 [Debug] (Connection) outstanding async_write
> 2021-04-02 13-26-28.613 [Info] (Controller) ServerSettings - buffer: 900, latency: 0, volume: 11, muted: 0
> 2021-04-02 13-26-28.613 [Info] (Controller) Codec: flac, sampleformat: 48000:16:2
> 2021-04-02 13-26-28.613 [Info] (Player) Player name: alsa, device: default:CARD=CMedia_1, description: HDA C-Media, Generic Analog
> 2021-04-02 13-26-28.613 [Info] (Player) Default Audio Device, idx: 15, sharing mode: unspecified, parameters: <none>
> 2021-04-02 13-26-28.613 [Info] (Player) Mixer mode: software, parameters: <none>
> 2021-04-02 13-26-28.613 [Info] (Player) Sampleformat: 48000:16:2, stream: 48000:16:2
> 2021-04-02 13-26-28.613 [Info] (Alsa) Using default buffer_time: 80 ms, default fragments: 4
> 2021-04-02 13-26-28.706 [Debug] (Alsa) ACCESS:  MMAP_INTERLEAVED MMAP_NONINTERLEAVED MMAP_COMPLEX RW_INTERLEAVED RW_NONINTERLEAVED
> 2021-04-02 13-26-28.706 [Debug] (Alsa) FORMAT:  S8 U8 S16_LE S16_BE U16_LE U16_BE S24_LE S24_BE U24_LE U24_BE S32_LE S32_BE U32_LE U32_BE FLOAT_LE FLOAT_BE FLOAT64_LE FLOAT64_BE MU_LAW A_LAW IMA_ADPCM S20_LE S20_BE U20_LE U20_BE S24_3LE S24_3BE U24_3LE U24_3BE S20_3LE S20_3BE U20_3LE U20_3BE S18_3LE S18_3BE U18_3LE U18_3BE
> 2021-04-02 13-26-28.706 [Debug] (Alsa) SUBFORMAT:  STD
> 2021-04-02 13-26-28.706 [Debug] (Alsa) SAMPLE_BITS: [4 64]
> 2021-04-02 13-26-28.706 [Debug] (Alsa) FRAME_BITS: [4 640000]
> 2021-04-02 13-26-28.706 [Debug] (Alsa) CHANNELS: [1 10000]
> 2021-04-02 13-26-28.706 [Debug] (Alsa) RATE: [4000 4294967295)
> 2021-04-02 13-26-28.706 [Debug] (Alsa) PERIOD_TIME: (21333 21334)
> 2021-04-02 13-26-28.706 [Debug] (Alsa) PERIOD_SIZE: (85 91628833)
> 2021-04-02 13-26-28.706 [Debug] (Alsa) PERIOD_BYTES: (42 4294967295)
> 2021-04-02 13-26-28.706 [Debug] (Alsa) PERIODS: (0 8623621)
> 2021-04-02 13-26-28.706 [Debug] (Alsa) BUFFER_TIME: [1 4294967295]
> 2021-04-02 13-26-28.706 [Debug] (Alsa) BUFFER_SIZE: [170 733007751]
> 2021-04-02 13-26-28.706 [Debug] (Alsa) BUFFER_BYTES: [85 4294967295]
> 2021-04-02 13-26-28.706 [Debug] (Alsa) TICK_TIME: ALL
> 2021-04-02 13-26-28.706 [Info] (Alsa) Period time too small, changing from 20000 to 21333
> 2021-04-02 13-26-28.706 [Info] (Alsa) PCM name: default:CARD=CMedia_1, sample rate: 48000 Hz, channels: 2, buffer time: 85333 us, periods: 4, period time: 21333 us, period frames: 1024
> 2021-04-02 13-26-28.707 [Debug] (Player) setVolume exp with base 10: 0.11 => 0.0320277
> 2021-04-02 13-26-28.707 [Debug] (Alsa) Resizing buffer from 0 to 16384
> 2021-04-02 13-26-28.707 [Info] (Stream) No chunks available
> 2021-04-02 13-26-28.707 [Info] (Alsa) Failed to get chunk
> 2021-04-02 13-26-28.721 [Info] (Controller) diff to server [ms]: 0.003
> 2021-04-02 13-26-29.432 [Debug] (Stream) Silent frames: 114, frames: 1024, age: -2.393
> 2021-04-02 13-26-29.474 [Debug] (Stats) Chunk: 0	0	0	0	1	42	0
> 2021-04-02 13-26-30.008 [Debug] (Stats) Chunk: 0	0	0	0	16	42	0

which continues, and sound is output as expected.

I've tried increasing/decreasing buffers, latency, sample formats to no avail. Any ideas on what might be going on?  I apologize in advance if this a specific ALSA issue, but since aplay works and snapclient doesn't, that's what drove me to post the issue.

**Comment by badaix** [comment]
Can you try to use 
```c++
avail = snd_pcm_avail_update(handle_);
```
instead of 
```c++
avail = snd_pcm_avail(handle_);
```
in `alsa_player.cpp`, line 533?

**Comment by graybiggins** [comment]
Appears to change the error message to:

`[Error] (Alsa) ERROR. Can't write to PCM device: File descriptor in bad state`

[snapclient24_modified_not_working.txt](https://github.com/badaix/snapcast/files/6368826/snapclient24_modified_not_working.txt)

Default ALSA devices still work:

[snapclient24_modified_working.txt](https://github.com/badaix/snapcast/files/6368827/snapclient24_modified_working.txt)


In an effort to isolate the issue, I downgraded back to 0.19 and it's also having issues, leaving me to think something in ALSA has changed?

[snapclient19_not_working.txt](https://github.com/badaix/snapcast/files/6368825/snapclient19_not_working.txt)

**Comment by badaix** [comment]
maybe your problem is related to #815

**Comment by graybiggins** [comment]
I got v0.19 working again by adjusting the sound card buffer:

`sudo -i
echo 128 > /proc/asound/card0/pcm0p/sub0/prealloc
echo 128 > /proc/asound/card1/pcm0p/sub0/prealloc`

when I get some more time, I'll try going back to v0.24 and see if the problem persists.
