### ISSUE TITLE
Allow different delay to be specified for each snapclient

### ISSUE THREAD

**Issue by milestogo** [badaix/snapcast#85]
I'd like a command line option for snapclient that allows specifying a certain number of ms delay between this snapclient and the snapserver master. 
This will allow surround sound and using snapclient to fill in audio with multiple speakers (and snapclients) in one large room. 
Is this just a question of modifying  getDiffToServer(), or is there a better way to insert delay?

**Comment by 1337sup3rh4x0r** [comment]
via the Android APP you can set this delay for each client and it will be stored with the server even if the client goes offline.

**Comment by badaix** [comment]
it's also a command line option for the Snapclient `--latency`. Using this will be even more time consuming ;).
The latency is working inversly to the delay: It means "the device has a certain latency, so it must be played out earlier"
