### ISSUE TITLE
Make fatal error on MacOS FLAC/stream_decoder.h

### ISSUE THREAD

**Issue by steamfan** [badaix/snapcast#854]
**Describe the bug**
The make command fails with "fatal error: 'FLAC/stream_decoder.h' file not found"

**Steps to Reproduce**
Following command are executed in Terminal.app under Mac OS 10.15.7 (Catalina)
1. cd /Applications
2. mkdir Snapcast 
3. cd Snapcast
4. git clone https://github.com/badaix/snapcast.git
5. cd snapcast
6. cd client
7. make TARGET=MACOS

**Environment details**
- OS: Mac OS 10.15.7 (Catalina)
- Snapcast version [e.g. 0.21.0]
- Installed as written in https://github.com/badaix/snapcast/blob/master/doc/build.md#macos-native

**Attach logfile if applicable**
21:45:12 client > make TARGET=MACOS
g++ -O2  -std=c++14 -Wall -Wextra -Wpedantic -Wno-unused-function -DBOOST_ERROR_CODE_HEADER_ONLY -DHAS_FLAC -DHAS_OGG -DHAS_OPUS -DHAS_SOXR -DVERSION=\"0.24.0\" -I. -I.. -I../common -DMACOS -DHAS_COREAUDIO -DHAS_VORBIS -DFREEBSD -DMACOS -DHAS_BONJOUR -DHAS_DAEMON -I/usr/local/include -Wno-unused-local-typedef -Wno-deprecated -c snapclient.cpp -o snapclient.o
snapclient.cpp:122:9: warning: Warning: the macOS support is experimental and might not be maintained [-W#pragma-messages]
#pragma message "Warning: the macOS support is experimental and might not be maintained"
        ^
1 warning generated.
g++ -O2  -std=c++14 -Wall -Wextra -Wpedantic -Wno-unused-function -DBOOST_ERROR_CODE_HEADER_ONLY -DHAS_FLAC -DHAS_OGG -DHAS_OPUS -DHAS_SOXR -DVERSION=\"0.24.0\" -I. -I.. -I../common -DMACOS -DHAS_COREAUDIO -DHAS_VORBIS -DFREEBSD -DMACOS -DHAS_BONJOUR -DHAS_DAEMON -I/usr/local/include -Wno-unused-local-typedef -Wno-deprecated -c stream.cpp -o stream.o
g++ -O2  -std=c++14 -Wall -Wextra -Wpedantic -Wno-unused-function -DBOOST_ERROR_CODE_HEADER_ONLY -DHAS_FLAC -DHAS_OGG -DHAS_OPUS -DHAS_SOXR -DVERSION=\"0.24.0\" -I. -I.. -I../common -DMACOS -DHAS_COREAUDIO -DHAS_VORBIS -DFREEBSD -DMACOS -DHAS_BONJOUR -DHAS_DAEMON -I/usr/local/include -Wno-unused-local-typedef -Wno-deprecated -c client_connection.cpp -o client_connection.o
g++ -O2  -std=c++14 -Wall -Wextra -Wpedantic -Wno-unused-function -DBOOST_ERROR_CODE_HEADER_ONLY -DHAS_FLAC -DHAS_OGG -DHAS_OPUS -DHAS_SOXR -DVERSION=\"0.24.0\" -I. -I.. -I../common -DMACOS -DHAS_COREAUDIO -DHAS_VORBIS -DFREEBSD -DMACOS -DHAS_BONJOUR -DHAS_DAEMON -I/usr/local/include -Wno-unused-local-typedef -Wno-deprecated -c time_provider.cpp -o time_provider.o
g++ -O2  -std=c++14 -Wall -Wextra -Wpedantic -Wno-unused-function -DBOOST_ERROR_CODE_HEADER_ONLY -DHAS_FLAC -DHAS_OGG -DHAS_OPUS -DHAS_SOXR -DVERSION=\"0.24.0\" -I. -I.. -I../common -DMACOS -DHAS_COREAUDIO -DHAS_VORBIS -DFREEBSD -DMACOS -DHAS_BONJOUR -DHAS_DAEMON -I/usr/local/include -Wno-unused-local-typedef -Wno-deprecated -c player/player.cpp -o player/player.o
g++ -O2  -std=c++14 -Wall -Wextra -Wpedantic -Wno-unused-function -DBOOST_ERROR_CODE_HEADER_ONLY -DHAS_FLAC -DHAS_OGG -DHAS_OPUS -DHAS_SOXR -DVERSION=\"0.24.0\" -I. -I.. -I../common -DMACOS -DHAS_COREAUDIO -DHAS_VORBIS -DFREEBSD -DMACOS -DHAS_BONJOUR -DHAS_DAEMON -I/usr/local/include -Wno-unused-local-typedef -Wno-deprecated -c player/file_player.cpp -o player/file_player.o
g++ -O2  -std=c++14 -Wall -Wextra -Wpedantic -Wno-unused-function -DBOOST_ERROR_CODE_HEADER_ONLY -DHAS_FLAC -DHAS_OGG -DHAS_OPUS -DHAS_SOXR -DVERSION=\"0.24.0\" -I. -I.. -I../common -DMACOS -DHAS_COREAUDIO -DHAS_VORBIS -DFREEBSD -DMACOS -DHAS_BONJOUR -DHAS_DAEMON -I/usr/local/include -Wno-unused-local-typedef -Wno-deprecated -c decoder/pcm_decoder.cpp -o decoder/pcm_decoder.o
g++ -O2  -std=c++14 -Wall -Wextra -Wpedantic -Wno-unused-function -DBOOST_ERROR_CODE_HEADER_ONLY -DHAS_FLAC -DHAS_OGG -DHAS_OPUS -DHAS_SOXR -DVERSION=\"0.24.0\" -I. -I.. -I../common -DMACOS -DHAS_COREAUDIO -DHAS_VORBIS -DFREEBSD -DMACOS -DHAS_BONJOUR -DHAS_DAEMON -I/usr/local/include -Wno-unused-local-typedef -Wno-deprecated -c decoder/ogg_decoder.cpp -o decoder/ogg_decoder.o
g++ -O2  -std=c++14 -Wall -Wextra -Wpedantic -Wno-unused-function -DBOOST_ERROR_CODE_HEADER_ONLY -DHAS_FLAC -DHAS_OGG -DHAS_OPUS -DHAS_SOXR -DVERSION=\"0.24.0\" -I. -I.. -I../common -DMACOS -DHAS_COREAUDIO -DHAS_VORBIS -DFREEBSD -DMACOS -DHAS_BONJOUR -DHAS_DAEMON -I/usr/local/include -Wno-unused-local-typedef -Wno-deprecated -c decoder/flac_decoder.cpp -o decoder/flac_decoder.o
In file included from decoder/flac_decoder.cpp:19:
decoder/flac_decoder.hpp:24:10: fatal error: 'FLAC/stream_decoder.h' file not found
#include <FLAC/stream_decoder.h>

```log
# Replace this with your logs
```

**Comment by badaix** [comment]
You must install the flac lib

**Comment by steamfan** [comment]
Thanks for the reply. I used
`brew install flac`
and
`brew link --overwrite flac`
and afterwards I was able to 
`make TARGET=MACOS`
successfully

Question: why wasn't flac installed with the original command from the instruction?
`brew install flac libsoxr libvorbis boost opus`

**Comment by badaix** [comment]
Don't know, I don't have a Mac. If you can figure this out, please report back.

**Comment by steamfan** [comment]
I was able to instakk Snapcast on MacOS 10.15.7 (Catalina) with the following procedure:

Based on
(A) https://github.com/badaix/snapcast/blob/master/doc/build.md#macos-native
(B) https://github.com/badaix/snapcast/issues/720


Prerequisite
(a) git is installed

Chain of commands
(01) Installation will be done in `/Applications/snapcast`
(02) `cd /Applications`
(03) `git clone https://github.com/badaix/snapcast.git`
(04) `brew install flac libsoxr libvorbis boost opus`
(05) `brew install flac` I don't know why this is necessary, but it works...
(06) `brew link --overwrite flac`
# The client
(07) `cd /Applications/snapcast/client`
(08) `make TARGET=MACOS`
(09)  `sudo make install TARGET=MACOS `

# The server (including steps from (B))
(10) `cd /Applications/snapcast/server`
(11) `make TARGET=MACOS`
(12) Open /`Applications/snapcast/server/Makefile` end perform the follwing edits
     (a) Remove "-Dt" from the install commands in the MACOS target install script
     (b) Replace "/usr/share" with "/usr/local/share"
(13) `sudo mkdir /usr/local/share/snapserver /usr/local/share/snapserver/snapweb /usr/local/share/snapserver/snapweb/3rd-party`
(14) `sudo chown -R root:wheel /usr/local/share/snapserver`
(15) `sudo chmod -R 755 /usr/local/share/snapserver`
(16) `sudo make install TARGET=MACOS`
(17) Replace "doc_root = /usr/share/snapserver/snapweb" with "doc_root = /usr/local/share/snapserver/snapweb"

**Comment by steamfan** [comment]
Now snapcast is installed but fails to start. In `/var/log/system` the messages appear (hostname replaced by `<hostname>`):

`Apr 16 10:47:46 <hostname> com.apple.xpc.launchd[1] (com.apple.mdworker.shared.01000000-0400-0000-0000-000000000000[8743]): Service exited due to SIGKILL | sent by mds[209]`
`Apr 16 10:47:49 <hostname> com.apple.xpc.launchd[1] (de.badaix.snapcast.snapserver[8771]): Service could not initialize: 19H1026: xpcproxy + 14537 [839][1413921B-A069-3664-8FF4-045BAE04574F]: 0xd`
`Apr 16 10:47:49 <hostname> com.apple.xpc.launchd[1] (de.badaix.snapcast.snapserver[8771]): Service exited with abnormal code: 78`
`Apr 16 10:47:49 <hostname> com.apple.xpc.launchd[1] (de.badaix.snapcast.snapserver): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.`
`Apr 16 10:47:51 <hostname> com.apple.xpc.launchd[1] (org.macports.rsyncd[8760]): Service exited with abnormal code: 2`

**Comment by badaix** [comment]
please add server logs

**Comment by badaix** [comment]
No response, closing
