### ISSUE TITLE
Clients don't list streams other than default

### ISSUE THREAD

**Issue by luke-12** [badaix/snapcast#857]
**Describe the bug**

**Steps to Reproduce**
1.
2.
3.

**Environment details**
- OS: [e.g. Raspbian, debian, Windows]
- Snapcast version [e.g. 0.21.0]
- Installed from a package, self compiled, ...

**Attach logfile if applicable**
Generate logs with `snapclient --logfilter debug` or `snapserver --logging.filter debug` if possible and paste them in the following codeblock

```log
# Replace this with your logs
```

**Comment by badaix** [comment]
???

**Comment by luke-12** [comment]
Sorry to bother you, I should have deleted the unfinished issue report.
I've solved it in my own and it's nothing that would require a fix in
snapcast. Thank you for such awesome piece of software.

Dne st 21. 4. 2021 15:19 uživatel Johannes Pohl ***@***.***>
napsal:
