### ISSUE TITLE
Segfault on RPi 3B + Jessie 

### ISSUE THREAD

**Issue by lleevveell66** [badaix/snapcast#86]
- RPi 3B 
- Raspbian 8.0 (Debian Jesse)
- snapserver_0.7.0_armhf.deb
- snapclient_0.7.0_armhf.deb

root@hyperclock:/usr/local/src# uname -a
Linux hyperclock 4.4.11-v7+ #888 SMP Mon May 23 20:10:33 BST 2016 armv7l GNU/Linux

(gdb) run
Starting program: /usr/sbin/snapserver
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
Settings file: /root/.config/snapcast/server.json
2016-07-08 18-28-22 [out] Adding service 'Snapcast'
[New Thread 0x76bfb460 (LWP 32407)]

Program received signal SIGSEGV, Segmentation fault.
0x000331c8 in ?? ()
(gdb) bt
#0  0x000331c8 in ?? ()
#1  0x000331c4 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb)

**Comment by lleevveell66** [comment]
root@hyperclock:/usr/local/src# snapserver -d
Settings file: /root/.config/snapcast/server.json
root@hyperclock:/usr/local/src# ps ax|grep snap
 1799 pts/0    S+     0:00 grep snap
24423 ?        S<sl   1:21 /usr/sbin/snapclient -d
24825 ?        Ssl    3:27 /usr/sbin/snapserver -d
root@hyperclock:/usr/local/src#


hmph.  Something wrong with the /etc/default/snapserver file?

root@hyperclock:/usr/local/src# ls -al /etc/default/snapserver
-rw-r--r-- 1 root root 930 May  7 05:22 /etc/default/snapserver
root@hyperclock:/usr/local/src# cat /etc/default/snapserver
# defaults file for snapserver

# start snapserver automatically?
START_SNAPSERVER=true

# Allowed options:
#   -h, --help                          produce help message
#   -v, --version                       show version number
#   -p, --port arg (=1704)              server port
#   --controlPort arg (=1705)           Remote control port
#   -s, --sampleformat arg (=48000:16:2)
#                                       sample format
#   -c, --codec arg (=flac)             transport codec [flac|ogg|pcm][:options]
#                                       Type codec:? to get codec specific options
#   -f, --fifo arg (=/tmp/snapfifo)     name of the input fifo file
#   -d, --daemon [=arg(=0)]             daemonize
#                                       optional process priority [-20..19]
#   -b, --buffer arg (=1000)            buffer [ms]
#   --pipeReadBuffer arg (=20)          pipe read buffer [ms]

SNAPSERVER_OPTS="-d"

**Comment by badaix** [comment]
can you compile in debug mode and pull another stack trace?
In the server/Makefile, replace `-O3` with `-g` (line 12) and `STRIP = strip` with `STRIP = echo` (line 23).

**Comment by lleevveell66** [comment]
I installed from the Debian packages.  I can get the source and compile, though it will take some time for me to get to it.  I'll update this when I have something for you.

Sorry, also I think I missed a line on my copy-n-paste (or deleted it as I was trying to figure out the syntax to code block it)...  Using the -d option on the command line actually worked.  There was a process running.  It's only with no command line options that it segfaults.

**Comment by badaix** [comment]
I now tried to reproduce this on an RPI3. On my RPI it's working.

    root@raspberrypi:~# uname -a
    Linux raspberrypi 4.4.13-v7+ #894 SMP Mon Jun 13 13:13:27 BST 2016 armv7l GNU/Linux

````
(gdb) run
Starting program: /usr/sbin/snapserver 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
Settings file: /root/.config/snapcast/server.json
2016-07-30 12-54-41 [out] Adding service 'Snapcast'
[New Thread 0x76c11460 (LWP 2920)]
2016-07-30 12-54-41 [out] PcmStream sampleFormat: 48000:16:2
2016-07-30 12-54-41 [out] PipeStream mode: create
2016-07-30 12-54-41 [out] Stream: {"fragment":"","host":"","path":"/tmp/snapfifo","query":{"buffer_ms":"20","codec":"flac","mode":"","name":"default","sampleformat":"48000:16:2"},"raw":"pipe:///tmp/snapfifo?name=default","scheme":"pipe"}
[New Thread 0x762ff460 (LWP 2921)]
2016-07-30 12-54-41 [err] Exception: end of file
[New Thread 0x758ff460 (LWP 2922)]
2016-07-30 12-54-41 [err] Exception: end of file
2016-07-30 12-54-41 [out] Service name collision, renaming service to 'Snapcast #2'
2016-07-30 12-54-41 [out] Adding service 'Snapcast #2'
2016-07-30 12-54-41 [err] Exception: end of file
````

Maybe something is wrong with the settings file `/root/.config/snapcast/server.json`. Can you backup and delete the file? 
(e.g. `mv /root/.config/snapcast/server.json /root/.config/snapcast/server.json.backup`)

Also please make sure that your system is up to date (`apt-get update` and `apt-get upgrade`) and update to the latest snapclient and snapserver.
