### ISSUE TITLE
add native pulseaudio support

### ISSUE THREAD

**Issue by treaki** [badaix/snapcast#88]
hi,

after much trail and error i was now able to get snapcast up and running. Its totally grate, thanks a lot. Ive got a a raspi in my kitchen and in my room a computer running also debian. The problems are

that i prefer to use xmms2 instead of mpd and that on my computer is pulseaudio

xmms2 dosnt support pipe output [01] ;(, so i had to route it through pulseaudio (after jackd also wasnt able to write to pipes)

i used following command:

```pactl load-module module-pipe-sink file=/tmp/snapfifo```

and then i had to figure out the correct sample rate which doent seams to be configureable in pulse audio completely. 

default resulted in a pitched playback but time was sync (i guess) strange... I figgured out this option to sound good:

```/usr/sbin/snapserver --codec=flac --sampleformat=44400:16:2```

but as i run snapclient to hear also in the living room it used pulses alsa emulation.

So it would be perfect if first of all you could add support for pulse playback to snapclient so it hasnt to use this unstable alsa emulation and secundly it would also be grate to use pulse recording as input for snapserver.

thanks in advance and keep up the good work

annotations: 
01: https://bugs.xmms2.org/view.php?id=2599

**Comment by badaix** [comment]
It should be possible to use an ALSA plugin with XMMS.
ALSA can be [configured](https://github.com/badaix/snapcast/issues/45#issuecomment-202892367) to redirect the stream into a file (i.e. the `snapfifo`)

**Comment by treaki** [comment]
thanks for that hint, i was unable to do that because the interface of xmms lookes incomatible because it uses regular files not named pipes, so my pulse null sink setting is working for now, and i guess its more likely an problem with xmms2 but thanks for looking in to it
