### ISSUE TITLE
Ability to set individual device latency?

### ISSUE THREAD

**Issue by mxmilkiib** [badaix/snapcast#886]
**Is your feature request related to a problem? Please describe.**
Sometimes it would be preferable to have the ability to set a small time delay on a specific output device so as to balance the speed of sound in relation to the RL speaker position of that device vis-a-vis the sweet spot of (the majority of the) listeners.

**Describe the solution you'd like**
The advanced ability to set, if required, a manual additional millisecond latency, to any of the outputs, to counter the distance/speed of sound of those outputs as they might be physically located at a point where latency would be an issue.

The concrete problem is that our system has an HDMI soundbar that has digital latency above and beyond what might be expected from a basic networked audio system.

**Comment by kingosticks** [comment]
Like https://github.com/badaix/snapcast/blob/master/doc/json_rpc_api/v2_0_0.md#clientsetlatency ?

**Comment by mxmilkiib** [comment]
Aha, thanks! And I see now this can be set though the dots>Details for each channel.

**Comment by badaix** [comment]
yep, you can start the snapclient with `--latency X` or adjust the latency in Snapweb or Snapdroid (command line and GUI latencies are summed up)
