### ISSUE TITLE
Snapclient inherently inefficient when launched by launchctl macOS Big Sur

### ISSUE THREAD

**Issue by repercussion** [badaix/snapcast#887]
Everything is as it came out of the build from source. Snapclient is trying to start from launchctl. It runs as my user but never shows in any snapcast controller. 

Console output shows: 

```
Jun  3 20:45:23 localhost com.apple.xpc.launchd[1] (de.badaix.snapcast.snapclient): This service is defined to be constantly running and is inherently inefficient.
```

I am able to get the snapclient to show up, but only by running it manually and defining host. 

```
snapclient -h 192.168.1.249
```
Changing values in /Library/LaunchAgents/de.badaix.snapcast.snapclient.plist to include -h 192.168.1.249 shows that the process is running properly upon reboot, with the custom flags, but still will not show in list of clients. 

```
536 username     24   0 4181M  2808 ?  0.0  0.0  0:00.19 /usr/local/bin/snapclient --logsink=system -h 192.168.1.249
```

```
OS: macOS 11.2.3 20D91 x86_64
```

**Comment by repercussion** [comment]
Unfortunately the only thing in the logs is that which I've posted above. It appears but once on each boot, but the service is running in top.

```
Jun  4 12:57:59 localhost com.apple.xpc.launchd[1] (de.badaix.snapcast.snapclient): This service is defined to be constantly running and is inherently inefficient.
Jun  4 12:59:22 localhost com.apple.xpc.launchd[1] (de.badaix.snapcast.snapclient): This service is defined to be constantly running and is inherently inefficient.
```

**Comment by repercussion** [comment]
I will have a  simple script run upon login, rather than use launchctl.

Because I know you're not a macOS user, I was submitting more to report and hope other users had a solution sometime in the future for me. This is only my first week in Big Sur after hanging on to Mojave, so I'm not too familiar with it yet.

Regardless, always appreciate your input and the software you've made. Thank you very very much!

**Comment by badaix** [comment]
I would have guessed that there is something logged from Snapclient to the MacOs syslog equivalent, but maybe system logging is broken for Mac. You can temporarily change the `de.badaix.snapcast.snapclient.plist` file to include the command line arguments `--logsink=file:/path/to/file --logfilter=*:debug`. This should create a log file at debug level into `/path/to/file`.
The message `This service is defined to be constantly running and is inherently inefficient.` just seems to [mean]( https://superuser.com/questions/982160/why-is-diagnostics-agent-inherently-inefficient-and-what-to-do-about-it)
> The inefficiency refers to energy usage. Since it never shuts down and runs constantly, there is no efficiency by definition (theirs).
