### ISSUE TITLE
dont run as root by default init script

### ISSUE THREAD

**Issue by treaki** [badaix/snapcast#89]
hi,

`root      7675  1.5  0.0 546800  2752 ?        Ssl  13:02   0:00 /usr/sbin/snapserver -d`

why that. I found out that i could run snapserver and snapclient without root without problems. But the init script from the debian package are running it as root by default. I would say that this is a big security issue. You should create a special user for usage of snapserver ans also the fifo should be secured correctly (not world read/writable)

Please impfove this security issues.

While that is like it is i have disabled the usage of the init scripts and are running both mannually from my music user...

thanks

**Comment by pfink** [comment]
I think you'll normally use snapcast within a private (W)LAN and not over the internet, so the security issue is not _that_ big. You could also argue that sysv init scripts are not state of the art anyway.

But you are right that this would be an improvement.

**Comment by treakiandroid** [comment]
nothing, even not non at all network related software, should run as root. Its maybe a bit less possibil to be used if only listening in local network but who says in tees days that wouldnt be possible. Also snapserver exencively is listening to all interfaces and i dont see a check if the ip address is a public one...

i just checked but it lokes like snapserver by default (or as configured here) isnt listening to ipv6 addresses but promoting itself using ipv6 using avahi, i thought it would also listen as i remebered that it spammed avahi on anny (even my virtual and vpn) interfaces 

so much about security which dosent lookes like it has been taken under advisement at all...

From the philosophical point of view i am at the opinion that security should be taken that serious as in openBSD, i know that that pedantic acting will be quite inpracitcal if you want to get things done but the argument that it is not intended for internet use and thereby not needed to be secure at all is imho more then stupid...

regards

**Comment by badaix** [comment]
there is no special reason to run as root. I think this is the default behavior when a process is started by an init script without taking special care about the user.
I agree that it should be changed. Which user should run it? A special "snapcast" user? (similar to mpd)

From philosophical point of view everyone is invited to contribute to open source projects ;)

**Comment by treaki** [comment]
@badaix i start tings not from a init skript as root but through users crontab @reboot alias thing because i dont need to use any sudo/su for that to drop my my rights but it is done by the crond and logged also properly as in the /var/log/auth log file so i can see who (i try to run any deamon in its onwn user container like setting box for security reasen and nothing as root that that what i have to (still waiting for xservers that dont need root level rights because of thats quite insecure like you know webGL and all that unsure graphic card driver stuff) but oopsie i am making a leeway as it lokes like. 

yust wanted to state that everytime i reboot my system i have to run snapserver once for a sort time as root and then i can run it as a user but i cant run it without any su befor somehow. So what i have to do is

* failed to run snapserver as normal user
* sudo snapserver
* sudo killall -v snapserver
* ps aux | grep -i snap
* repeat until noone is running anymore while having a very bad fealing cause i dont know what it is doing that workes only as route
* run snapserver as normal user and now its magicaly somehow working til the next reboot of my system

so if you could tell me why that is hapening and what can i do to dont need sudo anymore at anytime with snapcast i would be very very glad

thanks in advance

**Comment by badaix** [comment]
I started working on that in the `develop` branch. It's has been possible all the time to run Snapserver and Snapclient as non-root user. 
For the init scripts Snapcast simply inherits the user from init process (i.e. root).
The upcoming version will create a `snapcast` user during `deb` installation as well as in `make install`. When running as a daemon (started by root), the forked daemon process will switch the user to `snapcast`.

**Comment by badaix** [comment]
fixed in [0.11.0](https://github.com/badaix/snapcast/releases/tag/v0.11.0-beta-1)
use `--user <user>[:<group>]` to run as a different user.
