### ISSUE TITLE
Can't configure multiple sources

### ISSUE THREAD

**Issue by olivier-rolland** [badaix/snapcast#892]
Hi,

I'm trying to configure snapserver to accept multiple sources without success with the following /etc/snapserver.conf:

```
[stream]
source = spotify:///usr/bin/librespot?name=Spotify&devicename=Multiroom&bitrate=320
source = pipe:///tmp/snapfifo?name=MPD&sampleformat=48000:16:2
```

Only the Spotify source is working.  The MPD source is silent. You will see in the log files that nothing happens client side when audio is played server side.

If I comment the Spotify source, the MPD source is working.

Any idea of the problem?

Thanks,

Olivier

[snapserver.log](https://github.com/badaix/snapcast/files/6724929/snapserver.log)
[snapclient.log](https://github.com/badaix/snapcast/files/6724930/snapclient.log)

**Comment by badaix** [comment]
Did you activate the MPD source in Snapweb/Snapdroid/...?
See also #883

You can also configure a "meta" source, that will mix several sources
https://github.com/badaix/snapcast/blob/master/doc/configuration.md#meta

**Comment by olivier-rolland** [comment]
I don't see the MPD source in snapweb when the 2 sources are configured in /etc/snapserver.conf. I can see the MPD source when the Spotify source is commented.

I didn't try the loopback device, yet. I'll do that asap.

Thanks

**Comment by badaix** [comment]
Did you click on the source? Upper left part of the group view

**Comment by olivier-rolland** [comment]
Yes. Here is what I have:

![2021-06-28 12_18_17-Snapweb](https://user-images.githubusercontent.com/54670122/123621120-2d3acc00-d80b-11eb-82f9-6a8cf56a35c5.png)

![2021-06-28 12_18_51-Snapweb](https://user-images.githubusercontent.com/54670122/123621159-375cca80-d80b-11eb-9350-7489c9eebac5.png)

Why do I have a 3rd Spotify? Why snapweb is considered as a snapclient?

BTW, same using alsa loopback.

**Comment by badaix** [comment]
Did you click on "Spotify: idle"?

**Comment by olivier-rolland** [comment]
I didn't know I could click on it ! Ok, now it works !

Thanks
