### ISSUE TITLE
No sound from PHP + Apache

### ISSUE THREAD

**Issue by nocelab** [badaix/snapcast#893]
I'm trying to play audio files from Php 7.3 in Apache in machine a running DietPi (Debian based).
The sample commads:

`mplayer http://wms-15.streamsrus.com:11630 -novideo -channels 2 -srate 48000 -af format=s16le -ao pcm:file=/tmp/snapfifo`

or

`mpv http://wms-15.streamsrus.com:11630 --audio-display=no --audio-channels=stereo --audio-samplerate=48000 --audio-format=s16 --ao=pcm:file=/tmp/snapfifo`

runs perfectly... but executing in php page into Snapserver with:

`exec('mplayer http://wms-15.streamsrus.com:11630 -novideo -channels 2 -srate 48000 -af format=s16le -ao pcm:file=/tmp/snapfifo')`

thread starts but no sound is sent to clients.
I have no errors... I suspect some permission for pipe /tmp/snapfifo (or limits for apache running www-data user)

**Comment by badaix** [comment]
Seems not to be an issue related to snapcast itself, maybe something for [discussion](https://github.com/badaix/snapcast/discussions)
