### ISSUE TITLE
Any chance for an Android client?

### ISSUE THREAD

**Issue by apirogov** [badaix/snapcast#9]
Thanks for creating this! One question though - are there plans to port the client to Android?

My setup is the following - I have an MPD server with speakers in one room and want ocassionally to stream into a different room using my phone via HTTP streaming of MPD, which of course is awful if you hear both sources. So I would like to have a snapcast client on my phone, or I would have to install an RPi in the second room permanently, which I do not want for multiple reasons.

**Comment by badaix** [comment]
Well, it's possilbe, but not yet on the roadmap.
Actually, it shouldn't be too big effort. Most parts of the client's code should compile out of the box with the Android NDK (actually I've done this for another project). The alsa player might be problematic and need to be replaced with OpenSL.
Also it would require some front end app to control the client (at least switch on and off).

**Comment by badaix** [comment]
Hi,
the [develop branch](https://github.com/badaix/snapcast/tree/develop) contains an Android port of the `snapclient` and an Android wrapper app.  
I've attached a 0.4.9 alpha version APK: [Snapcast-0_4_9_alpha.apk.zip](https://github.com/badaix/snapcast/files/77482/Snapcast-0_4_9_alpha.apk.zip). You can install it with `adb install -r Snapcast-0_4_9_alpha.apk`. Please note that this is still a "preview tech-demo".  
It's strongly recommended to use 48kHz sampling rate on the snapserver. My test devices (Galaxy S5 and Nexus 7 2013) were not able to properly keep the audio in sync and massively stuttered with display off when using 44.1kHz.  
The app requires Android 4.1 (SDK level 16).

**Comment by apirogov** [comment]
Awesome! Tried it right now, almost perfect :)
