### ISSUE TITLE
ArchLinux Install problem

### ISSUE THREAD

**Issue by ElliottDyson** [badaix/snapcast#901]
**Describe the bug**
Upon trying to install I get the following error...

**Steps to Reproduce**
1. Following instructions to install snapcast on archlinux distro.
2. Inputting the makepkg -si command is where the error occurs

**Environment details**
- OS: [Manjaro, Arch Linux, Linux]

**The error I get**
==> ERROR: Cannot find the fakeroot binary.

**Comment by badaix** [comment]
From the error message I would guess that installing fakeroot should fix the problem.

**Comment by ElliottDyson** [comment]
> From the error message I would guess that installing fakeroot should fix the problem.

Ah, that fixed the issue, thank you

**Comment by badaix** [comment]
Let me close it for you
