### ISSUE TITLE
double free or corruption on Snapclient

### ISSUE THREAD

**Issue by ckt1010** [badaix/snapcast#92]
Hi,
After I install snapclient v0.8 on my raspberry PI 3 and execute "sudo snapclient -l", it report "*** Error in `snapclient': double free or corruption (out): 0x008045a0 ***"
After analysis, I see it corruption in snd_device_name_hint which is in "vector<PcmDevice> AlsaPlayer::pcm_list(void)". And the wired thing is my anther pi can startup quite will.
Is there something wrong with my pi board configuration?
Thanks!

**Comment by badaix** [comment]
did you install the deb package or did you compile it yourself?

**Comment by badaix** [comment]
I couldn't reproduce it on a RPI 3. Do you have any external DAC connected? Is it the latest Debian Jessie with latest updates installed?

**Comment by ckt1010** [comment]
deb package or compile all have same problem. But unfortunately after I reinstall my RPI 3, the problem fixed. Maybe it is ALAS's problem.
