### ISSUE TITLE
Enable configuring the sample format for librespot streams

### ISSUE THREAD

**Issue by nkvoll** [badaix/snapcast#929]
`librespot` supports (among others) 24 bit sample format (through [command line options](https://github.com/librespot-org/librespot/wiki/Options)).

Currently `snapserver` has the sampleformat of `44100:16:2` hardcoded for `librespot` streams. This seems like a reasonable default because if a user changes the default `sampleformat = ` in the configuration file, it's all too easy to break the setup.

However, since `librespot` exposes it, it would be great if there existed a way to take advantage of the higher sample format.

**Comment by badaix** [comment]
@nkvoll please find my comments in the PR #930

**Comment by badaix** [comment]
no response => closed

**Comment by nkvoll** [comment]
+1 on closing for now and sorry for not being more on the ball on the PR responses and following up on them. I've a temporary pause on building the system on my end because I was virtualizing the servers with the snapclients and it became impossible for me to tell whether I had messed something up or the virtualization (and following lack of real time / low latency audio) was causing some random stuttering and buffering issues.

I hope to pick this up later on this year or early next, but I will have to rebuild my physical system on bare metal first, so I cannot promise when I will be able to find the time for it.
