### ISSUE TITLE
set Volume is fail on snapclient

### ISSUE THREAD

**Issue by maotouying** [badaix/snapcast#93]
I try to set volume on snapclient, but is fail.
I modfiy as follow(controller.cpp):
                double  d_volume =50.;
		player_->setVolume(d_volume / 100.);
		player_->setMute(serverSettings_->isMuted());
		player_->start();

After I modify as that,there is noise,the volume is not modify success,why is that?

**Comment by badaix** [comment]
This should work. Try `make clean` and `make`
Did it run before your modification?
Any special reason for doing this (hard coded volume)?

**Comment by badaix** [comment]
If you set a volume < 1 then you will run into the `adjustVolume` function.
Maybe you have to compile with big endian: `make ENDIAN=BIG`.
What CPU architecture are you running on?

````
	template <typename T>
	void adjustVolume(char *buffer, size_t count, double volume)
	{
		T* bufferT = (T*)buffer;
		for (size_t n=0; n<count; ++n)
			bufferT[n] = endian::swap<T>(endian::swap<T>(bufferT[n]) * volume);
	}
````

**Comment by maotouying** [comment]
My cpu is little endian,that play is ok before I modfiy,when I delete my modify that work is well.
My system is openwrt, there is also noise after I modify the volume.
log is:

adjustVolume ==0.377541
adjustVolume ==0.377541
adjustVolume ==0.377541
adjustVolume ==0.377541
adjustVolume ==0.377541
adjustVolume ==0.377541
adjustVolume ==0.377541
adjustVolume ==0.377541
adjustVolume ==0.377541

**Comment by maotouying** [comment]
When I set d_volume =100,that play is ok, but other value can't work.

adjustVolume ==1.000000
adjustVolume ==1.000000
adjustVolume ==1.000000
adjustVolume ==1.000000
adjustVolume ==1.000000
adjustVolume ==1.000000
adjustVolume ==1.000000
adjustVolume ==1.000000
adjustVolume ==1.000000
adjustVolume ==1.000000

**Comment by badaix** [comment]
did you follow the [official guide](https://github.com/badaix/snapcast/blob/master/doc/build.md#openwrt-cross-compile) for building Snapcast?
In version 0.7 OpenWRT builds were hard coded to use big endian. Since 0.8 the OpenWRT makefile will use big endian only for MIPS CPUs:
````
ENDIANNESS:=LITTLE
ifeq ($(ARCH),mips)
ENDIANNESS:=BIG
endif
````

Your problem must be somehow endian related. For volumes < 1 the endian is considered twice. This calculation must cause the problem:
`endian::swap<T>(endian::swap<T>(bufferT[n]) * volume);`

**Comment by maotouying** [comment]
Yes,when I use " # define SWAP_16(x) x ",the sound is well, but the volume is not modfiy, the volume  also is 100% when I set d_volume =20.
adjustVolume ==0.128851
adjustVolume ==0.128851
adjustVolume ==0.128851
adjustVolume ==0.128851
adjustVolume ==0.128851
adjustVolume ==0.128851

**Comment by badaix** [comment]
so it seems you're compiling with big endian for a small endian architecture?

did you follow the [official guide](https://github.com/badaix/snapcast/blob/master/doc/build.md#openwrt-cross-compile) for building Snapcast?

**Comment by maotouying** [comment]
Yes,I find the problem is endian , my ARCH is mips but is little endian ,when I modify endian  the volume modify is ok . thanks very much.
