### ISSUE TITLE
Snapserver won't start after upgrade

### ISSUE THREAD

**Issue by Drizzt321** [badaix/snapcast#934]
**Describe the bug**
Don't remember the version I was running before, but was from the Debian testing repository. Recently testing updated to a new codename, so did a full dist-upgrade. I now get an error that it can't open file `/var/lib/snapserver/server.json`.

As part of the upgrade, I kept my existing config, rather than having the package config overwrite it. Original install was, I think, 0.23 or 0.24. 

`/var/lib/snapserver` dir is 750, `/var/lib/snapserver/server.json` is 644. 

When I run it manually (e.g. `snapserver --logging.filter debug`) as root, it starts up and runs fine, and I can connect to it fine and everything. When I manually run it as the snapserver user `su -s /bin/bash snapserver -c /usr/bin/snapserver` it comes up and says `Settings file: "/var/lib/snapserver/.config/snapserver/server.json"` and works fine as well.

I've tried deleting everything from within the /var/lib/snapserver/ dir, but the `/var/lib/snapserver/server.json` file doesn't get recreated. 

It certainly appears to be more OS/permissions related, yet there was no issue before the upgrade after the first install/setup.

Here's the full log output from `journalctl -f -u snapserver`

```
Nov 04 11:00:33 snapcast-server snapserver[134090]: Version 0.25.0
Nov 04 11:00:33 snapcast-server snapserver[134090]: Adding source: airplay:///usr/bin/shairport-sync?name=Airplay1&devicename=Airplay1&port=5000
Nov 04 11:00:33 snapcast-server snapserver[134090]: Adding source: pipe:///tmp/snapfifo?name=mopidiy&codec=pcm
Nov 04 11:00:33 snapcast-server snapserver[134090]: Adding source: tcp://192.168.10.154:4953?name=TcpInput
Nov 04 11:00:33 snapcast-server snapserver[134090]: Settings file: "/var/lib/snapserver/server.json"
Nov 04 11:00:33 snapcast-server snapserver[134090]: Exception: failed to open file "/var/lib/snapserver/server.json", permission denied (error 13)
Nov 04 11:00:33 snapcast-server snapserver[134090]: Snapserver terminated.
```

Here's my `/etc/snapserver.conf` values

```
[server]

[http]
#enabled = true

[tcp]
#enabled = true

[stream]
source = airplay:///usr/bin/shairport-sync?name=Airplay1&devicename=Airplay1&port=5000
#source = airplay:///usr/bin/shairport-sync?name=Airplay2&devicename=Airplay2&port=5001
source = pipe:///tmp/snapfifo?name=mopidiy&codec=pcm

source = tcp://192.168.10.154:4953?name=TcpInput
```

systemd unit file
```
[Unit]
Description=Snapcast server
Documentation=man:snapserver(1)
Wants=avahi-daemon.service
After=network.target time-sync.target avahi-daemon.service

[Service]
EnvironmentFile=-/etc/default/snapserver
ExecStart=/usr/bin/snapserver --logging.sink=system --server.datadir="${HOME}" $SNAPSERVER_OPTS
User=_snapserver
Group=_snapserver
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

/etc/default/snapserver
```
/etc/default/snapserver
```

**Comment by badaix** [comment]
This might be an user/group issue: #643

**Comment by Drizzt321** [comment]
@badaix Hm... didn't seem to be, but I do see an underscore prefixed user/groups. 

And looking above at the unit file... somehow it's now using the underscore versions, rather than the original non-underscore. That's...annoying. 

I thought things looked fine, but my eyes/brain missed the underscore there in the unit file. *sigh*

```
# grep snapserver /etc/passwd
snapserver:x:107:112::/var/lib/snapserver:/usr/sbin/nologin
_snapserver:x:111:117::/var/lib/snapserver:/usr/sbin/nologin

# grep snapserver /etc/group
audio:x:29:drizzt,_snapclient,shairport-sync,snapserver
snapserver:x:112:
_snapserver:x:117:

# ls -lh /var/lib | grep snapserver
drwxr-x---  3 snapserver  snapserver  4.0K Nov  4 11:18 snapserver
```

**Comment by Drizzt321** [comment]
@badaix  Hm, that didn't work. I tried changing the unit file to not have the `_` in front, that didn't work. Also tried changing the /var/lib/snapserver to be `_snapserver:_snapserver` while changing the unit file back, that didn't work. Same issue.

**Comment by Drizzt321** [comment]
I solved it by removing/purging the package after copying the config file out, then putting the config file back, enabling and restarting.
