### ISSUE TITLE
Can't intergrate snapcast to HACS

### ISSUE THREAD

**Issue by RStaes** [badaix/snapcast#935]
**Describe the bug**
When a try to add with 'custom repositories' I get the message "Repostitory structure for v0.25.0 is not compliant" when a click the add button.

**Steps to Reproduce**
1. Go to HACS in Home Assistant
2. Go to 'Integrations'
3. Click on the 3 dots in the right upper corner of the screen and click on 'Custom repositories'
4. Add the URL 'https://github.com/badaix/snapcast'
5. Choose category 'Integration' and click on ADD
6. Now the error 'Repostitory structure for v0.25.0 is not compliant' pops up.

**Environment details**
## System Health

version | core-2021.11.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.75
arch | x86_64
timezone | Europe/Amsterdam

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4994
Installed Version | 1.16.0
Stage | running
Available Repositories | 889
Installed Repositories | 9

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.6
-- | --
update_channel | stable
supervisor_version | supervisor-2021.10.8
docker_version | 20.10.8
disk_total | 30.8 GB
disk_used | 6.2 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Z-Wave JS (0.1.45), File editor (5.3.3), AirCast (3.1.1), Terminal & SSH (9.2.1), Duck DNS (1.14.0), Dnsmasq (1.4.4), FTP (4.2.1), Mosquitto broker (6.0.1), UniFi Controller (1.0.0), NGINX Home Assistant SSL proxy (3.0.2), Node-RED (10.0.1), Samba share (9.5.1)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 2
views | 7
mode | storage

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>
**Attach logfile if applicable**
Generate logs with `snapclient --logfilter debug` or `snapserver --logging.filter debug` if possible and paste them in the following codeblock

```log
# Replace this with your logs
```

**Comment by badaix** [comment]
This is not a snapcast issue, please report this to home assistant
