### ISSUE TITLE
Some times packet will lost

### ISSUE THREAD

**Issue by ckt1010** [badaix/snapcast#95]
Hi,
I tested Snapcast on my three raspberry pi 3 board, use MPD pipe and FLAC to transform music stream. 
And also I configure bufferMS as 10s, and print time stamp when server send packet, and client play packet.
 Then I play 10 songs to see if music play is consistently. It is good at first, but after one or two songs, client some times will block, and print this log:
Aug 15 09:28:52 rasp_client1 snapclient[5134]: sleep < -bufferDuration/2: -806 < -15, sleep: -806
And from client log it shows time stamp is not consistently. So I suspect it is because of packet lost(my network condition is not quite well, bandwidth around 10Mbps). But from tcpdump, it shows server didn't sent those packet. 
Then I check server's log, it shows that server get packet from pipe then use messages_.push(message) to add packet to Queue, then use messages_.try_pop() to get out that packet, but packet is not appeared. Maybe, you can check my log from attachment:
syslog_s.txt
Aug 15 09:28:44 rasp_server snapserver[18847]: 1471253322 s 26899 us
Aug 15 09:28:44 rasp_server snapserver[18847]: 192.168.0.50
Aug 15 09:28:44 rasp_server snapserver[18847]: 1471253322 s 50899 us
Aug 15 09:28:44 rasp_server snapserver[18847]: 192.168.0.50
Aug 15 09:28:44 rasp_server snapserver[18847]: 1471253322 s 74899 us
Aug 15 09:28:44 rasp_server snapserver[18847]: 192.168.0.50
Aug 15 09:28:44 rasp_server snapserver[18847]: 1471253322 s 98899 us
Aug 15 09:28:44 rasp_server snapserver[18847]: 192.168.0.50
Aug 15 09:28:44 rasp_server snapserver[18847]: 1471253322 s 122899 us
Aug 15 09:28:44 rasp_server snapserver[18847]: 192.168.0.50
Aug 15 09:28:44 rasp_server snapserver[18847]: 1471253322 s 146899 us
Aug 15 09:28:44 rasp_server snapserver[18847]: 192.168.0.50
Aug 15 09:28:44 rasp_server snapserver[18847]: 1471253322 s 170899 us
Aug 15 09:28:44 rasp_server snapserver[18847]: 192.168.0.50
Aug 15 09:28:44 rasp_server snapserver[18847]: 1471253322 s 194899 us
Aug 15 09:28:44 rasp_server snapserver[18847]: 192.168.0.50
Aug 15 09:28:44 rasp_server snapserver[18847]: 1471253322 s 218899 us
Aug 15 09:28:44 rasp_server snapserver[18847]: 192.168.0.50
Aug 15 09:28:44 rasp_server snapserver[18847]: 1471253322 s 242899 us

syslog_c1.txt
Aug 15 09:28:52 rasp_client1 snapclient[5134]: Tim: ts sec:1471253322 us:2899
Aug 15 09:28:52 rasp_client1 snapclient[5134]: Tim: ts sec:1471253322 us:2899
Aug 15 09:28:52 rasp_client1 snapclient[5134]: Tim: ts sec:1471253322 us:26899
Aug 15 09:28:52 rasp_client1 snapclient[5134]: Tim: ts sec:1471253322 us:50899
Aug 15 09:28:52 rasp_client1 snapclient[5134]: Tim: ts sec:1471253322 us:74899
Aug 15 09:28:52 rasp_client1 snapclient[5134]: Tim: ts sec:1471253322 us:98899
Aug 15 09:28:52 rasp_client1 snapclient[5134]: Tim: ts sec:1471253322 us:146899
Aug 15 09:28:52 rasp_client1 snapclient[5134]: Tim: ts sec:1471253322 us:170899
Aug 15 09:28:52 rasp_client1 snapclient[5134]: Tim: ts sec:1471253322 us:194899
Aug 15 09:28:52 rasp_client1 snapclient[5134]: Tim: ts sec:1471253322 us:218899
Aug 15 09:28:52 rasp_client1 snapclient[5134]: Tim: ts sec:1471253322 us:242899
Aug 15 09:28:52 rasp_client1 snapclient[5134]: Tim: ts sec:1471253323 us:274899
Aug 15 09:28:52 rasp_client1 snapclient[5134]: sleep < -bufferDuration/2: -806 < -15, sleep: -806
Aug 15 09:28:52 rasp_client1 snapclient[5134]: Tim: ts sec:1471253323 us:274899
Aug 15 09:28:52 rasp_client1 snapclient[5134]: sleep < -bufferDuration/2: -806 < -15, sleep: -775
Aug 15 09:28:52 rasp_client1 snapclient[5134]: Tim: ts sec:1471253323 us:274899
Aug 15 09:28:52 rasp_client1 snapclient[5134]: sleep < -bufferDuration/2: -775 < -15, sleep: -745
Aug 15 09:28:52 rasp_client1 snapclient[5134]: Tim: ts sec:1471253323 us:274899
Aug 15 09:28:52 rasp_client1 snapclient[5134]: sleep < -bufferDuration/2: -745 < -15, sleep: -715
Aug 15 09:28:52 rasp_client1 snapclient[5134]: Tim: ts sec:1471253323 us:274899
Aug 15 09:28:52 rasp_client1 snapclient[5134]: sleep < -bufferDuration/2: -715 < -15, sleep: -684
Aug 15 09:28:52 rasp_client1 snapclient[5134]: Tim: ts sec:1471253323 us:274899
Aug 15 09:28:52 rasp_client1 snapclient[5134]: sleep < -bufferDuration/2: -684 < -15, sleep: -652
Aug 15 09:28:52 rasp_client1 snapclient[5134]: Tim: ts sec:1471253323 us:274899
Aug 15 09:28:52 rasp_client1 snapclient[5134]: sleep < -bufferDuration/2: -652 < -15, sleep: -622
Aug 15 09:28:52 rasp_client1 snapclient[5134]: Tim: ts sec:1471253323 us:274899
Aug 15 09:28:52 rasp_client1 snapclient[5134]: sleep < -bufferDuration/2: -622 < -15, sleep: -592
Aug 15 09:28:52 rasp_client1 snapclient[5134]: Tim: ts sec:1471253323 us:274899

Did I make some miss something? Thanks for your reply!
[2016_8_15_b.zip](https://github.com/badaix/snapcast/files/417975/2016_8_15_b.zip)

**Comment by badaix** [comment]
often a wrong input sample rate is the reason: Snapserver expects 48000:16:2. If you feed in a 44.1kHz signal into the pipe file, the server will read faster and the input buffer will be empty after short time.

**Comment by ckt1010** [comment]
Thanks badaix!
But I found it seems because of StreamSession::add funtion's "messages_.size()>100".
Because, tcp re-transform cost too much time, some this size is bigger than 100. 
Would you please me what is 100 mean? Why you choice 100?
Thanks!

**Comment by badaix** [comment]
It's simply to avoid that the server is running out of memory. 
The `StreamSession::writer()` will pop audio chunks out of the queue and send them to the client. If this thread would stuck (socket timeout or something. Shouldn't actually stuck forever), the queue would fill up. 
In theory, the writer thread should take care of this and delete all audio chunks that are older than the configured buffer duration (no chance to play them in time).
So this check `messages_.size() > 100` shouldn't be neccessary, since the thread will also drop too old messages.
I'm a little bit afraid of deleting this check anyways, but I will do something smarter here. For now you can simply delete this check and the following pop.

**Comment by ckt1010** [comment]
Actually I delete it and check again, some block tcp packet store in that chunks for a long time. It is because of my bandwith, but I think your check is useful, because it can pretent some useless memory wast(like my old packet).
