### ISSUE TITLE
The stream restarts from the beginning if you pause output from Mopidy

### ISSUE THREAD

**Issue by jameyg** [badaix/snapcast#96]
I setup Mopidy playing a local file to /tmp/snapfifo as per the readme.

It works beautifully, I tested it with two snapclients (one on Android, one on the same machine).

However, if I pause Mopidy then the snapclients seem to start from the beginning of the /tmp/snapfifo file.

To test this theory, I zero-d out /tmp/snapfifo after pausing and that served as a workaround.

Is snapcast designed to work like this or am I using it wrong? I would have thought pausing the stream should output silence on the clients but I'm no expert.

Thanks

**Comment by 1337sup3rh4x0r** [comment]
I had a similar problem when I started working with this.
This happens when the fifo is not created by the snapserver but by another program (MPD in your case). 
Delete the fifo, terminate MPD and Snapserver and then restart Snapserver, wait till it is loaded and then start MPD.

**Comment by jameyg** [comment]
@1337sup3rh4x0r Thanks so much, that was the reason! This was also helpful to note (from the fifo(7) manpage):

>  FIFO special files can be created by mkfifo(3), and are indicated by ls -l with the file type 'p'.

@badaix Could you incorporate this sage piece of advice into the README under the MPD/Mopidy sections?

**Comment by badaix** [comment]
Something like this?

[Mopidy](https://www.mopidy.com/) can stream the audio output into the Snapserver's fifo with a `filesink` as audio output in `mopidy.conf`:

    [audio]
    #output = autoaudiosink
    output = audioresample ! audioconvert ! audio/x-raw,rate=48000,channels=2,format=S16LE ! wavenc ! filesink location=/tmp/snapfifo

Please make sure that the `snapfifo` file is not created by Mopidy, as Mopidy will create a regular file `/tmp/snapfifo` instead of a fifo. This will cause Snapcast to play from the beginning if you pause Mopidy.
Solution is to create the fifo manually with `mkfifo /tmp/snapfifo` or to start the Snapserver before Mopdy is started.

**Comment by badaix** [comment]
it's added now to the Readme

**Comment by 1337sup3rh4x0r** [comment]
Yes, that is a good addition to the Readme!
However this problem is not exclusive to Mopidy. To me it happened with Spotify-Connect-Web and if I recall correctly, I think also MPD showed the same behaviour. So maybe this hint could be moved to a different section of the readme.

**Comment by Maxcodesthings** [comment]
This issue is still pertient as I use it to fix my fifo pipe but it is no longer in the Readme
