### ISSUE TITLE
Compilation of v0.26 fails on armv7h (Archlinux Raspberry Pi 2 1.1 32bit) : out-of-memory

### ISSUE THREAD

**Issue by m040601** [badaix/snapcast#963]
**Describe the bug**

Can't compile v0.26 on armv7h ((Archlinux Raspberry Pi 32bit).
It aborts with out-of-memory kernel messages, and other compiler stop error messages.

**Environment details**

- OS: Archlinux ARM
- RAM: 1 GB
- CPU: BCM2835 (4) @ 900MHz
- Linux ... 5.10.83-1-rpi-legacy-ARCH ... SMP Dec 7  2021 ... armv7l GNU/Linux
- Hardware: Raspberry PI 2 1.1 (32bit armv7h)
- cmake: 3.22.1-1
- gcc: 10.2.0-1
- boost-libs: 1.76.0
- boost: 1.76.0-2
- Previous Snapcast version  [0.25.0] working perfectly

**Background**

I've been running Archlinux (ARM) and compiling Snapcast on my 1GB memory humble little Raspberry Pi 2 1.1 (32 bit armv7h) for 2 years. Until version 0.26, I had no problems. It always took aaaaaaages to compile this C++ thingy, but in the end it bravely managed to do it. Running MPD and Snapcast with Opus encoding was also very smooth, and the CPU and RAM has always been more than enough.

**Steps to Reproduce**

The Snapcast Archlinux installation process:

Compilation is done following a PKGBUILD recipe, to compile an Archlinux package ready to be installed. Available from the Archlinux AUR repo, https://aur.archlinux.org/packages/snapcast 

Before submiting this issue, I checked with this PKGBUILD maintainers, to see if any recent change made to the PKGBUILD itself could be the root cause. The consensus was this is most probably an upstream issue.

With the latest Snapcast realesed source version 0.26 in December, I'm stuck. I can't finish compiling it, without running out of memory apparently. Tried already several times. It's the exact same system I've been running for 2 years. But somehow I cant get past 15% in the compilation process and makepkg aborts with:

```log
boost::asio::wait_traits<std::chrono::_V2::steady_clock> > >::heap_entry> > >’ changed in GCC 7.1
 1198 |    _M_realloc_insert(end(), __x);
      |    ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
{standard input}: Assembler messages:
{standard input}:178970: Error: invalid operands (*UND* and .ARM.extab sections) for `-'
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [server/CMakeFiles/snapserver.dir/build.make:118: server/CMakeFiles/snapserver.dir/control_session_http.cpp.o] Error 1
make[2]: Leaving directory '/home/r1/deleteme/snapcast/src/snapcast-0.26.0/build'
make[1]: *** [CMakeFiles/Makefile2:160: server/CMakeFiles/snapserver.dir/all] Error 2
make[1]: Leaving directory '/home/r1/deleteme/snapcast/src/snapcast-0.26.0/build'
make: *** [Makefile:136: all] Error 2
make: Leaving directory '/home/r1/deleteme/snapcast/src/snapcast-0.26.0/build'
==> ERROR: A failure occurred in build().
    Aborting...
```
Sometimes I get a kernel "oom kill" thingy. The system runs out of memory, and the kernel aborts the process and reboots.

alarmpi kernel:

```log
cc1plus invoked oom-killer: gfp_mask=0x100cca(GFP_HIGHUSER_MOVABLE), 
CPU: 1 PID: 16110 Comm: cc1plus Tainted: G         C        5.10.83-1-r>
kernel: Hardware name: BCM2835
[<8010efe8>] (unwind_backtrace) from [<8010ade0>] (show_stack+0x10/0x14
```
and

```log
oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allow>
Out of memory: Killed process 16110 (cc1plus) total-vm:876596kB, anon-r>
oom_reaper: reaped process 16110 (cc1plus), now anon-rss:0kB, file-rss:>
```

I have very little understanding of C++, compilation processes etc. But the first thing that occurred to me, is that, with version 0.26, maybe somehow the requirements of Snapcast have changed, are beefier now, and this hardware can't cope with it now ? This is strange, as it worked, and still works fine with version 0.25

In any case, during compilation, tried to shut down all the other non necessary services, to minimize RAM and CPU usage, and tried over and over to no avail.

Funny thing.
I also have another Archlinux ARM device. A Samsung Chromebook, with a slightly diferent older kernel version (5.10.16), but the exact same package versions and architecture (armv7h) . Snapcast 0.26 compiled without problems.

```log
- CPU: Samsung Exynos 1.700GHz
- RAM: 2GB
- Linux ... 5.10.16-1-ARCH ... SMP PREEMPT ...  Sat Feb 13 19:42:53 UTC 2021 armv7l GNU/Linux
```

**Comment by badaix** [comment]
You should compile with a single thread (i.e. `make -j 1`).
If you're already doing this or if it doesn't help, you must use a larger swap file or swap partition.
