### ISSUE TITLE
An ARM64 Debian / Ubuntu package would be nice

### ISSUE THREAD

**Issue by Thynix** [badaix/snapcast#964]
**Is your feature request related to a problem? Please describe.**
Ubuntu's current [recommended flavor](https://ubuntu.com/download/raspberry-pi) for Raspberry Pi is `arm64`, with which the `armhf` packages give:

```
ubuntu@ubuntu:~$ sudo dpkg -i snapclient_0.26.0-1_without-pulse_armhf.deb
dpkg: error processing archive snapclient_0.26.0-1_without-pulse_armhf.deb (--install):
 package architecture (armhf) does not match system (arm64)
Errors were encountered while processing:
 snapclient_0.26.0-1_without-pulse_armhf.deb
ubuntu@ubuntu:~$ sudo dpkg -i snapserver_0.26.0-1_armhf.deb
dpkg: error processing archive snapserver_0.26.0-1_armhf.deb (--install):
 package architecture (armhf) does not match system (arm64)
Errors were encountered while processing:
 snapserver_0.26.0-1_armhf.deb
ubuntu@ubuntu:~$
```

**Describe the solution you'd like**
An ARM64 `.deb` would be nice.

**Describe alternatives you've considered**
Building from source and building the package myself are both options. The latter is currently running.

**Additional context**

I'm on a Raspberry Pi 4 B with 1 GiB RAM. Building, at least the package, has required a swapfile.

```
ubuntu@ubuntu:~$ cat /etc/os-release
PRETTY_NAME="Ubuntu 21.10"
NAME="Ubuntu"
VERSION_ID="21.10"
VERSION="21.10 (Impish Indri)"
VERSION_CODENAME=impish
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=impish
ubuntu@ubuntu:~$ uname -a
Linux ubuntu 5.13.0-1011-raspi #13-Ubuntu SMP PREEMPT Fri Nov 19 18:40:23 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by badaix** [comment]
Hi,

same response as always: providing packages is not in the scope of this project. Snapcast v0.25.0 should be available for debian and thus for Ubuntu: https://repology.org/project/snapcast/versions

Also I've removed the debian package stuff from the project yesterday in the develop branch. Building packages is now done in the [Snapos](https://github.com/badaix/snapos) project as [GitHub action](https://github.com/badaix/snapos/actions).

The problem with ARM builds is that GitHub doesn't offer any ARM build machines, the ARM builds are done on my private self hosted RPi4, running some older Buster based 32 bit Raspbian. No chance to run a 64 bit docker container on this machine. It might be possible to run 64 bit arm containers on X64 using qemu, but I don't have time to dig into this. Any help on this would be appreciated. 

Have you tried `dpkg --add-architecture armhf`, as described [here](https://unix.stackexchange.com/questions/625576/how-to-run-32-bit-armhf-binaries-on-64-bit-arm64-debian-os-on-raspberry-pi)?

**Comment by Thynix** [comment]
Alright. I can certainly understand limiting project scope. Thanks for explaining.
