### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by nanderer** [badaix/snapcast#975]
Hi,

thanks a lot, that's relay easy to set up once you get the hang of that you have to use ipv4 and dont mdns addresses and that the debian package snapserver starts one as a deamon right with he install (why havent im seen a hint in the apt proccess window, was i blind or have you forgotten to put one in the install script, if so please do so) and starting one afterwards accessing the same fifo leads to disrupted playback.

But now i would like to ask for another ui improvements:

on android: please add dark mode

and the one i was going to ask for i guess i just found with snapweb

**Comment by badaix** [comment]
The Android client is a different project, hosted [here](https://github.com/badaix/snapdroid)
