### ISSUE TITLE
sub modules git address changed

### ISSUE THREAD

**Issue by m-soori** [badaix/snapcast#994]
**Describe the bug**
i used SNAPCAST v 0.15.0 fot openwrt but sub modules git address changed . and when i make it it get error
pls modify it 
to this below address 

[submodule "externals/flac"]
	path = externals/flac
	url = https://gitlab.xiph.org/xiph/flac.git 
[submodule "externals/ogg"]
	path = externals/ogg
	url = https://gitlab.xiph.org/xiph/ogg.git
[submodule "externals/tremor"]
	path = externals/tremor
	url = https://gitlab.xiph.org/xiph/tremor.git

**Environment details**
- OS: ubuntu 20
- Snapcast version 0.15.0
- self compiled, ...

**Comment by xabolcs** [comment]
Do you have to use such an old release?

**Comment by badaix** [comment]
Submodules have been removed beginning with v0.24: 4f0cfade5af455afc8c480eb9238fef658860f41. You should rather add these libs as dependency in you OpenWrt makefile, as done in [SnapOS](DEPENDS := +libstdcpp +libavahi-client +libatomic +libogg +libflac +libopus +boost)
